// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef GEORESOURCES_H
#define GEORESOURCES_H

@class PBCodable, PBDataReader, PBUnknownFields, NSString, NSMutableArray;
@protocol NSCopying;


#import "GEOVersionManifest.h"

@interface GEOResources : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    NSString *_abExperimentURL;
    NSString *_addressCorrectionInitURL;
    NSString *_addressCorrectionUpdateURL;
    NSMutableArray *_announcementsSupportedLanguages;
    NSString *_announcementsURL;
    NSMutableArray *_attributions;
    NSString *_authProxyURL;
    NSString *_authToken;
    NSString *_backgroundDispatcherURL;
    NSString *_backgroundRevGeoURL;
    NSString *_batchReverseGeocoderURL;
    NSString *_batchTrafficProbeURL;
    NSString *_bluePOIDispatcherURL;
    NSString *_businessPortalBaseURL;
    NSMutableArray *_dataSetURLOverrides;
    NSMutableArray *_dataSets;
    NSString *_directionsURL;
    NSString *_dispatcherURL;
    NSMutableArray *_displayStrings;
    NSString *_etaURL;
    NSMutableArray *_fontChecksums;
    NSMutableArray *_fonts;
    NSMutableArray *_iconChecksums;
    NSMutableArray *_icons;
    NSMutableArray *_locationShiftEnabledRegions;
    NSString *_logMessageUsageURL;
    NSString *_logMessageUsageV3URL;
    NSString *_muninBaseURL;
    NSMutableArray *_muninBuckets;
    NSMutableArray *_muninVersions;
    NSString *_polyLocationShiftURL;
    NSString *_proactiveRoutingURL;
    NSString *_problemCategoriesURL;
    NSString *_problemOptInURL;
    NSString *_problemStatusURL;
    NSString *_problemSubmissionURL;
    NSString *_realtimeTrafficProbeURL;
    NSMutableArray *_regionalResources;
    NSString *_releaseInfo;
    NSString *_resourcesURL;
    NSMutableArray *_resources;
    NSString *_reverseGeocoderVersionsURL;
    NSString *_searchAttributionManifestURL;
    NSString *_simpleETAURL;
    NSString *_spatialLookupURL;
    NSMutableArray *_styleSheetChecksums;
    NSMutableArray *_styleSheets;
    NSMutableArray *_textureChecksums;
    NSMutableArray *_textures;
    NSMutableArray *_tileGroups;
    NSMutableArray *_tileSets;
    NSMutableArray *_urlInfoSets;
    GEOVersionManifest *_versionManifest;
    NSString *_wifiConnectionQualityProbeURL;
    NSMutableArray *_xmlChecksums;
    NSMutableArray *_xmls;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _locationShiftVersion;
    ? _flags;
}


@property (retain, nonatomic) NSString *abExperimentURL;
@property (retain, nonatomic) NSString *addressCorrectionInitURL;
@property (retain, nonatomic) NSString *addressCorrectionUpdateURL;
@property (retain, nonatomic) NSMutableArray *announcementsSupportedLanguages;
@property (retain, nonatomic) NSString *announcementsURL;
@property (retain, nonatomic) NSMutableArray *attributions;
@property (retain, nonatomic) NSString *authProxyURL;
@property (retain, nonatomic) NSString *authToken;
@property (retain, nonatomic) NSString *backgroundDispatcherURL;
@property (retain, nonatomic) NSString *backgroundRevGeoURL;
@property (retain, nonatomic) NSString *batchReverseGeocoderURL;
@property (retain, nonatomic) NSString *batchTrafficProbeURL;
@property (retain, nonatomic) NSString *bluePOIDispatcherURL;
@property (retain, nonatomic) NSString *businessPortalBaseURL;
@property (retain, nonatomic) NSMutableArray *dataSetURLOverrides;
@property (retain, nonatomic) NSMutableArray *dataSets;
@property (retain, nonatomic) NSString *directionsURL;
@property (retain, nonatomic) NSString *dispatcherURL;
@property (retain, nonatomic) NSMutableArray *displayStrings;
@property (retain, nonatomic) NSString *etaURL;
@property (retain, nonatomic) NSMutableArray *fontChecksums;
@property (retain, nonatomic) NSMutableArray *fonts;
@property (readonly, nonatomic) BOOL hasAbExperimentURL;
@property (readonly, nonatomic) BOOL hasAddressCorrectionInitURL;
@property (readonly, nonatomic) BOOL hasAddressCorrectionUpdateURL;
@property (readonly, nonatomic) BOOL hasAnnouncementsURL;
@property (readonly, nonatomic) BOOL hasAuthProxyURL;
@property (readonly, nonatomic) BOOL hasAuthToken;
@property (readonly, nonatomic) BOOL hasBackgroundDispatcherURL;
@property (readonly, nonatomic) BOOL hasBackgroundRevGeoURL;
@property (readonly, nonatomic) BOOL hasBatchReverseGeocoderURL;
@property (readonly, nonatomic) BOOL hasBatchTrafficProbeURL;
@property (readonly, nonatomic) BOOL hasBluePOIDispatcherURL;
@property (readonly, nonatomic) BOOL hasBusinessPortalBaseURL;
@property (readonly, nonatomic) BOOL hasDirectionsURL;
@property (readonly, nonatomic) BOOL hasDispatcherURL;
@property (readonly, nonatomic) BOOL hasEtaURL;
@property (nonatomic) BOOL hasLocationShiftVersion;
@property (readonly, nonatomic) BOOL hasLogMessageUsageURL;
@property (readonly, nonatomic) BOOL hasLogMessageUsageV3URL;
@property (readonly, nonatomic) BOOL hasMuninBaseURL;
@property (readonly, nonatomic) BOOL hasPolyLocationShiftURL;
@property (readonly, nonatomic) BOOL hasProactiveRoutingURL;
@property (readonly, nonatomic) BOOL hasProblemCategoriesURL;
@property (readonly, nonatomic) BOOL hasProblemOptInURL;
@property (readonly, nonatomic) BOOL hasProblemStatusURL;
@property (readonly, nonatomic) BOOL hasProblemSubmissionURL;
@property (readonly, nonatomic) BOOL hasRealtimeTrafficProbeURL;
@property (readonly, nonatomic) BOOL hasReleaseInfo;
@property (readonly, nonatomic) BOOL hasResourcesURL;
@property (readonly, nonatomic) BOOL hasReverseGeocoderVersionsURL;
@property (readonly, nonatomic) BOOL hasSearchAttributionManifestURL;
@property (readonly, nonatomic) BOOL hasSimpleETAURL;
@property (readonly, nonatomic) BOOL hasSpatialLookupURL;
@property (readonly, nonatomic) BOOL hasVersionManifest;
@property (readonly, nonatomic) BOOL hasWifiConnectionQualityProbeURL;
@property (retain, nonatomic) NSMutableArray *iconChecksums;
@property (retain, nonatomic) NSMutableArray *icons;
@property (retain, nonatomic) NSMutableArray *locationShiftEnabledRegions;
@property (nonatomic) unsigned int locationShiftVersion;
@property (retain, nonatomic) NSString *logMessageUsageURL;
@property (retain, nonatomic) NSString *logMessageUsageV3URL;
@property (retain, nonatomic) NSString *muninBaseURL;
@property (retain, nonatomic) NSMutableArray *muninBuckets;
@property (retain, nonatomic) NSMutableArray *muninVersions;
@property (retain, nonatomic) NSString *polyLocationShiftURL;
@property (retain, nonatomic) NSString *proactiveRoutingURL;
@property (retain, nonatomic) NSString *problemCategoriesURL;
@property (retain, nonatomic) NSString *problemOptInURL;
@property (retain, nonatomic) NSString *problemStatusURL;
@property (retain, nonatomic) NSString *problemSubmissionURL;
@property (retain, nonatomic) NSString *realtimeTrafficProbeURL;
@property (retain, nonatomic) NSMutableArray *regionalResources;
@property (retain, nonatomic) NSString *releaseInfo;
@property (retain, nonatomic) NSMutableArray *resources;
@property (retain, nonatomic) NSString *resourcesURL;
@property (retain, nonatomic) NSString *reverseGeocoderVersionsURL;
@property (retain, nonatomic) NSString *searchAttributionManifestURL;
@property (retain, nonatomic) NSString *simpleETAURL;
@property (retain, nonatomic) NSString *spatialLookupURL;
@property (retain, nonatomic) NSMutableArray *styleSheetChecksums;
@property (retain, nonatomic) NSMutableArray *styleSheets;
@property (retain, nonatomic) NSMutableArray *textureChecksums;
@property (retain, nonatomic) NSMutableArray *textures;
@property (retain, nonatomic) NSMutableArray *tileGroups;
@property (retain, nonatomic) NSMutableArray *tileSets;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;
@property (retain, nonatomic) NSMutableArray *urlInfoSets;
@property (retain, nonatomic) GEOVersionManifest *versionManifest;
@property (retain, nonatomic) NSString *wifiConnectionQualityProbeURL;
@property (retain, nonatomic) NSMutableArray *xmlChecksums;
@property (retain, nonatomic) NSMutableArray *xmls;


+(BOOL)isValid:(id)arg0 ;
+(Class)attributionType;
+(Class)dataSetType;
+(Class)dataSetURLOverrideType;
+(Class)fontChecksumType;
+(Class)fontType;
+(Class)iconChecksumType;
+(Class)iconType;
+(Class)locationShiftEnabledRegionType;
+(Class)muninBucketType;
+(Class)muninVersionType;
+(Class)regionalResourceType;
+(Class)resourceType;
+(Class)styleSheetChecksumType;
+(Class)styleSheetType;
+(Class)textureChecksumType;
+(Class)textureType;
+(Class)tileGroupType;
+(Class)tileSetType;
+(Class)urlInfoSetType;
+(Class)xmlChecksumType;
+(Class)xmlType;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)isValid;
-(BOOL)readFrom:(id)arg0 ;
-(NSUInteger)hash;
-(id)announcementsSupportedLanguagesAtIndex:(NSUInteger)arg0 ;
-(id)attributionAtIndex:(NSUInteger)arg0 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)dataSetAtIndex:(NSUInteger)arg0 ;
-(id)dataSetURLOverrideAtIndex:(NSUInteger)arg0 ;
-(id)description;
-(id)dictionaryRepresentation;
-(id)displayStringsAtIndex:(NSUInteger)arg0 ;
-(id)fontAtIndex:(NSUInteger)arg0 ;
-(id)fontChecksumAtIndex:(NSUInteger)arg0 ;
-(id)iconAtIndex:(NSUInteger)arg0 ;
-(id)iconChecksumAtIndex:(NSUInteger)arg0 ;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)locationShiftEnabledRegionAtIndex:(NSUInteger)arg0 ;
-(id)muninBucketAtIndex:(NSUInteger)arg0 ;
-(id)muninVersionAtIndex:(NSUInteger)arg0 ;
-(id)preferedURLSetFor:(id)arg0 ;
-(id)preferredDataSetForClientDatasetMetadata:(id)arg0 ;
-(id)preferredDataSetForMapsABClient;
-(id)regionalResourceAtIndex:(NSUInteger)arg0 ;
-(id)resourceAtIndex:(NSUInteger)arg0 ;
-(id)styleSheetAtIndex:(NSUInteger)arg0 ;
-(id)styleSheetChecksumAtIndex:(NSUInteger)arg0 ;
-(id)textureAtIndex:(NSUInteger)arg0 ;
-(id)textureChecksumAtIndex:(NSUInteger)arg0 ;
-(id)tileGroupAtIndex:(NSUInteger)arg0 ;
-(id)tileSetAtIndex:(NSUInteger)arg0 ;
-(id)urlInfoSetAtIndex:(NSUInteger)arg0 ;
-(id)xmlAtIndex:(NSUInteger)arg0 ;
-(id)xmlChecksumAtIndex:(NSUInteger)arg0 ;
-(void)addAnnouncementsSupportedLanguages:(id)arg0 ;
-(void)addAttribution:(id)arg0 ;
-(void)addDataSet:(id)arg0 ;
-(void)addDataSetURLOverride:(id)arg0 ;
-(void)addDisplayStrings:(id)arg0 ;
-(void)addFont:(id)arg0 ;
-(void)addFontChecksum:(id)arg0 ;
-(void)addIcon:(id)arg0 ;
-(void)addIconChecksum:(id)arg0 ;
-(void)addLocationShiftEnabledRegion:(id)arg0 ;
-(void)addMuninBucket:(id)arg0 ;
-(void)addMuninVersion:(id)arg0 ;
-(void)addRegionalResource:(id)arg0 ;
-(void)addResource:(id)arg0 ;
-(void)addStyleSheet:(id)arg0 ;
-(void)addStyleSheetChecksum:(id)arg0 ;
-(void)addTexture:(id)arg0 ;
-(void)addTextureChecksum:(id)arg0 ;
-(void)addTileGroup:(id)arg0 ;
-(void)addTileSet:(id)arg0 ;
-(void)addUrlInfoSet:(id)arg0 ;
-(void)addXml:(id)arg0 ;
-(void)addXmlChecksum:(id)arg0 ;
-(void)clearAnnouncementsSupportedLanguages;
-(void)clearAttributions;
-(void)clearDataSetURLOverrides;
-(void)clearDataSets;
-(void)clearDisplayStrings;
-(void)clearFontChecksums;
-(void)clearFonts;
-(void)clearIconChecksums;
-(void)clearIcons;
-(void)clearLocationShiftEnabledRegions;
-(void)clearMuninBuckets;
-(void)clearMuninVersions;
-(void)clearRegionalResources;
-(void)clearResources;
-(void)clearStyleSheetChecksums;
-(void)clearStyleSheets;
-(void)clearTextureChecksums;
-(void)clearTextures;
-(void)clearTileGroups;
-(void)clearTileSets;
-(void)clearUnknownFields:(BOOL)arg0 ;
-(void)clearUrlInfoSets;
-(void)clearXmlChecksums;
-(void)clearXmls;
-(void)copyTo:(id)arg0 ;
-(void)mergeFrom:(id)arg0 ;
-(void)readAll:(BOOL)arg0 ;
-(void)writeTo:(id)arg0 ;


@end


#endif