

#include "WPHomeKit.h"
#include "WPAWDL.h"
#include "WPDataTransfer.h"
#include "WPRanging.h"
#include "WPZoneTrackingRequest.h"
#include "WPAdvertising.h"
#include "WPAdvertisingRequest.h"
#include "WPPairing.h"
#include "WPCharacteristic.h"
#include "WPAirPlaySolo.h"
#include "WPTest.h"
#include "WPDObjectDiscoveryData.h"
#include "WPContinuity.h"
#include "WPNearby.h"
#include "WPScanRequest.h"
#include "WPTransfer.h"
#include "WPPeerTrackingRequest.h"
#include "WPMagicSwitch.h"
#include "WPDeviceScanner.h"
#include "WPObjectDiscovery.h"
#include "WPClient.h"
#include "WPZoneTracker.h"
#include "WPHeySiri.h"
