// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef IMDSERVICESESSION_H
#define IMDSERVICESESSION_H

@class NSRecursiveLock, NSMutableDictionary, NSMutableSet, IMTimer, IMConnectionMonitor, NSTimer, NSString, IMSystemProxySettingsFetcher, IMOneTimeCodeUtilities, NSDictionary, NSArray;
@protocol IMSystemMonitorListener, IMConnectionMonitorDelegate, IMServiceSessionProtocol, IMDAutoReplying;

#import <Foundation/Foundation.h>

#import "IMDAccount.h"
#import "IMDChatRegistry.h"
#import "IMDService.h"

@interface IMDServiceSession : NSObject <IMSystemMonitorListener, IMConnectionMonitorDelegate, IMServiceSessionProtocol>

 {
    NSRecursiveLock *_lock;
    NSMutableDictionary *_localProperties;
    NSMutableSet *_changedBuddies;
    NSMutableDictionary *_groupChatIdentifierToChatRoomMap;
    NSMutableDictionary *_chatRoomToGroupChatIdentifierMap;
    IMTimer *_messageRoutingTimer;
    IMTimer *_messageExpireStateTimer;
    IMTimer *_messageWatchdogTimer;
    id<IMDAutoReplying> *_messageAutoReplier;
    IMConnectionMonitor *_connectionMonitor;
    NSTimer *_reconnectTimer;
    NSString *_loginID;
    NSString *_pwRequestID;
    IMSystemProxySettingsFetcher *_systemProxySettingsFetcher;
    int _buddyChangeLevel;
    BOOL _activated;
    BOOL _saveKeychainPassword;
    IMOneTimeCodeUtilities *_otcUtilities;
    BOOL _awaitingDataContext;
    BOOL _shouldReconnect;
    BOOL _badPass;
    NSMutableDictionary *_buddies;
}


@property (readonly, retain, nonatomic) IMDAccount *account; // ivar: _account
@property (readonly, retain, nonatomic) NSDictionary *accountDefaults;
@property (readonly, retain, nonatomic) NSString *accountID;
@property (readonly, nonatomic) BOOL accountNeedsLogin;
@property (readonly, nonatomic) BOOL accountNeedsPassword;
@property (readonly, nonatomic) BOOL accountShouldBeAlwaysLoggedIn;
@property (readonly, retain, nonatomic) NSArray *accounts; // ivar: _accounts
@property (readonly, retain, nonatomic) NSArray *allBuddies;
@property (readonly, nonatomic) BOOL allowedAsChild;
@property (readonly, retain, nonatomic) NSDictionary *buddyPictures;
@property (readonly, retain) NSDictionary *buddyProperties;
@property (retain, nonatomic) IMDChatRegistry *chatRegistry; // ivar: _chatRegistry
@property (readonly, retain, nonatomic) NSString *displayName;
@property (readonly, nonatomic) BOOL isActive;
@property (readonly, nonatomic) BOOL networkConditionsAllowLogin;
@property (readonly, nonatomic) BOOL overrideNetworkAvailability;
@property (readonly, retain, nonatomic) NSString *password; // ivar: _password
@property (readonly, retain, nonatomic) NSString *proxyAccount; // ivar: _proxyAccount
@property (readonly, retain, nonatomic) NSString *proxyHost; // ivar: _proxyHost
@property (readonly, retain, nonatomic) NSString *proxyPassword; // ivar: _proxyPassword
@property (readonly, nonatomic) unsigned short proxyPort; // ivar: _proxyPort
@property (readonly, nonatomic) NSInteger proxyType; // ivar: _proxyType
@property (readonly, retain, nonatomic) NSDictionary *registrationAlertInfo;
@property (readonly, nonatomic) int registrationError;
@property (readonly, nonatomic) int registrationStatus;
@property (readonly, retain, nonatomic) NSString *serverHost; // ivar: _serverHost
@property (readonly, nonatomic) unsigned short serverPort; // ivar: _serverPort
@property (readonly, retain, nonatomic) IMDService *service; // ivar: _service
@property (readonly, nonatomic) BOOL useSSL; // ivar: _useSSL


+(id)__allServiceSessionsWeakReferenceArray;
+(id)_firewallUserNotificationForService:(id)arg0 ;
+(id)allServiceSessions;
+(id)existingServiceSessionForService:(id)arg0 ;
+(void)__registerNewServiceSession:(id)arg0 ;
+(void)initialize;
-(BOOL)_didReceiveMessageDeliveryReceiptForMessageID:(id)arg0 attempts:(NSInteger)arg1 date:(id)arg2 account:(id)arg3 ;
-(BOOL)_isActivated;
-(BOOL)_isMessageSWYSpamMessage:(id)arg0 inChat:(id)arg1 ;
-(BOOL)_shouldBlackholeGroupChatFromSender:(id)arg0 toRecipient:(id)arg1 withOtherParticipants:(id)arg2 forAccount:(id)arg3 ;
-(BOOL)_shouldDropSendingMessage;
-(BOOL)_shouldShowSWYQuickActionForMessage:(id)arg0 outAppName:(*id)arg1 outBundleID:(*id)arg2 ;
-(BOOL)_storeMessage:(id)arg0 chatIdentifier:(id)arg1 localChat:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 messagesToPostArray:(id)arg5 ;
-(BOOL)blockIdleStatus;
-(BOOL)canMakeExpireStateChecks;
-(BOOL)didReceiveMessageDeliveryReceiptForMessageID:(id)arg0 date:(id)arg1 ;
-(BOOL)didReceiveMessageDeliveryReceiptForMessageID:(id)arg0 date:(id)arg1 account:(id)arg2 ;
-(BOOL)didReceiveMessages:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 fromIDSID:(id)arg4 ;
-(BOOL)equalID:(id)arg0 andID:(id)arg1 ;
-(BOOL)hasCapability:(NSUInteger)arg0 ;
-(BOOL)isAwaitingStorageTimer;
-(BOOL)reflectMarkUnreadToPeerDevicesForMessageGUID:(id)arg0 ;
-(BOOL)reflectRecoverChatToPeerDevicesForMessageGUID:(id)arg0 ;
-(BOOL)sendNicknameUpdatesToPeerDevices:(id)arg0 toDestinations:(id)arg1 ;
-(BOOL)shouldImitateGroupChatUsingChatRooms;
-(BOOL)shouldInferRecoverableDeleteForCommandDictionary:(id)arg0 ;
-(BOOL)testOverrideTextValidationDidFail;
-(BOOL)warnIfPortBlocked:(int)arg0 forAction:(id)arg1 ;
-(Class)spotlightItemRecorderClass;
-(NSUInteger)capabilities;
-(NSUInteger)pendingReadReceiptFromStorageCount;
-(id)_IDSService;
-(id)_autoReplier;
-(id)_determineResultMessageForInput:(id)arg0 output:(id)arg1 original:(id)arg2 ;
-(id)_fetchMessagesFromChat:(id)arg0 onService:(id)arg1 numberOfMessages:(NSUInteger)arg2 ;
-(id)_newHashForChat:(id)arg0 style:(unsigned char)arg1 ;
-(id)_predominantServiceForChat:(id)arg0 usingMessageThreshold:(NSUInteger)arg1 ;
-(id)_sharedAccountController;
-(id)_sharedMessageStore;
-(id)_transcodeController;
-(id)allowList;
-(id)blockList;
-(id)broadcaster;
-(id)broadcasterForACConferenceListeners;
-(id)broadcasterForAVConferenceListeners;
-(id)broadcasterForChatListeners;
-(id)broadcasterForChatListenersWithBlackholeStatus:(BOOL)arg0 ;
-(id)broadcasterForChatObserverListeners;
-(id)broadcasterForNotificationsListeners;
-(id)broadcasterForVCConferenceListeners;
-(id)canonicalFormOfChatRoom:(id)arg0 ;
-(id)canonicalFormOfID:(id)arg0 ;
-(id)canonicalFormOfID:(id)arg0 withIDSensitivity:(int)arg1 ;
-(id)chatForChatIdentifier:(id)arg0 style:(unsigned char)arg1 ;
-(id)chatForChatIdentifier:(id)arg0 style:(unsigned char)arg1 account:(id)arg2 ;
-(id)chatForItemWithGUID:(id)arg0 ;
-(id)chatRoomForGroupChatIdentifier:(id)arg0 ;
-(id)defaultChatSuffix;
-(id)deleteCommandDictionaryWithIncomingDictionary:(id)arg0 inferredRecoverableDeleteForLegacyCommandsWithDate:(id)arg1 ;
-(id)existingChatsForGroupID:(id)arg0 ;
-(id)existingChatsForIDs:(id)arg0 style:(unsigned char)arg1 ;
-(id)groupChatIdentifierForChatRoom:(id)arg0 ;
-(id)groups;
-(id)initWithAccount:(id)arg0 service:(id)arg1 ;
-(id)itemWithGUID:(id)arg0 ;
-(id)localPropertiesOfBuddy:(id)arg0 ;
-(id)localProperty:(id)arg0 ofBuddy:(id)arg1 ;
-(id)loginID;
-(id)loginIDForAccount:(id)arg0 ;
-(id)otcUtilities;
-(id)pictureKeyForBuddy:(id)arg0 ;
-(id)pictureOfBuddy:(id)arg0 ;
-(id)property:(id)arg0 ofBuddy:(id)arg1 ;
-(id)server;
-(id)storageController;
-(struct _FZChatRoomValidity )validityOfChatRoomName:(id)arg0 ;
-(unsigned int)blockingMode;
// -(void)_IMDStoreMessage:(id)arg0 inMessage:(id)arg1 forceReplace:(BOOL)arg2 modifyError:(BOOL)arg3 modifyFlags:(BOOL)arg4 calculateUnreadCount:(BOOL)arg5 flagMask:(NSUInteger)arg6 shouldStoreBlock:(id)arg7 didStoreBlock:(unk)arg8 block:(id)arg9  ;
-(void)__forceSetLoginStatus:(unsigned int)arg0 oldStatus:(unsigned int)arg1 message:(id)arg2 reason:(int)arg3 properties:(id)arg4 account:(id)arg5 ;
-(void)_abandonPWFetcher;
-(void)_abandonSystemProxySettingsFetcher;
-(void)_autoReconnectTimer:(id)arg0 ;
-(void)_blastDoorProcessingWithIMMessageItem:(id)arg0 chat:(id)arg1 account:(id)arg2 fromToken:(id)arg3 fromIDSID:(id)arg4 fromIdentifier:(id)arg5 toIdentifier:(id)arg6 participants:(id)arg7 groupName:(id)arg8 groupID:(id)arg9 isEncrypted:(BOOL)arg10 isFromMe:(BOOL)arg11 isLastFromStorage:(BOOL)arg12 isFromStorage:(BOOL)arg13 hideLockScreenNotification:(BOOL)arg14 wantsCheckpointing:(BOOL)arg15 needsDeliveryReceipt:(id)arg16 messageBalloonPayloadAttachmentDictionary:(id)arg17 inlineAttachments:(id)arg18 attributionInfoArray:(id)arg19 nicknameDictionary:(id)arg20 availabilityVerificationRecipientChannelIDPrefix:(id)arg21 availabilityVerificationRecipientEncryptionValidationToken:(id)arg22 messageContext:(id)arg23 completionBlock:(id)arg24 ;
-(void)_blocklistIfNeededForChatDict:(id)arg0 ;
-(void)_callMonitorStateChanged:(id)arg0 ;
-(void)_checkMessageForENURL:(id)arg0 ;
-(void)_checkMessageForOneTimeCodes:(id)arg0 ;
-(void)_clearAutoReconnectTimer;
-(void)_clearConnectionMonitor;
-(void)_clearDowngradeMarkersForChat:(id)arg0 ;
-(void)_configureAccountInformationOnItem:(id)arg0 withAccount:(id)arg1 ;
-(void)_configureIdentifierForOutgoingItem:(id)arg0 withIdentifier:(id)arg1 withStyle:(unsigned char)arg2 ;
-(void)_configureSessionInformationOnItem:(id)arg0 toChat:(id)arg1 withStyle:(unsigned char)arg2 forAccount:(id)arg3 ;
-(void)_configureSyndicationRangesForMessage:(id)arg0 forChat:(id)arg1 withSyndicationStatus:(NSInteger)arg2 ;
-(void)_configureTimeOnOutgoingItem:(id)arg0 ;
-(void)_data_connection_readyWithAccount:(id)arg0 ;
-(void)_didReceiveMessagePlayedForMessageID:(id)arg0 date:(id)arg1 attempts:(NSInteger)arg2 completionBlock:(id)arg3 ;
-(void)_didReceiveMessagePlayedReceiptForMessageID:(id)arg0 date:(id)arg1 attempts:(NSInteger)arg2 completionBlock:(id)arg3 ;
-(void)_didReceiveMessageReadForMessageID:(id)arg0 date:(id)arg1 attempts:(NSInteger)arg2 completionBlock:(id)arg3 ;
-(void)_didReceiveMessageReadReceiptForMessageID:(id)arg0 date:(id)arg1 attempts:(NSInteger)arg2 completionBlock:(id)arg3 ;
-(void)_didReceiveMessageSavedForMessageID:(id)arg0 ofType:(NSInteger)arg1 forChat:(id)arg2 fromHandle:(id)arg3 fromMe:(BOOL)arg4 date:(id)arg5 attempts:(NSInteger)arg6 account:(id)arg7 completionBlock:(id)arg8 ;
-(void)_doLoginIgnoringProxy:(BOOL)arg0 ;
-(void)_doLoginIgnoringProxy:(BOOL)arg0 withAccount:(id)arg1 ;
-(void)_expireStateTimerFired;
-(void)_handleExpireStateDictionary:(id)arg0 ;
-(void)_handleFirewallUserNotificationDidFinish:(id)arg0 ;
-(void)_handleRoutingWithDictionary:(id)arg0 ;
-(void)_handleWatchdogWithDictionary:(id)arg0 ;
-(void)_login_checkUsernameAndPasswordWithAccount:(id)arg0 ;
-(void)_login_serverSettingsReadyWithAccount:(id)arg0 ;
-(void)_login_usernameAndPasswordReadyWithAccount:(id)arg0 ;
-(void)_managedPrefsNotification:(id)arg0 ;
-(void)_mapRoomChatToGroupChat:(*id)arg0 style:(*unsigned char)arg1 ;
-(void)_markChatAsDowngraded:(id)arg0 ;
-(void)_messageStoreCompletion:(BOOL)arg0 inputMessage:(id)arg1 outputMessage:(id)arg2 originalMessage:(id)arg3 completionBlock:(id)arg4 ;
-(void)_networkChanged:(id)arg0 ;
-(void)_processConnectionMonitorUpdate;
-(void)_processPotentialNetworkChange;
-(void)_reconnectIfNecessary;
-(void)_reconnectIfNecessaryWithAccount:(id)arg0 ;
-(void)_removeChatGuidFromCoreDuet:(id)arg0 ;
-(void)_routingTimerFired;
-(void)_setAutoReconnectTimer;
-(void)_setOutgoingFlagsOnMessage:(id)arg0 ;
-(void)_setPendingConnectionMonitorUpdate;
-(void)_setReplyGUIDOnMessage:(id)arg0 forChat:(id)arg1 ;
-(void)_setSortIDForMessage:(id)arg0 forChat:(id)arg1 ;
-(void)_updateConnectionMonitorFromAccountDefaultsIgnoringProxy:(BOOL)arg0 ;
-(void)_updateConnectionMonitorWithRemoteHost:(id)arg0 ;
-(void)_updateExpireStateForMessageGUID:(id)arg0 ;
-(void)_updateExpireStateTimerWithInterval:(CGFloat)arg0 ;
-(void)_updateInputMessage:(id)arg0 forExistingMessage:(id)arg1 ;
-(void)_updateLastMessageTimeStampForChat:(id)arg0 broadcaster:(id)arg1 ;
-(void)_updateRoutingForMessageGUID:(id)arg0 chatGUID:(id)arg1 error:(unsigned int)arg2 account:(id)arg3 ;
-(void)_updateRoutingTimerWithInterval:(CGFloat)arg0 ;
-(void)_updateWatchdogForMessageGUID:(id)arg0 ;
-(void)_updateWatchdogTimerWithInterval:(CGFloat)arg0 ;
-(void)_watchdogTimerFired;
-(void)_wentOfflineWithAccount:(id)arg0 ;
-(void)acceptSubscriptionRequest:(BOOL)arg0 from:(id)arg1 ;
-(void)accountDefaultsChanged:(id)arg0 ;
-(void)addAccount:(id)arg0 ;
-(void)addAliases:(id)arg0 account:(id)arg1 ;
-(void)authenticateAccount:(id)arg0 ;
-(void)autoLogin;
-(void)autoReconnect;
-(void)autoReconnectWithAccount:(id)arg0 ;
-(void)autoReplier:(id)arg0 generatedAutoReplyText:(id)arg1 forChat:(id)arg2 ;
-(void)autoReplier:(id)arg0 receivedUrgentRequestForMessages:(id)arg1 ;
-(void)autoReplier:(id)arg0 sendDeliveredQuietlyReceiptForMessages:(id)arg1 forIncomingMessageFromIDSID:(id)arg2 inChat:(id)arg3 withWillSendToDestinationsHandler:(id)arg4 ;
-(void)autoReplier:(id)arg0 sendNotifyRecipientCommandForMessages:(id)arg1 inChat:(id)arg2 ;
-(void)beginBuddyChanges;
-(void)cancelVCRequestWithPerson:(id)arg0 properties:(id)arg1 conference:(id)arg2 ;
-(void)canonicalizeChatIdentifier:(*id)arg0 style:(*unsigned char)arg1 ;
-(void)changeGroup:(id)arg0 changes:(id)arg1 ;
-(void)changeGroups:(id)arg0 ;
-(void)changeLocalProperty:(id)arg0 ofBuddy:(id)arg1 to:(id)arg2 ;
-(void)changeProperty:(id)arg0 ofBuddy:(id)arg1 to:(id)arg2 ;
-(void)clearLocalProperties;
-(void)clearPropertiesOfBuddy:(id)arg0 ;
-(void)closeSessionChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)closeSessionChatID:(id)arg0 identifier:(id)arg1 style:(unsigned char)arg2 ;
-(void)connectionMonitorDidUpdate:(id)arg0 ;
-(void)dealloc;
-(void)declineInvitationToChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)declineInvitationToChatID:(id)arg0 identifier:(id)arg1 style:(unsigned char)arg2 ;
-(void)decrementPendingReadReceiptFromStorageCount;
-(void)deleteChatsForCommandDictionary:(id)arg0 ;
-(void)deleteMessagePartsForCommandDictionary:(id)arg0 ;
-(void)deleteMessagesForCommandDictionary:(id)arg0 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 forChat:(id)arg2 style:(unsigned char)arg3 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 fromHandle:(id)arg2 unformattedNumber:(id)arg3 countryCode:(id)arg4 forChat:(id)arg5 style:(unsigned char)arg6 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 fromHandle:(id)arg2 unformattedNumber:(id)arg3 countryCode:(id)arg4 forChat:(id)arg5 style:(unsigned char)arg6 account:(id)arg7 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 fromHandle:(id)arg2 unformattedNumber:(id)arg3 countryCode:(id)arg4 forChat:(id)arg5 style:(unsigned char)arg6 account:(id)arg7 destinationCallerID:(id)arg8 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 fromHandle:(id)arg2 unformattedNumber:(id)arg3 countryCode:(id)arg4 forChat:(id)arg5 style:(unsigned char)arg6 account:(id)arg7 destinationCallerID:(id)arg8 messageTime:(id)arg9 ;
-(void)didChangeMemberStatus:(int)arg0 forHandle:(id)arg1 unformattedNumber:(id)arg2 countryCode:(id)arg3 forChat:(id)arg4 style:(unsigned char)arg5 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 account:(id)arg5 isBlackholed:(BOOL)arg6 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 category:(NSInteger)arg5 spamExtensionName:(id)arg6 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 lastAddressedHandle:(id)arg4 handleInfo:(id)arg5 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 lastAddressedHandle:(id)arg4 lastAddressedSIMID:(id)arg5 handleInfo:(id)arg6 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 handleInfo:(id)arg2 ;
-(void)didJoinChat:(id)arg0 style:(unsigned char)arg1 handleInfo:(id)arg2 account:(id)arg3 ;
-(void)didJoinReadOnlyChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 category:(NSInteger)arg5 spamExtensionName:(id)arg6 ;
-(void)didLeaveChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)didLeaveChat:(id)arg0 style:(unsigned char)arg1 account:(id)arg2 ;
-(void)didReceiveBalloonPayload:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 messageGUID:(id)arg3 account:(id)arg4 ;
-(void)didReceiveDisplayNameChange:(id)arg0 fromID:(id)arg1 toIdentifier:(id)arg2 forChat:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 ;
-(void)didReceiveDisplayNameChange:(id)arg0 fromID:(id)arg1 toIdentifier:(id)arg2 forChat:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 sender:(id)arg6 ;
-(void)didReceiveError:(unsigned int)arg0 forMessageID:(id)arg1 forceError:(BOOL)arg2 ;
-(void)didReceiveError:(unsigned int)arg0 forMessageID:(id)arg1 forceError:(BOOL)arg2 account:(id)arg3 ;
-(void)didReceiveErrorMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)didReceiveInvitation:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)didReceiveMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 fromIDSID:(id)arg4 ;
-(void)didReceiveMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 fromIDSID:(id)arg3 ;
-(void)didReceiveMessageEditingSendFailure:(unsigned int)arg0 forMessageGUID:(id)arg1 partIndex:(NSInteger)arg2 editType:(NSUInteger)arg3 ;
-(void)didReceiveMessageEditingUnsupportedHandleIDs:(id)arg0 forMessageGUID:(id)arg1 partIndex:(NSInteger)arg2 previousMessage:(id)arg3 backwardCompatibilityMessageGUID:(id)arg4 ;
-(void)didReceiveMessagePlayedForMessageID:(id)arg0 date:(id)arg1 completionBlock:(id)arg2 ;
-(void)didReceiveMessagePlayedReceiptForMessageID:(id)arg0 date:(id)arg1 completionBlock:(id)arg2 ;
-(void)didReceiveMessageReadForMessageID:(id)arg0 date:(id)arg1 completionBlock:(id)arg2 ;
-(void)didReceiveMessageReadReceiptForMessageID:(id)arg0 date:(id)arg1 completionBlock:(id)arg2 ;
-(void)didReceiveMessageSavedForMessageID:(id)arg0 ofType:(NSInteger)arg1 forChat:(id)arg2 fromHandle:(id)arg3 fromMe:(BOOL)arg4 date:(id)arg5 account:(id)arg6 completionBlock:(id)arg7 ;
-(void)didReceiveReplaceMessageID:(int)arg0 forChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)didSendBalloonPayload:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 messageGUID:(id)arg3 account:(id)arg4 completionBlock:(id)arg5 ;
-(void)didSendDeliveredQuietlyReceiptForMessageID:(id)arg0 ;
-(void)didSendDeliveredQuietlyReceiptForMessageID:(id)arg0 account:(id)arg1 ;
-(void)didSendMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)didSendMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 forceDate:(id)arg4 ;
-(void)didSendMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 forceDate:(id)arg4 itemIsComingFromStorage:(BOOL)arg5 ;
-(void)didSendMessage:(id)arg0 forChat:(id)arg1 style:(unsigned char)arg2 forceDate:(id)arg3 ;
-(void)didSendMessageEditForMessageGUID:(id)arg0 ;
-(void)didSendMessagePlayedReceiptForMessageID:(id)arg0 ;
-(void)didSendMessagePlayedReceiptForMessageID:(id)arg0 account:(id)arg1 ;
-(void)didSendMessageReadReceiptForMessageID:(id)arg0 ;
-(void)didSendMessageReadReceiptForMessageID:(id)arg0 account:(id)arg1 ;
-(void)didSendMessageSavedReceiptForMessageID:(id)arg0 ;
-(void)didSendMessageSavedReceiptForMessageID:(id)arg0 account:(id)arg1 ;
-(void)didSendNotifyRecipientCommandForMessageID:(id)arg0 ;
-(void)didSendNotifyRecipientCommandForMessageID:(id)arg0 account:(id)arg1 ;
-(void)didSendSyndicationActionItem:(id)arg0 forChat:(id)arg1 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 handleInfo:(id)arg5 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 handleInfo:(id)arg5 account:(id)arg6 category:(NSInteger)arg7 spamExtensionName:(id)arg8 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 handleInfo:(id)arg5 account:(id)arg6 isBlackholed:(BOOL)arg7 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 lastAddressedHandle:(id)arg5 handleInfo:(id)arg6 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 lastAddressedHandle:(id)arg5 lastAddressedSIMID:(id)arg6 handleInfo:(id)arg7 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 lastAddressedHandle:(id)arg5 lastAddressedSIMID:(id)arg6 handleInfo:(id)arg7 account:(id)arg8 category:(NSInteger)arg9 spamExtensionName:(id)arg10 isBlackholed:(BOOL)arg11 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 displayName:(id)arg3 groupID:(id)arg4 lastAddressedHandle:(id)arg5 lastAddressedSIMID:(id)arg6 handleInfo:(id)arg7 account:(id)arg8 isBlackholed:(BOOL)arg9 ;
-(void)didUpdateChatStatus:(int)arg0 chat:(id)arg1 style:(unsigned char)arg2 handleInfo:(id)arg3 ;
-(void)disallowReconnection;
-(void)eagerUploadCancel:(id)arg0 ;
-(void)eagerUploadTransfer:(id)arg0 recipients:(id)arg1 ;
-(void)endBuddyChanges;
-(void)enqueReplayMessageCallback:(id)arg0 ;
-(void)holdBuddyUpdates;
-(void)incrementPendingReadReceiptFromStorageCount;
-(void)invitePerson:(id)arg0 withMessage:(id)arg1 toChat:(id)arg2 style:(unsigned char)arg3 ;
-(void)invitePersonInfo:(id)arg0 withMessage:(id)arg1 toChat:(id)arg2 style:(unsigned char)arg3 ;
-(void)invitePersonInfo:(id)arg0 withMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 ;
-(void)invitePersonInfoToiMessageChat:(id)arg0 withMessage:(id)arg1 toChat:(id)arg2 style:(unsigned char)arg3 ;
-(void)invitePersonInfoToiMessageChat:(id)arg0 withMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 ;
-(void)joinChat:(id)arg0 handleInfo:(id)arg1 style:(unsigned char)arg2 groupID:(id)arg3 joinProperties:(id)arg4 ;
-(void)joinChat:(id)arg0 handleInfo:(id)arg1 style:(unsigned char)arg2 groupID:(id)arg3 lastAddressedHandle:(id)arg4 lastAddressedSIMID:(id)arg5 joinProperties:(id)arg6 ;
-(void)joinChat:(id)arg0 style:(unsigned char)arg1 groupID:(id)arg2 joinProperties:(id)arg3 ;
-(void)joinChat:(id)arg0 style:(unsigned char)arg1 joinProperties:(id)arg2 ;
-(void)joinChatID:(id)arg0 handleInfo:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 groupID:(id)arg4 lastAddressedHandle:(id)arg5 lastAddressedSIMID:(id)arg6 joinProperties:(id)arg7 ;
-(void)leaveChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)leaveChatID:(id)arg0 identifier:(id)arg1 style:(unsigned char)arg2 ;
-(void)leaveiMessageChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)leaveiMessageChatID:(id)arg0 identifier:(id)arg1 style:(unsigned char)arg2 ;
-(void)login;
-(void)loginServiceSessionWithAccount:(id)arg0 ;
-(void)loginWithAccount:(id)arg0 ;
-(void)logout;
-(void)logoutServiceSessionWithAccount:(id)arg0 ;
-(void)logoutWithAccount:(id)arg0 ;
-(void)markBuddiesAsChanged:(id)arg0 ;
-(void)noteBadPassword;
-(void)noteItemFromStorage:(id)arg0 ;
-(void)noteLastItemFromStorage:(id)arg0 ;
-(void)noteLastItemProcessed;
-(void)noteSuppressedMessageUpdate:(id)arg0 ;
-(void)notifyDidSendMessageID:(id)arg0 ;
-(void)notifyDidSendMessageID:(id)arg0 account:(id)arg1 shouldNotify:(BOOL)arg2 ;
-(void)notifyDidSendMessageID:(id)arg0 shouldNotify:(BOOL)arg1 ;
-(void)passwordUpdatedWithAccount:(id)arg0 ;
-(void)processMessageForSending:(id)arg0 toChat:(id)arg1 style:(unsigned char)arg2 allowWatchdog:(BOOL)arg3 account:(id)arg4 completionBlock:(id)arg5 ;
-(void)processMessageForSending:(id)arg0 toChat:(id)arg1 style:(unsigned char)arg2 allowWatchdog:(BOOL)arg3 completionBlock:(id)arg4 ;
-(void)processNetworkDataAvailabilityChange:(BOOL)arg0 ;
-(void)recoverChatsForCommandDictionary:(id)arg0 ;
-(void)refreshServiceCapabilities;
-(void)registerAccount:(id)arg0 ;
-(void)registerChat:(id)arg0 groupID:(id)arg1 style:(unsigned char)arg2 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 handleInfo:(id)arg4 account:(id)arg5 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 lastAddressedHandle:(id)arg4 handleInfo:(id)arg5 account:(id)arg6 isBlackholed:(BOOL)arg7 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 displayName:(id)arg2 groupID:(id)arg3 lastAddressedHandle:(id)arg4 lastAddressedSIMID:(id)arg5 handleInfo:(id)arg6 account:(id)arg7 isBlackholed:(BOOL)arg8 ;
-(void)registerChat:(id)arg0 style:(unsigned char)arg1 handleInfo:(id)arg2 ;
-(void)relay:(id)arg0 sendCancel:(id)arg1 toPerson:(id)arg2 ;
-(void)relay:(id)arg0 sendInitateRequest:(id)arg1 toPerson:(id)arg2 ;
-(void)relay:(id)arg0 sendUpdate:(id)arg1 toPerson:(id)arg2 ;
-(void)removeAccount:(id)arg0 ;
-(void)removeAliases:(id)arg0 account:(id)arg1 ;
-(void)removeChat:(id)arg0 style:(unsigned char)arg1 ;
-(void)removeChatID:(id)arg0 identifier:(id)arg1 style:(unsigned char)arg2 ;
-(void)removePersonInfo:(id)arg0 chatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)removePersonInfoFromiMessageChat:(id)arg0 chatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)renameGroup:(id)arg0 to:(id)arg1 ;
-(void)replayMessage:(id)arg0 ;
-(void)requestGroupPhotoIfNecessary:(id)arg0 incomingGroupPhotoCreationTime:(id)arg1 toIdentifier:(id)arg2 fromIdentifier:(id)arg3 messageIsFromStorage:(BOOL)arg4 ;
-(void)requestGroups;
-(void)requestProperty:(id)arg0 ofPerson:(id)arg1 ;
-(void)requestSubscriptionTo:(id)arg0 ;
-(void)requestVCWithPerson:(id)arg0 properties:(id)arg1 conference:(id)arg2 ;
-(void)respondToVCInvitationWithPerson:(id)arg0 properties:(id)arg1 conference:(id)arg2 ;
-(void)resumeBuddyUpdates;
-(void)retryGroupPhotoUpload:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 ;
-(void)scheduleTransactionLogTask:(id)arg0 ;
-(void)sendAVMessageToPerson:(id)arg0 sessionID:(unsigned int)arg1 type:(unsigned int)arg2 userInfo:(id)arg3 conference:(id)arg4 ;
-(void)sendCommand:(id)arg0 withProperties:(id)arg1 toPerson:(id)arg2 ;
-(void)sendCommand:(id)arg0 withProperties:(id)arg1 toPerson:(id)arg2 toChatID:(id)arg3 identifier:(id)arg4 style:(unsigned char)arg5 ;
-(void)sendCounterProposalToPerson:(id)arg0 properties:(id)arg1 conference:(id)arg2 ;
-(void)sendDeleteCommand:(id)arg0 forChatGUID:(id)arg1 ;
-(void)sendDeliveredQuietlyReceiptForMessage:(id)arg0 forIncomingMessageFromIDSID:(id)arg1 toChatGuid:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 withWillSendToDestinationsHandler:(id)arg5 ;
-(void)sendDeliveryReceiptForMessageID:(id)arg0 toID:(id)arg1 deliveryContext:(id)arg2 needsDeliveryReceipt:(id)arg3 callerID:(id)arg4 account:(id)arg5 ;
-(void)sendEditedMessage:(id)arg0 previousMessage:(id)arg1 partIndex:(NSInteger)arg2 editType:(NSUInteger)arg3 toChatIdentifier:(id)arg4 style:(unsigned char)arg5 account:(id)arg6 backwardCompatabilityText:(id)arg7 ;
-(void)sendGroupPhotoUpdate:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 ;
-(void)sendJunkReportMessage:(id)arg0 ;
-(void)sendLocationSharingInfo:(id)arg0 toID:(id)arg1 completionBlock:(id)arg2 ;
-(void)sendLogDumpMessageAtFilePath:(id)arg0 toRecipient:(id)arg1 shouldDeleteFile:(BOOL)arg2 withCompletion:(id)arg3 ;
-(void)sendMessage:(id)arg0 toChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)sendMessage:(id)arg0 toChat:(id)arg1 style:(unsigned char)arg2 account:(id)arg3 ;
-(void)sendMessage:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)sendNicknameInfoToChatID:(id)arg0 ;
-(void)sendNotifyRecipientCommandForMessage:(id)arg0 toChatGuid:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)sendPlayedReceiptForMessage:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)sendReadReceiptForMessage:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)sendSavedReceiptForMessage:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 ;
-(void)sendSavedReceiptForMessage:(id)arg0 toChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 ;
-(void)sendSyndicationAction:(id)arg0 toChatsWithIdentifiers:(id)arg1 ;
-(void)sendVCUpdate:(id)arg0 toPerson:(id)arg1 conference:(id)arg2 ;
-(void)serviceSessionDidLoginWithAccount:(id)arg0 ;
-(void)serviceSessionDidLogoutWithAccount:(id)arg0 ;
-(void)serviceSessionDidLogoutWithMessage:(id)arg0 reason:(int)arg1 properties:(id)arg2 account:(id)arg3 ;
-(void)sessionDidBecomeActive;
-(void)sessionWillBecomeInactiveWithAccount:(id)arg0 ;
-(void)setAllowList:(id)arg0 ;
-(void)setBlockIdleStatus:(BOOL)arg0 ;
-(void)setBlockList:(id)arg0 ;
-(void)setBlockingMode:(unsigned int)arg0 ;
-(void)setPendingReadReceiptFromStorageCount:(NSUInteger)arg0 ;
-(void)setProperties:(id)arg0 ofParticipant:(id)arg1 inChat:(id)arg2 style:(unsigned char)arg3 ;
-(void)setProperties:(id)arg0 ofParticipant:(id)arg1 inChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 ;
-(void)setValue:(id)arg0 ofProperty:(id)arg1 ofPerson:(id)arg2 ;
-(void)startWatchingBuddy:(id)arg0 ;
-(void)stopWatchingBuddy:(id)arg0 ;
-(void)storeItem:(id)arg0 toChat:(id)arg1 style:(unsigned char)arg2 ;
-(void)systemProxySettingsFetcher:(id)arg0 retrievedAccount:(id)arg1 password:(id)arg2 ;
-(void)systemProxySettingsFetcher:(id)arg0 retrievedHost:(id)arg1 port:(unsigned short)arg2 protocol:(NSInteger)arg3 ;
-(void)unregisterAccount:(id)arg0 ;
-(void)unvalidateAliases:(id)arg0 account:(id)arg1 ;
-(void)updateAuthorizationCredentials:(id)arg0 token:(id)arg1 account:(id)arg2 ;
-(void)updateChatGUID:(id)arg0 withLastReadTimeStamp:(NSInteger)arg1 withLastSeenMessageGUID:(id)arg2 fromMe:(BOOL)arg3 ;
-(void)updateConnectionMonitorWithLocalSocketAddress:(id)arg0 remoteSocketAddress:(id)arg1 ;
-(void)updateDisplayName:(id)arg0 fromDisplayName:(id)arg1 forChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 ;
-(void)useChatRoom:(id)arg0 forGroupChatIdentifier:(id)arg1 ;
-(void)userNotificationDidFinish:(id)arg0 ;
-(void)validateAliases:(id)arg0 account:(id)arg1 ;
-(void)validateProfileWithAccount:(id)arg0 ;


@end


#endif