

#include "FIMindfulnessReminder.h"
#include "FIMindfulnessAppMigrator.h"
#include "FITrailingQuantityTimeSlice.h"
#include "FIAppStoreAvailability.h"
#include "FIValidation.h"
#include "FISleepDataProvider.h"
#include "FIFitnessAppsStateObserver.h"
#include "FIMindfulnessSessionDataProvider.h"
#include "FITrailingIntervalController.h"
#include "FIIntervalDefinition.h"
#include "FIMutableTimeSliceGroup.h"
#include "FIReduction.h"
#include "FISleepUserDay.h"
#include "FIActivitySettingsController.h"
#include "FIQuantityTimeSlice.h"
#include "FIQuantityIntervalController.h"
#include "FISimpleHistogram.h"
#include "FIIntervalWorkoutDefinitionsManager.h"
#include "FIMindfulnessCustomReminderProvider.h"
#include "FIIntervalWorkoutDefinition.h"
#include "FITypicalDayActivityModel.h"
#include "FIIntervalQuantityTrigger.h"
#include "FIIntervalSetDefinition.h"
#include "FIQuantityInterval.h"
