// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef UICOLOR_H
#define UICOLOR_H

@class NSString, CIColor, NSArray;
@protocol NSItemProviderReading, NSItemProviderWriting, UIItemProviderReading, UIItemProviderWriting, NSSecureCoding, NSCopying;

#import <Foundation/Foundation.h>


@interface UIColor : NSObject <NSItemProviderReading, NSItemProviderWriting, UIItemProviderReading, UIItemProviderWriting, NSSecureCoding, NSCopying>

 {
    NSString *_systemColorName;
    NSString *_cachedStyleString;
}


@property (readonly, nonatomic) *CGColor CGColor;
@property (readonly, nonatomic) CIColor *CIColor;
@property (readonly, nonatomic) NSString *_accessibilityNameWithLuma;
@property (readonly, nonatomic) NSString *accessibilityName;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic, getter=_isDynamic) BOOL dynamic;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic, getter=_isDynamicTintColor) BOOL isDynamicTintColor;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (retain, nonatomic, getter=_systemColorName, setter=_setSystemColorName:) NSString *systemColorName;
@property (readonly, copy, nonatomic) NSArray *writableTypeIdentifiersForItemProvider;
@property (readonly, copy, nonatomic) NSArray *writableTypeIdentifiersForItemProvider;


+(BOOL)supportsSecureCoding;
+(CGFloat)_luminanceWithRed:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 ;
+(id)__darkSystemColorForColor:(id)arg0 ;
+(id)__halfTransparentBlackColor;
+(id)__halfTransparentWhiteColor;
+(id)__tintColor;
+(id)_accessibilityButtonShapesBackgroundColorOnDark;
+(id)_accessibilityButtonShapesBackgroundColorOnLight;
+(id)_accessibilityButtonShapesDisabledBackgroundColorOnDark;
+(id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnDark;
+(id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnLight;
+(id)_accessibilityDarkenedColorForColor:(id)arg0 ;
+(id)_accessibilityLightenedColorForColor:(id)arg0 ;
+(id)_alertControllerDimmingViewColor;
+(id)_alternateSystemInteractionTintColor;
+(id)_apiColorNames;
+(id)_appKeyColor;
+(id)_appKeyColorOrDefaultTint;
+(id)_barHairlineShadowColor;
+(id)_barStyleBlackHairlineShadowColor;
+(id)_carSystemFocusColor;
+(id)_carSystemFocusLabelColor;
+(id)_carSystemFocusPrimaryColor;
+(id)_carSystemFocusSecondaryColor;
+(id)_carSystemPrimaryColor;
+(id)_carSystemQuaternaryColor;
+(id)_carSystemSecondaryColor;
+(id)_carSystemTertiaryColor;
+(id)_composedColorFromSourceColor:(id)arg0 destinationColor:(id)arg1 tintColor:(id)arg2 alpha:(CGFloat)arg3 ;
+(id)_contentBackgroundColor;
+(id)_controlForegroundColor;
+(id)_controlHighlightColor;
+(id)_controlShadowColor;
+(id)_controlVibrantBottomBackgroundColor;
+(id)_controlVibrantTopBackgroundColor;
+(id)_convertColorPickerColor:(id)arg0 fromUserInterfaceStyle:(NSInteger)arg1 to:(NSInteger)arg2 ;
+(id)_dimmingViewColor;
+(id)_disabledColorForColor:(id)arg0 ;
+(id)_disambiguated_due_to_CIImage_colorWithCGColor:(struct CGColor *)arg0 ;
+(id)_disambiguated_due_to_CIImage_colorWithRed:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
+(id)_dynamicCatalogColorForNibEncodingWithName:(id)arg0 genericColor:(id)arg1 ;
+(id)_dynamicColorWithColorsByTraitCollection:(id)arg0 ;
+(id)_dynamicTestColor;
+(id)_externalBarBackgroundColor;
+(id)_externalSystemDarkGrayColor;
+(id)_externalSystemExtraDarkGrayColor;
+(id)_externalSystemGrayColor;
+(id)_externalSystemMidGrayColor;
+(id)_externalSystemSuperDarkGrayColor;
+(id)_externalSystemWhiteColor;
+(id)_fillColor;
+(id)_focusedCarSystemColor:(id)arg0 ;
+(id)_grayColorForFontSize:(CGFloat)arg0 ;
+(id)_groupTableHeaderFooterTextColor;
+(id)_labelColor;
+(id)_linkColor;
+(id)_markedTextBackgroundColor;
+(id)_monochromeCellImageTintColor;
+(id)_opaqueSeparatorColor;
+(id)_pageControlIndicatorColor;
+(id)_pageControlPlatterIndicatorColor;
+(id)_placeholderTextColor;
+(id)_plainTableHeaderFooterTextColor;
+(id)_quaternaryFillColor;
+(id)_quaternaryLabelColor;
+(id)_searchBarBackgroundColor;
+(id)_searchFieldDisabledBackgroundColor;
+(id)_searchFieldPlaceholderTextClearButtonColor;
+(id)_secondaryFillColor;
+(id)_secondaryLabelColor;
+(id)_secondarySystemBackgroundColor;
+(id)_secondarySystemGroupedBackgroundColor;
+(id)_separatorColor;
+(id)_sidebarBackgroundColor;
+(id)_splitViewBorderColor;
+(id)_swiftColor;
+(id)_swipedSidebarCellBackgroundColor;
+(id)_switchOffColor;
+(id)_switchOffImageColor;
+(id)_systemBackgroundColor;
+(id)_systemBackgroundSectionCellColor;
+(id)_systemBackgroundSectionColor;
+(id)_systemBlueColor2;
+(id)_systemChromeShadowColor;
+(id)_systemColorForColor:(id)arg0 withName:(id)arg1 ;
+(id)_systemColorSelectorTable;
+(id)_systemColorWithName:(id)arg0 ;
+(id)_systemColorWithUnvalidatedName:(id)arg0 ;
+(id)_systemDestructiveTintColor;
+(id)_systemGray2Color;
+(id)_systemGray3Color;
+(id)_systemGray4Color;
+(id)_systemGray5Color;
+(id)_systemGray6Color;
+(id)_systemGroupBackgroundCellColor;
+(id)_systemGroupBackgroundColor;
+(id)_systemGroupedBackgroundColor;
+(id)_systemInteractionTintColor;
+(id)_systemMidGrayTintColor;
+(id)_systemSelectedColor;
+(id)_tertiaryFillColor;
+(id)_tertiaryLabelColor;
+(id)_tertiarySystemBackgroundColor;
+(id)_tertiarySystemGroupedBackgroundColor;
+(id)_textFieldBackgroundColor;
+(id)_textFieldBorderColor;
+(id)_textFieldDisabledBackgroundColor;
+(id)_textFieldDisabledBorderColor;
+(id)_tintColor;
+(id)_translucentPaperTextureColor;
+(id)_tvInterfaceStyleDarkContentColor;
+(id)_tvInterfaceStyleLightContentColor;
+(id)_tvLabelOpacityAColor;
+(id)_tvLabelOpacityBColor;
+(id)_tvLabelOpacityCColor;
+(id)_unfocusedCarSystemColor:(id)arg0 ;
+(id)_vibrantDarkFillDodgeColor;
+(id)_vibrantLightDividerBurnColor;
+(id)_vibrantLightDividerDarkeningColor;
+(id)_vibrantLightFillBurnColor;
+(id)_vibrantLightFillDarkeningColor;
+(id)_vibrantLightSectionDelimiterDividerBurnColor;
+(id)_vibrantLightSectionDelimiterDividerDarkeningColor;
+(id)_webContentBackgroundColor;
+(id)_windowBackgroundColor;
+(id)allocWithZone:(struct _NSZone *)arg0 ;
+(id)blackColor;
+(id)blueColor;
+(id)brownColor;
+(id)classFallbacksForKeyedArchiver;
+(id)clearColor;
+(id)colorNamed:(id)arg0 ;
+(id)colorNamed:(id)arg0 inBundle:(id)arg1 compatibleWithTraitCollection:(id)arg2 ;
+(id)colorWithCGColor:(struct CGColor *)arg0 ;
+(id)colorWithCIColor:(id)arg0 ;
+(id)colorWithDisplayP3Red:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
+(id)colorWithDynamicProvider:(id)arg0 ;
+(id)colorWithHue:(CGFloat)arg0 saturation:(CGFloat)arg1 brightness:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
+(id)colorWithPatternImage:(id)arg0 ;
+(id)colorWithRed:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
+(id)colorWithWhite:(CGFloat)arg0 alpha:(CGFloat)arg1 ;
+(id)cyanColor;
+(id)darkGrayColor;
+(id)darkTextColor;
+(id)externalSystemGreenColor;
+(id)externalSystemRedColor;
+(id)externalSystemTealColor;
+(id)grayColor;
+(id)greenColor;
+(id)groupTableViewBackgroundColor;
+(id)infoTextOverPinStripeTextColor;
+(id)insertionPointColor;
+(id)keyboardFocusIndicatorColor;
+(id)labelColor;
+(id)lightGrayColor;
+(id)lightTextColor;
+(id)linkColor;
+(id)magentaColor;
+(id)noContentDarkGradientBackgroundColor;
+(id)noContentLightGradientBackgroundColor;
+(id)objectWithItemProviderData:(id)arg0 typeIdentifier:(id)arg1 error:(*id)arg2 ;
+(id)opaqueSeparatorColor;
+(id)orangeColor;
+(id)pinStripeColor;
+(id)placeholderTextColor;
+(id)purpleColor;
+(id)quaternaryLabelColor;
+(id)quaternarySystemFillColor;
+(id)readableTypeIdentifiersForItemProvider;
+(id)redColor;
+(id)scrollViewTexturedBackgroundColor;
+(id)secondaryLabelColor;
+(id)secondarySystemBackgroundColor;
+(id)secondarySystemFillColor;
+(id)secondarySystemGroupedBackgroundColor;
+(id)sectionHeaderBackgroundColor;
+(id)sectionHeaderBorderColor;
+(id)sectionHeaderOpaqueBackgroundColor;
+(id)sectionListBorderColor;
+(id)selectionGrabberColor;
+(id)selectionHighlightColor;
+(id)separatorColor;
+(id)systemBackgroundColor;
+(id)systemBlackColor;
+(id)systemBlueColor;
+(id)systemBrownColor;
+(id)systemCyanColor;
+(id)systemDarkBlueColor;
+(id)systemDarkExtraLightGrayColor;
+(id)systemDarkExtraLightGrayTintColor;
+(id)systemDarkGrayColor;
+(id)systemDarkGrayTintColor;
+(id)systemDarkGreenColor;
+(id)systemDarkLightGrayColor;
+(id)systemDarkLightGrayTintColor;
+(id)systemDarkLightMidGrayColor;
+(id)systemDarkLightMidGrayTintColor;
+(id)systemDarkMidGrayColor;
+(id)systemDarkMidGrayTintColor;
+(id)systemDarkOrangeColor;
+(id)systemDarkPinkColor;
+(id)systemDarkPurpleColor;
+(id)systemDarkRedColor;
+(id)systemDarkTealColor;
+(id)systemDarkYellowColor;
+(id)systemExtraLightGrayColor;
+(id)systemExtraLightGrayTintColor;
+(id)systemFillColor;
+(id)systemGray2Color;
+(id)systemGray3Color;
+(id)systemGray4Color;
+(id)systemGray5Color;
+(id)systemGray6Color;
+(id)systemGrayColor;
+(id)systemGrayTintColor;
+(id)systemGreenColor;
+(id)systemGroupedBackgroundColor;
+(id)systemIndigoColor;
+(id)systemLightGrayColor;
+(id)systemLightGrayTintColor;
+(id)systemLightMidGrayColor;
+(id)systemLightMidGrayTintColor;
+(id)systemMidGrayColor;
+(id)systemMidGrayTintColor;
+(id)systemMintColor;
+(id)systemOrangeColor;
+(id)systemPinkColor;
+(id)systemPurpleColor;
+(id)systemRedColor;
+(id)systemTealColor;
+(id)systemWhiteColor;
+(id)systemYellowColor;
+(id)tableBackgroundColor;
+(id)tableCellBackgroundColor;
+(id)tableCellBlueTextColor;
+(id)tableCellDefaultSelectionTintColor;
+(id)tableCellDisabledBackgroundColor;
+(id)tableCellFocusedBackgroundColor;
+(id)tableCellGrayTextColor;
+(id)tableCellGroupedBackgroundColor;
+(id)tableCellGroupedBackgroundColorLegacyWhite;
+(id)tableCellGroupedSelectedBackgroundColor;
+(id)tableCellHighlightedBackgroundColor;
+(id)tableCellPlainBackgroundColor;
+(id)tableCellPlainSelectedBackgroundColor;
+(id)tableCellValue1BlueColor;
+(id)tableCellValue2BlueColor;
+(id)tableCellbackgroundColorCarPlay;
+(id)tableGroupedSeparatorLightColor;
+(id)tableGroupedTopShadowColor;
+(id)tablePlainHeaderFooterBackgroundColor;
+(id)tablePlainHeaderFooterFloatingBackgroundColor;
+(id)tableSelectionColor;
+(id)tableSelectionGradientEndColor;
+(id)tableSelectionGradientStartColor;
+(id)tableSeparatorColor;
+(id)tableSeparatorDarkColor;
+(id)tableSeparatorLightColor;
+(id)tableShadowColor;
+(id)tertiaryLabelColor;
+(id)tertiarySystemBackgroundColor;
+(id)tertiarySystemFillColor;
+(id)tertiarySystemGroupedBackgroundColor;
+(id)textFieldAtomBlueColor;
+(id)textFieldAtomPurpleColor;
+(id)textGrammarIndicatorColor;
+(id)tintColor;
+(id)underPageBackgroundColor;
+(id)viewFlipsideBackgroundColor;
+(id)whiteColor;
+(id)yellowColor;
+(void)initialize;
-(BOOL)_getRed:(*CGFloat)arg0 green:(*CGFloat)arg1 blue:(*CGFloat)arg2 alpha:(*CGFloat)arg3 ;
-(BOOL)_getWhite:(*CGFloat)arg0 alpha:(*CGFloat)arg1 ;
-(BOOL)_isDeepColor;
-(BOOL)_isOpaque;
-(BOOL)_isSimilarToColor:(id)arg0 withinPercentage:(CGFloat)arg1 ;
-(BOOL)getHue:(*CGFloat)arg0 saturation:(*CGFloat)arg1 brightness:(*CGFloat)arg2 alpha:(*CGFloat)arg3 ;
-(BOOL)getRed:(*CGFloat)arg0 green:(*CGFloat)arg1 blue:(*CGFloat)arg2 alpha:(*CGFloat)arg3 ;
-(BOOL)getWhite:(*CGFloat)arg0 alpha:(*CGFloat)arg1 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)isPatternColor;
-(CGFloat)_colorDifferenceFromColor:(id)arg0 ;
-(CGFloat)_luminance;
-(CGFloat)_luminanceDifferenceFromColor:(id)arg0 ;
-(CGFloat)alphaComponent;
-(Class)classForCoder;
-(id)_backgroundColorIgnoringHighContrast;
-(id)_colorBlendedWithColor:(id)arg0 ;
-(id)_colorBlendedWithColor:(id)arg0 compositingFilter:(id)arg1 ;
-(id)_colorBlendedWithColors:(id)arg0 ;
-(id)_debugCatalogBundleIdentifier;
-(id)_debugName;
-(id)_resolvedMaterialWithTraitCollection:(id)arg0 ;
-(id)colorSpaceName;
-(id)colorWithAlphaComponent:(CGFloat)arg0 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)initWithCGColor:(struct CGColor *)arg0 ;
-(id)initWithCIColor:(id)arg0 ;
-(id)initWithCoder:(id)arg0 ;
-(id)initWithDisplayP3Red:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
-(id)initWithDynamicProvider:(id)arg0 ;
-(id)initWithHue:(CGFloat)arg0 saturation:(CGFloat)arg1 brightness:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
-(id)initWithItemProviderData:(id)arg0 typeIdentifier:(id)arg1 error:(*id)arg2 ;
-(id)initWithPatternImage:(id)arg0 ;
-(id)initWithRed:(CGFloat)arg0 green:(CGFloat)arg1 blue:(CGFloat)arg2 alpha:(CGFloat)arg3 ;
-(id)initWithWhite:(CGFloat)arg0 alpha:(CGFloat)arg1 ;
-(id)loadDataWithTypeIdentifier:(id)arg0 forItemProviderCompletionHandler:(id)arg1 ;
-(id)resolvedColorWithTraitCollection:(id)arg0 ;
-(id)styleString;
-(struct CGColor *)cgColor;
-(void)_setDebugCatalogBundleIdentifier:(id)arg0 ;
-(void)_setDebugName:(id)arg0 ;
-(void)encodeWithCoder:(id)arg0 ;
-(void)set;
-(void)setFill;
-(void)setStroke;


@end


#endif