// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef UIKEYBOARDIMPL_H
#define UIKEYBOARDIMPL_H

@class NSString, TIKeyboardCandidateResultSet, NSMutableDictionary, NSMutableArray, UIResponder<UIKeyInput>, NSDictionary, NSArray, TIKeyboardCandidate, TUIKeyboardBackendController, TICandidateRequestToken, TIKeyboardInputManagerStub, TIKeyboardInputManagerState, NSNumber, TIKeyboardState, TIKeyboardLayout, NSUUID, TISmartPunctuationController, TIKeyboardTouchEvent;
@protocol _UIIVCResponseDelegateImpl, _UIKeyboardTextSelectionGestureControllerDelegate, UIKeyboardCandidateControllerDelegate, TIKeyboardInputManagerToImplProtocol, UIPopoverPresentationControllerDelegate, UIKeyboardInputModeIndicatorControllerDelegate, UIKeyboardImplStateProtocol, UIKBRTIPartnerDelegate, UIKeyboardCandidateListDelegate, UIKeyboardLayoutSizeDelegate, UITextInputDelegatePrivate, UIKeyInput, UIKeyboardCandidateList, UITextCursorAssertion, _UIKBFeedbackGenerating, UIKeyboardImplGeometryDelegate, _UITextInputUserInteractionDelegate;


#import "UIView.h"
#import "UITextInteractionSelectableInputDelegate.h"
#import "UIKeyboardTaskQueue.h"
#import "UIAutocorrectInlinePrompt.h"
#import "UIKeyboardLayout.h"
#import "UIKeyboardScheduledTask.h"
#import "UIDelayedAction.h"
#import "UITextInputTraits.h"
#import "UILexicon.h"
#import "UIPhysicalKeyboardEvent.h"
#import "_UIKeyboardImplProxy.h"
#import "UIContinuousPathIntroductionView.h"
#import "UIKBEditingGesturesIntroduction.h"
#import "UIKeyboardEmojiPopoverController.h"
#import "UIDictationPopoverController.h"
#import "UIKeyboardInputModeIndicatorPopoverController.h"
#import "UIPressAndHoldPopoverController.h"
#import "UIKBRTIPartner.h"
#import "UIEditMenuInteraction.h"
#import "UITextInputArrowKeyHistory.h"
#import "UIAutocorrectBubbleContainer.h"
#import "UIKeyboardAutocorrectionController.h"
#import "UIKBAutofillController.h"
#import "UIKeyboardCandidateController.h"
#import "_UIActionWhenIdle.h"
#import "UIKBInputDelegateManager.h"
#import "UIKeyboardInputModeIndicatorController.h"
#import "_UIStringAndPositionPair.h"
#import "UITextSelectionView.h"
#import "UITextInteractionAssistant.h"
#import "_UIKeyboardTextSelectionController.h"

@interface UIKeyboardImpl : UIView <_UIIVCResponseDelegateImpl, _UIKeyboardTextSelectionGestureControllerDelegate, UIKeyboardCandidateControllerDelegate, TIKeyboardInputManagerToImplProtocol, UIPopoverPresentationControllerDelegate, UIKeyboardInputModeIndicatorControllerDelegate, UIKeyboardImplStateProtocol, UIKBRTIPartnerDelegate, UIKeyboardCandidateListDelegate, UIKeyboardLayoutSizeDelegate, UITextInputDelegatePrivate>

 {
    id<UIKeyInput> *m_delegate;
    UITextInteractionSelectableInputDelegate *m_selectableDelegate;
    UIKeyboardTaskQueue *m_taskQueue;
    BOOL m_keyboardDelegateStateNeedsRefresh;
    NSInteger m_textInputSource;
    UIView *m_languageIndicator;
    NSString *m_previousInputString;
    UIAutocorrectInlinePrompt *m_autocorrectPrompt;
    TIKeyboardCandidateResultSet *m_candidateResultSet;
    id<UIKeyboardCandidateList> *m_candidateList;
    UIView *m_markedTextOverlay;
    UIKeyboardLayout *m_layout;
    NSMutableDictionary *m_keyedLayouts;
    UIKeyboardScheduledTask *m_autoDeleteTask;
    unsigned int m_autoDeleteCount;
    CGFloat m_autoDeleteLastDelete;
    CGFloat m_autoDeleteInterval;
    unsigned int m_autoDeleteShiftCharacter;
    CGFloat m_autoDeleteCurrentForceMultipler;
    CGFloat m_autoDeleteCurrentForce;
    BOOL m_autoDeleteUseForce;
    UIDelayedAction *m_longPressAction;
    NSInteger m_originalOrientation;
    CGPoint m_inputPoint;
    int m_changeCount;
    CGFloat m_changeTime;
    *__CFRunLoopObserver m_observer;
    NSUInteger m_textInputChangingCount;
    BOOL m_textInputChangingText;
    BOOL m_textInputChangingDirection;
    BOOL m_textInputUpdatingSelection;
    BOOL m_disableSyncTextChanged;
    BOOL m_disableClearingTextSuggestions;
    UITextInputTraits *m_defaultTraits;
    UITextInputTraits *m_traits;
    UITextInputTraits *m_overrideTraits;
    int m_returnKeyState;
    BOOL m_returnKeyEnabledInLayout;
    NSInteger m_currentDirection;
    UILexicon *m_recentInputs;
    BOOL m_autoDeleteOK;
    BOOL m_autocapitalizationPreference;
    BOOL m_autocorrectionPreference;
    BOOL m_autoshift;
    BOOL m_caretShowingNow;
    BOOL m_changeNotificationDisabled;
    BOOL m_correctionLearningAllowed;
    BOOL m_delegateIsSMSTextView;
    BOOL m_doubleSpacePeriodWasAppliedInCurrentContext;
    BOOL m_doubleSpacePeriodPreference;
    BOOL m_hardwareKeyboardAttached;
    BOOL m_inDealloc;
    BOOL m_initializationDone;
    BOOL m_selecting;
    BOOL m_shift;
    BOOL m_shiftLocked;
    BOOL m_shiftLockedEnabled;
    BOOL m_settingShift;
    BOOL m_suggestionsShownForCurrentDeletion;
    BOOL m_originalShouldSkipCandidateSelection;
    BOOL m_suppressGeometryChangeNotifications;
    BOOL m_acceptingCandidate;
    BOOL m_didAutomaticallyInsertSpace;
    BOOL m_didSyncDocumentStateToInputDelegate;
    BOOL m_userChangedSelection;
    BOOL m_shouldChargeKeys;
    BOOL m_longPress;
    BOOL m_replacingWord;
    BOOL m_shiftNeedsUpdate;
    BOOL m_shiftPreventAutoshift;
    BOOL m_shiftHeldDownNeedsUpdated;
    BOOL m_clientVariantSupportEnabled;
    BOOL m_clientVariantSupportEnabledEver;
    NSMutableArray *m_keyplaneNamesPreviousDelegate;
    NSMutableArray *m_keyplaneNamesCurrentDelegate;
    BOOL m_isRotating;
    BOOL m_preRotateShift;
    BOOL m_preRotateShiftLocked;
    BOOL m_suppressUpdateCandidateView;
    BOOL m_shouldUpdateCacheOnInputModesChange;
    BOOL m_rivenCenterFilled;
    CGFloat m_splitProgress;
    BOOL m_needsCandidates;
    BOOL m_shouldSkipCandidateGeneration;
    BOOL m_updateLayoutOnShowKeyboard;
    int _currentAlertReason;
    BOOL m_layoutAllowsCP;
    BOOL m_needsPasteSupportUpdate;
    BOOL m_delegateSupportsImagePaste;
    BOOL m_remoteDelegateSupportsImagePaste;
    BOOL m_didUpdateCapsLockLanguageSwitchSetting;
    BOOL m_shouldEnableCapsLockLanguageSwitchByDefault;
    UIPhysicalKeyboardEvent *m_previousGlobeKeyEvent;
    BOOL m_delegateAdoptsKeyboardInput;
    BOOL m_delegateAdoptsTextInput;
    BOOL m_delegateAdoptsTextInputPrivate;
    BOOL m_delegateAdoptsWebTextInputPrivate;
    BOOL m_delegateAdoptsWKInteraction;
    BOOL m_delegateAdoptsKeyInputPrivate;
    BOOL m_delegateAdoptsRTISourceSession;
    BOOL m_firstResponderAdoptsTextInput;
    UIResponder<UIKeyInput> *_forwardingInputDelegate;
    BOOL _forwardingInputDelegateConformsToWKInteraction;
    BOOL _shouldRespectForwardingInputDelegate;
    BOOL m_scrolling;
    BOOL m_hasInputOnAcceptCandidate;
    BOOL m_maximizing;
    BOOL m_usesAutoShiftFor3PK;
    NSUInteger m_previousSpaceKeyBehavior;
    NSUInteger m_previousReturnKeyBehavior;
    BOOL m_usesCandidateSelection;
    BOOL m_UsedCandidateSelection;
    BOOL m_hasEditedMarkedTextInExtendedView;
    BOOL m_updatingLayout;
    BOOL m_needsToRecomputeDesirableModes;
    BOOL m_isCapsLocked;
    UITextInputTraits *m_traitsForPreviousDelegate;
    UIDelayedAction *m_detachHardwareKeyboardAction;
    UIDelayedAction *m_updateLastUsedInputModeAction;
    UIDelayedAction *m_idleDetection;
    UIDelayedAction *m_resumeDictationForResponderChange;
    UIView *m_capsLockSign;
    NSInteger m_userInteraction;
    BOOL m_didAutomaticallyInsertSpaceBeforeChangingInputMode;
    BOOL m_didExtendLongPressDelayForContinuousPath;
    BOOL m_inHandleKeyTextCommandForCurrentEvent;
    BOOL m_inHandleKeyAppCommandForCurrentEvent;
    BOOL m_webEventWasHandledAsKeyCommand;
    BOOL m_webEventWasHandledByInputManager;
    BOOL m_webEventIsKeyDown;
    BOOL m_needsOneShotGenerateCandidatesAfterStoppingAutoDelete;
    BOOL m_disableAutocapitalization;
    int m_predictionType;
    BOOL m_repeatDeleteFromHardwareKeyboard;
    NSInteger m_cachedAutofillMode;
    NSInteger m_autofillSubMode;
    BOOL m_isAutofilling;
    NSInteger m_pendingAutofillIndex;
    BOOL m_ignoreSelectionChange;
    BOOL m_suppressingDocumentAssertions;
    BOOL m_repeatDeleteWord;
    _NSRange m_textAlternativesRange;
    NSDictionary *m_autofillCustomInfo;
    NSUInteger m_numCPwords;
    _UIKeyboardImplProxy *m_implProxy;
    UIKeyboardScheduledTask *m_delayDeleteTask;
    id *_deferredUpdateTask;
    UIContinuousPathIntroductionView *_continuousPathIntroductionView;
    UIKBEditingGesturesIntroduction *_editingGestureIntroductionView;
    BOOL m_editingTraitsMarkedDirty;
    BOOL m_selectionIsEmpty;
    NSMutableDictionary *m_hardwareKeyDownCodeToEventMap;
    UIKeyboardEmojiPopoverController *_emojiPopoverController;
    UIDictationPopoverController *_dictationPopoverController;
    UIKeyboardInputModeIndicatorPopoverController *_indicatorPopoverController;
    UIPressAndHoldPopoverController *_pressAndHoldPopoverController;
    BOOL _emojiPopoverToRestoreAfterRotation;
    BOOL _isSettingDelegate;
    BOOL _isSettingExtensionInputMode;
    BOOL _needsUpdateAssistantView;
    CGFloat m_bottomPadding;
    NSUInteger _serviceRole;
    UIKBRTIPartner *_remoteTextInputPartner;
    UITextInputTraits *_remoteTextInputTraits;
    BOOL m_policyDelegateResult;
    BOOL m_shouldSuppressAssistantBar;
    BOOL m_inputModeSwitcherVisible;
    CGRect m_editMenuFrame;
    UIView *m_keyboardWindowSnapshot;
    UIDelayedAction *m_dictationMenuAction;
    int m_keyboardMenuType;
    int m_presentingKeyboardMenuType;
    NSString *m_languageForDictationMenu;
    UIEditMenuInteraction *m_editMenuInteraction;
    UIView *m_tipView;
}


@property (nonatomic) BOOL _mimicShiftBeingHeld; // ivar: _mimicShiftBeingHeld
@property (nonatomic, setter=_setShouldSuppressAssistantBar:) BOOL _shouldSuppressAssistantBar;
@property (readonly, nonatomic) UIKeyboardLayout *activeLayout;
@property (retain, nonatomic) NSArray *alternativePredictions; // ivar: _alternativePredictions
@property (nonatomic) BOOL animateUpdateBars; // ivar: m_animateUpdateBars
@property (retain, nonatomic) UITextInputArrowKeyHistory *arrowKeyHistory; // ivar: m_arrowKeyHistory
@property (retain, nonatomic) UIAutocorrectBubbleContainer *autocorrectBubbleContainer; // ivar: _autocorrectBubbleContainer
@property (retain, nonatomic) UIKeyboardScheduledTask *autocorrectPromptTask; // ivar: _autocorrectPromptTask
@property (readonly, nonatomic) UIKeyboardAutocorrectionController *autocorrectionController;
@property (readonly, nonatomic) UIKeyboardAutocorrectionController *autocorrectionController; // ivar: m_autocorrectionController
@property (retain, nonatomic) TIKeyboardCandidate *autocorrectionToAcceptBeforeProgressiveCandidates; // ivar: _autocorrectionToAcceptBeforeProgressiveCandidates
@property (retain, nonatomic) UIKBAutofillController *autofillController; // ivar: m_autofillController
@property (readonly, nonatomic) BOOL automaticMinimizationEnabled; // ivar: m_automaticMinimizationEnabled
@property (readonly, nonatomic) TUIKeyboardBackendController *backendController;
@property (readonly, nonatomic) BOOL canShowPredictionBar;
@property (nonatomic) BOOL canSuggestSupplementalItemsForCurrentSelection;
@property (readonly, nonatomic) UIKeyboardCandidateController *candidateController;
@property (readonly, nonatomic) UIKeyboardCandidateController *candidateController; // ivar: m_candidateController
@property (nonatomic) NSInteger candidateViewOffset; // ivar: _candidateViewOffset
@property (readonly) BOOL centerFilled;
@property (retain, nonatomic) id *changedDelegate;
@property (retain, nonatomic) id *changedDelegate; // ivar: m_changedDelegate
@property (copy, nonatomic) NSArray *characterRectsForCharacterRange; // ivar: _characterRectsForCharacterRange
@property (copy, nonatomic) id *chooseSupplementalCandidateCompletion; // ivar: _chooseSupplementalCandidateCompletion
@property (nonatomic) BOOL committingCandidate; // ivar: committingCandidate
@property (readonly, nonatomic) BOOL continuousPathUnderway;
@property (retain, nonatomic) TICandidateRequestToken *currentCandidateRequest; // ivar: _currentCandidateRequest
@property (retain, nonatomic) NSObject<UITextCursorAssertion> *cursorAssertion; // ivar: _cursorAssertion
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) _UIActionWhenIdle *deferredDidSetDelegateAction; // ivar: m_deferredDidSetDelegateAction
@property (retain, nonatomic) _UIActionWhenIdle *delayedCandidateRequest; // ivar: m_delayedCandidateRequest
@property (retain, nonatomic) UIResponder<UIKeyInput> *delegate;
@property (readonly, nonatomic) BOOL delegateRequiresKeyEvents; // ivar: m_delegateRequiresKeyEvents
@property (nonatomic) CGFloat deleteWordLastDelete; // ivar: _deleteWordLastDelete
@property (retain, nonatomic) NSString *deletedString; // ivar: _deletedString
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (nonatomic) BOOL disableSmartInsertDelete; // ivar: m_disableSmartInsertDelete
@property (retain, nonatomic) UIPhysicalKeyboardEvent *eventForCurrentWebEvent; // ivar: m_currentEventForKeyCommand
@property (copy, nonatomic) id *externalTask; // ivar: m_externalTask
@property (retain, nonatomic) NSObject<_UIKBFeedbackGenerating> *feedbackGenerator; // ivar: m_feedbackGenerator
@property (nonatomic) BOOL floatingForced; // ivar: floatingForced
@property (nonatomic) BOOL forCustomInputView; // ivar: _forCustomInputView
@property (weak, nonatomic) NSObject<UIKeyboardImplGeometryDelegate> *geometryDelegate; // ivar: m_geometryDelegate
@property (nonatomic) BOOL geometryIsChanging; // ivar: geometryIsChanging
@property (nonatomic) BOOL handlingKeyCommandFromHardwareKeyboard; // ivar: _handlingKeyCommandFromHardwareKeyboard
@property (nonatomic) BOOL hardwareKeyboardIsSeen;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (nonatomic, getter=isInHardwareKeyboardMode) BOOL inHardwareKeyboardMode;
@property (retain, nonatomic) UIKBInputDelegateManager *inputDelegateManager; // ivar: _inputDelegateManager
@property (readonly, nonatomic) TIKeyboardInputManagerStub *inputManager;
@property (readonly, nonatomic) TIKeyboardInputManagerStub *inputManager;
@property (retain, nonatomic) TIKeyboardInputManagerState *inputManagerState;
@property (retain, nonatomic) TIKeyboardInputManagerState *inputManagerState; // ivar: m_inputManagerState
@property (readonly, nonatomic) UIKeyboardInputModeIndicatorController *inputModeIndicatorController;
@property (retain, nonatomic) UIKeyboardInputModeIndicatorController *inputModeIndicatorController; // ivar: _inputModeIndicatorController
@property (retain, nonatomic) UIView *internationalKeyIntroductionView; // ivar: m_internationalKeyIntroductionView
@property (retain, nonatomic) NSNumber *isAttachedHardwareKeyboard; // ivar: _isAttachedHardwareKeyboard
@property (readonly, nonatomic) BOOL isAutofillPrediction;
@property (nonatomic) BOOL isCallingTextChangedDuringInputModeSwitch; // ivar: _isCallingTextChangedDuringInputModeSwitch
@property (readonly, nonatomic) BOOL isDefaultPrediction;
@property (readonly, nonatomic) BOOL isRotating;
@property (readonly, nonatomic) BOOL isSettingDelegate;
@property (readonly, nonatomic) TIKeyboardState *keyboardState; // ivar: m_keyboardState
@property (nonatomic) NSUInteger lastChooseSupplementalItemToInsertCallbackIdentifier; // ivar: m_lastChooseSupplementalItemToInsertCallbackIdentifier
@property (nonatomic) NSUInteger lastDeletionCountForFastDelete; // ivar: _lastDeletionCountForFastDelete
@property (retain, nonatomic) _UIStringAndPositionPair *lastMatchedSupplementalCandidate; // ivar: m_lastMatchedSupplementalCandidate
@property (retain, nonatomic) TIKeyboardLayout *layoutForKeyHitTest;
@property (getter=isFloatingLocked) BOOL lockFloating; // ivar: _lockFloating
@property (readonly) NSUInteger minimumTouchesForTranslation;
@property (readonly, nonatomic) BOOL needAutofillLogin;
@property (retain, nonatomic) _UIStringAndPositionPair *pendingSupplementalCandidateToInsert; // ivar: m_pendingSupplementalCandidateToInsert
@property (nonatomic) BOOL performingRemoteTextOperations; // ivar: performingRemoteTextOperations
@property (nonatomic) BOOL prewarmsPredictiveCandidates;
@property (nonatomic) BOOL receivedCandidatesInCurrentInputMode; // ivar: m_receivedCandidatesInCurrentInputMode
@property (readonly, nonatomic) UIKBRTIPartner *remoteTextInputPartner;
@property (nonatomic) NSUInteger requestedInteractionModel; // ivar: _requestedInteractionModel
@property (retain, nonatomic) NSUUID *resigningRTISessionIdentifier; // ivar: _resigningRTISessionIdentifier
@property BOOL rivenSplitLock;
@property (readonly, nonatomic) UITextSelectionView *selectionView;
@property (nonatomic) NSUInteger serviceRole;
@property (nonatomic) BOOL shouldIgnoreTextInputChanges; // ivar: m_textInputChangesIgnored
@property (readonly, nonatomic) BOOL shouldShowCandidateBar;
@property (nonatomic) BOOL shouldSkipCandidateSelection;
@property (nonatomic) BOOL shouldUpdateLayoutAutomatically; // ivar: _shouldUpdateLayoutAutomatically
@property (nonatomic) BOOL showInputModeIndicator; // ivar: m_showInputModeIndicator
@property (nonatomic) BOOL showsCandidateBar; // ivar: m_showsCandidateBar
@property (nonatomic) BOOL showsCandidateInline; // ivar: m_showsCandidateInline
@property (readonly, nonatomic) TISmartPunctuationController *smartPunctuationController; // ivar: m_smartPunctuationController
@property (readonly, nonatomic) BOOL splitTransitionInProgress;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (nonatomic) BOOL suppressUpdateAssistantView; // ivar: _suppressUpdateAssistantView
@property (nonatomic) BOOL suppressUpdateInputMode; // ivar: _suppressUpdateInputMode
@property (nonatomic) BOOL suppressUpdateLayout; // ivar: m_suppressUpdateLayout
@property (nonatomic) BOOL suppressUpdateShiftState; // ivar: m_suppressUpdateShiftState
@property (nonatomic) BOOL syncingDictationLanguageForInputModeSwitch; // ivar: syncingDictationLanguageForInputModeSwitch
@property (readonly, nonatomic) UIKeyboardTaskQueue *taskQueue;
@property (readonly, nonatomic) UITextInteractionAssistant *textInteractionAssistant;
@property (retain, nonatomic) _UIKeyboardTextSelectionController *textSelectionController; // ivar: _textSelectionController
@property (readonly, nonatomic) CGFloat timestampOfLastTouchesEnded;
@property (retain, nonatomic) TIKeyboardTouchEvent *touchEventWaitingForKeyInputEvent; // ivar: m_touchEventWaitingForKeyInputEvent
@property (retain, nonatomic) UIDelayedAction *updateCapsLockDelayOverrideForNonTyping; // ivar: m_updateCapsLockDelayOverrideForNonTyping
@property (readonly, nonatomic) BOOL updatingPreferences; // ivar: m_updatingPreferences
@property (weak, nonatomic) NSObject<_UITextInputUserInteractionDelegate> *userInteractionDelegate; // ivar: _userInteractionDelegate
@property (copy, nonatomic) id *waitingOnPerformAutocorrect; // ivar: _waitingOnPerformAutocorrect


+(BOOL)isActivatingForeground;
+(BOOL)isDictationPopoverEnabled;
+(BOOL)isFloating;
+(BOOL)isFloatingForced;
+(BOOL)isHardwareCommandKeyBeingHeld;
+(BOOL)isHardwareShiftKeyBeingHeld;
+(BOOL)isSplit;
+(BOOL)keyboardOrientation:(NSInteger)arg0 isEquivalentToOrientation:(NSInteger)arg1 ;
+(BOOL)overrideNativeScreen;
+(BOOL)rivenInstalled;
+(BOOL)rivenPreference;
+(BOOL)rivenShouldUndock;
+(BOOL)rivenTranslationPreference;
+(BOOL)shouldMergeAssistantBarWithKeyboardLayout;
+(BOOL)showsGlobeAndDictationKeysExternally;
+(BOOL)smartInsertDeleteIsEnabled;
+(BOOL)supportsFloating;
+(BOOL)supportsSplit;
+(CGFloat)additionalInstanceHeight;
+(CGFloat)additionalInstanceHeightForInterfaceOrientation:(NSInteger)arg0 ;
+(CGFloat)additionalInstanceHeightForInterfaceOrientation:(NSInteger)arg0 hasInputView:(BOOL)arg1 ;
+(CGFloat)floatingHeight;
+(CGFloat)floatingScreenWidthToEmulate;
+(CGFloat)floatingWidth;
+(CGFloat)keyboardWidthForScreen:(id)arg0 withOrientation:(NSInteger)arg1 ;
+(CGFloat)persistentSplitProgress;
+(CGFloat)splitProgress;
+(CGFloat)topMarginForInterfaceOrientation:(NSInteger)arg0 ;
+(Class)layoutClassForCurrentInputMode;
+(Class)layoutClassForInputMode:(id)arg0 keyboardType:(NSInteger)arg1 screenTraits:(id)arg2 ;
+(NSInteger)floatingIdiom;
+(id)activeInstance;
+(id)keyboardScreen;
+(id)keyboardWindow;
+(id)normalizedInputModesFromPreference;
+(id)sharedInstance;
+(id)sharedInstanceForCustomInputView:(BOOL)arg0 ;
+(id)uniqueNumberPadInputModesFromInputModes:(id)arg0 forKeyboardType:(NSInteger)arg1 ;
+(struct CGPoint )_normalizedScreenPoint:(struct CGPoint )arg0 ;
+(struct CGPoint )_screenPointFromNormalizedPoint:(struct CGPoint )arg0 ;
+(struct CGPoint )defaultUndockedOffsetForFloating:(BOOL)arg0 ;
+(struct CGPoint )floatingNormalizedPersistentOffset;
+(struct CGPoint )floatingPersistentOffset;
+(struct CGPoint )normalizedPersistentOffset;
+(struct CGPoint )normalizedPersistentOffsetIgnoringState;
+(struct CGPoint )persistentOffset;
+(struct CGSize )defaultSizeForInterfaceOrientation:(NSInteger)arg0 ;
+(struct CGSize )keyboardSizeForInterfaceOrientation:(NSInteger)arg0 ;
+(struct CGSize )sizeForInterfaceOrientation:(NSInteger)arg0 ;
+(struct CGSize )sizeForInterfaceOrientation:(NSInteger)arg0 ignoreInputView:(BOOL)arg1 ;
+(struct UIEdgeInsets )deviceSpecificPaddingForInterfaceOrientation:(NSInteger)arg0 inputMode:(id)arg1 ;
+(struct UIEdgeInsets )deviceSpecificStaticHitBufferForInterfaceOrientation:(NSInteger)arg0 inputMode:(id)arg1 ;
+(struct UIEdgeInsets )requestedFloatingInsets;
+(void)_clearHardwareKeyboardMinimizationPreference;
+(void)applicationDidBecomeActive:(id)arg0 ;
+(void)applicationDidEnterBackground:(id)arg0 ;
+(void)applicationDidReceiveMemoryWarning:(id)arg0 ;
+(void)applicationWillEnterForeground:(id)arg0 ;
+(void)applicationWillResignActive:(id)arg0 ;
+(void)applicationWillSuspend:(id)arg0 ;
+(void)performWithoutFloatingLock:(id)arg0 ;
+(void)purgeImageCache;
+(void)refreshRivenStateWithTraits:(id)arg0 isKeyboard:(BOOL)arg1 ;
+(void)releaseSharedInstance;
+(void)sendPerformanceNotification:(id)arg0 ;
+(void)sendPerformanceNotification:(id)arg0 userInfo:(id)arg1 ;
+(void)setFloating:(BOOL)arg0 ;
+(void)setFloating:(BOOL)arg0 positionedAtDefaultOffsetAnimated:(BOOL)arg1 ;
+(void)setFloating:(BOOL)arg0 positionedAtOffset:(struct CGPoint )arg1 animated:(BOOL)arg2 ;
+(void)setFloatingPersistentOffset:(struct CGPoint )arg0 ;
+(void)setParentTestForProfiling:(id)arg0 ;
+(void)setPersistentOffset:(struct CGPoint )arg0 ;
+(void)setPersistentSplitProgress:(CGFloat)arg0 ;
+(void)suppressSetPersistentOffset:(BOOL)arg0 ;
+(void)switchControlStatusDidChange:(id)arg0 ;
-(BOOL)_canDeleteForward;
-(BOOL)_canHandleResponderCommand:(SEL)arg0 ;
-(BOOL)_canHandleResponderCommandConservatively:(SEL)arg0 ;
-(BOOL)_cancelOperation:(BOOL)arg0 testOnly:(BOOL)arg1 ;
-(BOOL)_containsUsernamePasswordPairsInAutofillGroup:(id)arg0 ;
-(BOOL)_handleKeyCommand:(id)arg0 ;
-(BOOL)_handleKeyInputMethodCommandForEvent:(id)arg0 canHandleAppKeyCommand:(BOOL)arg1 ;
-(BOOL)_handlesKeyCommandForEvent:(id)arg0 ;
-(BOOL)_hasCandidates;
-(BOOL)_insertSupplementalCandidate:(id)arg0 overridingCandidateText:(id)arg1 ;
-(BOOL)_isKeyCommand:(id)arg0 ;
-(BOOL)_isShowingCandidateUIWithAvailableCandidates;
-(BOOL)_isShowingSuggestionForKeyboardCamera;
-(BOOL)_isValidKeyInput:(id)arg0 ;
-(BOOL)_needsCandidates;
-(BOOL)_shouldEmitString:(id)arg0 forKeyEvent:(id)arg1 ;
-(BOOL)_shouldLoadPredictionsBasedOnCurrentTraits;
-(BOOL)_shouldMinimizeForHardwareKeyboard;
-(BOOL)_shouldRequestInputManagerSyncForKeyboardOutputCallbacks:(id)arg0 ;
-(BOOL)_shouldSuppressSoftwareKeyboard;
-(BOOL)_shouldSuppressSoftwareKeyboardAndAssistantView;
-(BOOL)_shouldSuppressSoftwareKeyboardForResponder:(id)arg0 ignoringPolicyDelegate:(BOOL)arg1 ;
-(BOOL)_shouldSuppressSoftwareKeyboardIgnoringPolicyDelegate:(BOOL)arg0 ;
-(BOOL)_showsScribbleIconsInAssistantView;
-(BOOL)acceptAutofillExtraCandidateIfNeeded:(id)arg0 ;
-(BOOL)acceptInputString:(id)arg0 ;
-(BOOL)acceptWord:(id)arg0 firstDelete:(NSUInteger)arg1 ;
-(BOOL)acceptWord:(id)arg0 firstDelete:(NSUInteger)arg1 forInput:(id)arg2 ;
-(BOOL)accessibilityUsesExtendedKeyboardPredictionsEnabled;
-(BOOL)allowsReachableKeyboard;
-(BOOL)applyAutocorrection:(id)arg0 ;
-(BOOL)assertTextForRemoteDocument:(id)arg0 withSelectionDelta:(struct _NSRange )arg1 updatingSelection:(BOOL)arg2 ;
-(BOOL)autocapitalizationPreference;
-(BOOL)autocorrectSpellingEnabled;
-(BOOL)autocorrectionPreference;
-(BOOL)callLayoutIgnoresShiftState;
-(BOOL)callLayoutIsGeometricShiftOrMoreKeyForTouch:(id)arg0 ;
-(BOOL)callLayoutIsShiftKeyBeingHeld;
-(BOOL)callLayoutIsShiftKeyPlaneChooser;
-(BOOL)callLayoutUsesAutoShift;
-(BOOL)callShouldDeleteWithWordCountForRapidDelete:(int)arg0 characterCountForRapidDelete:(int)arg1 ;
-(BOOL)callShouldInsertText:(id)arg0 ;
-(BOOL)callShouldInsertText:(id)arg0 onDelegate:(id)arg1 ;
-(BOOL)canHandleDelete;
-(BOOL)canHandleEvent:(id)arg0 ;
-(BOOL)canHandleKeyHitTest;
-(BOOL)canPasteImage;
-(BOOL)canPresentEmojiPopover;
-(BOOL)canPresentOrDismissEmojiPopover;
-(BOOL)canPresentPressAndHoldPopover:(id)arg0 ;
-(BOOL)canShowAppConnections;
-(BOOL)canUseCandidateBarAsSupplementToInlineView;
-(BOOL)candidateSelectionPredictionForTraits;
-(BOOL)capsLockKeyHasLanguageSwitchLabel;
-(BOOL)caretBlinks;
-(BOOL)caretVisible;
-(BOOL)changeNotificationDisabled;
-(BOOL)checkSpellingPreference;
-(BOOL)checkSpellingPreferenceForTraits;
-(BOOL)currentKeyboardTraitsAllowCandidateBarWhileIgnoringHidePredictionTrait:(BOOL)arg0 ;
-(BOOL)cursorIsAtEndOfMarkedText;
-(BOOL)delayedCandidateList;
-(BOOL)deleteForwardAndNotify:(BOOL)arg0 ;
-(BOOL)disableInputBars;
-(BOOL)displaysCandidates;
-(BOOL)dontPushOneTimeCode;
-(BOOL)doubleSpacePeriodPreference;
-(BOOL)editingTraitsMarkedDirty;
-(BOOL)globeKeyDisplaysAsEmojiKey;
-(BOOL)handleCandidateListNavigation:(unsigned int)arg0 hasCandidatesForTypedInput:(BOOL)arg1 shiftDown:(BOOL)arg2 keyCommandTypeHandled:(*NSUInteger)arg3 allowRepeat:(*BOOL)arg4 beforePublic:(BOOL)arg5 keyEvent:(id)arg6 ;
// -(BOOL)handleHorizontalArrow:(BOOL)arg0 shiftDown:(BOOL)arg1 beforePublicKeyCommands:(BOOL)arg2 testOnly:(BOOL)arg3 isVerticalCandidate:(BOOL)arg4 hasCandidatesForTypedInput:(BOOL)arg5 shouldNavigateCandidateList:(BOOL)arg6 canHandleInputDelegateCommand:(id)arg7 savedHistory:(unk)arg8 keyCommandTypeHandled:(id)arg9 keyEvent:(*NSUInteger)arg10  ;
-(BOOL)handleInputManagerBasedKeybind:(id)arg0 testOnly:(BOOL)arg1 ;
-(BOOL)handleInputSwitcherForKeyEvent:(id)arg0 ;
-(BOOL)handleKeyAppCommandForCurrentEvent;
-(BOOL)handleKeyCommand:(id)arg0 repeatOkay:(*BOOL)arg1 beforePublicKeyCommands:(BOOL)arg2 ;
-(BOOL)handleKeyCommandsBeforePublicAsInputUIHost:(id)arg0 ;
-(BOOL)handleKeyInputMethodCommandForCurrentEvent;
-(BOOL)handleKeyTextCommandForCurrentEvent;
// -(BOOL)handleMoveCursorToEndOfLine:(BOOL)arg0 beforePublicKeyCommands:(BOOL)arg1 testOnly:(BOOL)arg2 savedHistory:(id)arg3 force:(BOOL)arg4 canHandleSelectableInputDelegateCommand:(id)arg5 keyEvent:(unk)arg6  ;
// -(BOOL)handleMoveCursorToStartOfLine:(BOOL)arg0 beforePublicKeyCommands:(BOOL)arg1 testOnly:(BOOL)arg2 savedHistory:(id)arg3 force:(BOOL)arg4 canHandleSelectableInputDelegateCommand:(id)arg5 keyEvent:(unk)arg6  ;
-(BOOL)handleMoveResponderWithShift:(BOOL)arg0 ;
-(BOOL)handleReturnKey:(BOOL)arg0 ;
-(BOOL)handleTabWithShift:(BOOL)arg0 ;
-(BOOL)handleTabWithShift:(BOOL)arg0 beforePublicKeyCommands:(BOOL)arg1 ;
-(BOOL)handleTabWithShift:(BOOL)arg0 beforePublicKeyCommands:(BOOL)arg1 isMoveAction:(BOOL)arg2 testOnly:(BOOL)arg3 ;
// -(BOOL)handleVerticalArrow:(BOOL)arg0 shiftDown:(BOOL)arg1 beforePublicKeyCommands:(BOOL)arg2 testOnly:(BOOL)arg3 isVerticalCandidate:(BOOL)arg4 hasCandidatesForTypedInput:(BOOL)arg5 inputDelegateCommandEnabled:(BOOL)arg6 canHandleInputDelegateCommand:(id)arg7 savedHistory:(unk)arg8 keyCommandTypeHandled:(id)arg9 keyEvent:(*NSUInteger)arg10  ;
-(BOOL)hardwareKeyboardAttached;
-(BOOL)hasDelegate;
-(BOOL)hasEditableMarkedText;
-(BOOL)hasMarkedText;
-(BOOL)hideAccessoryViewsDuringSplit;
-(BOOL)inputModeSwitcherVisible;
-(BOOL)inputUIHandleTabWithShift:(BOOL)arg0 testOnly:(BOOL)arg1 ;
-(BOOL)insertTextIfShould:(id)arg0 ;
-(BOOL)insertsSpaceAfterPredictiveInput;
-(BOOL)isAutoDeleteActive;
-(BOOL)isAutoFillMode;
-(BOOL)isAutoShifted;
-(BOOL)isCallingInputDelegate;
-(BOOL)isCapsLockASCIIToggle;
-(BOOL)isCapsLockSwitchEnabled;
-(BOOL)isCurrentEditResponderInEditingMode;
-(BOOL)isCurrentEditResponderWebKit;
-(BOOL)isDictationLanguageMenuPresented;
-(BOOL)isDictationMenuPresented;
-(BOOL)isDictationPopoverPresented;
-(BOOL)isEmojiPopoverBeingDismissed;
-(BOOL)isEmojiPopoverBeingPresented;
-(BOOL)isEmojiPopoverPresented;
-(BOOL)isEmojiPopoverVisibleOrDismissing;
-(BOOL)isInputModeIndicator;
-(BOOL)isLongPress;
-(BOOL)isMemberOfAutofillGroup:(id)arg0 ;
-(BOOL)isMemberOfPossibleAutofillGroup:(id)arg0 ;
-(BOOL)isMinimized;
-(BOOL)isOutOfProcess;
-(BOOL)isPredictionViewControllerVisible;
-(BOOL)isPressAndHoldPopoverPresented;
-(BOOL)isRTIClient;
-(BOOL)isSelectionAtSentenceAutoshiftBoundary;
-(BOOL)isShiftKeyBeingHeld;
-(BOOL)isShiftLocked;
-(BOOL)isShifted;
-(BOOL)isSyncingDictationLanguageForInputModeSwitch;
-(BOOL)isTrackpadMode;
-(BOOL)isUsingDictationLayout;
-(BOOL)keyboardDrawsOpaque;
-(BOOL)keyboardInputModeIndicatorControllerShouldPresentIndicator:(id)arg0 ;
-(BOOL)keyboardIsInPencilTextInputMode;
-(BOOL)keyboardIsKeyPad;
-(BOOL)keyboardLayoutIsInAnotherProcess;
-(BOOL)keyboardsExpandedPreference;
-(BOOL)layoutIsResizing;
-(BOOL)liveConversionEnabled;
-(BOOL)maximizing;
-(BOOL)needOneTimeCodeAutofill;
-(BOOL)needsToDeferUpdateTextCandidateView;
-(BOOL)nextCharacterIsWordCharacter;
-(BOOL)nextInputWouldStartSentence;
-(BOOL)noContent;
-(BOOL)performKeyboardEvent:(id)arg0 ;
-(BOOL)performKeyboardOutput:(id)arg0 checkingDelegate:(BOOL)arg1 forwardToRemoteInputSource:(BOOL)arg2 ;
-(BOOL)playInputClick;
-(BOOL)pointInside:(struct CGPoint )arg0 forEvent:(struct __GSEvent *)arg1 ;
-(BOOL)pointInside:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(BOOL)predictionFromPreference;
-(BOOL)preferFallbackAutofillGroup;
-(BOOL)presentationControllerShouldDismiss:(id)arg0 ;
-(BOOL)returnKeyEnabled;
-(BOOL)shiftLockPreference;
-(BOOL)shiftLockedEnabled;
-(BOOL)shouldAcceptCandidate:(id)arg0 beforeInputString:(id)arg1 ;
-(BOOL)shouldAcceptContinuousPathConversion:(id)arg0 ;
-(BOOL)shouldAllowRepeatEvent:(id)arg0 ;
-(BOOL)shouldAllowSelectionGestures:(BOOL)arg0 atPoint:(struct CGPoint )arg1 toBegin:(BOOL)arg2 ;
-(BOOL)shouldAllowTwoFingerSelectionGestureOnView:(id)arg0 ;
-(BOOL)shouldApplyAcceptedAutocorrection:(id)arg0 ;
-(BOOL)shouldApplyKeyboardCommandToUIHost;
-(BOOL)shouldApplyKeyboardInputToUIHost;
-(BOOL)shouldDeleteAutospaceBeforeTerminator:(id)arg0 ;
-(BOOL)shouldForwardInsertSpaceAfterAcceptingPredictiveInput:(id)arg0 ;
-(BOOL)shouldGenerateCandidatesAfterSelectionChange;
-(BOOL)shouldLoadAutofillSignUpInputViewController;
-(BOOL)shouldPrioritizeTextSuggestionsOverCandidateResultSet:(id)arg0 ;
-(BOOL)shouldRapidDelete;
-(BOOL)shouldRapidDeleteWithDelegate;
-(BOOL)shouldShowCandidateBarIfReceivedCandidatesInCurrentInputMode:(BOOL)arg0 ignoreHidePredictionTrait:(BOOL)arg1 ;
-(BOOL)shouldShowContinuousPathIntroductionView;
-(BOOL)shouldShowDictationKey;
-(BOOL)shouldShowEditingIntroductionView;
-(BOOL)shouldShowInternationalKey;
-(BOOL)shouldShowInternationalKeyIntroduction;
-(BOOL)shouldShowKeyboardMenu;
-(BOOL)shouldShowLongPredictionList;
-(BOOL)shouldShowModelessInputTip;
-(BOOL)shouldSwitchFromInputManagerMode:(id)arg0 toInputMode:(id)arg1 ;
-(BOOL)shouldSwitchInputMode:(id)arg0 ;
-(BOOL)shouldUseCarPlayModes;
-(BOOL)shouldUsePinyinStyleRowNavigation;
-(BOOL)showingEmojiSearch;
-(BOOL)showsDedicatedEmojiKeyAlongsideGlobeButton;
-(BOOL)smartInsertDeleteIsEnabled;
-(BOOL)suppliesCompletions;
-(BOOL)supportsNumberKeySelection;
-(BOOL)suppressOptOutASPCandidateUpdateForDelegate:(id)arg0 ;
-(BOOL)textInputTraitsNeedAutofill;
-(BOOL)textInputTraitsNeedAutofillExcludeOneTimeCodeAndContact;
-(BOOL)textInputTraitsNeedContactAutoFill;
-(BOOL)textInputTraitsNeedOneTimeCode;
-(BOOL)textInputTraitsNeedSignup;
-(BOOL)transitionInProgress;
-(BOOL)uncachedDelegateSupportsImagePaste;
-(BOOL)userSelectedCurrentCandidate;
-(BOOL)usesAutoDeleteWord;
-(BOOL)usesAutocorrectionLists;
-(BOOL)usesCandidateSelection;
-(BOOL)usesContinuousPath;
-(BOOL)usesContinuousPathProgressiveCandidates;
-(BOOL)willDoubleSpacePeriodForInputString:(id)arg0 afterSpace:(BOOL)arg1 elapsedTime:(CGFloat)arg2 ;
-(CGFloat)biasedKeyboardWidthRatio;
-(CGFloat)convertForceToGrams:(CGFloat)arg0 ;
-(CGFloat)lastTouchDownTimestamp;
-(CGFloat)scaleCurrentForceFrom:(CGFloat)arg0 to:(CGFloat)arg1 ;
-(CGFloat)shouldExtendLongPressAction:(id)arg0 ;
-(CGFloat)timeoutForCurrentForce;
-(NSInteger)_needAutofillCandidate:(id)arg0 ;
-(NSInteger)_positionInCandidateList:(id)arg0 ;
-(NSInteger)_textInputSourceForDelegate:(id)arg0 ;
-(NSInteger)adaptivePresentationStyleForPresentationController:(id)arg0 traitCollection:(id)arg1 ;
-(NSInteger)currentHandBias;
-(NSInteger)needAutofill;
-(NSInteger)needAutofillCandidate:(id)arg0 ;
-(NSInteger)preferredCandidateViewTypeForCandidateResultSet:(id)arg0 ;
-(NSUInteger)_clipCornersOfView:(id)arg0 ;
-(NSUInteger)_handleKeyCommandCommon:(id)arg0 options:(NSUInteger)arg1 ;
-(NSUInteger)_updateAutocorrectionPreferenceForTraitsWithCurrentPreference:(BOOL)arg0 ;
-(NSUInteger)autocorrectionPreferenceForTraits;
-(NSUInteger)handleKeyCommand:(id)arg0 repeatOkay:(*BOOL)arg1 options:(NSUInteger)arg2 ;
-(NSUInteger)maxNumberOfProactiveCells;
-(NSUInteger)phraseBoundary;
-(id)UILanguagePreference;
-(id)_activeAssertionController;
-(id)_autofillContext;
-(id)_autofillGroup;
-(id)_contentsOfUsernameField;
-(id)_fallbackAutofillGroup;
-(id)_getAutocorrection;
-(id)_getAutocorrectionList;
-(id)_getCurrentKeyboardName;
-(id)_getCurrentKeyplaneName;
-(id)_getLocalizedInputMode;
-(id)_keyboardBehaviorState;
-(id)_layout;
-(id)_passwordRules;
-(id)_rangeForAutocorrectionText:(id)arg0 ;
-(id)_rangeForSupplementalItemText:(id)arg0 ;
-(id)_remoteAppId;
-(id)_remoteAssociatedDomains;
-(id)_remoteLocalizedAppName;
-(id)_remoteUnlocalizedAppName;
-(id)_sessionIdentifier;
-(id)_supplementalCandidateIcon:(id)arg0 ;
-(id)acceptAutocorrectionForWordTerminator:(id)arg0 ;
-(id)acceptCurrentCandidate;
-(id)acceptCurrentCandidateForInput:(id)arg0 ;
-(id)acceptInlineCandidate;
-(id)acceptInlineCandidateForInput:(id)arg0 ;
-(id)asynchronousInputDelegate;
-(id)attributedText;
-(id)autocorrectPrompt;
-(id)autocorrectPromptRectsForInput:(id)arg0 ;
-(id)autocorrectPromptRectsFromFirstDelegateRect:(struct CGRect )arg0 lastDelegateRect:(struct CGRect )arg1 ;
-(id)autocorrectionRecordForWord:(id)arg0 ;
-(id)buildInputSourceState;
-(id)candidateList;
-(id)currentKey;
-(id)desirableInputModesWithExtensions:(BOOL)arg0 ;
-(id)documentIdentifierForInputDelegate:(id)arg0 ;
-(id)documentState;
-(id)dynamicCaretList;
-(id)editMenuInteraction:(id)arg0 menuForConfiguration:(id)arg1 suggestedActions:(id)arg2 ;
-(id)editMenuTipView;
-(id)emojiCandidate:(id)arg0 ;
-(id)generateAutocorrectionListForSelectedText;
-(id)generateAutocorrectionReplacements:(id)arg0 ;
-(id)handleDeleteAutospaceForInputString:(id)arg0 afterSpace:(BOOL)arg1 ;
-(id)handleReplacement:(id)arg0 forSpaceAndInput:(id)arg1 ;
-(id)hardwareKeyboardsSeenPreference;
-(id)hitTest:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(id)implProxy;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 forCustomInputView:(BOOL)arg1 ;
-(id)inputDelegate;
-(id)inputEventForInputString:(id)arg0 ;
-(id)inputForMarkedText;
-(id)inputModeLastUsedPreference;
-(id)inputModePreference;
-(id)inputOverlayContainer;
-(id)inputOverlayContainerForCandidateView:(BOOL)arg0 ;
-(id)inputStringFromPhraseBoundary;
-(id)inputSystemSourceSession;
-(id)inputWordForTerminatorAtSelection;
-(id)internationalKeyDisplayStringOnEmojiKeyboard;
-(id)keyboardMenuElements;
-(id)keyboardMenuTipIdentifier;
-(id)keyboardWindowSnapshot;
-(id)keyplaneView;
-(id)layoutState;
-(id)markedText;
-(id)markedTextOverlay;
-(id)physicalKeyboardEventWithInput:(id)arg0 inputFlags:(int)arg1 ;
-(id)remoteTextEditingMetadata;
-(id)replacementsFromSelectedText;
-(id)responderForSendCurrentLocation;
-(id)responderStylingTraitsForceEditingMask:(BOOL)arg0 ;
-(id)returnKeyDisplayName;
-(id)searchStringForMarkedText;
-(id)stopDictationMenuElements;
-(id)stopDictationMenuElementsForTextInputView:(id)arg0 ;
-(id)textInputTraits;
-(id)textSelectionControllerForInputDelegate:(id)arg0 ;
-(id)updateKeyBehaviors:(id)arg0 withBehaviors:(id)arg1 forState:(id)arg2 ;
-(id)updateSecureCandidateRenderTraits;
-(id)updatedKeyBehaviors;
-(int)changeCount;
-(int)returnKeyType;
-(int)textInputChangingCount;
-(struct CGRect )convertRectToAutocorrectRect:(struct CGRect )arg0 delegateView:(id)arg1 container:(id)arg2 ;
-(struct CGRect )correctionRect;
-(struct CGRect )dragGestureRectInView:(id)arg0 ;
-(struct CGRect )frameForKeylayoutName:(id)arg0 ;
-(struct CGRect )getCorrectionRectIsVertical:(*BOOL)arg0 ;
-(struct CGRect )subtractKeyboardFrameFromRect:(struct CGRect )arg0 inView:(id)arg1 ;
-(struct CGSize )defaultSizeForInterfaceOrientation:(NSInteger)arg0 ;
-(struct UIEdgeInsets )deviceSpecificPaddingForInterfaceOrientation:(NSInteger)arg0 inputMode:(id)arg1 ;
-(struct UIEdgeInsets )deviceSpecificStaticHitBufferForInterfaceOrientation:(NSInteger)arg0 inputMode:(id)arg1 ;
-(unsigned int)_setAttributedMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 inputString:(id)arg2 lastInputString:(id)arg3 searchString:(id)arg4 compareAttributes:(BOOL)arg5 ;
-(unsigned int)assertIntermediateText:(id)arg0 ;
-(unsigned int)setMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 inputString:(id)arg2 lastInputString:(id)arg3 searchString:(id)arg4 candidateOffset:(NSInteger)arg5 liveConversionSegments:(id)arg6 highlighSegmentIndex:(NSUInteger)arg7 ;
-(void)_acceptAutocorrection;
-(void)_acceptSupplementalCandidate:(id)arg0 completion:(id)arg1 ;
-(void)_addInputString:(id)arg0 withFlags:(NSUInteger)arg1 withInputManagerHint:(id)arg2 ;
-(void)_attemptAuthenticationWithMessage:(id)arg0 ;
-(void)_cancelPendingSupplementalCandidateInsertion;
-(void)_clearAutofillGroup;
-(void)_completePerformInputViewControllerOutput:(id)arg0 executionContext:(id)arg1 ;
-(void)_conditionallyNotifyPredictionsAreAvailableForCandidates:(id)arg0 containingProactiveTriggers:(BOOL)arg1 ;
-(void)_deactiveActiveKeys;
-(void)_deleteFromInputWithFlags:(NSUInteger)arg0 ;
-(void)_didChangeKeyplaneWithContext:(id)arg0 ;
-(void)_didReplaceText:(id)arg0 withSupplementalCandidate:(id)arg1 ;
-(void)_didTapTipView:(id)arg0 ;
-(void)_dispatchInsertionPointEnteredText:(id)arg0 range:(id)arg1 withSupplementalCandidate:(id)arg2 ;
-(void)_dispatchInsertionPointExitedRangeWithSupplementalCandidate;
-(void)_dynamicUserInterfaceTraitDidChange;
-(void)_ensureRTIConnection;
-(void)_generateTextSuggestionForKeyboardCamera;
-(void)_handleKeyBehavior:(NSUInteger)arg0 forKeyType:(id)arg1 ;
-(void)_handleKeyEvent:(id)arg0 executionContext:(id)arg1 ;
-(void)_handleWebKeyEvent:(id)arg0 withEventType:(int)arg1 withInputString:(id)arg2 withInputStringIgnoringModifiers:(id)arg3 executionContext:(id)arg4 ;
-(void)_handleWebKeyEvent:(id)arg0 withIndex:(NSUInteger)arg1 inInputString:(id)arg2 ;
-(void)_handleWebKeyEvent:(id)arg0 withIndex:(NSUInteger)arg1 inInputString:(id)arg2 executionContext:(id)arg3 ;
-(void)_handleWebKeyEvent:(id)arg0 withInputString:(id)arg1 executionContext:(id)arg2 ;
-(void)_inputManagerDidGenerateSupplementalCandidates:(id)arg0 ;
-(void)_insertionPointExitedRangeWithSupplementalCandidate;
-(void)_moveWithEvent:(id)arg0 ;
-(void)_nop;
-(void)_performInputViewControllerOutput:(id)arg0 ;
// -(void)_performKeyboardOutput:(id)arg0 respectingForwardingDelegate:(unk)arg1  ;
-(void)_postInputResponderCapabilitiesChangedNotificationWithOutput:(id)arg0 selectionChanged:(BOOL)arg1 ;
-(void)_postInputResponderChangedNotification;
-(void)_presentKeyboardPopoverWithType:(int)arg0 keyString:(id)arg1 popoverController:(id)arg2 textInputView:(id)arg3 caretRect:(struct CGRect )arg4 isVerticalText:(BOOL)arg5 completion:(id)arg6 ;
-(void)_processInputViewControllerKeyboardOutput:(id)arg0 executionContext:(id)arg1 ;
-(void)_remapKeyEvent:(id)arg0 withKeyEventMap:(id)arg1 ;
-(void)_requestInputManagerSync;
-(void)_scheduleInputAdditionOrDeletion:(id)arg0 ;
-(void)_setAutocorrects:(BOOL)arg0 ;
-(void)_setAutofillGroup:(id)arg0 ;
-(void)_setKeyboardInputMode:(id)arg0 userInitiated:(BOOL)arg1 force:(BOOL)arg2 ;
-(void)_setKeyboardInputMode:(id)arg0 userInitiated:(BOOL)arg1 updateIndicator:(BOOL)arg2 force:(BOOL)arg3 executionContext:(id)arg4 ;
-(void)_setNeedsCandidates:(BOOL)arg0 ;
-(void)_setShiftLockedEnabled:(BOOL)arg0 ;
-(void)_setSuggestions:(id)arg0 ;
-(void)_setTransientSelectionModeEnabled:(BOOL)arg0 forInputDelegate:(id)arg1 ;
-(void)_showAutofillExtras;
-(void)_showKeyboardIgnoringPolicyDelegate:(BOOL)arg0 ;
-(void)_stopAutoDeleteAtDocumentStart;
-(void)_suppressSoftwareKeyboardStateChangedIgnoringPolicyDelegate:(BOOL)arg0 ;
-(void)_tagTouchForTypingMenu:(unsigned int)arg0 ;
-(void)_touchIDDismissed;
-(void)_touchIDPresented;
-(void)_updateCanSuggestSupplementalItemsForCurrentSelection;
-(void)_updateDelegateRequiresKeyEventsFromRemoteTextInput;
-(void)_updateExternalDeviceInputSettingForWindow:(id)arg0 ;
-(void)_updateInputViewControllerOutput:(id)arg0 forKeyboardOutput:(id)arg1 ;
-(void)_updateKeyboardConfigurations;
-(void)_updateKeyboardLanguage:(id)arg0 ;
-(void)_updateKeyboardSuppression:(id)arg0 ;
-(void)_updateSoundPreheatingForWindow:(id)arg0 ;
-(void)_updateTextInputPencilSource;
-(void)_wheelChangedWithEvent:(id)arg0 ;
-(void)_willReplaceText:(id)arg0 withSupplementalCandidate:(id)arg1 ;
-(void)acceptAutocorrection;
-(void)acceptAutocorrection:(id)arg0 executionContextPassingTIKeyboardCandidate:(id)arg1 ;
-(void)acceptAutocorrectionAndEndComposition;
-(void)acceptAutocorrectionForWordTerminator:(id)arg0 executionContextPassingTIKeyboardCandidate:(id)arg1 ;
-(void)acceptAutocorrectionWithCompletionHandler:(id)arg0 ;
-(void)acceptCandidate:(id)arg0 ;
-(void)acceptCandidate:(id)arg0 forInput:(id)arg1 ;
-(void)acceptCandidate:(id)arg0 forInput:(id)arg1 executionContext:(id)arg2 ;
-(void)acceptCurrentCandidateIfSelected;
-(void)acceptCurrentCandidateIfSelectedWithExecutionContext:(id)arg0 ;
-(void)acceptFirstCandidate;
-(void)acceptHandwritingCandidate;
-(void)acceptPredictiveInput:(id)arg0 ;
-(void)acceptPredictiveInput:(id)arg0 executionContext:(id)arg1 ;
-(void)acceptRecentInput:(id)arg0 ;
-(void)addInputEvent:(id)arg0 executionContext:(id)arg1 ;
-(void)addInputObject:(id)arg0 ;
-(void)addInputObject:(id)arg0 executionContext:(id)arg1 ;
-(void)addInputString:(id)arg0 ;
-(void)addInputString:(id)arg0 fromVariantKey:(BOOL)arg1 ;
-(void)addInputString:(id)arg0 withFlags:(NSUInteger)arg1 ;
-(void)addInputString:(id)arg0 withFlags:(NSUInteger)arg1 executionContext:(id)arg2 ;
-(void)addInputString:(id)arg0 withFlags:(NSUInteger)arg1 withInputManagerHint:(id)arg2 ;
-(void)addInputString:(id)arg0 withFlags:(NSUInteger)arg1 withInputManagerHint:(id)arg2 executionContext:(id)arg3 ;
-(void)addSupplementalLexicon:(id)arg0 ;
-(void)addWordTerminator:(id)arg0 afterSpace:(BOOL)arg1 afterAcceptingCandidate:(id)arg2 elapsedTime:(CGFloat)arg3 executionContext:(id)arg4 ;
-(void)adjustAutoDeleteTimerForForce:(CGFloat)arg0 ;
-(void)adjustCapsLockDelayOverride;
-(void)adjustPhraseBoundaryInForwardDirection:(BOOL)arg0 granularity:(int)arg1 executionContext:(id)arg2 ;
-(void)adjustSegmentSize:(NSInteger)arg0 ;
-(void)animateAutocorrectionToRect:(struct CGRect )arg0 fromRect:(struct CGRect )arg1 ;
-(void)animateAutocorrectionToText:(id)arg0 fromRect:(struct CGRect )arg1 ;
-(void)applicationResumed:(id)arg0 ;
-(void)applicationResumedEventsOnly:(id)arg0 ;
-(void)applicationSuspendedEventsOnly:(id)arg0 ;
-(void)applyAssistantItem:(id)arg0 ;
-(void)assertTextForDictation;
-(void)autocorrectionAnimationDidStopWithAutocorrectionView:(id)arg0 ;
-(void)beginFloatingTransitionFromPanGestureRecognizer:(id)arg0 ;
-(void)callChanged;
-(void)callLayoutLongPressAction;
-(void)callLayoutSetAutoshift:(BOOL)arg0 ;
-(void)callLayoutSetShift:(BOOL)arg0 ;
-(void)callLayoutUpdateAllLocalizedKeys;
-(void)callLayoutUpdateLocalizedKeys;
-(void)callLayoutUpdateRecentInputs;
-(void)callLayoutUpdateReturnKey;
-(void)cancelAllKeyEvents;
-(void)cancelCandidateRequests;
-(void)cancelDictationOnSendReturnKeyPressed;
-(void)cancelSplitTransition;
-(void)candidateBarDidExtendWithGesture;
-(void)candidateListAcceptCandidate:(id)arg0 ;
-(void)candidateListInvalidateSelection:(id)arg0 ;
-(void)candidateListSelectionDidChange:(id)arg0 ;
-(void)changingContextWithTrigger:(id)arg0 ;
-(void)cleanUpBeforeInputModeSwitch;
-(void)cleanupKeyboardPopover:(id)arg0 ;
-(void)clearAnimations;
-(void)clearAutoDeleteTimer;
-(void)clearAutocorrectPromptTimer;
-(void)clearAutofillGroup;
-(void)clearCapsLockDelayOverrideTimer;
-(void)clearChangeTimeAndCount;
-(void)clearDelayDeleteTimer;
-(void)clearDelegate;
-(void)clearDetachHardwareKeyboardAction;
-(void)clearDictationMenuTimer;
-(void)clearExcessKeyboardMemory;
-(void)clearForwardingInputDelegateAndResign:(BOOL)arg0 ;
-(void)clearIdleDetectionAction;
-(void)clearInput;
-(void)clearInputForMarkedText;
-(void)clearInputWithCandidatesCleared:(BOOL)arg0 ;
-(void)clearKeyboardWindowSnapshot;
-(void)clearLanguageIndicator;
-(void)clearLayouts;
-(void)clearLongPressTimer;
-(void)clearRecentInput;
-(void)clearSelection;
-(void)clearShiftState;
-(void)clearTextAlternativesRange;
-(void)clearTimers;
-(void)clearTransientState;
-(void)clearUpdateLastUsedInputModeAction;
-(void)collapseSelection;
-(void)completeAcceptCandidate:(id)arg0 ;
-(void)completeAcceptCandidateBeforeAddingInputObject:(id)arg0 executionContext:(id)arg1 ;
-(void)completeAddInputString:(id)arg0 ;
-(void)completeAddInputString:(id)arg0 generateCandidates:(BOOL)arg1 ;
-(void)completeDelete;
-(void)completeDeleteFromInput;
-(void)completeDeleteOnceFromInputWithCharacterBefore:(unsigned int)arg0 ;
-(void)completeHandleAutoDelete;
-(void)completeHandleKeyEvent:(id)arg0 ;
-(void)completeUpdateForChangedSelection:(BOOL)arg0 ;
-(void)configureTipViewWithTitle:(id)arg0 description:(id)arg1 ;
-(void)copyOperation;
-(void)createTypoTrackerReport;
-(void)cutOperation;
-(void)deactivateLayout;
-(void)dealloc;
-(void)defaultsDidChange;
-(void)delayedInit;
-(void)deleteBackward;
-(void)deleteBackwardAndNotify:(BOOL)arg0 ;
-(void)deleteBackwardAndNotify:(BOOL)arg0 reinsertText:(BOOL)arg1 ;
-(void)deleteFromInput;
-(void)deleteFromInputWithFlags:(NSUInteger)arg0 ;
-(void)deleteFromInputWithFlags:(NSUInteger)arg0 executionContext:(id)arg1 ;
-(void)deleteHandwritingStrokesAtIndexes:(id)arg0 ;
-(void)deleteOnceFromInputWithExecutionContext:(id)arg0 ;
-(void)detach;
-(void)detachHardwareKeyboard;
-(void)didAcceptAutocorrection:(id)arg0 wordTerminator:(id)arg1 ;
-(void)didApplyAutocorrection:(id)arg0 autocorrectPromptFrame:(struct CGRect )arg1 ;
-(void)didChangeForwardingInputDelegate:(id)arg0 ;
-(void)didChangePhraseBoundary;
-(void)didClearText;
-(void)didDismissMemojiCard;
-(void)didMoveToSuperview;
-(void)didMoveToWindow;
-(void)didPresentMemojiCard;
-(void)didSetDelegate;
-(void)disableTransientSelectionMode;
-(void)dismissContinuousPathIntroductionView;
-(void)dismissDictationMenu;
-(void)dismissDictationPopover;
-(void)dismissDictationPopoverAndCancelDictation;
-(void)dismissDictationTip;
-(void)dismissEditingIntroductionView;
-(void)dismissEmojiPopoverBeforeCleanup:(BOOL)arg0 ;
-(void)dismissEmojiPopoverIfNecessaryWithCompletion:(id)arg0 ;
-(void)dismissFloatingKeyboardFromPencilKitIfNeeded;
-(void)dismissInputModeIndicator;
-(void)dismissKeyboard;
-(void)dismissKeyboardPopover:(id)arg0 beforeCleanup:(BOOL)arg1 completion:(id)arg2 ;
-(void)dismissPressAndHoldPopover;
-(void)documentStateFromInputDelegate:(id)arg0 ;
-(void)ejectKeyDown;
-(void)emojiSearchWillInsertEmoji:(id)arg0 forSearchQuery:(id)arg1 ;
-(void)emojiSearchWillInsertEmoji:(id)arg0 forSearchQuery:(id)arg1 selectionMethod:(id)arg2 inputType:(id)arg3 ;
-(void)enable;
-(void)enableTransientInputDelegateSelectionMode;
-(void)enableTransientSelectionMode;
-(void)fadeAutocorrectPrompt;
-(void)finishLayoutChangeWithArguments:(id)arg0 ;
-(void)finishLayoutToCurrentInterfaceOrientation;
-(void)finishSetExtensionInputMode:(id)arg0 didChangeDirection:(BOOL)arg1 ;
-(void)finishSetInputMode:(id)arg0 didChangeDirection:(BOOL)arg1 ;
-(void)finishSetInputModeToNextInPreferredListWithExecutionContext:(id)arg0 withPreviousInputMode:(id)arg1 ;
-(void)finishSetKeyboardInputMode:(id)arg0 previousInputMode:(id)arg1 didChangeDirection:(BOOL)arg2 ;
-(void)finishSplitTransitionWithProgress:(CGFloat)arg0 ;
-(void)finishTextChanged;
-(void)flushDelayedTasks;
-(void)flushTouchEventWaitingForKeyInputEventIfNecessary;
-(void)forceShiftUpdate;
-(void)forceShiftUpdateIfKeyboardStateChanged;
-(void)forwardDictationEvent_cancelDictation;
-(void)forwardDictationEvent_handleTip:(id)arg0 title:(id)arg1 ;
-(void)forwardDictationEvent_movePopoverView:(id)arg0 ;
-(void)forwardDictationEvent_startDictation;
-(void)forwardDictationEvent_stopDictation:(BOOL)arg0 ;
-(void)forwardDictationEvent_stopDictationIgnoreFinalizePhrases;
-(void)forwardDictationEvent_switchToDictationInputModeWithOptions:(id)arg0 ;
-(void)forwardDictationEvent_switchToDictationLanguage:(id)arg0 ;
-(void)forwardDictationEvent_updateIdleDetection:(NSInteger)arg0 ;
-(void)forwardKeyboardCameraEvent_selfDestruct;
-(void)forwardKeyboardCameraEvent_startCameraInput:(id)arg0 ;
-(void)forwardKeyboardCameraEvent_updatePreviewText:(id)arg0 asMarkedText:(BOOL)arg1 ;
-(void)forwardKeyboardEventBackToDestination:(id)arg0 ;
-(void)generateAutocorrectionWithExecutionContext:(id)arg0 ;
-(void)generateAutocorrectionsWithCompletionHandler:(id)arg0 ;
-(void)generateAutofillCandidate;
-(void)generateAutofillCandidateByAddingTask:(BOOL)arg0 ;
-(void)generateCandidates;
-(void)generateCandidatesAsynchronously;
-(void)generateCandidatesAsynchronouslyWithRange:(struct _NSRange )arg0 selectedCandidate:(id)arg1 ;
-(void)generateCandidatesFromReplacements;
-(void)generateCandidatesWithOptions:(int)arg0 ;
// -(void)generateReplacementsForString:(id)arg0 candidatesHandler:(id)arg1 executionContext:(unk)arg2  ;
-(void)geometryChangeDone:(BOOL)arg0 ;
-(void)handleAcceptedCandidate:(id)arg0 executionContext:(id)arg1 ;
-(void)handleAutoDeleteContinuationOnDestinationWithDeletionCount:(NSUInteger)arg0 ;
-(void)handleAutoDeleteWithExecutionContext:(id)arg0 ;
-(void)handleAutofillCredentialSaveIfNeeded:(id)arg0 ;
-(void)handleClear;
-(void)handleClearWithExecutionContext:(id)arg0 ;
-(void)handleClearWithInsertBeforeAdvance:(id)arg0 ;
-(void)handleDelayedActionLongPress:(id)arg0 ;
-(void)handleDelete;
-(void)handleDeleteAsRepeat:(BOOL)arg0 executionContext:(id)arg1 ;
-(void)handleDeleteWithExecutionContext:(id)arg0 ;
-(void)handleDeleteWordWithExecutionContext:(id)arg0 ;
-(void)handleDeletionForCandidate:(id)arg0 ;
-(void)handleDictationForResponderChange;
-(void)handleEmojiInput:(id)arg0 keyboardState:(id)arg1 ;
-(void)handleEmojiPopoverKeyCommand;
-(void)handleEventCallbackFromRemoteDestination_didChooseSupplementalItem:(id)arg0 toReplaceText:(id)arg1 ;
-(void)handleEventFromRemoteDestination_canSuggestSupplementalItemsForCurrentSelection:(BOOL)arg0 ;
-(void)handleEventFromRemoteSource_cancelChooseSupplementalItemToInsert;
-(void)handleEventFromRemoteSource_chooseSupplementalItem:(id)arg0 toReplaceText:(id)arg1 ;
-(void)handleEventFromRemoteSource_insertSupplementalCandidate:(id)arg0 textToCommit:(id)arg1 ;
-(void)handleEventFromRemoteSource_insertionPointEnteredText:(id)arg0 withSupplementalCandidate:(id)arg1 ;
-(void)handleEventFromRemoteSource_insertionPointExitedTextWithSupplementalItems;
-(void)handleIdleDetectionAction;
-(void)handleKeyEvent:(id)arg0 ;
-(void)handleKeyEvent:(id)arg0 executionContext:(id)arg1 ;
-(void)handleKeyWithString:(id)arg0 forKeyEvent:(id)arg1 executionContext:(id)arg2 ;
-(void)handleKeyboardInput:(id)arg0 executionContext:(id)arg1 ;
-(void)handleModifiersChangeForKeyEvent:(id)arg0 executionContext:(id)arg1 ;
-(void)handleObserverCallback;
-(void)handleRemoteDictationEvent_cancelDictation;
-(void)handleRemoteDictationEvent_handleTip:(id)arg0 ;
-(void)handleRemoteDictationEvent_movePopoverView:(id)arg0 ;
-(void)handleRemoteDictationEvent_setEditMenuFrame:(id)arg0 ;
-(void)handleRemoteDictationEvent_startDictation;
-(void)handleRemoteDictationEvent_stopDictation:(BOOL)arg0 ;
-(void)handleRemoteDictationEvent_stopDictationIgnoreFinalizePhrases;
-(void)handleRemoteDictationEvent_switchToDictationInputModeWithOptions:(id)arg0 ;
-(void)handleRemoteDictationEvent_switchToDictationLanguage:(id)arg0 ;
-(void)handleRemoteDictationEvent_updateIdleDetection:(NSInteger)arg0 ;
-(void)handleRemoteIndirectGestureWithState:(id)arg0 ;
-(void)handleRemoteKeyboardCameraEvent_startCameraInput:(id)arg0 ;
-(void)handleStringInput:(id)arg0 withFlags:(NSUInteger)arg1 withInputManagerHint:(id)arg2 executionContext:(id)arg3 ;
-(void)handleUpdateLastUsedInputModeAction:(id)arg0 ;
-(void)handleWebViewCredentialsSaveForWebsiteURL:(id)arg0 user:(id)arg1 password:(id)arg2 passwordIsAutoGenerated:(BOOL)arg3 ;
-(void)hardwareKeyboardAvailabilityChanged;
-(void)hardwareKeyboardAvailabilityDidChange:(id)arg0 ;
-(void)hideDictationMenuIfNeeded:(BOOL)arg0 ;
-(void)hideInternationalKeyIntroductionIfNeeded;
-(void)hideKeyboard;
-(void)hideKeyboardIgnoringHardwareLayouts:(BOOL)arg0 ;
-(void)hideKeyboardWithoutPreflightChecks;
-(void)inputManagerDidGenerateAutocorrections:(id)arg0 executionContext:(id)arg1 ;
-(void)inputManagerDidGenerateAutocorrections:(id)arg0 forPredictiveInput:(id)arg1 executionContext:(id)arg2 ;
-(void)inputManagerDidGenerateCandidatesForRequest:(id)arg0 resultSet:(id)arg1 ;
-(void)insertAttributedText:(id)arg0 ;
-(void)insertCustomTextSuggestion:(id)arg0 ;
-(void)insertDictationResult:(id)arg0 ;
-(void)insertText:(id)arg0 withAlternativePredictions:(id)arg1 ;
-(void)insertTextSuggestionCandidate:(id)arg0 ;
-(void)insertedAccentVariantFromPopover:(id)arg0 ;
-(void)insertedEmojiFromPopover:(id)arg0 selectionMethod:(id)arg1 ;
-(void)jumpToCompositions;
-(void)keyActivated;
-(void)keyDeactivated;
-(void)keyboardDidHide:(id)arg0 ;
-(void)keyboardInputModeIndicatorControllerDismissIndicator:(id)arg0 ;
-(void)keyboardInputModeIndicatorControllerPresentIndicator:(id)arg0 ;
-(void)layoutDidResize;
-(void)layoutHasChanged;
-(void)layoutSubviews;
-(void)logHandwritingData;
-(void)longPressAction;
-(void)longPressAction:(id)arg0 ;
-(void)lookUpResponderChainForCustomInputView;
-(void)moveCursorByAmount:(NSInteger)arg0 ;
-(void)moveCursorLeftShifted:(BOOL)arg0 ;
-(void)moveCursorRightShifted:(BOOL)arg0 ;
-(void)movePhraseBoundaryToDirection:(NSInteger)arg0 granularity:(NSInteger)arg1 ;
-(void)nonDestructivelyDismissKeyboard;
-(void)notifyInputSourceStateChangeIfNeeded;
-(void)notifyShiftState;
-(void)optOutASPInTextField;
-(void)pasteOperation;
-(void)pauseDictationForResponderChange;
-(void)performAutoDeleteNumberOfTimes:(NSUInteger)arg0 deleteOneWord:(BOOL)arg1 forwardToInputSource:(BOOL)arg2 ;
-(void)performBlockWithTextInputChangesIgnoredForNonMacOS:(id)arg0 ;
-(void)performDelete;
-(void)performHitTestForTouchEvent:(id)arg0 executionContextPassingNSNumber:(id)arg1 ;
-(void)performHitTestForTouchEvents:(id)arg0 executionContextPassingNSNumber:(id)arg1 ;
-(void)performKeyBehaviorCommitInline;
-(void)performKeyBehaviorConfirm;
-(void)performKeyBehaviorConfirmFirstCandidate;
-(void)performKeyboardOutput:(id)arg0 ;
-(void)performKeyboardOutput:(id)arg0 checkingDelegate:(BOOL)arg1 ;
-(void)performKeyboardOutput:(id)arg0 forwardToRemoteInputSource:(BOOL)arg1 ;
-(void)performKeyboardOutputAsInputViewControllerOutput:(id)arg0 ;
-(void)performKeyboardOutputAsInputViewControllerOutput:(id)arg0 textInputSource:(NSInteger)arg1 ;
-(void)performKeyboardOutputAsRTIClient:(id)arg0 ;
-(void)performKeyboardOutputInfo:(id)arg0 ;
-(void)performKeyboardOutputOnInputSourceSession:(id)arg0 ;
-(void)performOnInputSourceSessionActionSelector:(SEL)arg0 ;
// -(void)performOperations:(id)arg0 withTextInputSource:(unk)arg1  ;
-(void)performReturn;
-(void)performSendAction;
-(void)performSendCurrentLocation;
-(void)performStopAutoDeleteAtDocumentStart;
-(void)performTextOperationActionSelector:(SEL)arg0 ;
-(void)playDeleteKeyFeedbackIfNecessaryRepeat:(BOOL)arg0 rapid:(BOOL)arg1 ;
-(void)playDeleteKeyFeedbackRepeat:(BOOL)arg0 rapid:(BOOL)arg1 ;
-(void)popoverPresentationController:(id)arg0 willRepositionPopoverToRect:(struct CGRect *)arg1 inView:(*id)arg2 ;
-(void)postInputResponderCapabilitiesChangedNotification;
-(void)postInputViewControllerShouldUpdateNotification:(id)arg0 ;
-(void)prepareForFloatingTransition:(BOOL)arg0 ;
-(void)prepareForGeometryChange;
-(void)prepareForSelectionChange;
-(void)prepareKeyboardInputModeFromPreferences:(id)arg0 ;
-(void)prepareLayoutForInterfaceOrientation:(NSInteger)arg0 ;
-(void)presentContinuousPathIntroductionView;
-(void)presentDictationMenu;
-(void)presentDictationMenu:(id)arg0 ;
-(void)presentDictationMenuTipWithTitle:(id)arg0 description:(id)arg1 ;
-(void)presentDictationPopover;
-(void)presentEditingIntroductionView;
-(void)presentEmojiPopoverViaTrigger:(id)arg0 completion:(id)arg1 ;
-(void)presentKeyboardMenu:(int)arg0 ;
-(void)presentKeyboardPopoverWithType:(int)arg0 keyString:(id)arg1 completion:(id)arg2 ;
-(void)presentPressAndHoldPopoverWithKeyString:(id)arg0 ;
-(void)presentationControllerDidDismiss:(id)arg0 ;
-(void)proceedShouldReturnIfNeededForASP;
-(void)processPayloadInfo:(id)arg0 ;
-(void)provideAutoFillTypingUpdatesIfNecessary;
-(void)pushAutocorrections:(id)arg0 requestToken:(id)arg1 ;
-(void)queueDelayedTask:(id)arg0 ;
-(void)recomputeActiveInputModesWithExtensions:(BOOL)arg0 ;
-(void)recomputeActiveInputModesWithExtensions:(BOOL)arg0 allowNonLinguisticInputModes:(BOOL)arg1 ;
-(void)refreshAutofillModeIfNecessary;
-(void)refreshKeyboardState;
-(void)refreshKeyboardStateUpdatingSecureCandidateRenderTraits:(BOOL)arg0 ;
-(void)refreshRivenPreferences;
-(void)refreshSecureCandidatesIfNecessary;
-(void)reinitializeAfterInputModeSwitch:(BOOL)arg0 ;
-(void)rejectAutocorrection:(id)arg0 ;
-(void)releaseInputManager;
-(void)releaseInputManagerIfInactive;
-(void)releaseSuppressUpdateCandidateView;
-(void)reloadCurrentInputMode;
-(void)remoteControlReceivedWithEvent:(id)arg0 ;
-(void)removeASPVisualEffectsIfNecessary:(id)arg0 ;
-(void)removeAllDynamicDictionaries;
-(void)removeAutocorrectPrompt;
-(void)removeAutocorrectPromptAndCandidateList;
-(void)removeAutocorrection;
-(void)removeCandidateList;
-(void)removeCapsLockDelayOverride;
-(void)removeFromSuperview;
-(void)removeRecentInput:(id)arg0 completionHandler:(id)arg1 ;
-(void)removeSpaceAfterEmojiForInputString:(id)arg0 ;
-(void)removeSupplementalLexicon:(id)arg0 ;
-(void)replaceAllTextInResponder:(id)arg0 withText:(id)arg1 ;
-(void)replaceText:(id)arg0 ;
-(void)representDictationMenu;
-(void)resetInputDelegate;
-(void)responseContextDidChange;
-(void)restoreFocusFromEntryPoint:(struct CGPoint )arg0 ;
-(void)resumeDictationForResponderChange;
-(void)revealHiddenCandidates;
-(void)saveInputModesPreference:(id)arg0 ;
-(void)scheduleReplacementsAfterDeletionToEndOfWord;
-(void)scheduleReplacementsWithOptions:(NSUInteger)arg0 ;
-(void)scribbleWillBeginWriting:(id)arg0 ;
-(void)selectionDidChange:(id)arg0 ;
-(void)selectionScrolling:(id)arg0 ;
-(void)selectionWillChange:(id)arg0 ;
-(void)sendCallbacksForPostCorrectionsRemoval;
-(void)sendCallbacksForPreCorrectionsDisplay;
-(void)sendKeyboardDismissalNotification;
-(void)setAttributedMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 inputString:(id)arg2 searchString:(id)arg3 ;
-(void)setAutocorrectSpellingEnabled:(BOOL)arg0 ;
-(void)setAutocorrection:(id)arg0 ;
-(void)setAutocorrectionList:(id)arg0 ;
-(void)setCandidateList:(id)arg0 ;
-(void)setCandidates:(id)arg0 ;
-(void)setCapsLockIfNeeded;
-(void)setCapsLockSign;
-(void)setCaretBlinks:(BOOL)arg0 ;
-(void)setCaretVisible:(BOOL)arg0 ;
-(void)setChangeNotificationDisabled:(BOOL)arg0 ;
-(void)setChanged;
-(void)setCorrectionLearningAllowed:(BOOL)arg0 ;
-(void)setDefaultTextInputTraits:(id)arg0 ;
-(void)setDocumentState:(id)arg0 ;
-(void)setDocumentStateForAutocorrection:(id)arg0 ;
-(void)setEditMenuFrame:(struct CGRect )arg0 ;
-(void)setEditingTraitsMarkedDirty:(BOOL)arg0 ;
-(void)setFrame:(struct CGRect )arg0 ;
-(void)setHardwareKeyboardsSeenPreference:(id)arg0 ;
-(void)setInSplitKeyboardMode:(BOOL)arg0 ;
-(void)setInitialDirection;
-(void)setInputMode:(id)arg0 ;
-(void)setInputMode:(id)arg0 userInitiated:(BOOL)arg1 ;
-(void)setInputMode:(id)arg0 userInitiated:(BOOL)arg1 updateIndicator:(BOOL)arg2 executionContext:(id)arg3 ;
-(void)setInputModeFromPreferences;
-(void)setInputModeSwitcherVisibleInRemote:(BOOL)arg0 ;
-(void)setInputModeToNextASCIICapableInPreferredList;
-(void)setInputModeToNextInPreferredListWithExecutionContext:(id)arg0 ;
-(void)setInputPoint:(struct CGPoint )arg0 ;
-(void)setKeyboardInputMode:(id)arg0 userInitiated:(BOOL)arg1 ;
-(void)setKeyboardInputMode:(id)arg0 userInitiated:(BOOL)arg1 updateIndicator:(BOOL)arg2 executionContext:(id)arg3 ;
-(void)setKeyboardInputModeFromPreferences:(id)arg0 ;
-(void)setKeyboardMinimizedByDictation:(BOOL)arg0 ;
-(void)setLabel:(id)arg0 forKey:(id)arg1 ;
-(void)setLayoutAllowsContinuousPath:(BOOL)arg0 ;
-(void)setLayoutRenderConfig:(id)arg0 ;
-(void)setOverrideTextInputTraits:(id)arg0 ;
-(void)setPendingAutofillIndex:(NSInteger)arg0 ;
-(void)setPreviousGlobeKeyEvent:(id)arg0 ;
-(void)setPreviousInputString:(id)arg0 ;
-(void)setRemoteDelegateSupportsImagePaste:(BOOL)arg0 ;
-(void)setRemoteDictationPopover:(id)arg0 ;
-(void)setReturnKeyEnabled:(BOOL)arg0 ;
-(void)setSelectionWithPoint:(struct CGPoint )arg0 ;
-(void)setShift:(BOOL)arg0 ;
-(void)setShift:(BOOL)arg0 autoshift:(BOOL)arg1 ;
-(void)setShiftLocked:(BOOL)arg0 ;
-(void)setShiftLockedForced:(BOOL)arg0 ;
-(void)setShiftNeedsUpdate;
-(void)setShiftOffIfNeeded;
-(void)setShiftPreventAutoshift:(BOOL)arg0 ;
-(void)setShouldUpdateCacheOnInputModesChange:(BOOL)arg0 ;
-(void)setSplit:(BOOL)arg0 animated:(BOOL)arg1 ;
-(void)setSplitProgress:(CGFloat)arg0 ;
-(void)setSuggestions:(id)arg0 ;
-(void)setTextInputChangesIgnored:(BOOL)arg0 ;
-(void)setTwoFingerTapTimestamp:(CGFloat)arg0 ;
-(void)setUserSelectedCurrentCandidate:(BOOL)arg0 ;
-(void)setUsesCandidateSelection:(BOOL)arg0 ;
-(void)showDictationMenuIfNeeded;
-(void)showFirstTextAlternativeWithRangeAdjustment:(NSInteger)arg0 ;
-(void)showInternationalKeyIntroductionIfNeededWithPreviousInputMode:(id)arg0 ;
-(void)showKeyboard;
-(void)showKeyboardIfNeeded;
-(void)showKeyboardWithoutSuppressionPolicy;
-(void)showNextCandidates;
-(void)showNextPage;
-(void)showPreviousCandidate;
-(void)showSelectionCommands;
-(void)showTextAlternativesInRange:(struct _NSRange )arg0 ;
-(void)skipHitTestForTouchEvent:(id)arg0 ;
-(void)skipHitTestForTouchEvent:(id)arg0 delayed:(BOOL)arg1 ;
-(void)skipHitTestForTouchEvents:(id)arg0 ;
-(void)smartSelectionForTextInDocument:(id)arg0 inRange:(struct _NSRange )arg1 options:(NSUInteger)arg2 completion:(id)arg3 ;
-(void)startAutoDeleteTimer;
-(void)startAutoDeleteTimerForForce:(CGFloat)arg0 ;
-(void)startDelayDeleteTimer;
-(void)stopAutoDelete;
-(void)syncDocumentStateToInputDelegate;
-(void)syncDocumentStateToInputDelegateWithExecutionContext:(id)arg0 ;
-(void)syncInputManagerToAcceptedAutocorrection:(id)arg0 forInput:(id)arg1 ;
-(void)syncInputManagerToKeyboardState;
-(void)syncInputManagerToKeyboardStateWithExecutionContext:(id)arg0 ;
-(void)syncKeyboardToConfiguration:(id)arg0 ;
-(void)takeTextInputTraitsFromDelegate;
-(void)textAccepted:(id)arg0 ;
-(void)textAccepted:(id)arg0 executionContext:(id)arg1 ;
-(void)textChanged:(id)arg0 ;
-(void)textChanged:(id)arg0 executionContext:(id)arg1 ;
-(void)textDidChange:(id)arg0 ;
-(void)textFrameChanged:(id)arg0 ;
-(void)textSuggestionDidChange:(id)arg0 ;
-(void)textWillChange:(id)arg0 ;
-(void)toggleShift;
-(void)toggleSoftwareKeyboard;
-(void)touchAutoDeleteTimerWithThreshold:(CGFloat)arg0 adjustForPartialCompletion:(BOOL)arg1 ;
-(void)touchAutocorrectPromptTimer;
-(void)touchDelayDeleteTimerWithThreshold:(CGFloat)arg0 ;
-(void)touchDictationMenuTimer;
-(void)touchDictationMenuTimer:(BOOL)arg0 ;
-(void)touchLongPressTimer;
-(void)touchLongPressTimerWithDelay:(CGFloat)arg0 ;
-(void)touchLongPressTimerWithDelay:(CGFloat)arg0 userInfo:(id)arg1 ;
-(void)touchUpdateLastUsedInputModeAction;
-(void)trackResponderForAutofillIfNeeded:(id)arg0 ;
-(void)trackUsageForAcceptedAutocorrection:(id)arg0 promptWasShowing:(BOOL)arg1 ;
-(void)trackUsageForCandidateAcceptedAction:(id)arg0 ;
-(void)trackUsageForPromptedCorrection:(id)arg0 inputString:(id)arg1 previousPrompt:(id)arg2 ;
-(void)traitCollectionDidChange;
-(void)unmarkText:(id)arg0 ;
-(void)updateAssistantView;
-(void)updateAssistantViewInfo:(id)arg0 ;
-(void)updateAutocorrectContainerWithAutocorrection:(id)arg0 parentView:(id)arg1 correctionRects:(id)arg2 ;
-(void)updateAutocorrectPrompt:(id)arg0 ;
-(void)updateAutocorrectPrompt:(id)arg0 correctionRects:(id)arg1 ;
-(void)updateAutocorrectPrompt:(id)arg0 executionContext:(id)arg1 ;
-(void)updateCandidateDisplay;
-(void)updateCandidateDisplayAsyncWithCandidateSet:(id)arg0 ;
-(void)updateChangeTimeAndIncrementCount;
-(void)updateDefaultsWithResults:(id)arg0 ;
-(void)updateDelegatePasteSupport;
-(void)updateDictationPopoverLocationForCandidateInlineView:(id)arg0 yOffset:(CGFloat)arg1 ;
-(void)updateDictationPopoverLocationIfNeeded;
-(void)updateDocumentViewsAfterKeyboardOutput:(id)arg0 ;
-(void)updateDoubleSpacePeriodStateForCharacter:(unsigned int)arg0 ;
-(void)updateDoubleSpacePeriodStateForString:(id)arg0 ;
-(void)updateForChangedSelection;
-(void)updateForChangedSelectionWithExecutionContext:(id)arg0 ;
-(void)updateForHandBiasChange;
-(void)updateFromTextInputTraits;
-(void)updateHardwareKeyboardLayout;
-(void)updateHardwareKeyboardLayout:(BOOL)arg0 ;
-(void)updateIdleDetection:(NSInteger)arg0 ;
-(void)updateInputAssistantButtonItems;
-(void)updateInputDelegateForRemoteDocumentStateChange:(id)arg0 selectedTextRange:(struct _NSRange )arg1 forceSync:(BOOL)arg2 ;
-(void)updateInputDelegateForRemoteTraitChange:(id)arg0 forceSync:(BOOL)arg1 ;
-(void)updateInputManagerAutocapitalizationType;
-(void)updateInputManagerMode;
-(void)updateInputModeIndicatorOnSingleKeyOnly:(BOOL)arg0 ;
-(void)updateInputModeIndicatorOnSingleKeyOnly:(BOOL)arg0 preserveIfPossible:(BOOL)arg1 ;
-(void)updateInputModeLastChosenPreference;
-(void)updateIsAttachedHardwareKeyboard;
-(void)updateKeyboardConfigurations;
-(void)updateKeyboardEventsLagging:(id)arg0 ;
-(void)updateKeyboardOutput:(id)arg0 withInputForSmartPunctuation:(id)arg1 keyboardConfiguration:(id)arg2 ;
-(void)updateKeyboardStateForDeletion;
-(void)updateKeyboardStateForInsertion:(id)arg0 ;
-(void)updateLayout;
-(void)updateLayoutAndSetShift;
-(void)updateLayoutIfNecessary;
-(void)updateLayoutIfNeeded;
-(void)updateLayoutToCurrentInterfaceOrientation;
-(void)updateLegacyAutocorrectPromptWithAutocorrection:(id)arg0 parentView:(id)arg1 correctionRects:(id)arg2 ;
-(void)updateNoContentViews;
-(void)updateObserverState;
-(void)updateReturnKey;
-(void)updateReturnKey:(BOOL)arg0 ;
-(void)updateShiftState;
-(void)updateShowCandidateBar;
-(void)updateSmartPunctuationOptionsForLocaleIdentifier:(id)arg0 ;
-(void)updateStylingTraitsIfNeeded;
-(void)updateTextCandidateView;
-(void)updateTextInputKeyboardSource;
-(void)willDismissEditMenu;
-(void)willMoveToWindow:(id)arg0 ;
-(void)willReplaceTextInRangedSelectionWithKeyboardInput;


@end


#endif