// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef UIVIEW_H
#define UIVIEW_H

@class CALayer, NSArray, NSMutableArray, NSMutableSet, NSString, NSISVariable, NSISEngine, NSMapTable, NSLayoutYAxisAnchor, NSLayoutXAxisAnchor, NSLayoutDimension;
@protocol _UIFallbackEnvironment, UILayoutItem_Internal, UITextEffectsOrdering, UILargeContentViewerItem, UILargeContentViewerItem_Private, NSISVariableDelegate, _UILayoutItem, _UIMultilineTextContentSizing, NSISEngineDelegate, _UIScrollViewScrollObserver_Internal, _UIViewSubtreeMonitor, _UIGestureOwning, _UIPopoverPresentationControllerSourceItem_Internal, _UITraitEnvironmentInternal, _UIFocusItemInternal, _UIFocusItemDebuggable, _UIFocusRegionContainerInternal, _UILegacyFocusRegion, _UIGeometryChangeObserver, _UIDropInteractionOwning, _UIFocusEnvironmentPrivate, _UIFocusItemPrivate, _UIFocusItemContainerPrivate, _UIFocusRegionContainer, NSCoding, UIAppearance, UIAppearanceContainer, UIDynamicItem, UITraitEnvironment, UICoordinateSpace, UIFocusItem, UIFocusItemContainer, CALayerDelegate, _UIViewInternalDraggingSourceDelegate, _UIFocusBehavior, UIFocusEnvironment;


#import "UIResponder.h"
#import "UITraitCollection.h"
#import "UIViewAnimationInfo.h"
#import "UIWindow.h"
#import "UIViewController.h"
#import "UIVisualEffectBackingHost.h"
#import "_UIViewLayoutEngineRelativeAlignmentRectOriginCache.h"
#import "UIView.h"
#import "UIKBRenderConfig.h"
#import "UIPresentationController.h"
#import "_UITouchForceObservable.h"
#import "UIAccessibilityHUDItem.h"
#import "_UIBoundingPath.h"
#import "UIBezierPath.h"
#import "UIDropInteraction.h"
#import "UIFocusEffect.h"
#import "UIFocusSystem.h"
#import "_UIFocusSystemSceneComponent.h"
#import "UIColor.h"
#import "UIKeyboardLayoutGuide.h"
#import "UIKeyboardSceneDelegate.h"
#import "UIImage.h"
#import "UILayoutGuide.h"
#import "UIVisualEffect.h"
#import "UIPasteConfiguration.h"
#import "UIStoryboardPreviewingSegueTemplateStorage.h"

@interface UIView : UIResponder <_UIFallbackEnvironment, UILayoutItem_Internal, UITextEffectsOrdering, UILargeContentViewerItem, UILargeContentViewerItem_Private, NSISVariableDelegate, _UILayoutItem, _UIMultilineTextContentSizing, NSISEngineDelegate, _UIScrollViewScrollObserver_Internal, _UIViewSubtreeMonitor, _UIGestureOwning, _UIPopoverPresentationControllerSourceItem_Internal, _UITraitEnvironmentInternal, _UIFocusItemInternal, _UIFocusItemDebuggable, _UIFocusRegionContainerInternal, _UILegacyFocusRegion, _UIGeometryChangeObserver, _UIDropInteractionOwning, _UIFocusEnvironmentPrivate, _UIFocusItemPrivate, _UIFocusItemContainerPrivate, _UIFocusRegionContainer, NSCoding, UIAppearance, UIAppearanceContainer, UIDynamicItem, UITraitEnvironment, UICoordinateSpace, UIFocusItem, UIFocusItemContainer, CALayerDelegate>

 {
    UITraitCollection *_cachedTraitCollection;
    UIViewAnimationInfo *_animationInfo;
    CALayer *_layerRetained;
    NSArray *_subviewCache;
    UIWindow *_window;
    NSMutableArray *_gestureRecognizers;
    UIViewController *_viewDelegate;
    CGFloat _layoutEngineWidth;
    ? _viewFlags;
    unsigned short _unsatisfiableConstraintsLoggingSuspensionCount;
    unsigned int _pseudo_id;
    NSInteger _retainCount;
    id<_UIViewInternalDraggingSourceDelegate> *_draggingSourceDelegate;
    UIEdgeInsets _minimumSafeAreaInsets;
    CALayer *_layer;
    CALayer *_intermediateLayer;
    CALayer *_intermediateLayerRetained;
    NSMutableSet *_privateSubviews;
    UIVisualEffectBackingHost *_effectHost;
    NSString *_captureGroupName;
    unsigned short _tintAdjustmentDimmingCount;
    unsigned short _layoutSubviewsCount;
    unsigned short _imminentLayoutSubviewsCount;
    unsigned short _countOfFocusedAncestorTrackingViewsInSubtree;
}


@property (nonatomic, setter=_setAccessoryViewFrame:) CGRect _accessoryViewFrame;
@property (readonly, nonatomic) NSObject<_UIGestureOwning> *_actingGestureParent;
@property (readonly, nonatomic) NSObject<_UIGestureOwning> *_actingGestureParent;
@property (retain, nonatomic, setter=_setAlignmentRectOriginCache:) _UIViewLayoutEngineRelativeAlignmentRectOriginCache *_alignmentRectOriginCache; // ivar: __alignmentRectOriginCache
@property (readonly, nonatomic) BOOL _areLayoutMarginsDirectional;
@property (readonly, nonatomic) NSUInteger _axesForDerivingIntrinsicContentSizeFromLayoutSize;
@property (readonly, nonatomic) UIView *_backdropMaskViewForColorTint;
@property (readonly, nonatomic) UIView *_backdropMaskViewForFilters;
@property (readonly, nonatomic) UIView *_backdropMaskViewForGrayscaleTint;
@property (readonly, nonatomic) NSArray *_backdropMaskViews;
@property (nonatomic, setter=_setBackgroundMergeBehavior:) NSInteger _backgroundMergeBehavior;
@property (readonly, retain, nonatomic) NSISVariable *_boundsHeightVariable; // ivar: _boundsHeightVariable
@property (readonly, retain, nonatomic) NSISVariable *_boundsWidthVariable; // ivar: _boundsWidthVariable
@property (nonatomic, getter=_canBeParentTraitEnvironment, setter=_setCanBeParentTraitEnvironment:) BOOL _canBeParentTraitEnviroment;
@property (readonly, retain, nonatomic) NSArray *_constraintsExceptingSubviewAutoresizingConstraints; // ivar: _constraintsExceptingSubviewAutoresizingConstraints
@property (nonatomic, setter=_setContinuousCornerRadius:) CGFloat _continuousCornerRadius;
@property (nonatomic, setter=_setContinuousCornerRadius:) CGFloat _continuousCornerRadius;
@property (nonatomic, setter=_setCornerRadius:) CGFloat _cornerRadius;
@property (nonatomic, setter=_setCornerRadius:) CGFloat _cornerRadius;
@property (nonatomic, setter=_setCountOfFocusedAncestorTrackingViewsInSubtree:) NSUInteger _countOfFocusedAncestorTrackingViewsInSubtree;
@property (nonatomic, setter=_setCountOfMotionEffectsInSubtree:) NSUInteger _countOfMotionEffectsInSubtree;
@property (nonatomic, setter=_setDontUpdateInferredLayoutMargins:) BOOL _dontUpdateInferredLayoutMargins;
@property (weak, nonatomic, getter=_draggingSourceDelegate, setter=_setDraggingSourceDelegate:) NSObject<_UIViewInternalDraggingSourceDelegate> *_draggingSourceDelegate;
@property (readonly, nonatomic) UIWindow *_eventReceivingWindow;
@property (readonly, nonatomic) UIWindow *_eventReceivingWindow;
@property (nonatomic, setter=_setFlipsHorizontalAxis:) BOOL _flipsHorizontalAxis;
@property (readonly, nonatomic) NSInteger _focusItemDeferralMode;
@property (nonatomic, setter=_setFrameIgnoringLayerTransform:) CGRect _frameIgnoringLayerTransform;
@property (readonly, nonatomic) NSInteger _hiddenManagedByLayoutArrangementCount;
@property (readonly, nonatomic) BOOL _ignoreRemoveAllAnimations;
@property (nonatomic, setter=_setInferredLayoutMargins:) UIEdgeInsets _inferredLayoutMargins; // ivar: _inferredLayoutMargins
@property (readonly, nonatomic) UIKBRenderConfig *_inheritedRenderConfig;
@property (retain, nonatomic, setter=_setInternalConstraints:) NSMutableArray *_internalConstraints; // ivar: _internalConstraints
@property (readonly, nonatomic) BOOL _isInLayoutSubviews;
@property (readonly, nonatomic) BOOL _isUnsatisfiableConstraintsLoggingSuspended;
@property (readonly, nonatomic) NSInteger _keyboardOrientation;
@property (retain, nonatomic, setter=_setLastNotifiedTraitCollection:) UITraitCollection *_lastNotifiedTraitCollection; // ivar: __lastNotifiedTraitCollection
@property (copy, nonatomic, setter=_setLayoutDebuggingIdentifier:) NSString *_layoutDebuggingIdentifier;
@property (copy, nonatomic, setter=_setLayoutDebuggingIdentifier:) NSString *_layoutDebuggingIdentifier;
@property (retain, nonatomic, setter=_setLayoutEngine:) NSISEngine *_layoutEngine; // ivar: _layoutEngine
@property (readonly, nonatomic) BOOL _layoutHeightDependsOnWidth;
@property (nonatomic, setter=_setLayoutMarginsGuideIgnoresSystemMinimumMargins:) BOOL _layoutMarginsGuideIgnoresSystemMinimumMargins;
@property (nonatomic, setter=_setLayoutMarginsGuideIgnoresSystemMinimumMargins:) BOOL _layoutMarginsGuideIgnoresSystemMinimumMargins;
@property (readonly, nonatomic) NSMapTable *_lfld_constraintsAffectingVariableValueChanges;
@property (readonly, nonatomic) NSInteger _lfld_count;
@property (readonly, nonatomic) NSString *_lfld_currentLayoutMethodName;
@property (readonly, nonatomic) NSMutableArray *_lfld_geometryChangeRecords;
@property (readonly, nonatomic) NSMutableSet *_lfld_setNeedsLayoutCallStacks;
@property (readonly, nonatomic) NSMutableArray *_lfld_variableChangeRecords;
@property (readonly, nonatomic) BOOL _lightStyleRenderConfig;
@property (retain, nonatomic, getter=_localOverrideTraitCollection, setter=_setLocalOverrideTraitCollection:) UITraitCollection *_localOverrideTraitCollection;
@property (retain, nonatomic, setter=_setMaskView:) UIView *_maskView;
@property (readonly, retain, nonatomic) NSISVariable *_minXVariable; // ivar: _minXVariable
@property (readonly, retain, nonatomic) NSISVariable *_minYVariable; // ivar: _minYVariable
@property (nonatomic, setter=_setMultilineContextWidth:) CGFloat _multilineContextWidth;
@property (readonly, retain, nonatomic) NSMutableArray *_mutableLayoutArrangements;
@property (readonly, retain, nonatomic) NSMutableArray *_mutableLayoutGuides;
@property (readonly, nonatomic) NSArray *_nativeInteractions;
@property (readonly, nonatomic) NSArray *_nativeInteractions;
@property (nonatomic, setter=_setNeedsContentsFormatUpdate:) BOOL _needsContentsFormatUpdate;
@property (nonatomic, getter=_overrideUserInterfaceRenderingMode, setter=_setOverrideUserInterfaceRenderingMode:) NSInteger _overrideUserInterfaceRenderingMode;
@property (nonatomic, getter=_overrideUserInterfaceStyle, setter=_setOverrideUserInterfaceStyle:) NSInteger _overrideUserInterfaceStyle;
@property (nonatomic, getter=_overrideVibrancyTrait, setter=_setOverrideVibrancyTrait:) NSInteger _overrideVibrancyTrait;
@property (readonly, nonatomic) NSInteger _pendingHiddenCount;
@property (nonatomic, setter=_setPreferedContentsFormat:) NSInteger _preferedContentsFormat; // ivar: __preferedContentsFormat
@property (weak, nonatomic, getter=_presentationControllerToNotifyOnLayoutSubviews, setter=_setPresentationControllerToNotifyOnLayoutSubviews:) UIPresentationController *_presentationControllerToNotifyOnLayoutSubviews;
@property (nonatomic, setter=_setPreservesSafeAreaInsets:) BOOL _preservesSafeAreaInsets;
@property (nonatomic, setter=_setRawLayoutMargins:) UIEdgeInsets _rawLayoutMargins; // ivar: _rawLayoutMargins
@property (readonly, nonatomic) CGVector _scaleFromLayerTransforms;
@property (nonatomic, setter=_setShouldAdaptToMaterials:) BOOL _shouldAdaptToMaterials;
@property (nonatomic, setter=_setShouldArchiveUIAppearanceTags:) BOOL _shouldArchiveUIAppearanceTags;
@property (readonly, nonatomic) BOOL _shouldReverseLayoutDirection;
@property (readonly, nonatomic) NSMapTable *_stashedLayoutVariableObservations; // ivar: _stashedLayoutVariableObservations
@property (readonly, nonatomic) _UITouchForceObservable *_touchForceObservable;
@property (nonatomic, setter=_setTracksFocusedAncestors:) BOOL _tracksFocusedAncestors;
@property (readonly, nonatomic) CGRect _ui_bounds;
@property (nonatomic) CGRect _ui_frame;
@property (readonly, nonatomic) UIView *_ui_superview;
@property (nonatomic) BOOL _ui_usesManualLayout;
@property (readonly, nonatomic) UIView *_ui_view;
@property (nonatomic, getter=_userInterfaceIdiom, setter=_setUserInterfaceIdiom:) NSInteger _userInterfaceIdiom;
@property (nonatomic, setter=_setViewDelegateContentOverlayInsetsAreClean:) BOOL _viewDelegateContentOverlayInsetsAreClean;
@property (readonly, nonatomic) BOOL _wantsConstraintBasedLayout;
@property (readonly) CGFloat _widthForButtonBarItemLayout;
@property (readonly, nonatomic) UIAccessibilityHUDItem *accessibilityHUDRepresentation;
@property (nonatomic) BOOL accessibilityIgnoresInvertColors;
@property (nonatomic) BOOL allowsGroupBlending;
@property (nonatomic) BOOL allowsGroupOpacity;
@property (readonly, copy, nonatomic) NSString *appliedContentSizeCategoryLimitsDescription;
@property (nonatomic) BOOL areChildrenFocused;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *bottomAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *bottomAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *bottomAnchor;
@property (retain, nonatomic, getter=_boundingPath, setter=_setBoundingPath:) _UIBoundingPath *boundingPath;
@property (readonly, nonatomic, getter=_boundingPathForSubtree) _UIBoundingPath *boundingPathForSubtree;
@property (readonly, nonatomic) CGRect bounds;
@property (readonly, nonatomic) BOOL canBecomeFocused;
@property (nonatomic) CGPoint center;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *centerXAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *centerXAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *centerXAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *centerYAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *centerYAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *centerYAnchor;
@property (readonly, nonatomic) UIBezierPath *collisionBoundingPath;
@property (readonly, nonatomic) NSUInteger collisionBoundsType;
@property (nonatomic) NSInteger compositingMode;
@property (readonly, nonatomic, getter=_isContainedInHostedFocusSystem) BOOL containedInHostedFocusSystem;
@property (retain, nonatomic, getter=_contentSizeNotificationToken, setter=_setContentSizeNotificationToken:) id *contentSizeNotificationToken;
@property (readonly, nonatomic) NSObject<UICoordinateSpace> *coordinateSpace;
@property (readonly, nonatomic, getter=_currentScreenScale) CGFloat currentScreenScale;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL deliversButtonsForGesturesToSuperview;
@property (nonatomic) BOOL deliversTouchesForGesturesToSuperview;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (weak, nonatomic, getter=_dynamicDropInteraction, setter=_setDynamicDropInteraction:) UIDropInteraction *dynamicDropInteraction;
@property (readonly, nonatomic) NSInteger effectiveUserInterfaceLayoutDirection;
@property (readonly, nonatomic, getter=_isEligibleForFocusInteraction) BOOL eligibleForFocusInteraction;
@property (readonly, nonatomic, getter=_isEligibleForFocusOcclusion) BOOL eligibleForFocusOcclusion;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *firstBaselineAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *firstBaselineAnchor;
@property (readonly, nonatomic, getter=_focusBehavior) NSObject<_UIFocusBehavior> *focusBehavior;
@property (copy, nonatomic) UIFocusEffect *focusEffect;
@property (copy, nonatomic) NSString *focusGroupIdentifier;
@property (nonatomic) NSInteger focusGroupPriority;
@property (nonatomic, getter=_isFocusInteractionEnabled, setter=_setFocusInteractionEnabled:) BOOL focusInteractionEnabled;
@property (readonly, nonatomic) NSObject<UIFocusItemContainer> *focusItemContainer;
@property (readonly, weak, nonatomic, getter=_focusMapContainer) NSObject<_UIFocusRegionContainer> *focusMapContainer;
@property (readonly, nonatomic, getter=_focusSystem) UIFocusSystem *focusSystem;
@property (readonly, nonatomic, getter=_focusSystemSceneComponent) _UIFocusSystemSceneComponent *focusSystemSceneComponent;
@property (readonly, nonatomic, getter=_focusTouchSensitivityStyle) NSInteger focusTouchSensitivityStyle;
@property (readonly, nonatomic, getter=isFocused) BOOL focused;
@property (readonly, nonatomic) CGRect frame;
@property (readonly, nonatomic) NSObject<_UIGestureOwning> *gestureParent;
@property (readonly, nonatomic) NSObject<_UIGestureOwning> *gestureParent;
@property (readonly, nonatomic) NSArray *gestureRecognizers;
@property (readonly, nonatomic) NSArray *gestureRecognizers;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic) NSLayoutDimension *heightAnchor;
@property (readonly, nonatomic) NSLayoutDimension *heightAnchor;
@property (readonly, nonatomic) NSLayoutDimension *heightAnchor;
@property (nonatomic) NSDirectionalEdgeInsets hitTestDirectionalInsets;
@property (nonatomic) NSDirectionalEdgeInsets hitTestDirectionalInsets;
@property (nonatomic) UIEdgeInsets hitTestInsets;
@property (nonatomic) UIEdgeInsets hitTestInsets;
@property (retain, nonatomic) UIColor *interactionTintColor;
@property (retain, nonatomic) UIColor *interactionTintColor;
@property (readonly, nonatomic, getter=_isBoundingPathNonRectangular) BOOL isBoundingPathNonRectangular;
@property (readonly, nonatomic) BOOL isTransparentFocusItem;
@property (readonly, nonatomic) UIKeyboardLayoutGuide *keyboardLayoutGuide; // ivar: _keyboardLayoutGuide
@property (readonly, nonatomic) UIKeyboardSceneDelegate *keyboardSceneDelegate;
@property (retain, nonatomic) UIImage *largeContentImage;
@property (readonly, nonatomic) UIImage *largeContentImage;
@property (nonatomic) UIEdgeInsets largeContentImageInsets;
@property (readonly, nonatomic) UIEdgeInsets largeContentImageInsets;
@property (copy, nonatomic) NSString *largeContentTitle;
@property (readonly, copy, nonatomic) NSString *largeContentTitle;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *lastBaselineAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *lastBaselineAnchor;
@property (readonly, nonatomic) CALayer *layer;
@property (retain, nonatomic, setter=_setLayoutMarginsGuide:) UILayoutGuide *layoutMarginsGuide; // ivar: _layoutMarginsGuide
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leadingAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leadingAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leadingAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leftAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leftAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *leftAnchor;
@property (readonly, copy, nonatomic, getter=_linearFocusMovementSequences) NSArray *linearFocusMovementSequences;
@property (retain, nonatomic, getter=_maskView, setter=_setMaskView:) UIView *maskView;
@property (copy, nonatomic) NSString *maximumContentSizeCategory;
@property (readonly, nonatomic, getter=_mayRemainFocused) BOOL mayRemainFocused;
@property (copy, nonatomic) NSString *minimumContentSizeCategory;
@property (nonatomic, getter=_monitorsSubtree, setter=_setMonitorsSubtree:) BOOL monitorsSubtree;
@property (copy, nonatomic, setter=mt_setBackgroundEffects:) NSArray *mt_backgroundEffects;
@property (copy, nonatomic, setter=mt_setCaptureGroupName:) NSString *mt_captureGroupName;
@property (copy, nonatomic, setter=mt_setContentEffects:) NSArray *mt_contentEffects;
@property (copy, nonatomic, setter=mt_setVisualEffect:) UIVisualEffect *mt_visualEffect;
@property (setter=nsli_setPiercingToken:) NSUInteger nsli_piercingToken;
@property (nonatomic) NSInteger overrideUserInterfaceStyle;
@property (readonly, weak, nonatomic) NSObject<UIFocusEnvironment> *parentFocusEnvironment;
@property (copy, nonatomic) UIPasteConfiguration *pasteConfiguration;
@property (readonly, copy, nonatomic) NSArray *preferredFocusEnvironments;
@property (readonly, nonatomic, getter=_preferredFocusMovementStyle) NSInteger preferredFocusMovementStyle;
@property (readonly, weak, nonatomic) UIView *preferredFocusedView;
@property (retain, nonatomic, getter=_previewingSegueTemplateStorage, setter=_setPreviewingSegueTemplateStorage:) UIStoryboardPreviewingSegueTemplateStorage *previewingSegueTemplateStorage;
@property (retain, nonatomic, setter=_setReadableContentGuide:) UILayoutGuide *readableContentGuide; // ivar: _readableContentGuide
@property (readonly, nonatomic) NSLayoutXAxisAnchor *rightAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *rightAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *rightAnchor;
@property (nonatomic) UIEdgeInsets safeAreaInsets; // ivar: _safeAreaInsets
@property (readonly, nonatomic) UILayoutGuide *safeAreaLayoutGuide; // ivar: _safeAreaLayoutGuide
@property (readonly, nonatomic, getter=_safeAreaWidthExceedsReadableWidth) BOOL safeAreaWidthExceedsReadableWidth;
@property (nonatomic) BOOL scalesLargeContentImage;
@property (readonly, nonatomic) BOOL scalesLargeContentImage;
@property (nonatomic) NSInteger semanticContentAttribute;
@property (nonatomic) BOOL showsLargeContentViewer;
@property (readonly, nonatomic) BOOL showsLargeContentViewer;
@property (nonatomic) BOOL skipsSubviewEnumeration;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (nonatomic) NSInteger tag;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *topAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *topAnchor;
@property (readonly, nonatomic) NSLayoutYAxisAnchor *topAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *trailingAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *trailingAnchor;
@property (readonly, nonatomic) NSLayoutXAxisAnchor *trailingAnchor;
@property (readonly, nonatomic) UITraitCollection *traitCollection;
@property (readonly, nonatomic) UITraitCollection *traitCollection;
@property (nonatomic) CGAffineTransform transform;
@property (nonatomic, getter=isUserInteractionEnabled) BOOL userInteractionEnabled;
@property (readonly, nonatomic, getter=_viewDelegate) UIViewController *viewDelegate;
@property (nonatomic) BOOL viewTraversalMark;
@property (nonatomic) BOOL wantsDeepColorDrawing;
@property (nonatomic) BOOL wantsDeepColorDrawing;
@property (readonly, nonatomic) NSLayoutDimension *widthAnchor;
@property (readonly, nonatomic) NSLayoutDimension *widthAnchor;
@property (readonly, nonatomic) NSLayoutDimension *widthAnchor;


+(BOOL)_addCompletion:(id)arg0 ;
+(BOOL)_addCompletionWithPosition:(id)arg0 ;
+(BOOL)_allowsUnsupportedMacIdiomBehavior;
+(BOOL)_enableLegacyRTL;
+(BOOL)_enableRTL;
+(BOOL)_hasActiveAnimationContext;
+(BOOL)_hostLayoutEngineOnlyTAMIC_YES;
+(BOOL)_isAnimationTracking;
+(BOOL)_isInAnimationBlock;
+(BOOL)_isInAnimationBlockWithAnimationsEnabled;
+(BOOL)_isInRetargetableAnimationBlock;
+(BOOL)_legacyRTLPreferenceEnabled;
+(BOOL)_motionEffectsEnabled;
+(BOOL)_motionEffectsSupported;
+(BOOL)_preventsAppearanceProxyCustomization;
+(BOOL)_shouldTrackActionWithAnimator:(id)arg0 ;
+(BOOL)_shouldTrackAnimationsWithAnimator;
+(BOOL)_supportsInvalidatingFocusCache;
+(BOOL)_toolsDebugAlignmentRects;
+(BOOL)_toolsDebugColorViewBounds;
+(BOOL)_toolsDebugShouldDetectClippedViews;
+(BOOL)_wantsDeepColorByDefault;
+(BOOL)areAnimationsEnabled;
+(BOOL)requiresConstraintBasedLayout;
+(CGFloat)_currentAnimationDuration;
+(CGFloat)_durationForRotationFromInterfaceOrientation:(NSInteger)arg0 toInterfaceOrientation:(NSInteger)arg1 ;
+(CGFloat)_durationForRotationFromInterfaceOrientation:(NSInteger)arg0 toInterfaceOrientation:(NSInteger)arg1 withBaseDuration:(CGFloat)arg2 ;
+(CGFloat)inheritedAnimationDuration;
+(NSInteger)_currentAnimationCurve;
+(NSInteger)userInterfaceLayoutDirectionForSemanticContentAttribute:(NSInteger)arg0 ;
+(NSInteger)userInterfaceLayoutDirectionForSemanticContentAttribute:(NSInteger)arg0 relativeToLayoutDirection:(NSInteger)arg1 ;
+(id)_alongsideAnimations:(SEL)arg0 ;
+(id)_appearanceWhenContainedIn:(id)arg0 ;
+(id)_currentAnimationAttributes;
+(id)_currentAnimationSettings;
+(id)_currentViewAnimationState;
+(id)_defaultInteractionTintColorForIdiom:(NSInteger)arg0 ;
+(id)_defaultUIViewActionForLayer:(id)arg0 forKey:(id)arg1 ;
+(id)_defaultUIViewAnimationForLayer:(id)arg0 forKey:(id)arg1 ;
+(id)_disabledColorForTintColor:(id)arg0 ;
+(id)_enableAnimationTracking;
+(id)_enableAnimationTracking:(BOOL)arg0 ;
+(id)_performWithAnimationTracking:(id)arg0 ;
+(id)_startAnimationTracking;
+(id)_viewWithLayoutConstraints;
+(id)appearance;
+(id)appearanceForTraitCollection:(id)arg0 ;
+(id)appearanceForTraitCollection:(id)arg0 whenContainedIn:(Class)arg1 ;
+(id)appearanceForTraitCollection:(id)arg0 whenContainedInInstancesOfClasses:(id)arg1 ;
+(id)appearanceMatchingProperties:(id)arg0 whenContainedInInstancesOfClasses:(id)arg1 ;
+(id)appearanceWhenContainedIn:(Class)arg0 ;
+(id)appearanceWhenContainedInInstancesOfClasses:(id)arg0 ;
+(int)_degreesToRotateFromInterfaceOrientation:(NSInteger)arg0 toInterfaceOrientation:(NSInteger)arg1 ;
+(void)_addHierarchyTrackingVisitor:(id)arg0 ;
+(void)_addOrPerformCompletion:(id)arg0 ;
+(void)_addOrPerformCompletionWithPosition:(id)arg0 ;
// +(void)_animateByRetargetingAnimations:(id)arg0 completion:(unk)arg1  ;
// +(void)_animateUsingDefaultDampedSpringWithDelay:(CGFloat)arg0 initialSpringVelocity:(CGFloat)arg1 options:(NSUInteger)arg2 animations:(id)arg3 completion:(unk)arg4  ;
// +(void)_animateUsingDefaultTimingWithOptions:(NSUInteger)arg0 animations:(id)arg1 completion:(unk)arg2  ;
// +(void)_animateUsingSpringBehavior:(id)arg0 tracking:(BOOL)arg1 animations:(id)arg2 completion:(unk)arg3  ;
// +(void)_animateUsingSpringInteractive:(BOOL)arg0 animations:(id)arg1 completion:(unk)arg2  ;
// +(void)_animateUsingSpringWithDampingRatio:(CGFloat)arg0 response:(CGFloat)arg1 tracking:(BOOL)arg2 dampingRatioSmoothing:(CGFloat)arg3 responseSmoothing:(CGFloat)arg4 targetSmoothing:(CGFloat)arg5 projectionDeceleration:(CGFloat)arg6 animations:(id)arg7 completion:(unk)arg8  ;
// +(void)_animateUsingSpringWithDampingRatio:(CGFloat)arg0 response:(CGFloat)arg1 tracking:(BOOL)arg2 dampingRatioSmoothing:(CGFloat)arg3 responseSmoothing:(CGFloat)arg4 targetSmoothing:(CGFloat)arg5 projectionDeceleration:(CGFloat)arg6 retargetImpulse:(CGFloat)arg7 animations:(id)arg8 completion:(unk)arg9  ;
// +(void)_animateUsingSpringWithDampingRatio:(CGFloat)arg0 response:(CGFloat)arg1 tracking:(BOOL)arg2 initialDampingRatio:(CGFloat)arg3 initialResponse:(CGFloat)arg4 dampingRatioSmoothing:(CGFloat)arg5 responseSmoothing:(CGFloat)arg6 targetSmoothing:(CGFloat)arg7 projectionDeceleration:(CGFloat)arg8 animations:(id)arg9 completion:(unk)arg10  ;
// +(void)_animateUsingSpringWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 options:(NSUInteger)arg2 mass:(CGFloat)arg3 stiffness:(CGFloat)arg4 damping:(CGFloat)arg5 initialVelocity:(CGFloat)arg6 animations:(id)arg7 completion:(unk)arg8  ;
// +(void)_animateUsingSpringWithTension:(CGFloat)arg0 friction:(CGFloat)arg1 interactive:(BOOL)arg2 animations:(id)arg3 completion:(unk)arg4  ;
// +(void)_animateWithAnimationAndComposerGetter:(id)arg0 animations:(unk)arg1 completion:(id)arg2  ;
// +(void)_animateWithAnimationAndComposerGetter:(id)arg0 animations:(unk)arg1 completion:(id)arg2 animationStateSetup:(unk)arg3  ;
// +(void)_animateWithAttributes:(id)arg0 animations:(id)arg1 completion:(unk)arg2  ;
// +(void)_animateWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 options:(NSUInteger)arg2 animations:(id)arg3 start:(unk)arg4 completion:(id)arg5  ;
// +(void)_animateWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 options:(NSUInteger)arg2 factory:(id)arg3 animations:(id)arg4 completion:(unk)arg5  ;
+(void)_animateWithFilter:(int)arg0 filterView:(id)arg1 filterValue:(CGFloat)arg2 duration:(CGFloat)arg3 delay:(CGFloat)arg4 options:(NSUInteger)arg5 completion:(id)arg6 ;
// +(void)_animateWithFrictionBounceAnimations:(id)arg0 completion:(unk)arg1  ;
+(void)_beginSuspendingMotionEffectsForReason:(id)arg0 ;
+(void)_completeAnimationWithUUID:(id)arg0 duration:(CGFloat)arg1 curve:(NSInteger)arg2 reverse:(BOOL)arg3 ;
+(void)_conditionallyModifyAnimations:(BOOL)arg0 withPreferredFrameRateRange:(struct CAFrameRateRange )arg1 updateReason:(unsigned int)arg2 animations:(id)arg3 ;
// +(void)_createTransformerWithInputAnimatableProperties:(id)arg0 modelValueSetter:(id)arg1 presentationValueSetter:(unk)arg2  ;
+(void)_createTransformerWithInputAnimatableProperties:(id)arg0 presentationValueChangedCallback:(id)arg1 ;
+(void)_disableAnimationTracking:(id)arg0 ;
+(void)_disableAnimationTracking:(id)arg0 clearTrackedAnimations:(BOOL)arg1 ;
+(void)_enableToolsDebugAlignmentRects:(BOOL)arg0 ;
+(void)_enableToolsDebugColorViewBounds:(BOOL)arg0 ;
+(void)_endSuspendingMotionEffectsForReason:(id)arg0 ;
+(void)_finalizeStoppedAnimationWithUUID:(id)arg0 reverseAnimation:(BOOL)arg1 ;
+(void)_finalizeStoppedAnimationWithUUID:(id)arg0 reverseAnimation:(BOOL)arg1 state:(id)arg2 performCompletionsImmediately:(BOOL)arg3 ;
+(void)_finishAnimationTracking;
+(void)_inheritAnimationParameters;
+(void)_initializeForIdiom:(NSInteger)arg0 ;
+(void)_modifyAnimationsWithPreferredFrameRateRange:(struct CAFrameRateRange )arg0 reason:(id)arg1 animations:(id)arg2 ;
+(void)_modifyAnimationsWithPreferredFrameRateRange:(struct CAFrameRateRange )arg0 updateReason:(unsigned int)arg1 animations:(id)arg2 ;
+(void)_performForcedAppearanceModifications:(id)arg0 ;
+(void)_performSystemAppearanceModifications:(id)arg0 ;
+(void)_performWithAnimation:(id)arg0 ;
+(void)_performWithDurationOverride:(CGFloat)arg0 animations:(id)arg1 ;
+(void)_performWithState:(id)arg0 trackingIdentifier:(id)arg1 duration:(CGFloat)arg2 delay:(CGFloat)arg3 animations:(id)arg4 ;
+(void)_performWithoutAnimation:(id)arg0 ;
+(void)_performWithoutRetargetingAnimations:(id)arg0 ;
+(void)_registerClassForIdiomInitializationIfNeccessary;
+(void)_removeHierarchyTrackingVisitor:(id)arg0 ;
+(void)_resetHostLayoutEngineOnlyTAMIC_YES;
+(void)_setAllowsUnsupportedMacIdiomBehavior:(BOOL)arg0 ;
+(void)_setAlongsideAnimations:(id)arg0 ;
// +(void)_setAlongsideAnimations:(id)arg0 toRunByEndOfBlock:(unk)arg1  ;
+(void)_setAnimatedPropertiesEnabled:(BOOL)arg0 ;
+(void)_setAnimationAttributes:(id)arg0 ;
+(void)_setAnimationAttributes:(id)arg0 skipDelegateAssignment:(BOOL)arg1 ;
+(void)_setHostLayoutEngineOnlyTAMIC_YES;
+(void)_setShouldEnableUIKitParallaxEffects:(BOOL)arg0 ;
+(void)_stopAnimationWithUUID:(id)arg0 ;
+(void)_testIfFirstView:(id)arg0 secondView:(id)arg1 areDescendantsOfView:(id)arg2 results:(BOOL)arg3 ;
+(void)_transitionWithView:(id)arg0 duration:(CGFloat)arg1 options:(NSUInteger)arg2 transitionOptions:(id)arg3 completion:(id)arg4 ;
// +(void)_updateModelValuesForAnimationWithUUID:(id)arg0 useInitialValues:(BOOL)arg1 animatable:(BOOL)arg2 stateBlock:(id)arg3 animationBlock:(unk)arg4  ;
+(void)_updateOrientationForMotionEngine:(NSInteger)arg0 ;
+(void)addKeyframeWithRelativeStartTime:(CGFloat)arg0 relativeDuration:(CGFloat)arg1 animations:(id)arg2 ;
// +(void)animateKeyframesWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 options:(NSUInteger)arg2 animations:(id)arg3 completion:(unk)arg4  ;
+(void)animateWithDuration:(CGFloat)arg0 animations:(id)arg1 ;
// +(void)animateWithDuration:(CGFloat)arg0 animations:(id)arg1 completion:(unk)arg2  ;
// +(void)animateWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 options:(NSUInteger)arg2 animations:(id)arg3 completion:(unk)arg4  ;
// +(void)animateWithDuration:(CGFloat)arg0 delay:(CGFloat)arg1 usingSpringWithDamping:(CGFloat)arg2 initialSpringVelocity:(CGFloat)arg3 options:(NSUInteger)arg4 animations:(id)arg5 completion:(unk)arg6  ;
+(void)beginAnimations:(id)arg0 ;
+(void)beginAnimations:(id)arg0 context:(*void)arg1 ;
+(void)commitAnimations;
// +(void)conditionallyAnimate:(BOOL)arg0 withAnimation:(id)arg1 layout:(unk)arg2 completion:(id)arg3  ;
+(void)disableAnimation;
+(void)enableAnimation;
+(void)endAnimations;
+(void)flush;
+(void)initialize;
+(void)modifyAnimationsWithRepeatCount:(CGFloat)arg0 autoreverses:(BOOL)arg1 animations:(id)arg2 ;
// +(void)performSystemAnimation:(NSUInteger)arg0 onViews:(id)arg1 options:(NSUInteger)arg2 animations:(id)arg3 completion:(unk)arg4  ;
+(void)performWithoutAnimation:(id)arg0 ;
+(void)setAnimationAutoreverses:(BOOL)arg0 ;
+(void)setAnimationBeginsFromCurrentState:(BOOL)arg0 ;
+(void)setAnimationCurve:(NSInteger)arg0 ;
+(void)setAnimationDelay:(CGFloat)arg0 ;
+(void)setAnimationDelegate:(id)arg0 ;
+(void)setAnimationDidStopSelector:(SEL)arg0 ;
+(void)setAnimationDuration:(CGFloat)arg0 ;
+(void)setAnimationFrameInterval:(CGFloat)arg0 ;
+(void)setAnimationFromCurrentState:(BOOL)arg0 ;
+(void)setAnimationPosition:(struct CGPoint )arg0 ;
+(void)setAnimationPreventsAdditive:(BOOL)arg0 ;
+(void)setAnimationRepeatAutoreverses:(BOOL)arg0 ;
+(void)setAnimationRepeatCount:(float)arg0 ;
+(void)setAnimationStartDate:(id)arg0 ;
+(void)setAnimationStartTime:(CGFloat)arg0 ;
+(void)setAnimationTransition:(NSInteger)arg0 forView:(id)arg1 ;
+(void)setAnimationTransition:(NSInteger)arg0 forView:(id)arg1 cache:(BOOL)arg2 ;
+(void)setAnimationWillStartSelector:(SEL)arg0 ;
+(void)setAnimationsEnabled:(BOOL)arg0 ;
+(void)throttledFlush;
+(void)transitionFromView:(id)arg0 toView:(id)arg1 duration:(CGFloat)arg2 options:(NSUInteger)arg3 completion:(id)arg4 ;
// +(void)transitionWithView:(id)arg0 duration:(CGFloat)arg1 options:(NSUInteger)arg2 animations:(id)arg3 completion:(unk)arg4  ;
-(*void)_createIOSurfaceWithPadding:(struct UIEdgeInsets )arg0 ;
-(*void)_fallbackTraitCollection;
-(BOOL)_UIViewDebuggingIsViewClipping;
-(BOOL)__isKindOfUIView;
-(BOOL)_accessibilityAddItemsToDragSessionAtPlatformPoint:(struct CGPoint )arg0 ;
-(BOOL)_accessibilityAddItemsToDragSessionAtPoint:(struct CGPoint )arg0 ;
-(BOOL)_accessibilityCanAddItemsToDragSession;
-(BOOL)_accessibilityCanDrag;
-(BOOL)_accessibilityCanDrop;
-(BOOL)_allowAssistanceInSubtree;
-(BOOL)_allowsArchivingAsSubview;
-(BOOL)_allowsFocusToLeaveViaHeading:(NSUInteger)arg0 ;
-(BOOL)_allowsHighContrastForBackgroundColor;
-(BOOL)_allowsLinkPreviewInteractionInViewServices;
-(BOOL)_alwaysHandleScrollerMouseEvent;
-(BOOL)_ancestorHasInvertFilterApplied;
-(BOOL)_appearanceIsInvalid;
-(BOOL)_appliesExclusiveTouchToSubviewTree;
-(BOOL)_applyKeyPathsAndRelativeValues:(id)arg0 forMotionEffect:(id)arg1 ;
-(BOOL)_associatedViewControllerForwardsAppearanceCallbacks:(id)arg0 performHierarchyCheck:(BOOL)arg1 isRoot:(BOOL)arg2 ;
-(BOOL)_becomeFirstResponderWhenPossible;
-(BOOL)_beginDragWithInteractionTouches:(id)arg0 ;
-(BOOL)_beginDragWithTouches:(id)arg0 orInitialCentroid:(struct CGPoint )arg1 accessibilityEndpoint:(id)arg2 ;
-(BOOL)_cachedTraitCollectionIsValid;
-(BOOL)_canBeReusedInPickerView;
-(BOOL)_canBecomeFirstResponderWhenPossible;
-(BOOL)_canBecomeLayoutEngineDelegate;
-(BOOL)_canDrawContent;
-(BOOL)_canHandleStatusBarTouchAtLocation:(struct CGPoint )arg0 ;
-(BOOL)_canHostViewControllerContentScrollView;
-(BOOL)_canPerformDefaultImplementationForStandardEditAction:(SEL)arg0 ;
-(BOOL)_canSkipTraitsAndOverlayUpdatesForViewControllerToNotifyOnLayoutResetState:(BOOL)arg0 ;
-(BOOL)_containedInAbsoluteResponderChain;
-(BOOL)_contentHuggingDefault_isUsuallyFixedHeight;
-(BOOL)_contentHuggingDefault_isUsuallyFixedWidth;
-(BOOL)_controlsOwnScaleFactor;
-(BOOL)_definesDynamicTintColor;
-(BOOL)_definesTintColor;
-(BOOL)_delaysTouchesForSystemGestures;
-(BOOL)_disableGeometryObserverNotification;
-(BOOL)_drawsAsBackdropOverlay;
-(BOOL)_fakeShouldAnimatePropertyWithKey:(id)arg0 ;
-(BOOL)_forceLayoutEngineSolutionInRationalEdges;
-(BOOL)_forwardsSystemLayoutFittingSizeToContentView:(id)arg0 ;
-(BOOL)_gestureRecognizerShouldReceiveTouch:(id)arg0 ;
-(BOOL)_hasAmbiguousLayout;
-(BOOL)_hasAutolayoutHeightConstraint;
-(BOOL)_hasBackgroundMaterial;
-(BOOL)_hasBaseline;
-(BOOL)_hasCustomAutolayoutNeighborSpacingForAttribute:(*NSInteger)arg0 ;
-(BOOL)_hasDefaultImplementationForStandardEditAction:(SEL)arg0 ;
-(BOOL)_hasFontInfoForVerticalBaselineSpacing;
-(BOOL)_hasLayoutArrangements;
-(BOOL)_hasLayoutEngine;
-(BOOL)_hostsLayoutEngine;
-(BOOL)_hostsLayoutEngineAllowsTAMIC_NO;
-(BOOL)_ignoreBackdropViewsWhenHiding;
-(BOOL)_ignoresLayerTransformForSafeAreaInsets;
-(BOOL)_inSecondConstraintsPass;
-(BOOL)_isAncestorOfFirstResponder;
-(BOOL)_isChargeEnabled;
-(BOOL)_isFindAction:(SEL)arg0 ;
-(BOOL)_isFloatingLayoutItem;
-(BOOL)_isFocusDirectionFlippedHorizontally;
-(BOOL)_isGestureOwningType:(NSInteger)arg0 ;
-(BOOL)_isHasBaselinePropertyChangeable;
-(BOOL)_isHiddenForReuse;
-(BOOL)_isInAWindow;
-(BOOL)_isInAnimatedLayout;
-(BOOL)_isInExclusiveTouchSubviewTree;
-(BOOL)_isInTransitionBlock;
-(BOOL)_isKnownUISearchBarComponentContainer;
-(BOOL)_isLazyFocusItemContainer;
-(BOOL)_isManuallyResizedBySuperview;
-(BOOL)_isMemberOfViewControllerHierarchy:(id)arg0 ;
-(BOOL)_isPromiseFocusRegion;
-(BOOL)_isRootForKeyResponderCycle;
-(BOOL)_isScrollingEnabled;
-(BOOL)_isTransparentFocusRegion;
-(BOOL)_isView;
-(BOOL)_is_needsLayout;
-(BOOL)_la_isVisible;
-(BOOL)_layoutEngine_isEngineMergingAllowedBetweenEngine:(id)arg0 itemEngine:(id)arg1 forConstraint:(id)arg2 initialView:(id)arg3 ;
-(BOOL)_monitorsView:(id)arg0 ;
-(BOOL)_motionEffectsAreSuspended;
-(BOOL)_needsDoubleUpdateConstraintsPass;
-(BOOL)_needsLayoutOnAnimatedFrameChangeForNewFrame:(struct CGRect )arg0 ;
-(BOOL)_ola_isCandidateForMultilineTextWidthDisambiguationWhenArranged;
-(BOOL)_ola_shouldUseImprovedMultilineTextDisambiguation;
-(BOOL)_old_nsli_lowerAttribute:(int)arg0 intoExpression:(id)arg1 withCoefficient:(CGFloat)arg2 forConstraint:(id)arg3 ;
-(BOOL)_potentiallyHasDanglyConstraints;
-(BOOL)_preWhitetailUsesAutoresizingConstraints;
-(BOOL)_prefersDrawingWithForcedScaleFactorInClassicMode;
-(BOOL)_prefersFocusContainment;
-(BOOL)_recordBaselineLoweringInfo;
-(BOOL)_requiresExplicitLayoutMarginsGuideForAttribute:(NSInteger)arg0 getAttributeForGuide:(*int)arg1 ;
-(BOOL)_shouldAlwaysDiagnoseFocusInteractionEligibility;
-(BOOL)_shouldAnimatePropertyAdditivelyWithKey:(id)arg0 ;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg0 ;
-(BOOL)_shouldAppendTextInViewDescription;
-(BOOL)_shouldApplyExclusiveTouch;
-(BOOL)_shouldDecodeSubviews;
-(BOOL)_shouldDelayTouchForSystemGestures:(id)arg0 ;
-(BOOL)_shouldEnclosedScrollViewFlashIndicators:(id)arg0 ;
-(BOOL)_shouldIgnoreAutofillSave;
-(BOOL)_shouldInheritScreenScaleAsContentScaleFactor;
-(BOOL)_shouldInvalidateBaselineConstraintsForSize:(struct CGSize )arg0 oldSize:(struct CGSize )arg1 ;
-(BOOL)_shouldResignFirstResponderWithInteractionDisabled;
-(BOOL)_shouldUpdateFocusInContext:(id)arg0 ;
-(BOOL)_shouldUseViewForSceneDraggingBehavior;
-(BOOL)_strictDescendantNeedsDoubleUpdateConstraints;
-(BOOL)_strictDescendantNeedsDoubleUpdateConstraintsIsInvalid;
-(BOOL)_subclassImplementsDrawRect;
-(BOOL)_subviewPreventsSkipLayout:(id)arg0 ;
-(BOOL)_subviewWantsAutolayout;
-(BOOL)_supportsBecomeFirstResponderWhenPossible;
-(BOOL)_supportsContentDimensionVariables;
-(BOOL)_touchesInsideShouldHideCalloutBar;
-(BOOL)_uiib_hostsLayoutEngine;
-(BOOL)_uiib_tryToAddConstraint:(id)arg0 roundingAdjustment:(CGFloat)arg1 mutuallyExclusiveConstraints:(*id)arg2 ;
-(BOOL)_uili_isFocusGuide;
-(BOOL)_uili_requiresObservationForVariable:(id)arg0 ;
-(BOOL)_unapplyMotionEffect:(id)arg0 ;
-(BOOL)_unconditionallyWantsSetBoundsFromISEngineLayout;
-(BOOL)_useContentDimensionVariablesForConstraintLowering;
-(BOOL)_usesAutoresizingConstraints;
-(BOOL)_usesLayoutEngineHostingConstraints;
-(BOOL)_usesMinimumSafeAreas;
-(BOOL)_wantsAnimationRestoration;
-(BOOL)_wantsAutolayout;
-(BOOL)_wantsBaselineUpdatingFollowingConstraintsPass;
-(BOOL)_wantsDeepDrawing;
-(BOOL)_wantsKeyCommandsWhenDeferred;
-(BOOL)accessibilityInvertFilterApplied;
-(BOOL)autoresizesSubviews;
-(BOOL)becomeFirstResponder;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)cancelMouseTracking;
-(BOOL)cancelTouchTracking;
-(BOOL)clearsContextBeforeDrawing;
-(BOOL)clipsToBounds;
-(BOOL)containsView:(id)arg0 ;
-(BOOL)drawViewHierarchyInRect:(struct CGRect )arg0 ;
-(BOOL)drawViewHierarchyInRect:(struct CGRect )arg0 afterScreenUpdates:(BOOL)arg1 ;
-(BOOL)endEditing:(BOOL)arg0 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg0 ;
-(BOOL)hasAmbiguousLayout;
-(BOOL)insetsLayoutMarginsFromSafeArea;
-(BOOL)isAccessibilityElementByDefault;
-(BOOL)isDescendantOfView:(id)arg0 ;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
-(BOOL)isEnabled;
-(BOOL)isExclusiveTouch;
-(BOOL)isHidden;
-(BOOL)isHiddenOrHasHiddenAncestor;
-(BOOL)isMultipleTouchEnabled;
-(BOOL)isOpaque;
-(BOOL)layoutMarginsFollowReadableWidth;
-(BOOL)needsDisplay;
-(BOOL)needsDisplayOnBoundsChange;
-(BOOL)needsUpdateConstraints;
-(BOOL)nsis_shouldIntegralizeVariable:(id)arg0 ;
-(BOOL)nsis_valueOfVariableIsUserObservable:(id)arg0 ;
-(BOOL)nsli_canHostIndependentVariableAnchor;
-(BOOL)nsli_defaultResolvedValue:(*CGFloat)arg0 forSymbolicConstant:(id)arg1 inConstraint:(id)arg2 error:(*id)arg3 ;
-(BOOL)nsli_isCollectingConstraintChangesForLaterCoordinatedFlush:(id)arg0 ;
-(BOOL)nsli_isFlipped;
-(BOOL)nsli_isLegalConstraintItem;
-(BOOL)nsli_isRTL;
-(BOOL)nsli_lowerAttribute:(int)arg0 intoExpression:(id)arg1 withCoefficient:(CGFloat)arg2 container:(id)arg3 ;
-(BOOL)nsli_lowerAttribute:(int)arg0 intoExpression:(id)arg1 withCoefficient:(CGFloat)arg2 forConstraint:(id)arg3 ;
-(BOOL)nsli_lowerAttribute:(int)arg0 intoExpression:(id)arg1 withCoefficient:(CGFloat)arg2 forConstraint:(id)arg3 onBehalfOfLayoutGuide:(id)arg4 ;
-(BOOL)nsli_removeConstraint:(id)arg0 ;
-(BOOL)nsli_resolvedValue:(*CGFloat)arg0 forSymbolicConstant:(id)arg1 inConstraint:(id)arg2 error:(*id)arg3 ;
-(BOOL)pointInside:(struct CGPoint )arg0 forEvent:(struct __GSEvent *)arg1 ;
-(BOOL)pointInside:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(BOOL)preservesSuperviewLayoutMargins;
-(BOOL)shouldUpdateFocusInContext:(id)arg0 ;
-(BOOL)translatesAutoresizingMaskIntoConstraints;
-(BOOL)useBlockyMagnificationInClassic;
-(CGFloat)_autolayoutSpacingAtEdge:(int)arg0 forAttribute:(NSInteger)arg1 inContainer:(id)arg2 isGuide:(BOOL)arg3 ;
-(CGFloat)_autolayoutSpacingAtEdge:(int)arg0 forAttribute:(NSInteger)arg1 nextToNeighbor:(id)arg2 edge:(int)arg3 attribute:(NSInteger)arg4 multiplier:(CGFloat)arg5 ;
-(CGFloat)_baselineOffsetFromBottom;
-(CGFloat)_baselineOffsetFromNearestEdgeForLayoutAttribute:(NSInteger)arg0 ;
-(CGFloat)_calculatedIntrinsicHeight;
-(CGFloat)_contentMargin;
-(CGFloat)_convertVisualAltitude:(CGFloat)arg0 fromView:(id)arg1 ;
-(CGFloat)_convertVisualAltitude:(CGFloat)arg0 toView:(id)arg1 ;
-(CGFloat)_defaultAutolayoutSpacing;
-(CGFloat)_findAutolayoutHeightConstraint;
-(CGFloat)_firstBaselineOffsetFromTop;
-(CGFloat)_imageButtonMargin;
-(CGFloat)_paddingForBaselineSpacingFromEdge:(int)arg0 toNeighborEdge:(int)arg1 ;
-(CGFloat)_preferredDurationForFocusAnimation:(NSInteger)arg0 inContext:(id)arg1 ;
-(CGFloat)_preferredDurationScaleFactorForFocusAnimation:(NSInteger)arg0 inContext:(id)arg1 ;
-(CGFloat)_preferredMaxLayoutWidth;
-(CGFloat)_proportionalFillLengthForOrderedArrangement:(id)arg0 relevantParentAxis:(NSInteger)arg1 ;
-(CGFloat)_textButtonMargin;
-(CGFloat)_touchSloppinessFactor;
-(CGFloat)_uimorphingView_getInitialAlpha;
-(CGFloat)_visualAltitude;
-(CGFloat)alpha;
-(CGFloat)contentScaleFactor;
-(CGFloat)nsli_marginOffsetForAttribute:(NSInteger)arg0 ;
-(Class)_appearanceGuideClass;
-(NSInteger)_backdropMaskViewFlags;
-(NSInteger)_currentUserInterfaceIdiom;
-(NSInteger)_defaultTintAdjustmentMode;
-(NSInteger)_depthComparison:(id)arg0 ;
-(NSInteger)_disableLayoutFlushingCount;
-(NSInteger)_focusedSound;
-(NSInteger)_sceneDraggingBehaviorOnPan;
-(NSInteger)_systemDefaultFocusGroupPriority;
-(NSInteger)_topToBottomLeftToRightViewCompare:(id)arg0 ;
-(NSInteger)compareTextEffectsOrdering:(id)arg0 ;
-(NSInteger)contentMode;
-(NSInteger)tintAdjustmentMode;
-(NSUInteger)_accessibilityInterfaceStyleIntent;
-(NSUInteger)_accessibilityResolvedInterfaceStyle;
-(NSUInteger)_clipCorners;
-(NSUInteger)_clipCornersOfView:(id)arg0 ;
-(NSUInteger)_edgesPropagatingSafeAreaInsetsToSubviews;
-(NSUInteger)_focusGuideBehaviorForFocusMovement:(id)arg0 ;
-(NSUInteger)_speedBumpEdges;
-(NSUInteger)autoresizingMask;
-(NSUInteger)edgesInsettingLayoutMarginsFromSafeArea;
-(NSUInteger)edgesPreservingSuperviewLayoutMargins;
-(NSUInteger)nsli_autoresizingMask;
-(float)_priorityForEngineHostConstraints;
-(float)charge;
-(float)contentCompressionResistancePriorityForAxis:(NSInteger)arg0 ;
-(float)contentHuggingPriorityForAxis:(NSInteger)arg0 ;
-(id)_accessibilityDragInteractionsForAddingItems;
-(id)_accessibilityFocusContainers:(BOOL)arg0 ;
-(id)_accessibilityHigherContrastTintColorForColor:(id)arg0 ;
-(id)_actingParentViewForGestureRecognizers;
-(id)_activityItemsConfigurationAtLocation:(struct CGPoint )arg0 ;
-(id)_alignmentDebuggingOverlayCreateIfNecessary:(BOOL)arg0 ;
-(id)_allLayoutEngines;
-(id)_allSubviews;
-(id)_appearanceContainer;
-(id)_appearanceTraitCollection;
-(id)_attributesForFocusRegionContent;
-(id)_autolayoutTrace;
-(id)_autolayoutTraceAtLevel:(NSInteger)arg0 recursively:(BOOL)arg1 ;
-(id)_autolayoutTraceRecursively:(BOOL)arg0 ;
-(id)_backdropGroups;
-(id)_backdropMaskViewForFlag:(NSInteger)arg0 ;
-(id)_backgroundColor;
-(id)_baselineViewForConstraint:(id)arg0 forFirstItem:(BOOL)arg1 withOffset:(*CGFloat)arg2 ;
-(id)_basicAnimationWithKeyPath:(id)arg0 ;
-(id)_centerExpressionInContainer:(id)arg0 vertical:(BOOL)arg1 contentInsetScale:(CGFloat)arg2 engine:(id)arg3 ;
-(id)_childFocusRegionsInRect:(struct CGRect )arg0 inCoordinateSpace:(id)arg1 ;
-(id)_childFocusViews;
-(id)_clippedViewHierarchyDescription;
-(id)_colorViewBoundsOverlayCreateIfNecessary:(BOOL)arg0 ;
-(id)_constraintsArray;
-(id)_constraintsBrokenWhileUnsatisfiableConstraintsLoggingSuspended;
-(id)_constraintsBrokenWhileUnsatisfiableConstraintsLoggingSuspendedCreateIfNecessary:(BOOL)arg0 ;
-(id)_constraintsValidityDescription;
-(id)_containerForContentSizeConstraints;
-(id)_containingScrollView;
-(id)_contentHeightVariable;
-(id)_contentSizeCategoryLimitedTraitCollection:(id)arg0 ;
-(id)_contentWidthVariable;
-(id)_contentXOffsetVariable;
-(id)_contentYOffsetVariable;
-(id)_cornerCurve;
-(id)_currentFocusAnimationCoordinator;
-(id)_debuggableDescriptionForConstraintsAffectingAxis:(NSInteger)arg0 ;
-(id)_debuggableDescriptionForConstraintsAffectingHorizontalAxis;
-(id)_debuggableDescriptionForConstraintsAffectingVerticalAxis;
-(id)_defaultFocusEffect;
-(id)_defaultLayoutDescription;
-(id)_deferredAnimationForKey:(id)arg0 ;
-(id)_descendantWithAmbiguousLayout;
-(id)_dimensionExpressionInContainer:(id)arg0 vertical:(BOOL)arg1 useContentVariables:(BOOL)arg2 engine:(id)arg3 ;
-(id)_disabledColor;
-(id)_dummyFittingSizeInfo;
-(id)_edgeExpressionInContainer:(id)arg0 vertical:(BOOL)arg1 max:(BOOL)arg2 contentInsetScale:(CGFloat)arg3 engine:(id)arg4 ;
-(id)_effectiveBoundingPathAndBoundingPathView:(*id)arg0 ;
-(id)_enclosingInterfaceActionGroupView;
-(id)_enclosingInterfaceActionRepresentationView;
-(id)_enclosingScrollableScrollerIncludingSelf;
-(id)_enclosingScrollerIncludingSelf;
-(id)_encodableSubviews;
-(id)_engineHostingWidthConstraint;
-(id)_findInteractionIfExists;
-(id)_firstAncestorInteractionConformingToProtocol:(id)arg0 ;
-(id)_firstCommonAncestorToView:(id)arg0 givenCommonAncestor:(id)arg1 ;
-(id)_firstResponder;
-(id)_focusDebugOverlayParentView;
-(id)_focusGesturesForFailureRequirements;
-(id)_focusRegionFocusSystem;
-(id)_focusRegionGuides;
-(id)_focusRegionView;
-(id)_fulfillPromisedFocusRegion;
-(id)_generateBackdropMaskImage;
-(id)_generateBackdropMaskViewForFlag:(NSInteger)arg0 ;
-(id)_getGhostPortal;
-(id)_hierarchyRepresentation;
-(id)_hitTest:(struct CGPoint )arg0 withEvent:(id)arg1 windowServerHitTestWindow:(id)arg2 ;
-(id)_idleModeLayoutAttributes;
-(id)_imageFromRect:(struct CGRect )arg0 ;
-(id)_imageFromRect:(struct CGRect )arg0 gamut:(NSInteger)arg1 ;
-(id)_inheritedInteractionTintColor;
-(id)_initWithLayer:(id)arg0 ;
-(id)_initialValueForKey:(id)arg0 ;
-(id)_initialValueForLayer:(id)arg0 keyPath:(id)arg1 usePresentationValue:(BOOL)arg2 ;
-(id)_interceptEvent:(id)arg0 ;
-(id)_interceptMouseEvent:(struct __GSEvent *)arg0 ;
-(id)_largeContentStoredProperties;
-(id)_largeContentStoredPropertiesCreatingIfNecessary:(BOOL)arg0 ;
-(id)_largeContentViewerGestureManager;
-(id)_largeContentViewerItemAtPoint:(struct CGPoint )arg0 ;
-(id)_layoutDebuggingTitle;
-(id)_layoutDescriptionIfDifferentFromDefault;
-(id)_layoutRect;
-(id)_layoutVariablesWithAmbiguousValue;
-(id)_lfld_minimalDescription;
-(id)_lowerExpressionOneLevelWithCurrentXExpression:(id)arg0 YExpression:(id)arg1 vertical:(BOOL)arg2 container:(id)arg3 engine:(id)arg4 ;
-(id)_motionEffects;
-(id)_nextKeyResponder;
-(id)_normalInheritedTintColor;
-(id)_outermostLayer;
-(id)_parentDescription;
-(id)_preferredConfigurationForFocusAnimation:(NSInteger)arg0 inContext:(id)arg1 ;
-(id)_preferredFocusRegionCoordinateSpace;
-(id)_previewingSegueTemplateStorageForLocation:(struct CGPoint )arg0 inView:(id)arg1 ;
-(id)_previousFittingSizeInfo;
-(id)_previousKeyResponder;
-(id)_projectedTargetForKey:(id)arg0 decelerationFactor:(CGFloat)arg1 ;
-(id)_providedFocusFallbackScroller;
-(id)_recursiveConstraintsTraceAtLevel:(NSInteger)arg0 ;
-(id)_recursiveLayoutEngineDescription;
-(id)_referenceView;
-(id)_representationOfHierarchyForXcode;
-(id)_rootForKeyResponderCycle;
-(id)_rootInputWindowController;
-(id)_rootView;
-(id)_screen;
-(id)_scriptingInfo;
-(id)_scrollViewWantingUpdateInConstraint:(id)arg0 ;
-(id)_scroller;
-(id)_sourceViewForPresentationInWindow:(id)arg0 ;
-(id)_systemDefaultFocusGroupIdentifier;
-(id)_targetVelocityForKey:(id)arg0 ;
-(id)_textServicesResponderProxy;
-(id)_tintColorArchivingKey;
-(id)_traitCollectionForChildEnvironment:(id)arg0 ;
-(id)_traitStorageConstraints;
-(id)_traitStorageSubviews;
-(id)_uili_existingBaseFrameVariables;
-(id)_uili_existingObservationEligibleLayoutVariables;
-(id)_uili_observableLayoutEngineForBaseFrameVariables:(BOOL)arg0 ;
-(id)_uis_outline;
-(id)_velocityForKey:(id)arg0 ;
-(id)_viewControllerForAncestor;
-(id)_viewControllerToNotifyOnLayoutSubviews;
-(id)_viewForBaselineLayout;
-(id)_viewForLoweringBaselineLayoutAttribute:(int)arg0 ;
-(id)_viewsJostledDuringUpdateConstraintsPass;
-(id)_viewsJostledDuringUpdateConstraintsPassSuppressingDebugAssertion:(BOOL)arg0 ;
-(id)_visualRecursiveDescription;
-(id)_window;
-(id)actionForLayer:(id)arg0 forKey:(id)arg1 ;
-(id)backgroundColor;
-(id)constraints;
-(id)constraintsAffectingLayoutForAxis:(NSInteger)arg0 ;
-(id)constraintsAffectingLayoutForAxis:(NSInteger)arg0 ofItem:(id)arg1 ;
-(id)engine:(id)arg0 markerForConstraintToBreakAmongConstraints:(id)arg1 ;
-(id)focusGuides;
-(id)focusItemsInRect:(struct CGRect )arg0 ;
-(id)hitTest:(struct CGPoint )arg0 forEvent:(struct __GSEvent *)arg1 ;
-(id)hitTest:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)initWithSize:(struct CGSize )arg0 ;
-(id)inputResponderController;
-(id)interactions;
-(id)layoutGuides;
-(id)maskView;
-(id)motionEffects;
-(id)nextResponder;
-(id)nsis_descriptionOfVariable:(id)arg0 ;
-(id)nsli_constraintWithAnchor:(id)arg0 relatedBy:(NSInteger)arg1 toAnchor:(id)arg2 withSystemSpacingMultipliedBy:(CGFloat)arg3 ;
-(id)nsli_contentHeightVariable;
-(id)nsli_contentWidthVariable;
-(id)nsli_contentXOffsetVariable;
-(id)nsli_contentYOffsetVariable;
-(id)nsli_heightVariable;
-(id)nsli_installedConstraints;
-(id)nsli_layoutAnchorForAttribute:(NSInteger)arg0 ;
-(id)nsli_layoutMarginsItem;
-(id)nsli_superitem;
-(id)nsli_widthVariable;
-(id)recursiveDescription;
-(id)resizableSnapshotFromRect:(struct CGRect )arg0 withCapInsets:(struct UIEdgeInsets )arg1 ;
-(id)resizableSnapshotViewFromRect:(struct CGRect )arg0 afterScreenUpdates:(BOOL)arg1 withCapInsets:(struct UIEdgeInsets )arg2 ;
-(id)resizableSnapshotViewFromRect:(struct CGRect )arg0 withCapInsets:(struct UIEdgeInsets )arg1 ;
-(id)scriptingInfoWithChildren;
-(id)snapshot;
-(id)snapshotView;
-(id)snapshotViewAfterScreenUpdates:(BOOL)arg0 ;
-(id)subviews;
-(id)superview;
-(id)textInputView;
-(id)tintColor;
-(id)viewForBaselineLayout;
-(id)viewForFirstBaselineLayout;
-(id)viewForLastBaselineLayout;
-(id)viewWithTag:(NSInteger)arg0 ;
-(id)window;
-(int)_style;
-(int)nsis_orientationHintForVariable:(id)arg0 ;
-(int)textEffectsVisibilityLevel;
-(int)textEffectsVisibilityLevelInKeyboardWindow;
-(struct ? )_baselineOffsetsAtSize:(struct CGSize )arg0 ;
-(struct CGColor *)_backgroundCGColor;
-(struct CGImage *)newSnapshotWithRect:(struct CGRect )arg0 ;
-(struct CGPoint )_getSourceCenter;
-(struct CGPoint )_nsis_origin;
-(struct CGPoint )anchorPoint;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 fromCoordinateSpace:(id)arg1 ;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 fromView:(id)arg1 ;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 toCoordinateSpace:(id)arg1 ;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 toView:(id)arg1 ;
-(struct CGPoint )origin;
-(struct CGPoint )position;
-(struct CGRect )_alignmentBounds;
-(struct CGRect )_alignmentFrame;
-(struct CGRect )_alignmentRectForBounds:(struct CGRect )arg0 ;
-(struct CGRect )_boundsForAlignmentRect:(struct CGRect )arg0 ;
-(struct CGRect )_boundsForSceneDraggingConstrainedToSafeArea:(BOOL)arg0 ;
-(struct CGRect )_clippingRectInCoordinateSpace:(id)arg0 ;
-(struct CGRect )_compatibleBounds;
-(struct CGRect )_convertViewPointToSceneSpaceForKeyboard:(struct CGRect )arg0 ;
-(struct CGRect )_defaultFocusRegionFrame;
-(struct CGRect )_focusRegionFrame;
-(struct CGRect )_focusRegionFrameInCoordinateSpace:(id)arg0 ;
-(struct CGRect )_inscribedRectInBoundingPathByInsettingRect:(struct CGRect )arg0 onEdges:(NSUInteger)arg1 withOptions:(NSUInteger)arg2 ;
-(struct CGRect )_largestInscribedRectInBoundingPathWithCenter:(struct CGPoint )arg0 aspectRatio:(CGFloat)arg1 ;
-(struct CGRect )_layoutGuide:(id)arg0 adjustedLayoutFrameForFrame:(struct CGRect )arg1 ;
-(struct CGRect )_nsis_compatibleBoundsInEngine:(id)arg0 ;
-(struct CGRect )_nsis_layoutRectFromHostingViewInEngine:(id)arg0 ;
-(struct CGRect )_rectToScrollToVisibleInCellInWindow:(id)arg0 ;
-(struct CGRect )_rectTuckedAgainstBoundingPathEdge:(NSUInteger)arg0 withSize:(CGFloat)arg1 cornerRadii:(struct UIRectCornerRadii )arg2 minimumPadding:(CGFloat)arg3 ;
-(struct CGRect )_rectTuckedInBoundingPathCorner:(NSUInteger)arg0 withSize:(struct CGSize )arg1 cornerRadii:(struct UIRectCornerRadii )arg2 minimumPadding:(CGFloat)arg3 ;
-(struct CGRect )_responderExternalTouchRectForWindow:(id)arg0 ;
-(struct CGRect )_responderSelectionRectForWindow:(id)arg0 ;
-(struct CGRect )_sourceRectForPresentationInWindow:(id)arg0 ;
-(struct CGRect )_visualAltitudeSensitiveBoundsWithInfiniteEdges:(NSUInteger)arg0 ;
-(struct CGRect )alignmentRectForFrame:(struct CGRect )arg0 ;
-(struct CGRect )contentStretch;
-(struct CGRect )convertRect:(struct CGRect )arg0 fromCoordinateSpace:(id)arg1 ;
-(struct CGRect )convertRect:(struct CGRect )arg0 fromView:(id)arg1 ;
-(struct CGRect )convertRect:(struct CGRect )arg0 toCoordinateSpace:(id)arg1 ;
-(struct CGRect )convertRect:(struct CGRect )arg0 toView:(id)arg1 ;
-(struct CGRect )extent;
-(struct CGRect )frameForAlignmentRect:(struct CGRect )arg0 ;
-(struct CGRect )hitRect;
-(struct CGRect )visibleBounds;
-(struct CGSize )_calculatedSystemLayoutSizeFittingSize:(struct CGSize )arg0 withHorizontalFittingPriority:(float)arg1 verticalFittingPriority:(float)arg2 hasIntentionallyCollapsedHeight:(*BOOL)arg3 ;
-(struct CGSize )_contentCompressionResistancePriorities;
-(struct CGSize )_contentHuggingPriorities;
-(struct CGSize )_intrinsicSizeWithinSize:(struct CGSize )arg0 ;
-(struct CGSize )_layoutSizeThatFits:(struct CGSize )arg0 fixedAxes:(NSUInteger)arg1 ;
-(struct CGSize )_nsis_contentSize;
-(struct CGSize )_nsis_layoutSizeInEngine:(id)arg0 ;
-(struct CGSize )_preferredLayoutEngineToUserScalingCoefficients;
-(struct CGSize )_systemLayoutSizeFittingSize:(struct CGSize )arg0 withHorizontalFittingPriority:(float)arg1 verticalFittingPriority:(float)arg2 ;
-(struct CGSize )_systemLayoutSizeFittingSize:(struct CGSize )arg0 withHorizontalFittingPriority:(float)arg1 verticalFittingPriority:(float)arg2 hasIntentionallyCollapsedHeight:(*BOOL)arg3 ;
-(struct CGSize )_visualAltitudeBias;
-(struct CGSize )convertSize:(struct CGSize )arg0 fromView:(id)arg1 ;
-(struct CGSize )convertSize:(struct CGSize )arg0 toView:(id)arg1 ;
-(struct CGSize )intrinsicContentSize;
-(struct CGSize )nsli_convertSizeFromEngineSpace:(struct CGSize )arg0 ;
-(struct CGSize )nsli_convertSizeToEngineSpace:(struct CGSize )arg0 ;
-(struct CGSize )nsli_engineToUserScalingCoefficients;
-(struct CGSize )nsli_engineToUserScalingCoefficientsInEngine:(id)arg0 ;
-(struct CGSize )size;
-(struct CGSize )sizeThatFits:(struct CGSize )arg0 ;
-(struct CGSize )systemLayoutSizeFittingSize:(struct CGSize )arg0 ;
-(struct CGSize )systemLayoutSizeFittingSize:(struct CGSize )arg0 withHorizontalFittingPriority:(float)arg1 verticalFittingPriority:(float)arg2 ;
-(struct NSDirectionalEdgeInsets )directionalLayoutMargins;
-(struct UIEdgeInsets )_concreteDefaultLayoutMargins;
-(struct UIEdgeInsets )_focusableContentMargins;
-(struct UIEdgeInsets )_minimumSafeAreaInsets;
-(struct UIEdgeInsets )_safeAreaInsetsForFrame:(struct CGRect )arg0 inSuperview:(id)arg1 ;
-(struct UIEdgeInsets )_safeAreaInsetsInSuperview:(id)arg0 ;
-(struct UIEdgeInsets )_touchInsets;
-(struct UIEdgeInsets )alignmentRectInsets;
-(struct UIEdgeInsets )layoutMargins;
-(unsigned int)_secureName;
-(void)_accessibilityBeginDragAtPlatformPoint:(struct CGPoint )arg0 endpoint:(id)arg1 completion:(id)arg2 ;
-(void)_accessibilityBeginDragAtPoint:(struct CGPoint )arg0 endpoint:(id)arg1 completion:(id)arg2 ;
-(void)_accessibilitySetInterfaceStyleIntent:(NSUInteger)arg0 ;
-(void)_accessibilitySetResolvedInterfaceStyle:(NSUInteger)arg0 ;
-(void)_accumulateViewConstraintsIntoArray:(id)arg0 ;
-(void)_addBoundingPathChangeObserver:(id)arg0 ;
-(void)_addBoundsMatchingConstraintsForView:(id)arg0 ;
-(void)_addBoundsMatchingSubview:(id)arg0 ;
-(void)_addCenterExpressionToExpression:(id)arg0 isVertical:(BOOL)arg1 ;
-(void)_addConstraintPendingAnimatedChanges:(id)arg0 ;
-(void)_addMotionEffect:(id)arg0 ;
-(void)_addSubview:(id)arg0 positioned:(NSInteger)arg1 relativeTo:(id)arg2 ;
-(void)_ancestorWillUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)_animatePropertyWithKey:(id)arg0 currentValue:(id)arg1 targetValue:(id)arg2 newValueCallback:(id)arg3 ;
-(void)_applyAppearanceInvocations;
-(void)_applyISEngineLayoutValuesToBoundsOnly:(BOOL)arg0 ;
-(void)_applyPendingTraitStorageConstraints;
-(void)_beginOcclusion:(id)arg0 ;
-(void)_calculateSubviewAlignmentFrame:(struct CGRect *)arg0 superviewAlignmentBounds:(struct CGRect *)arg1 forAutoresizingMask:(NSUInteger)arg2 preservingNonzeroSuperviewAlignmentBoundsOriginForCompatibility:(BOOL)arg3 ;
-(void)_clearAnimationFilters;
-(void)_clearBecomeFirstResponderWhenCapable;
-(void)_clearConstraintsBrokenWhileUnsatisfiableConstraintsLoggingSuspended;
-(void)_clearLayoutVariableObservationsOnlyToSupportTAMICChange:(BOOL)arg0 ;
-(void)_clearSafeAreaInsets;
-(void)_collectKeyViews:(id)arg0 ;
// -(void)_collectKeyViews:(id)arg0 visibilityTest:(id)arg1 passingTest:(unk)arg2  ;
// -(void)_collectKeyViews:(id)arg0 visibilityTest:(id)arg1 passingTest:(unk)arg2 subviewsTest:(id)arg3  ;
-(void)_configureAutolayoutFlagsNeedingLayout:(BOOL)arg0 ;
-(void)_constantsForHorizontalAutoresizingConstraints:(*CGFloat)arg0 ;
-(void)_constantsForVerticalAutoresizingConstraints:(*CGFloat)arg0 ;
-(void)_constrainViewToSuperview;
-(void)_constraints_subviewWillChangeSuperview:(id)arg0 ;
-(void)_contentSizeCategoryLimitsDidChange;
-(void)_convertToAutolayoutSizingIfNecessary;
-(void)_createJostledViewsIfNecessary;
-(void)_decodeLargeContentViewerPropertiesWithCoder:(id)arg0 ;
-(void)_decrementHiddenManagedByLayoutArrangementCount;
-(void)_decrementUnsatisfiableConstraintsLoggingSuspensionCount;
-(void)_detectAndHandleClippedView;
-(void)_diagnoseFocusInteractionEligibilityForReport:(id)arg0 ;
-(void)_diagnoseFocusabilityForReport:(id)arg0 ;
-(void)_didAddDependentConstraint:(id)arg0 ;
-(void)_didChangeFromIdiom:(NSInteger)arg0 onScreen:(id)arg1 traverseHierarchy:(BOOL)arg2 ;
-(void)_didChangeKeyplaneWithContext:(id)arg0 ;
-(void)_didInvalidateIntrinsicContentSize;
-(void)_didMoveFromWindow:(id)arg0 toWindow:(id)arg1 ;
-(void)_didRemoveDependentConstraint:(id)arg0 ;
-(void)_didRemoveSubview:(id)arg0 ;
-(void)_didScroll;
-(void)_didStopBeingDisplayedInPointerContentEffect;
-(void)_didUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)_disableLayoutFlushing;
-(void)_discardLayoutEngine:(id)arg0 ;
-(void)_dumpClippedViewWithScreenshotIfNecessary;
-(void)_dynamicUserInterfaceTraitDidChange;
-(void)_enableLayerKitPatternDrawing:(BOOL)arg0 ;
-(void)_enableLayoutFlushing;
-(void)_encodeBackgroundColorWithCoder:(id)arg0 ;
-(void)_encodeFrameWithCoder:(id)arg0 ;
-(void)_encodeLargeContentViewerPropertiesWithCoder:(id)arg0 ;
-(void)_endOcclusion:(id)arg0 ;
-(void)_ensureViewsAreInstalledInRelativeOrder:(*id)arg0 viewCount:(NSInteger)arg1 insertionStartIndex:(NSInteger)arg2 ;
-(void)_enumerateDescendentViews:(id)arg0 ;
-(void)_faultInContentOffsetGuide;
-(void)_faultInGuidesForConstraint:(id)arg0 ;
-(void)_finishTrackingForAnimationRestoration;
-(void)_flushConstraintsPendingAnimatedChanges;
// -(void)_gatherKeyResponders:(id)arg0 indexOfSelf:(*NSUInteger)arg1 visibilityTest:(id)arg2 passingTest:(unk)arg3 subviewsTest:(id)arg4  ;
-(void)_generateDeferredAnimations:(id)arg0 ;
-(void)_geometryChanged:(struct ? *)arg0 forAncestor:(id)arg1 ;
-(void)_handleDoubleUpdateConstraintsIfNecessary;
-(void)_handleLayoutArrangementConstraintsIfNecessary;
-(void)_handleLayoutEngineHostingConstraintsIfNecessary;
-(void)_handleSizeConstraintsAsAppropriate;
-(void)_handleTraitChangeForHierarchyChange;
-(void)_incrementHiddenManagedByLayoutArrangementCount;
-(void)_incrementUnsatisfiableConstraintsLoggingSuspensionCount;
-(void)_informContainerThatSubviewsNeedUpdateConstraints;
-(void)_informContainerThatSubviewsNeedUpdateConstraintsNeedingLayout:(BOOL)arg0 ;
-(void)_informSuperviewChainThatDescendantNeedsDoubleUpdateConstraintsPass;
-(void)_informSuperviewChainThatStrictDescendantNeedsDoubleUpdateConstraintsIsInvalidIncludingSelf:(BOOL)arg0 ;
-(void)_initializeHostedLayoutEngine;
-(void)_initializeLayoutEngine;
-(void)_insertBoundsMatchingSubview:(id)arg0 aboveSubview:(id)arg1 ;
-(void)_insertBoundsMatchingSubview:(id)arg0 belowSubview:(id)arg1 ;
-(void)_intrinsicContentSizeInvalidatedForChildView:(id)arg0 ;
-(void)_invalidateAppearance;
-(void)_invalidateAppearanceForSubviewsOfClass:(Class)arg0 ;
-(void)_invalidateAppearanceForTraitCollection:(id)arg0 ;
-(void)_invalidateBaselineConstraints;
-(void)_invalidateIntrinsicContentSizeNeedingLayout:(BOOL)arg0 ;
-(void)_invalidateLayoutEngineHostConstraints;
-(void)_invalidateSubviewCache;
-(void)_invalidateSystemLayoutSizeFittingSizeAtEngineDelegateLevel;
-(void)_is_layout;
-(void)_is_setNeedsLayout;
-(void)_layoutMarginsDidChangeFromOldMargins:(struct UIEdgeInsets )arg0 ;
-(void)_lfld_addConstraintsAffectingVariableValueChange:(id)arg0 ;
-(void)_lfld_addGeometryChangeRecordWithPropertyName:(id)arg0 value:(id)arg1 ;
-(void)_lfld_addSetNeedsLayoutCallStack:(id)arg0 ;
-(void)_lfld_addVariableChangeRecordForVariable:(id)arg0 inLayoutEngine:(id)arg1 ;
-(void)_lfld_discardLastCurrentLayoutMethodName;
-(void)_lfld_incrementCount;
-(void)_lfld_prepareToResetCountIfNecessary;
-(void)_lfld_pushCurrentLayoutMethodName:(id)arg0 ;
-(void)_lfld_resetCount;
-(void)_localOverrideTraitCollectionWillChange:(id)arg0 ;
-(void)_makeSubtreePerformSelector:(SEL)arg0 withObject:(id)arg1 ;
-(void)_makeSubtreePerformSelector:(SEL)arg0 withObject:(id)arg1 withObject:(id)arg2 copySublayers:(BOOL)arg3 ;
-(void)_makeTemporaryInternalConstraintsWithEngine:(id)arg0 ignoreAutoresizingMaskConstraints:(BOOL)arg1 returningConstraintsForViewsNeedingSecondPass:(*id)arg2 currentTargetWidth:(CGFloat)arg3 ;
-(void)_measureViewWithSize:(struct CGSize )arg0 temporaryConstraints:(id)arg1 suspendingSystemConstraints:(BOOL)arg2 withOptimizedEngineBlock:(id)arg3 ;
-(void)_mergeConstraintsBrokenWhileUnsatisfiableConstraintsLoggingSuspendedToAncestor:(id)arg0 ;
-(void)_monitoredView:(id)arg0 didMoveFromSuperview:(id)arg1 toSuperview:(id)arg2 ;
-(void)_monitoredView:(id)arg0 willMoveFromSuperview:(id)arg1 toSuperview:(id)arg2 ;
-(void)_needsDoubleUpdateConstraintsPassMayHaveChangedFrom:(BOOL)arg0 ;
-(void)_noteLocalTraitsDidChangeRecursively;
-(void)_noteTraitsDidChangeRecursively;
-(void)_notifyReferenceViewSizeChange;
-(void)_nsis_center:(struct CGPoint *)arg0 bounds:(struct CGRect *)arg1 inEngine:(id)arg2 ;
-(void)_nsis_center:(struct CGPoint *)arg0 bounds:(struct CGRect *)arg1 inEngine:(id)arg2 forLayoutGuide:(id)arg3 ;
-(void)_nsis_origin:(struct CGPoint *)arg0 bounds:(struct CGRect *)arg1 inEngine:(id)arg2 ;
-(void)_objc_initiateDealloc;
-(void)_observeScrollViewDidScroll:(id)arg0 ;
-(void)_ola_willApplyMultilineTextWidthDisambiguationConstraint;
-(void)_oldUpdateLayoutEngineHostConstraints;
-(void)_parentalLayoutEngineDidChangeTo:(id)arg0 ;
-(void)_popDisableLayoutFlushing;
-(void)_populateArchivedSubviews:(id)arg0 ;
-(void)_prepareForFirstIntrinsicContentSizeCalculation;
-(void)_prepareForSecondIntrinsicContentSizeCalculationWithLayoutEngineBounds:(struct CGRect )arg0 ;
-(void)_prepareForWindowDealloc;
-(void)_prepareForWindowHostingSceneRemoval;
-(void)_processDidChangeRecursivelyFromOldTraits:(id)arg0 toCurrentTraits:(id)arg1 forceNotification:(BOOL)arg2 ;
-(void)_promoteSelfOrDescendantToFirstResponderIfNecessary;
-(void)_pushDisableLayoutFlushing;
-(void)_rebuildLayoutFromScratch;
-(void)_recalculateStrictDescendantNeedsDoubleUpdateConstraints;
-(void)_receiveVisitor:(id)arg0 ;
-(void)_recordConstraintBrokenWhileUnsatisfiableConstraintsLoggingSuspended:(id)arg0 ;
-(void)_recursiveInvalidateDescendantsNeedingDoubleUpdateConstraintsCollectingViews:(id)arg0 ;
-(void)_recursiveUpdateConstraintsIfNeededCollectingViews:(id)arg0 forSecondPass:(BOOL)arg1 ;
-(void)_recursivelyNameLayerTree;
-(void)_registerForGeometryChanges;
-(void)_relaxLayoutEngineHostConstraints;
-(void)_relaxLayoutEngineHostConstraintsForAxis:(NSInteger)arg0 ;
-(void)_removeAllAnimations:(BOOL)arg0 ;
-(void)_removeAllAnimationsIncludingSubviewsTrackingForAnimationRestoration;
-(void)_removeAllRetargetableAnimations:(BOOL)arg0 ;
-(void)_removeAutolayoutSizingConstraints;
-(void)_removeBackdropMaskViews;
-(void)_removeBoundingPathChangeObserver:(id)arg0 ;
-(void)_removeColorViewBoundsOverlays;
-(void)_removeMotionEffect:(id)arg0 ;
-(void)_removePropertyAnimationsForLayerKeyPath:(id)arg0 ;
-(void)_replaceLayer:(id)arg0 ;
-(void)_resetContentRect;
-(void)_resetContentStretch;
-(void)_resetLayoutEngineHostConstraintsForAxis:(NSInteger)arg0 collectingViews:(id)arg1 ;
-(void)_resetNeedsSystemLayoutFittingSizeUpdateInSubtreeForLayoutEngine:(id)arg0 ;
-(void)_resetToBeginningOfDoublePass;
-(void)_resizeWithOldSuperviewSize:(struct CGSize )arg0 ;
-(void)_restoreRemovedAnimationsIncludingSubviews;
-(void)_safeAreaInsetsDidChangeFromOldInsets:(struct UIEdgeInsets )arg0 ;
-(void)_scheduleFaultingInGuidesForConstraint:(id)arg0 ;
-(void)_scheduleUpdateConstraintsPassAsEngineHostNeedingLayout:(BOOL)arg0 ;
-(void)_searchForFocusRegionsInContext:(id)arg0 ;
-(void)_sendUpdateConstraintsIfNecessaryForSecondPass:(BOOL)arg0 ;
-(void)_setAllowsHighContrastForBackgroundColor:(BOOL)arg0 ;
-(void)_setAppearanceIsInvalid:(BOOL)arg0 ;
-(void)_setBackdropMaskView:(id)arg0 forFlag:(NSInteger)arg1 ;
-(void)_setBackdropMaskViewFlags:(NSInteger)arg0 ;
-(void)_setBackgroundColor:(id)arg0 ;
-(void)_setBaselineView:(id)arg0 offset:(CGFloat)arg1 forConstraint:(id)arg2 forFirstItem:(BOOL)arg3 ;
-(void)_setChargeEnabled:(BOOL)arg0 ;
-(void)_setContentCompressionResistancePriorities:(struct CGSize )arg0 ;
-(void)_setContentHuggingPriorities:(struct CGSize )arg0 ;
-(void)_setContentRectInPixels:(struct CGRect )arg0 forContentSize:(struct CGSize )arg1 ;
-(void)_setContentStretchInPixels:(struct CGRect )arg0 forContentSize:(struct CGSize )arg1 shouldTile:(BOOL)arg2 ;
-(void)_setDelaysTouchesForSystemGestures:(BOOL)arg0 ;
-(void)_setDisableLayoutFlushingCount:(NSInteger)arg0 ;
-(void)_setDrawsAsBackdropOverlay:(BOOL)arg0 ;
-(void)_setDrawsAsBackdropOverlayWithBlendMode:(NSInteger)arg0 ;
-(void)_setFirstResponder:(id)arg0 ;
-(void)_setFocusableContentMargins:(struct UIEdgeInsets )arg0 ;
-(void)_setGhostPortal:(id)arg0 ;
-(void)_setHiddenForReuse:(BOOL)arg0 ;
-(void)_setHostsLayoutEngine:(BOOL)arg0 ;
-(void)_setIdleModeLayoutAttributes:(id)arg0 ;
-(void)_setIgnoreBackdropViewsWhenHiding:(BOOL)arg0 ;
-(void)_setIgnoresLayerTransformForSafeAreaInsets:(BOOL)arg0 ;
-(void)_setInAnimatedLayout:(BOOL)arg0 ;
-(void)_setInSecondConstraintsPass:(BOOL)arg0 ;
-(void)_setInterceptMouseEvent:(BOOL)arg0 ;
-(void)_setIsAncestorOfFirstResponder:(BOOL)arg0 ;
-(void)_setLargeContentStoredProperties:(id)arg0 ;
-(void)_setLargeContentViewerGestureManager:(id)arg0 ;
-(void)_setNeedsContentsFormatUpdate;
-(void)_setNeedsNonDeferredFocusUpdate;
-(void)_setNeedsUpdateConstraints;
-(void)_setNeedsUpdateConstraintsNeedingLayout:(BOOL)arg0 ;
-(void)_setPotentiallyHasDanglyConstraints:(BOOL)arg0 ;
-(void)_setPresentationValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setPresentationValue:(id)arg0 velocity:(id)arg1 preferredFrameRateRangeMaximum:(int)arg2 forKey:(id)arg3 ;
-(void)_setPreviousFittingSizeInfo:(id)arg0 ;
-(void)_setRenderConfig:(id)arg0 ;
-(void)_setShouldRasterize:(BOOL)arg0 ;
-(void)_setSourceCenter:(struct CGPoint )arg0 ;
-(void)_setSpeedBumpEdges:(NSUInteger)arg0 ;
-(void)_setSubviewWantsAutolayoutTripWantsAutolayout:(BOOL)arg0 ;
-(void)_setTargetVelocity:(id)arg0 forKey:(id)arg1 ;
-(void)_setTouchInsets:(struct UIEdgeInsets )arg0 ;
-(void)_setTraitStorageConstraints:(id)arg0 ;
-(void)_setTraitStorageList:(id)arg0 ;
-(void)_setTraitStorageSubviews:(id)arg0 ;
-(void)_setVelocity:(id)arg0 forKey:(id)arg1 ;
-(void)_setViewsJostledDuringUpdateConstraintsPass:(id)arg0 ;
-(void)_setVisualAltitude:(CGFloat)arg0 ;
-(void)_setVisualAltitudeBias:(struct CGSize )arg0 ;
-(void)_setWantsAutolayout;
-(void)_snipDangliesWithForce:(BOOL)arg0 repairIfPossibleForViewThatMoved:(id)arg1 newSuperview:(id)arg2 oldSuperview:(id)arg3 ;
-(void)_startObservingVariablesOnlyToSupportTAMICChange:(BOOL)arg0 ;
-(void)_stopObservingVariablesOnlyToSupportTAMICChange:(BOOL)arg0 ;
-(void)_strokeClippedViewIfNecessary;
-(void)_subscribeToScrollNotificationsIfNecessary:(id)arg0 ;
-(void)_switchToLayoutEngine:(id)arg0 ;
-(void)_throwForUnsupportedNonMacIdiomBehaviorWithReason:(id)arg0 ;
-(void)_tintColorDidChange;
-(void)_traitCollectionDidChangeInternal:(struct _UITraitCollectionChangeDescription *)arg0 ;
-(void)_traitCollectionDidChangeOnSubtreeInternal:(struct _UITraitCollectionChangeDescription *)arg0 ;
-(void)_ui_addSubLayoutItem:(id)arg0 ;
-(void)_ui_addToView:(id)arg0 atIndex:(NSInteger)arg1 ;
-(void)_ui_insertSubLayoutItem:(id)arg0 atIndex:(NSInteger)arg1 ;
-(void)_ui_removeFromParentLayoutItem;
-(void)_uiib_invalidateAutoresizingConstraints;
-(void)_uiib_setHostsLayoutEngine:(BOOL)arg0 ;
-(void)_uili_removeLayoutVariableObservationsOnlyToSupportTAMICChange:(BOOL)arg0 ;
-(void)_uili_stashLayoutVariableObservation:(id)arg0 forVariable:(id)arg1 ;
-(void)_uimorphingView_setInitialAlpha:(CGFloat)arg0 ;
-(void)_uinavigationbar_prepareToAppearInNavigationItem:(id)arg0 onLeft:(BOOL)arg1 ;
-(void)_unregisterForGeometryChanges;
-(void)_unsubscribeToScrollNotificationsIfNecessary:(id)arg0 ;
-(void)_updateCombinedInsetsIfNecessary;
-(void)_updateConstraintsAtEngineLevelIfNeeded;
-(void)_updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:(id)arg0 ;
-(void)_updateConstraintsIfNeededCollectingViews:(id)arg0 forSecondPass:(BOOL)arg1 ;
-(void)_updateConstraintsIfNeededWithViewForVariableChangeNotifications:(id)arg0 ;
-(void)_updateInferredLayoutMargins;
-(void)_updateInferredLayoutMarginsFromSuperview:(id)arg0 ;
-(void)_updateLayoutEngineHostConstraints;
-(void)_updateLayoutMarginsGuideConstraintsIfNecessary;
-(void)_updateSafeAreaInsets;
-(void)_updateSystemConstraints;
-(void)_vendedBaselineViewDidMoveForFirst:(BOOL)arg0 ;
-(void)_vendedBaselineViewParametersDidChange;
-(void)_viewDidMoveFromScreen:(id)arg0 toScreen:(id)arg1 ;
-(void)_viewHierarchyUnpreparedForConstraint:(id)arg0 ;
-(void)_webCustomViewWillBeRemovedFromSuperview;
-(void)_willBeginBeingDisplayedInPointerContentEffect;
-(void)_willChangeToIdiom:(NSInteger)arg0 onScreen:(id)arg1 ;
-(void)_willMoveToWindow:(id)arg0 ;
-(void)_willMoveToWindow:(id)arg0 withAncestorView:(id)arg1 ;
-(void)_willUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)_withAutomaticEngineOptimizationDisabledIfEngineExists:(id)arg0 ;
-(void)_withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:(id)arg0 ;
-(void)accessibilityApplyInvertFilter;
-(void)accessibilityUnapplyInvertFilter;
-(void)addAnimation:(id)arg0 forKey:(id)arg1 ;
-(void)addConstraint:(id)arg0 ;
-(void)addConstraints:(id)arg0 ;
-(void)addGestureRecognizer:(id)arg0 ;
-(void)addInteraction:(id)arg0 ;
-(void)addLayoutGuide:(id)arg0 ;
-(void)addMotionEffect:(id)arg0 ;
-(void)addSubview:(id)arg0 ;
-(void)bringSubviewToFront:(id)arg0 ;
-(void)constraintsDidChangeInEngine:(id)arg0 ;
-(void)dealloc;
-(void)deferredBecomeFirstResponder;
-(void)didAddSubview:(id)arg0 ;
-(void)didMoveToSuperview;
-(void)didMoveToWindow;
-(void)didUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)drawLayer:(id)arg0 inContext:(struct CGContext *)arg1 ;
-(void)drawRect:(struct CGRect )arg0 ;
-(void)encodeWithCoder:(id)arg0 ;
-(void)engine:(id)arg0 willBreakConstraint:(id)arg1 dueToMutuallyExclusiveConstraints:(id)arg2 ;
-(void)exchangeSubviewAtIndex:(NSInteger)arg0 withSubviewAtIndex:(NSInteger)arg1 ;
-(void)exerciseAmbiguityInLayout;
-(void)find:(id)arg0 ;
-(void)findAndReplace:(id)arg0 ;
-(void)findNext:(id)arg0 ;
-(void)findPrevious:(id)arg0 ;
-(void)forceDisplayIfNeeded;
-(void)insertSubview:(id)arg0 above:(id)arg1 ;
-(void)insertSubview:(id)arg0 aboveSubview:(id)arg1 ;
-(void)insertSubview:(id)arg0 atIndex:(NSInteger)arg1 ;
-(void)insertSubview:(id)arg0 below:(id)arg1 ;
-(void)insertSubview:(id)arg0 belowSubview:(id)arg1 ;
-(void)invalidateIntrinsicContentSize;
-(void)layerWillDraw:(id)arg0 ;
-(void)layoutBelowIfNeeded;
-(void)layoutIfNeeded;
-(void)layoutMarginsDidChange;
-(void)layoutSublayersOfLayer:(id)arg0 ;
-(void)layoutSubviews;
-(void)movedFromSuperview:(id)arg0 ;
-(void)movedFromWindow:(id)arg0 ;
-(void)movedToSuperview:(id)arg0 ;
-(void)movedToWindow:(id)arg0 ;
-(void)mt_addPrivateSubview:(id)arg0 ;
-(void)nsis_valueOfVariable:(id)arg0 didChangeInEngine:(id)arg1 ;
-(void)nsli_addConstraint:(id)arg0 ;
-(void)recursivelyForceDisplayIfNeeded;
-(void)reduceWidth:(CGFloat)arg0 ;
-(void)removeAllGestureRecognizers;
-(void)removeConstraint:(id)arg0 ;
-(void)removeConstraints:(id)arg0 ;
-(void)removeFromSuperview;
-(void)removeGestureRecognizer:(id)arg0 ;
-(void)removeInteraction:(id)arg0 ;
-(void)removeLayoutGuide:(id)arg0 ;
-(void)removeMotionEffect:(id)arg0 ;
-(void)resizeSubviewsWithOldSize:(struct CGSize )arg0 ;
-(void)resizeWithOldSuperviewSize:(struct CGSize )arg0 ;
-(void)restoreUserActivityState:(id)arg0 ;
-(void)sendSubviewToBack:(id)arg0 ;
-(void)setAlpha:(CGFloat)arg0 ;
-(void)setAnchorPoint:(struct CGPoint )arg0 ;
-(void)setAutoresizesSubviews:(BOOL)arg0 ;
-(void)setAutoresizingMask:(NSUInteger)arg0 ;
-(void)setBackgroundColor:(id)arg0 ;
-(void)setCharge:(float)arg0 ;
-(void)setClearsContext:(BOOL)arg0 ;
-(void)setClearsContextBeforeDrawing:(BOOL)arg0 ;
-(void)setClipsSubviews:(BOOL)arg0 ;
-(void)setClipsToBounds:(BOOL)arg0 ;
-(void)setContentCompressionResistancePriority:(float)arg0 forAxis:(NSInteger)arg1 ;
-(void)setContentHuggingPriority:(float)arg0 forAxis:(NSInteger)arg1 ;
-(void)setContentMode:(NSInteger)arg0 ;
-(void)setContentScaleFactor:(CGFloat)arg0 ;
-(void)setContentStretch:(struct CGRect )arg0 ;
-(void)setContentsPosition:(int)arg0 ;
-(void)setDirectionalLayoutMargins:(struct NSDirectionalEdgeInsets )arg0 ;
-(void)setEdgesInsettingLayoutMarginsFromSafeArea:(NSUInteger)arg0 ;
-(void)setEdgesPreservingSuperviewLayoutMargins:(NSUInteger)arg0 ;
-(void)setEnabled:(BOOL)arg0 ;
-(void)setExclusiveTouch:(BOOL)arg0 ;
-(void)setFixedBackgroundPattern:(BOOL)arg0 ;
-(void)setHidden:(BOOL)arg0 ;
-(void)setInsetsLayoutMarginsFromSafeArea:(BOOL)arg0 ;
-(void)setInteractions:(id)arg0 ;
-(void)setLayoutMargins:(struct UIEdgeInsets )arg0 ;
-(void)setLayoutMarginsFollowReadableWidth:(BOOL)arg0 ;
-(void)setMaskView:(id)arg0 ;
-(void)setMotionEffects:(id)arg0 ;
-(void)setMultipleTouchEnabled:(BOOL)arg0 ;
-(void)setNeedsDisplay;
-(void)setNeedsDisplayInRect:(struct CGRect )arg0 ;
-(void)setNeedsDisplayOnBoundsChange:(BOOL)arg0 ;
-(void)setNeedsFocusUpdate;
-(void)setNeedsLayout;
-(void)setNeedsUpdateConstraints;
-(void)setOpaque:(BOOL)arg0 ;
-(void)setOrigin:(struct CGPoint )arg0 ;
-(void)setPosition:(struct CGPoint )arg0 ;
-(void)setPreservesSuperviewLayoutMargins:(BOOL)arg0 ;
-(void)setRotationBy:(float)arg0 ;
-(void)setSize:(struct CGSize )arg0 ;
-(void)setTintAdjustmentMode:(NSInteger)arg0 ;
-(void)setTintColor:(id)arg0 ;
-(void)setTranslatesAutoresizingMaskIntoConstraints:(BOOL)arg0 ;
-(void)setValue:(id)arg0 forKey:(id)arg1 ;
-(void)sizeToFit;
-(void)solutionDidChangeInEngine:(id)arg0 ;
-(void)stopSettingPresentationValueForKey:(id)arg0 ;
-(void)tintColorDidChange;
-(void)traitCollectionDidChange:(id)arg0 ;
-(void)updateConstraints;
-(void)updateConstraintsIfNeeded;
-(void)updateFocusIfNeeded;
-(void)updateUserActivityState:(id)arg0 ;
-(void)viewDidMoveToSuperview;
-(void)viewWillMoveToSuperview:(id)arg0 ;
-(void)willMoveToSuperview:(id)arg0 ;
-(void)willMoveToWindow:(id)arg0 ;
-(void)willRemoveSubview:(id)arg0 ;


@end


#endif