// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef BBSERVER_H
#define BBSERVER_H

@class NSMutableDictionary, NSMutableSet, NSMutableArray, NSDate, NSDateComponents, NSXPCListener, AFSiriAnnouncementRequestCapabilityManager, NSString;
@protocol BBDataProviderManagerDelegate, BBServerConduitServerInterface, BBSettingsGatewayServerInterface, NSXPCListenerDelegate, AFSiriAnnouncementRequestCapabilityObserving, BBSectionAuthorizationManagerDelegate, BBMuteExpirationManagerDelegate, BBSyncServiceDelegate, OS_dispatch_queue, OS_dispatch_source;

#import <Foundation/Foundation.h>

#import "BBDataProviderManager.h"
#import "BBMaskedSet.h"
#import "BBSyncService.h"
#import "BBDismissalSyncCache.h"
#import "BBSectionAuthorizationManager.h"
#import "BBMuteExpirationManager.h"
#import "BBBiometricResource.h"

@interface BBServer : NSObject <BBDataProviderManagerDelegate, BBServerConduitServerInterface, BBSettingsGatewayServerInterface, NSXPCListenerDelegate, AFSiriAnnouncementRequestCapabilityObserving, BBSectionAuthorizationManagerDelegate, BBMuteExpirationManagerDelegate, BBSyncServiceDelegate>

 {
    NSMutableDictionary *_bulletinRequestsByID;
    NSMutableDictionary *_sectionInfoByID;
    NSUInteger _currentSystemState;
    NSUInteger _globalCounter;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _isRunning;
    BBDataProviderManager *_dataProviderManager;
    NSMutableSet *_observers;
    BBMaskedSet *_observerFeedSet;
    NSMutableArray *_observerGateways;
    NSMutableDictionary *_observerGatewaysByName;
    NSMutableDictionary *_observerGatewayEnumerators;
    NSMutableDictionary *_pendingUpdatesByBulletinID;
    NSMutableSet *_settingsGatewayConnections;
    NSMutableDictionary *_activeSectionIDsByCategory;
    NSMutableDictionary *_sortedSectionIDsByCategory;
    NSMutableDictionary *_bulletinsByID;
    NSMutableDictionary *_bulletinIDsBySectionID;
    NSMutableDictionary *_noticeBulletinIDsBySectionID;
    NSMutableArray *_expiringBulletinIDs;
    NSObject<OS_dispatch_source> *_expirationTimer;
    NSMutableArray *_eventBasedExpiringBulletinIDs;
    NSDate *_nextScheduledExpirationTimerFireDate;
    NSDateComponents *_defaultExpirationComponents;
    NSDateComponents *_expirationReferenceComponents;
    NSMutableDictionary *_clearedSections;
    int _serverIsRunningToken;
    BBSyncService *_syncService;
    NSXPCListener *_observerListener;
    NSXPCListener *_conduitListener;
    NSXPCListener *_settingsListener;
    NSMutableSet *_suspendedConnections;
    BBDismissalSyncCache *_dismissalSyncCache;
    BBSectionAuthorizationManager *_sectionAuthorizationManager;
    BBMuteExpirationManager *_muteManager;
    BBBiometricResource *_biometricResource;
    BOOL _siriAllowedWhenLocked;
    BOOL _siriEnabled;
    BOOL _announceOnHearingAidsEnabled;
    BOOL _announceOnHearingAidsSupported;
    BOOL _announceOnBuiltInSpeakerEnabled;
    AFSiriAnnouncementRequestCapabilityManager *_announcementCapabilityManagerForHeadphones;
    AFSiriAnnouncementRequestCapabilityManager *_announcementCapabilityManagerForCarPlay;
}


@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;


+(BOOL)_removeSavedChronologicalSectionInfos:(id)arg0 ;
+(NSUInteger)pairedDeviceCount;
+(id)_behaviorOverridesPath;
+(id)_clearedSectionsPath;
+(id)_dataDirectoryPath;
+(id)_sectionIdentifiersForNonDefaultSectionCategoriesFromSectionInfos:(id)arg0 ;
+(id)_sectionIdentifiersForWeeAppsFromSectionInfos:(id)arg0 ;
+(id)_sectionInfoPath;
+(id)_sectionOrderPath;
+(id)_versionedSectionInfoPath;
+(id)savedChronologicalSectionOrder;
+(id)savedClearedSections;
+(id)savedLegacyOrderArray;
+(id)savedOrderDictionary;
+(id)savedSectionInfo;
+(void)initialize;
+(void)removeSavedChronologicalSectionInfo:(id)arg0 ;
+(void)writeClearedSections:(id)arg0 ;
+(void)writeOrderDictionary:(id)arg0 ;
+(void)writeSectionInfo:(id)arg0 ;
+(void)writeSectionInfo:(id)arg0 withVersionNumber:(NSUInteger)arg1 ;
-(BOOL)_deviceSupportsFavorites;
-(BOOL)_didNotificationCenterSettingsChangeWithSectionInfo:(id)arg0 replacingSectionInfo:(id)arg1 ;
-(BOOL)_hasPairedVehiclesForCarPlay;
-(BOOL)_isAnnounceSupportedForCarPlay;
-(BOOL)_isAnnounceSupportedForHeadphones;
-(BOOL)_verifyBulletinRequest:(id)arg0 forDataProvider:(id)arg1 ;
-(BOOL)isRunning;
-(BOOL)listener:(id)arg0 shouldAcceptNewConnection:(id)arg1 ;
-(BOOL)syncService:(id)arg0 shouldAbortDelayedDismissalForBulletin:(id)arg1 ;
-(NSInteger)_defaultGlobalContentPreviewSetting;
-(NSInteger)_effectiveGlobalAnnounceBuiltInSpeakerSetting;
-(NSInteger)_effectiveGlobalAnnounceCarPlaySetting;
-(NSInteger)_effectiveGlobalAnnounceHeadphonesSetting;
-(NSInteger)_effectiveGlobalAnnounceHearingAidsSetting;
-(NSInteger)_effectiveGlobalAnnounceSetting;
-(NSInteger)_effectiveGlobalContentPreviewsSetting;
-(NSInteger)_effectiveGlobalNotificationListDisplayStyleSetting;
-(NSInteger)_effectiveGlobalScheduledDeliverySetting;
-(NSInteger)_effectiveGlobalScheduledDeliveryShowNextSummarySetting;
-(NSInteger)_globalAnnounceCarPlaySetting;
-(NSInteger)_globalAnnounceHeadphonesSetting;
-(NSInteger)_globalAnnounceSetting;
-(NSInteger)_globalContentPreviewsSetting;
-(NSInteger)_globalNotificationListDisplayStyleSetting;
-(NSInteger)_globalScheduledDeliverySetting;
-(NSInteger)_globalScheduledDeliveryShowNextSummarySetting;
-(NSUInteger)_feedsForBulletin:(id)arg0 destinations:(NSUInteger)arg1 ;
-(NSUInteger)_filtersForSectionID:(id)arg0 ;
-(NSUInteger)_indexForNewDate:(id)arg0 inBulletinIDArray:(id)arg1 sortedAscendingByDateForKey:(id)arg2 ;
-(NSUInteger)_pairedDeviceCount;
-(NSUInteger)effectivePushSettingsForSectionInfo:(id)arg0 ;
-(id)_activeSectionIDs;
-(id)_allBulletinsForSectionID:(id)arg0 ;
-(id)_applicableSectionInfosForBulletin:(id)arg0 inSection:(id)arg1 ;
-(id)_bulletinDefaultExpirationDateFromDate:(id)arg0 ;
-(id)_bulletinIDsInSortedArray:(id)arg0 withDateForKey:(id)arg1 beforeCutoff:(id)arg2 ;
-(id)_bulletinRequestsForIDs:(id)arg0 ;
-(id)_bulletinsForIDs:(id)arg0 ;
-(id)_bulletinsForSectionID:(id)arg0 inFeeds:(NSUInteger)arg1 ;
-(id)_clearedInfoForSectionID:(id)arg0 ;
-(id)_effectiveGlobalScheduledDeliveryTimes;
-(id)_effectiveSectionInfoForSectionInfo:(id)arg0 ;
-(id)_enabledSectionIDsForDataProvider:(id)arg0 ;
-(id)_encodedScheduledDeliveryTimesForDeliveryTimes:(id)arg0 ;
-(id)_globalScheduledDeliveryTimes;
-(id)_mapForFeed:(NSUInteger)arg0 ;
-(id)_newDateCompontentsByInvertingInterestingPartsOfComponents:(id)arg0 ;
-(id)_newValidatedDefaultExpirationComponentsFromComponents:(id)arg0 ;
-(id)_nextExpireBulletinsDate;
-(id)_observerGatewaysForFeeds:(NSUInteger)arg0 ;
-(id)_observersForNoticesFeed;
-(id)_openApplicationOptionsForResponse:(id)arg0 ;
-(id)_scheduledDeliveryTimesForEncodedDeliveryTimes:(id)arg0 ;
-(id)_sectionIDsToMigrate;
-(id)_sectionInfoArray:(BOOL)arg0 ;
-(id)_sectionInfoArrayForActiveSections:(BOOL)arg0 ;
-(id)_sectionInfoArrayForSectionIDs:(id)arg0 effective:(BOOL)arg1 ;
-(id)_sectionInfoForSectionID:(id)arg0 effective:(BOOL)arg1 ;
-(id)_sinceDate;
-(id)_sortedSectionIDs;
-(id)allBulletinIDsForSectionID:(id)arg0 ;
-(id)bulletinIDsForSectionID:(id)arg0 inFeed:(NSUInteger)arg1 ;
-(id)bulletinsForPublisherMatchIDs:(id)arg0 sectionID:(id)arg1 ;
-(id)bulletinsRequestsForBulletinIDs:(id)arg0 ;
-(id)carBulletinIDsForSectionID:(id)arg0 ;
-(id)dataProviderForSectionID:(id)arg0 ;
-(id)dpManager:(id)arg0 sectionInfoForSectionID:(id)arg1 ;
-(id)initWithQueue:(id)arg0 ;
-(id)initWithQueue:(id)arg0 dataProviderManager:(id)arg1 syncService:(id)arg2 dismissalSyncCache:(id)arg3 observerListener:(id)arg4 conduitListener:(id)arg5 settingsListener:(id)arg6 ;
-(id)noticesBulletinIDsForSectionID:(id)arg0 ;
-(id)sectionIDsForUniversalSectionID:(id)arg0 ;
-(id)syncService:(id)arg0 sectionIdentifiersForUniversalSectionIdentifier:(id)arg1 ;
-(id)syncService:(id)arg0 universalSectionIdentifierForSectionIdentifier:(id)arg1 ;
-(id)universalSectionIDForSectionID:(id)arg0 ;
-(void)_addActiveSectionID:(id)arg0 ;
-(void)_addBulletin:(id)arg0 ;
-(void)_addObserver:(id)arg0 ;
-(void)_addSettingsGatewayConnection:(id)arg0 ;
-(void)_addStateCaptureHandlers;
-(void)_addSuspendedConnection:(id)arg0 ;
-(void)_assignIDToBulletinRequest:(id)arg0 ;
-(void)_assignIDToBulletinRequest:(id)arg0 checkAgainstBulletins:(id)arg1 ;
-(void)_biometricResourceStateChanged;
-(void)_clearBulletinIDIfPossible:(id)arg0 rescheduleExpirationTimer:(BOOL)arg1 ;
-(void)_clearBulletinIDs:(id)arg0 forSectionID:(id)arg1 shouldSync:(BOOL)arg2 ;
-(void)_clearBulletinsFromDate:(id)arg0 toDate:(id)arg1 forSection:(id)arg2 ;
-(void)_clearExpirationTimer;
-(void)_clearSection:(id)arg0 ;
-(void)_dataProviderDidClearInfo:(id)arg0 forSection:(id)arg1 ;
-(void)_didReceiveResponseForBulletin:(id)arg0 ;
-(void)_enqueueBulletinUpdate:(id)arg0 ;
-(void)_ensureDataDirectoryExists;
-(void)_expireBulletins;
-(void)_expireBulletinsAndRescheduleTimerIfNecessary;
-(void)_expireBulletinsDueToSystemEvent:(NSUInteger)arg0 ;
-(void)_fetchAllVehiclesForCarPlay;
-(void)_handleSignificantTimeChange;
-(void)_handleSystemSleep;
-(void)_handleSystemWake;
-(void)_loadClearedSections;
-(void)_loadDataProvidersAndSettings;
-(void)_loadSavedSectionInfo;
-(void)_loadSystemCapabilities;
-(void)_migrateContentPreviewSettings:(id)arg0 ;
-(void)_migrateGlobalAnnounceSettingIfNeeded;
-(void)_migrateLoadedData;
-(void)_migrateSectionIDs:(id)arg0 ;
-(void)_migrateSectionInfoIfNeeded;
-(void)_modifyBulletin:(id)arg0 ;
-(void)_observeManagedProfileChanges;
-(void)_pairedVehiclesForCarPlayDidChange:(id)arg0 ;
-(void)_performPendingBulletinUpdatesForBulletinID:(id)arg0 ;
-(void)_publishBiomeSignalEventForGlobalNotificationListDisplayStyleSettingChangeToSetting:(NSInteger)arg0 ;
-(void)_publishBulletinRequest:(id)arg0 forSectionID:(id)arg1 forDestinations:(NSUInteger)arg2 ;
-(void)_publishBulletinsForAllDataProviders;
-(void)_queue_managedUserNotificationsSetttingsDidChange;
-(void)_reloadReloadSectionInfoForSectionID:(id)arg0 ;
-(void)_reloadSectionParametersForSectionID:(id)arg0 ;
-(void)_removeActiveSectionID:(id)arg0 ;
-(void)_removeBulletin:(id)arg0 rescheduleTimerIfAffected:(BOOL)arg1 shouldSync:(BOOL)arg2 ;
-(void)_removeBulletin:(id)arg0 shouldSync:(BOOL)arg1 ;
-(void)_removeBulletins:(id)arg0 forSectionID:(id)arg1 shouldSync:(BOOL)arg2 ;
-(void)_removeObserver:(id)arg0 ;
-(void)_removeSection:(id)arg0 ;
-(void)_removeSettingsGatewayConnection:(id)arg0 ;
-(void)_removeSuspendedConnection:(id)arg0 ;
-(void)_removeVestigialSections:(id)arg0 ;
-(void)_resumeAllSuspendedConnectionsWithCompletionHandler:(id)arg0 ;
-(void)_saveGlobalAnnounceSettingEnabledEvent;
-(void)_saveUpdatedClearedInfo:(id)arg0 forSectionID:(id)arg1 ;
-(void)_saveUpdatedSectionInfo:(id)arg0 forSectionID:(id)arg1 ;
-(void)_scheduleExpirationForBulletin:(id)arg0 ;
-(void)_scheduleTimerForDate:(id)arg0 ;
-(void)_sendAddBulletin:(id)arg0 toFeeds:(NSUInteger)arg1 ;
-(void)_sendBulletinUpdate:(id)arg0 ;
-(void)_sendBulletinsLoadedForSectionID:(id)arg0 ;
-(void)_sendModifyBulletin:(id)arg0 toFeeds:(NSUInteger)arg1 ;
-(void)_sendObserver:(id)arg0 noticesBulletinsForSectionID:(id)arg1 ;
-(void)_sendRemoveBulletin:(id)arg0 toFeeds:(NSUInteger)arg1 shouldSync:(BOOL)arg2 ;
-(void)_sendRemoveBulletins:(id)arg0 toFeeds:(NSUInteger)arg1 shouldSync:(BOOL)arg2 ;
-(void)_sendRemoveSection:(id)arg0 ;
-(void)_sendUpdateSectionInfo:(id)arg0 ;
-(void)_setAnnounceSupportedForCarPlay:(BOOL)arg0 ;
-(void)_setAnnounceSupportedForHeadphones:(BOOL)arg0 ;
-(void)_setClearedInfo:(id)arg0 forSectionID:(id)arg1 ;
-(void)_setDefaultExpirationComponents:(id)arg0 ;
-(void)_setGlobalAnnounceCarPlaySetting:(NSInteger)arg0 ;
-(void)_setGlobalAnnounceHeadphonesSetting:(NSInteger)arg0 ;
-(void)_setGlobalAnnounceSetting:(NSInteger)arg0 ;
-(void)_setGlobalContentPreviewsSetting:(NSInteger)arg0 ;
-(void)_setGlobalNotificationListDisplayStyleSetting:(NSInteger)arg0 ;
-(void)_setGlobalScheduledDeliverySetting:(NSInteger)arg0 ;
-(void)_setGlobalScheduledDeliveryShowNextSummarySetting:(NSInteger)arg0 ;
-(void)_setGlobalScheduledDeliveryTimes:(id)arg0 ;
-(void)_setPairedVehiclesForCarPlay:(BOOL)arg0 ;
-(void)_setSectionInfo:(id)arg0 forSectionID:(id)arg1 ;
-(void)_setSectionInfoNoteSettingsChanged:(id)arg0 forSectionID:(id)arg1 ;
-(void)_siriPreferencesDidChange:(id)arg0 ;
-(void)_sortSectionIDs:(id)arg0 usingGuideArray:(id)arg1 ;
-(void)_sortSectionIDs:(id)arg0 usingOrder:(id)arg1 ;
-(void)_storeObserver:(id)arg0 forFeed:(NSUInteger)arg1 ;
-(void)_unobserveManagedProfileChanges;
-(void)_updateAllBulletinsForDataProvider:(id)arg0 ;
-(void)_updateAllBulletinsForDataProviderIfSectionIsEnabled:(id)arg0 ;
-(void)_updateAllSectionInfos;
-(void)_updateAnnounceControlCenterModuleAvailability;
-(void)_updateAnnounceSettings;
-(void)_updateBulletinsInFeed:(NSUInteger)arg0 forDataProvider:(id)arg1 enabledSectionIDs:(id)arg2 ;
-(void)_updateBulletinsInFeed:(NSUInteger)arg0 forDataProviderIfSectionIsEnabled:(id)arg1 ;
-(void)_updateBulletinsInFeed:(NSUInteger)arg0 ifSectionIsEnabled:(id)arg1 ;
-(void)_updateClearedInfoForSectionID:(id)arg0 handler:(id)arg1 ;
-(void)_updateDataProviderForSectionInfo:(id)arg0 sectionID:(id)arg1 ;
-(void)_updateGlobalSettings;
-(void)_updateInterruptionLevelForBulletin:(id)arg0 ;
-(void)_updateSectionInfoForSectionID:(id)arg0 handler:(id)arg1 ;
-(void)_updateSectionParametersForDataProvider:(id)arg0 ;
-(void)_updateShowsMessagePreviewForBulletin:(id)arg0 ;
-(void)_updateSiriPreferences;
-(void)_validateExpirationDateForBulletinRequest:(id)arg0 ;
-(void)_writeClearedSections;
-(void)_writeSectionInfo;
-(void)availableAnnouncementRequestTypesChanged:(NSUInteger)arg0 onPlatform:(NSInteger)arg1 ;
-(void)clearBulletinIDIfPossible:(id)arg0 rescheduleExpirationTimer:(BOOL)arg1 ;
-(void)dealloc;
-(void)deliverResponse:(id)arg0 withCompletion:(id)arg1 ;
-(void)didChangeEffectiveAuthorizationStatusForSectionID:(id)arg0 ;
-(void)didChangeMuteAssertionForSectionID:(id)arg0 ;
-(void)dpManager:(id)arg0 addDataProvider:(id)arg1 withSectionInfo:(id)arg2 ;
-(void)dpManager:(id)arg0 addParentSectionFactory:(id)arg1 ;
-(void)dpManager:(id)arg0 removeDataProviderSectionID:(id)arg1 ;
-(void)eligibleAnnouncementRequestTypesChanged:(NSUInteger)arg0 onPlatform:(NSInteger)arg1 ;
-(void)getBulletinsForPublisherMatchIDs:(id)arg0 sectionID:(id)arg1 withHandler:(id)arg2 ;
-(void)getBulletinsWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalAnnounceCarPlaySettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalAnnounceHeadphonesSettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalAnnounceSettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalContentPreviewsSettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalNotificationListDisplayStyleSettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalScheduledDeliverySettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalScheduledDeliveryShowNextSummarySettingWithHandler:(id)arg0 ;
-(void)getEffectiveGlobalScheduledDeliveryTimesWithHandler:(id)arg0 ;
-(void)getEffectiveSectionInfoForSectionID:(id)arg0 withHandler:(id)arg1 ;
-(void)getEffectiveSectionInfoForSectionIDs:(id)arg0 withHandler:(id)arg1 ;
-(void)getEffectiveSectionInfoWithHandler:(id)arg0 ;
-(void)getPublisherMatchIDsOfBulletinsPublishedAfterDate:(id)arg0 withHandler:(id)arg1 ;
-(void)getSectionIDsWithHandler:(id)arg0 ;
-(void)getSectionInfoForActiveSectionsWithHandler:(id)arg0 ;
-(void)getSectionInfoForSectionID:(id)arg0 withHandler:(id)arg1 ;
-(void)getSectionInfoForSectionIDs:(id)arg0 withHandler:(id)arg1 ;
-(void)getSectionInfoWithHandler:(id)arg0 ;
-(void)getSectionParametersForSectionID:(id)arg0 withHandler:(id)arg1 ;
-(void)getUniversalSectionIDForSectionID:(id)arg0 withHandler:(id)arg1 ;
-(void)loadDataProvidersAndSettings;
-(void)noteChangeOfState:(NSUInteger)arg0 newValue:(BOOL)arg1 ;
-(void)noteFinishedWithBulletinID:(id)arg0 ;
-(void)noteOccurrenceOfEvent:(NSUInteger)arg0 ;
-(void)observer:(id)arg0 clearBulletinIDs:(id)arg1 inSection:(id)arg2 ;
-(void)observer:(id)arg0 clearBulletinsFromDate:(id)arg1 toDate:(id)arg2 inSections:(id)arg3 ;
-(void)observer:(id)arg0 clearSection:(id)arg1 ;
-(void)observer:(id)arg0 finishedWithBulletinID:(id)arg1 transactionID:(NSUInteger)arg2 ;
-(void)observer:(id)arg0 getSectionInfoForActiveSectionsWithHandler:(id)arg1 ;
-(void)observer:(id)arg0 getSectionInfoForSectionIDs:(id)arg1 withHandler:(id)arg2 ;
-(void)observer:(id)arg0 getSectionInfoWithHandler:(id)arg1 ;
-(void)observer:(id)arg0 handleResponse:(id)arg1 withCompletion:(id)arg2 ;
-(void)observer:(id)arg0 removeBulletins:(id)arg1 inSection:(id)arg2 fromFeeds:(NSUInteger)arg3 ;
-(void)observer:(id)arg0 requestNoticesBulletinsForSectionID:(id)arg1 ;
-(void)observer:(id)arg0 setObserverFeed:(NSUInteger)arg1 asLightsAndSirensGateway:(id)arg2 priority:(NSUInteger)arg3 ;
-(void)observer:(id)arg0 setObserverFeed:(NSUInteger)arg1 attachToLightsAndSirensGateway:(id)arg2 ;
-(void)ping:(id)arg0 ;
-(void)publishBulletin:(id)arg0 destinations:(NSUInteger)arg1 ;
-(void)publishBulletinRequest:(id)arg0 destinations:(NSUInteger)arg1 ;
-(void)removeBulletinID:(id)arg0 fromNoticesSection:(id)arg1 ;
-(void)removeBulletinID:(id)arg0 fromSection:(id)arg1 inFeed:(NSUInteger)arg2 ;
-(void)requestNoticesBulletinsForAllSections:(id)arg0 ;
-(void)sendMessageToDataProviderSectionID:(id)arg0 name:(id)arg1 userInfo:(id)arg2 ;
-(void)setEffectiveGlobalAnnounceCarPlaySetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalAnnounceHeadphonesSetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalAnnounceSetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalContentPreviewsSetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalNotificationListDisplayStyleSetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalScheduledDeliverySetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalScheduledDeliveryShowNextSummarySetting:(NSInteger)arg0 withHandler:(id)arg1 ;
-(void)setEffectiveGlobalScheduledDeliveryTimes:(id)arg0 withHandler:(id)arg1 ;
-(void)setSectionInfo:(id)arg0 forSectionID:(id)arg1 ;
-(void)setSectionInfo:(id)arg0 forSectionID:(id)arg1 withHandler:(id)arg2 ;
-(void)syncService:(id)arg0 receivedDismissalDictionaries:(id)arg1 dismissalIDs:(id)arg2 inSection:(id)arg3 forFeeds:(NSUInteger)arg4 ;
-(void)updateSection:(id)arg0 inFeed:(NSUInteger)arg1 withBulletinRequests:(id)arg2 ;
-(void)weeAppWithBundleID:(id)arg0 getHiddenFromUser:(id)arg1 ;
-(void)weeAppWithBundleID:(id)arg0 setHiddenFromUser:(BOOL)arg1 ;
-(void)withdrawBulletinID:(id)arg0 ;
-(void)withdrawBulletinRequestsWithPublisherBulletinID:(id)arg0 forSectionID:(id)arg1 ;
-(void)withdrawBulletinRequestsWithRecordID:(id)arg0 forSectionID:(id)arg1 ;


@end


#endif