// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef WKWEBVIEW_H
#define WKWEBVIEW_H

@class UIView, NSURL, NSString, NSArray, NSData, UIEventAttribution, UIGestureRecognizer, UIColor, NSNumber, UIScrollView;
@protocol UIScrollViewDelegate, UIResponderStandardEditActions, WKUIDelegate, _WKAppHighlightDelegate, _WKDiagnosticLoggingDelegate, _WKFindDelegate, _WKFullscreenDelegate, WKHistoryDelegatePrivate, _WKIconLoadingDelegate, _WKInputDelegate, _WKWebViewPrintProvider, _WKResourceLoadDelegate, _WKTextManipulationDelegate, WKNavigationDelegate;


#import "WKWebViewContentProviderRegistry.h"
#import "WKBrowsingContextHandle.h"
#import "_WKInspector.h"
#import "_WKFrameHandle.h"
#import "WKPasswordView.h"
#import "_WKSessionState.h"
#import "_WKWebViewPrintFormatter.h"
#import "WKBackForwardList.h"
#import "WKWebViewConfiguration.h"

@interface WKWebView : UIView <UIScrollViewDelegate, UIResponderStandardEditActions>

 {
    RetainPtr<WKWebViewConfiguration> _configuration;
    RefPtr<WebKit::WebPageProxy, WTF::RawPtrTraits<WebKit::WebPageProxy>, WTF::DefaultRefDerefTraits<WebKit::WebPageProxy>> _page;
    unique_ptr<WebKit::NavigationState, std::default_delete<WebKit::NavigationState>> _navigationState;
    unique_ptr<WebKit::UIDelegate, std::default_delete<WebKit::UIDelegate>> _uiDelegate;
    unique_ptr<WebKit::IconLoadingDelegate, std::default_delete<WebKit::IconLoadingDelegate>> _iconLoadingDelegate;
    unique_ptr<WebKit::ResourceLoadDelegate, std::default_delete<WebKit::ResourceLoadDelegate>> _resourceLoadDelegate;
    WeakObjCPtr<id<_WKTextManipulationDelegate>> _textManipulationDelegate;
    WeakObjCPtr<id<_WKInputDelegate>> _inputDelegate;
    WeakObjCPtr<id<_WKAppHighlightDelegate>> _appHighlightDelegate;
    RetainPtr<WKSafeBrowsingWarning> _safeBrowsingWarning;
    optional<bool> _resolutionForShareSheetImmediateCompletionForTesting;
    NSUInteger _selectionAttributes;
    NSUInteger _observedRenderingProgressEvents;
    BOOL _usePlatformFindUI;
    RetainPtr<WKScrollView> _scrollView;
    RetainPtr<WKContentView> _contentView;
    unique_ptr<WebKit::ViewGestureController, std::default_delete<WebKit::ViewGestureController>> _gestureController;
    Vector<WTF::BlockPtr<void ()>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _visibleContentRectUpdateCallbacks;
    RetainPtr<WKFullScreenWindowController> _fullScreenWindowController;
    RetainPtr<_WKRemoteObjectRegistry> _remoteObjectRegistry;
    optional<CGSize> _viewLayoutSizeOverride;
    optional<WebCore::FloatSize> _lastSentViewLayoutSize;
    optional<CGSize> _minimumUnobscuredSizeOverride;
    optional<CGSize> _maximumUnobscuredSizeOverride;
    CGRect _inputViewBoundsInWindow;
    CGFloat _viewportMetaTagWidth;
    BOOL _viewportMetaTagWidthWasExplicit;
    BOOL _viewportMetaTagCameFromImageDocument;
    CGFloat _initialScaleFactor;
    BOOL _fastClickingIsDisabled;
    BOOL _allowsLinkPreview;
    UIEdgeInsets _obscuredInsets;
    BOOL _haveSetObscuredInsets;
    BOOL _isChangingObscuredInsetsInteractively;
    UIEdgeInsets _unobscuredSafeAreaInsets;
    BOOL _haveSetUnobscuredSafeAreaInsets;
    BOOL _avoidsUnsafeArea;
    NSUInteger _obscuredInsetEdgesAffectedBySafeArea;
    NSInteger _interfaceOrientationOverride;
    BOOL _overridesInterfaceOrientation;
    optional<int> _lastSentDeviceOrientation;
    BOOL _allowsViewportShrinkToFit;
    BOOL _hasCommittedLoadForMainFrame;
    BOOL _needsResetViewStateAfterCommitLoadForMainFrame;
    MonotonicObjectIdentifier<WebKit::TransactionIDType> _firstPaintAfterCommitLoadTransactionID;
    MonotonicObjectIdentifier<WebKit::TransactionIDType> _lastTransactionID;
    int _dynamicViewportUpdateMode;
    NSUInteger _currentDynamicViewportSizeUpdateID;
    CATransform3D _resizeAnimationTransformAdjustments;
    CGFloat _animatedResizeOriginalContentWidth;
    CGRect _animatedResizeOldBounds;
    CGFloat _animatedResizeOldMinimumEffectiveDeviceWidth;
    int _animatedResizeOldOrientation;
    UIEdgeInsets _animatedResizeOldObscuredInsets;
    RetainPtr<UIView> _resizeAnimationView;
    CGFloat _lastAdjustmentForScroller;
    optional<CGRect> _frozenVisibleContentRect;
    optional<CGRect> _frozenUnobscuredContentRect;
    BOOL _commitDidRestoreScrollPosition;
    optional<WebCore::FloatPoint> _scrollOffsetToRestore;
    RectEdges<float> _obscuredInsetsWhenSaved;
    optional<WebCore::FloatPoint> _unobscuredCenterToRestore;
    optional<WebKit::MonotonicObjectIdentifier<WebKit::TransactionIDType>> _firstTransactionIDAfterPageRestore;
    CGFloat _scaleToRestore;
    BOOL _allowsBackForwardNavigationGestures;
    RetainPtr<UIView<WKWebViewContentProvider>> _customContentView;
    RetainPtr<UIView> _customContentFixedOverlayView;
    RetainPtr<NSTimer> _enclosingScrollViewScrollTimer;
    BOOL _didScrollSinceLastTimerFire;
    Color _scrollViewBackgroundColor;
    CGFloat _totalScrollViewBottomInsetAdjustmentForKeyboard;
    BOOL _currentlyAdjustingScrollViewInsetsForKeyboard;
    BOOL _invokingUIScrollViewDelegateCallback;
    BOOL _didDeferUpdateVisibleContentRectsForUIScrollViewDelegateCallback;
    BOOL _didDeferUpdateVisibleContentRectsForAnyReason;
    BOOL _didDeferUpdateVisibleContentRectsForUnstableScrollView;
    BOOL _alwaysSendNextVisibleContentRectUpdate;
    BOOL _contentViewShouldBecomeFirstResponderAfterNavigationGesture;
    BOOL _waitingForEndAnimatedResize;
    BOOL _waitingForCommitAfterAnimatedResize;
    Vector<WTF::Function<void ()>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _callbacksDeferredDuringResize;
    RetainPtr<NSMutableArray> _stableStatePresentationUpdateCallbacks;
    RetainPtr<WKPasswordView> _passwordView;
    BOOL _hasScheduledVisibleRectUpdate;
    OptionSet<WebKit::ViewStabilityFlag> _viewStabilityWhenVisibleContentRectUpdateScheduled;
    optional<WebCore::WheelScrollGestureState> _currentScrollGestureState;
    NSUInteger _wheelEventCountInCurrentScrollGesture;
    NSUInteger _dragInteractionPolicy;
    MonotonicTime _timeOfRequestForVisibleContentRectUpdate;
    MonotonicTime _timeOfLastVisibleContentRectUpdate;
    optional<WTF::MonotonicTime> _timeOfFirstVisibleContentRectUpdateWithPendingCommit;
    NSUInteger _focusPreservationCount;
    NSUInteger _activeFocusedStateRetainCount;
}


@property (weak, nonatomic) NSObject<WKUIDelegate> *UIDelegate;
@property (readonly, copy, nonatomic) NSURL *URL;
@property (readonly, nonatomic) NSString *_MIMEType;
@property (nonatomic, setter=_setAddsVisitedLinks:) BOOL _addsVisitedLinks;
@property (readonly, nonatomic) BOOL _allowsDoubleTapGestures;
@property (nonatomic, getter=_allowsMediaDocumentInlinePlayback, setter=_setAllowsMediaDocumentInlinePlayback:) BOOL _allowsMediaDocumentInlinePlayback;
@property (nonatomic, setter=_setAllowsRemoteInspection:) BOOL _allowsRemoteInspection;
@property (nonatomic, setter=_setAllowsViewportShrinkToFit:) BOOL _allowsViewportShrinkToFit;
@property (readonly, nonatomic, getter=_isAnimatingDragCancel) BOOL _animatingDragCancel;
@property (weak, nonatomic, setter=_setAppHighlightDelegate:) NSObject<_WKAppHighlightDelegate> *_appHighlightDelegate;
@property (copy, setter=_setApplicationNameForUserAgent:) NSString *_applicationNameForUserAgent;
@property (nonatomic, setter=_setBackgroundExtendsBeyondPage:) BOOL _backgroundExtendsBeyondPage;
@property (readonly, nonatomic) BOOL _canTogglePictureInPicture;
@property (nonatomic, setter=_setCanUseCredentialStorage:) BOOL _canUseCredentialStorage;
@property (readonly, nonatomic) NSArray *_certificateChain;
@property (readonly, nonatomic) NSURL *_committedURL;
@property (readonly, nonatomic) UIEdgeInsets _computedObscuredInset;
@property (readonly, nonatomic) UIEdgeInsets _computedUnobscuredSafeAreaInset;
@property (readonly, nonatomic) WKWebViewContentProviderRegistry *_contentProviderRegistry;
@property (readonly, nonatomic) BOOL _contentViewIsFirstResponder;
@property (readonly, nonatomic) CGRect _contentVisibleRect;
@property (copy, nonatomic, setter=_setCORSDisablingPatterns:) NSArray *_corsDisablingPatterns;
@property (copy, setter=_setCustomUserAgent:) NSString *_customUserAgent;
@property (readonly, nonatomic) NSData *_dataForDisplayedPDF;
@property (readonly, nonatomic) BOOL _deferrableUserScriptsNeedNotification;
@property (readonly, nonatomic) int _deviceOrientation;
@property (weak, nonatomic, setter=_setDiagnosticLoggingDelegate:) NSObject<_WKDiagnosticLoggingDelegate> *_diagnosticLoggingDelegate;
@property (readonly, nonatomic, getter=_isDisplayingPDF) BOOL _displayingPDF;
@property (readonly, nonatomic, getter=_isDisplayingStandaloneImageDocument) BOOL _displayingStandaloneImageDocument;
@property (readonly, nonatomic, getter=_isDisplayingStandaloneMediaDocument) BOOL _displayingStandaloneMediaDocument;
@property (readonly, nonatomic) CGRect _dragCaretRect;
@property (nonatomic, setter=_setDragInteractionPolicy:) NSUInteger _dragInteractionPolicy;
@property (nonatomic, getter=_isEditable, setter=_setEditable:) BOOL _editable;
@property (readonly, nonatomic) UIView *_enclosingViewForExposedRectComputation;
@property (copy, nonatomic, setter=_setEphemeralUIEventAttribution:) UIEventAttribution *_ephemeralUIEventAttribution;
@property (weak, nonatomic, setter=_setFindDelegate:) NSObject<_WKFindDelegate> *_findDelegate;
@property (nonatomic, setter=_setFixedLayoutSize:) CGSize _fixedLayoutSize;
@property (nonatomic, setter=_setFullscreenDelegate:) NSObject<_WKFullscreenDelegate> *_fullscreenDelegate;
@property (nonatomic, setter=_setGapBetweenPages:) CGFloat _gapBetweenPages;
@property (readonly, nonatomic) WKBrowsingContextHandle *_handle;
@property (readonly, nonatomic) BOOL _hasServiceWorkerBackgroundActivityForTesting;
@property (readonly, nonatomic) BOOL _hasServiceWorkerForegroundActivityForTesting;
@property (readonly, nonatomic) BOOL _haveSetObscuredInsets;
@property (weak, nonatomic, setter=_setHistoryDelegate:) NSObject<WKHistoryDelegatePrivate> *_historyDelegate;
@property (weak, nonatomic, setter=_setIconLoadingDelegate:) NSObject<_WKIconLoadingDelegate> *_iconLoadingDelegate;
@property (readonly, nonatomic) UIGestureRecognizer *_imageAnalysisGestureRecognizer;
@property (weak, nonatomic, setter=_setInputDelegate:) NSObject<_WKInputDelegate> *_inputDelegate;
@property (readonly, nonatomic) CGRect _inputViewBoundsInWindow;
@property (readonly, nonatomic) _WKInspector *_inspector;
@property (nonatomic, setter=_setInterfaceOrientationOverride:) NSInteger _interfaceOrientationOverride;
@property (readonly, nonatomic) BOOL _isBackground;
@property (readonly, nonatomic) BOOL _isBeingInspected;
@property (readonly, nonatomic) BOOL _isInFullscreen;
@property (readonly, nonatomic) BOOL _isPictureInPictureActive;
@property (nonatomic, setter=_setLayoutMode:) NSUInteger _layoutMode;
@property (readonly, nonatomic) _WKFrameHandle *_mainFrame;
@property (readonly, nonatomic) NSURL *_mainFrameURL;
@property (readonly, nonatomic) CGSize _maximumUnobscuredSizeOverride;
@property (nonatomic, setter=_setMediaCaptureEnabled:) BOOL _mediaCaptureEnabled;
@property (nonatomic, setter=_setMediaCaptureReportingDelayForTesting:) CGFloat _mediaCaptureReportingDelayForTesting;
@property (readonly, nonatomic) NSUInteger _mediaCaptureState;
@property (readonly, nonatomic) NSUInteger _mediaMutedState;
@property (nonatomic, setter=_setMinimumEffectiveDeviceWidth:) CGFloat _minimumEffectiveDeviceWidth;
@property (readonly, nonatomic) CGSize _minimumLayoutSizeOverride;
@property (readonly, nonatomic) BOOL _negotiatedLegacyTLS;
@property (readonly, nonatomic) BOOL _networkRequestsInProgress;
@property (nonatomic, setter=_setObscuredInsetEdgesAffectedBySafeArea:) NSUInteger _obscuredInsetEdgesAffectedBySafeArea;
@property (nonatomic, setter=_setObscuredInsets:) UIEdgeInsets _obscuredInsets;
@property (nonatomic, setter=_setObservedRenderingProgressEvents:) NSUInteger _observedRenderingProgressEvents;
@property (readonly) NSUInteger _pageCount;
@property (readonly, nonatomic) UIColor *_pageExtendedBackgroundColor;
@property (nonatomic, setter=_setPageLength:) CGFloat _pageLength;
@property (nonatomic, setter=_setPageZoomFactor:) CGFloat _pageZoomFactor;
@property (nonatomic, setter=_setPaginationBehavesLikeColumns:) BOOL _paginationBehavesLikeColumns;
@property (nonatomic, setter=_setPaginationLineGridEnabled:) BOOL _paginationLineGridEnabled;
@property (nonatomic, setter=_setPaginationMode:) NSInteger _paginationMode;
@property (readonly, nonatomic) WKPasswordView *_passwordView;
@property (readonly, nonatomic, getter=_isPlayingAudio) BOOL _playingAudio;
@property (readonly, nonatomic) NSObject<_WKWebViewPrintProvider> *_printProvider;
@property (readonly, nonatomic) int _provisionalWebProcessIdentifier;
@property (copy, nonatomic, setter=_setRemoteInspectionNameOverride:) NSString *_remoteInspectionNameOverride;
@property (readonly, nonatomic) id *_remoteObjectRegistry;
@property (readonly, nonatomic) NSURL *_resourceDirectoryURL;
@property (weak, nonatomic, setter=_setResourceLoadDelegate:) NSObject<_WKResourceLoadDelegate> *_resourceLoadDelegate;
@property (readonly, nonatomic, getter=_isRetainingActiveFocusedState) BOOL _retainingActiveFocusedState;
@property (readonly, nonatomic) BOOL _safeAreaShouldAffectObscuredInsets;
@property (readonly, nonatomic) UIView *_safeBrowsingWarning;
@property (readonly, nonatomic) UIColor *_sampledPageTopColor;
@property (readonly, nonatomic) NSArray *_scrollPerformanceData;
@property (nonatomic, setter=_setScrollPerformanceDataCollectionEnabled:) BOOL _scrollPerformanceDataCollectionEnabled;
@property (readonly, nonatomic) NSString *_scrollingTreeAsText;
@property (nonatomic, setter=_setScrollingUpdatesDisabledForTesting:) BOOL _scrollingUpdatesDisabledForTesting;
@property (readonly, nonatomic) NSUInteger _selectionAttributes;
@property (readonly, nonatomic) NSInteger _selectionGranularity;
@property (readonly, nonatomic) _WKSessionState *_sessionState;
@property (readonly, nonatomic) NSData *_sessionStateData;
@property (readonly, nonatomic) BOOL _shouldAvoidResizingWhenInputViewBoundsChange;
@property (readonly, nonatomic, getter=_isShowingNavigationGestureSnapshot) BOOL _showingNavigationGestureSnapshot;
@property (readonly, nonatomic) NSNumber *_stableStateOverride;
@property (readonly, nonatomic) NSString *_suggestedFilenameForDisplayedPDF;
@property (readonly, nonatomic) BOOL _supportsTextZoom;
@property (readonly, nonatomic) CGRect _tapHighlightViewRect;
@property (weak, nonatomic, setter=_setTextManipulationDelegate:) NSObject<_WKTextManipulationDelegate> *_textManipulationDelegate;
@property (nonatomic, setter=_setTextZoomFactor:) CGFloat _textZoomFactor;
@property (readonly, nonatomic) UIColor *_themeColor;
@property (copy, nonatomic, setter=_setUIEventAttribution:) UIEventAttribution *_uiEventAttribution;
@property (readonly, nonatomic) CGRect _uiTextCaretRect;
@property (readonly, nonatomic) NSArray *_uiTextSelectionRects;
@property (readonly, nonatomic) NSString *_uiViewTreeAsText;
@property (nonatomic, setter=_setUnobscuredSafeAreaInsets:) UIEdgeInsets _unobscuredSafeAreaInsets;
@property (readonly, nonatomic) NSURL *_unreachableURL;
@property (readonly, nonatomic) NSString *_userAgent;
@property (nonatomic, setter=_setUserContentExtensionsEnabled:) BOOL _userContentExtensionsEnabled;
@property (nonatomic, setter=_setViewScale:) CGFloat _viewScale;
@property (nonatomic, setter=_setViewportSizeForCSSViewportUnits:) CGSize _viewportSizeForCSSViewportUnits;
@property (readonly, nonatomic) int _webProcessIdentifier;
@property (readonly, nonatomic) BOOL _webProcessIsResponsive;
@property (readonly, nonatomic) _WKWebViewPrintFormatter *_webViewPrintFormatter;
@property (readonly, nonatomic) BOOL _wirelessVideoPlaybackDisabled;
@property (nonatomic) BOOL allowsBackForwardNavigationGestures;
@property (nonatomic) BOOL allowsLinkPreview;
@property (readonly, nonatomic) WKBackForwardList *backForwardList;
@property (readonly, nonatomic) NSInteger cameraCaptureState;
@property (readonly, nonatomic) BOOL canGoBack;
@property (readonly, nonatomic) BOOL canGoForward;
@property (readonly, copy, nonatomic) NSArray *certificateChain;
@property (readonly, copy, nonatomic) WKWebViewConfiguration *configuration;
@property (copy, nonatomic) NSString *customUserAgent;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) CGFloat estimatedProgress;
@property (readonly, nonatomic) NSString *formInputLabel;
@property (readonly, nonatomic) NSInteger fullscreenState;
@property (readonly, nonatomic) BOOL hasOnlySecureContent;
@property (readonly) NSUInteger hash;
@property (copy, nonatomic) id *interactionState;
@property (readonly, nonatomic, getter=isLoading) BOOL loading;
@property (readonly, nonatomic) UIEdgeInsets maximumViewportInset; // ivar: _maximumViewportInset
@property (copy, nonatomic) NSString *mediaType;
@property (readonly, nonatomic) NSInteger microphoneCaptureState;
@property (readonly, nonatomic) UIEdgeInsets minimumViewportInset; // ivar: _minimumViewportInset
@property (weak, nonatomic) NSObject<WKNavigationDelegate> *navigationDelegate;
@property (nonatomic) CGFloat pageZoom;
@property (readonly, nonatomic) UIScrollView *scrollView;
@property (readonly, nonatomic) NSString *selectFormPopoverTitle;
@property (readonly, nonatomic) *__SecTrust serverTrust;
@property (readonly) Class superclass;
@property (readonly, nonatomic) NSString *textContentTypeForTesting;
@property (readonly, nonatomic) UIColor *themeColor;
@property (readonly, copy, nonatomic) NSString *title;
@property (copy, nonatomic) UIColor *underPageBackgroundColor;


+(BOOL)_willUpgradeToHTTPS:(id)arg0 ;
+(BOOL)automaticallyNotifiesObserversOfUnderPageBackgroundColor;
+(BOOL)handlesURLScheme:(id)arg0 ;
+(id)_confirmMalwareSentinel;
+(id)_stringForFind;
+(id)_visitUnsafeWebsiteSentinel;
+(void)_clearApplicationBundleIdentifierTestingOverride;
+(void)_setApplicationBundleIdentifier:(id)arg0 ;
+(void)_setStringForFind:(id)arg0 ;
-(BOOL)_allMediaPresentationsClosed;
-(BOOL)_beginBackSwipeForTesting;
-(BOOL)_completeBackSwipeForTesting;
-(BOOL)_effectiveAppearanceIsDark;
-(BOOL)_effectiveUserInterfaceLevelIsElevated;
-(BOOL)_hasSleepDisabler;
-(BOOL)_isClosed;
-(BOOL)_isNavigationSwipeGestureRecognizer:(id)arg0 ;
-(BOOL)_isShowingDataListSuggestions;
-(BOOL)_isShowingVideoPictureInPicture;
-(BOOL)_isValid;
-(BOOL)_mayAutomaticallyShowVideoPictureInPicture;
-(BOOL)_mayContainEditableElementsInRect:(struct CGRect )arg0 ;
-(BOOL)_restoreScrollAndZoomStateForTransaction:(*void)arg0 ;
-(BOOL)_scrollToRect:(struct FloatRect )arg0 origin:(struct FloatPoint )arg1 minimumScrollDistance:(float)arg2 ;
-(BOOL)_scrollViewIsRubberBanding:(id)arg0 ;
-(BOOL)_selectionRectIsFullyVisibleAndNonEmpty;
-(BOOL)_shouldUpdateKeyboardWithInfo:(id)arg0 ;
-(BOOL)_tryClose;
-(BOOL)_updateScrollViewContentInsetsIfNecessary;
-(BOOL)_zoomToRect:(struct FloatRect )arg0 withOrigin:(struct FloatPoint )arg1 fitEntireRect:(BOOL)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 minimumScrollDistance:(float)arg5 ;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)hasFullScreenWindowController;
-(BOOL)resignFirstResponder;
-(BOOL)selectFormAccessoryHasCheckedItemAtRow:(NSInteger)arg0 ;
-(BOOL)usesStandardContentView;
-(CGFloat)_audioRoutingArbitrationUpdateTime;
-(CGFloat)_contentZoomScale;
-(CGFloat)_initialScaleFactor;
-(CGFloat)_pageScale;
-(CGFloat)_targetContentZoomScaleForRect:(struct FloatRect *)arg0 currentScale:(CGFloat)arg1 fitEntireRect:(BOOL)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 ;
-(CGFloat)timePickerValueHour;
-(CGFloat)timePickerValueMinute;
-(Class)_printFormatterClass;
-(NSUInteger)_effectiveObscuredInsetEdgesAffectedBySafeArea;
-(float)_adjustScrollRectToAvoidHighlightOverlay:(struct FloatRect )arg0 ;
-(id)_attachmentForIdentifier:(id)arg0 ;
-(id)_contentSizeCategory;
-(id)_contentsOfUserInterfaceItem:(id)arg0 ;
-(id)_currentContentView;
-(id)_dataDetectionResults;
-(id)_filePickerAcceptedTypeIdentifiers;
-(id)_formDelegate;
-(id)_fullScreenPlaceholderView;
-(id)_insertAttachmentWithFileWrapper:(id)arg0 contentType:(id)arg1 completion:(id)arg2 ;
-(id)_insertAttachmentWithFileWrapper:(id)arg0 contentType:(id)arg1 options:(id)arg2 completion:(id)arg3 ;
-(id)_insertAttachmentWithFilename:(id)arg0 contentType:(id)arg1 data:(id)arg2 options:(id)arg3 completion:(id)arg4 ;
-(id)_loadData:(id)arg0 MIMEType:(id)arg1 characterEncodingName:(id)arg2 baseURL:(id)arg3 userData:(id)arg4 ;
-(id)_loadRequest:(id)arg0 shouldOpenExternalURLs:(BOOL)arg1 ;
-(id)_loadRequest:(id)arg0 shouldOpenExternalURLsPolicy:(NSInteger)arg1 ;
-(id)_propertiesOfLayerWithID:(NSUInteger)arg0 ;
-(id)_reloadExpiredOnly;
-(id)_reloadWithoutContentBlockers;
-(id)_restoreSessionState:(id)arg0 andNavigate:(BOOL)arg1 ;
-(id)_retainActiveFocusedState:(SEL)arg0 ;
-(id)_serializedSelectionCaretBackgroundColorForTesting;
-(id)_sessionStateWithFilter:(id)arg0 ;
-(id)_snapshotLayerContentsForBackForwardListItem:(id)arg0 ;
-(id)_suspendMediaPlaybackCounter;
-(id)_viewForFindUI;
-(id)browsingContextController;
-(id)fullScreenWindowController;
-(id)goBack;
-(id)goForward;
-(id)goToBackForwardListItem:(id)arg0 ;
-(id)initWithCoder:(id)arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 configuration:(id)arg1 ;
-(id)inputAccessoryView;
-(id)inputAssistantItem;
-(id)inputView;
-(id)loadData:(id)arg0 MIMEType:(id)arg1 characterEncodingName:(id)arg2 baseURL:(id)arg3 ;
-(id)loadFileRequest:(id)arg0 allowingReadAccessToURL:(id)arg1 ;
-(id)loadFileURL:(id)arg0 allowingReadAccessToURL:(id)arg1 ;
-(id)loadHTMLString:(id)arg0 baseURL:(id)arg1 ;
-(id)loadRequest:(id)arg0 ;
-(id)loadSimulatedRequest:(id)arg0 response:(id)arg1 responseData:(id)arg2 ;
-(id)loadSimulatedRequest:(id)arg0 responseHTMLString:(id)arg1 ;
-(id)loadSimulatedRequest:(id)arg0 withResponse:(id)arg1 responseData:(id)arg2 ;
-(id)loadSimulatedRequest:(id)arg0 withResponseHTMLString:(id)arg1 ;
-(id)reload;
-(id)reloadFromOrigin;
-(id)targetForAction:(SEL)arg0 withSender:(id)arg1 ;
-(id)undoManager;
-(id)urlSchemeHandlerForURLScheme:(id)arg0 ;
-(id)valueForUndefinedKey:(id)arg0 ;
-(id)viewForZoomingInScrollView:(id)arg0 ;
-(int)_audioRoutingArbitrationStatus;
-(struct CGPoint )_contentOffsetAdjustedForObscuredInset:(struct CGPoint )arg0 ;
-(struct CGPoint )_convertPointFromContentsToView:(struct CGPoint )arg0 ;
-(struct CGPoint )_convertPointFromViewToContents:(struct CGPoint )arg0 ;
-(struct CGPoint )_initialContentOffsetForScrollView;
-(struct CGPoint )_scrollView:(id)arg0 adjustedOffsetForOffset:(struct CGPoint )arg1 translation:(struct CGPoint )arg2 startPoint:(struct CGPoint )arg3 locationInView:(struct CGPoint )arg4 horizontalVelocity:(*CGFloat)arg5 verticalVelocity:(*CGFloat)arg6 ;
-(struct CGRect )_contentBoundsExtendedForRubberbandingWithScale:(CGFloat)arg0 ;
-(struct CGRect )_contentRectForUserInteraction;
-(struct CGRect )_visibleContentRect;
-(struct CGRect )_visibleRectInEnclosingView:(id)arg0 ;
-(struct CGSize )_minimumUnobscuredSizeOverride;
-(struct CGSize )scrollView:(id)arg0 contentSizeForZoomScale:(CGFloat)arg1 withProposedSize:(struct CGSize )arg2 ;
-(struct FloatRect )visibleRectInViewCoordinates;
-(struct FloatSize )activeViewLayoutSize:(struct CGRect *)arg0 ;
-(struct NakedPtr<WebKit::WebPageProxy> )_page;
-(struct OpaqueWKPage *)_pageForTesting;
-(struct OptionSet<WebKit::ViewStabilityFlag> )_viewStabilityState:(id)arg0 ;
-(struct RefPtr<WebKit::ViewSnapshot, WTF::RawPtrTraits<WebKit::ViewSnapshot>, WTF::DefaultRefDerefTraits<WebKit::ViewSnapshot>> )_takeViewSnapshot;
-(struct UIEdgeInsets )_computedContentInset;
-(struct UIEdgeInsets )_contentInsetsFromSystemMinimumLayoutMargins;
-(struct UIEdgeInsets )currentlyVisibleContentInsetsWithScale:(CGFloat)arg0 obscuredInsets:(struct UIEdgeInsets )arg1 ;
-(struct optional<bool> )_resolutionForShareSheetImmediateCompletionForTesting;
-(void)_accessibilityClearSelection;
-(void)_accessibilityDidGetSpeakSelectionContent:(id)arg0 ;
-(void)_accessibilityRetrieveRectsAtSelectionOffset:(NSInteger)arg0 withText:(id)arg1 completionHandler:(id)arg2 ;
-(void)_accessibilityRetrieveSpeakSelectionContent;
-(void)_accessibilitySettingsDidChange:(id)arg0 ;
-(void)_accessibilityStoreSelection;
-(void)_addAppHighlight;
-(void)_addAppHighlightInNewGroup:(BOOL)arg0 originatedInApp:(BOOL)arg1 ;
-(void)_addEventAttributionWithSourceID:(unsigned char)arg0 destinationURL:(id)arg1 sourceDescription:(id)arg2 purchaser:(id)arg3 reportEndpoint:(id)arg4 optionalNonce:(id)arg5 applicationBundleID:(id)arg6 ephemeral:(BOOL)arg7 ;
-(void)_addShortcut:(id)arg0 ;
-(void)_addUpdateVisibleContentRectPreCommitHandler;
-(void)_adjustSelectionWithDelta:(struct _NSRange )arg0 completionHandler:(id)arg1 ;
-(void)_alignCenter:(id)arg0 ;
-(void)_alignJustified:(id)arg0 ;
-(void)_alignLeft:(id)arg0 ;
-(void)_alignRight:(id)arg0 ;
-(void)_appPrivacyReportTestingData:(id)arg0 ;
-(void)_becomeFirstResponderWithSelectionMovingForward:(BOOL)arg0 completionHandler:(id)arg1 ;
-(void)_beginAnimatedResizeWithUpdates:(id)arg0 ;
-(void)_beginInteractiveObscuredInsetsChange;
-(void)_callAsyncJavaScript:(id)arg0 arguments:(id)arg1 inFrame:(id)arg2 inContentWorld:(id)arg3 completionHandler:(id)arg4 ;
-(void)_cancelAnimatedResize;
-(void)_changeListType:(id)arg0 ;
-(void)_clearAppPrivacyReportTestingData:(id)arg0 ;
-(void)_clearInterfaceOrientationOverride;
-(void)_clearOverrideLayoutParameters;
-(void)_clearSafeBrowsingWarning;
-(void)_clearSafeBrowsingWarningIfForMainFrameNavigation;
-(void)_clearServiceWorkerEntitlementOverride:(id)arg0 ;
-(void)_close;
-(void)_closeAllMediaPresentations;
-(void)_completeTextManipulation:(id)arg0 completion:(id)arg1 ;
-(void)_completeTextManipulationForItems:(id)arg0 completion:(id)arg1 ;
-(void)_computePagesForPrinting:(id)arg0 completionHandler:(id)arg1 ;
-(void)_contentSizeCategoryDidChange:(id)arg0 ;
-(void)_couldNotRestorePageState;
-(void)_countStringMatches:(id)arg0 options:(NSUInteger)arg1 maxCount:(NSUInteger)arg2 ;
-(void)_createMediaSessionCoordinatorForTesting:(id)arg0 completionHandler:(id)arg1 ;
-(void)_decreaseListLevel:(id)arg0 ;
-(void)_decrementFocusPreservationCount;
-(void)_define:(id)arg0 ;
-(void)_denyNextUserMediaRequest;
-(void)_detectDataWithTypes:(NSUInteger)arg0 completionHandler:(id)arg1 ;
-(void)_didChangeEditorState;
-(void)_didCommitLayerTree:(*void)arg0 ;
-(void)_didCommitLayerTreeDuringAnimatedResize:(*void)arg0 ;
-(void)_didCommitLoadForMainFrame;
-(void)_didCompleteAnimatedResize;
-(void)_didDisableBrowserExtensions:(id)arg0 ;
-(void)_didDismissContactPicker;
-(void)_didDismissContextMenu;
-(void)_didEnableBrowserExtensions:(id)arg0 ;
-(void)_didFailNavigation:(struct Navigation *)arg0 ;
-(void)_didFinishLoadingDataForCustomContentProviderWithSuggestedFilename:(*void)arg0 data:(id)arg1 ;
-(void)_didFinishNavigation:(struct Navigation *)arg0 ;
-(void)_didFinishScrolling;
-(void)_didFinishTextInteractionInTextInputContext:(id)arg0 ;
-(void)_didInsertAttachment:(*void)arg0 withSource:(id)arg1 ;
-(void)_didInvalidateDataForAttachment:(*void)arg0 ;
-(void)_didInvokeUIScrollViewDelegateCallback;
-(void)_didLoadAppInitiatedRequest:(id)arg0 ;
-(void)_didLoadNonAppInitiatedRequest:(id)arg0 ;
-(void)_didPresentContactPicker;
-(void)_didRelaunchProcess;
-(void)_didRemoveAttachment:(*void)arg0 ;
-(void)_didSameDocumentNavigationForMainFrame:(int)arg0 ;
-(void)_didScroll;
-(void)_didShowContextMenu;
-(void)_didStartProvisionalLoadForMainFrame;
-(void)_disableBackForwardSnapshotVolatilityForTesting;
-(void)_dismissContactPickerWithContacts:(id)arg0 ;
-(void)_dismissFilePicker;
-(void)_dispatchSetDeviceOrientation:(int)arg0 ;
-(void)_dispatchSetViewLayoutSize:(struct FloatSize )arg0 ;
-(void)_doAfterActivityStateUpdate:(id)arg0 ;
-(void)_doAfterNextPresentationUpdate:(id)arg0 ;
-(void)_doAfterNextPresentationUpdateWithoutWaitingForAnimatedResizeForTesting:(id)arg0 ;
-(void)_doAfterNextPresentationUpdateWithoutWaitingForPainting:(id)arg0 ;
-(void)_doAfterNextStablePresentationUpdate:(id)arg0 ;
-(void)_doAfterNextVisibleContentRectUpdate:(id)arg0 ;
-(void)_doAfterProcessingAllPendingMouseEvents:(id)arg0 ;
-(void)_doAfterReceivingEditDragSnapshotForTesting:(id)arg0 ;
-(void)_dumpPrivateClickMeasurement:(id)arg0 ;
-(void)_dynamicUserInterfaceTraitDidChange;
-(void)_enclosingScrollerScrollingEnded:(id)arg0 ;
-(void)_endAnimatedResize;
-(void)_endInteractiveObscuredInsetsChange;
-(void)_evaluateJavaScript:(id)arg0 asAsyncFunction:(BOOL)arg1 withSourceURL:(id)arg2 withArguments:(id)arg3 forceUserGesture:(BOOL)arg4 inFrame:(id)arg5 inWorld:(id)arg6 completionHandler:(id)arg7 ;
-(void)_evaluateJavaScript:(id)arg0 inFrame:(id)arg1 inContentWorld:(id)arg2 completionHandler:(id)arg3 ;
-(void)_evaluateJavaScript:(id)arg0 withSourceURL:(id)arg1 inFrame:(id)arg2 inContentWorld:(id)arg3 completionHandler:(id)arg4 ;
-(void)_evaluateJavaScriptWithoutUserGesture:(id)arg0 completionHandler:(id)arg1 ;
-(void)_executeEditCommand:(id)arg0 argument:(id)arg1 completion:(id)arg2 ;
-(void)_findString:(id)arg0 options:(NSUInteger)arg1 maxCount:(NSUInteger)arg2 ;
-(void)_firePresentationUpdateForPendingStableStatePresentationCallbacks;
-(void)_focusTextInputContext:(id)arg0 placeCaretAt:(struct CGPoint )arg1 completionHandler:(id)arg2 ;
-(void)_frameOrBoundsChanged;
-(void)_frames:(id)arg0 ;
-(void)_getApplicationManifestWithCompletionHandler:(id)arg0 ;
-(void)_getContentsAsAttributedStringWithCompletionHandler:(id)arg0 ;
-(void)_getContentsAsStringWithCompletionHandler:(id)arg0 ;
-(void)_getContentsAsStringWithCompletionHandlerKeepIPCConnectionAliveForTesting:(id)arg0 ;
-(void)_getContentsOfAllFramesAsStringWithCompletionHandler:(id)arg0 ;
-(void)_getMainResourceDataWithCompletionHandler:(id)arg0 ;
-(void)_getPDFFirstPageSizeInFrame:(id)arg0 completionHandler:(id)arg1 ;
-(void)_getProcessDisplayNameWithCompletionHandler:(id)arg0 ;
-(void)_getWebArchiveDataWithCompletionHandler:(id)arg0 ;
-(void)_gpuToWebProcessConnectionCountForTesting:(id)arg0 ;
-(void)_grantAccessToAssetServices;
-(void)_grantAccessToPreferenceService;
-(void)_handleKeyUIEvent:(id)arg0 ;
-(void)_hideContentUntilNextUpdate;
-(void)_hideFindUI;
-(void)_hidePasswordView;
-(void)_increaseListLevel:(id)arg0 ;
-(void)_incrementFocusPreservationCount;
-(void)_indent:(id)arg0 ;
-(void)_initializeWithConfiguration:(id)arg0 ;
-(void)_insertNestedOrderedList:(id)arg0 ;
-(void)_insertNestedUnorderedList:(id)arg0 ;
-(void)_insertOrderedList:(id)arg0 ;
-(void)_insertUnorderedList:(id)arg0 ;
// -(void)_internalDoAfterNextPresentationUpdate:(id)arg0 withoutWaitingForPainting:(unk)arg1 withoutWaitingForAnimatedResize:(BOOL)arg2  ;
-(void)_isForcedIntoAppBoundMode:(id)arg0 ;
-(void)_isJITEnabled:(id)arg0 ;
-(void)_isLayerTreeFrozenForTesting:(id)arg0 ;
-(void)_isNavigatingToAppBoundDomain:(id)arg0 ;
-(void)_keyboardChangedWithInfo:(id)arg0 adjustScrollView:(BOOL)arg1 ;
-(void)_keyboardDidChangeFrame:(id)arg0 ;
-(void)_keyboardDidShow:(id)arg0 ;
-(void)_keyboardWillChangeFrame:(id)arg0 ;
-(void)_keyboardWillHide:(id)arg0 ;
-(void)_keyboardWillShow:(id)arg0 ;
-(void)_killWebContentProcess;
-(void)_killWebContentProcessAndResetState;
-(void)_lastNavigationWasAppInitiated:(id)arg0 ;
-(void)_layerTreeCommitComplete;
-(void)_loadAlternateHTMLString:(id)arg0 baseURL:(id)arg1 forUnreachableURL:(id)arg2 ;
-(void)_loadServiceWorker:(id)arg0 completionHandler:(id)arg1 ;
-(void)_lookup:(id)arg0 ;
-(void)_navigationGestureDidBegin;
-(void)_navigationGestureDidEnd;
-(void)_nextAccessoryTab:(id)arg0 ;
-(void)_notifyUserScripts;
-(void)_outdent:(id)arg0 ;
-(void)_overrideLayoutParametersWithMinimumLayoutSize:(struct CGSize )arg0 maximumUnobscuredSizeOverride:(struct CGSize )arg1 ;
-(void)_overrideViewportWithArguments:(id)arg0 ;
-(void)_pasteAndMatchStyle:(id)arg0 ;
-(void)_pasteAsQuotation:(id)arg0 ;
-(void)_populateArchivedSubviews:(id)arg0 ;
-(void)_preconnectToServer:(id)arg0 ;
-(void)_previousAccessoryTab:(id)arg0 ;
-(void)_processDidExit;
-(void)_processDidResumeForTesting;
-(void)_processWillSuspendForTesting:(id)arg0 ;
-(void)_processWillSuspendImminentlyForTesting;
-(void)_processWillSwap;
-(void)_processWillSwapOrDidExit;
-(void)_promptForReplace:(id)arg0 ;
-(void)_recalculateViewportSizesWithMinimumViewportInset:(struct UIEdgeInsets )arg0 maximumViewportInset:(struct UIEdgeInsets )arg1 throwOnInvalidInput:(BOOL)arg2 ;
-(void)_registerForNotifications;
-(void)_removeDataDetectedLinks:(id)arg0 ;
-(void)_requestActivatedElementAtPosition:(struct CGPoint )arg0 completionBlock:(id)arg1 ;
-(void)_requestActiveNowPlayingSessionInfo:(id)arg0 ;
-(void)_requestDocumentContext:(id)arg0 completionHandler:(id)arg1 ;
-(void)_requestResource:(id)arg0 completionHandler:(id)arg1 ;
-(void)_requestTextInputContextsInRect:(struct CGRect )arg0 completionHandler:(id)arg1 ;
-(void)_resetCachedScrollViewBackgroundColor;
-(void)_resetFocusPreservationCount;
-(void)_resetNavigationGestureStateForTesting;
-(void)_resizeWhileHidingContentWithUpdates:(id)arg0 ;
-(void)_restoreAndScrollToAppHighlight:(id)arg0 ;
-(void)_restoreAppHighlights:(id)arg0 ;
-(void)_restoreFromSessionStateData:(id)arg0 ;
-(void)_restorePageScrollPosition:(struct optional<WebCore::FloatPoint> )arg0 scrollOrigin:(struct FloatPoint )arg1 previousObscuredInset:(struct RectEdges<float> )arg2 scale:(CGFloat)arg3 ;
-(void)_restorePageStateToUnobscuredCenter:(struct optional<WebCore::FloatPoint> )arg0 scale:(CGFloat)arg1 ;
-(void)_resumeAllMediaPlayback;
-(void)_resumePage:(id)arg0 ;
-(void)_revokeAccessToAssetServices;
-(void)_saveBackForwardSnapshotForItem:(id)arg0 ;
-(void)_scheduleForcedVisibleContentRectUpdate;
-(void)_scheduleVisibleContentRectUpdate;
-(void)_scheduleVisibleContentRectUpdateAfterScrollInView:(id)arg0 ;
-(void)_scrollToAndRevealSelectionIfNeeded;
-(void)_scrollToContentScrollPosition:(struct FloatPoint )arg0 scrollOrigin:(struct IntPoint )arg1 animated:(BOOL)arg2 ;
-(void)_scrollView:(id)arg0 asynchronouslyHandleScrollEvent:(id)arg1 completion:(id)arg2 ;
-(void)_scrollViewDidInterruptDecelerating:(id)arg0 ;
-(void)_selectDataListOption:(int)arg0 ;
-(void)_serviceWorkersEnabled:(id)arg0 ;
-(void)_setAssertionTypeForTesting:(int)arg0 ;
-(void)_setAvoidsUnsafeArea:(BOOL)arg0 ;
-(void)_setContinuousSpellCheckingEnabledForTesting:(BOOL)arg0 ;
-(void)_setDefersLoadingForTesting:(BOOL)arg0 ;
-(void)_setDeviceHasAGXCompilerServiceForTesting;
-(void)_setDeviceOrientationUserPermissionHandlerForTesting:(id)arg0 ;
-(void)_setFont:(id)arg0 sender:(id)arg1 ;
-(void)_setFontSize:(CGFloat)arg0 sender:(id)arg1 ;
-(void)_setFormDelegate:(id)arg0 ;
-(void)_setHasCustomContentView:(BOOL)arg0 loadedMIMEType:(*void)arg1 ;
-(void)_setMaximumUnobscuredSizeOverride:(struct CGSize )arg0 ;
-(void)_setMinimumUnobscuredSizeOverride:(struct CGSize )arg0 ;
-(void)_setOpaqueInternal:(BOOL)arg0 ;
-(void)_setOverlaidAccessoryViewsInset:(struct CGSize )arg0 ;
-(void)_setPageMuted:(NSUInteger)arg0 ;
-(void)_setPageScale:(CGFloat)arg0 withOrigin:(struct CGPoint )arg1 ;
-(void)_setPrivateClickMeasurementAppBundleIDForTesting:(id)arg0 completionHandler:(id)arg1 ;
-(void)_setPrivateClickMeasurementAttributionReportURLsForTesting:(id)arg0 destinationURL:(id)arg1 completionHandler:(id)arg2 ;
-(void)_setPrivateClickMeasurementAttributionTokenPublicKeyURLForTesting:(id)arg0 completionHandler:(id)arg1 ;
-(void)_setPrivateClickMeasurementAttributionTokenSignatureURLForTesting:(id)arg0 completionHandler:(id)arg1 ;
-(void)_setPrivateClickMeasurementOverrideTimerForTesting:(BOOL)arg0 completionHandler:(id)arg1 ;
-(void)_setShareSheetCompletesImmediatelyWithResolutionForTesting:(BOOL)arg0 ;
-(void)_setSuppressSoftwareKeyboard:(BOOL)arg0 ;
-(void)_setTextColor:(id)arg0 sender:(id)arg1 ;
-(void)_setViewLayoutSizeOverride:(struct CGSize )arg0 ;
-(void)_setupPageConfiguration:(*void)arg0 ;
-(void)_setupScrollAndContentViews;
-(void)_share:(id)arg0 ;
-(void)_showPasswordViewWithDocumentName:(id)arg0 passwordHandler:(id)arg1 ;
-(void)_showSafeBrowsingWarning:(*void)arg0 completionHandler:(*void)arg1 ;
-(void)_showSafeBrowsingWarningWithTitle:(id)arg0 warning:(id)arg1 details:(id)arg2 completionHandler:(id)arg3 ;
-(void)_showSafeBrowsingWarningWithURL:(id)arg0 title:(id)arg1 warning:(id)arg2 details:(id)arg3 completionHandler:(id)arg4 ;
-(void)_showSafeBrowsingWarningWithURL:(id)arg0 title:(id)arg1 warning:(id)arg2 detailsWithLinks:(id)arg3 completionHandler:(id)arg4 ;
-(void)_showTextStyleOptions:(id)arg0 ;
-(void)_simulateDeviceOrientationChangeWithAlpha:(CGFloat)arg0 beta:(CGFloat)arg1 gamma:(CGFloat)arg2 ;
-(void)_simulateElementAction:(NSInteger)arg0 atLocation:(struct CGPoint )arg1 ;
-(void)_simulateLongPressActionAtLocation:(struct CGPoint )arg0 ;
-(void)_simulateTextEntered:(id)arg0 ;
-(void)_snapshotRect:(struct CGRect )arg0 intoImageOfWidth:(CGFloat)arg1 completionHandler:(id)arg2 ;
-(void)_snapshotRectAfterScreenUpdates:(BOOL)arg0 rectInViewCoordinates:(struct CGRect )arg1 intoImageOfWidth:(CGFloat)arg2 completionHandler:(id)arg3 ;
-(void)_startImageAnalysis:(id)arg0 ;
-(void)_startTextManipulationsWithConfiguration:(id)arg0 completion:(id)arg1 ;
-(void)_stopAllMediaPlayback;
-(void)_stopMediaCapture;
-(void)_storeAppHighlight:(*void)arg0 ;
-(void)_suspendAllMediaPlayback;
-(void)_suspendPage:(id)arg0 ;
-(void)_switchFromStaticFontRegistryToUserFontRegistry;
-(void)_takeFindStringFromSelection:(id)arg0 ;
-(void)_takePDFSnapshotWithConfiguration:(id)arg0 completionHandler:(id)arg1 ;
-(void)_togglePictureInPicture;
-(void)_toggleStrikeThrough:(id)arg0 ;
-(void)_trackTransactionCommit:(*void)arg0 ;
-(void)_translate:(id)arg0 ;
-(void)_transliterateChinese:(id)arg0 ;
-(void)_triggerSystemPreviewActionOnElement:(NSUInteger)arg0 document:(NSUInteger)arg1 page:(NSUInteger)arg2 ;
-(void)_updateMediaPlaybackControlsManager;
-(void)_updateScrollViewBackground;
-(void)_updateScrollViewForTransaction:(*void)arg0 ;
-(void)_updateScrollViewIndicatorStyle;
-(void)_updateScrollViewInsetAdjustmentBehavior;
-(void)_updateVisibleContentRects;
-(void)_updateWebpagePreferences:(id)arg0 ;
-(void)_videoControlsManagerDidChange;
-(void)_willBeginTextInteractionInTextInputContext:(id)arg0 ;
-(void)_willInvokeUIScrollViewDelegateCallback;
-(void)_willOpenAppLink;
-(void)_windowDidRotate:(id)arg0 ;
-(void)_zoomOutWithOrigin:(struct FloatPoint )arg0 animated:(BOOL)arg1 ;
-(void)_zoomToFocusRect:(struct FloatRect *)arg0 selectionRect:(struct FloatRect *)arg1 fontSize:(float)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 allowScaling:(BOOL)arg5 forceScroll:(BOOL)arg6 ;
-(void)_zoomToInitialScaleWithOrigin:(struct FloatPoint )arg0 animated:(BOOL)arg1 ;
-(void)_zoomToPoint:(struct FloatPoint )arg0 atScale:(CGFloat)arg1 animated:(BOOL)arg2 ;
-(void)_zoomToRect:(struct FloatRect )arg0 atScale:(CGFloat)arg1 origin:(struct FloatPoint )arg2 animated:(BOOL)arg3 ;
-(void)applyAutocorrection:(id)arg0 toString:(id)arg1 withCompletionHandler:(id)arg2 ;
-(void)callAsyncJavaScript:(id)arg0 arguments:(id)arg1 inFrame:(id)arg2 inContentWorld:(id)arg3 completionHandler:(id)arg4 ;
-(void)captureTextFromCamera:(id)arg0 ;
-(void)closeAllMediaPresentations;
-(void)closeAllMediaPresentations:(id)arg0 ;
-(void)closeAllMediaPresentationsWithCompletionHandler:(id)arg0 ;
-(void)closeFullScreenWindowController;
-(void)copy:(id)arg0 ;
-(void)createPDFWithConfiguration:(id)arg0 completionHandler:(id)arg1 ;
-(void)createWebArchiveDataWithCompletionHandler:(id)arg0 ;
-(void)cut:(id)arg0 ;
-(void)dealloc;
-(void)decreaseSize:(id)arg0 ;
-(void)didEndFormControlInteraction;
-(void)didMoveToWindow;
-(void)didStartFormControlInteraction;
-(void)dismissFormAccessoryView;
-(void)encodeWithCoder:(id)arg0 ;
-(void)evaluateJavaScript:(id)arg0 completionHandler:(id)arg1 ;
-(void)evaluateJavaScript:(id)arg0 inFrame:(id)arg1 inContentWorld:(id)arg2 completionHandler:(id)arg3 ;
-(void)findString:(id)arg0 withConfiguration:(id)arg1 completionHandler:(id)arg2 ;
-(void)increaseSize:(id)arg0 ;
-(void)keyboardAccessoryBarNext;
-(void)keyboardAccessoryBarPrevious;
-(void)layoutSubviews;
-(void)makeTextWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeTextWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeft:(id)arg0 ;
-(void)paste:(id)arg0 ;
-(void)pasteAndMatchStyle:(id)arg0 ;
-(void)pauseAllMediaPlayback:(id)arg0 ;
-(void)pauseAllMediaPlaybackWithCompletionHandler:(id)arg0 ;
-(void)removeFromSuperview;
-(void)replace:(id)arg0 ;
-(void)requestMediaPlaybackState:(id)arg0 ;
-(void)requestMediaPlaybackStateWithCompletionHandler:(id)arg0 ;
-(void)resumeAllMediaPlayback:(id)arg0 ;
-(void)resumeDownloadFromResumeData:(id)arg0 completionHandler:(id)arg1 ;
-(void)safeAreaInsetsDidChange;
-(void)scrollViewDidEndDecelerating:(id)arg0 ;
-(void)scrollViewDidEndDragging:(id)arg0 willDecelerate:(BOOL)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg0 ;
-(void)scrollViewDidEndZooming:(id)arg0 withView:(id)arg1 atScale:(CGFloat)arg2 ;
-(void)scrollViewDidScroll:(id)arg0 ;
-(void)scrollViewDidScrollToTop:(id)arg0 ;
-(void)scrollViewDidZoom:(id)arg0 ;
-(void)scrollViewWillBeginDragging:(id)arg0 ;
-(void)scrollViewWillBeginZooming:(id)arg0 withView:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg0 withVelocity:(struct CGPoint )arg1 targetContentOffset:(struct CGPoint *)arg2 ;
-(void)select:(id)arg0 ;
-(void)selectAll:(id)arg0 ;
-(void)selectFormAccessoryPickerRow:(int)arg0 ;
-(void)setAllMediaPlaybackSuspended:(BOOL)arg0 completionHandler:(id)arg1 ;
-(void)setBackgroundColor:(id)arg0 ;
-(void)setBounds:(struct CGRect )arg0 ;
-(void)setFrame:(struct CGRect )arg0 ;
-(void)setOpaque:(BOOL)arg0 ;
-(void)setSelectedColorForColorPicker:(id)arg0 ;
-(void)setSemanticContentAttribute:(NSInteger)arg0 ;
-(void)setTimePickerValueToHour:(NSInteger)arg0 minute:(NSInteger)arg1 ;
-(void)startDownloadUsingRequest:(id)arg0 completionHandler:(id)arg1 ;
-(void)stopLoading;
-(void)suspendAllMediaPlayback:(id)arg0 ;
-(void)takeSnapshotWithConfiguration:(id)arg0 completionHandler:(id)arg1 ;
-(void)toggleBoldface:(id)arg0 ;
-(void)toggleItalics:(id)arg0 ;
-(void)toggleUnderline:(id)arg0 ;
-(void)willFinishIgnoringCalloutBarFadeAfterPerformingAction;


@end


#endif