// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef MTRBASECLUSTERTHERMOSTAT_H
#define MTRBASECLUSTERTHERMOSTAT_H



#import "MTRCluster.h"
#import "MTRBaseDevice.h"

@interface MTRBaseClusterThermostat : MTRCluster

@property (readonly, nonatomic) MTRBaseDevice *device; // ivar: _device
@property (readonly, nonatomic) unsigned short endpoint; // ivar: _endpoint


+(void)readAttributeACCapacityWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACCapacityWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACCapacityformatWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACCapacityformatWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACCoilTemperatureWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACCoilTemperatureWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACCompressorTypeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACCompressorTypeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACErrorCodeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACErrorCodeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACLouverPositionWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACLouverPositionWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACRefrigerantTypeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACRefrigerantTypeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeACTypeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeACTypeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAbsMaxCoolSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAbsMaxCoolSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAbsMaxHeatSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAbsMaxHeatSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAbsMinCoolSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAbsMinCoolSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAbsMinHeatSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAbsMinHeatSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcceptedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcceptedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAttributeListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAttributeListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeClusterRevisionWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeClusterRevisionWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeControlSequenceOfOperationWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeControlSequenceOfOperationWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeEmergencyHeatDeltaWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEmergencyHeatDeltaWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeFeatureMapWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFeatureMapWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeHVACSystemTypeConfigurationWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeHVACSystemTypeConfigurationWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLocalTemperatureCalibrationWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLocalTemperatureCalibrationWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLocalTemperatureWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLocalTemperatureWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMaxCoolSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMaxCoolSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMaxHeatSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMaxHeatSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMinCoolSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMinCoolSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMinHeatSetpointLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMinHeatSetpointLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMinSetpointDeadBandWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMinSetpointDeadBandWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfDailyTransitionsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfDailyTransitionsWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfWeeklyTransitionsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfWeeklyTransitionsWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupancyWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupancyWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupiedCoolingSetpointWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupiedCoolingSetpointWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupiedHeatingSetpointWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupiedHeatingSetpointWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupiedSetbackMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupiedSetbackMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupiedSetbackMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupiedSetbackMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOccupiedSetbackWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOccupiedSetbackWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOutdoorTemperatureWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOutdoorTemperatureWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePICoolingDemandWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePICoolingDemandWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePIHeatingDemandWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePIHeatingDemandWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRemoteSensingWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRemoteSensingWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSetpointChangeAmountWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSetpointChangeAmountWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSetpointChangeSourceTimestampWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSetpointChangeSourceTimestampWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSetpointChangeSourceWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSetpointChangeSourceWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeStartOfWeekWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeStartOfWeekWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSystemModeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSystemModeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeTemperatureSetpointHoldDurationWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTemperatureSetpointHoldDurationWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeTemperatureSetpointHoldWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTemperatureSetpointHoldWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeThermostatProgrammingOperationModeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeThermostatProgrammingOperationModeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeThermostatRunningModeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeThermostatRunningModeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeThermostatRunningStateWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeThermostatRunningStateWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUnoccupiedCoolingSetpointWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnoccupiedCoolingSetpointWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUnoccupiedHeatingSetpointWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnoccupiedHeatingSetpointWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnoccupiedSetbackWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
-(id)initWithDevice:(id)arg0 endpoint:(unsigned short)arg1 queue:(id)arg2 ;
-(id)initWithDevice:(id)arg0 endpointID:(id)arg1 queue:(id)arg2 ;
-(void)clearWeeklyScheduleWithCompletion:(id)arg0 ;
-(void)clearWeeklyScheduleWithCompletionHandler:(id)arg0 ;
-(void)clearWeeklyScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearWeeklyScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getWeeklyScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getWeeklyScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)readAttributeACCapacityWithCompletion:(id)arg0 ;
-(void)readAttributeACCapacityWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACCapacityformatWithCompletion:(id)arg0 ;
-(void)readAttributeACCapacityformatWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACCoilTemperatureWithCompletion:(id)arg0 ;
-(void)readAttributeACCoilTemperatureWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACCompressorTypeWithCompletion:(id)arg0 ;
-(void)readAttributeACCompressorTypeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACErrorCodeWithCompletion:(id)arg0 ;
-(void)readAttributeACErrorCodeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACLouverPositionWithCompletion:(id)arg0 ;
-(void)readAttributeACLouverPositionWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACRefrigerantTypeWithCompletion:(id)arg0 ;
-(void)readAttributeACRefrigerantTypeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeACTypeWithCompletion:(id)arg0 ;
-(void)readAttributeACTypeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAbsMaxCoolSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeAbsMaxCoolSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAbsMaxHeatSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeAbsMaxHeatSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAbsMinCoolSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeAbsMinCoolSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAbsMinHeatSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeAbsMinHeatSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcceptedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeAcceptedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletion:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletion:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletionHandler:(id)arg0 ;
-(void)readAttributeControlSequenceOfOperationWithCompletion:(id)arg0 ;
-(void)readAttributeControlSequenceOfOperationWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEmergencyHeatDeltaWithCompletion:(id)arg0 ;
-(void)readAttributeEmergencyHeatDeltaWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletion:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletionHandler:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeHVACSystemTypeConfigurationWithCompletion:(id)arg0 ;
-(void)readAttributeHVACSystemTypeConfigurationWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLocalTemperatureCalibrationWithCompletion:(id)arg0 ;
-(void)readAttributeLocalTemperatureCalibrationWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLocalTemperatureWithCompletion:(id)arg0 ;
-(void)readAttributeLocalTemperatureWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMaxCoolSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeMaxCoolSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMaxHeatSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeMaxHeatSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMinCoolSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeMinCoolSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMinHeatSetpointLimitWithCompletion:(id)arg0 ;
-(void)readAttributeMinHeatSetpointLimitWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMinSetpointDeadBandWithCompletion:(id)arg0 ;
-(void)readAttributeMinSetpointDeadBandWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfDailyTransitionsWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfDailyTransitionsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfWeeklyTransitionsWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfWeeklyTransitionsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupancyWithCompletion:(id)arg0 ;
-(void)readAttributeOccupancyWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupiedCoolingSetpointWithCompletion:(id)arg0 ;
-(void)readAttributeOccupiedCoolingSetpointWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupiedHeatingSetpointWithCompletion:(id)arg0 ;
-(void)readAttributeOccupiedHeatingSetpointWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupiedSetbackMaxWithCompletion:(id)arg0 ;
-(void)readAttributeOccupiedSetbackMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupiedSetbackMinWithCompletion:(id)arg0 ;
-(void)readAttributeOccupiedSetbackMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOccupiedSetbackWithCompletion:(id)arg0 ;
-(void)readAttributeOccupiedSetbackWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOutdoorTemperatureWithCompletion:(id)arg0 ;
-(void)readAttributeOutdoorTemperatureWithCompletionHandler:(id)arg0 ;
-(void)readAttributePICoolingDemandWithCompletion:(id)arg0 ;
-(void)readAttributePICoolingDemandWithCompletionHandler:(id)arg0 ;
-(void)readAttributePIHeatingDemandWithCompletion:(id)arg0 ;
-(void)readAttributePIHeatingDemandWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRemoteSensingWithCompletion:(id)arg0 ;
-(void)readAttributeRemoteSensingWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSetpointChangeAmountWithCompletion:(id)arg0 ;
-(void)readAttributeSetpointChangeAmountWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSetpointChangeSourceTimestampWithCompletion:(id)arg0 ;
-(void)readAttributeSetpointChangeSourceTimestampWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSetpointChangeSourceWithCompletion:(id)arg0 ;
-(void)readAttributeSetpointChangeSourceWithCompletionHandler:(id)arg0 ;
-(void)readAttributeStartOfWeekWithCompletion:(id)arg0 ;
-(void)readAttributeStartOfWeekWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSystemModeWithCompletion:(id)arg0 ;
-(void)readAttributeSystemModeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTemperatureSetpointHoldDurationWithCompletion:(id)arg0 ;
-(void)readAttributeTemperatureSetpointHoldDurationWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTemperatureSetpointHoldWithCompletion:(id)arg0 ;
-(void)readAttributeTemperatureSetpointHoldWithCompletionHandler:(id)arg0 ;
-(void)readAttributeThermostatProgrammingOperationModeWithCompletion:(id)arg0 ;
-(void)readAttributeThermostatProgrammingOperationModeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeThermostatRunningModeWithCompletion:(id)arg0 ;
-(void)readAttributeThermostatRunningModeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeThermostatRunningStateWithCompletion:(id)arg0 ;
-(void)readAttributeThermostatRunningStateWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnoccupiedCoolingSetpointWithCompletion:(id)arg0 ;
-(void)readAttributeUnoccupiedCoolingSetpointWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnoccupiedHeatingSetpointWithCompletion:(id)arg0 ;
-(void)readAttributeUnoccupiedHeatingSetpointWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackMaxWithCompletion:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackMinWithCompletion:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackWithCompletion:(id)arg0 ;
-(void)readAttributeUnoccupiedSetbackWithCompletionHandler:(id)arg0 ;
-(void)setWeeklyScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setWeeklyScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)setpointRaiseLowerWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setpointRaiseLowerWithParams:(id)arg0 completionHandler:(id)arg1 ;
// -(void)subscribeAttributeACCapacityWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACCapacityWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACCapacityformatWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACCapacityformatWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACCoilTemperatureWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACCoilTemperatureWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACCompressorTypeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACCompressorTypeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACErrorCodeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACErrorCodeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACLouverPositionWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACLouverPositionWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACRefrigerantTypeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACRefrigerantTypeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeACTypeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeACTypeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAbsMaxCoolSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAbsMaxCoolSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAbsMaxHeatSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAbsMaxHeatSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAbsMinCoolSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAbsMinCoolSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAbsMinHeatSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAbsMinHeatSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcceptedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcceptedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAttributeListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAttributeListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeClusterRevisionWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeClusterRevisionWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeControlSequenceOfOperationWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeControlSequenceOfOperationWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeEmergencyHeatDeltaWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEmergencyHeatDeltaWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeFeatureMapWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFeatureMapWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeGeneratedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeGeneratedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeHVACSystemTypeConfigurationWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeHVACSystemTypeConfigurationWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLocalTemperatureCalibrationWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLocalTemperatureCalibrationWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLocalTemperatureWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLocalTemperatureWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMaxCoolSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMaxCoolSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMaxHeatSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMaxHeatSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMinCoolSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMinCoolSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMinHeatSetpointLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMinHeatSetpointLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMinSetpointDeadBandWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMinSetpointDeadBandWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfDailyTransitionsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfDailyTransitionsWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfWeeklyTransitionsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfWeeklyTransitionsWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupancyWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupancyWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupiedCoolingSetpointWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupiedCoolingSetpointWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupiedHeatingSetpointWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupiedHeatingSetpointWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupiedSetbackMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupiedSetbackMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupiedSetbackMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupiedSetbackMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOccupiedSetbackWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOccupiedSetbackWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOutdoorTemperatureWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOutdoorTemperatureWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePICoolingDemandWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePICoolingDemandWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePIHeatingDemandWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePIHeatingDemandWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRemoteSensingWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRemoteSensingWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSetpointChangeAmountWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSetpointChangeAmountWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSetpointChangeSourceTimestampWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSetpointChangeSourceTimestampWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSetpointChangeSourceWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSetpointChangeSourceWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeStartOfWeekWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeStartOfWeekWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSystemModeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSystemModeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeTemperatureSetpointHoldDurationWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTemperatureSetpointHoldDurationWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeTemperatureSetpointHoldWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTemperatureSetpointHoldWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeThermostatProgrammingOperationModeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeThermostatProgrammingOperationModeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeThermostatRunningModeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeThermostatRunningModeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeThermostatRunningStateWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeThermostatRunningStateWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUnoccupiedCoolingSetpointWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnoccupiedCoolingSetpointWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUnoccupiedHeatingSetpointWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnoccupiedHeatingSetpointWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUnoccupiedSetbackMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnoccupiedSetbackMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUnoccupiedSetbackMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnoccupiedSetbackMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUnoccupiedSetbackWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnoccupiedSetbackWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
-(void)writeAttributeACCapacityWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACCapacityWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACCapacityWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACCapacityWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACCapacityformatWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACCapacityformatWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACCapacityformatWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACCapacityformatWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACCompressorTypeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACCompressorTypeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACCompressorTypeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACCompressorTypeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACErrorCodeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACErrorCodeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACErrorCodeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACErrorCodeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACLouverPositionWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACLouverPositionWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACLouverPositionWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACLouverPositionWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACRefrigerantTypeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACRefrigerantTypeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACRefrigerantTypeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACRefrigerantTypeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeACTypeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeACTypeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeACTypeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeACTypeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeControlSequenceOfOperationWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeControlSequenceOfOperationWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeControlSequenceOfOperationWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeControlSequenceOfOperationWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEmergencyHeatDeltaWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeEmergencyHeatDeltaWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEmergencyHeatDeltaWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeEmergencyHeatDeltaWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeHVACSystemTypeConfigurationWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeHVACSystemTypeConfigurationWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeHVACSystemTypeConfigurationWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeHVACSystemTypeConfigurationWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLocalTemperatureCalibrationWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeLocalTemperatureCalibrationWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLocalTemperatureCalibrationWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeLocalTemperatureCalibrationWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeMaxCoolSetpointLimitWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeMaxCoolSetpointLimitWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeMaxCoolSetpointLimitWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeMaxCoolSetpointLimitWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeMaxHeatSetpointLimitWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeMaxHeatSetpointLimitWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeMaxHeatSetpointLimitWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeMaxHeatSetpointLimitWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeMinCoolSetpointLimitWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeMinCoolSetpointLimitWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeMinCoolSetpointLimitWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeMinCoolSetpointLimitWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeMinHeatSetpointLimitWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeMinHeatSetpointLimitWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeMinHeatSetpointLimitWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeMinHeatSetpointLimitWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeMinSetpointDeadBandWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeMinSetpointDeadBandWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeMinSetpointDeadBandWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeMinSetpointDeadBandWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOccupiedCoolingSetpointWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOccupiedCoolingSetpointWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOccupiedCoolingSetpointWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOccupiedCoolingSetpointWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOccupiedHeatingSetpointWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOccupiedHeatingSetpointWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOccupiedHeatingSetpointWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOccupiedHeatingSetpointWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOccupiedSetbackWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOccupiedSetbackWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOccupiedSetbackWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOccupiedSetbackWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRemoteSensingWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRemoteSensingWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRemoteSensingWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRemoteSensingWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeSystemModeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeSystemModeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeSystemModeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeSystemModeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeTemperatureSetpointHoldDurationWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeTemperatureSetpointHoldDurationWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeTemperatureSetpointHoldDurationWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeTemperatureSetpointHoldDurationWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeTemperatureSetpointHoldWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeTemperatureSetpointHoldWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeTemperatureSetpointHoldWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeTemperatureSetpointHoldWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeThermostatProgrammingOperationModeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeThermostatProgrammingOperationModeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeThermostatProgrammingOperationModeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeThermostatProgrammingOperationModeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeUnoccupiedCoolingSetpointWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeUnoccupiedCoolingSetpointWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeUnoccupiedCoolingSetpointWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeUnoccupiedCoolingSetpointWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeUnoccupiedHeatingSetpointWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeUnoccupiedHeatingSetpointWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeUnoccupiedHeatingSetpointWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeUnoccupiedHeatingSetpointWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeUnoccupiedSetbackWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeUnoccupiedSetbackWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeUnoccupiedSetbackWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeUnoccupiedSetbackWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;


@end


#endif