// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef MTRBASECLUSTERELECTRICALMEASUREMENT_H
#define MTRBASECLUSTERELECTRICALMEASUREMENT_H



#import "MTRCluster.h"
#import "MTRBaseDevice.h"

@interface MTRBaseClusterElectricalMeasurement : MTRCluster

@property (readonly, nonatomic) MTRBaseDevice *device; // ivar: _device
@property (readonly, nonatomic) unsigned short endpoint; // ivar: _endpoint


+(void)readAttributeAcActivePowerOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcActivePowerOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcCurrentDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcCurrentDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcCurrentMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcCurrentMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcCurrentOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcCurrentOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcFrequencyDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcFrequencyDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcFrequencyMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcFrequencyMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcFrequencyMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcFrequencyMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcFrequencyMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcFrequencyMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcFrequencyWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcFrequencyWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcOverloadAlarmsMaskWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcOverloadAlarmsMaskWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcPowerDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcPowerDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcPowerMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcPowerMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcReactivePowerOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcReactivePowerOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcVoltageDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcVoltageDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcVoltageMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcVoltageMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcVoltageOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcVoltageOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAcceptedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcceptedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActiveCurrentPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActiveCurrentPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActiveCurrentPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActiveCurrentPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMaxPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMaxPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMaxPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMaxPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMinPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMinPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMinPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMinPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActivePowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActivePowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeApparentPowerPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeApparentPowerPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeApparentPowerPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeApparentPowerPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeApparentPowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeApparentPowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAttributeListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAttributeListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageCounterPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageCounterPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageCounterPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageCounterPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsOverVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageCounterWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsUnderVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAverageRmsVoltageMeasurementPeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeClusterRevisionWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeClusterRevisionWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeCurrentOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeCurrentOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcCurrentDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcCurrentDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcCurrentMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcCurrentMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcCurrentMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcCurrentMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcCurrentMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcCurrentMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcPowerDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcPowerDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcPowerMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcPowerMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcPowerMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcPowerMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcPowerMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcPowerMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcPowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcPowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcVoltageDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcVoltageDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcVoltageMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcVoltageMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcVoltageMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcVoltageMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcVoltageMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcVoltageMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDcVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDcVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeFeatureMapWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFeatureMapWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeHarmonicCurrentMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeHarmonicCurrentMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeInstantaneousActiveCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInstantaneousActiveCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeInstantaneousLineCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInstantaneousLineCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeInstantaneousPowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInstantaneousPowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeInstantaneousReactiveCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInstantaneousReactiveCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeInstantaneousVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInstantaneousVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLineCurrentPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLineCurrentPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLineCurrentPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLineCurrentPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured11thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured11thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured1stHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured1stHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured3rdHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured3rdHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured5thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured5thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured7thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured7thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasured9thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasured9thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase11thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase11thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase1stHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase1stHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase3rdHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase3rdHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase5thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase5thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase7thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase7thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasuredPhase9thHarmonicCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasuredPhase9thHarmonicCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMeasurementTypeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMeasurementTypeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNeutralCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNeutralCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOverloadAlarmsMaskWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOverloadAlarmsMaskWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePhaseHarmonicCurrentMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePhaseHarmonicCurrentMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePowerDivisorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePowerDivisorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePowerFactorPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePowerFactorPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePowerFactorPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePowerFactorPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePowerFactorWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePowerFactorWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributePowerMultiplierWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributePowerMultiplierWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeReactiveCurrentPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeReactiveCurrentPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeReactiveCurrentPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeReactiveCurrentPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeReactivePowerPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeReactivePowerPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeReactivePowerPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeReactivePowerPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeReactivePowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeReactivePowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMinPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMinPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMinPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMinPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsCurrentWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsCurrentWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltagePeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeOverVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltagePeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsExtremeUnderVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMaxWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMinPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMinPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMinPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMinPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageMinWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageMinWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltagePhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltagePhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltagePhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltagePhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSagPeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSagWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSagWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodPhaseBWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodPhaseBWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodPhaseCWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodPhaseCWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellPeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageSwellWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRmsVoltageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRmsVoltageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeTotalActivePowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTotalActivePowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeTotalApparentPowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTotalApparentPowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeTotalReactivePowerWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTotalReactivePowerWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeVoltageOverloadWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeVoltageOverloadWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
-(id)initWithDevice:(id)arg0 endpoint:(unsigned short)arg1 queue:(id)arg2 ;
-(id)initWithDevice:(id)arg0 endpointID:(id)arg1 queue:(id)arg2 ;
-(void)getMeasurementProfileCommandWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getMeasurementProfileCommandWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getProfileInfoCommandWithCompletion:(id)arg0 ;
-(void)getProfileInfoCommandWithCompletionHandler:(id)arg0 ;
-(void)getProfileInfoCommandWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getProfileInfoCommandWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)readAttributeAcActivePowerOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeAcActivePowerOverloadWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcCurrentDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeAcCurrentDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcCurrentMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeAcCurrentMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcCurrentOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeAcCurrentOverloadWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcFrequencyDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeAcFrequencyDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcFrequencyMaxWithCompletion:(id)arg0 ;
-(void)readAttributeAcFrequencyMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcFrequencyMinWithCompletion:(id)arg0 ;
-(void)readAttributeAcFrequencyMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcFrequencyMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeAcFrequencyMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcFrequencyWithCompletion:(id)arg0 ;
-(void)readAttributeAcFrequencyWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcOverloadAlarmsMaskWithCompletion:(id)arg0 ;
-(void)readAttributeAcOverloadAlarmsMaskWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcPowerDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeAcPowerDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcPowerMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeAcPowerMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcReactivePowerOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeAcReactivePowerOverloadWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcVoltageDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeAcVoltageDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcVoltageMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeAcVoltageMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcVoltageOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeAcVoltageOverloadWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAcceptedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeAcceptedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActiveCurrentPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeActiveCurrentPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActiveCurrentPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeActiveCurrentPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMaxPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMaxPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMaxPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMaxPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMaxWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMinPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMinPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMinPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMinPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerMinWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActivePowerWithCompletion:(id)arg0 ;
-(void)readAttributeActivePowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeApparentPowerPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeApparentPowerPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeApparentPowerPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeApparentPowerPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeApparentPowerWithCompletion:(id)arg0 ;
-(void)readAttributeApparentPowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletion:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageCounterPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageCounterPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageCounterPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageCounterPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsOverVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageCounterWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsUnderVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodWithCompletion:(id)arg0 ;
-(void)readAttributeAverageRmsVoltageMeasurementPeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletion:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletionHandler:(id)arg0 ;
-(void)readAttributeCurrentOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeCurrentOverloadWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcCurrentDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeDcCurrentDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcCurrentMaxWithCompletion:(id)arg0 ;
-(void)readAttributeDcCurrentMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcCurrentMinWithCompletion:(id)arg0 ;
-(void)readAttributeDcCurrentMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcCurrentMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeDcCurrentMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeDcCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcPowerDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeDcPowerDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcPowerMaxWithCompletion:(id)arg0 ;
-(void)readAttributeDcPowerMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcPowerMinWithCompletion:(id)arg0 ;
-(void)readAttributeDcPowerMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcPowerMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeDcPowerMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcPowerWithCompletion:(id)arg0 ;
-(void)readAttributeDcPowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcVoltageDivisorWithCompletion:(id)arg0 ;
-(void)readAttributeDcVoltageDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcVoltageMaxWithCompletion:(id)arg0 ;
-(void)readAttributeDcVoltageMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcVoltageMinWithCompletion:(id)arg0 ;
-(void)readAttributeDcVoltageMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcVoltageMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeDcVoltageMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDcVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeDcVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletion:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletionHandler:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeHarmonicCurrentMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributeHarmonicCurrentMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInstantaneousActiveCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeInstantaneousActiveCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInstantaneousLineCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeInstantaneousLineCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInstantaneousPowerWithCompletion:(id)arg0 ;
-(void)readAttributeInstantaneousPowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInstantaneousReactiveCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeInstantaneousReactiveCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInstantaneousVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeInstantaneousVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLineCurrentPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeLineCurrentPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLineCurrentPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeLineCurrentPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured11thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured11thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured1stHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured1stHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured3rdHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured3rdHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured5thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured5thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured7thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured7thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasured9thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasured9thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase11thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase11thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase1stHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase1stHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase3rdHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase3rdHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase5thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase5thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase7thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase7thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasuredPhase9thHarmonicCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeMeasuredPhase9thHarmonicCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMeasurementTypeWithCompletion:(id)arg0 ;
-(void)readAttributeMeasurementTypeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNeutralCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeNeutralCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOverloadAlarmsMaskWithCompletion:(id)arg0 ;
-(void)readAttributeOverloadAlarmsMaskWithCompletionHandler:(id)arg0 ;
-(void)readAttributePhaseHarmonicCurrentMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributePhaseHarmonicCurrentMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributePowerDivisorWithCompletion:(id)arg0 ;
-(void)readAttributePowerDivisorWithCompletionHandler:(id)arg0 ;
-(void)readAttributePowerFactorPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributePowerFactorPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributePowerFactorPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributePowerFactorPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributePowerFactorWithCompletion:(id)arg0 ;
-(void)readAttributePowerFactorWithCompletionHandler:(id)arg0 ;
-(void)readAttributePowerMultiplierWithCompletion:(id)arg0 ;
-(void)readAttributePowerMultiplierWithCompletionHandler:(id)arg0 ;
-(void)readAttributeReactiveCurrentPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeReactiveCurrentPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeReactiveCurrentPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeReactiveCurrentPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeReactivePowerPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeReactivePowerPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeReactivePowerPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeReactivePowerPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeReactivePowerWithCompletion:(id)arg0 ;
-(void)readAttributeReactivePowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMinPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMinPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMinPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMinPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentMinWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsCurrentWithCompletion:(id)arg0 ;
-(void)readAttributeRmsCurrentWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltagePeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeOverVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltagePeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeRmsExtremeUnderVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMaxWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMinPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMinPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMinPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMinPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageMinWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageMinWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltagePhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltagePhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltagePhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltagePhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSagPeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSagWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSagWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodPhaseBWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodPhaseBWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodPhaseCWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodPhaseCWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellPeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageSwellWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRmsVoltageWithCompletion:(id)arg0 ;
-(void)readAttributeRmsVoltageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTotalActivePowerWithCompletion:(id)arg0 ;
-(void)readAttributeTotalActivePowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTotalApparentPowerWithCompletion:(id)arg0 ;
-(void)readAttributeTotalApparentPowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTotalReactivePowerWithCompletion:(id)arg0 ;
-(void)readAttributeTotalReactivePowerWithCompletionHandler:(id)arg0 ;
-(void)readAttributeVoltageOverloadWithCompletion:(id)arg0 ;
-(void)readAttributeVoltageOverloadWithCompletionHandler:(id)arg0 ;
// -(void)subscribeAttributeAcActivePowerOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcActivePowerOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcCurrentDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcCurrentDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcCurrentMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcCurrentMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcCurrentOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcCurrentOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcFrequencyDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcFrequencyDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcFrequencyMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcFrequencyMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcFrequencyMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcFrequencyMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcFrequencyMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcFrequencyMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcFrequencyWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcFrequencyWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcOverloadAlarmsMaskWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcOverloadAlarmsMaskWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcPowerDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcPowerDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcPowerMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcPowerMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcReactivePowerOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcReactivePowerOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcVoltageDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcVoltageDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcVoltageMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcVoltageMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcVoltageOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcVoltageOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAcceptedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcceptedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActiveCurrentPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActiveCurrentPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActiveCurrentPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActiveCurrentPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMaxPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMaxPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMaxPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMaxPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMinPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMinPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMinPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMinPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActivePowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActivePowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeApparentPowerPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeApparentPowerPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeApparentPowerPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeApparentPowerPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeApparentPowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeApparentPowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAttributeListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAttributeListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsOverVoltageCounterPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsOverVoltageCounterPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsOverVoltageCounterPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsOverVoltageCounterPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsOverVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsOverVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageCounterWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsUnderVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAverageRmsVoltageMeasurementPeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeClusterRevisionWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeClusterRevisionWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeCurrentOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeCurrentOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcCurrentDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcCurrentDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcCurrentMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcCurrentMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcCurrentMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcCurrentMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcCurrentMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcCurrentMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcPowerDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcPowerDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcPowerMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcPowerMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcPowerMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcPowerMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcPowerMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcPowerMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcPowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcPowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcVoltageDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcVoltageDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcVoltageMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcVoltageMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcVoltageMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcVoltageMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcVoltageMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcVoltageMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDcVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDcVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeFeatureMapWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFeatureMapWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeGeneratedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeGeneratedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeHarmonicCurrentMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeHarmonicCurrentMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeInstantaneousActiveCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInstantaneousActiveCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeInstantaneousLineCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInstantaneousLineCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeInstantaneousPowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInstantaneousPowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeInstantaneousReactiveCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInstantaneousReactiveCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeInstantaneousVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInstantaneousVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLineCurrentPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLineCurrentPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLineCurrentPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLineCurrentPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured11thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured11thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured1stHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured1stHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured3rdHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured3rdHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured5thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured5thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured7thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured7thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasured9thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasured9thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase11thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase11thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase1stHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase1stHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase3rdHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase3rdHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase5thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase5thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase7thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase7thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasuredPhase9thHarmonicCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasuredPhase9thHarmonicCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMeasurementTypeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMeasurementTypeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNeutralCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNeutralCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOverloadAlarmsMaskWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOverloadAlarmsMaskWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePhaseHarmonicCurrentMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePhaseHarmonicCurrentMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePowerDivisorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePowerDivisorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePowerFactorPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePowerFactorPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePowerFactorPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePowerFactorPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePowerFactorWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePowerFactorWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributePowerMultiplierWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributePowerMultiplierWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeReactiveCurrentPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeReactiveCurrentPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeReactiveCurrentPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeReactiveCurrentPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeReactivePowerPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeReactivePowerPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeReactivePowerPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeReactivePowerPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeReactivePowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeReactivePowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMaxPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMaxPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMaxPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMaxPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMinPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMinPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMinPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMinPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsCurrentWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsCurrentWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeOverVoltagePeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeOverVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeOverVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltagePeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsExtremeUnderVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMaxPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMaxPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMaxPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMaxPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMaxWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMaxWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMinPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMinPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMinPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMinPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageMinWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageMinWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltagePhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltagePhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltagePhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltagePhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSagPeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSagWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSagWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodPhaseBWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodPhaseBWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodPhaseCWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodPhaseCWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSwellPeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageSwellWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageSwellWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRmsVoltageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRmsVoltageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeTotalActivePowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTotalActivePowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeTotalApparentPowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTotalApparentPowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeTotalReactivePowerWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTotalReactivePowerWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeVoltageOverloadWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeVoltageOverloadWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
-(void)writeAttributeAcOverloadAlarmsMaskWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeAcOverloadAlarmsMaskWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeAcOverloadAlarmsMaskWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeAcOverloadAlarmsMaskWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeAverageRmsUnderVoltageCounterWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeAverageRmsUnderVoltageCounterWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeAverageRmsUnderVoltageCounterWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeAverageRmsUnderVoltageCounterWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeAverageRmsVoltageMeasurementPeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeAverageRmsVoltageMeasurementPeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeAverageRmsVoltageMeasurementPeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeAverageRmsVoltageMeasurementPeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOverloadAlarmsMaskWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOverloadAlarmsMaskWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOverloadAlarmsMaskWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOverloadAlarmsMaskWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRmsExtremeOverVoltagePeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRmsExtremeOverVoltagePeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRmsExtremeOverVoltagePeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRmsExtremeOverVoltagePeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRmsExtremeUnderVoltagePeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRmsExtremeUnderVoltagePeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRmsExtremeUnderVoltagePeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRmsExtremeUnderVoltagePeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRmsVoltageSagPeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRmsVoltageSagPeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRmsVoltageSagPeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRmsVoltageSagPeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRmsVoltageSwellPeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRmsVoltageSwellPeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRmsVoltageSwellPeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRmsVoltageSwellPeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;


@end


#endif