// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef MTRBASECLUSTERTESTCLUSTER_H
#define MTRBASECLUSTERTESTCLUSTER_H



#import "MTRBaseClusterUnitTesting.h"

@interface MTRBaseClusterTestCluster : MTRBaseClusterUnitTesting



+(void)readAttributeAcceptedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAttributeListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeBitmap16WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeBitmap32WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeBitmap64WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeBitmap8WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeBooleanWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeCharStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeClusterErrorBooleanWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeClusterRevisionWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnum16WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnum8WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnumAttrWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEpochSWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEpochUsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFeatureMapWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFloatDoubleWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFloatSingleWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeGeneralErrorBooleanWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt16sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt16uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt24sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt24uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt32sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt32uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt40sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt40uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt48sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt48uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt56sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt56uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt64sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt64uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt8sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListFabricScopedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListLongOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListNullablesAndOptionalsStructWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeListStructOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLongCharStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLongOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableBitmap16WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableBitmap32WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableBitmap64WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableBitmap8WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableBooleanWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableCharStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableEnum16WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableEnum8WithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableEnumAttrWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableFloatDoubleWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableFloatSingleWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt16sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt16uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt24sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt24uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt32sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt32uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt40sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt40uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt48sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt48uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt56sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt56uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt64sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt64uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt8sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableRangeRestrictedInt16sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableRangeRestrictedInt16uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableRangeRestrictedInt8sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableRangeRestrictedInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNullableStructWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOctetStringWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRangeRestrictedInt16sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRangeRestrictedInt16uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRangeRestrictedInt8sWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRangeRestrictedInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeStructAttrWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeTimedWriteBooleanWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUnsupportedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeVendorIdWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeWriteOnlyInt8uWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
-(id)initWithDevice:(id)arg0 endpoint:(unsigned short)arg1 queue:(id)arg2 ;
-(void)readAttributeAcceptedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeBitmap16WithCompletionHandler:(id)arg0 ;
-(void)readAttributeBitmap32WithCompletionHandler:(id)arg0 ;
-(void)readAttributeBitmap64WithCompletionHandler:(id)arg0 ;
-(void)readAttributeBitmap8WithCompletionHandler:(id)arg0 ;
-(void)readAttributeBooleanWithCompletionHandler:(id)arg0 ;
-(void)readAttributeCharStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeClusterErrorBooleanWithCompletionHandler:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnum16WithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnum8WithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnumAttrWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEpochSWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEpochUsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFloatDoubleWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFloatSingleWithCompletionHandler:(id)arg0 ;
-(void)readAttributeGeneralErrorBooleanWithCompletionHandler:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt16sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt16uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt24sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt24uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt32sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt32uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt40sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt40uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt48sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt48uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt56sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt56uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt64sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt64uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt8sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeInt8uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeListFabricScopedWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)readAttributeListInt8uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeListLongOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeListNullablesAndOptionalsStructWithCompletionHandler:(id)arg0 ;
-(void)readAttributeListOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeListStructOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLongCharStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLongOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableBitmap16WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableBitmap32WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableBitmap64WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableBitmap8WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableBooleanWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableCharStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableEnum16WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableEnum8WithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableEnumAttrWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableFloatDoubleWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableFloatSingleWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt16sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt16uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt24sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt24uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt32sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt32uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt40sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt40uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt48sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt48uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt56sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt56uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt64sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt64uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt8sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableInt8uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableRangeRestrictedInt16sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableRangeRestrictedInt16uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableRangeRestrictedInt8sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableRangeRestrictedInt8uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNullableStructWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOctetStringWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRangeRestrictedInt16sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRangeRestrictedInt16uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRangeRestrictedInt8sWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRangeRestrictedInt8uWithCompletionHandler:(id)arg0 ;
-(void)readAttributeStructAttrWithCompletionHandler:(id)arg0 ;
-(void)readAttributeTimedWriteBooleanWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUnsupportedWithCompletionHandler:(id)arg0 ;
-(void)readAttributeVendorIdWithCompletionHandler:(id)arg0 ;
-(void)readAttributeWriteOnlyInt8uWithCompletionHandler:(id)arg0 ;
-(void)simpleStructEchoRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
// -(void)subscribeAttributeAcceptedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAttributeListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeBitmap16WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeBitmap32WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeBitmap64WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeBitmap8WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeBooleanWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeCharStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeClusterErrorBooleanWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeClusterRevisionWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnum16WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnum8WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnumAttrWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEpochSWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEpochUsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFeatureMapWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFloatDoubleWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFloatSingleWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeGeneralErrorBooleanWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeGeneratedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt16sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt16uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt24sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt24uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt32sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt32uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt40sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt40uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt48sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt48uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt56sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt56uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt64sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt64uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt8sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListFabricScopedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListLongOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListNullablesAndOptionalsStructWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeListStructOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLongCharStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLongOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableBitmap16WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableBitmap32WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableBitmap64WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableBitmap8WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableBooleanWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableCharStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableEnum16WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableEnum8WithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableEnumAttrWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableFloatDoubleWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableFloatSingleWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt16sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt16uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt24sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt24uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt32sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt32uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt40sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt40uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt48sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt48uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt56sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt56uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt64sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt64uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt8sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableRangeRestrictedInt16sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableRangeRestrictedInt16uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableRangeRestrictedInt8sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableRangeRestrictedInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNullableStructWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOctetStringWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRangeRestrictedInt16sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRangeRestrictedInt16uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRangeRestrictedInt8sWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRangeRestrictedInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeStructAttrWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeTimedWriteBooleanWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUnsupportedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeVendorIdWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeWriteOnlyInt8uWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
-(void)testAddArgumentsWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testComplexNullableOptionalRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testEmitTestEventRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testEmitTestFabricScopedEventRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testEnumsRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testListInt8UArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testListInt8UReverseRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testListNestedStructListArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testListStructArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testNestedStructArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testNestedStructListArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testNotHandledWithCompletionHandler:(id)arg0 ;
-(void)testNotHandledWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testNullableOptionalRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testSimpleArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testSimpleOptionalArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testSpecificWithCompletionHandler:(id)arg0 ;
-(void)testSpecificWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testStructArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testStructArrayArgumentRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testUnknownCommandWithCompletionHandler:(id)arg0 ;
-(void)testUnknownCommandWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)testWithCompletionHandler:(id)arg0 ;
-(void)testWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)timedInvokeRequestWithCompletionHandler:(id)arg0 ;
-(void)timedInvokeRequestWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBitmap16WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBitmap16WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeBitmap32WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBitmap32WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeBitmap64WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBitmap64WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeBitmap8WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBitmap8WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeBooleanWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeBooleanWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeCharStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeCharStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeClusterErrorBooleanWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeClusterErrorBooleanWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnum16WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnum16WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnum8WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnum8WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnumAttrWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnumAttrWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEpochSWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEpochSWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEpochUsWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEpochUsWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeFloatDoubleWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeFloatDoubleWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeFloatSingleWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeFloatSingleWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeGeneralErrorBooleanWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeGeneralErrorBooleanWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt16sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt16sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt16uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt16uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt24sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt24sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt24uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt24uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt32sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt32sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt32uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt32uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt40sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt40sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt40uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt40uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt48sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt48sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt48uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt48uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt56sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt56sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt56uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt56uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt64sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt64sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt64uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt64uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt8sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt8sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListFabricScopedWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListFabricScopedWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListLongOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListLongOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListNullablesAndOptionalsStructWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListNullablesAndOptionalsStructWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeListStructOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeListStructOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLongCharStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLongCharStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLongOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLongOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableBitmap16WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableBitmap16WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableBitmap32WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableBitmap32WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableBitmap64WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableBitmap64WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableBitmap8WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableBitmap8WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableBooleanWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableBooleanWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableCharStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableCharStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableEnum16WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableEnum16WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableEnum8WithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableEnum8WithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableEnumAttrWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableEnumAttrWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableFloatDoubleWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableFloatDoubleWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableFloatSingleWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableFloatSingleWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt16sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt16sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt16uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt16uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt24sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt24sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt24uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt24uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt32sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt32sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt32uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt32uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt40sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt40sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt40uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt40uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt48sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt48sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt48uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt48uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt56sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt56sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt56uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt56uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt64sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt64sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt64uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt64uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt8sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt8sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableRangeRestrictedInt16sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableRangeRestrictedInt16sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableRangeRestrictedInt16uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableRangeRestrictedInt16uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableRangeRestrictedInt8sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableRangeRestrictedInt8sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableRangeRestrictedInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableRangeRestrictedInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeNullableStructWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeNullableStructWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOctetStringWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOctetStringWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRangeRestrictedInt16sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRangeRestrictedInt16sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRangeRestrictedInt16uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRangeRestrictedInt16uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRangeRestrictedInt8sWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRangeRestrictedInt8sWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRangeRestrictedInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRangeRestrictedInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeStructAttrWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeStructAttrWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeTimedWriteBooleanWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeTimedWriteBooleanWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeUnsupportedWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeUnsupportedWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeVendorIdWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeVendorIdWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeWriteOnlyInt8uWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeWriteOnlyInt8uWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;


@end


#endif