// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef MTRBASECLUSTERDOORLOCK_H
#define MTRBASECLUSTERDOORLOCK_H



#import "MTRCluster.h"
#import "MTRBaseDevice.h"

@interface MTRBaseClusterDoorLock : MTRCluster

@property (readonly, nonatomic) MTRBaseDevice *device; // ivar: _device
@property (readonly, nonatomic) unsigned short endpoint; // ivar: _endpoint


+(void)readAttributeAcceptedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAcceptedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeActuatorEnabledWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeActuatorEnabledWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAttributeListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAttributeListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeAutoRelockTimeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeAutoRelockTimeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeClusterRevisionWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeClusterRevisionWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeCredentialRulesSupportWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeCredentialRulesSupportWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDefaultConfigurationRegisterWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDefaultConfigurationRegisterWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDoorClosedEventsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDoorClosedEventsWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDoorOpenEventsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDoorOpenEventsWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeDoorStateWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeDoorStateWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeEnableInsideStatusLEDWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnableInsideStatusLEDWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeEnableLocalProgrammingWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnableLocalProgrammingWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeEnableOneTouchLockingWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnableOneTouchLockingWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeEnablePrivacyModeButtonWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeEnablePrivacyModeButtonWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeExpiringUserTimeoutWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeExpiringUserTimeoutWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeFeatureMapWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeFeatureMapWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeGeneratedCommandListWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLEDSettingsWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLEDSettingsWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLanguageWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLanguageWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLocalProgrammingFeaturesWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLocalProgrammingFeaturesWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLockStateWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLockStateWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeLockTypeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeLockTypeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMaxPINCodeLengthWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMaxPINCodeLengthWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMaxRFIDCodeLengthWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMaxRFIDCodeLengthWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMinPINCodeLengthWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMinPINCodeLengthWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeMinRFIDCodeLengthWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeMinRFIDCodeLengthWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfCredentialsSupportedPerUserWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfCredentialsSupportedPerUserWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfHolidaySchedulesSupportedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfHolidaySchedulesSupportedWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfPINUsersSupportedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfPINUsersSupportedWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfRFIDUsersSupportedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfRFIDUsersSupportedWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfTotalUsersSupportedWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfTotalUsersSupportedWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfWeekDaySchedulesSupportedPerUserWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfWeekDaySchedulesSupportedPerUserWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeNumberOfYearDaySchedulesSupportedPerUserWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeNumberOfYearDaySchedulesSupportedPerUserWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOpenPeriodWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOpenPeriodWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeOperatingModeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeOperatingModeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeRequirePINforRemoteOperationWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeRequirePINforRemoteOperationWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSendPINOverTheAirWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSendPINOverTheAirWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSoundVolumeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSoundVolumeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeSupportedOperatingModesWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeSupportedOperatingModesWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeUserCodeTemporaryDisableTimeWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeUserCodeTemporaryDisableTimeWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
+(void)readAttributeWrongCodeEntryLimitWithAttributeCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completionHandler:(id)arg3 ;
+(void)readAttributeWrongCodeEntryLimitWithClusterStateCache:(id)arg0 endpoint:(id)arg1 queue:(id)arg2 completion:(id)arg3 ;
-(id)initWithDevice:(id)arg0 endpoint:(unsigned short)arg1 queue:(id)arg2 ;
-(id)initWithDevice:(id)arg0 endpointID:(id)arg1 queue:(id)arg2 ;
-(void)clearCredentialWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearCredentialWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)clearHolidayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearHolidayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)clearUserWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearUserWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)clearWeekDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearWeekDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)clearYearDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)clearYearDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getCredentialStatusWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getCredentialStatusWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getHolidayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getHolidayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getUserWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getUserWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getWeekDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getWeekDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)getYearDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)getYearDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)lockDoorWithParams:(id)arg0 completion:(id)arg1 ;
-(void)lockDoorWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)readAttributeAcceptedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeAcceptedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeActuatorEnabledWithCompletion:(id)arg0 ;
-(void)readAttributeActuatorEnabledWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletion:(id)arg0 ;
-(void)readAttributeAttributeListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeAutoRelockTimeWithCompletion:(id)arg0 ;
-(void)readAttributeAutoRelockTimeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletion:(id)arg0 ;
-(void)readAttributeClusterRevisionWithCompletionHandler:(id)arg0 ;
-(void)readAttributeCredentialRulesSupportWithCompletion:(id)arg0 ;
-(void)readAttributeCredentialRulesSupportWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDefaultConfigurationRegisterWithCompletion:(id)arg0 ;
-(void)readAttributeDefaultConfigurationRegisterWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDoorClosedEventsWithCompletion:(id)arg0 ;
-(void)readAttributeDoorClosedEventsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDoorOpenEventsWithCompletion:(id)arg0 ;
-(void)readAttributeDoorOpenEventsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeDoorStateWithCompletion:(id)arg0 ;
-(void)readAttributeDoorStateWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnableInsideStatusLEDWithCompletion:(id)arg0 ;
-(void)readAttributeEnableInsideStatusLEDWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnableLocalProgrammingWithCompletion:(id)arg0 ;
-(void)readAttributeEnableLocalProgrammingWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnableOneTouchLockingWithCompletion:(id)arg0 ;
-(void)readAttributeEnableOneTouchLockingWithCompletionHandler:(id)arg0 ;
-(void)readAttributeEnablePrivacyModeButtonWithCompletion:(id)arg0 ;
-(void)readAttributeEnablePrivacyModeButtonWithCompletionHandler:(id)arg0 ;
-(void)readAttributeExpiringUserTimeoutWithCompletion:(id)arg0 ;
-(void)readAttributeExpiringUserTimeoutWithCompletionHandler:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletion:(id)arg0 ;
-(void)readAttributeFeatureMapWithCompletionHandler:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletion:(id)arg0 ;
-(void)readAttributeGeneratedCommandListWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLEDSettingsWithCompletion:(id)arg0 ;
-(void)readAttributeLEDSettingsWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLanguageWithCompletion:(id)arg0 ;
-(void)readAttributeLanguageWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLocalProgrammingFeaturesWithCompletion:(id)arg0 ;
-(void)readAttributeLocalProgrammingFeaturesWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLockStateWithCompletion:(id)arg0 ;
-(void)readAttributeLockStateWithCompletionHandler:(id)arg0 ;
-(void)readAttributeLockTypeWithCompletion:(id)arg0 ;
-(void)readAttributeLockTypeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMaxPINCodeLengthWithCompletion:(id)arg0 ;
-(void)readAttributeMaxPINCodeLengthWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMaxRFIDCodeLengthWithCompletion:(id)arg0 ;
-(void)readAttributeMaxRFIDCodeLengthWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMinPINCodeLengthWithCompletion:(id)arg0 ;
-(void)readAttributeMinPINCodeLengthWithCompletionHandler:(id)arg0 ;
-(void)readAttributeMinRFIDCodeLengthWithCompletion:(id)arg0 ;
-(void)readAttributeMinRFIDCodeLengthWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfCredentialsSupportedPerUserWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfCredentialsSupportedPerUserWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfHolidaySchedulesSupportedWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfHolidaySchedulesSupportedWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfPINUsersSupportedWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfPINUsersSupportedWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfRFIDUsersSupportedWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfRFIDUsersSupportedWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfTotalUsersSupportedWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfTotalUsersSupportedWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfWeekDaySchedulesSupportedPerUserWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfWeekDaySchedulesSupportedPerUserWithCompletionHandler:(id)arg0 ;
-(void)readAttributeNumberOfYearDaySchedulesSupportedPerUserWithCompletion:(id)arg0 ;
-(void)readAttributeNumberOfYearDaySchedulesSupportedPerUserWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOpenPeriodWithCompletion:(id)arg0 ;
-(void)readAttributeOpenPeriodWithCompletionHandler:(id)arg0 ;
-(void)readAttributeOperatingModeWithCompletion:(id)arg0 ;
-(void)readAttributeOperatingModeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeRequirePINforRemoteOperationWithCompletion:(id)arg0 ;
-(void)readAttributeRequirePINforRemoteOperationWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSendPINOverTheAirWithCompletion:(id)arg0 ;
-(void)readAttributeSendPINOverTheAirWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSoundVolumeWithCompletion:(id)arg0 ;
-(void)readAttributeSoundVolumeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeSupportedOperatingModesWithCompletion:(id)arg0 ;
-(void)readAttributeSupportedOperatingModesWithCompletionHandler:(id)arg0 ;
-(void)readAttributeUserCodeTemporaryDisableTimeWithCompletion:(id)arg0 ;
-(void)readAttributeUserCodeTemporaryDisableTimeWithCompletionHandler:(id)arg0 ;
-(void)readAttributeWrongCodeEntryLimitWithCompletion:(id)arg0 ;
-(void)readAttributeWrongCodeEntryLimitWithCompletionHandler:(id)arg0 ;
-(void)setCredentialWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setCredentialWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)setHolidayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setHolidayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)setUserWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setUserWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)setWeekDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setWeekDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)setYearDayScheduleWithParams:(id)arg0 completion:(id)arg1 ;
-(void)setYearDayScheduleWithParams:(id)arg0 completionHandler:(id)arg1 ;
// -(void)subscribeAttributeAcceptedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAcceptedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeActuatorEnabledWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeActuatorEnabledWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAttributeListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAttributeListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeAutoRelockTimeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeAutoRelockTimeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeClusterRevisionWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeClusterRevisionWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeCredentialRulesSupportWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeCredentialRulesSupportWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDefaultConfigurationRegisterWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDefaultConfigurationRegisterWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDoorClosedEventsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDoorClosedEventsWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDoorOpenEventsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDoorOpenEventsWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeDoorStateWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeDoorStateWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeEnableInsideStatusLEDWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnableInsideStatusLEDWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeEnableLocalProgrammingWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnableLocalProgrammingWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeEnableOneTouchLockingWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnableOneTouchLockingWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeEnablePrivacyModeButtonWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeEnablePrivacyModeButtonWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeExpiringUserTimeoutWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeExpiringUserTimeoutWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeFeatureMapWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeFeatureMapWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeGeneratedCommandListWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeGeneratedCommandListWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLEDSettingsWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLEDSettingsWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLanguageWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLanguageWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLocalProgrammingFeaturesWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLocalProgrammingFeaturesWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLockStateWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLockStateWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeLockTypeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeLockTypeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMaxPINCodeLengthWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMaxPINCodeLengthWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMaxRFIDCodeLengthWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMaxRFIDCodeLengthWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMinPINCodeLengthWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMinPINCodeLengthWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeMinRFIDCodeLengthWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeMinRFIDCodeLengthWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfCredentialsSupportedPerUserWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfCredentialsSupportedPerUserWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfHolidaySchedulesSupportedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfHolidaySchedulesSupportedWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfPINUsersSupportedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfPINUsersSupportedWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfRFIDUsersSupportedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfRFIDUsersSupportedWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfTotalUsersSupportedWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfTotalUsersSupportedWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfWeekDaySchedulesSupportedPerUserWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfWeekDaySchedulesSupportedPerUserWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeNumberOfYearDaySchedulesSupportedPerUserWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeNumberOfYearDaySchedulesSupportedPerUserWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOpenPeriodWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOpenPeriodWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeOperatingModeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeOperatingModeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeRequirePINforRemoteOperationWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeRequirePINforRemoteOperationWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSendPINOverTheAirWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSendPINOverTheAirWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSoundVolumeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSoundVolumeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeSupportedOperatingModesWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeSupportedOperatingModesWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeUserCodeTemporaryDisableTimeWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeUserCodeTemporaryDisableTimeWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
// -(void)subscribeAttributeWrongCodeEntryLimitWithMinInterval:(id)arg0 maxInterval:(id)arg1 params:(id)arg2 subscriptionEstablished:(id)arg3 reportHandler:(unk)arg4  ;
// -(void)subscribeAttributeWrongCodeEntryLimitWithParams:(id)arg0 subscriptionEstablished:(id)arg1 reportHandler:(unk)arg2  ;
-(void)unlockDoorWithParams:(id)arg0 completion:(id)arg1 ;
-(void)unlockDoorWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)unlockWithTimeoutWithParams:(id)arg0 completion:(id)arg1 ;
-(void)unlockWithTimeoutWithParams:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeAutoRelockTimeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeAutoRelockTimeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeAutoRelockTimeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeAutoRelockTimeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeDoorClosedEventsWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeDoorClosedEventsWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeDoorClosedEventsWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeDoorClosedEventsWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeDoorOpenEventsWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeDoorOpenEventsWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeDoorOpenEventsWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeDoorOpenEventsWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnableInsideStatusLEDWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeEnableInsideStatusLEDWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnableInsideStatusLEDWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeEnableInsideStatusLEDWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnableLocalProgrammingWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeEnableLocalProgrammingWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnableLocalProgrammingWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeEnableLocalProgrammingWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnableOneTouchLockingWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeEnableOneTouchLockingWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnableOneTouchLockingWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeEnableOneTouchLockingWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeEnablePrivacyModeButtonWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeEnablePrivacyModeButtonWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeEnablePrivacyModeButtonWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeEnablePrivacyModeButtonWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeExpiringUserTimeoutWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeExpiringUserTimeoutWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeExpiringUserTimeoutWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeExpiringUserTimeoutWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLEDSettingsWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeLEDSettingsWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLEDSettingsWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeLEDSettingsWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLanguageWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeLanguageWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLanguageWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeLanguageWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeLocalProgrammingFeaturesWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeLocalProgrammingFeaturesWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeLocalProgrammingFeaturesWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeLocalProgrammingFeaturesWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOpenPeriodWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOpenPeriodWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOpenPeriodWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOpenPeriodWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeOperatingModeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeOperatingModeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeOperatingModeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeOperatingModeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeRequirePINforRemoteOperationWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeRequirePINforRemoteOperationWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeRequirePINforRemoteOperationWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeRequirePINforRemoteOperationWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeSendPINOverTheAirWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeSendPINOverTheAirWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeSendPINOverTheAirWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeSendPINOverTheAirWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeSoundVolumeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeSoundVolumeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeSoundVolumeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeSoundVolumeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeUserCodeTemporaryDisableTimeWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeUserCodeTemporaryDisableTimeWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeUserCodeTemporaryDisableTimeWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeUserCodeTemporaryDisableTimeWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;
-(void)writeAttributeWrongCodeEntryLimitWithValue:(id)arg0 completion:(id)arg1 ;
-(void)writeAttributeWrongCodeEntryLimitWithValue:(id)arg0 completionHandler:(id)arg1 ;
-(void)writeAttributeWrongCodeEntryLimitWithValue:(id)arg0 params:(id)arg1 completion:(id)arg2 ;
-(void)writeAttributeWrongCodeEntryLimitWithValue:(id)arg0 params:(id)arg1 completionHandler:(id)arg2 ;


@end


#endif