// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef _TTC23SIRIINVOCATIONANALYTICS20INTERTURNFEATUREKEYS_H
#define _TTC23SIRIINVOCATIONANALYTICS20INTERTURNFEATUREKEYS_H


#import <Foundation/Foundation.h>


@interface _TtC23SiriInvocationAnalytics20InterTurnFeatureKeys : NSObject



+(id)CANCELLATION_FOLLOWED_KEY;
+(id)CONFIRMATION_FOLLOWED_KEY;
+(id)PHONETIC_RESTATE_SCORE_NEXT_CONV_KEY;
+(id)PHONETIC_RESTATE_SCORE_NEXT_REQ_KEY;
+(id)SECONDS_TILL_NEXT_CONVERSATION_KEY;
+(id)SECONDS_TILL_NEXT_REQUEST_KEY;
+(id)TEXT_SIMILARITY_NEXT_CONVERSATION_KEY;
+(id)TEXT_SIMILARITY_SCORE_WITH_NEXT_REQ_KEY;
-(id)init;


@end


#endif