// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef _TTC23SIRIINVOCATIONANALYTICS20INTRATURNFEATUREKEYS_H
#define _TTC23SIRIINVOCATIONANALYTICS20INTRATURNFEATUREKEYS_H


#import <Foundation/Foundation.h>


@interface _TtC23SiriInvocationAnalytics20IntraTurnFeatureKeys : NSObject



+(id)ASR_BEST_PHONETIC_SEQUENCE_KEY;
+(id)ASR_BEST_POST_ITN_UTTERANCE_KEY;
+(id)DIM_DEVICE_TYPE_KEY;
+(id)DIM_OPT_IN_STATUS_KEY;
+(id)DIM_SIRI_INPUT_LOCALE_KEY;
+(id)DIM_SYSTEM_BUILD_KEY;
+(id)DIM_TIMESTAMP_KEY;
+(id)FLOW_FINAL_FLOW_STATE_TYPE_KEY;
+(id)FLOW_FINAL_FLOW_STATUS_REASON_KEY;
+(id)FLOW_FINAL_FLOW_TASK_NAME_KEY;
+(id)FLOW_STATE_TYPE_SEQUENCE_KEY;
+(id)FLOW_STATUS_REASON_SEQUENCE_KEY;
+(id)FLOW_TASK_NAME_SEQUENCE_KEY;
+(id)ORCH_REQUEST_ID_KEY;
+(id)SIRI_MH_URES_MITIGATOR_SCORE;
+(id)SIRI_MH_URES_MITIGATOR_THRESHOLD;
+(id)UEI_CAT_ID_KEY;
+(id)UEI_CAT_ID_SEQUENCE_KEY;
+(id)UEI_DISMISSAL_REASON_KEY;
+(id)UEI_INVOCATION_SOURCE_ID_KEY;
+(id)UEI_INVOCATION_SOURCE_KEY;
+(id)UEI_SPEAKEASY_CATEGORY_KEY;
+(id)VALID_TURN_CONTAINS_ASR_CANCELLED;
+(id)VALID_TURN_CONTAINS_ASR_FAILED;
+(id)VALID_TURN_CONTAINS_ORCH_CANCELLED;
+(id)VALID_TURN_CONTAINS_ORCH_ENDED;
+(id)VALID_TURN_CONTAINS_ORCH_FAILED;
+(id)VALID_TURN_CONTAINS_UUFR_PRESENTED;
+(id)VALID_TURN_CONTAINS_UUFR_SAID;
+(id)VALID_TURN_CONTAINS_UUFR_SHOWN;
+(id)VALID_TURN_KEY;
+(id)VALID_TURN_ORCH_CANCELLATION_REASON;
-(id)init;


@end


#endif