// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef _TTC23SIRIINVOCATIONANALYTICS21INTRAEVENTFEATUREKEYS_H
#define _TTC23SIRIINVOCATIONANALYTICS21INTRAEVENTFEATUREKEYS_H


#import <Foundation/Foundation.h>


@interface _TtC23SiriInvocationAnalytics21IntraEventFeatureKeys : NSObject



+(id)APP_LAUNCH_BUNDLE_ID_KEY;
+(id)APP_LAUNCH_IS_STARTING_KEY;
+(id)APP_LAUNCH_LAUNCH_REASON_KEY;
+(id)APP_LAUNCH_LAUNCH_TYPE_KEY;
+(id)CARPLAY_IS_STARTING_KEY;
+(id)CARPLAY_REASON_KEY;
+(id)NOTIFICATION_BUNDLE_ID_KEY;
+(id)NOTIFICATION_SECTION_ID_KEY;
+(id)NOTIFICATION_USAGE_TYPE_KEY;
+(id)NOW_PLAYING_ALBUM_KEY;
+(id)NOW_PLAYING_ARTIST_KEY;
+(id)NOW_PLAYING_BUNDLE_ID_KEY;
+(id)NOW_PLAYING_DURATION_KEY;
+(id)NOW_PLAYING_ELAPSED_KEY;
+(id)NOW_PLAYING_GENRE_KEY;
+(id)NOW_PLAYING_MEDIA_TYPE_KEY;
+(id)NOW_PLAYING_PLAYBACK_STATE_KEY;
+(id)NOW_PLAYING_TITLE_KEY;
+(id)POI_CATEGORY_KEY;
+(id)READ_MESSAGE_IDS_HANDLE_KEY;
+(id)SEMANTIC_LOCATION_PLACE_TYPE_KEY;
+(id)SEMANTIC_LOCATION_STARTING_KEY;
+(id)SEMANTIC_LOCATION_USER_SPECIFIC_KEY;
+(id)SIRI_EXECUTION_APP_BUNDLE_ID_KEY;
+(id)SIRI_EXECUTION_INTENT_NAME_KEY;
+(id)SIRI_EXECUTION_SLOT_VALUE_KEY;
+(id)SIRI_EXECUTION_STATUS_REASON_KEY;
+(id)SIRI_UI_DIMISSAL_REASON_KEY;
+(id)SIRI_UI_IS_STARTING_KEY;
+(id)SIRI_UI_VIEW_MODE_KEY;
+(id)SLEEP_MODE_CHANGE_REASON_KEY;
+(id)SLEEP_MODE_EXPECTED_END_DATE_KEY;
+(id)SLEEP_MODE_STATE_KEY;
+(id)TEXT_INPUT_BUNDLE_ID_KEY;
+(id)TEXT_INPUT_DATE_INTERVAL_KEY;
+(id)USER_STATUS_CHANGE_CHANGE_TYPE_KEY;
+(id)USER_STATUS_CHANGE_IDS_HANDLES_KEY;
-(id)init;


@end


#endif