// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef GEOCELLCONNECTIONQUALITY_H
#define GEOCELLCONNECTIONQUALITY_H

@class PBCodable, PBDataReader, NSString;
@protocol NSCopying;


#import "GEOLocation.h"

@interface GEOCellConnectionQuality : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    NSUInteger _bytesDlTotal;
    NSUInteger _bytesUlTotal;
    NSString *_callID;
    NSString *_cellGCI;
    NSString *_cellHomePLMN2;
    NSString *_cellHomePLMN;
    NSString *_cellRatType;
    NSString *_cellServiceProvider2;
    NSString *_cellServiceProvider;
    NSString *_ftIRATRecommendationReason;
    NSString *_ftIRATRecommendation;
    GEOLocation *_location;
    NSUInteger _timeOfDay;
    NSInteger _wifiRssi;
    NSInteger _wifiSNR;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _cellArfcn;
    unsigned int _cellBand;
    unsigned int _cellBssLoad;
    unsigned int _cellDataLQM;
    unsigned int _cellEstimatedBW;
    int _cellLteRSRP;
    int _cellLteRSRQ;
    int _cellLteSNR;
    unsigned int _cellMaxDlCaNumConf;
    unsigned int _cellMaxUlCaNumConf;
    unsigned int _cellNpn;
    int _cellNrRSRP;
    int _cellNrRSRQ;
    int _cellNrSNR;
    unsigned int _cellNsaFR1;
    unsigned int _cellNsaFR2;
    unsigned int _cellPMax;
    unsigned int _cellRrcState;
    unsigned int _cellTotalDlBW;
    unsigned int _cellTotalUlBW;
    unsigned int _cellVoiceLQM;
    unsigned int _connectionDuration;
    int _connectionType;
    float _dlMedThroughput;
    float _dlPeakThroughput;
    int _environment;
    unsigned int _ftCounter;
    unsigned int _ftFacetimeAction;
    unsigned int _ftFacetimePacketLoss;
    unsigned int _ftFacetimeTimeDelay;
    unsigned int _latency;
    int _messageTrigger;
    int _messageType;
    int _motionState;
    float _ulMedThroughput;
    float _ulPeakThroughput;
    unsigned int _wifiBand;
    unsigned int _wifiCca;
    unsigned int _wifiChannelWidth;
    unsigned int _wifiChannel;
    unsigned int _wifiEstimatedBW;
    unsigned int _wifiPhyMode;
    unsigned int _wifiQbssLoad;
    unsigned int _wifiRxPhyRate;
    unsigned int _wifiRxRetry;
    unsigned int _wifiStationCount;
    unsigned int _wifiTxPER;
    unsigned int _wifiTxPhyRate;
    unsigned int _wrmAudioErasure;
    unsigned int _wrmVideoErasure;
    BOOL _cellIsLimitedService;
    BOOL _cellIsNoService;
    BOOL _cellIsRoaming;
    BOOL _cellNpnStatus;
    BOOL _isCallFailed;
    BOOL _isEmergency;
    BOOL _lowInternetDL;
    BOOL _lowInternetUL;
    BOOL _wifiCaptiveNetworks;
    BOOL _wrmAlertedMode;
    BOOL _wrmIsPCDetected;
    BOOL _wrmIsStallDetected;
    ? _flags;
}


@property (nonatomic) NSUInteger bytesDlTotal;
@property (nonatomic) NSUInteger bytesUlTotal;
@property (retain, nonatomic) NSString *callID;
@property (nonatomic) unsigned int cellArfcn;
@property (nonatomic) unsigned int cellBand;
@property (nonatomic) unsigned int cellBssLoad;
@property (nonatomic) unsigned int cellDataLQM;
@property (nonatomic) unsigned int cellEstimatedBW;
@property (retain, nonatomic) NSString *cellGCI;
@property (retain, nonatomic) NSString *cellHomePLMN;
@property (retain, nonatomic) NSString *cellHomePLMN2;
@property (nonatomic) BOOL cellIsLimitedService;
@property (nonatomic) BOOL cellIsNoService;
@property (nonatomic) BOOL cellIsRoaming;
@property (nonatomic) int cellLteRSRP;
@property (nonatomic) int cellLteRSRQ;
@property (nonatomic) int cellLteSNR;
@property (nonatomic) unsigned int cellMaxDlCaNumConf;
@property (nonatomic) unsigned int cellMaxUlCaNumConf;
@property (nonatomic) unsigned int cellNpn;
@property (nonatomic) BOOL cellNpnStatus;
@property (nonatomic) int cellNrRSRP;
@property (nonatomic) int cellNrRSRQ;
@property (nonatomic) int cellNrSNR;
@property (nonatomic) unsigned int cellNsaFR1;
@property (nonatomic) unsigned int cellNsaFR2;
@property (nonatomic) unsigned int cellPMax;
@property (retain, nonatomic) NSString *cellRatType;
@property (nonatomic) unsigned int cellRrcState;
@property (retain, nonatomic) NSString *cellServiceProvider;
@property (retain, nonatomic) NSString *cellServiceProvider2;
@property (nonatomic) unsigned int cellTotalDlBW;
@property (nonatomic) unsigned int cellTotalUlBW;
@property (nonatomic) unsigned int cellVoiceLQM;
@property (nonatomic) unsigned int connectionDuration;
@property (nonatomic) int connectionType;
@property (nonatomic) float dlMedThroughput;
@property (nonatomic) float dlPeakThroughput;
@property (nonatomic) int environment;
@property (nonatomic) unsigned int ftCounter;
@property (nonatomic) unsigned int ftFacetimeAction;
@property (nonatomic) unsigned int ftFacetimePacketLoss;
@property (nonatomic) unsigned int ftFacetimeTimeDelay;
@property (retain, nonatomic) NSString *ftIRATRecommendation;
@property (retain, nonatomic) NSString *ftIRATRecommendationReason;
@property (nonatomic) BOOL hasBytesDlTotal;
@property (nonatomic) BOOL hasBytesUlTotal;
@property (readonly, nonatomic) BOOL hasCallID;
@property (nonatomic) BOOL hasCellArfcn;
@property (nonatomic) BOOL hasCellBand;
@property (nonatomic) BOOL hasCellBssLoad;
@property (nonatomic) BOOL hasCellDataLQM;
@property (nonatomic) BOOL hasCellEstimatedBW;
@property (readonly, nonatomic) BOOL hasCellGCI;
@property (readonly, nonatomic) BOOL hasCellHomePLMN;
@property (readonly, nonatomic) BOOL hasCellHomePLMN2;
@property (nonatomic) BOOL hasCellIsLimitedService;
@property (nonatomic) BOOL hasCellIsNoService;
@property (nonatomic) BOOL hasCellIsRoaming;
@property (nonatomic) BOOL hasCellLteRSRP;
@property (nonatomic) BOOL hasCellLteRSRQ;
@property (nonatomic) BOOL hasCellLteSNR;
@property (nonatomic) BOOL hasCellMaxDlCaNumConf;
@property (nonatomic) BOOL hasCellMaxUlCaNumConf;
@property (nonatomic) BOOL hasCellNpn;
@property (nonatomic) BOOL hasCellNpnStatus;
@property (nonatomic) BOOL hasCellNrRSRP;
@property (nonatomic) BOOL hasCellNrRSRQ;
@property (nonatomic) BOOL hasCellNrSNR;
@property (nonatomic) BOOL hasCellNsaFR1;
@property (nonatomic) BOOL hasCellNsaFR2;
@property (nonatomic) BOOL hasCellPMax;
@property (readonly, nonatomic) BOOL hasCellRatType;
@property (nonatomic) BOOL hasCellRrcState;
@property (readonly, nonatomic) BOOL hasCellServiceProvider;
@property (readonly, nonatomic) BOOL hasCellServiceProvider2;
@property (nonatomic) BOOL hasCellTotalDlBW;
@property (nonatomic) BOOL hasCellTotalUlBW;
@property (nonatomic) BOOL hasCellVoiceLQM;
@property (nonatomic) BOOL hasConnectionDuration;
@property (nonatomic) BOOL hasConnectionType;
@property (nonatomic) BOOL hasDlMedThroughput;
@property (nonatomic) BOOL hasDlPeakThroughput;
@property (nonatomic) BOOL hasEnvironment;
@property (nonatomic) BOOL hasFtCounter;
@property (nonatomic) BOOL hasFtFacetimeAction;
@property (nonatomic) BOOL hasFtFacetimePacketLoss;
@property (nonatomic) BOOL hasFtFacetimeTimeDelay;
@property (readonly, nonatomic) BOOL hasFtIRATRecommendation;
@property (readonly, nonatomic) BOOL hasFtIRATRecommendationReason;
@property (nonatomic) BOOL hasIsCallFailed;
@property (nonatomic) BOOL hasIsEmergency;
@property (nonatomic) BOOL hasLatency;
@property (readonly, nonatomic) BOOL hasLocation;
@property (nonatomic) BOOL hasLowInternetDL;
@property (nonatomic) BOOL hasLowInternetUL;
@property (nonatomic) BOOL hasMessageTrigger;
@property (nonatomic) BOOL hasMessageType;
@property (nonatomic) BOOL hasMotionState;
@property (nonatomic) BOOL hasTimeOfDay;
@property (nonatomic) BOOL hasUlMedThroughput;
@property (nonatomic) BOOL hasUlPeakThroughput;
@property (nonatomic) BOOL hasWifiBand;
@property (nonatomic) BOOL hasWifiCaptiveNetworks;
@property (nonatomic) BOOL hasWifiCca;
@property (nonatomic) BOOL hasWifiChannel;
@property (nonatomic) BOOL hasWifiChannelWidth;
@property (nonatomic) BOOL hasWifiEstimatedBW;
@property (nonatomic) BOOL hasWifiPhyMode;
@property (nonatomic) BOOL hasWifiQbssLoad;
@property (nonatomic) BOOL hasWifiRssi;
@property (nonatomic) BOOL hasWifiRxPhyRate;
@property (nonatomic) BOOL hasWifiRxRetry;
@property (nonatomic) BOOL hasWifiSNR;
@property (nonatomic) BOOL hasWifiStationCount;
@property (nonatomic) BOOL hasWifiTxPER;
@property (nonatomic) BOOL hasWifiTxPhyRate;
@property (nonatomic) BOOL hasWrmAlertedMode;
@property (nonatomic) BOOL hasWrmAudioErasure;
@property (nonatomic) BOOL hasWrmIsPCDetected;
@property (nonatomic) BOOL hasWrmIsStallDetected;
@property (nonatomic) BOOL hasWrmVideoErasure;
@property (nonatomic) BOOL isCallFailed;
@property (nonatomic) BOOL isEmergency;
@property (nonatomic) unsigned int latency;
@property (retain, nonatomic) GEOLocation *location;
@property (nonatomic) BOOL lowInternetDL;
@property (nonatomic) BOOL lowInternetUL;
@property (nonatomic) int messageTrigger;
@property (nonatomic) int messageType;
@property (nonatomic) int motionState;
@property (nonatomic) NSUInteger timeOfDay;
@property (nonatomic) float ulMedThroughput;
@property (nonatomic) float ulPeakThroughput;
@property (nonatomic) unsigned int wifiBand;
@property (nonatomic) BOOL wifiCaptiveNetworks;
@property (nonatomic) unsigned int wifiCca;
@property (nonatomic) unsigned int wifiChannel;
@property (nonatomic) unsigned int wifiChannelWidth;
@property (nonatomic) unsigned int wifiEstimatedBW;
@property (nonatomic) unsigned int wifiPhyMode;
@property (nonatomic) unsigned int wifiQbssLoad;
@property (nonatomic) NSInteger wifiRssi;
@property (nonatomic) unsigned int wifiRxPhyRate;
@property (nonatomic) unsigned int wifiRxRetry;
@property (nonatomic) NSInteger wifiSNR;
@property (nonatomic) unsigned int wifiStationCount;
@property (nonatomic) unsigned int wifiTxPER;
@property (nonatomic) unsigned int wifiTxPhyRate;
@property (nonatomic) BOOL wrmAlertedMode;
@property (nonatomic) unsigned int wrmAudioErasure;
@property (nonatomic) BOOL wrmIsPCDetected;
@property (nonatomic) BOOL wrmIsStallDetected;
@property (nonatomic) unsigned int wrmVideoErasure;


+(BOOL)isValid:(id)arg0 ;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)readFrom:(id)arg0 ;
-(NSUInteger)hash;
-(id)connectionTypeAsString:(int)arg0 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)description;
-(id)dictionaryRepresentation;
-(id)environmentAsString:(int)arg0 ;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)messageTriggerAsString:(int)arg0 ;
-(id)messageTypeAsString:(int)arg0 ;
-(id)motionStateAsString:(int)arg0 ;
-(int)StringAsConnectionType:(id)arg0 ;
-(int)StringAsEnvironment:(id)arg0 ;
-(int)StringAsMessageTrigger:(id)arg0 ;
-(int)StringAsMessageType:(id)arg0 ;
-(int)StringAsMotionState:(id)arg0 ;
-(void)clearSensitiveFields:(NSUInteger)arg0 ;
-(void)copyTo:(id)arg0 ;
-(void)mergeFrom:(id)arg0 ;
-(void)readAll:(BOOL)arg0 ;
-(void)writeTo:(id)arg0 ;


@end


#endif