// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef GEOROUTE_H
#define GEOROUTE_H

@class PBCodable, PBDataReader, PBUnknownFields, NSMutableArray, NSData, NSString;
@protocol NSCopying;


#import "GEOAlertNonRecommendedRouteText.h"
#import "GEOClickableAdvisory.h"
#import "GEODrivingWalkingInstruction.h"
#import "GEOWaypointInfo.h"
#import "GEOElevationProfile.h"
#import "GEOFormattedString.h"
#import "GEOLaunchAndGoCardText.h"
#import "GEORouteInformation.h"

@interface GEORoute : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    ? _cellularCoverageOffsets;
    ? _cellularCoverages;
    ? _incidentEndOffsetsInRoutes;
    ? _incidentIndices;
    ? _trafficColorOffsets;
    ? _trafficColors;
    NSMutableArray *_advisoryNotices;
    GEOAlertNonRecommendedRouteText *_alertNonRecommendedRouteText;
    NSData *_arrivalRouteID;
    NSMutableArray *_basicPoints;
    GEOClickableAdvisory *_clickableAdvisory;
    NSData *_departureRouteID;
    GEODrivingWalkingInstruction *_destinationListInstruction;
    GEOWaypointInfo *_destinationWaypointInfo;
    GEOElevationProfile *_elevationProfile;
    NSMutableArray *_endingRouteInstructions;
    NSMutableArray *_enrouteNotices;
    NSMutableArray *_guidanceEvents;
    NSMutableArray *_incidentOnRouteInfos;
    GEOFormattedString *_infrastructureDescription;
    NSMutableArray *_laneWidths;
    GEOLaunchAndGoCardText *_launchAndGoCardText;
    NSString *_name;
    GEODrivingWalkingInstruction *_originListInstruction;
    GEOWaypointInfo *_originWaypointInfo;
    NSData *_pathLeg;
    NSString *_phoneticName;
    NSMutableArray *_restrictedZoneIds;
    NSMutableArray *_roadComplexitys;
    NSData *_routeID;
    NSMutableArray *_routeNames;
    NSMutableArray *_routeCameraInputInfos;
    NSMutableArray *_routeDescriptions;
    GEOFormattedString *_routeLabelDetailText;
    NSMutableArray *_routeLineStyleInfos;
    GEORouteInformation *_routePlanningDescription;
    NSMutableArray *_startingRouteInstructions;
    NSMutableArray *_stepGroups;
    NSMutableArray *_steps;
    NSMutableArray *_trafficColorInfos;
    NSString *_trafficDescriptionLong;
    NSString *_trafficDescription;
    NSData *_unpackedLatLngVertices;
    NSMutableArray *_updateLocations;
    NSMutableArray *_zilchPoints;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _arrivalStepID;
    unsigned int _arrivalParameterIndex;
    unsigned int _departureStepID;
    unsigned int _distance;
    int _drivingSide;
    int _environmentalCongestionZoneImpact;
    unsigned int _expectedTime;
    unsigned int _historicTravelTime;
    int _licensePlateRestrictionImpact;
    int _routeType;
    unsigned int _staticTravelTime;
    int _tollCongestionZoneImpact;
    int _transportType;
    unsigned int _travelTimeAggressiveEstimate;
    unsigned int _travelTimeConservativeEstimate;
    BOOL _avoidsHighways;
    BOOL _avoidsTolls;
    BOOL _avoidsTraffic;
    ? _flags;
}


@property (retain, nonatomic) NSMutableArray *advisoryNotices;
@property (retain, nonatomic) GEOAlertNonRecommendedRouteText *alertNonRecommendedRouteText;
@property (nonatomic) unsigned int arrivalParameterIndex;
@property (retain, nonatomic) NSData *arrivalRouteID;
@property (nonatomic) unsigned int arrivalStepID;
@property (nonatomic) BOOL avoidsHighways;
@property (nonatomic) BOOL avoidsTolls;
@property (nonatomic) BOOL avoidsTraffic;
@property (retain, nonatomic) NSMutableArray *basicPoints;
@property (readonly, nonatomic) *unsigned int cellularCoverageOffsets;
@property (readonly, nonatomic) NSUInteger cellularCoverageOffsetsCount;
@property (readonly, nonatomic) *int cellularCoverages;
@property (readonly, nonatomic) NSUInteger cellularCoveragesCount;
@property (retain, nonatomic) GEOClickableAdvisory *clickableAdvisory;
@property (retain, nonatomic) NSData *departureRouteID;
@property (nonatomic) unsigned int departureStepID;
@property (retain, nonatomic) GEODrivingWalkingInstruction *destinationListInstruction;
@property (retain, nonatomic) GEOWaypointInfo *destinationWaypointInfo;
@property (nonatomic) unsigned int distance;
@property (nonatomic) int drivingSide;
@property (retain, nonatomic) GEOElevationProfile *elevationProfile;
@property (retain, nonatomic) NSMutableArray *endingRouteInstructions;
@property (retain, nonatomic) NSMutableArray *enrouteNotices;
@property (nonatomic) int environmentalCongestionZoneImpact;
@property (nonatomic) unsigned int expectedTime;
@property (retain, nonatomic) NSMutableArray *guidanceEvents;
@property (readonly, nonatomic) BOOL hasAlertNonRecommendedRouteText;
@property (nonatomic) BOOL hasArrivalParameterIndex;
@property (readonly, nonatomic) BOOL hasArrivalRouteID;
@property (nonatomic) BOOL hasArrivalStepID;
@property (nonatomic) BOOL hasAvoidsHighways;
@property (nonatomic) BOOL hasAvoidsTolls;
@property (nonatomic) BOOL hasAvoidsTraffic;
@property (readonly, nonatomic) BOOL hasClickableAdvisory;
@property (readonly, nonatomic) BOOL hasDepartureRouteID;
@property (nonatomic) BOOL hasDepartureStepID;
@property (readonly, nonatomic) BOOL hasDestinationListInstruction;
@property (readonly, nonatomic) BOOL hasDestinationWaypointInfo;
@property (nonatomic) BOOL hasDistance;
@property (nonatomic) BOOL hasDrivingSide;
@property (readonly, nonatomic) BOOL hasElevationProfile;
@property (nonatomic) BOOL hasEnvironmentalCongestionZoneImpact;
@property (nonatomic) BOOL hasExpectedTime;
@property (nonatomic) BOOL hasHistoricTravelTime;
@property (readonly, nonatomic) BOOL hasInfrastructureDescription;
@property (readonly, nonatomic) BOOL hasLaunchAndGoCardText;
@property (nonatomic) BOOL hasLicensePlateRestrictionImpact;
@property (readonly, nonatomic) BOOL hasName;
@property (readonly, nonatomic) BOOL hasOriginListInstruction;
@property (readonly, nonatomic) BOOL hasOriginWaypointInfo;
@property (readonly, nonatomic) BOOL hasPathLeg;
@property (readonly, nonatomic) BOOL hasPhoneticName;
@property (readonly, nonatomic) BOOL hasRouteID;
@property (readonly, nonatomic) BOOL hasRouteLabelDetailText;
@property (readonly, nonatomic) BOOL hasRoutePlanningDescription;
@property (nonatomic) BOOL hasRouteType;
@property (nonatomic) BOOL hasStaticTravelTime;
@property (nonatomic) BOOL hasTollCongestionZoneImpact;
@property (readonly, nonatomic) BOOL hasTrafficDescription;
@property (readonly, nonatomic) BOOL hasTrafficDescriptionLong;
@property (nonatomic) BOOL hasTransportType;
@property (nonatomic) BOOL hasTravelTimeAggressiveEstimate;
@property (nonatomic) BOOL hasTravelTimeConservativeEstimate;
@property (readonly, nonatomic) BOOL hasUnpackedLatLngVertices;
@property (nonatomic) unsigned int historicTravelTime;
@property (readonly, nonatomic) *unsigned int incidentEndOffsetsInRoutes;
@property (readonly, nonatomic) NSUInteger incidentEndOffsetsInRoutesCount;
@property (readonly, nonatomic) *unsigned int incidentIndices;
@property (readonly, nonatomic) NSUInteger incidentIndicesCount;
@property (retain, nonatomic) NSMutableArray *incidentOnRouteInfos;
@property (retain, nonatomic) GEOFormattedString *infrastructureDescription;
@property (retain, nonatomic) NSMutableArray *laneWidths;
@property (retain, nonatomic) GEOLaunchAndGoCardText *launchAndGoCardText;
@property (nonatomic) int licensePlateRestrictionImpact;
@property (retain, nonatomic) NSString *name;
@property (retain, nonatomic) GEODrivingWalkingInstruction *originListInstruction;
@property (retain, nonatomic) GEOWaypointInfo *originWaypointInfo;
@property (retain, nonatomic) NSData *pathLeg;
@property (retain, nonatomic) NSString *phoneticName;
@property (readonly) unsigned int pointCount;
@property (retain, nonatomic) NSMutableArray *restrictedZoneIds;
@property (retain, nonatomic) NSMutableArray *roadComplexitys;
@property (retain, nonatomic) NSMutableArray *routeCameraInputInfos;
@property (retain, nonatomic) NSMutableArray *routeDescriptions;
@property (retain, nonatomic) NSData *routeID;
@property (retain, nonatomic) GEOFormattedString *routeLabelDetailText;
@property (retain, nonatomic) NSMutableArray *routeLineStyleInfos;
@property (retain, nonatomic) NSMutableArray *routeNames;
@property (retain, nonatomic) GEORouteInformation *routePlanningDescription;
@property (nonatomic) int routeType;
@property (retain, nonatomic) NSMutableArray *startingRouteInstructions;
@property (nonatomic) unsigned int staticTravelTime;
@property (retain, nonatomic) NSMutableArray *stepGroups;
@property (retain, nonatomic) NSMutableArray *steps;
@property (nonatomic) int tollCongestionZoneImpact;
@property (retain, nonatomic) NSMutableArray *trafficColorInfos;
@property (readonly, nonatomic) *unsigned int trafficColorOffsets;
@property (readonly, nonatomic) NSUInteger trafficColorOffsetsCount;
@property (readonly, nonatomic) *unsigned int trafficColors;
@property (readonly, nonatomic) NSUInteger trafficColorsCount;
@property (retain, nonatomic) NSString *trafficDescription;
@property (retain, nonatomic) NSString *trafficDescriptionLong;
@property (nonatomic) int transportType;
@property (nonatomic) unsigned int travelTimeAggressiveEstimate;
@property (nonatomic) unsigned int travelTimeConservativeEstimate;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;
@property (retain, nonatomic) NSData *unpackedLatLngVertices;
@property (retain, nonatomic) NSMutableArray *updateLocations;
@property (retain, nonatomic) NSMutableArray *zilchPoints;


+(BOOL)isValid:(id)arg0 ;
+(Class)advisoryNoticeType;
+(Class)endingRouteInstructionType;
+(Class)enrouteNoticeType;
+(Class)guidanceEventType;
+(Class)incidentOnRouteInfoType;
+(Class)laneWidthType;
+(Class)roadComplexityType;
+(Class)routeCameraInputInfoType;
+(Class)routeDescriptionType;
+(Class)routeLineStyleInfoType;
+(Class)routeNameType;
+(Class)startingRouteInstructionType;
+(Class)stepGroupType;
+(Class)stepType;
+(Class)trafficColorInfoType;
+(Class)updateLocationType;
-(*void)controlPoints;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)isContingentRoute;
-(BOOL)isContingentRouteFor:(id)arg0 afterPoint:(unsigned int)arg1 mainRoutes:(id)arg2 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)isMainOrAlternateRoute;
-(BOOL)readFrom:(id)arg0 ;
-(BOOL)unpackBasicPoints;
-(BOOL)unpackLatLngVertices;
-(BOOL)unpackZilchPoints;
-(CGFloat)distanceFromStepIndex:(NSUInteger)arg0 toStepIndex:(NSUInteger)arg1 ;
-(NSUInteger)hash;
-(NSUInteger)indexForStepID:(NSUInteger)arg0 ;
-(NSUInteger)stepIndexForPointIndex:(unsigned int)arg0 ;
-(id)advisoryNoticeAtIndex:(NSUInteger)arg0 ;
-(id)basicPointsAtIndex:(NSUInteger)arg0 ;
-(id)cellularCoveragesAsString:(int)arg0 ;
-(id)convertToFullRoute:(id)arg0 includeDepartureRoutes:(BOOL)arg1 uniquePointRange:(struct _NSRange *)arg2 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)debugDescription;
-(id)description;
-(id)dictionaryRepresentation;
-(id)drivingSideAsString:(int)arg0 ;
-(id)endingRouteInstructionAtIndex:(NSUInteger)arg0 ;
-(id)enrouteNoticeAtIndex:(NSUInteger)arg0 ;
-(id)environmentalCongestionZoneImpactAsString:(int)arg0 ;
-(id)guidanceEventAtIndex:(NSUInteger)arg0 ;
-(id)incidentOnRouteInfoAtIndex:(NSUInteger)arg0 ;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)laneWidthAtIndex:(NSUInteger)arg0 ;
-(id)licensePlateRestrictionImpactAsString:(int)arg0 ;
-(id)newETARoute;
-(id)newETARouteFromStepIndex:(NSUInteger)arg0 stepPercentRemaining:(CGFloat)arg1 ;
-(id)restrictedZoneIdsAtIndex:(NSUInteger)arg0 ;
-(id)roadComplexityAtIndex:(NSUInteger)arg0 ;
-(id)routeCameraInputInfoAtIndex:(NSUInteger)arg0 ;
-(id)routeDescriptionAtIndex:(NSUInteger)arg0 ;
-(id)routeLineStyleInfoAtIndex:(NSUInteger)arg0 ;
-(id)routeNameAtIndex:(NSUInteger)arg0 ;
-(id)routeTypeAsString:(int)arg0 ;
-(id)simplifiedDescription;
-(id)startingRouteInstructionAtIndex:(NSUInteger)arg0 ;
-(id)stepAtIndex:(NSUInteger)arg0 ;
-(id)stepGroupAtIndex:(NSUInteger)arg0 ;
-(id)tollCongestionZoneImpactAsString:(int)arg0 ;
-(id)trafficColorInfoAtIndex:(NSUInteger)arg0 ;
-(id)transportTypeAsString:(int)arg0 ;
-(id)updateLocationAtIndex:(NSUInteger)arg0 ;
-(id)zilchPointsAtIndex:(NSUInteger)arg0 ;
-(int)StringAsCellularCoverages:(id)arg0 ;
-(int)StringAsDrivingSide:(id)arg0 ;
-(int)StringAsEnvironmentalCongestionZoneImpact:(id)arg0 ;
-(int)StringAsLicensePlateRestrictionImpact:(id)arg0 ;
-(int)StringAsRouteType:(id)arg0 ;
-(int)StringAsTollCongestionZoneImpact:(id)arg0 ;
-(int)StringAsTransportType:(id)arg0 ;
-(int)cellularCoverageAtIndex:(NSUInteger)arg0 ;
-(int)transportTypeForStep:(id)arg0 ;
-(struct ? )coordinateAt:(unsigned int)arg0 ;
-(struct ? )pointAt:(unsigned int)arg0 ;
-(unsigned int)cellularCoverageOffsetAtIndex:(NSUInteger)arg0 ;
-(unsigned int)incidentEndOffsetsInRouteAtIndex:(NSUInteger)arg0 ;
-(unsigned int)incidentIndicesAtIndex:(NSUInteger)arg0 ;
-(unsigned int)trafficColorAtIndex:(NSUInteger)arg0 ;
-(unsigned int)trafficColorOffsetAtIndex:(NSUInteger)arg0 ;
-(void)addAdvisoryNotice:(id)arg0 ;
-(void)addBasicPoints:(id)arg0 ;
-(void)addCellularCoverage:(int)arg0 ;
-(void)addCellularCoverageOffset:(unsigned int)arg0 ;
-(void)addEndingRouteInstruction:(id)arg0 ;
-(void)addEnrouteNotice:(id)arg0 ;
-(void)addGuidanceEvent:(id)arg0 ;
-(void)addIncidentEndOffsetsInRoute:(unsigned int)arg0 ;
-(void)addIncidentIndices:(unsigned int)arg0 ;
-(void)addIncidentOnRouteInfo:(id)arg0 ;
-(void)addLaneWidth:(id)arg0 ;
-(void)addRestrictedZoneIds:(id)arg0 ;
-(void)addRoadComplexity:(id)arg0 ;
-(void)addRouteCameraInputInfo:(id)arg0 ;
-(void)addRouteDescription:(id)arg0 ;
-(void)addRouteLineStyleInfo:(id)arg0 ;
-(void)addRouteName:(id)arg0 ;
-(void)addStartingRouteInstruction:(id)arg0 ;
-(void)addStep:(id)arg0 ;
-(void)addStepGroup:(id)arg0 ;
-(void)addTrafficColor:(unsigned int)arg0 ;
-(void)addTrafficColorInfo:(id)arg0 ;
-(void)addTrafficColorOffset:(unsigned int)arg0 ;
-(void)addUpdateLocation:(id)arg0 ;
-(void)addZilchPoints:(id)arg0 ;
-(void)clearAdvisoryNotices;
-(void)clearBasicPoints;
-(void)clearCellularCoverageOffsets;
-(void)clearCellularCoverages;
-(void)clearEndingRouteInstructions;
-(void)clearEnrouteNotices;
-(void)clearGuidanceEvents;
-(void)clearIncidentEndOffsetsInRoutes;
-(void)clearIncidentIndices;
-(void)clearIncidentOnRouteInfos;
-(void)clearLaneWidths;
-(void)clearRestrictedZoneIds;
-(void)clearRoadComplexitys;
-(void)clearRouteCameraInputInfos;
-(void)clearRouteDescriptions;
-(void)clearRouteLineStyleInfos;
-(void)clearRouteNames;
-(void)clearStartingRouteInstructions;
-(void)clearStepGroups;
-(void)clearSteps;
-(void)clearTrafficColorInfos;
-(void)clearTrafficColorOffsets;
-(void)clearTrafficColors;
-(void)clearUnknownFields:(BOOL)arg0 ;
-(void)clearUpdateLocations;
-(void)clearZilchPoints;
-(void)copyTo:(id)arg0 ;
-(void)dealloc;
-(void)mergeFrom:(id)arg0 ;
-(void)readAll:(BOOL)arg0 ;
-(void)writeTo:(id)arg0 ;


@end


#endif