// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef CSSEARCHABLEITEMATTRIBUTESET_H
#define CSSEARCHABLEITEMATTRIBUTESET_H

@class NSString, NSData, NSArray, NSNumber, NSDictionary, NSMutableDictionary, NSDate;
@protocol NSCopying, NSSecureCoding;

#import <Foundation/Foundation.h>

#import "CSDecoder.h"
#import "CSDonatedEvent.h"
#import "CSPerson.h"

@interface CSSearchableItemAttributeSet : NSObject <NSCopying, NSSecureCoding>



@property (copy) NSString *FPFilename;
@property (readonly) NSData *HTMLContentDataNoCopy;
@property (copy) NSArray *LPMediaPaths;
@property (copy) NSString *accountType;
@property (copy) NSString *adamID;
@property (retain) NSNumber *aestheticScore;
@property (copy) NSString *albumPersistentID;
@property (copy) NSString *applicationName;
@property (readonly) NSDictionary *attributes; // ivar: _attributes
@property (retain) NSArray *authorPhotosPersonIdentifiers;
@property (copy) NSArray *autocompleteTriggers;
@property (retain) NSNumber *backgroundRunnable;
@property (copy) NSString *bundleID;
@property (readonly, nonatomic) ? codedAttributes; // ivar: _codedAttributes
@property (readonly, nonatomic) ? codedCustomAttributes; // ivar: _codedCustomAttributes
@property (retain) NSString *collaborationIdentifier;
@property (readonly) NSNumber *contentCreationDateHour;
@property (readonly) NSNumber *contentCreationDateMonth;
@property (readonly) NSNumber *contentCreationDateWeekOfMonth;
@property (readonly) NSNumber *contentCreationDateWeekOfYear;
@property (readonly) NSNumber *contentCreationDateWeekday;
@property (readonly) NSNumber *contentCreationDateWeekdayOrdinal;
@property (readonly) NSNumber *contentCreationDateYear;
@property (readonly, nonatomic) CSDecoder *contentDecoder; // ivar: _contentDecoder
@property (readonly) NSNumber *contentModificationDateHour;
@property (readonly) NSNumber *contentModificationDateMonth;
@property (readonly) NSNumber *contentModificationDateWeekOfMonth;
@property (readonly) NSNumber *contentModificationDateWeekOfYear;
@property (readonly) NSNumber *contentModificationDateWeekday;
@property (readonly) NSNumber *contentModificationDateWeekdayOrdinal;
@property (readonly) NSNumber *contentModificationDateYear;
@property (readonly, nonatomic) ? contentObj; // ivar: _contentObj
@property (readonly) NSString *contentSnippet;
@property (retain) NSNumber *curationScore;
@property (readonly) NSMutableDictionary *customAttributes; // ivar: _customAttributes
@property (retain) NSNumber *dataOwnerType;
@property (readonly, nonatomic) CSDecoder *decoder; // ivar: _decoder
@property (retain) NSNumber *deletedWithRelatedUniqueIdentifier;
@property (retain) NSNumber *documentIdentifier;
@property (retain, nonatomic) CSDonatedEvent *donatedEvent;
@property (retain) NSNumber *downloadError;
@property (retain, nonatomic, getter=isDownloading) NSNumber *downloading;
@property (copy) NSString *downloadingStatus;
@property (retain) NSNumber *eligibleForPhotosProcessing;
@property (retain, getter=isExistingThread) NSNumber *existingThread;
@property (retain) NSDate *expirationDate;
@property (retain) NSNumber *extendedContentRating;
@property (copy) NSData *extraData;
@property (retain) NSNumber *favoriteRank;
@property (retain) NSNumber *fileIdentifier;
@property (copy) NSString *fileItemID;
@property (copy) NSString *fileProviderDomainIdentifier;
@property (copy) NSString *fileProviderDomaindentifier;
@property (copy) NSString *fileProviderID;
@property (copy) NSArray *fileProviderUserInfoKeys;
@property (copy) NSArray *fileProviderUserInfoValues;
@property (copy) NSString *filename;
@property (copy) NSString *groupPhotoPath;
@property (readonly, nonatomic) BOOL hasCodedCustomAttributes; // ivar: _hasCodedCustomAttributes
@property (readonly, nonatomic) BOOL hasKnownKeysDictionary; // ivar: _hasKnownKeysDictionary
@property (copy) NSNumber *hasLPMedia;
@property (retain) NSNumber *hasTopMomentScore;
@property (copy) NSArray *hashtags;
@property (retain) NSString *importSandboxExtension;
@property (copy) NSData *intentData;
@property (retain) NSNumber *isCinematicVideo;
@property (retain) NSNumber *isPlaceholder;
@property (retain) NSNumber *isProResVideo;
@property (retain) NSNumber *isZombie;
@property (copy) NSDate *lastApplicationLaunchedDate;
@property (copy) NSString *lastEditorIdentifier;
@property (copy) NSString *lastEditorName;
@property (retain) NSNumber *lastMotionActivityState;
@property (copy) NSArray *mailAttachmentKinds;
@property (copy) NSArray *mailAttachmentNames;
@property (copy) NSArray *mailAttachmentTypes;
@property (copy) NSString *mailCategory;
@property (copy) NSString *mailConversationID;
@property (retain) NSDate *mailDateLastViewed;
@property (retain) NSDate *mailDateReceived;
@property (retain) NSNumber *mailFlagColor;
@property (retain) NSNumber *mailFlagged;
@property (copy) NSArray *mailGMailLabels;
@property (copy) NSString *mailMessageID;
@property (retain) NSNumber *mailPriority;
@property (retain) NSNumber *mailRead;
@property (retain) NSNumber *mailRepliedTo;
@property (retain) NSArray *matchingHints; // ivar: _matchingHints
@property (retain) NSString *messageSuggestedContactName;
@property (retain) NSString *messageSuggestedContactPhotoPath;
@property (readonly) NSMutableDictionary *mutableAttributes; // ivar: _mutableAttributes
@property (copy) NSString *ownerIdentifier;
@property (copy) NSString *ownerName;
@property (retain) NSNumber *parentFileIdentifier;
@property (copy) NSString *parentFileItemID;
@property (retain, getter=isPartiallyDownloaded) NSNumber *partiallyDownloaded;
@property (copy) NSString *photosAcquisitionMake;
@property (copy) NSString *photosAcquisitionModel;
@property (retain) NSNumber *photosAestheticScore;
@property (retain) NSArray *photosBusinessCategories;
@property (retain) NSArray *photosBusinessNames;
@property (retain, nonatomic) NSNumber *photosCharacterRecognitionAnalysisVersion;
@property (retain) NSString *photosCollectionKeyAssetUUID;
@property (retain) NSNumber *photosCollectionResultCount;
@property (retain) NSString *photosCollectionSubtitle;
@property (copy) NSString *photosContainerIdentifier;
@property (retain) NSDate *photosContentCreationDate;
@property (copy) NSString *photosContentDescription;
@property (retain) NSNumber *photosContentRating;
@property (copy) NSString *photosContentType;
@property (retain) CSPerson *photosContributor;
@property (retain) NSNumber *photosCurationScore;
@property (copy) NSString *photosDisplayName;
@property (retain, nonatomic) NSNumber *photosDonationState;
@property (retain) NSNumber *photosDuration;
@property (retain) NSArray *photosEventCategories;
@property (retain) NSArray *photosEventNames;
@property (retain) NSArray *photosEventPerformers;
@property (retain, nonatomic) NSNumber *photosFaceAnalysisVersion;
@property (retain) NSNumber *photosFavorited;
@property (copy) NSString *photosFilename;
@property (retain) NSNumber *photosHasTopMomentScore;
@property (retain) NSArray *photosHolidays;
@property (retain, nonatomic) NSNumber *photosInferredTimeZoneOffset;
@property (retain) NSNumber *photosIsCinematicVideo;
@property (retain) NSNumber *photosIsProResVideo;
@property (retain) NSArray *photosKeywords;
@property (retain) NSString *photosLibraryName;
@property (retain) NSArray *photosMeanings;
@property (retain, nonatomic) NSNumber *photosMediaAnalysisVersion;
@property (retain) NSArray *photosMediaTypes;
@property (retain) NSString *photosMemoryTitle;
@property (retain) NSArray *photosPeople;
@property (retain) NSString *photosResultType;
@property (retain) NSString *photosSavingApplication;
@property (retain) NSString *photosSavingApplicationBundleIdentifier;
@property (retain, nonatomic) NSNumber *photosSceneAnalysisVersion;
@property (copy) NSArray *photosSceneClassifications;
@property (retain) NSArray *photosSceneIdentifiers;
@property (retain) NSArray *photosScenes;
@property (retain) NSArray *photosSeasons;
@property (retain) NSArray *photosTextContentPieces;
@property (copy, nonatomic) NSString *photosTimeZoneName;
@property (retain, nonatomic) NSNumber *photosTimeZoneOffset;
@property (copy) NSString *photosTitle;
@property (retain, nonatomic, getter=isPinned) NSNumber *pinned;
@property (retain) NSData *portraitFeatureVector;
@property (retain) NSNumber *portraitFeatureVectorVersion;
@property (retain) NSDictionary *portraitNamedEntities;
@property (retain) NSNumber *portraitStaticScore;
@property (retain, nonatomic, getter=isPotentialEventMessage) NSNumber *potentialEventMessage;
@property (copy) NSString *protectionClass;
@property (copy) NSString *punchoutLabel;
@property (readonly) NSArray *queryResultMatchedFields;
@property (copy) NSString *queryResultRelevance;
@property (retain, nonatomic, getter=isReaderView) NSNumber *readerView;
@property (retain) NSArray *recipientPhotosPersonIdentifiers;
@property (copy) NSString *relatedAppBundleIdentifier;
@property (retain) NSNumber *requiresImport;
@property (copy) NSString *richLinkID;
@property (copy) NSString *richLinkTitle;
@property (copy) NSString *richLinkURL;
@property (retain) NSString *savingApplication;
@property (retain) NSString *savingApplicationBundleIdentifier;
@property NSInteger searchableItemFlags; // ivar: _searchableItemFlags
@property (retain, nonatomic, getter=isShared) NSNumber *shared;
@property (copy) NSString *sharedItemCurrentUserRole;
@property (retain) NSNumber *shortcutAvailability;
@property (retain) NSNumber *subItemCount;
@property (copy) NSString *subtitle;
@property (copy) NSString *suggestedInvocationPhrase;
@property (copy) NSDate *syndicatedContentServerDate;
@property (copy) NSNumber *syndicationStatus;
@property (copy) NSString *textContentDataSource;
@property (readonly) NSString *textContentNoCopy;
@property (copy) NSString *textSelected;
@property (copy) NSString *thumbnailBundleID;
@property (copy) NSString *thumbnailContentType;
@property (copy) NSArray *topic;
@property (retain, nonatomic, getter=isTrashed) NSNumber *trashed;
@property (copy) NSString *uniqueIdentifier;
@property (retain) NSNumber *uploadError;
@property (retain, nonatomic, getter=isUploaded) NSNumber *uploaded;
@property (retain, nonatomic, getter=isUploading) NSNumber *uploading;
@property (copy) NSString *userActivityType;
@property (copy) NSArray *userTags;
@property (copy) NSString *versionIdentifier;
@property (retain) NSNumber *visualAssetPriority;


+(BOOL)supportsSecureCoding;
+(id)_allKeys;
+(id)_requiredAttributesForContentType:(id)arg0 ;
+(id)_sharedAttributeKeySet;
-(BOOL)attributeIsDelete:(id)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)isValidAttributeSet;
-(NSUInteger)hash;
-(id)EXIFGPSVersion;
-(id)EXIFVersion;
-(id)GPSAreaInformation;
-(id)GPSDOP;
-(id)GPSDateStamp;
-(id)GPSDestBearing;
-(id)GPSDestDistance;
-(id)GPSDestLatitude;
-(id)GPSDestLongitude;
-(id)GPSDifferental;
-(id)GPSMapDatum;
-(id)GPSMeasureMode;
-(id)GPSProcessingMethod;
-(id)GPSStatus;
-(id)GPSTrack;
-(id)HTMLContentData;
-(id)ISOSpeed;
-(id)URL;
-(id)_getNonNullValueForKey:(id)arg0 ;
-(id)accountHandles;
-(id)accountIdentifier;
-(id)acquisitionMake;
-(id)acquisitionModel;
-(id)actionIdentifiers;
-(id)addedDate;
-(id)additionalRecipients;
-(id)album;
-(id)allDay;
-(id)alternateNames;
-(id)altitude;
-(id)aperture;
-(id)appleLoopDescriptors;
-(id)appleLoopsKeyFilterType;
-(id)appleLoopsLoopMode;
-(id)appleLoopsRootKey;
-(id)applicationCategories;
-(id)artist;
-(id)attachmentNames;
-(id)attachmentPaths;
-(id)attachmentTypes;
-(id)attributeDictionary;
-(id)attributeForKey:(id)arg0 ;
-(id)audiences;
-(id)audioBitRate;
-(id)audioChannelCount;
-(id)audioEncodingApplication;
-(id)audioSampleRate;
-(id)audioTrackNumber;
-(id)authorAddresses;
-(id)authorEmailAddresses;
-(id)authorNames;
-(id)authors;
-(id)bitsPerSample;
-(id)bundleIdentifier;
-(id)calendarDelegateIdentifier;
-(id)calendarHolidayIdentifier;
-(id)cameraOwner;
-(id)city;
-(id)codecs;
-(id)colorSpace;
-(id)comment;
-(id)completionDate;
-(id)composer;
-(id)contactKeywords;
-(id)containerDisplayName;
-(id)containerIdentifier;
-(id)containerOrder;
-(id)containerTitle;
-(id)contentCreationDate;
-(id)contentDescription;
-(id)contentModificationDate;
-(id)contentRating;
-(id)contentSources;
-(id)contentType;
-(id)contentTypeTree;
-(id)contentURL;
-(id)contributors;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)copyright;
-(id)country;
-(id)coverage;
-(id)creator;
-(id)customAttributeDictionary;
-(id)darkThumbnailURL;
-(id)debugDescription;
-(id)deliveryType;
-(id)description;
-(id)director;
-(id)displayName;
-(id)domainIdentifier;
-(id)downloadedDate;
-(id)dueDate;
-(id)duration;
-(id)editors;
-(id)emailAddresses;
-(id)emailHeaders;
-(id)encodingApplications;
-(id)endDate;
-(id)executableArchitectures;
-(id)executablePlatform;
-(id)exposureMode;
-(id)exposureProgram;
-(id)exposureTime;
-(id)exposureTimeString;
-(id)fNumber;
-(id)fileSize;
-(id)finderComment;
-(id)focalLength;
-(id)fontNames;
-(id)fullyFormattedAddress;
-(id)genre;
-(id)hasAlphaChannel;
-(id)headline;
-(id)hiddenAdditionalRecipients;
-(id)identifier;
-(id)imageDirection;
-(id)importantDates;
-(id)information;
-(id)init;
-(id)initWithAttributeSet:(id)arg0 ;
-(id)initWithAttributes:(id)arg0 ;
-(id)initWithCoder:(id)arg0 ;
-(id)initWithContentType:(id)arg0 ;
-(id)initWithDecoder:(id)arg0 obj:(struct ? )arg1 ;
-(id)initWithItemContentType:(id)arg0 ;
-(id)initWithKnownKeysDictionary:(id)arg0 ;
-(id)initWithMutableDictionary:(id)arg0 ;
-(id)initWithSerializedAttributes:(id)arg0 ;
-(id)instantAnswers;
-(id)instantMessageAddresses;
-(id)instructions;
-(id)isApplicationManaged;
-(id)isFlashOn;
-(id)isFocalLength35mm;
-(id)isGeneralMIDISequence;
-(id)isLikelyJunk;
-(id)isLocal;
-(id)isRedEyeOn;
-(id)isStreamable;
-(id)isUserCreated;
-(id)isUserCurated;
-(id)isUserOwned;
-(id)keySignature;
-(id)keywords;
-(id)kind;
-(id)languages;
-(id)lastUsedDate;
-(id)latitude;
-(id)layerNames;
-(id)lensModel;
-(id)longitude;
-(id)lyricist;
-(id)mailboxIdentifiers;
-(id)maxAperture;
-(id)mediaTypes;
-(id)metadataModificationDate;
-(id)meteringMode;
-(id)musicalGenre;
-(id)musicalInstrumentCategory;
-(id)musicalInstrumentName;
-(id)namedLocation;
-(id)organizations;
-(id)orientation;
-(id)originalFormat;
-(id)originalSource;
-(id)pageCount;
-(id)pageHeight;
-(id)pageWidth;
-(id)participants;
-(id)path;
-(id)performers;
-(id)phoneNumbers;
-(id)pixelCount;
-(id)pixelHeight;
-(id)pixelWidth;
-(id)playCount;
-(id)postalCode;
-(id)primaryRecipients;
-(id)producer;
-(id)profileName;
-(id)projects;
-(id)providerDataTypeIdentifiers;
-(id)providerDataTypes;
-(id)providerFileTypeIdentifiers;
-(id)providerFileTypes;
-(id)providerInPlaceFileTypeIdentifiers;
-(id)publishers;
-(id)rankingHint;
-(id)rating;
-(id)ratingDescription;
-(id)recipientAddresses;
-(id)recipientEmailAddresses;
-(id)recipientNames;
-(id)recordingDate;
-(id)relatedUniqueIdentifier;
-(id)requiredAttributes;
-(id)resolutionHeightDPI;
-(id)resolutionWidthDPI;
-(id)rights;
-(id)role;
-(id)securityMethod;
-(id)serializedAttributes;
-(id)sharedItemContentType;
-(id)speed;
-(id)startDate;
-(id)stateOrProvince;
-(id)subThoroughfare;
-(id)subject;
-(id)supportFileType;
-(id)supportsNavigation;
-(id)supportsPhoneCall;
-(id)tempo;
-(id)textContent;
-(id)textContentPieces;
-(id)theme;
-(id)thoroughfare;
-(id)thumbnailData;
-(id)thumbnailURL;
-(id)timeSignature;
-(id)timestamp;
-(id)title;
-(id)totalBitRate;
-(id)userCreatedDate;
-(id)userCreatedUserHandle;
-(id)userDownloadedDate;
-(id)userDownloadedUserHandle;
-(id)userModifiedDate;
-(id)userModifiedUserHandle;
-(id)userPrintedDate;
-(id)userPrintedUserHandle;
-(id)userSharedReceivedDate;
-(id)userSharedReceivedRecipient;
-(id)userSharedReceivedRecipientHandle;
-(id)userSharedReceivedSender;
-(id)userSharedReceivedSenderHandle;
-(id)userSharedReceivedTransport;
-(id)userSharedSentDate;
-(id)userSharedSentRecipient;
-(id)userSharedSentRecipientHandle;
-(id)userSharedSentSender;
-(id)userSharedSentSenderHandle;
-(id)userSharedSentTransport;
-(id)valueForCustomKey:(id)arg0 ;
-(id)vendorName;
-(id)version;
-(id)videoBitRate;
-(id)weakRelatedUniqueIdentifier;
-(id)whiteBalance;
-(void)_markAs:(id)arg0 userHandle:(id)arg1 dateKey:(id)arg2 userHandleKey:(id)arg3 ;
-(void)_markAs:(int)arg0 date:(id)arg1 sender:(id)arg2 senderHandle:(id)arg3 recipients:(id)arg4 recipientHandles:(id)arg5 transport:(id)arg6 ;
-(void)_setArrayValue:(id)arg0 withItemClass:(Class)arg1 forKey:(id)arg2 ;
-(void)_setDataValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setDateValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setDictionaryValue:(id)arg0 withValueClass:(Class)arg1 keyClass:(Class)arg2 forKey:(id)arg3 ;
-(void)_setNumberValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setStringValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setURLValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setValue:(id)arg0 withClass:(Class)arg1 forKey:(id)arg2 ;
-(void)_setValue:(id)arg0 withClass:(Class)arg1 forKey:(id)arg2 copy:(BOOL)arg3 ;
-(void)_standardizeMarkAs;
-(void)addAttributesFromAttributeSet:(id)arg0 ;
-(void)addAttributesFromDictionary:(id)arg0 ;
-(void)encodeWithCSCoder:(id)arg0 ;
-(void)encodeWithCSCoder:(id)arg0 includeText:(BOOL)arg1 ;
-(void)encodeWithCoder:(id)arg0 ;
-(void)incrementAttributeValue:(id)arg0 forKey:(id)arg1 ;
-(void)markAsCreated:(id)arg0 userHandle:(id)arg1 ;
-(void)markAsDownloaded:(id)arg0 userHandle:(id)arg1 ;
-(void)markAsModified:(id)arg0 userHandle:(id)arg1 ;
-(void)markAsPrinted:(id)arg0 userHandle:(id)arg1 ;
-(void)markAsReceived:(id)arg0 sender:(id)arg1 senderHandle:(id)arg2 recipients:(id)arg3 recipientHandles:(id)arg4 transport:(id)arg5 ;
-(void)markAsSent:(id)arg0 sender:(id)arg1 senderHandle:(id)arg2 recipients:(id)arg3 recipientHandles:(id)arg4 transport:(id)arg5 ;
-(void)setAccountHandles:(id)arg0 ;
-(void)setAccountIdentifier:(id)arg0 ;
-(void)setAcquisitionMake:(id)arg0 ;
-(void)setAcquisitionModel:(id)arg0 ;
-(void)setActionIdentifiers:(id)arg0 ;
-(void)setAddedDate:(id)arg0 ;
-(void)setAdditionalRecipients:(id)arg0 ;
-(void)setAlbum:(id)arg0 ;
-(void)setAllDay:(id)arg0 ;
-(void)setAlternateNames:(id)arg0 ;
-(void)setAltitude:(id)arg0 ;
-(void)setAperture:(id)arg0 ;
-(void)setAppleLoopDescriptors:(id)arg0 ;
-(void)setAppleLoopsKeyFilterType:(id)arg0 ;
-(void)setAppleLoopsLoopMode:(id)arg0 ;
-(void)setAppleLoopsRootKey:(id)arg0 ;
-(void)setApplicationCategories:(id)arg0 ;
-(void)setApplicationManaged:(id)arg0 ;
-(void)setArtist:(id)arg0 ;
-(void)setAttachmentNames:(id)arg0 ;
-(void)setAttachmentPaths:(id)arg0 ;
-(void)setAttachmentTypes:(id)arg0 ;
-(void)setAttribute:(id)arg0 forKey:(id)arg1 ;
-(void)setAudiences:(id)arg0 ;
-(void)setAudioBitRate:(id)arg0 ;
-(void)setAudioChannelCount:(id)arg0 ;
-(void)setAudioEncodingApplication:(id)arg0 ;
-(void)setAudioSampleRate:(id)arg0 ;
-(void)setAudioTrackNumber:(id)arg0 ;
-(void)setAuthorAddresses:(id)arg0 ;
-(void)setAuthorEmailAddresses:(id)arg0 ;
-(void)setAuthorNames:(id)arg0 ;
-(void)setAuthors:(id)arg0 ;
-(void)setBitsPerSample:(id)arg0 ;
-(void)setBundleIdentifier:(id)arg0 ;
-(void)setCalendarDelegateIdentifier:(id)arg0 ;
-(void)setCalendarHolidayIdentifier:(id)arg0 ;
-(void)setCameraOwner:(id)arg0 ;
-(void)setCity:(id)arg0 ;
-(void)setCodecs:(id)arg0 ;
-(void)setColorSpace:(id)arg0 ;
-(void)setComment:(id)arg0 ;
-(void)setCompletionDate:(id)arg0 ;
-(void)setComposer:(id)arg0 ;
-(void)setContactKeywords:(id)arg0 ;
-(void)setContainerDisplayName:(id)arg0 ;
-(void)setContainerIdentifier:(id)arg0 ;
-(void)setContainerOrder:(id)arg0 ;
-(void)setContainerTitle:(id)arg0 ;
-(void)setContentCreationDate:(id)arg0 ;
-(void)setContentDescription:(id)arg0 ;
-(void)setContentModificationDate:(id)arg0 ;
-(void)setContentRating:(id)arg0 ;
-(void)setContentSources:(id)arg0 ;
-(void)setContentType:(id)arg0 ;
-(void)setContentTypeTree:(id)arg0 ;
-(void)setContentURL:(id)arg0 ;
-(void)setContributors:(id)arg0 ;
-(void)setCopyright:(id)arg0 ;
-(void)setCountry:(id)arg0 ;
-(void)setCoverage:(id)arg0 ;
-(void)setCreator:(id)arg0 ;
-(void)setDarkThumbnailURL:(id)arg0 ;
-(void)setDeliveryType:(id)arg0 ;
-(void)setDirector:(id)arg0 ;
-(void)setDisplayName:(id)arg0 ;
-(void)setDomainIdentifier:(id)arg0 ;
-(void)setDownloadedDate:(id)arg0 ;
-(void)setDueDate:(id)arg0 ;
-(void)setDuration:(id)arg0 ;
-(void)setEXIFGPSVersion:(id)arg0 ;
-(void)setEXIFVersion:(id)arg0 ;
-(void)setEditors:(id)arg0 ;
-(void)setEmailAddresses:(id)arg0 ;
-(void)setEmailHeaders:(id)arg0 ;
-(void)setEncodingApplications:(id)arg0 ;
-(void)setEndDate:(id)arg0 ;
-(void)setExecutableArchitectures:(id)arg0 ;
-(void)setExecutablePlatform:(id)arg0 ;
-(void)setExposureMode:(id)arg0 ;
-(void)setExposureProgram:(id)arg0 ;
-(void)setExposureTime:(id)arg0 ;
-(void)setExposureTimeString:(id)arg0 ;
-(void)setFNumber:(id)arg0 ;
-(void)setFileSize:(id)arg0 ;
-(void)setFinderComment:(id)arg0 ;
-(void)setFlashOn:(id)arg0 ;
-(void)setFocalLength35mm:(id)arg0 ;
-(void)setFocalLength:(id)arg0 ;
-(void)setFontNames:(id)arg0 ;
-(void)setFullyFormattedAddress:(id)arg0 ;
-(void)setGPSAreaInformation:(id)arg0 ;
-(void)setGPSDOP:(id)arg0 ;
-(void)setGPSDateStamp:(id)arg0 ;
-(void)setGPSDestBearing:(id)arg0 ;
-(void)setGPSDestDistance:(id)arg0 ;
-(void)setGPSDestLatitude:(id)arg0 ;
-(void)setGPSDestLongitude:(id)arg0 ;
-(void)setGPSDifferental:(id)arg0 ;
-(void)setGPSMapDatum:(id)arg0 ;
-(void)setGPSMeasureMode:(id)arg0 ;
-(void)setGPSProcessingMethod:(id)arg0 ;
-(void)setGPSStatus:(id)arg0 ;
-(void)setGPSTrack:(id)arg0 ;
-(void)setGeneralMIDISequence:(id)arg0 ;
-(void)setGenre:(id)arg0 ;
-(void)setHTMLContentData:(id)arg0 ;
-(void)setHasAlphaChannel:(id)arg0 ;
-(void)setHeadline:(id)arg0 ;
-(void)setHiddenAdditionalRecipients:(id)arg0 ;
-(void)setISOSpeed:(id)arg0 ;
-(void)setIdentifier:(id)arg0 ;
-(void)setImageDirection:(id)arg0 ;
-(void)setImportantDates:(id)arg0 ;
-(void)setInformation:(id)arg0 ;
-(void)setInstantAnswers:(id)arg0 ;
-(void)setInstantMessageAddresses:(id)arg0 ;
-(void)setInstructions:(id)arg0 ;
-(void)setKeySignature:(id)arg0 ;
-(void)setKeywords:(id)arg0 ;
-(void)setKind:(id)arg0 ;
-(void)setLanguages:(id)arg0 ;
-(void)setLastUsedDate:(id)arg0 ;
-(void)setLatitude:(id)arg0 ;
-(void)setLayerNames:(id)arg0 ;
-(void)setLensModel:(id)arg0 ;
-(void)setLikelyJunk:(id)arg0 ;
-(void)setLocal:(id)arg0 ;
-(void)setLongitude:(id)arg0 ;
-(void)setLyricist:(id)arg0 ;
-(void)setMailboxIdentifiers:(id)arg0 ;
-(void)setMaxAperture:(id)arg0 ;
-(void)setMediaTypes:(id)arg0 ;
-(void)setMetadataModificationDate:(id)arg0 ;
-(void)setMeteringMode:(id)arg0 ;
-(void)setMusicalGenre:(id)arg0 ;
-(void)setMusicalInstrumentCategory:(id)arg0 ;
-(void)setMusicalInstrumentName:(id)arg0 ;
-(void)setNamedLocation:(id)arg0 ;
-(void)setOrganizations:(id)arg0 ;
-(void)setOrientation:(id)arg0 ;
-(void)setOriginalFormat:(id)arg0 ;
-(void)setOriginalSource:(id)arg0 ;
-(void)setPageCount:(id)arg0 ;
-(void)setPageHeight:(id)arg0 ;
-(void)setPageWidth:(id)arg0 ;
-(void)setParticipants:(id)arg0 ;
-(void)setPath:(id)arg0 ;
-(void)setPerformers:(id)arg0 ;
-(void)setPhoneNumbers:(id)arg0 ;
-(void)setPixelCount:(id)arg0 ;
-(void)setPixelHeight:(id)arg0 ;
-(void)setPixelWidth:(id)arg0 ;
-(void)setPlayCount:(id)arg0 ;
-(void)setPostalCode:(id)arg0 ;
-(void)setPrimaryRecipients:(id)arg0 ;
-(void)setProducer:(id)arg0 ;
-(void)setProfileName:(id)arg0 ;
-(void)setProjects:(id)arg0 ;
-(void)setProviderDataTypeIdentifiers:(id)arg0 ;
-(void)setProviderDataTypes:(id)arg0 ;
-(void)setProviderFileTypeIdentifiers:(id)arg0 ;
-(void)setProviderFileTypes:(id)arg0 ;
-(void)setProviderInPlaceFileTypeIdentifiers:(id)arg0 ;
-(void)setPublishers:(id)arg0 ;
-(void)setRankingHint:(id)arg0 ;
-(void)setRating:(id)arg0 ;
-(void)setRatingDescription:(id)arg0 ;
-(void)setRecipientAddresses:(id)arg0 ;
-(void)setRecipientEmailAddresses:(id)arg0 ;
-(void)setRecipientNames:(id)arg0 ;
-(void)setRecordingDate:(id)arg0 ;
-(void)setRedEyeOn:(id)arg0 ;
-(void)setRelatedUniqueIdentifier:(id)arg0 ;
-(void)setResolutionHeightDPI:(id)arg0 ;
-(void)setResolutionWidthDPI:(id)arg0 ;
-(void)setRights:(id)arg0 ;
-(void)setRole:(id)arg0 ;
-(void)setSecurityMethod:(id)arg0 ;
-(void)setSpeed:(id)arg0 ;
-(void)setStartDate:(id)arg0 ;
-(void)setStateOrProvince:(id)arg0 ;
-(void)setStreamable:(id)arg0 ;
-(void)setSubThoroughfare:(id)arg0 ;
-(void)setSubject:(id)arg0 ;
-(void)setSupportFileType:(id)arg0 ;
-(void)setSupportsNavigation:(id)arg0 ;
-(void)setSupportsPhoneCall:(id)arg0 ;
-(void)setTempo:(id)arg0 ;
-(void)setTextContent:(id)arg0 ;
-(void)setTextContentPieces:(id)arg0 ;
-(void)setTheme:(id)arg0 ;
-(void)setThoroughfare:(id)arg0 ;
-(void)setThumbnailData:(id)arg0 ;
-(void)setThumbnailURL:(id)arg0 ;
-(void)setTimeSignature:(id)arg0 ;
-(void)setTimestamp:(id)arg0 ;
-(void)setTitle:(id)arg0 ;
-(void)setTotalBitRate:(id)arg0 ;
-(void)setURL:(id)arg0 ;
-(void)setUserCreated:(id)arg0 ;
-(void)setUserCurated:(id)arg0 ;
-(void)setUserOwned:(id)arg0 ;
-(void)setValue:(id)arg0 forCustomKey:(id)arg1 ;
-(void)setVendorName:(id)arg0 ;
-(void)setVersion:(id)arg0 ;
-(void)setVideoBitRate:(id)arg0 ;
-(void)setWeakRelatedUniqueIdentifier:(id)arg0 ;
-(void)setWhiteBalance:(id)arg0 ;


@end


#endif