// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef WEBBOOKMARKCOLLECTION_H
#define WEBBOOKMARKCOLLECTION_H

@class NSString, NSNumber, NSArray;
@protocol WBDatabaseLockAcquisitorDelegate, WBBookmarkProvider;

#import <Foundation/Foundation.h>

#import "WebBookmarkTitleWordTokenizer.h"
#import "WebBookmark.h"
#import "SafariFetcherServerProxy.h"
#import "WBDatabaseLockAcquisitor.h"
#import "WebBookmarkList.h"
#import "WBCollectionConfiguration.h"

@interface WebBookmarkCollection : NSObject <WBDatabaseLockAcquisitorDelegate, WBBookmarkProvider>

 {
    *sqlite3 _db;
    *__CFLocale _locale;
    WebBookmarkTitleWordTokenizer *_wordTokenizer;
    WebBookmark *_rootBookmark;
    int _favoritesFolderIdentifier;
    BOOL _dirty;
    SafariFetcherServerProxy *_safariFetcherServerProxy;
    BOOL _setupFinished;
    NSInteger _mergeMode;
    WBDatabaseLockAcquisitor *_databaseLockAcquisitor;
    NSInteger _lastObservedLocalMigrationState;
}


@property (readonly, nonatomic) NSInteger _cloudKitLocalMigrationState;
@property (readonly, nonatomic) BOOL _usesCloudKit;
@property (readonly, nonatomic) WebBookmark *bookmarksBarBookmark;
@property (readonly, nonatomic) WebBookmarkList *bookmarksBarList;
@property (readonly, nonatomic) WebBookmarkList *bookmarksNeedingIcons;
@property (readonly, nonatomic) WBCollectionConfiguration *configuration; // ivar: _configuration
@property (readonly, nonatomic) BOOL containsOnlyStockBookmarks;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic) WebBookmark *favoritesFolder;
@property (readonly, nonatomic) WebBookmarkList *favoritesFolderList;
@property (readonly, nonatomic) WebBookmark *frequentlyVisitedSitesFolder;
@property (readonly, copy, nonatomic) NSNumber *frequentlyVisitedSitesFolderBookmarkID;
@property (readonly, nonatomic) WebBookmarkList *frequentlyVisitedSitesList;
@property (readonly, nonatomic) NSUInteger generation;
@property (readonly, nonatomic) BOOL hasInMemoryChanges;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic) BOOL isEmpty;
@property (readonly, nonatomic, getter=isMerging) BOOL merging;
@property (readonly, copy, nonatomic) NSArray *purgeableReadingListItems;
@property (readonly, nonatomic) NSUInteger purgeableSpace;
@property (readonly, nonatomic) WebBookmark *readingListFolder;
@property (readonly, nonatomic) int readingListFolderBookmarkID;
@property (readonly, nonatomic) WebBookmarkList *rollingListOfArchivedReadingListItems;
@property (readonly, nonatomic) NSUInteger rollingReadingListMaximumCount;
@property (readonly, nonatomic) WebBookmark *rootBookmark;
@property (readonly, nonatomic) WebBookmarkList *rootList;
@property (readonly) Class superclass;
@property (readonly, nonatomic) WebBookmarkList *webFilterWhiteList;
@property (readonly, nonatomic) WebBookmark *webFilterWhiteListFolder;
@property (readonly, nonatomic) int webFilterWhiteListFolderBookmarkID;


+(BOOL)_isLockedSync;
+(BOOL)_lockSync;
+(BOOL)_removeCorruptedBookmarksDatabaseAtPath:(id)arg0 ;
+(BOOL)isLockedSync;
+(BOOL)isSyncAllowed;
+(BOOL)lockSync;
+(NSUInteger)readingListArchivesDiskUsage;
+(id)_cloudKitSyncMetadataFileNameWithCollectionType:(NSInteger)arg0 ;
+(id)_defaultDatabaseFileNameForCollectionType:(NSInteger)arg0 ;
+(id)_deviceIdentifierForCloudKitWithCollectionType:(NSInteger)arg0 ;
+(id)_deviceIdentifierForCloudKitWithCollectionType:(NSInteger)arg0 generateIfNeeded:(BOOL)arg1 ;
+(id)_syncFlags;
+(id)_syncLockFileName;
+(id)_uniqueExternalUUID;
+(id)bookmarkImagesDirectoryPath;
+(id)databasePathForConfiguration:(id)arg0 ;
+(id)inMemoryChangeSet;
+(id)inMemoryChangesFileURL;
+(id)readingListArchivesDirectoryPath;
+(id)safariBookmarkCollection;
+(id)safariDirectoryPath;
+(void)_postBookmarksChangedSyncNotificationOnSyncQueue;
+(void)_resetDeviceIdentifierForCloudKitWithCollectionType:(NSInteger)arg0 ;
+(void)_unlockSync;
+(void)holdLockSync:(*void)arg0 ;
+(void)unholdLockSync:(*void)arg0 ;
+(void)unlockSync;
+(void)unlockSyncAsynchronously;
-(BOOL)_addBookmarkWithTitle:(id)arg0 address:(id)arg1 parentID:(int)arg2 orderIndex:(unsigned int)arg3 isFolder:(BOOL)arg4 externalUUID:(id)arg5 associatedBookmark:(id)arg6 updateParentChildCount:(BOOL)arg7 updateAncestorEntries:(BOOL)arg8 ;
-(BOOL)_addChildrenOfID:(int)arg0 toCollection:(id)arg1 recursive:(BOOL)arg2 error:(*id)arg3 ;
-(BOOL)_bookmark:(id)arg0 hasCurrentDAVHomePath:(id)arg1 ;
-(BOOL)_bookmark:(id)arg0 hasPriorityOverBookmarkForDeduplication:(id)arg1 prioritizeBookmarksWithSyncData:(BOOL)arg2 davHomePath:(id)arg3 ;
-(BOOL)_bookmark:(id)arg0 isDuplicateOfBookmark:(id)arg1 ;
-(BOOL)_bookmarkHasSyncedToServer:(id)arg0 ;
-(BOOL)_checkDatabaseIntegrity;
-(BOOL)_childrenOfParentBookmarkAreUnsyncable:(id)arg0 ;
-(BOOL)_clearAllDAVSyncData;
-(BOOL)_clearAllSyncKeys;
-(BOOL)_clearAllTombstones;
-(BOOL)_clearChangeList;
-(BOOL)_clearSyncKeysUnderBookmarkID:(int)arg0 isFolder:(BOOL)arg1 ;
-(BOOL)_clearTitleWordsForBookmarkID:(int)arg0 ;
-(BOOL)_deduplicateBookmarksForBookmarkDAVWithHomeURL:(id)arg0 ;
-(BOOL)_deduplicateBookmarksForSyncingAndTrackChanges:(BOOL)arg0 considerBookmarksWithSyncDataAsUnique:(BOOL)arg1 ;
-(BOOL)_deduplicateBookmarksWithRootFolder:(int)arg0 depth:(NSUInteger)arg1 trackChanges:(BOOL)arg2 considerBookmarksWithSyncDataAsUnique:(BOOL)arg3 davHomeURL:(id)arg4 ;
-(BOOL)_deleteAncestorTableEntriesForBookmarkID:(int)arg0 ;
-(BOOL)_deleteAndRebuildAncestorTableRecords;
-(BOOL)_deleteBookmark:(id)arg0 leaveTombstone:(BOOL)arg1 ;
-(BOOL)_deleteBookmark:(id)arg0 postChangeNotification:(BOOL)arg1 forApplyingInMemoryChanges:(BOOL)arg2 ;
-(BOOL)_deleteBookmarks:(id)arg0 leaveTombstone:(BOOL)arg1 ;
-(BOOL)_deleteRecursively:(int)arg0 descendantsOnly:(BOOL)arg1 ;
-(BOOL)_deleteSyncPropertyForKey:(id)arg0 ;
-(BOOL)_ensureFolderChildrenCount:(id)arg0 ;
-(BOOL)_importBookmarksPlist:(id)arg0 ;
-(BOOL)_importSyncAnchorPlist:(id)arg0 ;
-(BOOL)_incrementDAVGeneration;
-(BOOL)_incrementGeneration;
-(BOOL)_indexAllTitleWords;
-(BOOL)_indexBookmarkID:(int)arg0 title:(id)arg1 ;
-(BOOL)_insertAncestorTableEntriesForBookmarkID:(int)arg0 withAncestorIDs:(id)arg1 ;
-(BOOL)_insertAncestorTableEntriesForBookmarkID:(int)arg0 withParentID:(int)arg1 ;
-(BOOL)_insertTombsonesRecursivelyForRootFolder:(id)arg0 ;
-(BOOL)_insertTombsonesRecursivelyHelperCurrentDepth:(NSUInteger)arg0 folder:(id)arg1 ;
-(BOOL)_insertTombstoneWithServerID:(id)arg0 syncData:(id)arg1 ;
-(BOOL)_isDatabaseWriteAllowed;
-(BOOL)_isTombstoneWithServerID:(id)arg0 ;
-(BOOL)_markBookmarkID:(int)arg0 added:(BOOL)arg1 ;
-(BOOL)_markBookmarkID:(int)arg0 withSpecialID:(int)arg1 ;
-(BOOL)_markSpecialBookmarks;
-(BOOL)_mergeBookmark:(id)arg0 withOriginalBookmark:(id)arg1 prioritizeOriginalBookmarkAttributes:(BOOL)arg2 generateChangesIfNeeded:(BOOL)arg3 ;
-(BOOL)_mergeChildrenOfID:(int)arg0 referencingBase:(id)arg1 error:(*id)arg2 ;
-(BOOL)_migrateBookmarksPlist:(id)arg0 syncAnchorPlist:(id)arg1 ;
-(BOOL)_migrateToCurrentSchema;
-(BOOL)_moveBookmark:(id)arg0 toFolderWithID:(int)arg1 ;
-(BOOL)_moveBookmark:(id)arg0 toFolderWithID:(int)arg1 detectCycles:(BOOL)arg2 ;
-(BOOL)_moveBookmark:(id)arg0 toIndex:(unsigned int)arg1 ;
-(BOOL)_needsDeduplicationForBookmarkDAVWithHomeURL:(id)arg0 ;
-(BOOL)_openDatabaseAtPath:(id)arg0 checkIntegrity:(BOOL)arg1 error:(*id)arg2 ;
-(BOOL)_orderChildrenWithServerIDs:(id)arg0 inFolderWithServerID:(id)arg1 excludeDeletedBookmarks:(BOOL)arg2 ;
-(BOOL)_primaryCollection;
-(BOOL)_rebuildAncestorTable;
-(BOOL)_recalculateCachedChildrenCountAndOrderIndices;
-(BOOL)_reindexBookmarkID:(int)arg0 title:(id)arg1 ;
-(BOOL)_reorderBookmark:(id)arg0 afterBookmark:(id)arg1 ;
-(BOOL)_reorderBookmark:(id)arg0 toIndex:(unsigned int)arg1 ;
-(BOOL)_restoreBookmarkBarIfMissing;
-(BOOL)_restoreMissingSpecialBookmarksWithChangeNotification:(BOOL)arg0 ;
-(BOOL)_saveAndMoveBookmark:(id)arg0 toFolderID:(int)arg1 ;
-(BOOL)_saveAndMoveBookmarks:(id)arg0 toFolderID:(int)arg1 ;
-(BOOL)_saveBookmark:(id)arg0 startReadingListFetcher:(BOOL)arg1 forApplyingInMemoryChanges:(BOOL)arg2 ;
-(BOOL)_saveBookmark:(id)arg0 withSpecialID:(int)arg1 updateGenerationIfNeeded:(BOOL)arg2 ;
-(BOOL)_saveSyncMetadataForBookmarkIfNeeded:(id)arg0 ;
-(BOOL)_setAccountHash:(id)arg0 ;
-(BOOL)_setLocalMigrationState:(NSInteger)arg0 generateDeviceIdentifierIfNeeded:(BOOL)arg1 ;
-(BOOL)_setServerID:(id)arg0 forBookmark:(id)arg1 ;
-(BOOL)_setSyncData:(id)arg0 forBookmark:(id)arg1 ;
-(BOOL)_setSyncKey:(id)arg0 forBookmark:(id)arg1 ;
-(BOOL)_setupWithPath:(id)arg0 checkIntegrity:(BOOL)arg1 ;
-(BOOL)_setupWithPath:(id)arg0 migratingBookmarksPlist:(id)arg1 syncAnchorPlist:(id)arg2 checkIntegrity:(BOOL)arg3 ;
-(BOOL)_shouldSaveBookmarkWhenUpdatingInFolderWithID:(int)arg0 ;
-(BOOL)_syncAdd:(id)arg0 toParent:(int)arg1 withOrderIndex:(unsigned int)arg2 error:(*id)arg3 ;
-(BOOL)_syncPropertyExistsForKey:(id)arg0 ;
-(BOOL)_syncSetString:(id)arg0 forKey:(id)arg1 updatedExistingKey:(*BOOL)arg2 ;
-(BOOL)_trackChangesInMemoryIfDatabaseWriteIsNotAllowed;
-(BOOL)_unsafeOrderChildrenWithServerIDs:(id)arg0 inFolderWithServerID:(id)arg1 excludeDeletedBookmarks:(BOOL)arg2 ;
-(BOOL)_updateBookmarks:(id)arg0 inFolderWithID:(int)arg1 ;
-(BOOL)_updateCachedChildCountForParentID:(int)arg0 inDirection:(int)arg1 ;
-(BOOL)_updateHiddenAncestorCountForBookmarksUnderFolderID:(int)arg0 addingOffset:(int)arg1 ;
-(BOOL)_verifyAllTablesExist:(*int)arg0 ;
-(BOOL)applyInMemoryChangesToDatabase;
-(BOOL)beginSyncTransaction;
-(BOOL)bookmarkContainsLeafBookmark:(id)arg0 ;
-(BOOL)bookmarkIsFavoritesFolder:(id)arg0 ;
-(BOOL)bookmarkIsFrequentlyVisitedSite:(id)arg0 ;
-(BOOL)bookmarkIsInFavoritesFolder:(id)arg0 ;
-(BOOL)cleanUpReadingListArchives;
-(BOOL)clearAllReadingListArchives;
-(BOOL)clearFrequentlyVisitedSitesFolder;
-(BOOL)clearReadingListArchiveWithUUID:(id)arg0 ;
-(BOOL)deduplicateBookmarks;
-(BOOL)deduplicateBookmarksWithRootFolder:(int)arg0 depth:(NSUInteger)arg1 ;
-(BOOL)deleteAllFavoriteIcons;
-(BOOL)deleteBookmark:(id)arg0 ;
-(BOOL)deleteBookmark:(id)arg0 postChangeNotification:(BOOL)arg1 ;
-(BOOL)deleteBookmarks:(id)arg0 postChangeNotification:(BOOL)arg1 ;
-(BOOL)fixCachedNumberOfChildrenIfNeeded;
-(BOOL)maintainsSyncMetadata;
-(BOOL)markAllFavoritesAsNeedingIcons;
-(BOOL)markArchivedReadingListItemsAsNonRecoverable;
-(BOOL)markWebContentFilterAllowsAllReadingListItems;
-(BOOL)mergeWithBookmarksDictionary:(id)arg0 clearHidden:(BOOL)arg1 clearSyncData:(BOOL)arg2 error:(*id)arg3 ;
-(BOOL)mergeWithBookmarksDictionary:(id)arg0 clearHidden:(BOOL)arg1 error:(*id)arg2 ;
-(BOOL)migrateReadingListIconsFromDatabaseToBookmarkImagesDirectory;
-(BOOL)moveBookmark:(id)arg0 toFolderWithID:(int)arg1 ;
-(BOOL)moveBookmark:(id)arg0 toIndex:(unsigned int)arg1 ;
// -(BOOL)performDatabaseUpdatesWithTransaction:(id)arg0 applyInMemoryChanges:(unk)arg1 secureDelete:(BOOL)arg2  ;
// -(BOOL)performDatabaseUpdatesWithTransaction:(id)arg0 secureDelete:(unk)arg1  ;
-(BOOL)reorderBookmark:(id)arg0 toIndex:(unsigned int)arg1 ;
-(BOOL)reorderList:(id)arg0 moveBookmarkAtIndex:(unsigned int)arg1 toIndex:(unsigned int)arg2 ;
-(BOOL)rollOutLastReadingListItem;
-(BOOL)saveBookmark:(id)arg0 ;
-(BOOL)saveBookmark:(id)arg0 startReadingListFetcher:(BOOL)arg1 ;
-(BOOL)saveBookmarks:(id)arg0 postNotification:(BOOL)arg1 ;
-(BOOL)setSyncData:(id)arg0 forKey:(id)arg1 ;
-(BOOL)shouldFetchIconForBookmark:(id)arg0 ;
-(BOOL)syncSetString:(id)arg0 forKey:(id)arg1 ;
-(BOOL)truncateWAL;
-(BOOL)updateBookmarks:(id)arg0 inFolderWithID:(int)arg1 secureDelete:(BOOL)arg2 ;
-(BOOL)updateReadingListWebFilterStatusForUnsetItemsOnly:(BOOL)arg0 ;
-(BOOL)vacuum;
-(NSInteger)_localMigrationState;
-(NSInteger)_mergeMode;
-(NSInteger)_syncType;
-(NSInteger)_userVersion;
-(NSInteger)nextDatabaseSyncChangeID;
-(NSUInteger)countReadingListBookmarksNeedingArchiveInMode:(NSInteger)arg0 ;
-(NSUInteger)countReadingListBookmarksNeedingArchiveInMode:(NSInteger)arg0 automaticArchivingEnabled:(BOOL)arg1 ;
-(NSUInteger)indexOfReadingListBookmark:(id)arg0 countingOnlyUnread:(BOOL)arg1 ;
-(NSUInteger)leafChildCountForBookmarksInFolderWithID:(int)arg0 ;
-(NSUInteger)modifiedAttributesOfBookmark:(id)arg0 ;
-(NSUInteger)purge:(NSUInteger)arg0 ;
-(id)_accountHash;
-(id)_applyInMemoryChanges:(id)arg0 postChangeNotification:(BOOL)arg1 ;
-(id)_bookmarkDictionaryForSqliteRow:(struct sqlite3_stmt *)arg0 recursive:(BOOL)arg1 error:(*id)arg2 ;
-(id)_bookmarkUUIDsInFolderWithID:(int)arg0 ;
-(id)_bookmarkWithServerID:(id)arg0 excludeDeletedBookmarks:(BOOL)arg1 ;
-(id)_bookmarkWithSpecialID:(int)arg0 ;
-(id)_bookmarksFromStatementSelectingIDs:(char *)arg0 withQuery:(id)arg1 ;
-(id)_changeList;
-(id)_databaseTitleForSpecialID:(int)arg0 ;
-(id)_errorForMostRecentSQLiteError;
-(id)_errorForMostRecentSQLiteErrorWithErrorCode:(NSInteger)arg0 ;
-(id)_fastFetchBookmarksInBookmarkFolder:(int)arg0 includingHiddenBookmarks:(BOOL)arg1 ;
-(id)_fastFetchBookmarksInBookmarkFolder:(int)arg0 includingInMemoryChanges:(BOOL)arg1 ;
-(id)_fastFetchBookmarksInBookmarkFolder:(int)arg0 options:(NSUInteger)arg1 offset:(int)arg2 limit:(int)arg3 ;
-(id)_fastFetchBookmarksInBookmarkFolder:(int)arg0 options:(NSUInteger)arg1 offset:(int)arg2 limit:(int)arg3 includingInMemoryChanges:(BOOL)arg4 ;
-(id)_fetchBookmarkIDsInFolder:(int)arg0 onlyFolders:(BOOL)arg1 includingHiddenBookmarks:(BOOL)arg2 ;
-(id)_firstBookmarkWithURLMatchingString:(id)arg0 prefixMatch:(BOOL)arg1 inParent:(int)arg2 ;
-(id)_firstOrLastServerIDInFolderWithServerID:(id)arg0 isFirst:(BOOL)arg1 ;
-(id)_firstServerIDInFolderWithServerID:(id)arg0 ;
-(id)_generateSyncPositionForBookmark:(id)arg0 ;
-(id)_inMemoryChangeSet;
-(id)_lastServerIDInFolderWithServerID:(id)arg0 ;
-(id)_mergeCandidateBookmarkWithTitle:(id)arg0 address:(id)arg1 parent:(int)arg2 mergeMode:(NSInteger)arg3 ;
-(id)_mergeCandidateFolderWithTitle:(id)arg0 parent:(int)arg1 mergeMode:(NSInteger)arg2 ;
-(id)_orderedWhereClauseForArchiveMode:(NSInteger)arg0 ;
-(id)_orderedWhereClauseForArchiveMode:(NSInteger)arg0 automaticArchivingEnabled:(BOOL)arg1 ;
-(id)_parentIdentifiersOfBookmarksNeedingIcons;
-(id)_readingListItemsWhere:(id)arg0 filteredBy:(id)arg1 withInMemoryFilter:(id)arg2 ;
-(id)_rootFolderHiddenChildrenClause;
-(id)_safariFetcherServerProxy;
-(id)_serverIDAfterServerID:(id)arg0 ;
-(id)_serverIDAtOrderIndex:(unsigned int)arg0 inFolderWithServerID:(id)arg1 ;
-(id)_serverIDBeforeServerID:(id)arg0 ;
-(id)_serverIDForBookmarkID:(int)arg0 ;
-(id)_serverIDOfSiblingBookmarkWithServerID:(id)arg0 immediatelyBeforeOrAfter:(BOOL)arg1 ;
-(id)_serverIDsInFolderWithServerID:(id)arg0 excludeDeletedBookmarks:(BOOL)arg1 ;
-(id)_syncKeysForServerIDs:(id)arg0 ;
-(id)_syncableBookmarksIDsInFolderWithBookmarkID:(int)arg0 ;
-(id)_tableExpressionForArchiveMode:(NSInteger)arg0 ;
-(id)applyInMemoryChanges:(id)arg0 ;
-(id)bookmarkAtPath:(id)arg0 ;
-(id)bookmarkWithID:(int)arg0 ;
-(id)bookmarkWithID:(int)arg0 includingInMemoryChanges:(BOOL)arg1 ;
-(id)bookmarkWithUUID:(id)arg0 ;
-(id)bookmarksDictionary;
-(id)bookmarksMatchingString:(id)arg0 ;
-(id)databaseHealthInformation;
-(id)databaseSyncData;
-(id)descendantsOfBookmarkFolder:(id)arg0 ;
-(id)fastFetchBookmarksInBookmarkList:(id)arg0 ;
-(id)firstReadingListBookmarkNeedingArchiveInMode:(NSInteger)arg0 ;
-(id)firstReadingListBookmarkNeedingArchiveInMode:(NSInteger)arg0 automaticArchivingEnabled:(BOOL)arg1 ;
-(id)firstReadingListBookmarkWithURLMatchingString:(id)arg0 prefixMatch:(BOOL)arg1 ;
-(id)frequentlyVisitedSitesFolderCreatingIfNeeded:(BOOL)arg0 ;
-(id)frequentlyVisitedSitesFolderCreatingIfNeeded:(BOOL)arg0 postChangeNotification:(BOOL)arg1 ;
-(id)initWithConfiguration:(id)arg0 ;
-(id)initWithConfiguration:(id)arg0 checkIntegrity:(BOOL)arg1 ;
-(id)initWithPath:(id)arg0 migratingBookmarksPlist:(id)arg1 syncAnchorPlist:(id)arg2 ;
-(id)leafChildCountForFoldersInFolderWithID:(int)arg0 ;
-(id)listWithID:(int)arg0 ;
-(id)listWithID:(int)arg0 skipOffset:(unsigned int)arg1 ;
-(id)listWithID:(int)arg0 skipOffset:(unsigned int)arg1 includeHidden:(BOOL)arg2 ;
-(id)listWithID:(int)arg0 skipOffset:(unsigned int)arg1 includeHidden:(BOOL)arg2 includeDescendantsAsChildren:(BOOL)arg3 filteredUsingString:(id)arg4 ;
-(id)listWithSpecialID:(int)arg0 ;
-(id)readingListBookmarksMatchingString:(id)arg0 maxResults:(unsigned int)arg1 onlyArchivedBookmarks:(BOOL)arg2 ;
-(id)readingListBookmarksNeedingArchiveInMode:(NSInteger)arg0 ;
-(id)readingListBookmarksNeedingArchiveInMode:(NSInteger)arg0 automaticArchivingEnabled:(BOOL)arg1 ;
-(id)readingListWithUnreadOnly:(BOOL)arg0 ;
-(id)readingListWithUnreadOnly:(BOOL)arg0 filteredUsingString:(id)arg1 ;
-(id)subfoldersOfID:(int)arg0 ;
-(id)syncDataForBookmark:(id)arg0 ;
-(id)syncDataForKey:(id)arg0 ;
-(id)syncStringForKey:(id)arg0 ;
-(id)validBookmarkUUIDsFromUUIDs:(id)arg0 ;
-(int)_DAVGeneration;
-(int)_bookmarkIDForServerID:(id)arg0 excludeDeletedBookmarks:(BOOL)arg1 ;
-(int)_executeSQL:(id)arg0 ;
-(int)_executeSQLWithCString:(char *)arg0 ;
-(int)_finalizeStatementIfNotNull:(struct sqlite3_stmt *)arg0 ;
-(int)_intFromExecutingSQL:(id)arg0 ;
-(int)_specialIDForBookmarkBeingSaved:(id)arg0 ;
-(int)_specialIDForBookmarkTitle:(id)arg0 ;
-(int)_sqliteStatementWithQuery:(id)arg0 runInBlock:(id)arg1 ;
-(int)identifierOfBookmarkWithUUID:(id)arg0 ;
-(int)parentIdentifierOfBookmark:(id)arg0 ;
-(struct sqlite3_stmt *)_prefixSearch:(id)arg0 usingColumns:(char *)arg1 maxCount:(unsigned int)arg2 ;
-(struct sqlite3_stmt *)_selectBookmarksWhere:(id)arg0 ;
-(struct sqlite3_stmt *)_selectBookmarksWhere:(id)arg0 returnType:(NSInteger)arg1 ;
-(struct sqlite3_stmt *)_sqliteStatementWithQuery:(id)arg0 ;
-(unsigned int)_orderIndexForBookmarkInsertedIntoParent:(int)arg0 insertAtBeginning:(BOOL)arg1 ;
-(unsigned int)orderIndexOfBookmark:(id)arg0 ;
-(void)_addBookmarksForReadingListMatchStatement:(id)arg0 normalizedQuery:(id)arg1 toArray:(id)arg2 maxResults:(int)arg3 ;
-(void)_appendDuplicateBookmarkGroupsInBookmarks:(id)arg0 toGroups:(id)arg1 considerBookmarksWithSyncDataAsUnique:(BOOL)arg2 davHomePath:(id)arg3 ;
-(void)_applyInMemoryChange:(id)arg0 fromChangeSet:(id)arg1 updatedBookmarks:(id)arg2 ;
-(void)_clearAndCreateAncestorTable;
-(void)_clearAndCreateBookmarksTables;
-(void)_clearAndCreateBookmarksTitleWordTable;
-(void)_clearCachedFavoritesFolderIdentifier;
-(void)_collectChangesOfType:(int)arg0 withClause:(id)arg1 intoArray:(id)arg2 ;
-(void)_createFreshDatabase;
-(void)_createInMemoryChangeSet;
-(void)_createSchema;
-(void)_cullReadingListBookmarksList:(id)arg0 toSize:(NSUInteger)arg1 ;
-(void)_deleteBookmarkInMemory:(id)arg0 ;
-(void)_deleteIconForBookmark:(id)arg0 ;
-(void)_enableAutoVacuum;
-(void)_enableForeignKeys;
-(void)_enumerateBookmarksForMatchStatement:(id)arg0 normalizedQuery:(id)arg1 usingBlock:(id)arg2 ;
-(void)_enumerateContentsOfBookmarkFolder:(int)arg0 includingSubfolders:(BOOL)arg1 usingBlock:(id)arg2 ;
-(void)_metaDataFileChanged:(id)arg0 ;
-(void)_migrateSchemaVersion0ToVersion1;
-(void)_migrateSchemaVersion10ToVersion11;
-(void)_migrateSchemaVersion11And12And13ToVersion14;
-(void)_migrateSchemaVersion14ToVersion15;
-(void)_migrateSchemaVersion15ToVersion16;
-(void)_migrateSchemaVersion16AndVersion17AndVersion18ToVersion19;
-(void)_migrateSchemaVersion19And20ToVersion21;
-(void)_migrateSchemaVersion1And2ToVersion3;
-(void)_migrateSchemaVersion21ToVersion22;
-(void)_migrateSchemaVersion22ToVersion23;
-(void)_migrateSchemaVersion23ToVersion24;
-(void)_migrateSchemaVersion24ToVersion25;
-(void)_migrateSchemaVersion25ToVersion26;
-(void)_migrateSchemaVersion26ToVersion27;
-(void)_migrateSchemaVersion27ToVersion28;
-(void)_migrateSchemaVersion28ToVersion29;
-(void)_migrateSchemaVersion29ToVersion30;
-(void)_migrateSchemaVersion30ToVersion31;
-(void)_migrateSchemaVersion31ToVersion32;
-(void)_migrateSchemaVersion32ToVersion33;
-(void)_migrateSchemaVersion33ToVersion34;
-(void)_migrateSchemaVersion34ToVersion35;
-(void)_migrateSchemaVersion35ToVersion36;
-(void)_migrateSchemaVersion36ToVersion37;
-(void)_migrateSchemaVersion37ToVersion38;
-(void)_migrateSchemaVersion38ToVersion39;
-(void)_migrateSchemaVersion39Or40ToVersion41;
-(void)_migrateSchemaVersion3ToVersion4;
-(void)_migrateSchemaVersion41ToVersion42;
-(void)_migrateSchemaVersion42ToVersion43;
-(void)_migrateSchemaVersion43ToVersion44;
-(void)_migrateSchemaVersion44ToVersion45;
-(void)_migrateSchemaVersion4ToVersion5;
-(void)_migrateSchemaVersion5ToVersion6;
-(void)_migrateSchemaVersion6ToVersion7;
-(void)_migrateSchemaVersion7ToVersion8;
-(void)_migrateSchemaVersion8ToVersion9;
-(void)_migrateSchemaVersion9ToVersion10;
-(void)_normalizeDatabaseURLs;
-(void)_normalizeSearchString:(struct __CFString *)arg0 ;
-(void)_postBookmarksChangedSyncNotification;
-(void)_postBookmarksDidReloadNotification;
-(void)_postBookmarksDidReloadNotificationAndStartReadingListFetcherIfChangesWereMade;
-(void)_postBookmarksFolderContentsDidChangeNotification:(int)arg0 ;
-(void)_postBookmarksSpecialFoldersDidChangeNotification;
-(void)_registerForSyncBookmarksFileChangedNotification;
-(void)_rerunMigrationsIfNecessary;
-(void)_restoreOrMergeReadingListFolderWithChangeNotification:(BOOL)arg0 ;
-(void)_restoreOrMergeWhiteListFolderAndContentsWithWebFilterWhiteList:(id)arg0 ensureChildCount:(BOOL)arg1 postChangeNotification:(BOOL)arg2 ;
-(void)_setMergeMode:(NSInteger)arg0 ;
-(void)_setSyncNotificationType:(NSInteger)arg0 ;
-(void)_setupInMemoryChangeSet;
-(void)_simulateCrashWithDescription:(id)arg0 ;
-(void)_startReadingListFetcher;
-(void)_test_preventPeriodicallyApplyingInMemoryChangesToDatabase;
-(void)_updateSelectedFavoritesFolderWithBookmarkID:(int)arg0 wasFavoritesFolder:(BOOL)arg1 isFavoritesFolder:(BOOL)arg2 ;
-(void)_updateSyncNotificationType;
-(void)addBookmarkInMemory:(id)arg0 toFolderWithID:(int)arg1 ;
-(void)clearCarrierBookmarks;
-(void)commitSyncTransaction;
-(void)databaseLockAcquisitor:(id)arg0 acquiredLock:(BOOL)arg1 ;
-(void)dealloc;
-(void)deleteArchiveForReadingListBookmarkWithID:(int)arg0 ;
-(void)deleteBookmarkInMemory:(id)arg0 ;
-(void)deleteBookmarksInMemory:(id)arg0 inFolder:(int)arg1 ;
-(void)enumerateBookmarks:(BOOL)arg0 andReadingListItems:(BOOL)arg1 matchingString:(id)arg2 usingBlock:(id)arg3 ;
-(void)localeSettingsChanged;
-(void)logRegulatoryBookmarksRead;
-(void)modifyBookmarkInMemory:(id)arg0 ;
-(void)moveBookmarkInMemory:(id)arg0 toFolderWithID:(int)arg1 ;
-(void)persistChangesWithCompletion:(id)arg0 ;
-(void)postBookmarksDidReloadNotification;
-(void)removePersistedInMemoryBookmarkChangesFile;
-(void)reorderBookmarkInMemory:(id)arg0 afterBookmark:(id)arg1 ;
-(void)replaceBookmarksInMemory:(id)arg0 inFolderWithID:(int)arg1 ;
-(void)restoreOrMergeWhiteListFolderAndContentsWithChangeNotification:(BOOL)arg0 ;
-(void)rollOutReadingListItemIfNeededToMakeRoomForOneNewItem;
-(void)rollbackSyncTransaction;
-(void)saveAndMoveBookmark:(id)arg0 toFolderID:(int)arg1 ;
-(void)saveArchiveForReadingListBookmarkWithID:(int)arg0 ;
-(void)saveArchivesForReadingListBookmarks:(id)arg0 ;
-(void)saveIconWithData:(id)arg0 urlString:(id)arg1 forBookmark:(id)arg2 ;
-(void)test_restoreMissingSpecialBookmarks;


@end


#endif