

#include "W5BluetoothDevice.h"
#include "W5DiagnosticsTestRequest.h"
#include "W5PowerStatus.h"
#include "W5Status.h"
#include "W5Event.h"
#include "W5WiFiChannel.h"
#include "W5LogItemReceipt.h"
#include "W5WiFiStatus.h"
#include "W5BluetoothStatus.h"
#include "W5WiFiLinkQualityUpdate.h"
#include "W5WiFiPreferredNetwork.h"
#include "W5DebugConfiguration.h"
#include "W5WiFiScanResult.h"
#include "W5NetworkStatus.h"
#include "W5PingResult.h"
#include "W5Peer.h"
#include "W5LogItemRequest.h"
#include "W5Client.h"
#include "W5DiagnosticsTestResult.h"
#include "W5AWDLStatus.h"
