

#include "_ICNamedEntityRecord.h"
#include "_ICContactRecord.h"
#include "_ICInputContextManager.h"
#include "_ICProactiveTrigger.h"
#include "_ICPredictedItem.h"
#include "_ICPredictionManager.h"
#include "_ICContact.h"
#include "_ICNullLexiconManager.h"
#include "_ICPortraitPredictionSource.h"
#include "_ICPortraitLexiconSource.h"
#include "_ICLexiconManager.h"
#include "_ICInternalSource.h"
#include "_ICInputSuggesterPredictionSource.h"
#include "_ICSearchContext.h"
#include "_ICTransientLexicon.h"
#include "_ICLexiconView.h"
#include "_ICPortraitUtilities.h"
#include "_ICInputContextFactory.h"
#include "_ICResultCache.h"
#include "_ICLexiconUtilities.h"
#include "_ICNamedEntityStore.h"
