// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef TSWPSTORAGE_H
#define TSWPSTORAGE_H

@class NSMutableString, NSString, TSPObject<TSDOwningAttachment>;
@protocol TSDContainerInfo, TSKSearchable, TSSThemedObject, TSWPStorageParent, TSSStyleClient, TSWPTextSource;


#import "TSPObject.h"
#import "TSWPStorageBroadcaster.h"
#import "TSKDocumentRoot.h"
#import "TSSStylesheet.h"
#import "TSDInfoGeometry.h"

@interface TSWPStorage : TSPObject <TSDContainerInfo, TSKSearchable, TSSThemedObject, TSWPStorageParent, TSSStyleClient, TSWPTextSource>

 {
    NSMutableString *_string;
    ? _attributesTable;
    TSWPStorageBroadcaster *_broadcaster;
    TSKDocumentRoot *_documentRoot;
    TSSStylesheet *_stylesheet;
    int _WPKind;
    unsigned int _disallowElementKinds;
    BOOL _dolcSuppressed;
    BOOL _delayBroadcast;
    _NSRange _rangeToBroadcast;
    int _writingDirectionCache;
}


@property (readonly, nonatomic, getter=isAnchoredToText) BOOL anchoredToText;
@property (readonly, nonatomic, getter=isAttachedToBodyText) BOOL attachedToBodyText;
@property (readonly, nonatomic) NSUInteger changeCount; // ivar: _changeCount
@property (readonly, nonatomic) NSInteger contentWritingDirection;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) *TSWPChangeAttributeArray deletionChangesTable;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic, getter=isFloatingAboveText) BOOL floatingAboveText;
@property (copy, nonatomic) TSDInfoGeometry *geometry;
@property (readonly, nonatomic) BOOL hasTrackedChanges;
@property (readonly) NSUInteger hash;
@property (nonatomic) ? hyperlinkCellID;
@property (nonatomic) BOOL ignoreContentsChangedNotifications; // ivar: _ignoreContentsChangedNotifications
@property (readonly, nonatomic, getter=isInlineWithText) BOOL inlineWithText;
@property (readonly, nonatomic) *TSWPChangeAttributeArray insertionChangesTable;
@property (readonly, nonatomic) BOOL isInInit; // ivar: _isInInit
@property (nonatomic) BOOL matchesObjectPlaceholderGeometry;
@property (nonatomic) TSPObject<TSDOwningAttachment> *owningAttachment; // ivar: _owningAttachment
@property (readonly, nonatomic) TSPObject<TSDOwningAttachment> *owningAttachmentNoRecurse;
@property (nonatomic) NSObject<TSDContainerInfo> *parentInfo; // ivar: _parentInfo
@property (readonly) Class superclass;


+(?)createAttributeArrayForKindundoTransaction;
+(?)createEmptyAttributeArrayForKind;
+(BOOL)allowsElementKind:(int)arg0 forStorageKind:(int)arg1 ;
+(Class)pStringClassForWPKind:(int)arg0 ;
+(id)filterMarkAttributes:(id)arg0 ;
+(id)filterText:(id)arg0 ;
+(id)filterText:(id)arg0 removingAttachments:(BOOL)arg1 ;
+(id)plainTextPasteStringForStorages:(id)arg0 forcePlainText:(BOOL)arg1 ;
+(void)initialize;
+(void)resetDisallowedElementKinds;
+(void)setDisallowedElementKinds:(unsigned int)arg0 forStorageKind:(int)arg1 ;
-(?)attributeArrayForKind;
-(?)attributeArrayForKind:(?)arg0 withCreate:(?)arg1 fromUndoundoTransaction;
-(?)compareAttributeArray1:(?)arg0 array2:(?)arg1 range1:(?)arg2 range2:(?)arg3 attributeIndex1attributeIndex2;
-(?)compareAttributeArray:(?)arg0 range:(?)arg1 otherStorageotherRange;
-(?)deletedRangeVectorInRange;
-(?)insertObject:(?)arg0 charIndex:(?)arg1 attributeArray:(?)arg2 attributeIndex:(?)arg3 dolcContextundoTransaction;
-(?)insertParagraphData:(?)arg0 charIndex:(?)arg1 attributeArray:(?)arg2 attributeIndexundoTransaction;
-(?)transferAttributeArraySource:(?)arg0 forSourceRange:(?)arg1 toDestStorage:(?)arg2 objectContext:(?)arg3 dolcContextflags;
-(?)transferAttributeArraySource:(?)arg0 toAttributeArrayDest:(?)arg1 atCharIndex:(?)arg2 dolcContextundoTransaction;
-(BOOL)adjustRangesByDelta:(NSInteger)arg0 ;
-(BOOL)allowsElementKind:(int)arg0 ;
-(BOOL)anchoredDrawableAttachmentCharacterAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)autoListRecognition;
-(BOOL)autoListTermination;
-(BOOL)canBeStoredInAStringValueCell;
-(BOOL)canPasteAsPlainText;
-(BOOL)canPasteAsPlainTextWithUniformParagraphs;
-(BOOL)canUserReplaceText;
-(BOOL)changesWithPageCount;
-(BOOL)hasAttachmentsThatChangeWithPageNumberOrPageCount;
-(BOOL)hasColumnBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasColumnStyleForParagraphBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasDeletedTextAtCharIndex:(NSUInteger)arg0 range:(struct _NSRange *)arg1 ;
-(BOOL)hasDeletionInRange:(struct _NSRange )arg0 ;
-(BOOL)hasHiddenTextAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasHiddenTextAtCharIndex:(NSUInteger)arg0 range:(struct _NSRange *)arg1 ;
-(BOOL)hasSectionForParagraphBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasSmartFields;
-(BOOL)hasSmartFieldsInRange:(struct _NSRange )arg0 ;
-(BOOL)hasVisibleText;
-(BOOL)hasVisibleTextAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)highlightsAllowed;
-(BOOL)isAllWhitespaceInRange:(struct _NSRange )arg0 ;
-(BOOL)isDOLCSuppressed;
-(BOOL)isEmptyParagraphSelection:(id)arg0 outRange:(struct _NSRange *)arg1 ;
-(BOOL)isThemeContent;
-(BOOL)isWholeParagraphsForRange:(struct _NSRange )arg0 ignoreAttachmentCharacters:(BOOL)arg1 requireParagraphBreakSelected:(BOOL)arg2 ;
-(BOOL)isWritingDirectionRightToLeftForListAtParIndex:(NSUInteger)arg0 ;
-(BOOL)isWritingDirectionRightToLeftForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)isWritingDirectionRightToLeftForParagraphAtParIndex:(NSUInteger)arg0 ;
-(BOOL)p_hasDeletedTextAtCharIndex:(NSUInteger)arg0 requireHidden:(BOOL)arg1 range:(struct _NSRange *)arg2 ;
-(BOOL)p_hasGoodAttributesForPlainTextPaste;
-(BOOL)p_passesExtraTablesChecksForStoringInAStringValueCell;
-(BOOL)p_shouldInsertionSplitChange:(id)arg0 changeSession:(id)arg1 ;
-(BOOL)paragraphHasListLabelAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)selectionContainsVisibleTrackedChanges:(id)arg0 ;
-(BOOL)setDOLCSuppressed:(BOOL)arg0 ;
-(BOOL)styleOverridesAppliedToRange:(struct _NSRange )arg0 ;
-(BOOL)supportsColumnStyles;
-(BOOL)supportsListStyles;
-(BOOL)supportsSectionCopying;
-(BOOL)supportsSections;
-(BOOL)textIsVertical;
-(CGFloat)filteredCoreTextAttributesFontScaleEffectiveRange:(struct _NSRange *)arg0 filterDelegate:(id)arg1 ;
-(Class)layoutClass;
-(Class)repClass;
-(NSInteger)hyphenationLocationBeforeIndex:(NSInteger)arg0 inRange:(struct _NSRange )arg1 locale:(struct __CFLocale *)arg2 hyphenChar:(*unsigned int)arg3 ;
-(NSInteger)pMapListsFromStorageRange:(struct _NSRange )arg0 toString:(id)arg1 atStringLoc:(NSUInteger)arg2 textListMap:(id)arg3 ;
-(NSUInteger)attachmentCount;
-(NSUInteger)attachmentIndexAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)attachmentIndexForInsertionAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)autoNumberFootnoteCountForRange:(struct _NSRange )arg0 ;
-(NSUInteger)charIndexMappedFromStorage:(NSUInteger)arg0 ;
-(NSUInteger)charIndexMappedToStorage:(NSUInteger)arg0 ;
-(NSUInteger)charIndexRemappedFromStorage:(NSUInteger)arg0 ;
-(NSUInteger)characterCount;
-(NSUInteger)characterStyleAttributeCount;
-(NSUInteger)columnStyleCount;
-(NSUInteger)emptyParagraphCount:(struct _NSRange )arg0 ;
-(NSUInteger)findCharIndexForAttachment:(id)arg0 ;
-(NSUInteger)findCharIndexForFootnoteAttachment:(id)arg0 ;
-(NSUInteger)findCharacterIndexForContainedInfo:(id)arg0 ;
-(NSUInteger)findNextParagraphStyleChange:(NSUInteger)arg0 maxCharIndex:(NSUInteger)arg1 ;
-(NSUInteger)firstParIndexInListAtParIndex:(NSUInteger)arg0 ;
-(NSUInteger)footnoteCount;
-(NSUInteger)footnoteIndexForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)footnoteIndexForFootnote:(id)arg0 ;
-(NSUInteger)footnoteIndexForFootnoteStorage:(id)arg0 ;
-(NSUInteger)indexAfterLastVisibleCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)indexForCharacter:(unsigned short)arg0 startCharIndex:(NSUInteger)arg1 ;
-(NSUInteger)indexOfFirstNonDeletedCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)indexOfFirstVisibleCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)length;
-(NSUInteger)listEndAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)listNumberForParagraphEnumerator:(struct TSWPParagraphEnumerator *)arg0 numberingData:(struct ? *)arg1 ;
-(NSUInteger)listNumberForParagraphIndex:(NSUInteger)arg0 numberingData:(struct ? *)arg1 ;
-(NSUInteger)listStartAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)listStyleCount;
-(NSUInteger)nextCharacterIndex:(NSUInteger)arg0 ;
-(NSUInteger)p_indexOfFirstNonDeletedCharInRange:(struct _NSRange )arg0 requireVisible:(BOOL)arg1 ;
-(NSUInteger)paragraphCount;
-(NSUInteger)paragraphEndAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphIndexAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphLevelAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphLevelAtParIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphStartAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)previousCharacterIndex:(NSUInteger)arg0 ;
-(NSUInteger)previousCharacterIndex:(NSUInteger)arg0 forDelete:(BOOL)arg1 ;
-(NSUInteger)sectionCount;
-(NSUInteger)sectionIndexForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)sectionIndexForSection:(id)arg0 ;
-(NSUInteger)selectedParagraphBreakCount:(struct _NSRange )arg0 ;
-(NSUInteger)selectionRangeMaxForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)selectionRangeMinForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)storageLength;
-(NSUInteger)wordCount;
-(id)attachmentAtAttachmentIndex:(NSUInteger)arg0 outCharIndex:(*NSUInteger)arg1 ;
-(id)attachmentAtCharIndex:(NSUInteger)arg0 ;
-(id)attachmentOrFootnoteAtCharIndex:(NSUInteger)arg0 ;
-(id)bestCharacterLanguageForTextRange:(struct _NSRange )arg0 ;
-(id)changeAtCharIndex:(NSUInteger)arg0 attributeKind:(unsigned int)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)changeAtCharIndex:(NSUInteger)arg0 outRange:(struct _NSRange *)arg1 ;
-(id)changeDetailsAtCharIndex:(NSUInteger)arg0 outRange:(struct _NSRange *)arg1 ;
-(id)changeDetailsForChange:(id)arg0 withRange:(struct _NSRange )arg1 ;
-(id)characterStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)characterStyleAtCharIndex:(NSUInteger)arg0 left:(BOOL)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)childCommandForApplyThemeCommand:(id)arg0 ;
-(id)childEnumerator;
-(id)childEnumeratorForRange:(struct _NSRange )arg0 ;
-(id)childInfos;
-(id)columnStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)columnStyleAtColumnStyleIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)copyWithContext:(id)arg0 ;
-(id)deletedRangesInRange:(struct _NSRange )arg0 ;
-(id)dictationAndAutocorrectionKeyAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)documentRoot;
-(id)editableAnnotationForInsertionPointSelection:(id)arg0 includeComments:(BOOL)arg1 withOutRange:(struct _NSRange *)arg2 selectionIsOnEdge:(*BOOL)arg3 ;
-(id)editableSmartFieldAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)extendSelectionForTopicChildren:(id)arg0 ;
-(id)extendSelectionToIncludeSmartFields:(id)arg0 ;
-(id)firstHighlightForSelectionRange:(struct _NSRange )arg0 outRange:(struct _NSRange *)arg1 ;
-(id)firstHighlightForSelectionRange:(struct _NSRange )arg0 outRange:(struct _NSRange *)arg1 requireComment:(BOOL)arg2 ;
-(id)fontNameAtCharIndex:(NSUInteger)arg0 size:(*CGFloat)arg1 effectiveRange:(struct _NSRange *)arg2 styleProvider:(id)arg3 ;
-(id)footnoteAtFootnoteIndex:(NSUInteger)arg0 outCharIndex:(*NSUInteger)arg1 ;
-(id)footnoteMarkAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteReferenceAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteReferenceAttachmentOrFootnoteMarkAttachmentAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteStorages;
-(id)glyphVariantDataAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)hiddenRangesInRange:(struct _NSRange )arg0 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 kind:(int)arg2 stylesheet:(id)arg3 paragraphStyle:(id)arg4 listStyle:(id)arg5 section:(id)arg6 columnStyle:(id)arg7 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 kind:(int)arg2 stylesheet:(id)arg3 paragraphStyle:(id)arg4 listStyle:(id)arg5 section:(id)arg6 columnStyle:(id)arg7 paragraphDirection:(int)arg8 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 stylesheet:(id)arg2 kind:(int)arg3 ;
-(id)languageAtParIndex:(NSUInteger)arg0 useStringTokenizer:(BOOL)arg1 useCreationLanguage:(BOOL)arg2 ;
-(id)languageForTextRange:(struct _NSRange )arg0 useStringTokenizer:(BOOL)arg1 useCreationLanguage:(BOOL)arg2 ;
-(id)listStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)listStyleAtParIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 context:(id)arg1 flags:(unsigned int)arg2 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 context:(id)arg1 flags:(unsigned int)arg2 kind:(int)arg3 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 storageContext:(id)arg1 objectsContext:(id)arg2 flags:(unsigned int)arg3 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 storageContext:(id)arg1 objectsContext:(id)arg2 flags:(unsigned int)arg3 kind:(int)arg4 ;
-(id)nextChangeFromCharIndex:(NSUInteger)arg0 afterChange:(id)arg1 changeRange:(struct _NSRange *)arg2 ;
-(id)nsAttributedStringWithAttributeDelegate:(id)arg0 ignoreLists:(BOOL)arg1 withLayoutParent:(id)arg2 ;
-(id)nsAttributedStringWithAttributeDelegate:(id)arg0 withLayoutParent:(id)arg1 ;
-(id)nsAttributedStringWithDefaultAttributeDelegateWithLayoutParent:(id)arg0 ;
-(id)nsAttributedStringWithLayoutParent:(id)arg0 ;
-(id)nsAttributedSubstringFromRange:(struct _NSRange )arg0 delegate:(id)arg1 scale:(CGFloat)arg2 applyChanges:(BOOL)arg3 includeInlineDrawables:(BOOL)arg4 withLayoutParent:(id)arg5 ;
-(id)nsAttributedSubstringFromRange:(struct _NSRange )arg0 scale:(CGFloat)arg1 ;
-(id)nsAttributedSubstringFromRange:(struct _NSRange )arg0 scale:(CGFloat)arg1 applyChanges:(BOOL)arg2 includeInlineDrawables:(BOOL)arg3 withLayoutParent:(id)arg4 ;
-(id)nsAttributedSubstringWithAttachmentsRemovedFromRange:(struct _NSRange )arg0 withLayoutParent:(id)arg1 ;
-(id)objectAtLocationAtExactCharIndex:(NSUInteger)arg0 forAttributeKind:(unsigned int)arg1 ;
-(id)objectAtLocationPriorToMappedCharIndex:(NSUInteger)arg0 forAttributeKind:(unsigned int)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)pDefaultSectionForContext:(id)arg0 ;
-(id)pDrawableInfoFromImporter:(id)arg0 error:(*id)arg1 ;
-(id)pExportAttributes:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 stickyFont:(*id)arg2 scale:(CGFloat)arg3 ;
-(id)pExportParagraphAttributes:(id)arg0 nextParagraphStyle:(id)arg1 scale:(CGFloat)arg2 ;
-(id)pFindValidInsertionCharStyleFromCharIndex:(NSUInteger)arg0 ;
-(id)pImportParagraphAttributes:(id)arg0 paragraphStyle:(id)arg1 ;
-(id)pNSAttributedStringWithAttributeDelegate:(id)arg0 ignoreLists:(BOOL)arg1 stripTextualAttachments:(BOOL)arg2 stripGraphicalAttachments:(BOOL)arg3 stripInlineAttachments:(BOOL)arg4 attachmentChar:(id)arg5 scale:(CGFloat)arg6 withLayoutParent:(id)arg7 ;
-(id)pNSAttributedStringWithDefaultDelegateIgnoreLists:(BOOL)arg0 stripTextualAttachments:(BOOL)arg1 stripGraphicalAttachments:(BOOL)arg2 stripInlineAttachments:(BOOL)arg3 attachmentChar:(id)arg4 scale:(CGFloat)arg5 withLayoutParent:(id)arg6 ;
-(id)pOverrideObjectBeforeReplacingCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 withInsertionBehavior:(int)arg2 ;
-(id)pOverrideObjectBeforeReplacingCharactersInSelection:(id)arg0 withString:(id)arg1 ;
-(id)pParagraphStyleWithFrequentAttributesInString:(id)arg0 withinStringRange:(struct _NSRange )arg1 currentParagraphStyle:(id)arg2 ;
-(id)pTextListsFromListStyle:(id)arg0 atLevel:(NSUInteger)arg1 labelTypeMap:(id)arg2 ;
-(id)p_replacementsForSelection:(id)arg0 withString:(id)arg1 changeSession:(id)arg2 shouldTrackDeletions:(BOOL)arg3 ;
-(id)paragraphStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)paragraphStyleAtParIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)plainTextStringFromRange:(struct _NSRange )arg0 convertTextualAttachments:(BOOL)arg1 includeChildTextStorages:(BOOL)arg2 forExport:(BOOL)arg3 withLayoutParent:(id)arg4 ;
-(id)previousChangeFromCharIndex:(NSUInteger)arg0 beforeChange:(id)arg1 changeRange:(struct _NSRange *)arg2 ;
-(id)referencedStyles;
-(id)referencedStylesOfClass:(Class)arg0 ;
-(id)relocateNonSelectedAnchorsInSelection:(id)arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(id)searchForAnnotationsWithHitBlock:(id)arg0 ;
-(id)searchForString:(id)arg0 options:(NSUInteger)arg1 onHit:(id)arg2 ;
-(id)searchInRange:(struct _NSRange )arg0 forString:(id)arg1 options:(NSUInteger)arg2 onHit:(id)arg3 ;
-(id)sectionAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)sectionAtSectionIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)smartFieldAtCharIndex:(NSUInteger)arg0 attributeKind:(unsigned int)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)smartFieldsWithAttributeKind:(unsigned int)arg0 intersectingRange:(struct _NSRange )arg1 ;
-(id)smartFieldsWithAttributeKind:(unsigned int)arg0 intersectingRange:(struct _NSRange )arg1 passingTest:(id)arg2 ;
-(id)string;
-(id)stringEquivalentFromRange:(struct _NSRange )arg0 ;
-(id)stringEquivalentFromRange:(struct _NSRange )arg0 withLayoutParent:(id)arg1 ;
-(id)stringValue;
-(id)stylesheet;
-(id)substringWithRange:(struct _NSRange )arg0 ;
-(id)substringWithSelection:(id)arg0 ;
-(id)textSourceForLayoutInRange:(struct _NSRange )arg0 ;
-(id)valueForBIUProperties:(id)arg0 ;
-(id)valueForBIUProperties:(id)arg0 selection:(id)arg1 insertionStyle:(id)arg2 ;
-(id)valueForProperty:(int)arg0 atCharIndex:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)visibleRangesInRange:(struct _NSRange )arg0 ;
-(int)compareRange:(struct _NSRange )arg0 otherStorage:(id)arg1 otherRange:(struct _NSRange )arg2 options:(NSUInteger)arg3 ;
-(int)wpKind;
-(int)writingDirectionForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(int)writingDirectionForParagraphAtParIndex:(NSUInteger)arg0 ;
-(struct TSWPAttributeArray *)attributeArrayForKind:(unsigned int)arg0 withCreate:(BOOL)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(struct TSWPParagraphAttributeArray *)paragraphAttributeArrayForKind:(unsigned int)arg0 withCreate:(BOOL)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorAtCharIndex:(NSUInteger)arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorAtParIndex:(NSUInteger)arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorForCharRange:(struct _NSRange )arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorForCharRange:(struct _NSRange )arg0 styleProvider:(id)arg1 requireHidden:(BOOL)arg2 ;
-(struct _NSRange )attachmentIndexRangeForTextRange:(struct _NSRange )arg0 ;
-(struct _NSRange )attachmentRangeForCharIndex:(NSUInteger)arg0 forwards:(BOOL)arg1 ;
-(struct _NSRange )attachmentRangeForCharIndex:(NSUInteger)arg0 forwards:(BOOL)arg1 attributeKind:(unsigned int)arg2 ;
-(struct _NSRange )charRangeMappedFromStorage:(struct _NSRange )arg0 ;
-(struct _NSRange )charRangeMappedToStorage:(struct _NSRange )arg0 ;
-(struct _NSRange )footnoteRangeForTextRange:(struct _NSRange )arg0 ;
-(struct _NSRange )insertAttachmentOrFootnote:(id)arg0 range:(struct _NSRange )arg1 ;
-(struct _NSRange )insertAttachmentOrFootnote:(id)arg0 range:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 changeSession:(id)arg4 ;
-(struct _NSRange )insertSection:(id)arg0 atCharIndex:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 changeSession:(id)arg4 ;
-(struct _NSRange )insertSpecialCharacter:(unsigned short)arg0 object:(id)arg1 kind:(unsigned int)arg2 range:(struct _NSRange )arg3 dolcContext:(id)arg4 undoTransaction:(struct TSWPStorageTransaction *)arg5 changeSession:(id)arg6 ;
-(struct _NSRange )nextWordFromIndex:(NSUInteger)arg0 forward:(BOOL)arg1 ;
-(struct _NSRange )p_RelocateNonSelectedAnchorsInRange:(struct _NSRange )arg0 selectionInfos:(id)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(struct _NSRange )p_extendRangeToIncludeSmartFields:(struct _NSRange )arg0 ;
-(struct _NSRange )p_rangeForSelectionAtCharIndex:(NSUInteger)arg0 caretIndex:(NSUInteger)arg1 handleNextWordWhitespace:(BOOL)arg2 ;
-(struct _NSRange )p_replaceCharactersInLogicalSelection:(id)arg0 withString:(id)arg1 withFlags:(unsigned int)arg2 replaceTextData:(struct ? *)arg3 changeSession:(id)arg4 undoTransaction:(struct TSWPStorageTransaction *)arg5 outInsertedRange:(struct _NSRange *)arg6 ;
-(struct _NSRange )paragraphIndexRangeForCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )range;
-(struct _NSRange )rangeByExpandingToIncludePartialWords:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToLineBreak:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToWhitespace:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToWhitespace:(struct _NSRange )arg0 skipVisibleDeleted:(BOOL)arg1 ;
-(struct _NSRange )rangeByTrimmingRange:(struct _NSRange )arg0 withBlock:(id)arg1 ;
-(struct _NSRange )rangeForChange:(id)arg0 ;
-(struct _NSRange )rangeForHighlight:(id)arg0 ;
-(struct _NSRange )rangeForSelectionAtCharIndex:(NSUInteger)arg0 caretIndex:(NSUInteger)arg1 ;
-(struct _NSRange )rangeForSelectionAtCharIndex:(NSUInteger)arg0 includePreviousWord:(BOOL)arg1 ;
-(struct _NSRange )rangeForSelectionWithInsertionSelection:(id)arg0 ;
-(struct _NSRange )rangeForTrackedChanges:(id)arg0 ;
-(struct _NSRange )rangeOfAnnotationWithOptions:(NSUInteger)arg0 range:(struct _NSRange )arg1 ;
-(struct _NSRange )rangeOfParagraphBreakingCharacter:(unsigned short)arg0 backwards:(BOOL)arg1 range:(struct _NSRange )arg2 ;
-(struct _NSRange )rangeOfString:(id)arg0 searchOptions:(NSUInteger)arg1 range:(struct _NSRange )arg2 ;
-(struct _NSRange )rangeOfString:(id)arg0 searchOptions:(NSUInteger)arg1 updatingSearchRange:(struct _NSRange *)arg2 ;
-(struct _NSRange )replaceAllOccurrencesOfObject:(id)arg0 withObject:(id)arg1 forKind:(unsigned int)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(struct _NSRange )replaceAllOccurrencesOfStyle:(id)arg0 withStyle:(id)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withStorage:(id)arg1 usePasteRules:(BOOL)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 notifyObservers:(BOOL)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(struct _NSRange )replaceCharactersInSelection:(id)arg0 withStorage:(id)arg1 usePasteRules:(BOOL)arg2 dolcContext:(id)arg3 changeSession:(id)arg4 undoTransaction:(*void)arg5 ;
-(struct _NSRange )replaceCharactersInSelection:(id)arg0 withString:(id)arg1 withFlags:(unsigned int)arg2 replaceTextData:(struct ? *)arg3 changeSession:(id)arg4 undoTransaction:(struct TSWPStorageTransaction *)arg5 outInsertedRange:(struct _NSRange *)arg6 ;
-(struct _NSRange )scanLeftForWordAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )selectionRangeForCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForListAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForListsInCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForParagraphAtIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForParagraphsInCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeForParagraphsInRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeIgnoringTrailingLineBreaksForParagraphAtIndex:(NSUInteger)arg0 ;
-(struct _NSRange )whiteSpaceRangeAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )whiteSpaceRangeAtCharIndex:(NSUInteger)arg0 includingBreaks:(BOOL)arg1 ;
-(struct _NSRange )wordAtCharIndex:(NSUInteger)arg0 includePreviousWord:(BOOL)arg1 ;
-(struct __CFDictionary *)createFilteredCoreTextAttributes:(struct __CFDictionary *)arg0 effectiveRange:(struct _NSRange *)arg1 filterDelegate:(id)arg2 ;
-(struct __CTFont *)createFontAtCharIndex:(NSUInteger)arg0 scaleTextPercent:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 styleProvider:(id)arg3 ;
-(unsigned int)disallowedElementKinds;
-(unsigned short)characterAtIndex:(NSUInteger)arg0 ;
-(unsigned short)paragraphFlagsAtCharIndex:(NSUInteger)arg0 ;
-(void)acceptVisitor:(id)arg0 ;
-(void)addAllDictationAndAutocorrectionKeyRangesInRange:(struct _NSRange )arg0 toRanges:(*void)arg1 ;
-(void)addDisallowedElementKind:(int)arg0 ;
-(void)addGlyphVariantData:(id)arg0 toRange:(struct _NSRange )arg1 ;
-(void)addObserver:(id)arg0 ;
-(void)addSmartField:(id)arg0 toRange:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)adoptStylesheet:(id)arg0 withMapper:(id)arg1 ;
-(void)appendSection:(id)arg0 charIndex:(NSUInteger)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)applyChange:(id)arg0 changeRange:(struct _NSRange )arg1 accept:(BOOL)arg2 undoTransaction:(*void)arg3 ;
-(void)applyChanges:(BOOL)arg0 inRange:(struct _NSRange )arg1 inSelectionRange:(struct _NSRange )arg2 outChangedRange:(struct _NSRange *)arg3 outSelectionRange:(struct _NSRange *)arg4 undoTransaction:(*void)arg5 forceAll:(BOOL)arg6 ;
-(void)applyDataValue:(unsigned int)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(unsigned int)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)applyFlags:(unsigned short)arg0 level:(NSUInteger)arg1 toParagraphIndexRange:(struct _NSRange )arg2 forKind:(unsigned int)arg3 undoTransaction:(struct TSWPStorageTransaction *)arg4 ;
-(void)applyFlags:(unsigned short)arg0 level:(NSUInteger)arg1 toParagraphsInCharRange:(struct _NSRange )arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)applyObject:(id)arg0 toCharRange:(struct _NSRange )arg1 forKind:(int)arg2 dolcContext:(id)arg3 undoTransaction:(struct TSWPStorageTransaction *)arg4 ;
-(void)applyObject:(id)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(unsigned int)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)applyObject:(id)arg0 toParagraphsInCharRange:(struct _NSRange )arg1 forKind:(unsigned int)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)applyWritingDirection:(int)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(unsigned int)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)attributesAtCharIndex:(NSUInteger)arg0 attributesOfInterest:(BOOL)arg1 attributesTable:(id)arg2 effectiveRange:(struct _NSRange *)arg3 ;
-(void)autoUpdateField:(id)arg0 withRange:(struct _NSRange )arg1 documentRoot:(id)arg2 returningInsertedRange:(struct _NSRange *)arg3 ;
-(void)autoUpdateSmartFieldsWithDocumentRoot:(id)arg0 ;
-(void)changeViewSettingsDidChange;
-(void)clearBackPointerToParentInfoIfNeeded:(id)arg0 ;
-(void)compress:(struct TSWPStorageTransaction *)arg0 ;
-(void)compressAttributeArrayKind:(unsigned int)arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(void)continueSearch:(id)arg0 ;
-(void)dealloc;
-(void)deleteRange:(struct _NSRange )arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(void)enumerateAttachmentsInTextRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateAttachmentsOfClass:(Class)arg0 inTextRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)enumerateParagraphsIntersectingTextRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateSmartFieldsWithAttributeKind:(unsigned int)arg0 inRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)enumerateWithAttributeKind:(unsigned int)arg0 inRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)filterInvalidContentForStorage:(id)arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(void)filterSectionBreaksFromStorage:(id)arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(void)findChangesInRange:(struct _NSRange )arg0 onHit:(id)arg1 ;
-(void)findCommentsInRange:(struct _NSRange )arg0 onHit:(id)arg1 ;
-(void)fixGlyphVariantFontsForRange:(struct _NSRange )arg0 ;
-(void)getCharacters:(*unsigned short)arg0 range:(struct _NSRange )arg1 ;
-(void)insertStorage:(id)arg0 atCharIndex:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)insertString:(id)arg0 atCharIndex:(NSUInteger)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)invalidateCharIndexForAttachment:(id)arg0 ;
-(void)invalidateFootnoteAttachmentCharIndexes;
-(void)invalidateForStyle:(id)arg0 ;
-(void)invalidatePageCountAttachmentCharIndexes:(BOOL)arg0 ;
-(void)lowLevelApplyObject:(id)arg0 toCharRange:(struct _NSRange )arg1 forKind:(int)arg2 dolcContext:(id)arg3 undoTransaction:(struct TSWPStorageTransaction *)arg4 ;
-(void)pApplyOverrideObjectAfterReplacingCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 overrideObject:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)pApplyOverrideObjectAfterReplacingCharactersInSelection:(id)arg0 withString:(id)arg1 overrideObject:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)pMapAttributesFromAttributedString:(id)arg0 ontoRange:(struct _NSRange )arg1 asCharacterStylesOnly:(BOOL)arg2 ;
-(void)p_attributesAtCharIndex:(NSUInteger)arg0 attributesOfInterest:(BOOL)arg1 attributesTable:(id)arg2 effectiveRange:(struct _NSRange *)arg3 ;
-(void)p_didChangeRange:(struct _NSRange )arg0 delta:(NSInteger)arg1 broadcastKind:(int)arg2 ;
-(void)p_fillMarkers:(*void)arg0 startingAtCharIndex:(NSUInteger)arg1 forCount:(NSUInteger)arg2 ;
-(void)p_fillMarkers:(*void)arg0 string:(id)arg1 length:(NSUInteger)arg2 hasAttachments:(*BOOL)arg3 hasFootnotes:(*BOOL)arg4 hasBreaks:(*BOOL)arg5 ;
// -(void)p_findChangesInRange:(struct _NSRange )arg0 onHit:(id)arg1 withAttributeKind:(unk)arg2  ;
-(void)p_handleChangeSplittingForInsertedRange:(struct _NSRange )arg0 changeSession:(id)arg1 undoTransaction:(*void)arg2 ;
-(void)p_lowLevelReplaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 length:(NSUInteger)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)p_replaceCharactersInSelection:(id)arg0 withString:(id)arg1 length:(NSUInteger)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)paragraphFlags:(*unsigned short)arg0 andLevel:(*NSUInteger)arg1 atCharIndex:(NSUInteger)arg2 ;
-(void)removeDisallowedElementKind:(int)arg0 ;
-(void)removeGlyphVariantDataFromRange:(struct _NSRange )arg0 ;
-(void)removeObserver:(id)arg0 ;
-(void)removeSmartField:(id)arg0 fromRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 options:(NSUInteger)arg2 changedRange:(struct _NSRange *)arg3 changeDelta:(*NSInteger)arg4 undoTransaction:(struct TSWPStorageTransaction *)arg5 changeSession:(id)arg6 ;
-(void)replaceReferencedStylesUsingBlock:(id)arg0 ;
-(void)replaceSectionAtSectionIndex:(NSUInteger)arg0 withSection:(id)arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)replaceWithAttachment:(id)arg0 forAttachmentIndex:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)setCharacterStyle:(id)arg0 range:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setColumnStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setDictationAndAutocorrection:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setDocumentRoot:(id)arg0 ;
-(void)setLanguage:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setListStart:(NSUInteger)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setListStyle:(id)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setListStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphFlags:(unsigned short)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphFlags:(unsigned short)arg0 level:(NSUInteger)arg1 forCharRange:(struct _NSRange )arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)setParagraphLevel:(NSUInteger)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphLevel:(NSUInteger)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphStyle:(id)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setParagraphWritingDirection:(int)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(struct TSWPStorageTransaction *)arg2 ;
-(void)setWPKind:(int)arg0 undoTransaction:(struct TSWPStorageTransaction *)arg1 ;
-(void)smartFieldDidChange:(id)arg0 ;
-(void)splitSmartFieldAtCharIndex:(NSUInteger)arg0 lengthToInsert:(NSUInteger)arg1 attributeKind:(unsigned int)arg2 dolcContext:(id)arg3 undoTransaction:(struct TSWPStorageTransaction *)arg4 ;
-(void)splitSmartFieldAtCharIndex:(NSUInteger)arg0 lengthToInsert:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(struct TSWPStorageTransaction *)arg3 ;
-(void)stashBroadcaster;
-(void)styleDidChangeInRange:(struct _NSRange )arg0 ;
-(void)unstashBroadcaster;
-(void)wasAddedToDocumentRoot:(id)arg0 dolcContext:(id)arg1 ;
-(void)wasRemovedFromDocumentRoot:(id)arg0 ;
-(void)willBeAddedToDocumentRoot:(id)arg0 dolcContext:(id)arg1 ;
-(void)willBeRemovedFromDocumentRoot:(id)arg0 ;


@end


#endif