// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef GEOANALYTICSPIPELINESTATEDATA_H
#define GEOANALYTICSPIPELINESTATEDATA_H

@class PBCodable, PBDataReader, NSString, NSMutableArray, NSData;
@protocol NSCopying;


#import "GEOLogMsgStateAccount.h"
#import "GEOCarInfo.h"
#import "GEOLogMsgStateCuratedCollection.h"
#import "GEOLocation.h"
#import "GEOMapRegion.h"
#import "GEOMapsServerMetadata.h"
#import "GEOLogMsgStatePlaceCard.h"
#import "GEOLogMsgEventPredExTrainingData.h"
#import "GEORouteDetails.h"
#import "GEOLogMsgStateUGCPhoto.h"

@interface GEOAnalyticsPipelineStateData : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    ? _placeCardPossibleActions;
    ? _placeCardUnactionableUiElements;
    GEOLogMsgStateAccount *_account;
    GEOCarInfo *_carPlayInfo;
    GEOLogMsgStateCuratedCollection *_curatedCollectionState;
    NSString *_deviceInputLocale;
    NSString *_deviceOutputLocale;
    GEOLocation *_lookAroundLocation;
    CGFloat _lookAroundZoom;
    CGFloat _lookaroundSessionEndTime;
    CGFloat _lookaroundSessionStartTime;
    NSString *_mapLaunchLaunchUri;
    NSString *_mapLaunchReferringWebsite;
    NSString *_mapLaunchSourceAppId;
    NSString *_mapLaunchSourceHandoffDevice;
    NSMutableArray *_mapSettingsNavVoiceSettings;
    CGFloat _mapViewLocationTouristTimestamp;
    GEOMapRegion *_mapViewMapRegion;
    CGFloat _mapViewPitch;
    CGFloat _mapViewStyleZoomLevel;
    CGFloat _mapViewZoomLevel;
    NSMutableArray *_mapsServerMetadataSuggestionEntryDisplayeds;
    NSData *_mapsServerMetadataSuggestionEntryTappedOn;
    GEOMapsServerMetadata *_mapsServerMetadata;
    NSString *_metroRegion;
    NSString *_placeCardPlaceActionDetailsActionUrl;
    NSUInteger _placeCardPlaceActionDetailsAnimationId;
    NSUInteger _placeCardPlaceActionDetailsBusinessId;
    NSString *_placeCardPlaceActionDetailsDestinationApp;
    NSString *_placeCardPlaceActionDetailsPhotoId;
    NSInteger _placeCardPlaceActionDetailsPlaceId;
    NSString *_placeCardPlaceActionDetailsRichProviderId;
    CGFloat _placeCardPlaceActionDetailsSearchResponseRelativeTimestamp;
    NSUInteger _placeCardPlaceActionDetailsTargetId;
    NSString *_placeCardPlaceActionDetailsTransitPlaceCardIncidentType;
    NSString *_placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageDirection;
    NSString *_placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageHeadsign;
    NSUInteger _placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageLineId;
    NSString *_placeCardPlaceActionDetailsTransitPlaceCardTransitSystemName;
    NSString *_placeCardPlaceCardCategory;
    GEOLogMsgStatePlaceCard *_placeCardState;
    GEOLogMsgEventPredExTrainingData *_predExTrainingData;
    GEORouteDetails *_routeRouteDetails;
    NSMutableArray *_suggestionsDisplayedResults;
    NSString *_suggestionsSearchString;
    GEOLogMsgStateUGCPhoto *_ugcPhotoState;
    NSString *_userHomeCountry;
    NSString *_userHomeMetro;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _lookAroundHeading;
    unsigned int _lookAroundNumberPoisInView;
    int _mapFeatureElectronicVehicleCount;
    int _mapFeatureFavoritesCount;
    int _mapFeatureLicensePlateCount;
    int _mapFeaturePersonalCollectionsCount;
    int _mapFeatureSavedCollectionsCount;
    int _mapFeatureSubmittedPhotosCount;
    int _mapFeatureSubmittedRatingsCount;
    int _mapSettingsLocationPrecisionType;
    int _mapSettingsNavVolume;
    int _mapSettingsTransportMode;
    unsigned int _mapUiCurrentTabIndex;
    int _mapUiLayoutInfo;
    int _mapUiLayoutStyle;
    unsigned int _mapUiNumberOfTabsOpen;
    int _mapUiShownActiveNavMode;
    int _mapViewMapType;
    int _mapViewViewMode;
    int _placeCardPlaceActionDetailsLocalSearchProviderId;
    int _placeCardPlaceActionDetailsResultIndex;
    int _placeCardPlaceActionDetailsTransitPlaceCardTransitCategory;
    int _placeCardPlaceCardType;
    int _restoreLayoutInfo;
    int _restoreLayoutStyle;
    int _restoreUiTarget;
    int _suggestionsAcSequenceNumber;
    int _suggestionsSearchFieldType;
    int _suggestionsSelectedIndex;
    BOOL _deviceInDarkMode;
    BOOL _landscape;
    BOOL _lookAroundEntryIconShown;
    BOOL _lookAroundIsLabelingShown;
    BOOL _lookaroundSessionHadMoveAction;
    BOOL _lookaroundSessionHadPanAction;
    BOOL _lookaroundSessionHadShareAction;
    BOOL _lookaroundSessionHadTapPoiAction;
    BOOL _lookaroundSessionHadZoomAction;
    BOOL _mapFeatureIsHomeFavoriteSet;
    BOOL _mapFeatureIsSchoolFavoriteSet;
    BOOL _mapFeatureIsTransitFavoriteSet;
    BOOL _mapFeatureIsWorkFavoriteSet;
    BOOL _mapLaunchIsHandoff;
    BOOL _mapSettingsAvoidBusyRoads;
    BOOL _mapSettingsAvoidHighways;
    BOOL _mapSettingsAvoidHills;
    BOOL _mapSettingsAvoidStairs;
    BOOL _mapSettingsAvoidTolls;
    BOOL _mapSettingsEBike;
    BOOL _mapSettingsFindMyCarEnabled;
    BOOL _mapSettingsHeadingEnabled;
    BOOL _mapSettingsIsHandsFreeProfileEnabled;
    BOOL _mapSettingsLabelEnabled;
    BOOL _mapSettingsPauseSpokenAudioEnabled;
    BOOL _mapSettingsSpeedLimitEnabled;
    BOOL _mapSettingsTrafficEnabled;
    BOOL _mapUiShownAqiShown;
    BOOL _mapUiShownWeatherShown;
    BOOL _mapViewIsAdvancedMap;
    BOOL _mapViewIsGlobeProjection;
    BOOL _mapViewLocationIsTourist;
    BOOL _mapViewLocationPuckInViewport;
    BOOL _placeCardTransitAdvisoryBanner;
    BOOL _rideBookingAppEnabled;
    BOOL _rideBookingAppInstalled;
    BOOL _suggestionsSiriEnabled;
    BOOL _tableBookingAppEnabled;
    BOOL _tableBookingAppInstalled;
    BOOL _venueExperienceShown;
    ? _flags;
}


@property (retain, nonatomic) GEOLogMsgStateAccount *account;
@property (retain, nonatomic) GEOCarInfo *carPlayInfo;
@property (retain, nonatomic) GEOLogMsgStateCuratedCollection *curatedCollectionState;
@property (nonatomic) BOOL deviceInDarkMode;
@property (retain, nonatomic) NSString *deviceInputLocale;
@property (retain, nonatomic) NSString *deviceOutputLocale;
@property (readonly, nonatomic) BOOL hasAccount;
@property (readonly, nonatomic) BOOL hasCarPlayInfo;
@property (readonly, nonatomic) BOOL hasCuratedCollectionState;
@property (nonatomic) BOOL hasDeviceInDarkMode;
@property (readonly, nonatomic) BOOL hasDeviceInputLocale;
@property (readonly, nonatomic) BOOL hasDeviceOutputLocale;
@property (nonatomic) BOOL hasLandscape;
@property (nonatomic) BOOL hasLookAroundEntryIconShown;
@property (nonatomic) BOOL hasLookAroundHeading;
@property (nonatomic) BOOL hasLookAroundIsLabelingShown;
@property (readonly, nonatomic) BOOL hasLookAroundLocation;
@property (nonatomic) BOOL hasLookAroundNumberPoisInView;
@property (nonatomic) BOOL hasLookAroundZoom;
@property (nonatomic) BOOL hasLookaroundSessionEndTime;
@property (nonatomic) BOOL hasLookaroundSessionHadMoveAction;
@property (nonatomic) BOOL hasLookaroundSessionHadPanAction;
@property (nonatomic) BOOL hasLookaroundSessionHadShareAction;
@property (nonatomic) BOOL hasLookaroundSessionHadTapPoiAction;
@property (nonatomic) BOOL hasLookaroundSessionHadZoomAction;
@property (nonatomic) BOOL hasLookaroundSessionStartTime;
@property (nonatomic) BOOL hasMapFeatureElectronicVehicleCount;
@property (nonatomic) BOOL hasMapFeatureFavoritesCount;
@property (nonatomic) BOOL hasMapFeatureIsHomeFavoriteSet;
@property (nonatomic) BOOL hasMapFeatureIsSchoolFavoriteSet;
@property (nonatomic) BOOL hasMapFeatureIsTransitFavoriteSet;
@property (nonatomic) BOOL hasMapFeatureIsWorkFavoriteSet;
@property (nonatomic) BOOL hasMapFeatureLicensePlateCount;
@property (nonatomic) BOOL hasMapFeaturePersonalCollectionsCount;
@property (nonatomic) BOOL hasMapFeatureSavedCollectionsCount;
@property (nonatomic) BOOL hasMapFeatureSubmittedPhotosCount;
@property (nonatomic) BOOL hasMapFeatureSubmittedRatingsCount;
@property (nonatomic) BOOL hasMapLaunchIsHandoff;
@property (readonly, nonatomic) BOOL hasMapLaunchLaunchUri;
@property (readonly, nonatomic) BOOL hasMapLaunchReferringWebsite;
@property (readonly, nonatomic) BOOL hasMapLaunchSourceAppId;
@property (readonly, nonatomic) BOOL hasMapLaunchSourceHandoffDevice;
@property (nonatomic) BOOL hasMapSettingsAvoidBusyRoads;
@property (nonatomic) BOOL hasMapSettingsAvoidHighways;
@property (nonatomic) BOOL hasMapSettingsAvoidHills;
@property (nonatomic) BOOL hasMapSettingsAvoidStairs;
@property (nonatomic) BOOL hasMapSettingsAvoidTolls;
@property (nonatomic) BOOL hasMapSettingsEBike;
@property (nonatomic) BOOL hasMapSettingsFindMyCarEnabled;
@property (nonatomic) BOOL hasMapSettingsHeadingEnabled;
@property (nonatomic) BOOL hasMapSettingsIsHandsFreeProfileEnabled;
@property (nonatomic) BOOL hasMapSettingsLabelEnabled;
@property (nonatomic) BOOL hasMapSettingsLocationPrecisionType;
@property (nonatomic) BOOL hasMapSettingsNavVolume;
@property (nonatomic) BOOL hasMapSettingsPauseSpokenAudioEnabled;
@property (nonatomic) BOOL hasMapSettingsSpeedLimitEnabled;
@property (nonatomic) BOOL hasMapSettingsTrafficEnabled;
@property (nonatomic) BOOL hasMapSettingsTransportMode;
@property (nonatomic) BOOL hasMapUiCurrentTabIndex;
@property (nonatomic) BOOL hasMapUiLayoutInfo;
@property (nonatomic) BOOL hasMapUiLayoutStyle;
@property (nonatomic) BOOL hasMapUiNumberOfTabsOpen;
@property (nonatomic) BOOL hasMapUiShownActiveNavMode;
@property (nonatomic) BOOL hasMapUiShownAqiShown;
@property (nonatomic) BOOL hasMapUiShownWeatherShown;
@property (nonatomic) BOOL hasMapViewIsAdvancedMap;
@property (nonatomic) BOOL hasMapViewIsGlobeProjection;
@property (nonatomic) BOOL hasMapViewLocationIsTourist;
@property (nonatomic) BOOL hasMapViewLocationPuckInViewport;
@property (nonatomic) BOOL hasMapViewLocationTouristTimestamp;
@property (readonly, nonatomic) BOOL hasMapViewMapRegion;
@property (nonatomic) BOOL hasMapViewMapType;
@property (nonatomic) BOOL hasMapViewPitch;
@property (nonatomic) BOOL hasMapViewStyleZoomLevel;
@property (nonatomic) BOOL hasMapViewViewMode;
@property (nonatomic) BOOL hasMapViewZoomLevel;
@property (readonly, nonatomic) BOOL hasMapsServerMetadata;
@property (readonly, nonatomic) BOOL hasMapsServerMetadataSuggestionEntryTappedOn;
@property (readonly, nonatomic) BOOL hasMetroRegion;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsActionUrl;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsAnimationId;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsBusinessId;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsDestinationApp;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsLocalSearchProviderId;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsPhotoId;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsPlaceId;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsResultIndex;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsRichProviderId;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsSearchResponseRelativeTimestamp;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsTargetId;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardIncidentType;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardTransitCategory;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageDirection;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageHeadsign;
@property (nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageLineId;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceActionDetailsTransitPlaceCardTransitSystemName;
@property (readonly, nonatomic) BOOL hasPlaceCardPlaceCardCategory;
@property (nonatomic) BOOL hasPlaceCardPlaceCardType;
@property (readonly, nonatomic) BOOL hasPlaceCardState;
@property (nonatomic) BOOL hasPlaceCardTransitAdvisoryBanner;
@property (readonly, nonatomic) BOOL hasPredExTrainingData;
@property (nonatomic) BOOL hasRestoreLayoutInfo;
@property (nonatomic) BOOL hasRestoreLayoutStyle;
@property (nonatomic) BOOL hasRestoreUiTarget;
@property (nonatomic) BOOL hasRideBookingAppEnabled;
@property (nonatomic) BOOL hasRideBookingAppInstalled;
@property (readonly, nonatomic) BOOL hasRouteRouteDetails;
@property (nonatomic) BOOL hasSuggestionsAcSequenceNumber;
@property (nonatomic) BOOL hasSuggestionsSearchFieldType;
@property (readonly, nonatomic) BOOL hasSuggestionsSearchString;
@property (nonatomic) BOOL hasSuggestionsSelectedIndex;
@property (nonatomic) BOOL hasSuggestionsSiriEnabled;
@property (nonatomic) BOOL hasTableBookingAppEnabled;
@property (nonatomic) BOOL hasTableBookingAppInstalled;
@property (readonly, nonatomic) BOOL hasUgcPhotoState;
@property (readonly, nonatomic) BOOL hasUserHomeCountry;
@property (readonly, nonatomic) BOOL hasUserHomeMetro;
@property (nonatomic) BOOL hasVenueExperienceShown;
@property (nonatomic) BOOL landscape;
@property (nonatomic) BOOL lookAroundEntryIconShown;
@property (nonatomic) unsigned int lookAroundHeading;
@property (nonatomic) BOOL lookAroundIsLabelingShown;
@property (retain, nonatomic) GEOLocation *lookAroundLocation;
@property (nonatomic) unsigned int lookAroundNumberPoisInView;
@property (nonatomic) CGFloat lookAroundZoom;
@property (nonatomic) CGFloat lookaroundSessionEndTime;
@property (nonatomic) BOOL lookaroundSessionHadMoveAction;
@property (nonatomic) BOOL lookaroundSessionHadPanAction;
@property (nonatomic) BOOL lookaroundSessionHadShareAction;
@property (nonatomic) BOOL lookaroundSessionHadTapPoiAction;
@property (nonatomic) BOOL lookaroundSessionHadZoomAction;
@property (nonatomic) CGFloat lookaroundSessionStartTime;
@property (nonatomic) int mapFeatureElectronicVehicleCount;
@property (nonatomic) int mapFeatureFavoritesCount;
@property (nonatomic) BOOL mapFeatureIsHomeFavoriteSet;
@property (nonatomic) BOOL mapFeatureIsSchoolFavoriteSet;
@property (nonatomic) BOOL mapFeatureIsTransitFavoriteSet;
@property (nonatomic) BOOL mapFeatureIsWorkFavoriteSet;
@property (nonatomic) int mapFeatureLicensePlateCount;
@property (nonatomic) int mapFeaturePersonalCollectionsCount;
@property (nonatomic) int mapFeatureSavedCollectionsCount;
@property (nonatomic) int mapFeatureSubmittedPhotosCount;
@property (nonatomic) int mapFeatureSubmittedRatingsCount;
@property (nonatomic) BOOL mapLaunchIsHandoff;
@property (retain, nonatomic) NSString *mapLaunchLaunchUri;
@property (retain, nonatomic) NSString *mapLaunchReferringWebsite;
@property (retain, nonatomic) NSString *mapLaunchSourceAppId;
@property (retain, nonatomic) NSString *mapLaunchSourceHandoffDevice;
@property (nonatomic) BOOL mapSettingsAvoidBusyRoads;
@property (nonatomic) BOOL mapSettingsAvoidHighways;
@property (nonatomic) BOOL mapSettingsAvoidHills;
@property (nonatomic) BOOL mapSettingsAvoidStairs;
@property (nonatomic) BOOL mapSettingsAvoidTolls;
@property (nonatomic) BOOL mapSettingsEBike;
@property (nonatomic) BOOL mapSettingsFindMyCarEnabled;
@property (nonatomic) BOOL mapSettingsHeadingEnabled;
@property (nonatomic) BOOL mapSettingsIsHandsFreeProfileEnabled;
@property (nonatomic) BOOL mapSettingsLabelEnabled;
@property (nonatomic) int mapSettingsLocationPrecisionType;
@property (retain, nonatomic) NSMutableArray *mapSettingsNavVoiceSettings;
@property (nonatomic) int mapSettingsNavVolume;
@property (nonatomic) BOOL mapSettingsPauseSpokenAudioEnabled;
@property (nonatomic) BOOL mapSettingsSpeedLimitEnabled;
@property (nonatomic) BOOL mapSettingsTrafficEnabled;
@property (nonatomic) int mapSettingsTransportMode;
@property (nonatomic) unsigned int mapUiCurrentTabIndex;
@property (nonatomic) int mapUiLayoutInfo;
@property (nonatomic) int mapUiLayoutStyle;
@property (nonatomic) unsigned int mapUiNumberOfTabsOpen;
@property (nonatomic) int mapUiShownActiveNavMode;
@property (nonatomic) BOOL mapUiShownAqiShown;
@property (nonatomic) BOOL mapUiShownWeatherShown;
@property (nonatomic) BOOL mapViewIsAdvancedMap;
@property (nonatomic) BOOL mapViewIsGlobeProjection;
@property (nonatomic) BOOL mapViewLocationIsTourist;
@property (nonatomic) BOOL mapViewLocationPuckInViewport;
@property (nonatomic) CGFloat mapViewLocationTouristTimestamp;
@property (retain, nonatomic) GEOMapRegion *mapViewMapRegion;
@property (nonatomic) int mapViewMapType;
@property (nonatomic) CGFloat mapViewPitch;
@property (nonatomic) CGFloat mapViewStyleZoomLevel;
@property (nonatomic) int mapViewViewMode;
@property (nonatomic) CGFloat mapViewZoomLevel;
@property (retain, nonatomic) GEOMapsServerMetadata *mapsServerMetadata;
@property (retain, nonatomic) NSMutableArray *mapsServerMetadataSuggestionEntryDisplayeds;
@property (retain, nonatomic) NSData *mapsServerMetadataSuggestionEntryTappedOn;
@property (retain, nonatomic) NSString *metroRegion;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsActionUrl;
@property (nonatomic) NSUInteger placeCardPlaceActionDetailsAnimationId;
@property (nonatomic) NSUInteger placeCardPlaceActionDetailsBusinessId;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsDestinationApp;
@property (nonatomic) int placeCardPlaceActionDetailsLocalSearchProviderId;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsPhotoId;
@property (nonatomic) NSInteger placeCardPlaceActionDetailsPlaceId;
@property (nonatomic) int placeCardPlaceActionDetailsResultIndex;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsRichProviderId;
@property (nonatomic) CGFloat placeCardPlaceActionDetailsSearchResponseRelativeTimestamp;
@property (nonatomic) NSUInteger placeCardPlaceActionDetailsTargetId;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsTransitPlaceCardIncidentType;
@property (nonatomic) int placeCardPlaceActionDetailsTransitPlaceCardTransitCategory;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageDirection;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageHeadsign;
@property (nonatomic) NSUInteger placeCardPlaceActionDetailsTransitPlaceCardTransitDepartureSequenceUsageLineId;
@property (retain, nonatomic) NSString *placeCardPlaceActionDetailsTransitPlaceCardTransitSystemName;
@property (retain, nonatomic) NSString *placeCardPlaceCardCategory;
@property (nonatomic) int placeCardPlaceCardType;
@property (readonly, nonatomic) *int placeCardPossibleActions;
@property (readonly, nonatomic) NSUInteger placeCardPossibleActionsCount;
@property (retain, nonatomic) GEOLogMsgStatePlaceCard *placeCardState;
@property (nonatomic) BOOL placeCardTransitAdvisoryBanner;
@property (readonly, nonatomic) *int placeCardUnactionableUiElements;
@property (readonly, nonatomic) NSUInteger placeCardUnactionableUiElementsCount;
@property (retain, nonatomic) GEOLogMsgEventPredExTrainingData *predExTrainingData;
@property (nonatomic) int restoreLayoutInfo;
@property (nonatomic) int restoreLayoutStyle;
@property (nonatomic) int restoreUiTarget;
@property (nonatomic) BOOL rideBookingAppEnabled;
@property (nonatomic) BOOL rideBookingAppInstalled;
@property (retain, nonatomic) GEORouteDetails *routeRouteDetails;
@property (nonatomic) int suggestionsAcSequenceNumber;
@property (retain, nonatomic) NSMutableArray *suggestionsDisplayedResults;
@property (nonatomic) int suggestionsSearchFieldType;
@property (retain, nonatomic) NSString *suggestionsSearchString;
@property (nonatomic) int suggestionsSelectedIndex;
@property (nonatomic) BOOL suggestionsSiriEnabled;
@property (nonatomic) BOOL tableBookingAppEnabled;
@property (nonatomic) BOOL tableBookingAppInstalled;
@property (retain, nonatomic) GEOLogMsgStateUGCPhoto *ugcPhotoState;
@property (retain, nonatomic) NSString *userHomeCountry;
@property (retain, nonatomic) NSString *userHomeMetro;
@property (nonatomic) BOOL venueExperienceShown;


+(BOOL)isValid:(id)arg0 ;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)readFrom:(id)arg0 ;
-(NSUInteger)hash;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)description;
-(id)dictionaryRepresentation;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)mapSettingsLocationPrecisionTypeAsString:(int)arg0 ;
-(id)mapSettingsNavVoiceSettingsAtIndex:(NSUInteger)arg0 ;
-(id)mapSettingsNavVolumeAsString:(int)arg0 ;
-(id)mapSettingsTransportModeAsString:(int)arg0 ;
-(id)mapUiLayoutInfoAsString:(int)arg0 ;
-(id)mapUiLayoutStyleAsString:(int)arg0 ;
-(id)mapUiShownActiveNavModeAsString:(int)arg0 ;
-(id)mapViewMapTypeAsString:(int)arg0 ;
-(id)mapViewViewModeAsString:(int)arg0 ;
-(id)mapsServerMetadataSuggestionEntryDisplayedAtIndex:(NSUInteger)arg0 ;
-(id)placeCardPlaceActionDetailsTransitPlaceCardTransitCategoryAsString:(int)arg0 ;
-(id)placeCardPlaceCardTypeAsString:(int)arg0 ;
-(id)restoreLayoutInfoAsString:(int)arg0 ;
-(id)restoreLayoutStyleAsString:(int)arg0 ;
-(id)restoreUiTargetAsString:(int)arg0 ;
-(id)suggestionsDisplayedResultsAtIndex:(NSUInteger)arg0 ;
-(id)suggestionsSearchFieldTypeAsString:(int)arg0 ;
-(int)StringAsMapSettingsLocationPrecisionType:(id)arg0 ;
-(int)StringAsMapSettingsNavVolume:(id)arg0 ;
-(int)StringAsMapSettingsTransportMode:(id)arg0 ;
-(int)StringAsMapUiLayoutInfo:(id)arg0 ;
-(int)StringAsMapUiLayoutStyle:(id)arg0 ;
-(int)StringAsMapUiShownActiveNavMode:(id)arg0 ;
-(int)StringAsMapViewMapType:(id)arg0 ;
-(int)StringAsMapViewViewMode:(id)arg0 ;
-(int)StringAsPlaceCardPlaceActionDetailsTransitPlaceCardTransitCategory:(id)arg0 ;
-(int)StringAsPlaceCardPlaceCardType:(id)arg0 ;
-(int)StringAsRestoreLayoutInfo:(id)arg0 ;
-(int)StringAsRestoreLayoutStyle:(id)arg0 ;
-(int)StringAsRestoreUiTarget:(id)arg0 ;
-(int)StringAsSuggestionsSearchFieldType:(id)arg0 ;
-(int)placeCardPossibleActionsAtIndex:(NSUInteger)arg0 ;
-(int)placeCardUnactionableUiElementsAtIndex:(NSUInteger)arg0 ;
-(void)addMapSettingsNavVoiceSettings:(id)arg0 ;
-(void)addMapsServerMetadataSuggestionEntryDisplayed:(id)arg0 ;
-(void)addPlaceCardPossibleActions:(int)arg0 ;
-(void)addPlaceCardUnactionableUiElements:(int)arg0 ;
-(void)addSuggestionsDisplayedResults:(id)arg0 ;
-(void)clearMapSettingsNavVoiceSettings;
-(void)clearMapsServerMetadataSuggestionEntryDisplayeds;
-(void)clearPlaceCardPossibleActions;
-(void)clearPlaceCardUnactionableUiElements;
-(void)clearSensitiveFields:(NSUInteger)arg0 ;
-(void)clearSuggestionsDisplayedResults;
-(void)copyTo:(id)arg0 ;
-(void)dealloc;
-(void)mergeFrom:(id)arg0 ;
-(void)readAll:(BOOL)arg0 ;
-(void)writeTo:(id)arg0 ;


@end


#endif