// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef GEOMAPSERVICETRAITS_H
#define GEOMAPSERVICETRAITS_H

@class PBCodable, PBDataReader, PBUnknownFields, NSString, NSMutableArray;
@protocol NSCopying;


#import "GEOAutomobileOptions.h"
#import "GEOCyclingOptions.h"
#import "GEOLocation.h"
#import "GEOMapRegion.h"
#import "GEOPDViewportInfo.h"
#import "GEOPDResultRefinementQuery.h"
#import "GEOTransitOptions.h"
#import "GEOTraitsTransitScheduleFilter.h"
#import "GEOPDVenueIdentifier.h"
#import "GEOWalkingOptions.h"

@interface GEOMapServiceTraits : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    ? _engineTypes;
    ? _knownClientResolvedTypes;
    ? _knownRefinementTypes;
    ? _supportedAutocompleteListTypes;
    ? _supportedAutocompleteResultCellTypes;
    ? _supportedChildActions;
    ? _supportedPlaceSummaryFormatTypes;
    ? _supportedSearchTierTypes;
    ? _transportTypes;
    GEOSessionID _sessionId;
    NSString *_analyticsAppIdentifier;
    NSString *_appIdentifier;
    NSString *_appMajorVersion;
    NSString *_appMinorVersion;
    GEOAutomobileOptions *_automobileOptions;
    NSString *_carHeadunitManufacturer;
    NSString *_carHeadunitModel;
    CGFloat _carHeadunitPixelHeight;
    CGFloat _carHeadunitPixelWidth;
    NSString *_currentLocaleCurrencySymbol;
    GEOCyclingOptions *_cyclingOptions;
    GEOLocation *_deviceLocation;
    NSMutableArray *_deviceDisplayLanguages;
    NSString *_deviceKeyboardLocale;
    NSString *_deviceSpokenLocale;
    NSString *_displayRegion;
    NSMutableArray *_evChargingPorts;
    NSMutableArray *_historicalLocations;
    CGFloat _isTourist;
    GEOMapRegion *_mapRegion;
    CGFloat _mapZoomLevel;
    NSMutableArray *_photoSizes;
    GEOPDViewportInfo *_previousSearchViewport;
    NSString *_providerID;
    GEOPDResultRefinementQuery *_resultRefinementQuery;
    NSMutableArray *_reviewUserPhotoSizes;
    CGFloat _sessionRelativeTimestamp;
    GEOTransitOptions *_transitOptions;
    GEOTraitsTransitScheduleFilter *_transitScheduleFilter;
    GEOTraitsTransitScheduleFilter *_transitTripStopTimeFilter;
    GEOPDVenueIdentifier *_venueIdentifier;
    GEOWalkingOptions *_walkingOptions;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _auxiliaryTierNumResults;
    int _carHeadunitConnectionType;
    int _carHeadunitInteractionModel;
    int _deviceBatteryState;
    int _deviceInterfaceOrientation;
    unsigned int _httpRequestPriority;
    int _mode;
    int _navigationTransportType;
    unsigned int _photoAlbumCount;
    unsigned int _photosCount;
    unsigned int _placeSummaryRevision;
    unsigned int _ratingsCount;
    unsigned int _relatedPlaceItemCount;
    int _requestPurpose;
    unsigned int _reviewUserPhotosCount;
    int _searchRequestType;
    unsigned int _sequenceNumber;
    int _source;
    unsigned int _timeSinceMapEnteredForeground;
    unsigned int _timeSinceMapViewportChanged;
    BOOL _appDarkMode;
    BOOL _autocompleteRequestSupportsSectionHeader;
    BOOL _deviceDarkMode;
    BOOL _deviceInVehicle;
    BOOL _isAPICall;
    BOOL _isRefund;
    BOOL _isSettlement;
    BOOL _isWidgetRequest;
    BOOL _navigating;
    BOOL _supportAutocompleteGuideResults;
    BOOL _supportAutocompletePublisherResults;
    BOOL _supportAutocompleteRapAffordance;
    BOOL _supportChildItems;
    BOOL _supportClientRankingFeatureMetadata;
    BOOL _supportDirectionIntentAutocomplete;
    BOOL _supportDirectionIntentSearch;
    BOOL _supportDymSuggestion;
    BOOL _supportUnresolvedDirectionIntent;
    BOOL _supportsBrandFallback;
    BOOL _useBackgroundUrl;
    BOOL _wantsBrandIcon;
    ? _flags;
}


@property (retain, nonatomic) NSString *analyticsAppIdentifier;
@property (nonatomic) BOOL appDarkMode;
@property (retain, nonatomic) NSString *appIdentifier;
@property (retain, nonatomic) NSString *appMajorVersion;
@property (retain, nonatomic) NSString *appMinorVersion;
@property (nonatomic) BOOL autocompleteRequestSupportsSectionHeader;
@property (retain, nonatomic) GEOAutomobileOptions *automobileOptions;
@property (nonatomic) unsigned int auxiliaryTierNumResults;
@property (nonatomic) int carHeadunitConnectionType;
@property (nonatomic) int carHeadunitInteractionModel;
@property (retain, nonatomic) NSString *carHeadunitManufacturer;
@property (retain, nonatomic) NSString *carHeadunitModel;
@property (nonatomic) CGFloat carHeadunitPixelHeight;
@property (nonatomic) CGFloat carHeadunitPixelWidth;
@property (retain, nonatomic) NSString *currentLocaleCurrencySymbol;
@property (retain, nonatomic) GEOCyclingOptions *cyclingOptions;
@property (nonatomic) int deviceBatteryState;
@property (nonatomic) BOOL deviceDarkMode;
@property (retain, nonatomic) NSMutableArray *deviceDisplayLanguages;
@property (nonatomic) BOOL deviceInVehicle;
@property (nonatomic) int deviceInterfaceOrientation;
@property (retain, nonatomic) NSString *deviceKeyboardLocale;
@property (retain, nonatomic) GEOLocation *deviceLocation;
@property (retain, nonatomic) NSString *deviceSpokenLocale;
@property (retain, nonatomic) NSString *displayRegion;
@property (readonly, nonatomic) *int engineTypes;
@property (readonly, nonatomic) NSUInteger engineTypesCount;
@property (retain, nonatomic) NSMutableArray *evChargingPorts;
@property (readonly, nonatomic) BOOL hasAnalyticsAppIdentifier;
@property (nonatomic) BOOL hasAppDarkMode;
@property (readonly, nonatomic) BOOL hasAppIdentifier;
@property (readonly, nonatomic) BOOL hasAppMajorVersion;
@property (readonly, nonatomic) BOOL hasAppMinorVersion;
@property (nonatomic) BOOL hasAutocompleteRequestSupportsSectionHeader;
@property (readonly, nonatomic) BOOL hasAutomobileOptions;
@property (nonatomic) BOOL hasAuxiliaryTierNumResults;
@property (nonatomic) BOOL hasCarHeadunitConnectionType;
@property (nonatomic) BOOL hasCarHeadunitInteractionModel;
@property (readonly, nonatomic) BOOL hasCarHeadunitManufacturer;
@property (readonly, nonatomic) BOOL hasCarHeadunitModel;
@property (nonatomic) BOOL hasCarHeadunitPixelHeight;
@property (nonatomic) BOOL hasCarHeadunitPixelWidth;
@property (readonly, nonatomic) BOOL hasCurrentLocaleCurrencySymbol;
@property (readonly, nonatomic) BOOL hasCyclingOptions;
@property (nonatomic) BOOL hasDeviceBatteryState;
@property (nonatomic) BOOL hasDeviceDarkMode;
@property (nonatomic) BOOL hasDeviceInVehicle;
@property (nonatomic) BOOL hasDeviceInterfaceOrientation;
@property (readonly, nonatomic) BOOL hasDeviceKeyboardLocale;
@property (readonly, nonatomic) BOOL hasDeviceLocation;
@property (readonly, nonatomic) BOOL hasDeviceSpokenLocale;
@property (readonly, nonatomic) BOOL hasDisplayRegion;
@property (nonatomic) BOOL hasHttpRequestPriority;
@property (nonatomic) BOOL hasIsAPICall;
@property (nonatomic) BOOL hasIsRefund;
@property (nonatomic) BOOL hasIsSettlement;
@property (nonatomic) BOOL hasIsTourist;
@property (nonatomic) BOOL hasIsWidgetRequest;
@property (readonly, nonatomic) BOOL hasMapRegion;
@property (nonatomic) BOOL hasMapZoomLevel;
@property (nonatomic) BOOL hasMode;
@property (nonatomic) BOOL hasNavigating;
@property (nonatomic) BOOL hasNavigationTransportType;
@property (nonatomic) BOOL hasPhotoAlbumCount;
@property (nonatomic) BOOL hasPhotosCount;
@property (nonatomic) BOOL hasPlaceSummaryRevision;
@property (readonly, nonatomic) BOOL hasPreviousSearchViewport;
@property (readonly, nonatomic) BOOL hasProviderID;
@property (nonatomic) BOOL hasRatingsCount;
@property (nonatomic) BOOL hasRelatedPlaceItemCount;
@property (nonatomic) BOOL hasRequestPurpose;
@property (readonly, nonatomic) BOOL hasResultRefinementQuery;
@property (nonatomic) BOOL hasReviewUserPhotosCount;
@property (nonatomic) BOOL hasSearchRequestType;
@property (nonatomic) BOOL hasSequenceNumber;
@property (nonatomic) BOOL hasSessionId;
@property (nonatomic) BOOL hasSessionRelativeTimestamp;
@property (nonatomic) BOOL hasSource;
@property (nonatomic) BOOL hasSupportAutocompleteGuideResults;
@property (nonatomic) BOOL hasSupportAutocompletePublisherResults;
@property (nonatomic) BOOL hasSupportAutocompleteRapAffordance;
@property (nonatomic) BOOL hasSupportChildItems;
@property (nonatomic) BOOL hasSupportClientRankingFeatureMetadata;
@property (nonatomic) BOOL hasSupportDirectionIntentAutocomplete;
@property (nonatomic) BOOL hasSupportDirectionIntentSearch;
@property (nonatomic) BOOL hasSupportDymSuggestion;
@property (nonatomic) BOOL hasSupportUnresolvedDirectionIntent;
@property (nonatomic) BOOL hasSupportsBrandFallback;
@property (nonatomic) BOOL hasTimeSinceMapEnteredForeground;
@property (nonatomic) BOOL hasTimeSinceMapViewportChanged;
@property (readonly, nonatomic) BOOL hasTransitOptions;
@property (readonly, nonatomic) BOOL hasTransitScheduleFilter;
@property (readonly, nonatomic) BOOL hasTransitTripStopTimeFilter;
@property (nonatomic) BOOL hasUseBackgroundUrl;
@property (readonly, nonatomic) BOOL hasVenueIdentifier;
@property (readonly, nonatomic) BOOL hasWalkingOptions;
@property (nonatomic) BOOL hasWantsBrandIcon;
@property (retain, nonatomic) NSMutableArray *historicalLocations;
@property (nonatomic) unsigned int httpRequestPriority;
@property (nonatomic) BOOL isAPICall;
@property (nonatomic) BOOL isRefund;
@property (nonatomic) BOOL isSettlement;
@property (nonatomic) CGFloat isTourist;
@property (nonatomic) BOOL isWidgetRequest;
@property (readonly, nonatomic) *int knownClientResolvedTypes;
@property (readonly, nonatomic) NSUInteger knownClientResolvedTypesCount;
@property (readonly, nonatomic) *int knownRefinementTypes;
@property (readonly, nonatomic) NSUInteger knownRefinementTypesCount;
@property (retain, nonatomic) GEOMapRegion *mapRegion;
@property (nonatomic) CGFloat mapZoomLevel;
@property (nonatomic) int mode;
@property (nonatomic) BOOL navigating;
@property (nonatomic) int navigationTransportType;
@property (nonatomic) unsigned int photoAlbumCount;
@property (retain, nonatomic) NSMutableArray *photoSizes;
@property (nonatomic) unsigned int photosCount;
@property (nonatomic) unsigned int placeSummaryRevision;
@property (retain, nonatomic) GEOPDViewportInfo *previousSearchViewport;
@property (retain, nonatomic) NSString *providerID;
@property (nonatomic) unsigned int ratingsCount;
@property (nonatomic) unsigned int relatedPlaceItemCount;
@property (nonatomic) int requestPurpose;
@property (retain, nonatomic) GEOPDResultRefinementQuery *resultRefinementQuery;
@property (retain, nonatomic) NSMutableArray *reviewUserPhotoSizes;
@property (nonatomic) unsigned int reviewUserPhotosCount;
@property (nonatomic) int searchRequestType;
@property (nonatomic) unsigned int sequenceNumber;
@property (nonatomic) GEOSessionID sessionId;
@property (nonatomic) CGFloat sessionRelativeTimestamp;
@property (nonatomic) int source;
@property (nonatomic) BOOL supportAutocompleteGuideResults;
@property (nonatomic) BOOL supportAutocompletePublisherResults;
@property (nonatomic) BOOL supportAutocompleteRapAffordance;
@property (nonatomic) BOOL supportChildItems;
@property (nonatomic) BOOL supportClientRankingFeatureMetadata;
@property (nonatomic) BOOL supportDirectionIntentAutocomplete;
@property (nonatomic) BOOL supportDirectionIntentSearch;
@property (nonatomic) BOOL supportDymSuggestion;
@property (nonatomic) BOOL supportUnresolvedDirectionIntent;
@property (readonly, nonatomic) *int supportedAutocompleteListTypes;
@property (readonly, nonatomic) NSUInteger supportedAutocompleteListTypesCount;
@property (readonly, nonatomic) *int supportedAutocompleteResultCellTypes;
@property (readonly, nonatomic) NSUInteger supportedAutocompleteResultCellTypesCount;
@property (readonly, nonatomic) *int supportedChildActions;
@property (readonly, nonatomic) NSUInteger supportedChildActionsCount;
@property (readonly, nonatomic) *int supportedPlaceSummaryFormatTypes;
@property (readonly, nonatomic) NSUInteger supportedPlaceSummaryFormatTypesCount;
@property (readonly, nonatomic) *int supportedSearchTierTypes;
@property (readonly, nonatomic) NSUInteger supportedSearchTierTypesCount;
@property (nonatomic) BOOL supportsBrandFallback;
@property (nonatomic) unsigned int timeSinceMapEnteredForeground;
@property (nonatomic) unsigned int timeSinceMapViewportChanged;
@property (retain, nonatomic) GEOTransitOptions *transitOptions;
@property (retain, nonatomic) GEOTraitsTransitScheduleFilter *transitScheduleFilter;
@property (retain, nonatomic) GEOTraitsTransitScheduleFilter *transitTripStopTimeFilter;
@property (readonly, nonatomic) *int transportTypes;
@property (readonly, nonatomic) NSUInteger transportTypesCount;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;
@property (nonatomic) BOOL useBackgroundUrl;
@property (retain, nonatomic) GEOPDVenueIdentifier *venueIdentifier;
@property (retain, nonatomic) GEOWalkingOptions *walkingOptions;
@property (nonatomic) BOOL wantsBrandIcon;


+(BOOL)isValid:(id)arg0 ;
+(Class)deviceDisplayLanguageType;
+(Class)evChargingPortType;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)readFrom:(id)arg0 ;
-(NSUInteger)hash;
-(id)carHeadunitConnectionTypeAsString:(int)arg0 ;
-(id)carHeadunitInteractionModelAsString:(int)arg0 ;
-(id)copyByIncrementingSessionCounters;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)description;
-(id)deviceBatteryStateAsString:(int)arg0 ;
-(id)deviceDisplayLanguageAtIndex:(NSUInteger)arg0 ;
-(id)deviceInterfaceOrientationAsString:(int)arg0 ;
-(id)dictionaryRepresentation;
-(id)engineTypesAsString:(int)arg0 ;
-(id)evChargingPortAtIndex:(NSUInteger)arg0 ;
-(id)historicalLocationsAtIndex:(NSUInteger)arg0 ;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)knownClientResolvedTypesAsString:(int)arg0 ;
-(id)knownRefinementTypesAsString:(int)arg0 ;
-(id)modeAsString:(int)arg0 ;
-(id)navigationTransportTypeAsString:(int)arg0 ;
-(id)photoSizesAtIndex:(NSUInteger)arg0 ;
-(id)requestPurposeAsString:(int)arg0 ;
-(id)reviewUserPhotoSizesAtIndex:(NSUInteger)arg0 ;
-(id)searchRequestTypeAsString:(int)arg0 ;
-(id)sourceAsString:(int)arg0 ;
-(id)supportedAutocompleteListTypesAsString:(int)arg0 ;
-(id)supportedAutocompleteResultCellTypesAsString:(int)arg0 ;
-(id)supportedChildActionsAsString:(int)arg0 ;
-(id)supportedPlaceSummaryFormatTypesAsString:(int)arg0 ;
-(id)supportedSearchTierTypesAsString:(int)arg0 ;
-(id)transportTypesAsString:(int)arg0 ;
-(int)StringAsCarHeadunitConnectionType:(id)arg0 ;
-(int)StringAsCarHeadunitInteractionModel:(id)arg0 ;
-(int)StringAsDeviceBatteryState:(id)arg0 ;
-(int)StringAsDeviceInterfaceOrientation:(id)arg0 ;
-(int)StringAsEngineTypes:(id)arg0 ;
-(int)StringAsKnownClientResolvedTypes:(id)arg0 ;
-(int)StringAsKnownRefinementTypes:(id)arg0 ;
-(int)StringAsMode:(id)arg0 ;
-(int)StringAsNavigationTransportType:(id)arg0 ;
-(int)StringAsRequestPurpose:(id)arg0 ;
-(int)StringAsSearchRequestType:(id)arg0 ;
-(int)StringAsSource:(id)arg0 ;
-(int)StringAsSupportedAutocompleteListTypes:(id)arg0 ;
-(int)StringAsSupportedAutocompleteResultCellTypes:(id)arg0 ;
-(int)StringAsSupportedChildActions:(id)arg0 ;
-(int)StringAsSupportedPlaceSummaryFormatTypes:(id)arg0 ;
-(int)StringAsSupportedSearchTierTypes:(id)arg0 ;
-(int)StringAsTransportTypes:(id)arg0 ;
-(int)engineTypeAtIndex:(NSUInteger)arg0 ;
-(int)knownClientResolvedTypeAtIndex:(NSUInteger)arg0 ;
-(int)knownRefinementTypeAtIndex:(NSUInteger)arg0 ;
-(int)supportedAutocompleteListTypeAtIndex:(NSUInteger)arg0 ;
-(int)supportedAutocompleteResultCellTypeAtIndex:(NSUInteger)arg0 ;
-(int)supportedChildActionAtIndex:(NSUInteger)arg0 ;
-(int)supportedPlaceSummaryFormatTypeAtIndex:(NSUInteger)arg0 ;
-(int)supportedSearchTierTypeAtIndex:(NSUInteger)arg0 ;
-(int)transportTypeAtIndex:(NSUInteger)arg0 ;
-(void)_internal_incrementSessionCounters;
-(void)addDeviceDisplayLanguage:(id)arg0 ;
-(void)addEngineType:(int)arg0 ;
-(void)addEvChargingPort:(id)arg0 ;
-(void)addHistoricalLocations:(id)arg0 ;
-(void)addKnownClientResolvedType:(int)arg0 ;
-(void)addKnownRefinementType:(int)arg0 ;
-(void)addPhotoSizes:(id)arg0 ;
-(void)addReviewUserPhotoSizes:(id)arg0 ;
-(void)addSupportedAutocompleteListType:(int)arg0 ;
-(void)addSupportedAutocompleteResultCellType:(int)arg0 ;
-(void)addSupportedChildAction:(int)arg0 ;
-(void)addSupportedPlaceSummaryFormatType:(int)arg0 ;
-(void)addSupportedSearchTierType:(int)arg0 ;
-(void)addTransportType:(int)arg0 ;
-(void)clearDeviceDisplayLanguages;
-(void)clearEngineTypes;
-(void)clearEvChargingPorts;
-(void)clearHistoricalLocations;
-(void)clearKnownClientResolvedTypes;
-(void)clearKnownRefinementTypes;
-(void)clearLocations;
-(void)clearPhotoSizes;
-(void)clearReviewUserPhotoSizes;
-(void)clearSensitiveFields:(NSUInteger)arg0 ;
-(void)clearSessionId;
-(void)clearSupportedAutocompleteListTypes;
-(void)clearSupportedAutocompleteResultCellTypes;
-(void)clearSupportedChildActions;
-(void)clearSupportedPlaceSummaryFormatTypes;
-(void)clearSupportedSearchTierTypes;
-(void)clearTransportTypes;
-(void)clearUnknownFields:(BOOL)arg0 ;
-(void)copyTo:(id)arg0 ;
-(void)dealloc;
-(void)mergeFrom:(id)arg0 ;
-(void)readAll:(BOOL)arg0 ;
-(void)updateAnalyticsShortSession;
-(void)writeTo:(id)arg0 ;


@end


#endif