// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef WEBACCESSIBILITYOBJECTWRAPPER_H
#define WEBACCESSIBILITYOBJECTWRAPPER_H



#import "WebAccessibilityObjectWrapperBase.h"

@interface WebAccessibilityObjectWrapper : WebAccessibilityObjectWrapperBase {
    int m_isAccessibilityElement;
    NSUInteger m_accessibilityTraitsFromAncestor;
}




-(*void)detailParentForObject:(*void)arg0 ;
-(*void)detailParentForSummaryObject:(*void)arg0 ;
-(*void)tableCellParent;
-(*void)tableParent;
-(*void)treeItemParentForObject:(*void)arg0 ;
-(?)nextMarkerForCharacterOffset;
-(?)previousMarkerForCharacterOffset;
-(BOOL)_accessibilityActivate;
-(BOOL)_accessibilityHasTouchEventListener;
-(BOOL)_accessibilityIsInTableCell;
-(BOOL)_accessibilityIsLandmarkRole:(int)arg0 ;
-(BOOL)_accessibilityIsStrongPasswordField;
-(BOOL)_accessibilityScrollToVisible;
-(BOOL)_accessibilityValueIsAutofilled;
-(BOOL)accessibilityARIAIsBusy;
-(BOOL)accessibilityARIALiveRegionIsAtomic;
-(BOOL)accessibilityCanFuzzyHitTest;
-(BOOL)accessibilityCanSetValue;
-(BOOL)accessibilityHasDocumentRoleAncestor;
-(BOOL)accessibilityHasPopup;
-(BOOL)accessibilityHasWebApplicationAncestor;
-(BOOL)accessibilityInsertText:(id)arg0 ;
-(BOOL)accessibilityIsAttachmentElement;
-(BOOL)accessibilityIsAttributeSettable:(id)arg0 ;
-(BOOL)accessibilityIsComboBox;
-(BOOL)accessibilityIsDialog;
-(BOOL)accessibilityIsExpanded;
-(BOOL)accessibilityIsInDescriptionListDefinition;
-(BOOL)accessibilityIsInDescriptionListTerm;
-(BOOL)accessibilityIsIndeterminate;
-(BOOL)accessibilityIsMathTopObject;
-(BOOL)accessibilityIsMediaMuted;
-(BOOL)accessibilityIsMediaPlaying;
-(BOOL)accessibilityIsPressed;
-(BOOL)accessibilityIsRequired;
-(BOOL)accessibilityIsShowingValidationMessage;
-(BOOL)accessibilityIsWebInteractiveVideo;
-(BOOL)accessibilityPerformEscape;
-(BOOL)accessibilityReplaceRange:(struct _NSRange )arg0 withText:(id)arg1 ;
-(BOOL)accessibilityRequired;
-(BOOL)accessibilityScroll:(NSInteger)arg0 ;
-(BOOL)accessibilitySupportsARIAExpanded;
-(BOOL)accessibilitySupportsARIAPressed;
-(BOOL)containsUnnaturallySegmentedChildren;
-(BOOL)determineIsAccessibilityElement;
-(BOOL)isAccessibilityElement;
-(BOOL)isAttachment;
-(BOOL)isSVGGroupElement;
-(BOOL)stringValueShouldBeUsedInLabel;
-(CGFloat)_accessibilityMaxValue;
-(CGFloat)_accessibilityMinValue;
-(NSInteger)accessibilityElementCount;
-(NSInteger)accessibilityMathLineThickness;
-(NSInteger)indexOfAccessibilityElement:(id)arg0 ;
-(NSInteger)lengthForTextMarkers:(id)arg0 ;
-(NSInteger)positionForTextMarker:(id)arg0 ;
-(NSUInteger)_accessibilityTextEntryTraits;
-(NSUInteger)_accessibilityTraitsFromAncestors;
-(NSUInteger)_axAdjustableTrait;
-(NSUInteger)_axButtonTrait;
-(NSUInteger)_axContainedByFieldsetTrait;
-(NSUInteger)_axContainedByLandmarkTrait;
-(NSUInteger)_axContainedByListTrait;
-(NSUInteger)_axContainedByTableTrait;
-(NSUInteger)_axHasTextCursorTrait;
-(NSUInteger)_axHeaderTrait;
-(NSUInteger)_axImageTrait;
-(NSUInteger)_axLinkTrait;
-(NSUInteger)_axMenuItemTrait;
-(NSUInteger)_axNotEnabledTrait;
-(NSUInteger)_axPopupButtonTrait;
-(NSUInteger)_axRadioButtonTrait;
-(NSUInteger)_axSearchFieldTrait;
-(NSUInteger)_axSecureTextFieldTrait;
-(NSUInteger)_axSelectedTrait;
-(NSUInteger)_axStaticTextTrait;
-(NSUInteger)_axTabButtonTrait;
-(NSUInteger)_axTextAreaTrait;
-(NSUInteger)_axTextEntryTrait;
-(NSUInteger)_axTextOperationsAvailableTrait;
-(NSUInteger)_axToggleTrait;
-(NSUInteger)_axUpdatesFrequentlyTrait;
-(NSUInteger)_axVisitedTrait;
-(NSUInteger)_axWebContentTrait;
-(NSUInteger)accessibilityARIAColumnCount;
-(NSUInteger)accessibilityARIAColumnIndex;
-(NSUInteger)accessibilityARIARowCount;
-(NSUInteger)accessibilityARIARowIndex;
-(NSUInteger)accessibilityBlockquoteLevel;
-(NSUInteger)accessibilityColumnCount;
-(NSUInteger)accessibilityRowCount;
-(NSUInteger)accessibilityTraits;
-(id)_accessibilityArticleAncestor;
-(id)_accessibilityDescriptionListAncestor;
-(id)_accessibilityFieldsetAncestor;
-(id)_accessibilityFrameAncestor;
-(id)_accessibilityLandmarkAncestor;
-(id)_accessibilityListAncestor;
-(id)_accessibilityNextElementsWithCount:(unsigned int)arg0 ;
-(id)_accessibilityParentForSubview:(id)arg0 ;
-(id)_accessibilityPhotoDescription;
-(id)_accessibilityPreviousElementsWithCount:(unsigned int)arg0 ;
-(id)_accessibilityResolvedEditingStyles;
-(id)_accessibilityTableAncestor;
-(id)_accessibilityTreeAncestor;
-(id)_accessibilityWebDocumentView;
-(id)_accessibilityWebRoleAsString;
-(id)_stringForRange:(struct _NSRange )arg0 attributed:(BOOL)arg1 ;
-(id)_stringFromStartMarker:(id)arg0 toEndMarker:(id)arg1 attributed:(BOOL)arg2 ;
-(id)accessibilityARIALiveRegionStatus;
-(id)accessibilityARIARelevantStatus;
-(id)accessibilityBrailleLabel;
-(id)accessibilityBrailleRoleDescription;
-(id)accessibilityColorStringValue;
-(id)accessibilityContainer;
-(id)accessibilityCurrentState;
-(id)accessibilityDOMIdentifier;
-(id)accessibilityDatetimeValue;
-(id)accessibilityDetailsElements;
-(id)accessibilityElementAtIndex:(NSInteger)arg0 ;
-(id)accessibilityElementForRow:(NSInteger)arg0 andColumn:(NSInteger)arg1 ;
-(id)accessibilityElements;
-(id)accessibilityErrorMessageElements;
-(id)accessibilityExpandedTextValue;
-(id)accessibilityFindMatchingObjects:(id)arg0 ;
-(id)accessibilityFlowToElements;
-(id)accessibilityFocusedUIElement;
-(id)accessibilityHeaderElements;
-(id)accessibilityHint;
-(id)accessibilityHitTest:(struct CGPoint )arg0 ;
-(id)accessibilityIdentifier;
-(id)accessibilityImageOverlayElements;
-(id)accessibilityInvalidStatus;
-(id)accessibilityLabel;
-(id)accessibilityLanguage;
-(id)accessibilityLinkRelationshipType;
-(id)accessibilityLinkedElement;
-(id)accessibilityMathBaseObject;
-(id)accessibilityMathDenominatorObject;
-(id)accessibilityMathFencedCloseString;
-(id)accessibilityMathFencedOpenString;
-(id)accessibilityMathNumeratorObject;
-(id)accessibilityMathOverObject;
-(id)accessibilityMathPostscripts;
-(id)accessibilityMathPrescripts;
-(id)accessibilityMathRadicand;
-(id)accessibilityMathRootIndexObject;
-(id)accessibilityMathSubscriptObject;
-(id)accessibilityMathSuperscriptObject;
-(id)accessibilityMathType;
-(id)accessibilityMathUnderObject;
-(id)accessibilityObjectForTextMarker:(id)arg0 ;
-(id)accessibilityPlaceholderValue;
-(id)accessibilityPlatformMathSubscriptKey;
-(id)accessibilityPlatformMathSuperscriptKey;
-(id)accessibilityPopupValue;
-(id)accessibilityPostProcessHitTest:(struct CGPoint )arg0 ;
-(id)accessibilityRoleDescription;
-(id)accessibilitySortDirection;
-(id)accessibilitySpeechHint;
-(id)accessibilityTextualContext;
-(id)accessibilityTitleElement;
-(id)accessibilityURL;
-(id)accessibilityValue;
-(id)arrayOfTextForTextMarkers:(id)arg0 attributed:(BOOL)arg1 ;
-(id)attachmentView;
-(id)attributedStringForElement;
-(id)attributedStringForRange:(struct _NSRange )arg0 ;
-(id)description;
-(id)elementsForRange:(struct _NSRange )arg0 ;
-(id)initWithAccessibilityObject:(*void)arg0 ;
-(id)interactiveVideoDescription;
-(id)lineEndMarkerForMarker:(id)arg0 ;
-(id)lineMarkersForMarker:(id)arg0 ;
-(id)lineRectsForTextMarkerRange:(id)arg0 ;
-(id)lineStartMarkerForMarker:(id)arg0 ;
-(id)misspellingTextMarkerRange:(id)arg0 forward:(BOOL)arg1 ;
-(id)nextMarkerForMarker:(id)arg0 ;
-(id)previousMarkerForMarker:(id)arg0 ;
-(id)selectedTextMarker;
-(id)selectionRangeString;
-(id)startOrEndTextMarkerForTextMarkers:(id)arg0 isStart:(BOOL)arg1 ;
-(id)stringForRange:(struct _NSRange )arg0 ;
-(id)stringForTextMarkers:(id)arg0 ;
-(id)textMarkerForPoint:(struct CGPoint )arg0 ;
-(id)textMarkerForPosition:(NSInteger)arg0 ;
-(id)textMarkerRange;
-(id)textMarkerRangeForMarkers:(id)arg0 ;
-(id)textMarkerRangeForSelection;
-(id)textMarkerRangeFromMarkers:(id)arg0 withText:(id)arg1 ;
-(id)textMarkersForRange:(*void)arg0 ;
-(id)textRectsFromMarkers:(id)arg0 withText:(id)arg1 ;
-(struct CGPath *)_accessibilityPath;
-(struct CGPoint )_accessibilityConvertPointToViewSpace:(struct CGPoint )arg0 ;
-(struct CGPoint )_accessibilityScrollPosition;
-(struct CGPoint )accessibilityActivationPoint;
-(struct CGPoint )accessibilityClickPoint;
-(struct CGRect )_accessibilityRelativeFrame;
-(struct CGRect )_accessibilityScrollVisibleRect;
-(struct CGRect )accessibilityElementRect;
-(struct CGRect )accessibilityFrame;
-(struct CGRect )accessibilityVisibleContentRect;
-(struct CGRect )frameForRange:(struct _NSRange )arg0 ;
-(struct CGRect )frameForTextMarkers:(id)arg0 ;
-(struct CGSize )_accessibilityScrollSize;
-(struct _NSRange )_accessibilitySelectedTextRange;
-(struct _NSRange )accessibilityColumnRange;
-(struct _NSRange )accessibilityRowRange;
-(struct _NSRange )elementTextRange;
-(struct optional<WebCore::SimpleRange> )rangeForTextMarkers:(id)arg0 ;
-(struct optional<WebCore::SimpleRange> )rangeFromMarkers:(id)arg0 withText:(id)arg1 ;
-(void)_accessibilitySetFocus:(BOOL)arg0 ;
-(void)_accessibilitySetSelectedTextRange:(struct _NSRange )arg0 ;
-(void)_accessibilitySetValue:(id)arg0 ;
-(void)accessibilityDecreaseSelection:(unsigned char)arg0 ;
-(void)accessibilityDecrement;
-(void)accessibilityIncreaseSelection:(unsigned char)arg0 ;
-(void)accessibilityIncrement;
-(void)accessibilityModifySelection:(unsigned char)arg0 increase:(BOOL)arg1 ;
-(void)accessibilityMoveSelectionToMarker:(id)arg0 ;
-(void)accessibilityToggleMuteForMedia;
-(void)accessibilityVideoEnterFullscreen;
-(void)dealloc;
-(void)detach;
-(void)disableAttributeCaching;
-(void)enableAttributeCaching;
-(void)postNotification:(id)arg0 ;


@end


#endif