

#include "AXCameraTorchManagerBackgroundAdapter.h"
#include "__AXVisualAlertSBNCSoundController_super.h"
#include "AXVisualAlertSBNCSoundController.h"
#include "__AXVisualAlertSBUIFlashlightController_super.h"
#include "AXVisualAlertSBUIFlashlightController.h"
#include "__AXVisualAlertSBNCScreenController_super.h"
#include "AXVisualAlertSBNCScreenController.h"
#include "AXVisualAlertManager.h"
#include "VISAXNotificationHandler.h"
#include "AXLocalNotificationHandler.h"
#include "AXAutoForwardingLocalNotificationHandler.h"
#include "AXDistributedNotificationHandler.h"
#include "AXTelephonyNotificationHandler.h"
