// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef AXSETTINGS_H
#define AXSETTINGS_H

@class AXBaseSettings, NSMutableSet, NSMutableDictionary, NSURL, NSSet, NSArray, NSString, NSDictionary, NSData, NSNumber, NSDate, NSUUID, NSOrderedSet;


#import "AXVoiceOverActivity.h"

@interface AXSettings : AXBaseSettings {
    NSMutableSet *_migratedSwitchControlMenuItemsPreferenceKeys;
    NSMutableDictionary *_unarchivedVoiceCache;
}


@property (readonly) BOOL accessibilityEnabled;
@property (retain, nonatomic) NSURL *alexLocalAssetURL;
@property (nonatomic) BOOL allowHearingAidControlOnLockScreen;
@property (nonatomic) BOOL appValidationTestingMode;
@property (nonatomic) BOOL appleTVRemoteClickpadTapsForDirectionalNavigationEnabled;
@property BOOL applicationAccessibilityEnabled;
@property (nonatomic) BOOL assistiveTouchActionRepeatEnabled;
@property (nonatomic) CGFloat assistiveTouchActionRepeatInterval;
@property (nonatomic) BOOL assistiveTouchAlwaysShowMenuEnabled;
@property (nonatomic) CGFloat assistiveTouchAxisSweepSpeed;
@property (retain, nonatomic) NSSet *assistiveTouchCameraPointPickerSwitches;
@property (nonatomic) BOOL assistiveTouchCameraSwitchPreviewEnabled;
@property (nonatomic) NSInteger assistiveTouchCursorColor;
@property (retain, nonatomic) NSArray *assistiveTouchCustomGestures;
@property (nonatomic) CGFloat assistiveTouchDelayAfterInput;
@property (nonatomic) BOOL assistiveTouchDelayAfterInputEnabled;
@property (retain, nonatomic) NSString *assistiveTouchDoubleTapAction;
@property (nonatomic) CGFloat assistiveTouchDoubleTapActionTimeout;
@property BOOL assistiveTouchEnabled;
@property (readonly, nonatomic) NSDictionary *assistiveTouchEyeTrackerCustomizedSettings;
@property (nonatomic) BOOL assistiveTouchGameControllerEnabled;
@property (nonatomic) BOOL assistiveTouchGroupElementsEnabled;
@property BOOL assistiveTouchHardwareEnabled;
@property (nonatomic) NSInteger assistiveTouchHeadMovementSensitivity;
@property (nonatomic) CGFloat assistiveTouchIdleOpacity;
@property (nonatomic) CGFloat assistiveTouchInputCoalescingDuration;
@property (nonatomic) BOOL assistiveTouchInputCoalescingEnabled;
@property (nonatomic) CGFloat assistiveTouchInputHoldDuration;
@property (nonatomic) BOOL assistiveTouchInputHoldEnabled;
@property (nonatomic) BOOL assistiveTouchInternalOnlyHiddenNubbitModeEnabled; // ivar: _assistiveTouchInternalOnlyHiddenNubbitModeEnabled
@property (nonatomic) BOOL assistiveTouchInternalOnlyPearlTrackingEnabled;
@property (retain, nonatomic) NSString *assistiveTouchLongPressAction;
@property (nonatomic) CGFloat assistiveTouchLongPressActionDuration;
@property (nonatomic) CGFloat assistiveTouchLongPressDuration;
@property (nonatomic) BOOL assistiveTouchLongPressEnabled;
@property (nonatomic) BOOL assistiveTouchLongPressPauseScanningEnabled;
@property (retain, nonatomic) NSDictionary *assistiveTouchMainScreenCustomization;
@property (readonly, nonatomic) NSDictionary *assistiveTouchMainScreenDefaultCustomization;
@property (nonatomic) BOOL assistiveTouchMotionTrackerConfigurable;
@property (nonatomic) BOOL assistiveTouchMotionTrackerShouldOffsetBufferPoints; // ivar: _assistiveTouchMotionTrackerShouldOffsetBufferPoints
@property (nonatomic) NSUInteger assistiveTouchMotionTrackerSmoothingBufferSize;
@property (nonatomic) CGFloat assistiveTouchMotionTrackerSmoothingMaxDelta;
@property (nonatomic) CGFloat assistiveTouchMotionTrackerXNormalizationOffset;
@property (nonatomic) CGFloat assistiveTouchMotionTrackerXNormalizationOrder;
@property (nonatomic) CGFloat assistiveTouchMotionTrackerYNormalizationOffset;
@property (nonatomic) CGFloat assistiveTouchMotionTrackerYNormalizationOrder;
@property (nonatomic) BOOL assistiveTouchMouseAllowAppleBluetoothDevicesPairing;
@property (nonatomic) BOOL assistiveTouchMouseAlwaysShowSoftwareKeyboardEnabled;
@property (nonatomic) BOOL assistiveTouchMouseBehavesLikeFinger;
@property (readonly, nonatomic) NSArray *assistiveTouchMouseCustomizedClickActions;
@property (nonatomic) CGFloat assistiveTouchMouseDwellControlActivationTimeout;
@property (retain, nonatomic) NSString *assistiveTouchMouseDwellControlAutorevertAction;
@property (nonatomic) BOOL assistiveTouchMouseDwellControlAutorevertEnabled;
@property (retain, nonatomic) NSDictionary *assistiveTouchMouseDwellControlCornerCustomization;
@property (nonatomic) BOOL assistiveTouchMouseDwellControlEnabled;
@property (nonatomic) CGFloat assistiveTouchMouseDwellControlMovementToleranceRadius;
@property (nonatomic) BOOL assistiveTouchMouseDwellControlMutatedMenu;
@property (nonatomic) BOOL assistiveTouchMouseDwellControlShowPrompt;
@property (nonatomic) NSInteger assistiveTouchMouseKeysDelay;
@property (nonatomic) BOOL assistiveTouchMouseKeysEnabled;
@property (nonatomic) NSInteger assistiveTouchMouseKeysMaxSpeed;
@property (nonatomic) BOOL assistiveTouchMouseKeysOptionToggleEnabled;
@property (nonatomic) BOOL assistiveTouchMouseKeysUseMainKeyboardKeys;
@property (nonatomic) NSInteger assistiveTouchMousePointerColor;
@property (nonatomic) CGFloat assistiveTouchMousePointerSizeMultiplier;
@property (nonatomic) CGFloat assistiveTouchMousePointerTimeout;
@property (nonatomic) BOOL assistiveTouchMousePointerTimeoutEnabled;
@property (nonatomic) NSUInteger assistiveTouchMouseZoomPanningStyle;
@property (nonatomic) BOOL assistiveTouchOpenMenuSwaggleEnabled;
@property (retain, nonatomic) NSString *assistiveTouchOrbAction;
@property (nonatomic) NSInteger assistiveTouchPreferredPointPicker;
@property (retain, nonatomic) NSArray *assistiveTouchRecentGestures;
@property (retain, nonatomic) NSArray *assistiveTouchSavedGestures;
@property (nonatomic) NSInteger assistiveTouchScanCycles;
@property (nonatomic) CGFloat assistiveTouchScanTimeout;
@property (nonatomic) BOOL assistiveTouchScanTimeoutEnabled;
@property (nonatomic) BOOL assistiveTouchScannerAddedTripleClickAutomatically;
@property (nonatomic) BOOL assistiveTouchScannerCompactMenuEnabled;
@property (nonatomic) BOOL assistiveTouchScannerCursorHighVisibilityEnabled;
@property (nonatomic) BOOL assistiveTouchScannerMenuLabelsEnabled;
@property (nonatomic) BOOL assistiveTouchScannerSoundEnabled;
@property (nonatomic) BOOL assistiveTouchScannerSpeechEnabled;
@property (nonatomic) BOOL assistiveTouchScannerSpeechIsInterruptedByScanning;
@property (nonatomic) CGFloat assistiveTouchScannerSpeechRate;
@property (nonatomic) BOOL assistiveTouchScannerSpeechShouldSpeakTraits;
@property (nonatomic) NSInteger assistiveTouchScanningMode;
@property (retain, nonatomic) NSString *assistiveTouchSingleTapAction;
@property (nonatomic) CGFloat assistiveTouchSpeed;
@property (nonatomic) CGFloat assistiveTouchStepInterval;
@property (nonatomic) BOOL assistiveTouchSwitchUsageConfirmed;
@property (retain, nonatomic) NSSet *assistiveTouchSwitches;
@property BOOL assistiveTouchUIEnabled;
@property (copy, nonatomic) NSDictionary *assistiveTouchUsageCount;
@property CGFloat audioLeftRightBalance;
@property (nonatomic) CGFloat audiogramIngestionLastModelAccess;
@property (nonatomic) BOOL automaticAccessibilityEnabled;
@property (nonatomic) BOOL automaticAccessibilityIgnoreAppAccessibilityPreferred;
@property (nonatomic) BOOL automaticAccessibilityVisualizationsEnabled;
@property BOOL automationEnabled;
@property BOOL automationFauxCollectionViewCellsEnabled;
@property BOOL automationFauxTableViewCellsEnabled;
@property BOOL automationHitpointWarpingEnabled;
@property BOOL automationLocalizedStringLookupInfoEnabled;
@property (readonly) NSString *automationPreferredLocalization;
@property (retain, nonatomic) NSString *backTapDoubleTapAction;
@property (nonatomic) BOOL backTapEnabled;
@property (nonatomic) BOOL backTapFalsePositiveAlertsEnabled;
@property (retain, nonatomic) NSString *backTapTripleTapAction;
@property (nonatomic) NSInteger brokenHomeButtonCount;
@property BOOL buttonShapesEnabled;
@property (nonatomic) CGFloat callAudioRoutingAutoAnswerDelay;
@property (nonatomic) BOOL callAudioRoutingAutoAnswerEnabled;
@property (nonatomic) CGFloat characterFeedbackDelayDuration;
@property (nonatomic) NSInteger characterVoicesUsageCount;
@property (nonatomic) BOOL classicInvertColors;
@property (retain, nonatomic) NSArray *currentVoices;
@property (readonly, nonatomic) BOOL currentVoicesExist;
@property (retain, nonatomic) NSArray *customPronunciationSubstitutions;
@property (nonatomic) BOOL dataMigratorRequestedVoiceCacheRefresh;
@property (readonly, nonatomic) NSArray *deviceKeys;
@property (nonatomic) BOOL didResetD22Preferences;
@property (nonatomic) BOOL didTriggerSOSToday;
@property (nonatomic) CGFloat dockSize;
@property (nonatomic) BOOL enableHearingAidReporter;
@property (nonatomic) BOOL enableVoiceOverCaptions;
@property BOOL enhanceBackgroundContrastEnabled;
@property BOOL enhanceTextLegibilityEnabled;
@property BOOL enhanceTextTrackingEnabled;
@property (retain, nonatomic) NSArray *extantVoices;
@property (readonly, nonatomic) BOOL extantVoicesExist;
@property (retain, nonatomic) NSData *fullKeyboardAccessCommandMapData;
@property (nonatomic) NSInteger fullKeyboardAccessFocusRingColor;
@property (nonatomic) BOOL fullKeyboardAccessFocusRingHighContrastEnabled;
@property (nonatomic) CGFloat fullKeyboardAccessFocusRingTimeout;
@property (nonatomic) BOOL fullKeyboardAccessFocusRingTimeoutEnabled;
@property (nonatomic) BOOL fullKeyboardAccessLargeFocusRingEnabled;
@property (nonatomic) BOOL fullKeyboardAccessShouldShowDebugKeyCommandsView;
@property (nonatomic) BOOL fullKeyboardAccessShouldShowTextEditingModeInstructions;
@property (copy, nonatomic) NSString *gaxInternalSettingsActiveAppID;
@property (copy, nonatomic) NSNumber *gaxInternalSettingsActiveAppOrientation;
@property (copy, nonatomic) NSNumber *gaxInternalSettingsECID;
@property (nonatomic) BOOL gaxInternalSettingsIsActiveAppSelfLocked;
@property (retain, nonatomic) NSDate *gaxInternalSettingsLastActivationDate;
@property (retain, nonatomic) NSDate *gaxInternalSettingsLastPasscodeSetDate;
@property (copy, nonatomic) NSString *gaxInternalSettingsProductBuildVersion;
@property (retain, nonatomic) NSDictionary *gaxInternalSettingsSavedAccessibilityFeatures;
@property (retain, nonatomic) NSArray *gaxInternalSettingsSavedAccessibilityTripleClickOptions;
@property (nonatomic) BOOL gaxInternalSettingsSystemDidRestartDueToLowBattery;
@property (nonatomic) BOOL gaxInternalSettingsTimeRestrictionHasExpired;
@property (retain, nonatomic) NSDictionary *gaxInternalSettingsUserAppProfile;
@property (retain, nonatomic) NSArray *gaxInternalSettingsUserConfiguredAppIDs;
@property (retain, nonatomic) NSDictionary *gaxInternalSettingsUserGlobalProfile;
@property (readonly, nonatomic) NSArray *gestureKeys;
@property (nonatomic) BOOL gizmoApplicationAccessibilityEnabled;
@property (nonatomic) BOOL guidedAccessAXFeaturesEnabled;
@property (readonly, nonatomic) BOOL guidedAccessAllowsMultipleWindows;
@property (nonatomic) BOOL guidedAccessAllowsUnlockWithTouchID;
@property (nonatomic) NSInteger guidedAccessAutoLockTimeInSeconds;
@property (readonly, nonatomic) NSString *guidedAccessDefaultToneIdentifierForTimeRestrictionEvents;
@property (nonatomic) BOOL guidedAccessDisallowDirectInactiveToActiveTransition;
@property (nonatomic) BOOL guidedAccessEnableExperimentalUI;
@property (readonly, nonatomic) BOOL guidedAccessOverrideIdleTime;
@property (retain, nonatomic) NSNumber *guidedAccessOverrideTimeRestrictionDuration;
@property (nonatomic) BOOL guidedAccessShouldSpeakForTimeRestrictionEvents;
@property (nonatomic) NSInteger guidedAccessTimeLimitsUsageCount;
@property (copy, nonatomic) NSString *guidedAccessToneIdentifierForTimeRestrictionEvents;
@property (nonatomic) NSInteger guidedAccessUsageCount;
@property (nonatomic) NSInteger hearingAidControlPanelCount;
@property (nonatomic) NSInteger hearingAidHandOffCount;
@property BOOL highContrastFocusIndicatorsEnabled;
@property BOOL hoverTextActivationLockEnabled;
@property (copy) NSData *hoverTextBackgroundColorData;
@property CGFloat hoverTextBackgroundOpacity;
@property (copy) NSData *hoverTextBorderColorData;
@property (retain, nonatomic) NSString *hoverTextContentSize;
@property NSInteger hoverTextDisplayMode;
@property (nonatomic) BOOL hoverTextEnabled;
@property (copy) NSString *hoverTextFontName;
@property CGFloat hoverTextFontSize;
@property (copy) NSData *hoverTextInsertionPointColorData;
@property NSInteger hoverTextPreferredActivatorKey;
@property (nonatomic) NSInteger hoverTextScrollingSpeed;
@property (copy) NSData *hoverTextTextColorData;
@property (nonatomic) BOOL ignoreAXAsserts;
@property (nonatomic) BOOL ignoreAXServerEntitlements;
@property (nonatomic) NSUInteger imageCaptionGenderStrategy;
@property (copy, nonatomic) NSArray *imageCaptioningDisabledApps;
@property (nonatomic) BOOL includeBacktraceInLogs;
@property BOOL increaseButtonLegibilityEnabled;
@property (nonatomic) BOOL independentHearingAidSettings;
@property BOOL inspectorEnabled;
@property (nonatomic) NSInteger internalLoggingColorTheme;
@property (readonly, nonatomic) BOOL laserEnabled;
@property (nonatomic) NSUInteger laserZoomPanningStyle;
@property (nonatomic) CGFloat lastAssistiveTouchTimeResetCount;
@property (nonatomic) CGFloat lastBrailleScreenInputTimeResetCount;
@property (nonatomic) CGFloat lastCharacterVoiceTimeResetCount;
@property (nonatomic) CGFloat lastGuidedAccessTimeLimitResetCount; // ivar: _lastGuidedAccessTimeLimitResetCount
@property (nonatomic) CGFloat lastGuidedAccessTimeResetCount; // ivar: _lastGuidedAccessTimeResetCount
@property (nonatomic) CGFloat lastHearingAidControlPanelTimeResetCount; // ivar: _lastHearingAidControlPanelTimeResetCount
@property (nonatomic) CGFloat lastHearingAidHandoffTimeResetCount; // ivar: _lastHearingAidHandoffTimeResetCount
@property (nonatomic) CGFloat lastMagnifierResetCount;
@property (nonatomic) CGFloat lastPlatformSwitchTimeResetCount; // ivar: _lastPlatformSwitchTimeResetCount
@property (nonatomic) CGFloat lastSmartInvertColorsEnablement;
@property (nonatomic) CGFloat lastTapticTimeResetCount;
@property (nonatomic) BOOL leftRightBalanceEnabled;
@property (nonatomic) CGFloat leftRightBalanceValue;
@property (nonatomic) BOOL letterFeedbackEnabled;
@property (nonatomic) BOOL localizationQACaptionMode;
@property (nonatomic) BOOL localizationQACaptionShowFilePath;
@property (nonatomic) BOOL localizationQACaptionShowLocalizedString;
@property (nonatomic) BOOL localizationQACaptionShowUSString;
@property (nonatomic) BOOL logAXNotificationPosting;
@property (nonatomic) CGFloat magnifierBrightness;
@property (nonatomic) CGFloat magnifierContrast;
@property (nonatomic) BOOL magnifierEnabled;
@property (nonatomic) BOOL magnifierFilterInverted;
@property (nonatomic) NSUInteger magnifierFilterSetIdentifier;
@property (nonatomic) BOOL magnifierShouldAdjustFiltersForAmbientLight;
@property (nonatomic) BOOL magnifierShouldUseVideoStabilization;
@property (nonatomic) NSInteger magnifierUsageCount;
@property (nonatomic) CGFloat magnifierZoomLevel;
@property (readonly, nonatomic) NSArray *mediaControlsKeys;
@property (retain, nonatomic) NSString *medicalPreamble;
@property BOOL monoAudioEnabled;
@property (copy, nonatomic) NSArray *perAppSettingsCustomizedAppIDs;
@property (copy, nonatomic) NSDictionary *perAppSettingsStats;
@property (nonatomic) BOOL phoneticFeedbackEnabled;
@property (nonatomic) NSUInteger quickSpeakHighlightOption;
@property (nonatomic) CGPoint quickSpeakNubbitNormalizedPosition;
@property (nonatomic) NSInteger quickSpeakSentenceHighlightColor;
@property (nonatomic) NSUInteger quickSpeakSentenceHighlightOption;
@property (nonatomic) float quickSpeakSpeakingRate;
@property (nonatomic) BOOL quickSpeakUnderlineSentence;
@property (nonatomic) float quickSpeakVolume;
@property (nonatomic) NSInteger quickSpeakWordHighlightColor;
@property (nonatomic) BOOL quickTypeWordFeedbackEnabled;
@property (nonatomic) BOOL reachabilityEnabled;
@property BOOL reduceMotionAutoplayVideoPreviewsEnabled;
@property BOOL reduceMotionEnabled;
@property BOOL reduceWhitePointEnabled;
@property (nonatomic) float reduceWhitePointLevel; // ivar: _reduceWhitePointLevel
@property (retain, nonatomic) NSDictionary *remoteHandGestureCustomizedActions;
@property (readonly, nonatomic) NSArray *settingsKeys;
@property (nonatomic) BOOL shouldCaptureVisionEngineDiagnosticsToDisk;
@property (nonatomic) BOOL shouldFlashForAlertInSilentMode;
@property (nonatomic) BOOL shouldFlashWhileUnlocked;
@property (nonatomic) BOOL shouldLimitDisplayRefreshRate;
@property (nonatomic) BOOL shouldPerformValidationsAtRuntime;
@property (nonatomic) BOOL shouldSpeakMedicalPreamble;
@property (nonatomic) BOOL shouldStreamToLeftAid;
@property (nonatomic) BOOL shouldStreamToRightAid;
@property (nonatomic) BOOL shouldTTYMedicalPreamble;
@property (nonatomic) BOOL showSpeechController;
@property (nonatomic) BOOL siriAutoUpdateListInitialized;
@property BOOL siriSemanticContextEnabled;
@property (nonatomic) BOOL skipHearingAidMFiAuth;
@property (nonatomic) CGFloat soundActionsLastModelAccess;
@property (nonatomic) BOOL speakCorrectionsEnabled;
@property (nonatomic) NSInteger speechControllerDoubleTapAction;
@property (nonatomic) CGFloat speechControllerIdleOpacity;
@property (nonatomic) NSInteger speechControllerLongPressAction;
@property (retain, nonatomic) NSString *spokenContentDefaultFallbackLanguage;
@property (nonatomic) BOOL spokenContentShouldUseLanguageDetection;
@property (nonatomic) BOOL startupSoundEnabled;
@property (nonatomic) BOOL stickyKeysBeepEnabled;
@property (nonatomic) BOOL stickyKeysEnabled;
@property (nonatomic) BOOL stickyKeysShiftToggleEnabled;
@property (nonatomic) BOOL supportsAdvancedDisplayFilters;
@property (nonatomic) CGFloat switchControlAutoTapTimeout;
@property (nonatomic) CGFloat switchControlCameraPointPickerDwellActivationTimeout;
@property (nonatomic) CGFloat switchControlCameraPointPickerDwellMovementToleranceRadius;
@property (nonatomic) NSUInteger switchControlCameraPointPickerMode;
@property (nonatomic) CGFloat switchControlCameraPointPickerMovementToleranceInJoystickMode;
@property (nonatomic) CGFloat switchControlCameraPointPickerSensitivity;
@property (retain, nonatomic) NSArray *switchControlCombinedTopLevelMenuItems; // ivar: _switchControlCombinedTopLevelMenuItems
@property (retain, nonatomic) NSArray *switchControlDeviceMenuItems;
@property (retain, nonatomic) NSArray *switchControlDeviceTopLevelMenuItems;
@property (nonatomic) CGFloat switchControlDwellTime;
@property BOOL switchControlEnabled;
@property (retain, nonatomic) NSArray *switchControlGesturesMenuItems;
@property (retain, nonatomic) NSArray *switchControlGesturesTopLevelMenuItems;
@property (readonly, nonatomic) BOOL switchControlHasEmptyTopLevelMenu;
@property (nonatomic) BOOL switchControlIsEnabledAsReceiver;
@property (retain, nonatomic) NSUUID *switchControlLaunchRecipeUUID;
@property (retain, nonatomic) NSArray *switchControlMediaControlsMenuItems;
@property (retain, nonatomic) NSArray *switchControlMediaControlsTopLevelMenuItems;
@property (nonatomic) NSInteger switchControlPlatformSwitchedCount;
@property (nonatomic) NSInteger switchControlPointPickerSelectionStyle;
@property (retain, nonatomic) NSArray *switchControlRecipes;
@property (nonatomic) BOOL switchControlRestartScanningAtCurrentKey;
@property (nonatomic) NSInteger switchControlScanAfterTapLocation;
@property (nonatomic) NSInteger switchControlScanningStyle;
@property (retain, nonatomic) NSArray *switchControlSettingsMenuItems;
@property (retain, nonatomic) NSArray *switchControlSettingsTopLevelMenuItems;
@property (nonatomic) BOOL switchControlShouldAlwaysActivateKeyboardKeys;
@property (nonatomic) BOOL switchControlShouldDisallowUSBRestrictedMode;
@property (nonatomic) BOOL switchControlShouldUseExtendedKeyboardPredictions;
@property (nonatomic) BOOL switchControlShouldUseShortFirstPage;
@property (nonatomic) NSInteger switchControlTapBehavior;
@property (retain, nonatomic) NSArray *switchControlTopLevelMenuItems;
@property (nonatomic) BOOL switchControlUseCameraForPointMode;
@property (nonatomic) BOOL switchControlUserDidReadUSBRestrictedModeAlert;
@property (nonatomic) BOOL syncPronunciationsWithCloudKit;
@property (nonatomic) NSInteger tapToSpeakTimeAvailability;
@property (nonatomic) BOOL tapToSpeakTimeEnabled;
@property (nonatomic) BOOL tapticTimeInternalFlashScreenEnabled;
@property (readonly, nonatomic) BOOL tapticTimeIsAvailable;
@property (nonatomic) NSInteger tapticTimeUsageCount;
@property (nonatomic) BOOL touchAccommodationsAllowsSwipeGesturesToBypass;
@property (readonly, nonatomic) BOOL touchAccommodationsAreConfigured;
@property (nonatomic) BOOL touchAccommodationsEnabled;
@property (nonatomic) CGFloat touchAccommodationsHoldDuration;
@property (nonatomic) BOOL touchAccommodationsHoldDurationAllowsSwipeGesturesToBypass; // ivar: _touchAccommodationsHoldDurationAllowsSwipeGesturesToBypass
@property (nonatomic) BOOL touchAccommodationsHoldDurationEnabled;
@property (readonly, nonatomic) NSInteger touchAccommodationsHoldDurationSwipeGestureSensitivity;
@property (nonatomic) CGFloat touchAccommodationsIgnoreRepeatDuration;
@property (nonatomic) BOOL touchAccommodationsIgnoreRepeatEnabled;
@property (nonatomic) CGFloat touchAccommodationsSwipeGestureMinimumDistance;
@property (nonatomic) NSInteger touchAccommodationsTapActivationMethod;
@property (nonatomic) CGFloat touchAccommodationsTapActivationTimeout;
@property (nonatomic) BOOL touchAccommodationsTripleClickConfirmed;
@property (nonatomic) BOOL touchAccommodationsUsageConfirmed;
@property (retain) NSArray *tripleClickOptions;
@property (copy, nonatomic) NSArray *tripleClickOrderedOptions;
@property (nonatomic) BOOL useNewAXBundleLoader;
@property (nonatomic) BOOL validateSecondPartyApps;
@property (nonatomic) BOOL voiceOverActionFeedbackFirstInListOnly;
@property (nonatomic) NSInteger voiceOverActionsFeedback;
@property (nonatomic) NSInteger voiceOverActivationWorkaround;
@property (retain, nonatomic) NSArray *voiceOverActivities;
@property (nonatomic) BOOL voiceOverAdjustSoundVolumeIndependently;
@property (nonatomic) BOOL voiceOverAlwaysUseNemethCodeForMathEnabled;
@property (nonatomic) BOOL voiceOverAudioDuckingEnabled;
@property (nonatomic) BOOL voiceOverAudioFollowsHDMIAudio;
@property (nonatomic) BOOL voiceOverAutomaticButtonLabels;
@property (nonatomic) NSInteger voiceOverBSIUsageCount;
@property (nonatomic) CGFloat voiceOverBrailleAlertDisplayDuration;
@property (nonatomic) BOOL voiceOverBrailleAlertsEnabled;
@property (nonatomic) CGFloat voiceOverBrailleAutoAdvanceDuration;
@property (copy) NSDictionary *voiceOverBrailleBluetoothDisplay;
@property NSInteger voiceOverBrailleContractionMode;
@property BOOL voiceOverBrailleEightDotMode;
@property (readonly, nonatomic) BOOL voiceOverBrailleGesturesEnabled;
@property (nonatomic) NSInteger voiceOverBrailleGesturesTypingFeedback;
@property (nonatomic) BOOL voiceOverBrailleGradeTwoAutoTranslateEnabled;
@property (nonatomic) CGFloat voiceOverBrailleKeyDebounceTimeout;
@property (copy, nonatomic) NSArray *voiceOverBrailleLanguageRotorItems;
@property NSInteger voiceOverBrailleMasterStatusCellIndex;
@property (nonatomic) NSInteger voiceOverBrailleStatusCellPreference;
@property (copy, nonatomic) NSString *voiceOverBrailleTableIdentifier;
@property NSInteger voiceOverBrailleVirtualStatusAlignment;
@property (nonatomic) BOOL voiceOverBrailleWordWrapEnabled;
@property (nonatomic) NSInteger voiceOverCapitalLetterFeedback;
@property (nonatomic) NSInteger voiceOverContainerOutputFeedback;
@property (nonatomic) NSInteger voiceOverContentDescriptionLevel;
@property (nonatomic) CGFloat voiceOverContinuousPathKeyboardStartTimeout;
@property (retain, nonatomic) NSData *voiceOverCustomCommandProfile;
@property (copy, nonatomic) NSUUID *voiceOverDefaultPunctuationGroup;
@property (nonatomic) NSInteger voiceOverDeletionFeedback;
@property (nonatomic) NSInteger voiceOverDescribedMedia;
@property (copy, nonatomic) NSDictionary *voiceOverDirectTouchEnabledApps;
@property (nonatomic) NSInteger voiceOverDiscoveredSensitiveContentFeedback;
@property (nonatomic) CGFloat voiceOverDoubleTapInterval;
@property (nonatomic) BOOL voiceOverEditAppsActionEnabled;
@property BOOL voiceOverEnabled;
@property BOOL voiceOverEnabledThroughAccessory;
@property (nonatomic) BOOL voiceOverExploreFocusAffectsNativeFocus;
@property (nonatomic) BOOL voiceOverFlashlightNotificationsEnabled;
@property (retain, nonatomic) NSDictionary *voiceOverHandGesturesActionCustomizations;
@property (nonatomic) BOOL voiceOverHandGesturesEnabled;
@property (readonly, nonatomic) BOOL voiceOverHandwritingEnabled;
@property (retain, nonatomic) NSNumber *voiceOverHandwritingWasNativeAutocorrectEnabled;
@property (nonatomic) CGFloat voiceOverHapticIntensity;
@property (nonatomic) BOOL voiceOverHapticsEnabled;
@property (nonatomic) NSInteger voiceOverHardwareTypingFeedback;
@property (nonatomic) BOOL voiceOverHearingAidRoutingEnabled;
@property (nonatomic) NSInteger voiceOverHelpMode;
@property (nonatomic) BOOL voiceOverHintsEnabled;
@property (nonatomic) BOOL voiceOverImageCaptionsEnabled;
@property (nonatomic) NSInteger voiceOverKeyboardModifierChoice;
@property (nonatomic) BOOL voiceOverLanguageDetectionEnabled;
@property (retain) NSArray *voiceOverLanguageRotorItems;
@property (readonly) BOOL voiceOverLanguageRotorItemsExist;
@property (nonatomic) BOOL voiceOverLargeCursorEnabled;
@property (nonatomic) NSInteger voiceOverLinkFeedback;
@property (nonatomic) NSInteger voiceOverMoreContentOutputFeedback;
@property (nonatomic) NSInteger voiceOverNavigateImagesOption;
@property (nonatomic) NSInteger voiceOverNavigationDirectionMode;
@property (nonatomic) NSInteger voiceOverNavigationStyle;
@property (nonatomic) NSInteger voiceOverNeuralElementFeedback;
@property (nonatomic) NSInteger voiceOverNumberFeedback;
@property (nonatomic) NSInteger voiceOverPhoneticsFeedback;
@property (nonatomic) CGFloat voiceOverPitch;
@property (nonatomic) BOOL voiceOverPitchChangeEnabled;
@property (nonatomic) NSInteger voiceOverPreferredTVInteractionMode;
@property (nonatomic) BOOL voiceOverPrefersFollowFocusNavigationStyle;
@property (copy, nonatomic) NSUUID *voiceOverPunctuationGroup;
@property (nonatomic) NSInteger voiceOverPunctuationLevel;
@property (nonatomic) NSInteger voiceOverQuickNavAnnouncementFeedback;
@property (copy, nonatomic) NSArray *voiceOverQuickSettingsItems;
@property (copy, nonatomic) NSArray *voiceOverRotorItems;
@property (nonatomic) NSInteger voiceOverRotorSummaryFeedback;
@property (nonatomic) BOOL voiceOverSceneDescriptionsEnabled;
@property BOOL voiceOverScreenCurtainEnabled;
@property (retain, nonatomic) AXVoiceOverActivity *voiceOverSelectedActivity;
@property (retain, nonatomic) NSString *voiceOverSelectedLanguage;
@property (nonatomic) BOOL voiceOverShouldDisallowUSBRestrictedMode;
@property (nonatomic) BOOL voiceOverShouldOutputToHearingAid;
@property (nonatomic) BOOL voiceOverShouldSpeakDiscoveredText;
@property (readonly, nonatomic) BOOL voiceOverShowBrailleWatchSettings;
@property (nonatomic) BOOL voiceOverShowSoftwareKeyboardWithBraille;
@property (nonatomic) BOOL voiceOverSilenceAnnouncements;
@property (nonatomic) NSInteger voiceOverSoftwareTypingFeedback;
@property (retain, nonatomic) NSDictionary *voiceOverSoundAndHapticPreferences;
@property (nonatomic) BOOL voiceOverSoundEffectsEnabled;
@property (nonatomic) CGFloat voiceOverSoundVolume;
@property (nonatomic) BOOL voiceOverSpeakActionConfirmation;
@property (nonatomic) BOOL voiceOverSpeakNonfocusableElementsAfterDelay;
@property (nonatomic) BOOL voiceOverSpeakNotificationsEnabled;
@property (nonatomic) NSInteger voiceOverSpeakSecondsEncoding;
@property (nonatomic) BOOL voiceOverSpeakTableColumnRowInformation;
@property (nonatomic) BOOL voiceOverSpeakTableHeaders;
@property float voiceOverSpeakingRate;
@property (nonatomic) BOOL voiceOverSpeakingRateInRotorEnabled;
@property (nonatomic) BOOL voiceOverSpeaksOverTelephoneCalls;
@property (nonatomic) NSInteger voiceOverTapticChimesAvailability;
@property (nonatomic) BOOL voiceOverTapticChimesEnabled;
@property (nonatomic) NSInteger voiceOverTapticChimesFrequencyEncoding;
@property (nonatomic) NSInteger voiceOverTapticChimesSoundType;
@property (nonatomic) NSInteger voiceOverTapticTimeEncoding;
@property (nonatomic) BOOL voiceOverTapticTimeMode;
@property (nonatomic) float voiceOverTapticTimeSpeed;
@property (nonatomic) NSInteger voiceOverTouchBrailleDisplayInputMode;
@property (nonatomic) NSInteger voiceOverTouchBrailleDisplayOutputMode;
@property (nonatomic) BOOL voiceOverTouchBrailleGesturesDidPlayCalibrationHint;
@property (nonatomic) NSInteger voiceOverTouchBrailleGesturesInputMode;
@property (nonatomic) NSInteger voiceOverTouchBrailleGesturesLockedOrientation;
@property (nonatomic) NSInteger voiceOverTouchBrailleGesturesLockedTypingMode;
@property (nonatomic) BOOL voiceOverTouchBrailleGesturesShouldUseLockedConfiguration;
@property (nonatomic) BOOL voiceOverTouchBraillePanningAutoTurnsReadingContent;
@property (nonatomic) BOOL voiceOverTouchBrailleShouldReverseDots;
@property (nonatomic) BOOL voiceOverTouchBrailleShowGeneralStatus;
@property (nonatomic) BOOL voiceOverTouchBrailleShowTextStyleStatus;
@property (copy) NSString *voiceOverTouchBrailleTableIdentifier;
@property (nonatomic) BOOL voiceOverTouchSingleLetterQuickNavEnabled;
@property (nonatomic) BOOL voiceOverTouchUpdateBrailleWithoutConnectedDisplay;
@property int voiceOverTypingMode;
@property BOOL voiceOverUIEnabled;
@property BOOL voiceOverUsageConfirmed;
@property (nonatomic) BOOL voiceOverUseActiveSiriVoice;
@property (nonatomic) BOOL voiceOverUseDigitalCrownNavigation;
@property (nonatomic) BOOL voiceOverUseTVToggleStyleNavigation;
@property (nonatomic) BOOL voiceOverUserDidReadUSBRestrictedModeAlert;
@property (nonatomic) NSInteger voiceOverVerbosityEmojiFeedback;
@property (nonatomic) BOOL voiceOverVerbosityEmojiSuffixEnabled;
@property (nonatomic) BOOL voiceOverVerbositySpeakCustomActionsHint; // ivar: _voiceOverVerbositySpeakCustomActionsHint
@property float voiceOverVolume;
@property (nonatomic) BOOL wordFeedbackEnabled;
@property (nonatomic) BOOL writeAXLogsToFile; // ivar: _writeAXLogsToFile
@property (nonatomic) BOOL zoomAdjustZoomLevelKbShortcutEnabled;
@property (nonatomic) BOOL zoomAlwaysUseWindowedZoomForTyping;
@property (nonatomic) BOOL zoomAutopannerShouldPanWithAcceleration;
@property (nonatomic) NSInteger zoomControllerColor;
@property (retain, nonatomic) NSString *zoomCurrentLensEffect;
@property (retain, nonatomic) NSString *zoomCurrentLensMode;
@property (nonatomic) BOOL zoomDebugDisableZoomLensScaleTransform;
@property (nonatomic) BOOL zoomDebugShowExternalFocusRect;
@property BOOL zoomEnabled;
@property (retain, nonatomic) NSDictionary *zoomHandGesturesActionCustomizations;
@property (nonatomic) BOOL zoomHandGesturesEnabled;
@property (nonatomic) CGFloat zoomIdleSlugOpacity;
@property (nonatomic) BOOL zoomInStandby;
@property (nonatomic) BOOL zoomKeyboardShortcutsEnabled;
@property (nonatomic) CGPoint zoomPanOffset;
@property (nonatomic) BOOL zoomPanZoomKbShortcutEnabled;
@property (nonatomic) BOOL zoomPeekZoomEnabled;
@property (nonatomic) BOOL zoomPeekZoomEverEnabled;
@property (nonatomic) BOOL zoomPreferencesWereInitialized;
@property (retain, nonatomic) NSString *zoomPreferredCurrentDockPosition;
@property (retain, nonatomic) NSString *zoomPreferredCurrentLensMode;
@property (retain, nonatomic) NSOrderedSet *zoomPreferredDockPositions;
@property (retain, nonatomic) NSOrderedSet *zoomPreferredLensModes;
@property (nonatomic) CGFloat zoomPreferredMaximumZoomScale;
@property (nonatomic) BOOL zoomResizeZoomWindowKbShortcutEnabled;
@property (nonatomic) CGFloat zoomScale;
@property (nonatomic) BOOL zoomScrollWheelKbShortcutEnabled;
@property (nonatomic) BOOL zoomShouldAllowFullscreenAutopanning;
@property (nonatomic) BOOL zoomShouldFollowFocus;
@property (nonatomic) BOOL zoomShouldShowSlug;
@property (nonatomic) BOOL zoomShowedBanner;
@property (nonatomic) NSInteger zoomSlugDoubleTapAction;
@property (nonatomic) CGPoint zoomSlugNormalizedPosition;
@property (nonatomic) NSInteger zoomSlugSingleTapAction;
@property (nonatomic) BOOL zoomSlugTapAndSlideToAdjustZoomLevelEnabled;
@property (nonatomic) NSInteger zoomSlugTripleTapAction;
@property BOOL zoomSmoothScalingEnabled;
@property (nonatomic) BOOL zoomSwitchZoomModeKbShortcutEnabled;
@property (nonatomic) BOOL zoomTempToggleZoomKbShortcutEnabled;
@property (nonatomic) BOOL zoomToggleZoomKbShortcutEnabled;
@property BOOL zoomToggledByPreferenceSwitch;
@property BOOL zoomToggledByVoiceOver;
@property (nonatomic) CGRect zoomWindowFrame;


+(id)sharedInstance;
-(BOOL)_hasSwitchWithUUID:(id)arg0 ;
-(BOOL)_switchControlHasEmptyTopLevelMenuItems:(id)arg0 ;
-(BOOL)_updateWithoutSavingExistingRecipe:(id)arg0 allRecipes:(id)arg1 ;
-(BOOL)_voiceOverRotorItemEnabled:(id)arg0 ;
-(BOOL)anyUserPreferredLangaugeIsRTL;
-(BOOL)assistiveTouchAutoScanningEnabled;
-(BOOL)assistiveTouchCustomizationEnabled;
-(BOOL)assistiveTouchInternalOnlyHiddenNubbitMode;
-(BOOL)assistiveTouchScannerPrefersCompact:(id)arg0 ;
-(BOOL)didTriggerSOSValueSet;
-(BOOL)gizmoGetAutoSpeakEnabledForComplication:(id)arg0 slot:(id)arg1 face:(id)arg2 ;
-(BOOL)isNewRecipe:(id)arg0 ;
-(BOOL)updateRecipe:(id)arg0 ;
-(BOOL)userDidSelectVoiceForLanguage:(id)arg0 source:(NSInteger)arg1 ;
-(BOOL)validateAndUpdateRecipeIfNeeded:(id)arg0 ;
-(NSInteger)automaticAccessibilityModeForBundleIdentifier:(id)arg0 ;
-(float)quickSpeakSpeakingRateForLanguage:(id)arg0 ;
-(float)voiceOverSpeakingRateForLanguage:(id)arg0 ;
-(id)_allSubmenuKeys;
-(id)_audioHardwareChannelLayout;
-(id)_createAndSaveRecipeForInterfaceOrientedPoint:(struct CGPoint )arg0 forHold:(BOOL)arg1 ;
-(id)_gesturesForPreferenceKeyMigratingIfNecessary:(id)arg0 ;
-(id)_legacyIdentifierForEyeTracker:(id)arg0 ;
-(id)_migratePreferenceIfNecessary:(id)arg0 ;
-(id)_quickSpeakAltVoices;
-(id)_quickSpeakPrefersCompact;
-(id)_retrieveVoices:(id)arg0 ;
-(id)_switchControlAltVoices;
-(id)_switchControlMenuItemPreferences;
-(id)_switchControlMenuItemsForPreferenceKey:(id)arg0 allTypes:(id)arg1 enabledByDefault:(BOOL)arg2 topLevel:(BOOL)arg3 ;
-(id)_switchControlMigratePreMonarchIncludedMenuItemsForNewTypes:(id)arg0 ;
-(id)_switchControlPrefersCompact;
-(id)_switchControlScannerDefaultDialect;
-(id)_switchWithAction:(NSInteger)arg0 excludedUUIDs:(id)arg1 needsToSupportLongPress:(BOOL)arg2 ;
-(id)_switchWithAnyActionExcludingUUIDs:(id)arg0 needsToSupportLongPress:(BOOL)arg1 ;
-(id)_voiceOverAlternativeVoiceIdentifiers;
-(id)_voiceOverDefaultDialect;
-(id)_voiceOverPrefersCompactByLanguage;
-(id)_voiceOverSoundOrHapticValueForPreference:(id)arg0 outputEvent:(id)arg1 ;
-(id)_voiceOverTouchSpeakingRateLanguages;
-(id)allDomainNamesForPreferenceKey:(id)arg0 ;
-(id)automaticAccessibilityModes;
-(id)createAndSaveRecipeForInterfaceOrientedHoldPoint:(struct CGPoint )arg0 ;
-(id)createAndSaveRecipeForInterfaceOrientedPoint:(struct CGPoint )arg0 ;
-(id)domainNameForPreferenceKey:(id)arg0 ;
-(id)gizmoGetWatchFaceAutoSpeakPreferences;
-(id)init;
-(id)keysToIgnoreDuringBuddyTransfer;
-(id)preferenceKeyForSelector:(SEL)arg0 ;
-(id)preferredBrailleTableIdentifierForKeyboardLanguage:(id)arg0 keyboardLayout:(id)arg1 ;
-(id)programmingActivity;
-(id)selectedSpeechVoiceIdentifiers;
-(id)selectedSpeechVoiceIdentifiersForSource:(NSInteger)arg0 ;
-(id)selectedSpeechVoiceIdentifiersWithLanguageSource;
-(id)smoothingBufferSizeForEyeTracker:(id)arg0 ;
-(id)speechVoiceIdentifierForLanguage:(id)arg0 source:(NSInteger)arg1 exists:(*BOOL)arg2 ;
-(id)speechVoiceIdentifierForLanguageWithoutFallback:(id)arg0 source:(NSInteger)arg1 ;
-(id)switchForUUID:(id)arg0 ;
-(id)testingExtantVoices;
-(id)topLevelKeys;
-(id)valueForPreferenceKey:(id)arg0 ;
-(id)voiceOverAlternativeVoiceIdentifier:(id)arg0 ;
-(id)voiceOverHapticEnabledForEvent:(id)arg0 ;
-(id)voiceOverSoundEnabledForEvent:(id)arg0 ;
-(id)voiceOverTouchPreferredBrailleTableIdentifiers;
-(int)_domainForPreferenceKey:(id)arg0 ;
-(struct __CFString *)_domainNameForDomain:(int)arg0 ;
-(void)_assignDefaultTitleIfNeededToRecipe:(id)arg0 ;
-(void)_clearWhitetailMigrationSettings;
-(void)_handleVoiceUnarchivedCache:(id)arg0 ;
-(void)_listenForAccessibilitySupportPassthroughs;
-(void)_localeChange:(id)arg0 ;
-(void)_removeSpeakingRatePreferenceForLanguage:(id)arg0 ;
-(void)_setAudioHardwareChannelLayout:(id)arg0 ;
-(void)_setGestures:(id)arg0 forPreferenceKey:(id)arg1 ;
-(void)_setVoiceArray:(id)arg0 forKey:(id)arg1 ;
-(void)_switchControlClearMenuItemMigrationTracking;
-(void)_switchControlClearMenuItemPreferences;
-(void)_updateTouchAccommodationsTripleClickSetting;
-(void)_voiceOverSetSoundOrHapticValue:(id)arg0 forPreference:(id)arg1 outputEvent:(id)arg2 ;
-(void)addCustomizedAppID:(id)arg0 ;
-(void)addRotorOptionsForLoginSession;
-(void)aggregatePerAppSettingsStatistics;
-(void)assistiveTouchMotionTrackerShouldOffsetBufferPoints:(BOOL)arg0 ;
-(void)clearVoicePrefersCompactSettings;
-(void)configureZoomForLoginSession;
-(void)gizmoSetAutoSpeakEnabledForComplication:(id)arg0 slot:(id)arg1 face:(id)arg2 toggle:(BOOL)arg3 ;
-(void)nukeAll;
-(void)nukePrefsForDomains:(*int)arg0 numDomains:(NSUInteger)arg1 ;
-(void)removeCustomizedAppID:(id)arg0 ;
-(void)saveRecipe:(id)arg0 ;
-(void)setAssistiveTouchScannerPrefersCompact:(BOOL)arg0 forLanguage:(id)arg1 ;
-(void)setAutomaticAccessibilityMode:(NSInteger)arg0 forBundleIdentifier:(id)arg1 ;
-(void)setAutomaticAccessibilityModes:(id)arg0 ;
-(void)setPreferredBrailleTableIdentifier:(id)arg0 forKeyboardLanguage:(id)arg1 keyboardLayout:(id)arg2 ;
-(void)setSelectedSpeechVoiceIdentifiersWithLanguageSource:(id)arg0 ;
-(void)setSpeechVoiceIdentifier:(id)arg0 forLanguage:(id)arg1 source:(NSInteger)arg2 ;
-(void)setTestingExtantVoices:(id)arg0 ;
-(void)setUserDidSelectVoiceForLanguage:(id)arg0 source:(NSInteger)arg1 ;
-(void)setVoiceOverAlternativeVoiceIdentifier:(id)arg0 forLanguage:(id)arg1 ;
-(void)setVoiceOverTouchPreferredBrailleTableIdentifiers:(id)arg0 ;
-(void)setlastGuidedAccessTimeLimitResetCount:(CGFloat)arg0 ;
-(void)setlastGuidedAccessTimeResetCount:(CGFloat)arg0 ;
-(void)setlastHearingAidControlPanelTimeResetCount:(CGFloat)arg0 ;
-(void)setlastHearingAidHandoffTimeResetCount:(CGFloat)arg0 ;
-(void)setlastPlatformSwitchTimeResetCount:(CGFloat)arg0 ;
-(void)updateCustomizableMouse:(id)arg0 ;
-(void)updateSmoothingBufferSize:(id)arg0 forEyeTracker:(id)arg1 ;
-(void)voiceOverResetSoundAndHapticPreferences;
-(void)voiceOverSetHapticEnabled:(BOOL)arg0 forEvent:(id)arg1 ;
-(void)voiceOverSetSoundEnabled:(BOOL)arg0 forEvent:(id)arg1 ;
-(void)willPerformUpdateBlocksForPreferenceKey:(id)arg0 ;
-(void)willPostNotificationForPreferenceKey:(id)arg0 value:(id)arg1 ;
-(void)zoomUserHadLegacyZoomEnabled:(*BOOL)arg0 wasZoomedIn:(*BOOL)arg1 withScale:(*CGFloat)arg2 ;


@end


#endif