// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef PLMANAGEDASSET_H
#define PLMANAGEDASSET_H

@class NSString, NSDate, NSSet, NSArray, NSURL, CLLocation, NSError, NSNumber, NSData, NSDictionary, NSManagedObjectID, NSOrderedSet;
@protocol PLPTPTransferableAsset, PLSyncableAsset, PLCreateFromSearchableItem, PLValidatesResourceModel, PLCloudDeletable, PLMomentAssetData, _PLImageLoadingAsset, _PLThumbnailLoadingAsset, PLDeletableManagedObject, PLAssetDateDescriptor, PLCloudSharedAlbumProtocol, PLPhotosHighlightData, PLPTPTransferableAdditionalAssetAttributes, PLPTPTransferableSidecarFile, NSCopying;

#import <Foundation/Foundation.h>

#import "PLManagedObject.h"
#import "PLAdditionalAssetAttributes.h"
#import "PLManagedAssetID.h"
#import "PLCloudFeedAssetsEntry.h"
#import "PLComputedAssetAttributes.h"
#import "PLConversation.h"
#import "PLManagedAlbum.h"
#import "PLExtendedAttributes.h"
#import "PLFaceCrop.h"
#import "PLImportSession.h"
#import "PLLibraryScope.h"
#import "PLRevGeoLocationInfo.h"
#import "PLCloudMaster.h"
#import "PLMediaAnalysisAssetAttributes.h"
#import "PLMoment.h"
#import "PLMomentShare.h"
#import "PLManagedAsset.h"
#import "PLPhotoAnalysisAssetAttributes.h"
#import "PLRevGeoPlaceAnnotation.h"
#import "PLShareParticipant.h"

@interface PLManagedAsset : PLManagedObject <PLPTPTransferableAsset, PLSyncableAsset, PLCreateFromSearchableItem, PLValidatesResourceModel, PLCloudDeletable, PLMomentAssetData, _PLImageLoadingAsset, _PLThumbnailLoadingAsset, PLDeletableManagedObject, PLAssetDateDescriptor>

 {
    BOOL _didPrepareForDeletion;
    BOOL _isRegisteredForChanges;
    BOOL _didLoadReverseGeo;
    BOOL _isLocatedAtHome;
    BOOL _setCustomCreationDate;
    BOOL _setCustomLocation;
    NSString *_reverseGeoDescription;
    BOOL _deleteReasonExists;
    NSInteger _width;
    NSInteger _height;
    CLLocationCoordinate2D _cachedCoordinate;
    BOOL _isCoordinateCached;
    NSDate *_cachedDateCreated;
    NSDate *_cachedLocalDateCreated;
}


@property (nonatomic) unsigned char RAWBadgeAttribute;
@property (retain, nonatomic) NSString *accessibilityDescription;
@property (nonatomic) short activeLibraryScopeParticipationState;
@property (retain, nonatomic) NSDate *addedDate;
@property (retain, nonatomic) PLAdditionalAssetAttributes *additionalAttributes;
@property (readonly, nonatomic) NSDate *adjustmentTimestamp;
@property (retain, nonatomic) NSSet *albumOrders;
@property (retain, nonatomic) NSSet *albums;
@property (retain, nonatomic) NSSet *albumsBeingCustomKeyAssetFor;
@property (retain, nonatomic) NSSet *albumsBeingKeyAssetFor;
@property (retain, nonatomic) NSSet *albumsBeingSecondaryKeyAssetFor;
@property (retain, nonatomic) NSSet *albumsBeingTertiaryKeyAssetFor;
@property (readonly, copy, nonatomic) NSSet *allFileURLs;
@property (readonly, copy, nonatomic) NSArray *allUniformTypeIdentifiers;
@property (retain, nonatomic) NSDate *analysisStateModificationDate;
@property (retain, nonatomic) NSSet *analysisStates;
@property (retain, nonatomic) PLManagedAssetID *assetID; // ivar: _assetID
@property (readonly, nonatomic) NSURL *assetURL;
@property (readonly, nonatomic) int avalanchePickType;
@property (nonatomic) int avalanchePickType;
@property (readonly, copy, nonatomic) NSString *avalancheUUID;
@property (retain, nonatomic) NSString *avalancheUUID;
@property (retain, nonatomic) id *boundedByRect;
@property (nonatomic) unsigned short bundleScope;
@property (retain, nonatomic) CLLocation *cachedLocation; // ivar: _cachedLocation
@property (retain, nonatomic) NSURL *cachedNonPersistedVideoPlaybackURL; // ivar: cachedNonPersistedVideoPlaybackURL
@property (retain, nonatomic) NSError *cachedNonPersistedVideoPlaybackURLError; // ivar: cachedNonPersistedVideoPlaybackURLError
@property (retain, nonatomic) NSDate *cachedNonPersistedVideoPlaybackURLExpiration; // ivar: cachedNonPersistedVideoPlaybackURLExpiration
@property (nonatomic) unsigned short cameraProcessingAdjustmentState;
@property (readonly, nonatomic) NSInteger cameraProcessingAdjustmentTrashedState;
@property (readonly, nonatomic) BOOL canPlayPhotoIris;
@property (retain, nonatomic) NSString *cloudAssetGUID;
@property (readonly, retain, nonatomic) NSString *cloudAssetGUID;
@property (retain, nonatomic) NSString *cloudBatchID;
@property (retain, nonatomic) NSDate *cloudBatchPublishDate;
@property (retain, nonatomic) NSString *cloudCollectionGUID;
@property (retain, nonatomic) NSSet *cloudComments;
@property (readonly, nonatomic) NSUInteger cloudCommentsCount;
@property (nonatomic) short cloudDeleteState;
@property (readonly) NSInteger cloudDeletionType;
@property (retain, nonatomic) NSNumber *cloudDownloadRequests;
@property (retain, nonatomic) PLCloudFeedAssetsEntry *cloudFeedAssetsEntry;
@property (nonatomic) BOOL cloudHasCommentsByMe;
@property (nonatomic) BOOL cloudHasCommentsConversation;
@property (nonatomic) BOOL cloudHasUnseenComments;
@property (readonly, retain, nonatomic) NSString *cloudIdentifier;
@property (nonatomic) BOOL cloudIsDeletable;
@property (nonatomic) BOOL cloudIsMyAsset;
@property (retain, nonatomic) NSDate *cloudLastViewedCommentDate;
@property (nonatomic) short cloudLocalState;
@property (nonatomic) short cloudLocalState;
@property (readonly, nonatomic) NSString *cloudOwnerDisplayName;
@property (readonly, nonatomic) NSString *cloudOwnerEmail;
@property (readonly, nonatomic) NSString *cloudOwnerFirstName;
@property (readonly, nonatomic) NSString *cloudOwnerFullName;
@property (retain, nonatomic) NSString *cloudOwnerHashedPersonID;
@property (readonly, nonatomic) NSString *cloudOwnerLastName;
@property (readonly, nonatomic) BOOL cloudPhotoLibraryEnabled;
@property (nonatomic) short cloudPlaceholderKind;
@property (retain, nonatomic) NSDate *cloudServerPublishDate;
@property (readonly, weak, nonatomic) NSObject<PLCloudSharedAlbumProtocol> *cloudShareAlbum;
@property (readonly, copy) NSString *cloudUUIDForDeletion;
@property (nonatomic) BOOL complete;
@property (retain, nonatomic) PLComputedAssetAttributes *computedAttributes;
@property (retain, nonatomic) PLConversation *conversation;
@property (readonly, nonatomic) CLLocationCoordinate2D coordinate;
@property (nonatomic) CGFloat curationScore;
@property (readonly, copy, nonatomic) NSDate *dateCreated;
@property (retain, nonatomic) NSDate *dateCreated;
@property (readonly, copy, nonatomic) NSDate *dateForComparingAdjustmentVersions;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *dayGroupHighlightBeingAssets;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *dayGroupHighlightBeingExtendedAssets;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *dayGroupHighlightBeingKeyAssetPrivate;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *dayGroupHighlightBeingKeyAssetShared;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *dayGroupHighlightBeingSummaryAssets;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) unsigned short deferredProcessingNeeded;
@property (nonatomic) unsigned short deferredProcessingNeeded;
@property (retain, nonatomic) NSString *deleteReason;
@property (nonatomic) short depthType;
@property (readonly, nonatomic) short derivedCameraCaptureDevice;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (retain, nonatomic) NSSet *destinationAssetsForDuplication;
@property (retain, nonatomic) NSSet *detectedFaces;
@property (retain, nonatomic) NSSet *detectedFaces;
@property (retain, nonatomic) NSString *directory;
@property (nonatomic) BOOL disableDupeAnalysis; // ivar: _disableDupeAnalysis
@property (nonatomic) BOOL disableFileSystemPersistency; // ivar: _disableFileSystemPersistency
@property (nonatomic) short duplicateAssetVisibilityState;
@property (retain, nonatomic) PLManagedAlbum *duplicateMetadataMatchingAlbum;
@property (retain, nonatomic) PLManagedAlbum *duplicatePerceptualMatchingAlbum;
@property (readonly, nonatomic) CGFloat duration;
@property (nonatomic) CGFloat duration;
@property (retain, nonatomic) NSString *editorBundleID;
@property NSUInteger effectiveThumbnailIndex;
@property (readonly, retain, nonatomic) NSData *embeddedThumbnailData;
@property (nonatomic) short embeddedThumbnailHeight;
@property (nonatomic) int embeddedThumbnailLength;
@property (nonatomic) int embeddedThumbnailOffset;
@property (readonly, nonatomic) int embeddedThumbnailOffset;
@property (nonatomic) short embeddedThumbnailWidth;
@property (retain, nonatomic) PLExtendedAttributes *extendedAttributes;
@property (readonly, nonatomic) id *faceAdjustmentVersion;
@property (retain, nonatomic) id *faceAdjustmentVersion;
@property (nonatomic) NSInteger faceAreaPoints;
@property (retain, nonatomic) PLFaceCrop *faceCrop;
@property (retain, nonatomic) NSSet *faceCrops;
@property (readonly, nonatomic) BOOL faceDetectionComplete;
@property (retain, nonatomic) NSData *faceRegions;
@property (nonatomic) BOOL favorite;
@property (readonly, copy, nonatomic) NSString *fileExtension;
@property (readonly, copy, nonatomic) NSSet *filePathsWithoutThumbs;
@property (readonly, copy, nonatomic) NSURL *fileURLForLargeThumbnailFile;
@property (readonly, copy, nonatomic) NSURL *fileURLForThumbnailFile;
@property (readonly, copy, nonatomic) NSString *filename;
@property (retain, nonatomic) NSString *filename;
@property (readonly, nonatomic) CLLocationCoordinate2D gpsCoordinate;
@property (readonly, nonatomic) CGFloat gpsHorizontalAccuracy;
@property (readonly, nonatomic) BOOL hasAdjustedVideoComplement;
@property (readonly, nonatomic) BOOL hasAdjustments;
@property (nonatomic) BOOL hasAdjustments;
@property (readonly, nonatomic) BOOL hasChanges;
@property (readonly, nonatomic) BOOL hasLibraryScope;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (retain, nonatomic) NSNumber *hdrGain;
@property (nonatomic) short hdrType;
@property (readonly, nonatomic) NSInteger height;
@property (readonly, nonatomic) NSInteger height;
@property (nonatomic) NSInteger height;
@property (nonatomic) BOOL hidden;
@property (nonatomic) unsigned short highFrameRateState;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *highlightBeingAssets;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *highlightBeingExtendedAssets;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *highlightBeingKeyAssetPrivate;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *highlightBeingKeyAssetShared;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *highlightBeingSummaryAssets;
@property (nonatomic) CGFloat highlightPromotionScore;
@property (nonatomic) CGFloat highlightVisibilityScore;
@property (retain, nonatomic) NSData *imageRequestHints;
@property (nonatomic) CGSize imageSize;
@property (retain, nonatomic) PLImportSession *importSession;
@property (nonatomic) short importedBy;
@property (retain, nonatomic) NSString *importedByBundleIdentifier;
@property (retain, nonatomic) NSString *importedByDisplayName;
@property (readonly, nonatomic) int inferredTimeZoneOffset;
@property (readonly, nonatomic) NSObject *inflightImage;
@property (retain, nonatomic) NSObject *inflightImageInMemory; // ivar: inflightImageInMemory
@property (retain, nonatomic) NSString *inflightImagePath; // ivar: inflightImagePath
@property (retain, nonatomic) NSObject *inflightIndexSheetImage; // ivar: inflightIndexSheetImage
@property (retain, nonatomic) NSDictionary *inflightMetadata; // ivar: inflightMetadata
@property (readonly, nonatomic) BOOL isAnimation;
@property (readonly, nonatomic) BOOL isAudio;
@property (readonly, nonatomic) BOOL isAudio;
@property (readonly, nonatomic) BOOL isAutoloop;
@property (readonly, nonatomic) BOOL isAvalanchePhoto;
@property (readonly, nonatomic) BOOL isAvalancheStackPhoto;
@property (readonly) BOOL isBundleScopeSyndication;
@property (readonly, nonatomic) BOOL isCameraConnectionKitAsset;
@property (readonly, nonatomic) BOOL isCameraProcessingAdjustmentCandidate;
@property (readonly, nonatomic) BOOL isCloudPhotoLibraryAsset;
@property (readonly, nonatomic) BOOL isCloudSharedAsset;
@property (readonly, nonatomic) BOOL isColorAware;
@property (readonly, nonatomic) BOOL isDefaultAdjustedSlomo;
@property (readonly, nonatomic) BOOL isDeferredProcessingCandidate;
@property (readonly, nonatomic) BOOL isFinderSyncedAsset;
@property (readonly, nonatomic) BOOL isHDVideo;
@property (readonly, nonatomic) BOOL isHEIF;
@property (readonly, nonatomic) BOOL isInFlight;
@property (nonatomic) BOOL isInFlight;
@property (readonly, nonatomic) BOOL isInterestingForAvalanche;
@property (readonly, nonatomic) BOOL isJPEG;
@property (readonly, nonatomic) BOOL isLongExposure;
@property (nonatomic) BOOL isMagicCarpet;
@property (readonly, nonatomic) BOOL isMirror;
@property (readonly, nonatomic) BOOL isMogul;
@property (readonly, nonatomic) BOOL isMomentSharedAsset;
@property (readonly, nonatomic) BOOL isPhoto;
@property (readonly, nonatomic) BOOL isPhoto;
@property (readonly, nonatomic) BOOL isPhotoIris;
@property (readonly, nonatomic) BOOL isPhotoIris;
@property (readonly, nonatomic) BOOL isPhotoIrisPlaceholder;
@property (readonly, nonatomic) BOOL isPhotoStreamPhoto;
@property (readonly, nonatomic) BOOL isPlaceholderAsset;
@property (readonly, nonatomic) BOOL isPrimaryImageFormat;
@property (readonly, nonatomic) BOOL isReferencedAsset;
@property (readonly, nonatomic) BOOL isScreenRecording;
@property (readonly, nonatomic) BOOL isStreamedVideo;
@property (readonly, nonatomic) BOOL isSuggestedForSharingByPhotos;
@property (readonly, nonatomic) BOOL isUnknown;
@property (readonly, nonatomic) BOOL isVideo;
@property (readonly, nonatomic) BOOL isVideo;
@property (nonatomic) unsigned char keywordBadgeAttribute;
@property (nonatomic) short kind;
@property (readonly, nonatomic) short kindSubtype;
@property (nonatomic) short kindSubtype;
@property (retain, nonatomic) NSDate *lastSharedDate;
@property (retain, nonatomic) NSDate *lastSpotlightChangeDate;
@property (nonatomic) CGFloat latitude;
@property (retain, nonatomic) NSSet *legacyFaces;
@property (retain, nonatomic) PLLibraryScope *libraryScope;
@property (retain, nonatomic) NSSet *libraryScopeAssetContributors;
@property (readonly, nonatomic) NSSet *libraryScopeContributors;
@property (nonatomic) NSInteger libraryScopeShareState;
@property (retain, nonatomic) NSSet *likeComments;
@property (retain, nonatomic) NSSet *likeComments;
@property (readonly, nonatomic) NSUInteger likeCommentsCount;
@property (readonly, retain, nonatomic) NSDate *localDateCreated;
@property (readonly, retain, nonatomic) id *localID;
@property (nonatomic, getter=isLocalOnlyDelete) BOOL localOnlyDelete; // ivar: localOnlyDelete
@property (readonly, retain, nonatomic) CLLocation *location;
@property (retain, nonatomic) CLLocation *location;
@property (retain, nonatomic) NSData *locationData;
@property (nonatomic) int locationHash;
@property (readonly, retain, nonatomic) PLRevGeoLocationInfo *locationInfo;
@property (retain, nonatomic) NSString *longDescription;
@property (nonatomic) CGFloat longitude;
@property (readonly, copy, nonatomic) NSURL *mainFileURL;
@property (readonly, copy, nonatomic) NSURL *mainFileURL;
@property (retain, nonatomic) PLCloudMaster *master;
@property (retain, nonatomic) PLMediaAnalysisAssetAttributes *mediaAnalysisAttributes;
@property (readonly, copy, nonatomic) NSString *mediaGroupUUID;
@property (retain, nonatomic) NSString *mediaGroupUUID;
@property (retain, nonatomic) NSSet *memoriesBeingCuratedAssets;
@property (retain, nonatomic) NSSet *memoriesBeingCustomUserAssets;
@property (retain, nonatomic) NSSet *memoriesBeingExtendedCuratedAssets;
@property (retain, nonatomic) NSSet *memoriesBeingKeyAsset;
@property (retain, nonatomic) NSSet *memoriesBeingMovieCuratedAssets;
@property (retain, nonatomic) NSSet *memoriesBeingRepresentativeAssets;
@property (retain, nonatomic) NSSet *memoriesBeingUserCuratedAssets;
@property (retain, nonatomic) NSSet *modernResources;
@property (readonly, copy, nonatomic) NSDate *modificationDate;
@property (retain, nonatomic) NSDate *modificationDate;
@property (retain, nonatomic) PLMoment *moment;
@property (retain, nonatomic) PLMomentShare *momentShare;
@property (nonatomic) short monoskiType;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *monthHighlightBeingKeyAssetPrivate;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *monthHighlightBeingKeyAssetShared;
@property (nonatomic) BOOL needsMomentUpdate; // ivar: _needsMomentUpdate
@property (readonly, nonatomic) NSManagedObjectID *objectID;
@property (readonly, retain, nonatomic) NSOrderedSet *orderedCloudComments;
@property (readonly, retain, nonatomic) NSOrderedSet *orderedLikeComments;
@property (nonatomic) short orientation;
@property (retain, nonatomic) PLManagedAsset *originalAsset;
@property (retain, nonatomic) NSString *originalAssetsUUID;
@property (retain, nonatomic) NSString *originalColorSpace;
@property (retain, nonatomic) NSString *originalFilename;
@property (readonly, copy, nonatomic) NSString *originalFilename;
@property (nonatomic) NSUInteger originalFilesize;
@property (readonly, nonatomic) NSUInteger originalFilesize;
@property (retain, nonatomic) NSData *originalHash;
@property (nonatomic) NSInteger originalHeight;
@property (readonly, nonatomic) NSInteger originalHeight;
@property (nonatomic) short originalOrientation;
@property (readonly, nonatomic) short originalOrientation;
@property (readonly, copy, nonatomic) NSString *originalUniformTypeIdentifier;
@property (nonatomic) NSInteger originalWidth;
@property (readonly, nonatomic) NSInteger originalWidth;
@property (nonatomic) float overallAestheticScore;
@property (nonatomic) NSInteger packedAcceptableCropRect;
@property (nonatomic) int packedBadgeAttributes;
@property (nonatomic) NSInteger packedPreferredCropRect;
@property (readonly, copy, nonatomic) NSString *pathForAdjustmentDirectory;
@property (readonly, copy, nonatomic) NSString *pathForAdjustmentFile;
@property (readonly, copy, nonatomic) NSString *pathForComputeDirectory;
@property (readonly, copy, nonatomic) NSString *pathForDiagnosticFile;
@property (readonly, copy, nonatomic) NSString *pathForFullsizeRenderImageFile;
@property (readonly, copy, nonatomic) NSString *pathForFullsizeRenderVideoFile;
@property (readonly, copy, nonatomic) NSString *pathForLargeDisplayableImageFile;
@property (readonly, copy, nonatomic) NSString *pathForLargeThumbnailFile;
@property (readonly, copy, nonatomic) NSString *pathForLegacySlalomRegionsArchive;
@property (readonly, copy, nonatomic) NSString *pathForMediumThumbnailFile;
@property (readonly, copy, nonatomic) NSString *pathForMetadataDirectory;
@property (readonly, copy, nonatomic) NSString *pathForOriginalAdjustmentFile;
@property (readonly, copy, nonatomic) NSString *pathForOriginalFile;
@property (readonly, copy, nonatomic) NSString *pathForOriginalFile;
@property (readonly, copy, nonatomic) NSString *pathForPenultimateFullsizeRenderImageFile;
@property (readonly, copy, nonatomic) NSString *pathForPenultimateFullsizeRenderVideoFile;
@property (readonly, copy, nonatomic) NSString *pathForPrebakedLandscapeScrubberThumbnails;
@property (readonly, copy, nonatomic) NSString *pathForPrebakedPortraitScrubberThumbnails;
@property (readonly, copy, nonatomic) NSString *pathForSpatialOverCaptureContentFile;
@property (readonly, copy, nonatomic) NSString *pathForTrimmedVideoFile;
@property (readonly, copy, nonatomic) NSString *pathForVideoComplementSpatialOverCaptureContentFile;
@property (readonly, copy, nonatomic) NSString *pathForVideoFile;
@property (readonly, copy, nonatomic) NSString *pathForVideoPreviewFile;
@property (readonly, copy, nonatomic) NSString *pathForXMPFile;
@property (readonly, copy, nonatomic) NSURL *persistedFileSystemAttributesFileURL;
@property (retain, nonatomic) PLPhotoAnalysisAssetAttributes *photoAnalysisAttributes;
@property (nonatomic) ? photoIrisStillDisplayTime;
@property (nonatomic) ? photoIrisVideoDuration;
@property (readonly, nonatomic) CLLocationCoordinate2D pl_coordinate;
@property (readonly, nonatomic) NSDate *pl_date;
@property (readonly, nonatomic) CGFloat pl_gpsHorizontalAccuracy;
@property (readonly, nonatomic) NSString *pl_uuid;
@property (readonly, retain, nonatomic) PLRevGeoPlaceAnnotation *placeAnnotation;
@property (retain, nonatomic) NSData *placeAnnotationData;
@property (nonatomic) unsigned short playbackStyle;
@property (nonatomic) unsigned short playbackVariation;
@property (nonatomic) unsigned char proResBadgeAttribute;
@property (readonly, retain, nonatomic) NSObject<PLPTPTransferableAdditionalAssetAttributes> *ptpAdditionalAttributes;
@property (readonly, nonatomic) NSUInteger ptpCloudMasterOriginalFileSize;
@property (readonly, nonatomic) NSObject<PLPTPTransferableSidecarFile> *ptpPhotoIrisSidecar;
@property (readonly, retain, nonatomic) NSSet *ptpSidecarFiles;
@property (retain, nonatomic) NSString *publicGlobalUUID;
@property (readonly, nonatomic) NSString *rawTimeZoneName;
@property (readonly, nonatomic) NSNumber *rawTimeZoneOffsetValue;
@property (retain, nonatomic) NSSet *resources;
@property (retain, nonatomic) NSData *reverseLocationData;
@property (nonatomic) BOOL reverseLocationDataIsValid;
@property (readonly, nonatomic) short savedAssetType;
@property (nonatomic) short savedAssetType;
@property (nonatomic) short searchIndexRebuildState;
@property (readonly, nonatomic) unsigned char shareState;
@property (retain, nonatomic) CLLocation *shiftedLocation;
@property (nonatomic) BOOL shiftedLocationIsValid;
@property (nonatomic) CGFloat sortToken;
@property (readonly, copy, nonatomic) NSArray *sortedSidecarFiles;
@property (readonly, nonatomic) CGSize spatialOverCaptureSize;
@property (retain, nonatomic) NSSet *suggestionsBeingKeyAssets;
@property (retain, nonatomic) NSSet *suggestionsBeingRepresentativeAssets;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly, copy, nonatomic) NSString *syncedAdjustmentFingerprint;
@property (nonatomic) unsigned short syndicationState;
@property (readonly, copy, nonatomic) NSString *textBadgeString;
@property (nonatomic) int thumbnailIndex;
@property (retain, nonatomic) NSString *title;
@property (readonly, nonatomic) NSUInteger totalCommentsCount;
@property (retain, nonatomic) PLShareParticipant *trashedByParticipant;
@property (retain, nonatomic) NSDate *trashedDate;
@property (nonatomic) short trashedState;
@property (readonly, copy, nonatomic) NSString *uniformTypeIdentifier;
@property (retain, nonatomic) NSString *uniformTypeIdentifier;
@property (readonly, retain, nonatomic) NSObject<NSCopying> *uniqueObjectID;
@property (nonatomic) BOOL userCloudSharedLiked;
@property (readonly, nonatomic) NSDate *utcDate;
@property (readonly, retain, nonatomic) id *uuid;
@property (retain, nonatomic) id *uuid;
@property (readonly, nonatomic) CGSize videoComplementSpatialOverCaptureSize;
@property (nonatomic) NSInteger videoCpDurationValue;
@property (nonatomic) unsigned short videoCpVisibilityState;
@property (nonatomic) unsigned short videoDeferredProcessingNeeded;
@property (nonatomic) int videoKeyFrameTimeScale;
@property (nonatomic) NSInteger videoKeyFrameValue;
@property (nonatomic) short visibilityState;
@property (readonly, nonatomic) NSInteger width;
@property (readonly, nonatomic) NSInteger width;
@property (nonatomic) NSInteger width;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *yearHighlightBeingKeyAssetPrivate;
@property (retain, nonatomic) NSObject<PLPhotosHighlightData> *yearHighlightBeingKeyAssetShared;


+(?)_insertAssetIntoPhotoLibrary:(?)arg0 mainFileURL:(?)arg1 mainFileMetadata:(?)arg2 savedAssetType:(?)arg3 bundleScope:(?)arg4 uuid:(?)arg5 replacementUUID:(?)arg6 imageSource:(?)arg7 imageData:(?)arg8 isPlaceholderdeleteFileOnFailure;
+(?)insertAssetIntoPhotoLibrary:(?)arg0 mainFileURL:(?)arg1 mainFileMetadata:(?)arg2 savedAssetType:(?)arg3 bundleScope:(?)arg4 uuid:(?)arg5 replacementUUID:(?)arg6 imageSource:(?)arg7 imageData:(?)arg8 isPlaceholderdeleteFileOnFailure;
+(?)insertAssetIntoPhotoLibrary:(?)arg0 mainFileURL:(?)arg1 savedAssetType:(?)arg2 bundleScope:(?)arg3 uuid:(?)arg4 replacementUUID:(?)arg5 imageSourceimageData;
+(BOOL)_isLoopingVideoPlaybackVariation:(unsigned short)arg0 ;
+(BOOL)_isPlayableVideoUTI:(struct __CFString *)arg0 ;
+(BOOL)canPlayPhotoIrisWithPhotoIris:(BOOL)arg0 photoIrisPlaceholder:(BOOL)arg1 hasAdjustments:(BOOL)arg2 videoCpVisibilityState:(unsigned short)arg3 ;
+(BOOL)cloneResourceFileFromURL:(id)arg0 toURL:(id)arg1 forDestinationResource:(id)arg2 forDestinationAsset:(id)arg3 fileManager:(id)arg4 error:(*id)arg5 ;
+(BOOL)createMasterForPlaceholderAsset:(id)arg0 withSourceAsset:(id)arg1 shouldBakeInAdjustments:(BOOL)arg2 shouldFlattenLivePhoto:(BOOL)arg3 placeholderResourceURLToSourceResourceURLMap:(id)arg4 photoLibrary:(id)arg5 ;
+(BOOL)createMomentShareAssetsForMomentShare:(id)arg0 batchedSourceAssetsToCopy:(id)arg1 creationRequestSourceAssetsCMMAssetsMap:(id)arg2 curatedSourceAssets:(id)arg3 adjustmentBakeInOptionsDictionary:(id)arg4 metadataCopyOptionsDictionary:(id)arg5 keySourceAssetIdentifier:(id)arg6 clientConnection:(id)arg7 library:(id)arg8 error:(*id)arg9 ;
+(BOOL)guaranteedFlashOffForAssetAtURL:(id)arg0 ;
+(BOOL)hasRequiredExtendedAttributesForMainFileURL:(id)arg0 ;
+(BOOL)hasRequiredExtendedAttributesForPersistanceAttributes:(id)arg0 ;
+(BOOL)installResourcesForAssetAndRemoveDeferredProcessingPreviewFile:(id)arg0 error:(*id)arg1 ;
+(BOOL)invalidateBehavioralScoreOnAllAssetsInManagedObjectContext:(id)arg0 error:(*id)arg1 ;
+(BOOL)invalidateReverseLocationDataOnAllAssetsInManagedObjectContext:(id)arg0 error:(*id)arg1 ;
+(BOOL)isHFRVideoAVAsset:(id)arg0 ;
+(BOOL)isKnownFileExtension:(id)arg0 ;
+(BOOL)isOrphanedMediaGroupUUID:(id)arg0 ;
+(BOOL)isPhotoIrisPlaceholderWithPhotoIris:(BOOL)arg0 isCameraProcessingAdjustment:(BOOL)arg1 videoCpDuration:(NSInteger)arg2 isCloudShared:(BOOL)arg3 videoCpFilePath:(id)arg4 cameraProcessingAdjustmentVideoCpFilePath:(id)arg5 deferredProcessingNeedingAdjustment:(BOOL)arg6 ;
+(BOOL)isPrimaryImageFormatForUTI:(id)arg0 ;
+(BOOL)isScreenRecordingFileName:(id)arg0 ;
+(BOOL)isValidFileExtensionForImport:(id)arg0 ;
+(BOOL)isValidFileURLForImport:(id)arg0 ;
+(BOOL)isVideoComplementVisibilityStatePlayable:(unsigned short)arg0 hasAdjustments:(BOOL)arg1 ;
+(BOOL)shouldBakeInAdjustmentsAndFlattenLivePhoto:(*BOOL)arg0 forSourceAsset:(id)arg1 adjustmentBakeInOptions:(id)arg2 ;
+(BOOL)shouldPerformServerCopyOnPlaceholderAsset:(id)arg0 photoLibrary:(id)arg1 ;
+(BOOL)shouldPerformServerCopyWithSourceAsset:(id)arg0 copyingFromMomentShare:(BOOL)arg1 photoLibrary:(id)arg2 ;
+(BOOL)validMomentShareForPlaceholderAsset:(id)arg0 ;
+(NSInteger)_locationDataFormat:(id)arg0 ;
+(NSInteger)adjustmentBaseVersionFromPFAdjustmentsBaseVersion:(NSInteger)arg0 ;
+(NSInteger)cloudDeletionTypeForTombstone:(id)arg0 ;
+(NSInteger)pfAdjustmentsBaseVersionFromAdjustmentBaseVersion:(NSInteger)arg0 ;
+(NSInteger)totalPurgeableSizeOnDiskInLibrary:(id)arg0 urgency:(NSInteger)arg1 ;
+(NSUInteger)CPLAssetHDRTypeFromPLAssetHDRType:(short)arg0 ;
+(NSUInteger)_sumOfCountsInCountedSet:(id)arg0 ;
+(NSUInteger)countForAssetsWithUUIDs:(id)arg0 includePendingChanges:(BOOL)arg1 inManagedObjectContext:(id)arg2 error:(*id)arg3 ;
+(NSUInteger)countOfDeferredAssetsToSyncInPhotoLibrary:(id)arg0 outAssetList:(id)arg1 ;
+(NSUInteger)countOfNotUploadedAssetsInPhotoLibrary:(id)arg0 forAssetType:(short)arg1 error:(*id)arg2 ;
+(NSUInteger)countUsedAssetsWithKind:(short)arg0 excludeTrashed:(BOOL)arg1 excludeInvisible:(BOOL)arg2 excludeCloudShared:(BOOL)arg3 excludePhotoStream:(BOOL)arg4 inManagedObjectContext:(id)arg5 ;
+(NSUInteger)resourceTypeForUnadjustedFlattenedLivePhotoAssetResourceType:(NSUInteger)arg0 ;
+(NSUInteger)totalSizeOfUnpushedOriginalsInPhotoLibrary:(id)arg0 outMasterList:(id)arg1 isInitialUpload:(BOOL)arg2 ;
+(id)_cloudAdjustmentFingerprintWithAdjustmentDataBlob:(id)arg0 largeAdjustmentBlobFingerpint:(id)arg1 formatIdentifier:(id)arg2 formatVersion:(id)arg3 editorBundleID:(id)arg4 baseVersion:(NSInteger)arg5 baseImageData:(id)arg6 baseImageFingerprint:(id)arg7 ;
+(id)_countOfAssetsByKindWithResourcePredicate:(id)arg0 inContext:(id)arg1 ;
+(id)_createAssetModelToInsert:(id)arg0 uuid:(id)arg1 replacementUUID:(id)arg2 ;
+(id)_dataFromCPLPlaceAnnotation:(id)arg0 ;
+(id)_importAlbumIsolationQueue;
+(id)_insertSyndicationAssetIntoPhotoLibrary:(id)arg0 uuid:(id)arg1 syndicationIdentifier:(id)arg2 bundleID:(id)arg3 addedDate:(id)arg4 ;
+(id)_newPathAndDateDictionariesByAssetUUIDFromFetchResults:(id)arg0 photoLibrary:(id)arg1 ;
+(id)_notPushedAssetsToUploadInitiallyInManagedObjectContext:(id)arg0 withSavedAssetTypePredicate:(id)arg1 shouldSort:(BOOL)arg2 limit:(NSUInteger)arg3 ;
+(id)_placeAnnotationFromAnnotationData:(id)arg0 ;
+(id)_predicateForAssetsWithNotCompleteResourcesOnResource;
+(id)_predicateForCloudLocalStates:(id)arg0 ;
+(id)_predicateForDepthType:(short)arg0 ;
+(id)_predicateForTrashedAssetsToExcludeInInitialUpload;
+(id)_ptpCalendar;
+(id)_ptpEventInfoIsolationQueue;
+(id)_syncablePredicate;
+(id)_syndicationAssetForSearchableItem:(id)arg0 inLibrary:(id)arg1 createIfNeeded:(BOOL)arg2 didCreate:(*BOOL)arg3 error:(*id)arg4 ;
+(id)allCloudSharedAssetsInLibrary:(id)arg0 ;
+(id)allHDRValues;
+(id)assetUUIDsByObjectIDs:(id)arg0 withFilterPredicate:(id)arg1 context:(id)arg2 error:(*id)arg3 ;
+(id)assetWithObjectID:(id)arg0 inLibrary:(id)arg1 ;
+(id)assetWithObjectID:(id)arg0 inManagedObjectContext:(id)arg1 ;
+(id)assetWithScopedIdentifier:(id)arg0 inLibrary:(id)arg1 prefetchResources:(BOOL)arg2 ;
+(id)assetWithSyndicationIdentifier:(id)arg0 inLibrary:(id)arg1 ;
+(id)assetWithUUID:(id)arg0 inLibrary:(id)arg1 ;
+(id)assetWithUUID:(id)arg0 inManagedObjectContext:(id)arg1 ;
+(id)assetsByCloudAssetUUID:(id)arg0 inLibrary:(id)arg1 ;
+(id)assetsByScopedIdentifiers:(id)arg0 relationshipKeyPathsForPrefetching:(id)arg1 inLibrary:(id)arg2 ;
+(id)assetsLibraryURLWithUUID:(id)arg0 extension:(id)arg1 ;
+(id)assetsToConsiderForTypePromotionInContext:(id)arg0 withExtensions:(id)arg1 error:(*id)arg2 ;
+(id)assetsToRetryInLibrary:(id)arg0 limit:(NSUInteger)arg1 ;
+(id)assetsToUploadInitiallyInManagedObjectContext:(id)arg0 limit:(NSUInteger)arg1 ;
+(id)assetsWithGroupingUUID:(id)arg0 inManagedObjectContext:(id)arg1 ;
+(id)assetsWithObjectIDs:(id)arg0 inLibrary:(id)arg1 ;
+(id)assetsWithScopedIdentifiers:(id)arg0 prefetchResources:(BOOL)arg1 relationshipKeyPathsForPrefetching:(id)arg2 inLibrary:(id)arg3 ;
+(id)assetsWithUUIDs:(id)arg0 options:(NSUInteger)arg1 inLibrary:(id)arg2 ;
+(id)assetsWithUUIDs:(id)arg0 options:(NSUInteger)arg1 inManagedObjectContext:(id)arg2 ;
+(id)assetsWithValidatedSavedAssetTypeMask:(unsigned short)arg0 inManagedObjectContext:(id)arg1 ;
+(id)attributeValidationRules;
+(id)baseSearchIndexPredicate;
+(id)calculateImageRequestHintsFromSortedResources:(id)arg0 asset:(id)arg1 ;
+(id)cloudAdjustmentFingerprintWithAdjustmentDataBlob:(id)arg0 formatIdentifier:(id)arg1 formatVersion:(id)arg2 editorBundleID:(id)arg3 baseVersion:(NSInteger)arg4 baseFingerprint:(id)arg5 ;
+(id)cloudAdjustmentFingerprintWithAdjustmentDataBlob:(id)arg0 formatIdentifier:(id)arg1 formatVersion:(id)arg2 editorBundleID:(id)arg3 baseVersion:(NSInteger)arg4 baseImageData:(id)arg5 ;
+(id)cloudSharedAssetsWithGUIDs:(id)arg0 inLibrary:(id)arg1 ;
+(id)cloudUUIDKeyForDeletion;
+(id)createCloudPhotoLibraryAssetWithAssetRecord:(id)arg0 withCloudMaster:(id)arg1 inLibrary:(id)arg2 ;
+(id)createOrUpdateObjectFromSearchableItem:(id)arg0 library:(id)arg1 createIfNeeded:(BOOL)arg2 didCreate:(*BOOL)arg3 isSyndicatable:(*BOOL)arg4 error:(*id)arg5 ;
+(id)diagnosticFilePathForLibrary:(id)arg0 mainFilename:(id)arg1 createIfNeeded:(BOOL)arg2 ;
+(id)entityName;
+(id)eventInfoForPTP;
+(id)extensionForFullsizeThumbnailFile;
+(id)extensionForLargeThumbnailFile;
+(id)extensionForMediumThumbnailFile;
+(id)failedToPushAssetInLibrary:(id)arg0 ;
+(id)fetchPredicateForLegacyRequiredResourcesLocallyAvailable:(BOOL)arg0 photoLibrary:(id)arg1 ;
+(id)fetchRequestForSortedCloudSharedAssetsWithPlaceholderKinds:(id)arg0 additionalPredicate:(id)arg1 ascending:(BOOL)arg2 ;
+(id)fetchResourcesForAssetWithObjectID:(id)arg0 inContext:(id)arg1 versions:(id)arg2 includeVirtualResources:(BOOL)arg3 allowDerivatives:(BOOL)arg4 excludeDynamicCPLResources:(BOOL)arg5 additionalPredicate:(id)arg6 relationshipKeyPathsForPrefetching:(id)arg7 error:(*id)arg8 ;
+(id)fileURLFromAssetURL:(id)arg0 photoLibrary:(id)arg1 ;
+(id)filterPredicateToExcludeNoSyndicationAssets;
+(id)filterPredicateToIncludeOnlyReceivedSyndicatedAssets;
+(id)imageAssetsForMediaGroupUUID:(id)arg0 moc:(id)arg1 ;
+(id)isEligibleForSearchIndexingPredicate;
+(id)keyPathsForValuesAffectingGpsCoordinate;
+(id)keyPathsForValuesAffectingImageSize;
+(id)keyPathsForValuesAffectingIsJPEG;
+(id)keyPathsForValuesAffectingIsPhotoStreamPhoto;
+(id)lightweightReimportFileNameWithGUID:(id)arg0 type:(id)arg1 ;
+(id)listOfSharingAttributesRelevantForUpload;
+(id)listOfSharingRelationshipsRelevantForUpload;
+(id)listOfStatesWithOutstandingDeferredPhotoProcessingWork;
+(id)listOfSyncedProperties;
+(id)needsSearchIndexingForRebuildPredicate;
+(id)newImagePropertiesFromImageSource:(struct CGImageSource *)arg0 ;
+(id)newLocationDataFromLocation:(id)arg0 ;
+(id)newLocationFromLocationData:(id)arg0 timestampIfMissing:(id)arg1 ;
+(id)objectsWithScopedIdentifiers:(id)arg0 forEntityName:(id)arg1 prefetchResources:(BOOL)arg2 relationshipKeyPathsForPrefetching:(id)arg3 inLibrary:(id)arg4 ;
+(id)pathAndDateDictionariesForAllIncompleteAssetsInManagedObjectContext:(id)arg0 ;
+(id)pathForAdjustmentDataFileWithPathManager:(id)arg0 uuid:(id)arg1 directory:(id)arg2 filename:(id)arg3 ;
+(id)pathForAdjustmentDirectoryWithMutationsDirectory:(id)arg0 ;
+(id)pathForAdjustmentFileWithPathManager:(id)arg0 uuid:(id)arg1 directory:(id)arg2 filename:(id)arg3 ;
+(id)pathForMutationsDirectoryWithDirectory:(id)arg0 filename:(id)arg1 ;
+(id)persistedRecentlyUsedGUIDSWithPathManager:(id)arg0 ;
+(id)photoFromAssetURL:(id)arg0 photoLibrary:(id)arg1 ;
+(id)photoFromAssetURL:(id)arg0 photoLibrary:(id)arg1 sidecar:(*id)arg2 ;
+(id)predicateExcludingLocallyUnavailableDynamicCPLResources;
+(id)predicateFilteringForNonDerivativeRecipeIDs;
+(id)predicateForAssetSharingFilter:(short)arg0 ;
+(id)predicateForAssetSubtype:(short)arg0 ;
+(id)predicateForAssetsToCheckForDeletionOnCPLDisable;
+(id)predicateForAssetsWithCompleteResourcesOnAsset;
+(id)predicateForBurstStackAssets;
+(id)predicateForCinematicVideos;
+(id)predicateForDepthEffectPhotos;
+(id)predicateForLocallyAvailablePrimaryStoreResourcesWithCPLResourceTypes:(id)arg0 version:(unsigned int)arg1 ;
+(id)predicateForProResAssets;
+(id)predicateForRAWAndRPlusJAssets;
+(id)predicateForReframedAssets;
+(id)predicateForSpatialOverCaptureAssets;
+(id)predicateForSupportedAssetTypesForUpload;
+(id)predicateForSupportedAssetTypesForUploadWithoutMomentSharesAndPlaceholders;
+(id)predicateForSyndicatedAssetIdentifiers:(id)arg0 includeRejected:(BOOL)arg1 ;
+(id)predicateForSyndicatedAssetIdentifiersSuffix:(id)arg0 ;
+(id)predicateForUnpushedDeferredAssets;
+(id)predicateForUploadableAssetsWithCloudLocalState:(short)arg0 ;
+(id)predicateForUploadableAssetsWithCloudLocalStates:(id)arg0 ;
+(id)predicateForUploadableAssetsWithMasterCloudLocalStateNotEqualTo:(short)arg0 ;
+(id)predicateForUploadableAssetsWithoutCloudLocalState:(short)arg0 ;
+(id)predicateToExcludeAssetsMissingMasterThumbnailsWithThumbnailIndexKeyPath:(id)arg0 ;
+(id)predicateToExcludeHiddenAssets;
+(id)predicateToExcludeHiddenAssetsWithHiddenKeyPath:(id)arg0 ;
+(id)predicateToExcludeNonvisibleBurstAssets;
+(id)predicateToExcludeNonvisibleBurstAssetsWithAvalanchePickTypeKeyPath:(id)arg0 ;
+(id)predicateToExcludeRestrictedLockedAssets;
+(id)predicateToExcludeTrashedAssets;
+(id)predicateToExcludeTrashedAssetsWithTrashedStateKeyPath:(id)arg0 ;
+(id)predicateToExcludeVideosWithVideoKeyFrameSetWithKeyPathToAsset:(id)arg0 ;
+(id)predicateToFetchResourcesAwaitingLocalAvailabilityChange;
+(id)predicateToIncludeBothPrivateAssetsAndSharedContentContributedByCurrentUser;
+(id)predicateToIncludeOnlyAllowedForAnalysisAssets;
+(id)predicateToIncludeOnlyContentContributedByCurrentUser;
+(id)predicateToIncludePrivateLibraryAssetsAllowingIndexingOnParticipationState:(BOOL)arg0 ;
+(id)predicateToIncludeSharedLibraryAssetsAllowingIndexingOnParticipationState:(BOOL)arg0 ;
+(id)predicateToIncludeSharedLibrarySharingSuggestionsAssets;
+(id)preferredFileExtensionForType:(id)arg0 ;
+(id)ptpAssetIDForEventAndFilenameKey:(id)arg0 ;
+(id)quarantinedAssetsInLibrary:(id)arg0 ;
+(id)recentlyUsedGUIDsPathWithPathManager:(id)arg0 ;
+(id)toUploadAssetsInLibrary:(id)arg0 ;
+(id)uniformTypeFromPathExtension:(id)arg0 assetType:(short)arg1 ;
+(id)uniformTypeIdentifierFromPathExtension:(id)arg0 assetType:(short)arg1 ;
+(id)uuidFromAssetURL:(id)arg0 ;
+(id)uuidFromAssetURL:(id)arg0 fileExtension:(*id)arg1 sidecarIndex:(*id)arg2 ;
+(id)videoAssetsForMediaGroupUUID:(id)arg0 moc:(id)arg1 ;
+(id)videoComplementVisibilityStatePlayablePredicate;
+(short)_correctedOrientation:(short)arg0 ;
+(short)assetTypeFromUniformTypeIdentifier:(id)arg0 ;
+(short)imageDepthTypeFromCustomRenderedValue:(short)arg0 ;
+(short)imageHDRTypeFromCustomRenderedValue:(short)arg0 ;
+(struct CGSize )dimensionsForAVAsset:(id)arg0 ;
+(struct CGSize )dimensionsForVideoAtURL:(id)arg0 ;
+(struct CGSize )sizeOfImageAtURL:(id)arg0 outOrientation:(*short)arg1 ;
+(unsigned short)defaultPlaybackStyleFromAssetType:(short)arg0 subtype:(short)arg1 playbackVariation:(unsigned short)arg2 ;
+(unsigned short)landscapeScrubberThumbnailFormat;
+(unsigned short)portraitScrubberThumbnailFormat;
+(void)_cloneResourcesForMomentSharePlaceholderAsset:(id)arg0 withPlaceholderResourceURLToSourceResourceURLMap:(id)arg1 fileManager:(id)arg2 photoLibrary:(id)arg3 ;
+(void)_rm_copyResourceFileFrom:(id)arg0 to:(id)arg1 forCloudMaster:(id)arg2 andAsset:(id)arg3 ;
+(void)batchFetchAssetsByFaceUUIDWithFaceUUIDs:(id)arg0 library:(id)arg1 completion:(id)arg2 ;
+(void)clearImportSessionObjectIDCacheOnManagedObjectContext:(id)arg0 ;
+(void)computePreCropThumbnailSize:(struct CGSize *)arg0 andPostCropSize:(struct CGSize *)arg1 forOrientedOriginalSize:(struct CGSize )arg2 andCroppedSize:(struct CGSize )arg3 isLargeThumbnail:(BOOL)arg4 ;
+(void)countOfAssetsWithRequiredResourcesNotLocallyAvailableInLibrary:(id)arg0 outCount:(*NSUInteger)arg1 photoCount:(*NSUInteger)arg2 videoCount:(*NSUInteger)arg3 ;
+(void)createMastersInLibrary:(id)arg0 ;
+(void)createTHMFileWithPreviewImage:(id)arg0 thumbnailImage:(id)arg1 fileURLForThumbnailFile:(id)arg2 ;
+(void)createThumbnailImage:(*id)arg0 previewImage:(*id)arg1 withToBeReleasedImageSource:(struct CGImageSource *)arg2 ;
+(void)deDupCMMAssets:(id)arg0 ;
+(void)deleteOldPlaceholderAssetsInManagedObjectContext:(id)arg0 ;
+(void)fixupCloudPhotoLibraryAsset:(id)arg0 withCloudMaster:(id)arg1 inLibrary:(id)arg2 ;
+(void)markAssetAsRecentlyUsed:(id)arg0 ;
+(void)performTransactionOnSyndicationLibraryWithSyndicationIdentifier:(id)arg0 block:(id)arg1 ;
+(void)processMediaMetadataForAsset:(id)arg0 withCloudMaster:(id)arg1 ;
+(void)ptpResetEventAndFilenameMapping;
+(void)ptpSetAssetIDForEventAndFilenameKey:(id)arg0 value:(id)arg1 ;
+(void)resetAssetsCloudStateInLibrary:(id)arg0 ;
+(void)rm_cplResourceWasUploaded:(id)arg0 photoLibrary:(id)arg1 ;
-(BOOL)_analysisStateWasChangedForWorkerType:(short)arg0 ;
-(BOOL)_hasBecomeNonVisibleToMemoriesAndPersonsAndSuggestions:(id)arg0 ;
-(BOOL)_hasPanoramaDimensions;
-(BOOL)_hasScreenshotDimensions;
-(BOOL)_hasScreenshotMetadataWithMetadata:(id)arg0 ;
-(BOOL)_hasVideoComplementData;
-(BOOL)_isAdjustedResourceAvailableForResourceType:(NSUInteger)arg0 ;
-(BOOL)_isAdjustedResourceAvailableForResourceType:(NSUInteger)arg0 outResource:(*id)arg1 ;
-(BOOL)_isGoldilocksEnabled;
-(BOOL)_isMasterResourceAvailableForResourceType:(NSUInteger)arg0 ;
-(BOOL)_isMasterResourceAvailableForResourceType:(NSUInteger)arg0 outResource:(*id)arg1 ;
-(BOOL)_isResourceAvailableForResourceType:(NSUInteger)arg0 outResource:(*id)arg1 ;
-(BOOL)_isResourceType:(NSUInteger)arg0 inResources:(id)arg1 ;
-(BOOL)_isValidUTI:(id)arg0 forService:(id)arg1 ;
-(BOOL)_isVisibleAvalanchePickType:(int)arg0 ;
-(BOOL)_linkVideoFileFromSourcePath:(id)arg0 toDestinationPath:(id)arg1 ;
-(BOOL)_location:(id)arg0 isEqualToLocationForUpdating:(id)arg1 ;
-(BOOL)_migrateKeyedArchiverAdjustmentsToPropertyListSerializationFormat;
-(BOOL)_migrateLegacySLMAdjustments;
-(BOOL)_setDefaultSlowMotionAdjustmentsWithMainFileMetadata:(id)arg0 ;
-(BOOL)_setHDRTypeFromMetadata:(id)arg0 ;
-(BOOL)_shouldSetupVideoComplementForAsyncEditWithBaseVersion:(NSInteger)arg0 ;
-(BOOL)_updateAndStoreFinalPhotoResourceForResourceType:(unsigned int)arg0 version:(unsigned int)arg1 error:(*id)arg2 ;
-(BOOL)_updateAndStoreFinalVideoComplementResourceWithOutError:(*id)arg0 ;
-(BOOL)_updateKindSubtypeIfScreenshotWithCheckTask:(id)arg0 ;
-(BOOL)addSidecarFileAtIndex:(NSUInteger)arg0 sidecarURL:(id)arg1 withFilename:(id)arg2 compressedSize:(id)arg3 captureDate:(id)arg4 modificationDate:(id)arg5 uniformTypeIdentifier:(id)arg6 imageOrientation:(unsigned int)arg7 pathManager:(id)arg8 ;
-(BOOL)addSidecarFileInfo:(id)arg0 pathManager:(id)arg1 atIndex:(NSUInteger)arg2 mainFileMetadata:(id)arg3 ;
-(BOOL)anyInternalResourceIsLocal;
-(BOOL)attemptPromoteFromUnknownKindUsingCloudMaster;
-(BOOL)becomePhotoIrisWithMediaGroupUUID:(id)arg0 mainFileMetadata:(id)arg1 videoURL:(id)arg2 spatialOverCaptureURL:(id)arg3 videoDuration:(struct ? )arg4 stillDisplayTime:(struct ? )arg5 options:(NSUInteger)arg6 ;
-(BOOL)becomePhotoIrisWithMediaGroupUUID:(id)arg0 mainFileMetadata:(id)arg1 videoURL:(id)arg2 videoDuration:(struct ? )arg3 stillDisplayTime:(struct ? )arg4 options:(NSUInteger)arg5 ;
-(BOOL)becomeSyndicationLivePhotoWithVideoComplementContentType:(id)arg0 ;
-(BOOL)calculateAllowedForAnalysis;
-(BOOL)canMoveToTrash;
-(BOOL)canPerformDeleteOperation;
-(BOOL)canPerformEditOperation:(NSUInteger)arg0 ;
-(BOOL)checkAllResourcesRequiredForCPLDisableWithReachableBlock:(id)arg0 ;
-(BOOL)cleanUpMetadataPath;
-(BOOL)cloudHasSameOwnerAsAsset:(id)arg0 ;
-(BOOL)couldBeStoredInDCIM;
-(BOOL)eligibleForGuestAssetPromotion;
-(BOOL)hasAdjustedCPLThumbResource;
-(BOOL)hasAllThumbs;
-(BOOL)hasDeferredProcessingPreviewFile;
-(BOOL)hasGPS;
-(BOOL)hasJustBeenHidden;
-(BOOL)hasJustBeenShown;
-(BOOL)hasLegacyRequiredResourcesLocallyAvailable;
-(BOOL)hasMasterThumb;
-(BOOL)hasNonSlomoAdjustments;
-(BOOL)hasOriginalFile;
-(BOOL)hasOutstandingDeferredCaptureProcessing;
-(BOOL)hasScreenshotMetadata;
-(BOOL)hasTableThumbs;
-(BOOL)hasUnrenderedAsyncAdjustments;
-(BOOL)installExistingWallpaperComputeResourcesFileAtPath:(id)arg0 error:(*id)arg1 ;
-(BOOL)installFinalImageAndRemoveDeferredFilesWithFinalImageURL:(id)arg0 outError:(*id)arg1 ;
-(BOOL)installFinalVideoComplementAndRemoveDeferredFilesWithOutError:(*id)arg0 ;
-(BOOL)isCloudPlaceholder;
-(BOOL)isDeletableFromAssetsLibrary;
-(BOOL)isEditableFromAssetsLibrary;
-(BOOL)isEligibleForSearchIndexing;
-(BOOL)isFavorite;
-(BOOL)isHidden;
-(BOOL)isInTrash;
-(BOOL)isIncludedInCloudFeeds;
-(BOOL)isIncludedInHighlights;
-(BOOL)isIncludedInMoments;
-(BOOL)isLocalVideoKeyFrameValid;
-(BOOL)isLocatedAtCoordinates:(struct CLLocationCoordinate2D )arg0 ;
-(BOOL)isLocatedAtHome;
-(BOOL)isLoopingVideo;
-(BOOL)isOriginalRAW;
-(BOOL)isOriginalSRGB;
-(BOOL)isPanorama;
-(BOOL)isPartOfBurst;
-(BOOL)isPlayableVideo:(*id)arg0 ;
-(BOOL)isRAW;
-(BOOL)isRAWOnly;
-(BOOL)isRAWPlusJPEG;
-(BOOL)isRAWPlusJPEGWithRAWOnTop;
-(BOOL)isResourceAvailableForResourceType:(NSUInteger)arg0 ;
-(BOOL)isSavedPhotosAsset;
-(BOOL)isSyncableChange;
-(BOOL)isTimelapsePlaceholder;
-(BOOL)isTrashed;
-(BOOL)isValidForJournalPersistence;
-(BOOL)isValidForPerceptualProcessing;
-(BOOL)isValidTypeForPersistence;
-(BOOL)migrateLegacyVideoAdjustments;
-(BOOL)migrateLocationDataIfNeededAfterOTARestore:(BOOL)arg0 ;
-(BOOL)placeholder_shouldAllowServerCopy;
-(BOOL)placeholder_shouldBakeInAdjustments;
-(BOOL)placeholder_shouldFlattenLivePhoto;
-(BOOL)promoteDeferredPreviewToFinalImageWithOutError:(*id)arg0 ;
-(BOOL)promoteFromUnknownKind;
-(BOOL)promoteProxyToFinalVideoComplementWithOutError:(*id)arg0 ;
-(BOOL)promoteSemanticEnhancePreviewToFinalImage:(*id)arg0 ;
-(BOOL)promoteToGuestAsset:(*id)arg0 ;
-(BOOL)pruneLocalVideoKeyFrameImage;
-(BOOL)renderableAdjustmentDictionary:(*id)arg0 error:(*id)arg1 ;
-(BOOL)repairAssetScopeValidationErrors:(id)arg0 ;
-(BOOL)resetGuestAssetPromotion:(*id)arg0 ;
-(BOOL)resetVideoKeyFrameTime;
-(BOOL)resetVideoKeyFrameTimeAndDeleteKeyFrameResource;
-(BOOL)rm_createNewResourcesIn:(id)arg0 inManagedObjectContext:(id)arg1 ;
-(BOOL)sceneAnalysisWasPerformedOnLatestAdjustment;
-(BOOL)setAttributesFromMainFileURL:(id)arg0 mainFileMetadata:(id)arg1 savedAssetType:(short)arg2 bundleScope:(unsigned short)arg3 isPlaceholder:(BOOL)arg4 placeholderFileURL:(id)arg5 imageSource:(struct CGImageSource **)arg6 imageData:(*id)arg7 ;
-(BOOL)setCameraCaptureDeviceFromMetadata:(id)arg0 ;
-(BOOL)setCurrentAdjustmentAsOriginalAdjustment;
-(BOOL)setDefaultAdjustmentsIfNecessaryWithMainFileMetadata:(id)arg0 ;
-(BOOL)setImageInfoFromImageMetadata:(id)arg0 overwriteOriginalProperties:(BOOL)arg1 ;
-(BOOL)setTimeExifTimestampStringFromMetadata:(id)arg0 ;
-(BOOL)setVideoInfoFromFileAtURL:(id)arg0 mainFileMetadata:(id)arg1 fullSizeRenderURL:(id)arg2 overwriteOriginalProperties:(BOOL)arg3 ;
-(BOOL)setupPlaceholderAssetWithRequiredPropertiesFromSourceAsset:(id)arg0 placeholderAssetUUID:(id)arg1 bundleScope:(unsigned short)arg2 momentShare:(id)arg3 importSessionID:(id)arg4 bakeInAdjustmentsFromSourceAsset:(BOOL)arg5 flattenLivePhoto:(BOOL)arg6 copyTitleDescriptionAndKeywords:(BOOL)arg7 copyCameraProcessingAdjustmentResources:(BOOL)arg8 library:(id)arg9 ;
-(BOOL)shouldIncludeInCPLCounts;
-(BOOL)shouldPurgeSyndicationResourcesWithChangedValues:(id)arg0 ;
-(BOOL)shouldSimulateQuarantineOriginalImageResourceOnPush;
-(BOOL)shouldSyncToSPL;
-(BOOL)shouldUseNonAdjustedVideo;
-(BOOL)supportsCloudUpload;
-(BOOL)syndicationOriginalResourcesAreLocal;
-(BOOL)unQuarantineIfPossible;
-(BOOL)updateAttributesFromMainFileURL:(id)arg0 mainFileMetadata:(id)arg1 fullSizeRenderURL:(id)arg2 ;
-(BOOL)updateExtendedAttributesWithError:(*id)arg0 ;
-(BOOL)updateKindSubtypeIfScreenshot;
-(BOOL)updateKindSubtypeIfScreenshotWithMetadata:(id)arg0 ;
-(BOOL)updatePlaybackVariationAndLoopingStyleFromAVAsset:(id)arg0 ;
-(BOOL)updatePlaybackVariationAndLoopingStyleFromVariation:(unsigned short)arg0 ;
-(BOOL)updatePlaybackVariationAndStyleFromOriginalMetadata:(id)arg0 ;
-(BOOL)validForPersistenceChangedForChangedKeys:(id)arg0 ;
-(BOOL)validateForInsert:(*id)arg0 ;
-(BOOL)validateForUpdate:(*id)arg0 ;
-(BOOL)visibilityStateIsEqualToState:(short)arg0 ;
-(NSInteger)_plAdjustmentBaseVersionFromCPLAdjustmentSourceType:(NSUInteger)arg0 ;
-(NSInteger)_prepareFileSystemResourcesForAdjustmentsWithCurrentAdjustmentBaseVersion:(NSInteger)arg0 penultimateRenderedJPEGData:(id)arg1 penultimateRenderedVideoContentURL:(id)arg2 penultimateRenderedVideoComplementContentURL:(id)arg3 fileIngestionType:(NSInteger)arg4 ;
-(NSInteger)cloudSharedAssetPlaceholderKind;
-(NSInteger)compareToAsset:(id)arg0 ;
-(NSInteger)originalImageOrientation;
-(NSUInteger)_countForCommentRelationshipNamed:(id)arg0 inverseRelationshipName:(id)arg1 ;
-(NSUInteger)bestResourceTypeForAdjustedFingerPrint;
-(NSUInteger)cplAssetSubtypeFromPLAssetSubtype:(short)arg0 ;
-(NSUInteger)cplBurstFlagsFromPLAvalancheType:(int)arg0 ;
-(NSUInteger)deferredProcessingHash;
-(NSUInteger)masterResourceTypeForAdjustedAssetResourceType:(NSUInteger)arg0 flattenLivePhoto:(BOOL)arg1 ;
-(NSUInteger)originalResourceChoice;
-(id)_anyOriginalNonDerivativeAlternateImageResource;
-(id)_avAssetProxyForFullSize:(BOOL)arg0 allowReadFromFile:(BOOL)arg1 ;
-(id)_availableCloudResourcesForPhotosRequireUnadjusted:(BOOL)arg0 allowPenultimate:(BOOL)arg1 ;
-(id)_calculateCloudAdjustmentFingerprintFromAdjustmentPListAndCPLResources;
-(id)_cloudSharedPathWithExtension:(id)arg0 ;
-(id)_compactDebugDescription;
-(id)_cplRelationsForAssetInLibrary:(id)arg0 ;
-(id)_createCPLResourceFromResourcePath:(id)arg0 withResourceType:(NSUInteger)arg1 uniformTypeIdentifier:(id)arg2 scopedIdentifier:(id)arg3 ;
-(id)_createImageResourceForResourceType:(NSUInteger)arg0 withPreviewImagePath:(id)arg1 scopedIdentifier:(id)arg2 forMaster:(BOOL)arg3 ;
-(id)_createJPEGResourcesFromFullSizePath:(id)arg0 withScopedIdentifier:(id)arg1 forMaster:(BOOL)arg2 ;
-(id)_createJPEGResourcesFromFullSizePath:(id)arg0 withScopedIdentifier:(id)arg1 forMaster:(BOOL)arg2 forResourceTypes:(id)arg3 ;
-(id)_createVideoResourceFromVideoURL:(id)arg0 withResourceType:(NSUInteger)arg1 scopedIdentifier:(id)arg2 applyVideoAdjustments:(BOOL)arg3 forMaster:(BOOL)arg4 forPhotoIris:(BOOL)arg5 ;
-(id)_effectiveMetadataForMainFileURL:(id)arg0 mainFileMetadata:(id)arg1 fullSizeRenderURL:(id)arg2 shouldCache:(BOOL)arg3 ;
-(id)_generateDeferredAdjustmentWithImageConversionClient:(id)arg0 videoConversionClient:(id)arg1 reason:(id)arg2 retryNumber:(NSUInteger)arg3 completion:(id)arg4 ;
-(id)_generatePosterFrameForVideoAtURL:(id)arg0 withResourceType:(NSUInteger)arg1 scopedIdentifier:(id)arg2 forMaster:(BOOL)arg3 ;
-(id)_generatePosterFrameResourcesFromVideoURL:(id)arg0 withScopedIdentifier:(id)arg1 forMaster:(BOOL)arg2 ;
-(id)_generateVideoResourcesFromURL:(id)arg0 withScopedIdentifier:(id)arg1 forMaster:(BOOL)arg2 ;
-(id)_imagePropertiesFromMetadata:(id)arg0 ;
-(id)_mediaGroupUUIDFromPersistence:(id)arg0 ;
-(id)_nameForContributor:(id)arg0 ;
-(id)_pathForSidecarResource:(id)arg0 ;
-(id)_persistedResourceForResourceIdentity:(id)arg0 error:(*id)arg1 ;
-(id)_prettyDescription;
-(id)_rm_localResourceURLForResource:(id)arg0 ;
-(id)_scopeIdentifier;
-(id)_sourceURLForAsyncEditWithBaseVersion:(NSInteger)arg0 ;
-(id)_videoComplementDerivativeResourcesForMaster:(id)arg0 ;
-(id)activityViewController:(id)arg0 itemForActivityType:(id)arg1 ;
-(id)activityViewControllerPlaceholderItem:(id)arg0 ;
-(id)addLegacyFaceWithRelativeRect:(struct CGRect )arg0 identifier:(short)arg1 albumUUID:(id)arg2 ;
-(id)adjustedFileURLs;
-(id)adjustedPathForCPLResourceType:(NSUInteger)arg0 ;
-(id)adjustmentDataResource;
-(id)allAssetCPLResources;
-(id)allCPLResourcesForPruning;
-(id)allFileBackedResources;
-(id)allFileExtensions;
-(id)allMasterCPLResources;
-(id)allRequiredResourcesForCPLDisable;
-(id)analysisStateForWorkerType:(short)arg0 ;
-(id)assetComparisonSortDescriptors;
-(id)assetResourceForCPLType:(NSUInteger)arg0 ;
-(id)assetURLForSidecarFile:(id)arg0 ;
-(id)assetURLWithExtension:(id)arg0 ;
-(id)attemptCameraProcessingAdjustmentWithImageConversionClient:(id)arg0 videoConversionClient:(id)arg1 isOnDemand:(BOOL)arg2 completionHandler:(id)arg3 ;
-(id)avAssetProxyForFullSizeAllowReadFromFile:(BOOL)arg0 ;
-(id)avAssetProxyForOriginalAllowReadFromFile:(BOOL)arg0 ;
-(id)availableAdjustedCloudResourcesForPhotos:(BOOL)arg0 ;
-(id)availableUnadjustedCloudResourcesForPhotos;
-(id)avalanchePickDescription;
-(id)bestAvaliableAdjustedResource;
-(id)cameraMake;
-(id)cameraModel;
-(id)cloudSharedAssetPathForPlaceholderKind:(short)arg0 ;
-(id)cplAssetChangeWithMasterScopedIdentifier:(id)arg0 withChangeType:(NSUInteger)arg1 shouldGenerateDerivatives:(BOOL)arg2 inLibrary:(id)arg3 ;
-(id)cplFullRecord;
-(id)cplMasterChangeInLibrary:(id)arg0 shouldGenerateDerivatives:(BOOL)arg1 ;
-(id)createPlaceNamesSortedByCategoryAllowFallbackToCompoundNameInfo:(BOOL)arg0 ;
-(id)createResourcesForAssetInPhotoLibrary:(id)arg0 shouldGenerateDerivatives:(BOOL)arg1 ;
-(id)createResourcesForMaster:(id)arg0 shouldGenerateDerivatives:(BOOL)arg1 inPhotoLibrary:(id)arg2 ;
-(id)decodedFaceRegions;
-(id)documentObservation;
-(id)duplicateAlbum;
-(id)duplicateSortPropertyNames;
-(id)duplicateSortPropertyNamesSkip;
-(id)evaluateWhiteBalanceValueWithOriginalExifProperties:(id)arg0 ;
-(id)existingCloudMasterNeedsRepush:(*BOOL)arg0 ;
-(id)extendedAttributesCreateIfNeeded:(BOOL)arg0 ;
-(id)faceDescription;
-(id)fetchOrCreateResourceWithIdentity:(id)arg0 ;
-(id)fetchResourceWithIdentity:(id)arg0 error:(*id)arg1 ;
-(id)fetchResourcesForAssetVersions:(id)arg0 allowDerivatives:(BOOL)arg1 additionalPredicate:(id)arg2 relationshipKeyPathsForPrefetching:(id)arg3 error:(*id)arg4 ;
-(id)fetchSourceAssetForDuplicationIfExists;
-(id)fileURLForAdjustedLargeThumbnailFile;
-(id)fileURLForAdjustedMediumThumbnailFile;
-(id)fileURLForAsyncAdjustedRenderPreviewImage;
-(id)fileURLForCurrentDeferredProcessingPreviewFile;
-(id)fileURLForFullsizeRenderImage;
-(id)fileURLForFullsizeRenderVideo;
-(id)fileURLForHypotheticalSidecarFileWithFilename:(id)arg0 ;
-(id)fileURLForMediumThumbnailFile;
-(id)fileURLForMetadataWithExtension:(id)arg0 ;
-(id)fileURLForNonAdjustedLargeThumbnailFile;
-(id)fileURLForNonAdjustedMediumThumbnailFile;
-(id)filterCameraProcessingAdjustmentResourcesFromPlaceholderCloudResources:(id)arg0 ;
-(id)firstPersistedResourceMatching:(id)arg0 ;
-(id)formattedCameraModel;
-(id)generateDeferredAdjustmentWithImageConversionClient:(id)arg0 videoConversionClient:(id)arg1 reason:(id)arg2 completion:(id)arg3 ;
-(id)generatePortraitAdjustment:(*id)arg0 ;
-(id)globalUUID;
-(id)imageDataForThumbGenerationAndIfNeededRAWUTI:(*id)arg0 isPreviewSource:(*BOOL)arg1 ;
-(id)imageProperties;
-(id)imageWithFormat:(unsigned short)arg0 ;
-(id)indexSheetImage;
-(id)largestAvailableDataRepresentationAndType:(*id)arg0 ;
-(id)lastUploadAttemptDate;
-(id)legacyFaceWithIdentifier:(short)arg0 ;
-(id)lensModel;
-(id)localDateAndCreateIfNeededWithLocalDateCreator:(id)arg0 ;
-(id)localResourcePathForMasterResource:(id)arg0 ;
-(id)localResourcePathForMasterResourceWithCPLType:(NSUInteger)arg0 andUTI:(id)arg1 ;
-(id)localVideoKeyFrameResource;
-(id)managedAssetForPhotoLibrary:(id)arg0 ;
-(id)masterFingerPrintCacheIfNecessaryAndAdjustedFingerPrint:(*id)arg0 error:(*id)arg1 ;
-(id)masterFingerPrintCacheIfNecessaryAndAdjustedFingerPrint:(*id)arg0 fullsizeRenderImageIfNecessary:(BOOL)arg1 error:(*id)arg2 ;
-(id)masterResourceForCPLType:(NSUInteger)arg0 ;
-(id)mediaMetadataForResourceVersion:(unsigned int)arg0 mediaMetadataType:(*id)arg1 ;
-(id)mediaMetadataVirtualResources;
-(id)metadataFromMediaPropertiesOrOriginalResource;
-(id)mutableAlbumsBeingCustomKeyAssetFor;
-(id)mutableAlbumsBeingKeyAssetFor;
-(id)mutableAlbumsBeingSecondaryKeyAssetFor;
-(id)mutableAlbumsBeingTertiaryKeyAssetFor;
-(id)mutableDetectedFaces;
-(id)newFullSizeImage;
-(id)nonAdjustedPathForCPLResourceType:(NSUInteger)arg0 ;
-(id)nonDynamicOriginalUTI;
-(id)nonPersistedResources;
-(id)originalVideoComplementUniformTypeIdentifier;
-(id)overflowAdjustmentDataResource;
-(id)pasteBoardRepresentation;
-(id)pathForAdjustedFullsizeImageFile;
-(id)pathForAdjustedLargeSizeImageFile;
-(id)pathForAdjustedLargeThumbnailFile;
-(id)pathForAdjustedLargeVideoFile;
-(id)pathForAdjustedMediaMetadataFile;
-(id)pathForAdjustedMediumHDRVideoFile;
-(id)pathForAdjustedMediumThumbnailFile;
-(id)pathForAdjustedMediumVideoFile;
-(id)pathForAdjustedSmallVideoFile;
-(id)pathForAdjustmentDataFile;
-(id)pathForAsyncAdjustedRenderPreviewImageFile;
-(id)pathForBestAvailableFullsizeRenderImageFileOutIsSubstandard:(*BOOL)arg0 ;
-(id)pathForCPLResourceType:(NSUInteger)arg0 adjusted:(BOOL)arg1 ;
-(id)pathForCameraMetadataDiagnosticFile;
-(id)pathForCameraMetadataFile;
-(id)pathForCameraSpatialOverCaptureMetadataDiagnosticFile;
-(id)pathForDeferredProcessingPreviewFile;
-(id)pathForDeferredVideoComplementFile;
-(id)pathForFullsizeImageFile;
-(id)pathForFullsizeRenderImageFileWithUTI:(id)arg0 ;
-(id)pathForLargeSizeImageFile;
-(id)pathForLocalVideoKeyFrame;
-(id)pathForMediaMetadataFile;
-(id)pathForMediumVideoFile;
-(id)pathForMetadataWithExtension:(id)arg0 ;
-(id)pathForMutationsDirectory;
-(id)pathForNonAdjustedFullsizeImageFile;
-(id)pathForNonAdjustedLargeSizeImageFile;
-(id)pathForNonAdjustedLargeThumbnailFile;
-(id)pathForNonAdjustedLargeVideoFile;
-(id)pathForNonAdjustedMediumHDRVideoFile;
-(id)pathForNonAdjustedMediumThumbnailFile;
-(id)pathForNonAdjustedMediumVideoFile;
-(id)pathForNonAdjustedSmallVideoFile;
-(id)pathForOriginalVideoComplementDiagnosticFile;
-(id)pathForPenultimateFullsizeRenderImageFileWithUTI:(id)arg0 ;
-(id)pathForReframeDiagnosticDirectory;
-(id)pathForReframeDiagnosticFile;
-(id)pathForSpatialOverCaptureDiagnosticFile;
-(id)pathForSubstandardFullsizeRenderImageFile;
-(id)pathForTransientVideoPosterFramePreview;
-(id)pathForVideoComplementFile;
-(id)pathForVideoMetadataFile;
-(id)pathForWallpaperComputeResourcesFile;
-(id)pathToOriginalVideoFile;
-(id)payloadForChangedKeys:(id)arg0 ;
-(id)payloadID;
-(id)payloadIDForTombstone:(id)arg0 ;
-(id)penultimateImageResource;
-(id)persistedAdjustedResources;
-(id)persistedResourcesMatching:(id)arg0 ;
-(id)persistedResourcesWithRecipeID:(unsigned int)arg0 andVersion:(unsigned int)arg1 ;
-(id)photoDataCPLResourceDestinationDirectoryCreateIfNeededWithIdentifier:(id)arg0 ;
-(id)photoIrisSidecarIgnoringSubtype:(BOOL)arg0 ;
-(id)pictureTransferProtocolAssetsWithConversionSupport:(id)arg0 ;
-(id)pl_photoLibrary;
-(id)primaryStoreOriginalResource;
-(id)resourceForCPLType:(NSUInteger)arg0 version:(unsigned int)arg1 ;
-(id)resourcesWithVersion:(unsigned int)arg0 ;
-(id)reverseGeoDescription;
-(id)rm_applyResourcesFromAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(id)rm_cplExpungeableMasterResourceStates;
-(id)rm_cplMasterResourceForResourceType:(NSUInteger)arg0 ;
-(id)rm_cplMasterResourcesFromCloudMaster:(id)arg0 addOriginalResourceMode:(BOOL)arg1 ;
-(id)rm_cplResourceForResourceType:(NSUInteger)arg0 ;
-(id)scopedIdentifier;
-(id)shortenedFilePath;
-(id)sidecarFileMatchingContentType:(id)arg0 requireExactMatch:(BOOL)arg1 requireSort:(BOOL)arg2 ;
-(id)sidecarWithResourceObjectID:(id)arg0 ;
-(id)sidecars;
-(id)sortPlaceholderCloudResourcesByOrderOfCloudReReference:(id)arg0 ;
-(id)storedResourceForCPLResource:(id)arg0 asset:(id)arg1 adjusted:(BOOL)arg2 ;
-(id)storedResourceForExternalResource:(id)arg0 asset:(id)arg1 ;
-(id)syncDescription;
-(id)syndicationDescription;
-(id)syndicationFileIdentifierForResourceType:(unsigned int)arg0 version:(unsigned int)arg1 recipeID:(unsigned int)arg2 utiString:(id)arg3 ;
-(id)syndicationOriginalResource;
-(id)syndicationOriginalVideoComplementResource;
-(id)syndicationResourceURLForResourceType:(unsigned int)arg0 version:(unsigned int)arg1 recipeID:(unsigned int)arg2 utiString:(id)arg3 error:(*id)arg4 ;
-(id)syndicationResourcesDescription;
-(id)thumbnailIdentifier;
-(id)unadjustedDerivativeImageURLs;
-(id)urlForSideCarImageFile;
-(id)userAddCloudSharedCommentWithText:(id)arg0 ;
-(id)validateForAssetID:(id)arg0 resourceIdentity:(id)arg1 ;
-(id)videoComplementData;
-(int)_avalancheTypeFromCplBurstFlags:(NSUInteger)arg0 ;
-(int)cloudCommentsStatusForOwnedAsset:(BOOL)arg0 ;
-(short)uploadAttempts;
-(struct ? )videoKeyFrameTime;
-(struct CGSize )_targetSizeForInputSize:(struct CGSize )arg0 maxPixelSize:(NSUInteger)arg1 ;
-(struct CGSize )originalImageSize;
-(struct CGSize )targetSizeForInputSize:(struct CGSize )arg0 maxPixelSize:(NSUInteger)arg1 ;
-(unsigned int)updateAdjustmentRenderTypes:(unsigned int)arg0 withAdjustmentData:(id)arg1 formatIdentifier:(id)arg2 formatVersion:(id)arg3 ;
-(unsigned int)updateAdjustmentRenderTypes:(unsigned int)arg0 withAdjustmentState:(unsigned short)arg1 ;
-(unsigned int)updateAdjustmentRenderTypes:(unsigned int)arg0 withDepthType:(short)arg1 ;
-(unsigned int)updateAdjustmentRenderTypes:(unsigned int)arg0 withPlaybackVariation:(unsigned short)arg1 ;
-(unsigned short)_playbackVariationWithAdjustmentRenderTypes:(unsigned int)arg0 ;
-(unsigned short)expectedBundleScopeBasedOnAssetLockingProperties;
-(unsigned short)expectedDeferredProcessingNeededOnAssetCreation;
-(unsigned short)playbackVariationFromAVAsset:(id)arg0 isLivePhotoVideoComplement:(BOOL)arg1 ;
-(void)_appendAssetTextDataToAsset:(id)arg0 ;
-(void)_appendBusinessCategories:(id)arg0 toAsset:(id)arg1 ;
-(void)_appendBusinessNames:(id)arg0 toAsset:(id)arg1 ;
-(void)_appendContributorToAsset:(id)arg0 ;
-(void)_appendDateCreatedToAsset:(id)arg0 dateFormatter:(id)arg1 withSynonyms:(id)arg2 ;
-(void)_appendExifDataToAsset:(id)arg0 ;
-(void)_appendFavoriteToAsset:(id)arg0 ;
-(void)_appendFilenameToAsset:(id)arg0 ;
-(void)_appendGEODataToAsset:(id)arg0 ;
-(void)_appendHolidays:(id)arg0 toAsset:(id)arg1 ;
-(void)_appendHomeToAsset:(id)arg0 ;
-(void)_appendKeywords:(id)arg0 toAsset:(id)arg1 ;
-(void)_appendLibraryScopeToAsset:(id)arg0 ;
-(void)_appendMeanings:(id)arg0 withSynonyms:(id)arg1 toAsset:(id)arg2 ;
-(void)_appendMediaTypesToAsset:(id)arg0 ;
-(void)_appendOCRTextForAsset:(id)arg0 documentObservation:(id)arg1 ;
-(void)_appendPersonsToAsset:(id)arg0 ;
-(void)_appendPublicEventCategories:(id)arg0 withSynonyms:(id)arg1 toAsset:(id)arg2 ;
-(void)_appendPublicEventStrings:(id)arg0 toAsset:(id)arg1 forSearchIndexCategory:(NSUInteger)arg2 ;
-(void)_appendSavedFromAppToAsset:(id)arg0 ;
-(void)_appendSceneClassificationsToAsset:(id)arg0 sceneTaxonomyProvider:(id)arg1 ;
-(void)_appendSocialGroupIdentifiers:(id)arg0 toAsset:(id)arg1 ;
-(void)_appendWorkText:(id)arg0 toAsset:(id)arg1 ;
-(void)_applyFaceChangeToCPLAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(void)_applyPropertiesChangeToCPLAssetChange:(id)arg0 withMasterScopedIdentifier:(id)arg1 inLibrary:(id)arg2 ;
-(void)_applyPropertiesFromCloudMaster:(id)arg0 ;
-(void)_applyResourceChangeToCPLAsset:(id)arg0 forChangeType:(NSUInteger)arg1 shouldGenerateDerivatives:(BOOL)arg2 inLibrary:(id)arg3 ;
-(void)_applySharingChangeToCPLAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(void)_asyncGenerateRenderImageFileWithSize:(struct CGSize )arg0 formatIdentifier:(id)arg1 formatVersion:(id)arg2 adjustmentDataBlob:(id)arg3 originalImageFilePath:(id)arg4 originalImageEXIFOrientation:(NSInteger)arg5 renderedImageFilePath:(id)arg6 completionHandler:(id)arg7 ;
-(void)_cleanupPenultimateResources;
-(void)_clearAcceptableCropRect;
-(void)_clearOverallAestheticScore;
-(void)_clearPreferredCropRect;
-(void)_coordinatesFromDoubles:(CGFloat)arg0 faceMaxX:(CGFloat)arg1 faceMinY:(CGFloat)arg2 faceMaxY:(CGFloat)arg3 minX:(*CGFloat)arg4 maxX:(*CGFloat)arg5 minY:(*CGFloat)arg6 maxY:(*CGFloat)arg7 ;
-(void)_createPhotoResourcesForMaster:(id)arg0 withOriginalResource:(id)arg1 intoMasterResources:(id)arg2 shouldGenerateDerivatives:(BOOL)arg3 inPhotoLibrary:(id)arg4 ;
-(void)_createVideoResourcesForMaster:(id)arg0 intoMasterResources:(id)arg1 shouldGenerateDerivatives:(BOOL)arg2 ;
-(void)_debugPrintAdjustmentState;
-(void)_deleteComputedAttributes;
-(void)_deleteDeferredIntermediatesForDeferredPhotoIdentifier:(id)arg0 withFinalizer:(id)arg1 ;
-(void)_deleteMediaAnalysisAttributes;
-(void)_getLargestAvailableDataRepresentation:(*id)arg0 type:(*id)arg1 ;
-(void)_handleHighlightRelationshipChangeForKey:(id)arg0 forAssetCountKey:(id)arg1 newValue:(id)arg2 ;
-(void)_ingestAndApplyMetadataChangesFromAdjustmentRenderedContentURL:(id)arg0 fullSizeRenderURL:(id)arg1 renderedVideoComplementContentURL:(id)arg2 videoPosterContentURL:(id)arg3 videoPosterRenderURL:(id)arg4 ingestionType:(NSInteger)arg5 updateAdjustmentDictionary:(id)arg6 mainFileMetadata:(id)arg7 shouldUpdateAttributes:(BOOL)arg8 isSubstandardRender:(BOOL)arg9 isRevertToOriginal:(BOOL)arg10 ;
-(void)_loadReverseGeoIfNeeded;
-(void)_populateSyndicationAssetWithAssetType:(short)arg0 subtype:(short)arg1 contentType:(id)arg2 videoComplementContentType:(id)arg3 originalFilename:(id)arg4 ;
-(void)_preserveRelationshipsOfDeletedGuestAsset:(id)arg0 ;
-(void)_promptForNilScopeIdentifierRadar;
-(void)_reloadWidgetTimelineIfNeeded:(id)arg0 ;
-(void)_removeAdjustmentDataResources;
-(void)_resetSceneAnalysisStates;
-(void)_rm_insertResource:(id)arg0 forOtherDuplicatedAssetInMaster:(id)arg1 inPhotoLibrary:(id)arg2 ;
-(void)_setAllowedForAnalysisDependentValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setBurstUuidFromMetadata:(id)arg0 ;
-(void)_setColorSpaceNameFromMetadata:(id)arg0 ;
-(void)_setHDRGainFromMetadata:(id)arg0 ;
-(void)_setOriginalSizeAndOrientationFromMetadata:(id)arg0 ;
-(void)_setPhotoIrisPropertiesFromMetadata:(id)arg0 ;
-(void)_setSOCGroupIdentifierFromMetadata:(id)arg0 ;
-(void)_setSizeAndOrientationFromMetadata:(id)arg0 ;
-(void)_setVideoComplementData:(id)arg0 ;
-(void)_setupMediaConversionSourceURLCollection:(id)arg0 destinationURLCollection:(id)arg1 baseVersion:(NSInteger)arg2 ;
-(void)_triggerGuestAssetSyncUpdateWithLibraryServicesManager:(id)arg0 ;
-(void)_updateAssetSubtypeForCPLAssetChange:(id)arg0 ;
-(void)_updateAssetSubtypeFromCPLAssetSubtype:(NSUInteger)arg0 ;
-(void)_updateBurstFlagsForCPLAssetChange:(id)arg0 photoLibrary:(id)arg1 ;
-(void)_updateCoreExtendedAttributes:(id)arg0 fromMetadata:(id)arg1 ;
-(void)_updateDerivativesAndThumbnails:(BOOL)arg0 withPreviewImage:(id)arg1 thumbnailImage:(id)arg2 metadata:(id)arg3 didRevertToOriginal:(BOOL)arg4 updateInternalResources:(BOOL)arg5 isSubstandardRender:(BOOL)arg6 isDeferred:(BOOL)arg7 ;
-(void)_updateDestinationAssetCopyStateOnCMMAsset;
-(void)_updateIMCoreSyndicationForIdentifier:(id)arg0 hide:(BOOL)arg1 ;
-(void)_updateOriginalResourceChoice;
-(void)_updatePackedBadgeAttributesIfNeeded:(int)arg0 ;
-(void)_updatePhotoIrisTemporalMetadataFromVideoComplementAVAsset:(id)arg0 ;
-(void)_updatePhotoIrisVisibilityStateFromVideoComplementAVAsset:(id)arg0 ;
-(void)_updateSyndicationState:(unsigned short)arg0 enabled:(BOOL)arg1 logPrefix:(id)arg2 ;
-(void)_updateSyndicationStateWithSavedToLibrary:(BOOL)arg0 ;
-(void)_writeOutAdjustmentsToFile:(id)arg0 ;
-(void)addComment:(id)arg0 ;
-(void)addSearchIndexContentsToAsset:(id)arg0 graphData:(id)arg1 dateFormatter:(id)arg2 keywords:(id)arg3 synonymsDictionaries:(id)arg4 sceneTaxonomyProvider:(id)arg5 documentObservation:(id)arg6 ;
-(void)applyFacesFromAssetChange:(id)arg0 inSyncContext:(id)arg1 ;
-(void)applyPropertiesFromAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(void)applySharingPropertiesFromAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(void)applyTrashedState:(short)arg0 ;
-(void)awakeFromFetch;
-(void)awakeFromInsert;
-(void)awakeFromSnapshotEvents:(NSUInteger)arg0 ;
-(void)copyAuxiliaryImagesFromImageSource:(struct CGImageSource *)arg0 toDestination:(struct CGImageDestination *)arg1 fromImageAtIndex:(NSUInteger)arg2 imageProperties:(id)arg3 applyingOrientation:(short)arg4 scalingToLongSideLength:(NSInteger)arg5 ;
-(void)createMasterIfNecessaryInLibrary:(id)arg0 ;
-(void)dealloc;
-(void)delete;
-(void)deleteAdjustedResources;
-(void)deleteComment:(id)arg0 ;
-(void)deleteFromDatabaseOnly;
-(void)deleteFromDatabaseOnlyWithReason:(id)arg0 ;
-(void)deleteResourceForSidecarRepresentation:(id)arg0 ;
-(void)deleteResourcesWithRecipeID:(unsigned int)arg0 andVersion:(unsigned int)arg1 ;
-(void)deleteWithReason:(id)arg0 ;
-(void)didSave;
-(void)didSetCustomDateCreated;
-(void)didSetCustomLocation;
-(void)didTurnIntoFault;
-(void)expungeTrashedSpatialOverCaptureResources;
-(void)fixupMemoriesWithMissingKeyAsset;
-(void)fixupPersonsWithMissingKeyAsset;
-(void)fixupPlaceholderAssetWithSavedAssetType:(short)arg0 ;
-(void)generateAndUpdateThumbnailsWithPreviewImage:(id)arg0 thumbnailImage:(id)arg1 fromImageSource:(struct CGImageSource *)arg2 imageData:(id)arg3 forceSRGBConversion:(BOOL)arg4 ;
-(void)generateAndUpdateThumbnailsWithPreviewImage:(id)arg0 thumbnailImage:(id)arg1 fromImageSource:(struct CGImageSource *)arg2 imageData:(id)arg3 metadata:(id)arg4 forceSRGBConversion:(BOOL)arg5 saveCameraPreviewWellImage:(BOOL)arg6 ;
-(void)generateLargeThumbnailFileIfNecessary;
-(void)generateThumbnailsWithImageSource:(struct CGImageSource *)arg0 imageData:(id)arg1 metadata:(id)arg2 allowMediumPreview:(BOOL)arg3 forceSRGBConversion:(BOOL)arg4 outSmallThumbnail:(*id)arg5 outLargeThumbnail:(*id)arg6 isPreviewSource:(BOOL)arg7 ;
-(void)getFileURL:(*id)arg0 originalFilename:(*id)arg1 uti:(*id)arg2 fileSize:(*NSUInteger)arg3 forSidecarMatchingUTI:(id)arg4 requireExactMatch:(BOOL)arg5 ;
-(void)incrementUploadAttempts;
-(void)insertTableThumbImageRequestHints;
-(void)invalidateThumbnailIfNeededAfterMasterResourceChangeInLibrary:(id)arg0 ;
-(void)markAsUnavailableCloudResourceOfType:(NSUInteger)arg0 ;
-(void)markForNeedingFaceDetection;
-(void)persistMetadataToFileURL:(id)arg0 ;
-(void)persistMetadataToFilesystem;
-(void)postProcessResourceDependentPropertyChangesFromAssetChange:(id)arg0 inLibrary:(id)arg1 ;
-(void)preGateForReframingWithSOCMetadata:(id)arg0 ;
-(void)prepareForDeletion;
-(void)purgeSyndicationResources;
-(void)recalculateImageRequestHints;
-(void)recalculateImageRequestHintsForResource:(id)arg0 afterLocalAvailabilityChangeFrom:(short)arg1 previousDataStoreKey:(id)arg2 ;
-(void)reconsiderLocalAvailabilityTargetsForResourceGeneratableByAvailabilityWorker;
-(void)reevaluateCameraProcessingAdjustmentState;
-(void)registerForChanges;
-(void)rejectSyndicatedAsset;
-(void)removeAssetFromRelatedSuggestionsAndFixupSuggestions;
-(void)removeFromDuplicateAlbum;
-(void)removeLibraryScopeAndContributors;
-(void)removeLocalFileForResource:(id)arg0 ;
-(void)removeLocalFileForResource:(id)arg0 allowDCIMPath:(BOOL)arg1 ;
-(void)removeSceneClassifications;
-(void)removeSidecar:(id)arg0 ;
-(void)removeTracesOfDeferredSOC;
-(void)reportSharedAssetIncrementalChange:(id)arg0 ;
-(void)requestDeletionOfDeferredPhotoProcessingIntermediates;
-(void)resetFaceAnalysisStates;
-(void)restoreSyndicatedAsset;
-(void)revalidateFaceAreaPoints;
-(void)revertToOriginal;
-(void)rm_createMasterResourcesForCPLResources:(id)arg0 master:(id)arg1 inLibrary:(id)arg2 ;
-(void)rm_createMasterResourcesIn:(id)arg0 inManagedObjectContext:(id)arg1 ;
-(void)setAdjustmentInfo:(id)arg0 mainFileMetadata:(id)arg1 ;
-(void)setAdjustments:(id)arg0 mainFileMetadata:(id)arg1 shouldUpdateAttributes:(BOOL)arg2 ;
-(void)setAdjustments:(id)arg0 renderedContentURL:(id)arg1 penultimateRenderedJPEGData:(id)arg2 penultimateRenderedVideoContentURL:(id)arg3 isSubstandardRender:(BOOL)arg4 deferredProcessingNeeded:(BOOL)arg5 fullSizeRenderSize:(struct CGSize )arg6 fullSizeRenderDuration:(CGFloat)arg7 renderedVideoComplementContentURL:(id)arg8 penultimateRenderedVideoComplementContentURL:(id)arg9 renderedVideoPosterContentURL:(id)arg10 mainFileMetadata:(id)arg11 shouldUpdateAttributes:(BOOL)arg12 fileIngestionType:(NSInteger)arg13 shouldGenerateThumbnails:(BOOL)arg14 ;
-(void)setAdjustments:(id)arg0 renderedContentURL:(id)arg1 penultimateRenderedJPEGData:(id)arg2 penultimateRenderedVideoContentURL:(id)arg3 isSubstandardRender:(BOOL)arg4 fullSizeRenderSize:(struct CGSize )arg5 fullSizeRenderDuration:(CGFloat)arg6 renderedVideoComplementContentURL:(id)arg7 penultimateRenderedVideoComplementContentURL:(id)arg8 renderedVideoPosterContentURL:(id)arg9 mainFileMetadata:(id)arg10 shouldUpdateAttributes:(BOOL)arg11 fileIngestionType:(NSInteger)arg12 ;
-(void)setDestinationAssetCopyStateOnSourceAsset:(short)arg0 ;
-(void)setImageInfoFromOriginalImageMetadata:(id)arg0 ;
-(void)setKeywordsFromImageProperties:(id)arg0 ;
-(void)setLastUploadAttemptDate:(id)arg0 ;
-(void)setMetadataFromCustomRenderedValue:(NSInteger)arg0 ;
-(void)setOriginalResourceChoice:(NSUInteger)arg0 ;
-(void)setOriginalSizeAndOrientationFromImageProperties:(id)arg0 ;
-(void)setSizeAndOrientationFromImageProperties:(id)arg0 ;
-(void)setSyndicationAttributesFromMainFileURL:(id)arg0 metadata:(id)arg1 ;
-(void)setSyndicationFilenameAndDirectoryWithOriginalFilename:(id)arg0 ;
-(void)setSyndicationLivePhotoAttributesFromMainFileURL:(id)arg0 metadata:(id)arg1 videoComplementFileURL:(id)arg2 ;
-(void)setThumbnailDataFromImageProperties:(id)arg0 ;
-(void)setUBFFilenameAndDirectoryWithOriginalUniformTypeIdentifier:(id)arg0 originalFilename:(id)arg1 ;
-(void)setUploadAttempts:(short)arg0 ;
-(void)setVideoInfoOnMasterFromAVAsset:(id)arg0 ;
-(void)setVideoKeyFrameTime:(struct ? )arg0 ;
-(void)setWasGuestAsset:(BOOL)arg0 ;
-(void)setupPropertiesOnExistingMaster:(id)arg0 ;
-(void)setupPropertiesOnNewCloudMaster:(id)arg0 withPlaceholderSourceAsset:(id)arg1 uniformTypeIdentifier:(id)arg2 ;
-(void)simulateQuarantineOriginalImageResourceOnPush:(id)arg0 ;
-(void)synchronizeWithPersistedFileSystemAttributes;
-(void)synchronouslyFetchAdjustmentBlobWithCompletionHandler:(id)arg0 ;
-(void)synchronouslyFetchAdjustmentDataWithCompletionHandler:(id)arg0 ;
-(void)synchronouslyGenerateFullsizeRenderImageIfNecessaryAtPath:(id)arg0 withCompletionHandler:(id)arg1 ;
-(void)syndicatedAssetDidSaveToUserLibrary;
-(void)unregisterForChanges;
-(void)unsaveSyndicatedAsset;
-(void)updateAdjustmentFileWithAdjustmentRenderTypes:(unsigned int)arg0 ;
-(void)updateAudioExtendedAttributesFromMetadata:(id)arg0 ;
-(void)updateDeferredAdjustmentWithFullSizeRenderImageURL:(id)arg0 videoURL:(id)arg1 videoPosterURL:(id)arg2 ;
-(void)updateImageExtendedAttributesFromMetadata:(id)arg0 ;
-(void)updateMatchingAssetFromSyndicationLibraryWithSavedToLibrary:(BOOL)arg0 ;
-(void)updatePanoramosity;
-(void)updatePhotoIrisMetadataWithMediaGroupUUID:(id)arg0 videoDuration:(struct ? )arg1 stillDisplayTime:(struct ? )arg2 ;
-(void)updatePlaybackStyleWithLivePhotoPlayability:(BOOL)arg0 ;
-(void)updateSyndicationStateWithSyndicationProcessingValue:(unsigned short)arg0 ;
-(void)updateVideoAttributesFromMetadata:(id)arg0 overwriteOriginalProperties:(BOOL)arg1 ;
-(void)updateVideoExtendedAttributesFromMetadata:(id)arg0 ;
-(void)updateWithCustomAssetProperties:(id)arg0 ;
-(void)userDeleteCloudSharedComment:(id)arg0 ;
-(void)userReadAllCloudSharedComments;
-(void)willSave;
-(void)willTurnIntoFault;


@end


#endif