// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef AVCAPTUREFIGVIDEODEVICE_H
#define AVCAPTUREFIGVIDEODEVICE_H

@class NSDictionary, NSString, NSArray, AVWeakReference, NSMutableArray, NSMutableDictionary, NSData;
@protocol MCProfileConnectionObserver, OS_dispatch_queue, OS_dispatch_semaphore;


#import "AVCaptureDevice.h"
#import "AVCaptureDeviceFormat.h"
#import "AVCaptureDeviceControlRequestQueue.h"
#import "AVCaptureSystemPressureState.h"

@interface AVCaptureFigVideoDevice : AVCaptureDevice <MCProfileConnectionObserver>

 {
    NSObject<OS_dispatch_queue> *_fcsQueue;
    *OpaqueFigCaptureSource _fcs;
    NSDictionary *_fcsAttributes;
    NSObject<OS_dispatch_queue> *_devicePropsQueue;
    NSString *_fcsUID;
    NSInteger _position;
    NSString *_localizedName;
    NSArray *_formats;
    AVCaptureDeviceFormat *_activeFormat;
    AVCaptureDeviceFormat *_activeDepthDataFormat;
    NSString *_activeSessionPreset;
    ? _activeDepthDataMinFrameDuration;
    ? _videoMinFrameDurationOverride;
    id *_videoMinFrameDurationOverrideOwner;
    ? _activeMinFrameDuration;
    BOOL _activeMinFrameDurationSetByClient;
    ? _activeMaxFrameDuration;
    BOOL _activeMaxFrameDurationSetByClient;
    BOOL _cachesFigCaptureSourceConfigurationChanges;
    NSInteger _focusMode;
    CGPoint _focusPointOfInterest;
    float _lensPositionKVO;
    BOOL _adjustingFocus;
    NSInteger _autoFocusRangeRestriction;
    BOOL _smoothAutoFocusEnabled;
    BOOL _automaticallyAdjustsFaceDrivenAutoFocusEnabled;
    BOOL _cameraOption9;
    BOOL _cameraOption10;
    CGRect _cameraFaceResult29;
    BOOL _cameraFaceResult30;
    NSInteger _exposureMode;
    ? _exposureDurationKVO;
    float _ISOKVO;
    float _exposureTargetBias;
    float _exposureTargetOffsetKVO;
    CGPoint _exposurePointOfInterest;
    BOOL _automaticallyAdjustsFaceDrivenAutoExposureEnabled;
    ? _activeMaxExposureDuration;
    ? _activeMaxExposureDurationClientOverride;
    BOOL _adjustingExposure;
    BOOL _waitingForExposureAdjustmentBeforeLocking;
    NSInteger _wbMode;
    ? _deviceWhiteBalanceGainsKVO;
    ? _grayWorldDeviceWhiteBalanceGainsKVO;
    BOOL _adjustingWB;
    NSUInteger _wbCalibrationCount;
    *? _wbCalibrationTemperatures;
    **CGFloat _wbCalibrationMatrices;
    CGFloat _wbLastPredictedTemp;
    CGFloat _wbSeedTemp;
    BOOL _wbSeedEnabled;
    NSUInteger _wbTemperatureIterations;
    BOOL _providesStortorgetMetadata;
    BOOL _automaticallyAdjustsImageControlMode;
    AVCaptureDeviceControlRequestQueue *_manualFocusControlRequests;
    AVCaptureDeviceControlRequestQueue *_manualExposureControlRequests;
    AVCaptureDeviceControlRequestQueue *_biasedExposureControlRequests;
    AVCaptureDeviceControlRequestQueue *_manualWhiteBalanceControlRequests;
    ? _lastCustomExposureDuration;
    float _lastCustomExposureISO;
    NSInteger _imageControlMode;
    NSInteger _flashMode;
    BOOL _avcaptureDeviceAutoFlashEnabled;
    BOOL _photoOutputFlashSceneEnabled;
    BOOL _flashActive;
    BOOL _flashSceneDetectedForPhotoOutput;
    NSInteger _digitalFlashMode;
    NSDictionary *_digitalFlashSceneForPhotoOutput;
    BOOL _flashAvailable;
    NSInteger _torchMode;
    BOOL _torchActive;
    float _torchLevel;
    BOOL _torchAvailable;
    BOOL _isConnected;
    BOOL _isSuspended;
    BOOL _subjectMonitoringEnabled;
    int _faceDrivenAEAFMode;
    CGRect _faceRectangle;
    int _faceRectangleAngle;
    BOOL _automaticallyAdjustsVideoHDREnabled;
    BOOL _videoHDREnabled;
    BOOL _videoHDRSuspended;
    BOOL _HDRSceneDetectedForPhotoOutput;
    BOOL _isStillImageStabilizationScene;
    NSInteger _activeColorSpace;
    float _videoZoomFactor;
    float _videoZoomRampTarget;
    int _videoZoomRampCounter;
    float _videoZoomRampAcceleration;
    CGFloat _minAvailableVideoZoomFactor;
    CGFloat _maxAvailableVideoZoomFactor;
    BOOL _depthDataDeliveryEnabled;
    NSInteger _shallowDepthOfFieldEffectStatus;
    BOOL _cameraCalibrationDataDeliveryEnabled;
    BOOL _focusedAtMacro;
    AVCaptureDevice *_activePrimaryConstituentDevice;
    NSInteger _activePrimaryConstituentDeviceSwitchingBehavior;
    NSUInteger _activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions;
    NSInteger _primaryConstituentDeviceSwitchingBehavior;
    NSUInteger _primaryConstituentDeviceRestrictedSwitchingBehaviorConditions;
    NSArray *_supportedFallbackPrimaryConstituentDevices;
    NSArray *_fallbackPrimaryConstituentDevices;
    AVCaptureDevice *_preferredPrimaryConstituentDevice;
    AVWeakReference *_weakReference;
    NSMutableArray *_captureSourceSupportedMetadata;
    NSDictionary *_supportedOptionalFaceDetectionFeatures;
    BOOL _eyeDetectionEnabled;
    BOOL _eyeClosedDetectionEnabled;
    BOOL _smileDetectionEnabled;
    NSArray *_availableBoxedMetadataFormatDescriptions;
    NSDictionary *_sessionPresetCompressionSettings;
    NSDictionary *_h264EncoderLimitations;
    NSDictionary *_hevcEncoderSettings;
    NSObject<OS_dispatch_queue> *_observedHighFrequencyPropertiesQueue;
    NSMutableDictionary *_observedHighFrequencyPropertyCounts;
    NSMutableDictionary *_propertyToFigCaptureSourcePropertyMap;
    NSObject<OS_dispatch_semaphore> *_serverConnectionDiedSemaphore;
    NSMutableDictionary *_cachedFigCaptureSourceProperties;
    AVCaptureSystemPressureState *_systemPressureState;
    int _highestSystemPressureLevelEncountered;
    BOOL _lowLightVideoCaptureEnabled;
    BOOL _spatialOverCaptureEnabled;
    BOOL _nonDestructiveCropEnabled;
    NSInteger _nonDestructiveCropAspectRatio;
    BOOL _geometricDistortionCorrectionEnabled;
    BOOL _globalToneMappingEnabled;
    BOOL _variableFrameRateVideoCaptureEnabled;
    NSInteger _videoStabilizationStrength;
    NSInteger _timeOfFlightProjectorMode;
    NSData *_cameraPoseMatrix;
    NSUInteger _degradedCaptureQualityFactors;
    BOOL _degradedCaptureQualityFactorsNeedInitialization;
    BOOL _walletDegradesCaptureQuality;
    BOOL _batteryPackDegradesCaptureQuality;
    BOOL _centerStageSupported;
    BOOL _centerStageActive;
    BOOL _centerStageAllowedByClient;
    CGRect _centerStageRectOfInterest;
    BOOL _backgroundBlurSupported;
    BOOL _backgroundBlurActive;
    BOOL _backgroundBlurAllowedByClient;
    BOOL _studioLightingSupported;
    BOOL _studioLightingActive;
    BOOL _studioLightingAllowedByClient;
    NSInteger _deskViewCameraMode;
    NSInteger _portraitEffectStudioLightQuality;
}


@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;


+(BOOL)_cameraAccessIsEnabled;
+(BOOL)automaticallyNotifiesObserversForKey:(id)arg0 ;
+(id)_devices;
+(id)_devicesWithPriorRegisteredDevices:(id)arg0 ;
+(id)_newFigCaptureSources;
+(void)_reconnectDevices:(id)arg0 ;
+(void)initialize;
-(BOOL)_centerStageRectOfInterestSupportedOnDevice;
-(BOOL)_ensureWhiteBalanceCalibrationUnpacked;
-(BOOL)_hasKeyValueObserversForHighFrequencyProperty:(id)arg0 ;
-(BOOL)_isAppleManufacturer;
-(BOOL)_isBackgroundBlurActiveForEnabled:(BOOL)arg0 ;
-(BOOL)_isBravoVariant;
-(BOOL)_isCenterStageActiveForEnabled:(BOOL)arg0 ;
-(BOOL)_isDepthDataDeliveryEnabled;
-(BOOL)_isFlashScene;
-(BOOL)_isHighDynamicRangeScene;
-(BOOL)_isStillImageStabilizationScene;
-(BOOL)_isStudioLightingActiveForEnabled:(BOOL)arg0 ;
-(BOOL)_isWBSeedEnabled;
-(BOOL)appliesSessionPresetMaxIntegrationTimeOverrideToActiveFormat;
-(BOOL)automaticallyAdjustsFaceDrivenAutoExposureEnabled;
-(BOOL)automaticallyAdjustsFaceDrivenAutoFocusEnabled;
-(BOOL)automaticallyAdjustsImageControlMode;
-(BOOL)automaticallyAdjustsVideoHDREnabled;
-(BOOL)cachesFigCaptureSourceConfigurationChanges;
-(BOOL)eyeClosedDetectionEnabled;
-(BOOL)eyeDetectionEnabled;
-(BOOL)hasFlash;
-(BOOL)hasMediaType:(id)arg0 ;
-(BOOL)hasTorch;
-(BOOL)hevcAllowBFramesForHighCTUCount;
-(BOOL)isActiveVideoMaxFrameDurationSet;
-(BOOL)isActiveVideoMinFrameDurationSet;
-(BOOL)isAdjustingExposure;
-(BOOL)isAdjustingFocus;
-(BOOL)isAdjustingWhiteBalance;
-(BOOL)isAutoFocusRangeRestrictionSupported;
-(BOOL)isAutoRedEyeReductionSupported;
-(BOOL)isBackgroundBlurActive;
-(BOOL)isCameraIntrinsicMatrixDeliverySupported;
-(BOOL)isCenterStageActive;
-(BOOL)isCenterStageRectOfInterestSupported;
-(BOOL)isCinematicFramingActive;
-(BOOL)isCinematicVideoFocusAtPointSupported;
-(BOOL)isConnected;
-(BOOL)isConstituentPhotoCalibrationDataSupported;
-(BOOL)isContinuityCamera;
-(BOOL)isDeskViewCameraModeSupported:(NSInteger)arg0 ;
-(BOOL)isDiagnosticsTestSupported:(id)arg0 ;
-(BOOL)isExposureModeSupported:(NSInteger)arg0 ;
-(BOOL)isExposurePointOfInterestSupported;
-(BOOL)isEyeClosedDetectionSupported;
-(BOOL)isEyeDetectionSupported;
-(BOOL)isFaceDetectionDrivenImageProcessingEnabled;
-(BOOL)isFaceDetectionDuringVideoPreviewSupported;
-(BOOL)isFaceDetectionSupported;
-(BOOL)isFaceDrivenAutoExposureEnabled;
-(BOOL)isFaceDrivenAutoFocusEnabled;
-(BOOL)isFlashActive;
-(BOOL)isFlashAvailable;
-(BOOL)isFlashModeSupported:(NSInteger)arg0 ;
-(BOOL)isFlashSceneDetectedForPhotoOutput;
-(BOOL)isFocusModeSupported:(NSInteger)arg0 ;
-(BOOL)isFocusPointOfInterestSupported;
-(BOOL)isFocusedAtMacro;
-(BOOL)isGeometricDistortionCorrectionEnabled;
-(BOOL)isGeometricDistortionCorrectionSupported;
-(BOOL)isGlobalToneMappingEnabled;
-(BOOL)isHDRSceneDetectedForPhotoOutput;
-(BOOL)isHEIFSupported;
-(BOOL)isHEVCPreferred;
-(BOOL)isHEVCRelaxedAverageBitRateTargetSupported;
-(BOOL)isHEVCSupported;
-(BOOL)isImageControlModeSupported:(NSInteger)arg0 ;
-(BOOL)isLensStabilizationSupported;
-(BOOL)isLockedForConfiguration;
-(BOOL)isLockingFocusWithCustomLensPositionSupported;
-(BOOL)isLockingWhiteBalanceWithCustomDeviceGainsSupported;
-(BOOL)isLowLightVideoCaptureEnabled;
-(BOOL)isMachineReadableCodeDetectionSupported;
-(BOOL)isNonDestructiveCropEnabled;
-(BOOL)isObjectDetectionSupported;
-(BOOL)isOverheadCameraModeSupported:(NSInteger)arg0 ;
-(BOOL)isPortraitEffectActive;
-(BOOL)isPreviewQualityAdjustedPhotoFilterRenderingSupported;
-(BOOL)isProResSupported;
-(BOOL)isRampingVideoZoom;
-(BOOL)isSISSupported;
-(BOOL)isSmileDetectionSupported;
-(BOOL)isSmoothAutoFocusEnabled;
-(BOOL)isSmoothAutoFocusSupported;
-(BOOL)isSpatialOverCaptureEnabled;
-(BOOL)isStillImageStabilizationScene;
-(BOOL)isStudioLightActive;
-(BOOL)isStudioLightingActive;
-(BOOL)isSubjectAreaChangeMonitoringEnabled;
-(BOOL)isTimeOfFlightProjectorModeSupported:(NSInteger)arg0 ;
-(BOOL)isTorchActive;
-(BOOL)isTorchAvailable;
-(BOOL)isTorchModeSupported:(NSInteger)arg0 ;
-(BOOL)isVariableFrameRateVideoCaptureEnabled;
-(BOOL)isVideoHDREnabled;
-(BOOL)isVideoHDRSuspended;
-(BOOL)isVideoStabilizationSupported;
-(BOOL)isVideoZoomSmoothingSupported;
-(BOOL)isWhiteBalanceModeSupported:(NSInteger)arg0 ;
-(BOOL)isWideColorSupported;
-(BOOL)lockForConfiguration:(*id)arg0 ;
-(BOOL)providesStortorgetMetadata;
-(BOOL)setTorchModeOnWithLevel:(float)arg0 error:(*id)arg1 ;
-(BOOL)smileDetectionEnabled;
-(BOOL)supportsAVCaptureSessionPreset:(id)arg0 ;
-(BOOL)supportsMultiCamCaptureWithDevice:(id)arg0 ;
-(BOOL)usesQuantizationScalingMatrix_H264_Steep_16_48;
-(BOOL)wideAngleCameraSourcesFromUltraWide;
-(CGFloat)_predictedTempForGains:(struct ? )arg0 ;
-(CGFloat)_whiteBalanceMixingFactorForTemperature:(CGFloat)arg0 ;
-(CGFloat)_whiteBalanceTemperatureForMixingFactor:(CGFloat)arg0 ;
-(CGFloat)dualCameraSwitchOverVideoZoomFactor;
-(CGFloat)maxAvailableVideoZoomFactor;
-(CGFloat)minAvailableVideoZoomFactor;
-(CGFloat)videoZoomFactor;
-(NSInteger)_digitalFlashStatus;
-(NSInteger)activeColorSpace;
-(NSInteger)activePrimaryConstituentDeviceSwitchingBehavior;
-(NSInteger)autoFocusRangeRestriction;
-(NSInteger)deskViewCameraMode;
-(NSInteger)digitalFlashMode;
-(NSInteger)exposureMode;
-(NSInteger)flashMode;
-(NSInteger)focusMode;
-(NSInteger)imageControlMode;
-(NSInteger)minimumFocusDistance;
-(NSInteger)nonDestructiveCropAspectRatio;
-(NSInteger)overheadCameraMode;
-(NSInteger)position;
-(NSInteger)primaryConstituentDeviceSwitchingBehavior;
-(NSInteger)shallowDepthOfFieldEffectStatus;
-(NSInteger)timeOfFlightBankCount;
-(NSInteger)timeOfFlightProjectorMode;
-(NSInteger)torchMode;
-(NSInteger)videoStabilizationStrength;
-(NSInteger)whiteBalanceMode;
-(NSUInteger)_wbTemperatureIterations;
-(NSUInteger)activePrimaryConstituentDeviceRestrictedSwitchingBehaviorConditions;
-(NSUInteger)degradedCaptureQualityFactors;
-(NSUInteger)primaryConstituentDeviceRestrictedSwitchingBehaviorConditions;
-(float)ISO;
-(float)ISODigitalThreshold;
-(float)exposureTargetBias;
-(float)exposureTargetOffset;
-(float)focalLength;
-(float)lensAperture;
-(float)lensPosition;
-(float)maxExposureTargetBias;
-(float)maxWhiteBalanceGain;
-(float)minExposureTargetBias;
-(float)timeLapseCaptureRate;
-(float)torchLevel;
-(float)videoZoomRampAcceleration;
-(id)AVVideoSettingsForSessionPreset:(id)arg0 ;
-(id)_copyFigCaptureSourceProperty:(struct __CFString *)arg0 ;
-(id)_copyFormatsArray;
-(id)_digitalFlashExposureTimes;
-(id)_faceDetectionConfigurationDictionary;
-(id)_getFigCaptureSourceProperty:(struct __CFString *)arg0 ;
-(id)_initWithFigCaptureSource:(struct OpaqueFigCaptureSource *)arg0 ;
-(id)_recommendedFrameRateRangeForVideoFormat:(id)arg0 depthFormat:(id)arg1 figSystemPressureLevel:(int)arg2 ;
-(id)_supportedOptionalFaceDetectionFeaturesDictionary;
-(id)activeDepthDataFormat;
-(id)activeFormat;
-(id)activePrimaryConstituentDevice;
-(id)availableBoxedMetadataFormatDescriptions;
-(id)bravoCameraSelectionBehavior;
-(id)cameraPoseMatrix;
-(id)companionDeskViewCamera;
-(id)constituentDeviceWithDeviceType:(id)arg0 ;
-(id)currentPrimaryConstituentDevice;
-(id)deviceFormatForSessionPreset:(id)arg0 videoFormat:(unsigned int)arg1 ;
-(id)deviceType;
-(id)digitalFlashSceneForPhotoOutput;
-(id)fallbackPrimaryConstituentDevices;
-(id)formats;
-(id)init;
-(id)localizedName;
-(id)manufacturer;
-(id)modelID;
-(id)preferredPrimaryConstituentDevice;
-(id)runDiagnosticsWithTestType:(id)arg0 ;
-(id)supportedFallbackPrimaryConstituentDevices;
-(id)supportedMetadataObjectIdentifiers;
-(id)supportedVisionDataProperties;
-(id)systemPressureState;
-(id)uniqueID;
-(id)virtualDeviceSwitchOverVideoZoomFactors;
-(int)_orderInDevicesArray;
-(int)_setActiveVideoMaxFrameDurationInternal:(struct ? )arg0 ;
-(int)_setActiveVideoMinFrameDurationInternal:(struct ? )arg0 ;
-(int)_setExposureWithMode:(NSInteger)arg0 duration:(struct ? )arg1 ISO:(float)arg2 requestID:(int)arg3 newMaxFrameDuration:(struct ? *)arg4 ;
-(int)_setFaceDetectionFeatureEnabled:(BOOL)arg0 enabledState:(*BOOL)arg1 ;
-(int)_setFigCaptureSourceProperty:(struct __CFString *)arg0 withValue:(id)arg1 ;
-(int)_setFigCaptureSourceProperty:(struct __CFString *)arg0 withValue:(id)arg1 cacheOnly:(BOOL)arg2 ;
-(int)_setFocusWithMode:(NSInteger)arg0 lensPosition:(float)arg1 requestID:(int)arg2 ;
-(int)_setTorchMode:(NSInteger)arg0 withLevel:(float)arg1 ;
-(int)_setWhiteBalanceWithMode:(NSInteger)arg0 gains:(struct ? )arg1 requestID:(int)arg2 ;
-(int)faceDrivenAEAFMode;
-(int)faceRectangleAngle;
-(int)figCaptureSourceDeviceType;
-(int)hevcTurboModeVersion;
-(int)minMacroblocksForHighProfileAbove30fps;
-(int)minMacroblocksForHighProfileUpTo30fps;
-(int)powerConsumptionAt30FPSForOISMode:(int)arg0 ;
-(struct ? )_chromaticityValuesForDeviceWhiteBalanceGains:(struct ? )arg0 atMix:(CGFloat)arg1 ;
-(struct ? )_deviceWhiteBalanceGainsForChromaticityValues:(struct ? )arg0 temperature:(CGFloat)arg1 ;
-(struct ? )activeDepthDataMinFrameDuration;
-(struct ? )activeMaxExposureDuration;
-(struct ? )activeMaxExposureDurationClientOverride;
-(struct ? )activeVideoMaxFrameDuration;
-(struct ? )activeVideoMinFrameDuration;
-(struct ? )chromaticityValuesForDeviceWhiteBalanceGains:(struct ? )arg0 ;
-(struct ? )deviceWhiteBalanceGains;
-(struct ? )deviceWhiteBalanceGainsForChromaticityValues:(struct ? )arg0 ;
-(struct ? )deviceWhiteBalanceGainsForTemperatureAndTintValues:(struct ? )arg0 ;
-(struct ? )exposureDuration;
-(struct ? )grayWorldDeviceWhiteBalanceGains;
-(struct ? )maxH264PhotoDimensions;
-(struct ? )maxH264VideoDimensions;
-(struct ? )temperatureAndTintValuesForDeviceWhiteBalanceGains:(struct ? )arg0 ;
-(struct CGPoint )exposurePointOfInterest;
-(struct CGPoint )focusPointOfInterest;
-(struct CGRect )centerStageRectOfInterest;
-(struct CGRect )faceRectangle;
-(struct OpaqueCMClock *)deviceClock;
-(struct OpaqueFigCaptureSource *)figCaptureSource;
-(void)_checkTCCAccess;
-(void)_decrementObserverCountForHighFrequencyProperty:(id)arg0 ;
-(void)_drainManualControlRequestQueue:(id)arg0 ;
-(void)_drainManualControlRequestQueues;
-(void)_handleManualControlCompletionForRequestQueue:(id)arg0 withPayload:(id)arg1 ;
-(void)_handleNotification:(struct __CFString *)arg0 payload:(id)arg1 ;
-(void)_incrementObserverCountForHighFrequencyProperty:(id)arg0 ;
-(void)_initDegradedCaptureQualityFactors;
-(void)_performBlockOnMainThread:(id)arg0 ;
-(void)_populateSupportedFallbackPrimaryConstituentDevices;
-(void)_rampToVideoZoomFactor:(CGFloat)arg0 withRate:(float)arg1 duration:(CGFloat)arg2 rampType:(int)arg3 rampTuning:(int)arg4 ;
-(void)_reconnectToFigCaptureSource:(struct OpaqueFigCaptureSource *)arg0 ;
-(void)_resetVideoHDRSuspended;
-(void)_restoreFigCaptureSourceProperties;
-(void)_setActiveFormat:(id)arg0 resetVideoZoomFactorAndMinMaxFrameDurations:(BOOL)arg1 sessionPreset:(id)arg2 ;
-(void)_setActivePrimaryConstituentDeviceSwitchingBehavior:(NSInteger)arg0 restrictedSwitchingBehaviorConditions:(NSUInteger)arg1 ;
-(void)_setActiveVideoMaxFrameDuration:(struct ? )arg0 ;
-(void)_setActiveVideoMinFrameDuration:(struct ? )arg0 ;
-(void)_setAdjustingExposure:(BOOL)arg0 ;
-(void)_setAdjustingFocus:(BOOL)arg0 ;
-(void)_setAdjustingWhiteBalance:(BOOL)arg0 ;
-(void)_setBackgroundBlurAllowed:(BOOL)arg0 ;
-(void)_setCameraCalibrationDataDeliveryEnabled:(BOOL)arg0 ;
-(void)_setCenterStageAllowed:(BOOL)arg0 ;
-(void)_setDepthDataDeliveryEnabled:(BOOL)arg0 ;
-(void)_setDigitalFlashModeInternal:(NSInteger)arg0 ;
-(void)_setDigitalFlashSceneForPhotoOutput:(id)arg0 ;
-(void)_setFigCaptureSource:(struct OpaqueFigCaptureSource *)arg0 allowSendingWorkToMainThread:(BOOL)arg1 ;
-(void)_setFlashActive:(BOOL)arg0 ;
-(void)_setFlashAvailable:(BOOL)arg0 ;
-(void)_setFlashSceneDetectedForPhotoOutput:(BOOL)arg0 ;
-(void)_setGlobalToneMappingEnabledInternal:(BOOL)arg0 ;
-(void)_setHDRSceneDetectedForPhotoOutput:(BOOL)arg0 ;
-(void)_setImageControlMode:(NSInteger)arg0 ;
-(void)_setIsStillImageStabilizationScene:(BOOL)arg0 ;
-(void)_setMaxAvailableVideoZoomFactor:(CGFloat)arg0 ;
-(void)_setMinAvailableVideoZoomFactor:(CGFloat)arg0 ;
-(void)_setPhotoSettingsForSceneMonitoring:(id)arg0 ;
-(void)_setShallowDepthOfFieldEffectStatus:(NSInteger)arg0 ;
-(void)_setStillImageStabilizationAutomaticallyEnabled:(BOOL)arg0 ;
-(void)_setStudioLightingAllowed:(BOOL)arg0 ;
-(void)_setTorchActive:(BOOL)arg0 ;
-(void)_setTorchAvailable:(BOOL)arg0 ;
-(void)_setTorchLevel:(float)arg0 ;
-(void)_setVideoHDREnabled:(BOOL)arg0 forceResetVideoHDRSuspended:(BOOL)arg1 ;
-(void)_setVideoZoomFactor:(CGFloat)arg0 ;
-(void)_setWBSeedEnabled:(BOOL)arg0 ;
-(void)_updateBackgroundBlurActiveForEnabled:(BOOL)arg0 ;
-(void)_updateCenterStageActiveForEnabled:(BOOL)arg0 updateDependentProperties:(BOOL)arg1 ;
-(void)_updateFigCaptureSourceObserverCounts;
-(void)_updatePortraitEffectStudioLightQuality:(NSInteger)arg0 ;
-(void)_updateStudioLightingActiveForEnabled:(BOOL)arg0 ;
-(void)addObserver:(id)arg0 forKeyPath:(id)arg1 options:(NSUInteger)arg2 context:(*void)arg3 ;
-(void)cancelVideoZoomRamp;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg0 ofObject:(id)arg1 change:(id)arg2 context:(*void)arg3 ;
-(void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg0 userInfo:(id)arg1 ;
-(void)rampExponentiallyToVideoZoomFactor:(float)arg0 withDuration:(CGFloat)arg1 ;
-(void)rampToVideoZoomFactor:(CGFloat)arg0 withRate:(float)arg1 ;
-(void)rampToVideoZoomFactor:(float)arg0 withTuning:(NSInteger)arg1 ;
-(void)removeObserver:(id)arg0 forKeyPath:(id)arg1 ;
-(void)removeObserver:(id)arg0 forKeyPath:(id)arg1 context:(*void)arg2 ;
-(void)resetVideoMinFrameDurationOverrideForOwner:(id)arg0 ;
-(void)setActiveColorSpace:(NSInteger)arg0 ;
-(void)setActiveDepthDataFormat:(id)arg0 ;
-(void)setActiveDepthDataMinFrameDuration:(struct ? )arg0 ;
-(void)setActiveFormat:(id)arg0 ;
-(void)setActiveMaxExposureDuration:(struct ? )arg0 ;
-(void)setActiveVideoMaxFrameDuration:(struct ? )arg0 ;
-(void)setActiveVideoMinFrameDuration:(struct ? )arg0 ;
-(void)setAutoFocusRangeRestriction:(NSInteger)arg0 ;
-(void)setAutomaticallyAdjustsFaceDrivenAutoExposureEnabled:(BOOL)arg0 ;
-(void)setAutomaticallyAdjustsFaceDrivenAutoFocusEnabled:(BOOL)arg0 ;
-(void)setAutomaticallyAdjustsImageControlMode:(BOOL)arg0 ;
-(void)setAutomaticallyAdjustsVideoHDREnabled:(BOOL)arg0 ;
-(void)setCachesFigCaptureSourceConfigurationChanges:(BOOL)arg0 ;
-(void)setCenterStageRectOfInterest:(struct CGRect )arg0 ;
-(void)setCinematicVideoFocusAtPoint:(struct CGPoint )arg0 objectID:(NSInteger)arg1 isHardFocus:(BOOL)arg2 isFixedPlaneFocus:(BOOL)arg3 ;
-(void)setDeskViewCameraMode:(NSInteger)arg0 ;
-(void)setDigitalFlashMode:(NSInteger)arg0 ;
-(void)setExposureMode:(NSInteger)arg0 ;
-(void)setExposureModeCustomWithDuration:(struct ? )arg0 ISO:(float)arg1 completionHandler:(id)arg2 ;
-(void)setExposurePointOfInterest:(struct CGPoint )arg0 ;
-(void)setExposureTargetBias:(float)arg0 completionHandler:(id)arg1 ;
-(void)setEyeClosedDetectionEnabled:(BOOL)arg0 ;
-(void)setEyeDetectionEnabled:(BOOL)arg0 ;
-(void)setFaceDetectionDrivenImageProcessingEnabled:(BOOL)arg0 ;
-(void)setFaceDrivenAutoExposureEnabled:(BOOL)arg0 ;
-(void)setFaceDrivenAutoFocusEnabled:(BOOL)arg0 ;
-(void)setFallbackPrimaryConstituentDevices:(id)arg0 ;
-(void)setFlashMode:(NSInteger)arg0 ;
-(void)setFocusMode:(NSInteger)arg0 ;
-(void)setFocusModeLockedWithLensPosition:(float)arg0 completionHandler:(id)arg1 ;
-(void)setFocusPointOfInterest:(struct CGPoint )arg0 ;
-(void)setGeometricDistortionCorrectionEnabled:(BOOL)arg0 ;
-(void)setGlobalToneMappingEnabled:(BOOL)arg0 ;
-(void)setImageControlMode:(NSInteger)arg0 ;
-(void)setLowLightVideoCaptureEnabled:(BOOL)arg0 ;
-(void)setNonDestructiveCropAspectRatio:(NSInteger)arg0 ;
-(void)setNonDestructiveCropEnabled:(BOOL)arg0 ;
-(void)setOverheadCameraMode:(NSInteger)arg0 ;
-(void)setPrimaryConstituentDeviceSwitchingBehavior:(NSInteger)arg0 restrictedSwitchingBehaviorConditions:(NSUInteger)arg1 ;
-(void)setProvidesStortorgetMetadata:(BOOL)arg0 ;
-(void)setSmileDetectionEnabled:(BOOL)arg0 ;
-(void)setSmoothAutoFocusEnabled:(BOOL)arg0 ;
-(void)setSpatialOverCaptureEnabled:(BOOL)arg0 ;
-(void)setSubjectAreaChangeMonitoringEnabled:(BOOL)arg0 ;
-(void)setTimeLapseCaptureRate:(float)arg0 ;
-(void)setTimeOfFlightProjectorMode:(NSInteger)arg0 ;
-(void)setTorchMode:(NSInteger)arg0 ;
-(void)setVariableFrameRateVideoCaptureEnabled:(BOOL)arg0 ;
-(void)setVideoHDREnabled:(BOOL)arg0 ;
-(void)setVideoHDRSuspended:(BOOL)arg0 ;
-(void)setVideoMinFrameDurationOverride:(struct ? )arg0 forOwner:(id)arg1 ;
-(void)setVideoStabilizationStrength:(NSInteger)arg0 ;
-(void)setVideoZoomFactor:(CGFloat)arg0 ;
-(void)setVideoZoomRampAcceleration:(float)arg0 ;
-(void)setWhiteBalanceMode:(NSInteger)arg0 ;
-(void)setWhiteBalanceModeLockedWithDeviceWhiteBalanceGains:(struct ? )arg0 completionHandler:(id)arg1 ;
-(void)unlockForConfiguration;


@end


#endif