// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef UIAPPLICATION_H
#define UIAPPLICATION_H

@class NSArray, NSTimer, NSMutableArray, NSString, FBSDisplayLayoutMonitor, NSDate, NSMutableDictionary, NSMutableSet, BKSAnimationFenceHandle, UISApplicationState, PKPushRegistry, BSServiceConnectionEndpointMonitor, NSSet, SBSApplicationShortcutService;
@protocol _UIWindowSceneActivator_Internal, FBSWorkspaceDelegate, FBSWorkspaceDelegate_Exiting, FBSDisplayLayoutObserver, PKPushRegistryDelegate, UIActivityContinuationManagerApplicationContext, UIApplicationSnapshotPreparing, UIRepeatedActionDelegate, UIStatusBarStyleDelegate_SpringBoardOnly, _UIApplicationInitializationContextFactory, OS_dispatch_queue, UIFenceProviding, UIApplicationDelegate;


#import "UIResponder.h"
#import "UIAlertController.h"
#import "UIStatusBar.h"
#import "UIStatusBarWindow.h"
#import "_UIIdleModeController.h"
#import "UIEventFetcher.h"
#import "UIEventDispatcher.h"
#import "_UIHIDEventOrderedDescriptorSet.h"
#import "UIWindow.h"
#import "_UIApplicationInfoParser.h"
#import "UIRepeatedAction.h"
#import "_UIFenceTask.h"
#import "UISystemNavigationAction.h"
#import "UIActivityContinuationManager.h"
#import "UIGestureEnvironment.h"
#import "UIForceStageObservable.h"
#import "UINotificationFeedbackGenerator.h"

@interface UIApplication : UIResponder <_UIWindowSceneActivator_Internal, FBSWorkspaceDelegate, FBSWorkspaceDelegate_Exiting, FBSDisplayLayoutObserver, PKPushRegistryDelegate, UIActivityContinuationManagerApplicationContext, UIApplicationSnapshotPreparing, UIRepeatedActionDelegate, UIStatusBarStyleDelegate_SpringBoardOnly, _UIApplicationInitializationContextFactory>

 {
    NSInteger _remoteControlEventObservers;
    NSArray *_topLevelNibObjects;
    NSInteger _networkResourcesCurrentlyLoadingCount;
    NSTimer *_hideNetworkActivityIndicatorTimer;
    UIAlertController *_editAlertController;
    UIStatusBar *_statusBar;
    NSInteger _statusBarRequestedStyle;
    UIStatusBarWindow *_statusBarWindow;
    NSMutableArray *_observerBlocks;
    NSMutableArray *_postCommitActions;
    BOOL _postCommitActionsNeedToSynchronize;
    NSString *_mainStoryboardName;
    _UIIdleModeController *_idleModeController;
    FBSDisplayLayoutMonitor *_displayLayoutMonitor;
    NSInteger _systemUserInterfaceStyle;
    UIEventFetcher *_eventFetcher;
    UIEventDispatcher *_eventDispatcher;
    NSDate *_proximityEventsEnabledStartDate;
    ? _applicationFlags;
    NSInteger _couldNotRestoreStateWhenLockedTime;
    NSMutableArray *_keyCommandRegistrationAssertions;
    NSMutableDictionary *_physicalKeyCommandMap;
    _UIHIDEventOrderedDescriptorSet *_physicalKeycodeSet;
    BOOL _alwaysHitTestsForMainScreen;
    UIWindow *_backgroundHitTestWindow;
    _UIApplicationInfoParser *_appInfo;
    NSMutableSet *_actionsPendingInitialization;
    NSMutableSet *_idleTimerDisabledReasons;
    UIRepeatedAction *_keyRepeatAction;
    NSMutableDictionary *_hardwareKeyDownCodeToEventMap;
    CGFloat _currentTimestampWhenFirstTouchCameDown;
    CGPoint _currentLocationWhereFirstTouchCameDown;
    BOOL _saveStateRestorationArchiveWithFileProtectionCompleteUntilFirstUserAuthentication;
    _UIFenceTask *_fenceTask;
    BKSAnimationFenceHandle *_cachedSystemAnimationFence;
    UISystemNavigationAction *_systemNavigationAction;
    UIActivityContinuationManager *_activityContinuationManager;
    UIGestureEnvironment *__gestureEnvironment;
    UIForceStageObservable *_forceStageObservable;
    id *_HIDGameControllerEventObserver;
    NSObject<OS_dispatch_queue> *_HIDGameControllerEventQueue;
    UINotificationFeedbackGenerator *_motionNotificationGenerator;
    UISApplicationState *_appState;
    PKPushRegistry *_applicationPushRegistry;
    id *_storyboardInitialMenu;
    BSServiceConnectionEndpointMonitor *_endpointMonitor;
}


@property (copy, nonatomic, setter=__setQueuedOrientationChange:) id *__queuedOrientationChange; // ivar: ___queuedOrientationChange
@property (readonly, nonatomic) NSSet *_canvases;
@property (nonatomic, setter=_setExpectedViewOrientation:) NSInteger _expectedViewOrientation; // ivar: __expectedViewOrientation
@property (readonly, nonatomic) NSObject<UIFenceProviding> *_fenceProvider;
@property (readonly, nonatomic) NSSet *_openRepresentations;
@property (nonatomic) BOOL _shouldAllowContentTextContextExtraction; // ivar: __shouldAllowContentTextContextExtraction
@property (readonly, nonatomic) NSString *alternateIconName;
@property (nonatomic) NSInteger applicationIconBadgeNumber;
@property (readonly, nonatomic) NSInteger applicationState;
@property (nonatomic) BOOL applicationSupportsShakeToEdit;
@property (getter=_applicationWantsGESEvents, setter=_setApplicationWantsGESEvents:) BOOL applicationWantsGESEvents; // ivar: _applicationWantsGESEvents
@property (readonly, nonatomic) NSInteger backgroundRefreshStatus;
@property (readonly, nonatomic) CGFloat backgroundTimeRemaining;
@property (readonly, nonatomic) NSSet *connectedScenes;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) NSObject<UIApplicationDelegate> *delegate; // ivar: _delegate
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic, getter=_disableLayoutAwareShortcuts) BOOL disableLayoutAwareShortcuts;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic, getter=_hostsSystemStatusBar) BOOL hostsSystemStatusBar;
@property (nonatomic, getter=isIdleTimerDisabled) BOOL idleTimerDisabled;
@property (readonly, nonatomic, getter=isIgnoringInteractionEvents) BOOL ignoringInteractionEvents;
@property (nonatomic, getter=_isDisplayingActivityContinuationUI, setter=_setIsDisplayingActivityContinuationUI:) BOOL isDisplayingActivityContinuationUI; // ivar: _isDisplayingActivityContinuationUI
@property (readonly, nonatomic) UIWindow *keyWindow;
@property (nonatomic, getter=isNetworkActivityIndicatorVisible) BOOL networkActivityIndicatorVisible;
@property (readonly, nonatomic) NSSet *openSessions;
@property (nonatomic, getter=_shouldOptOutOfRTL, setter=_setOptOutOfRTL:) BOOL optOutOfRTL; // ivar: optOutOfRTL
@property (readonly, nonatomic) NSString *preferredContentSizeCategory;
@property (readonly, nonatomic, getter=isProtectedDataAvailable) BOOL protectedDataAvailable;
@property (retain, nonatomic) SBSApplicationShortcutService *shortcutService; // ivar: _shortcutService
@property (readonly, nonatomic) CGRect statusBarFrame;
@property (readonly, nonatomic, getter=isStatusBarHidden) BOOL statusBarHidden;
@property (readonly, nonatomic) NSInteger statusBarOrientation;
@property (readonly, nonatomic) CGFloat statusBarOrientationAnimationDuration;
@property (readonly, nonatomic) NSInteger statusBarStyle;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly, nonatomic) BOOL supportsAlternateIcons;
@property (readonly, nonatomic) BOOL supportsMultipleScenes;
@property (readonly, nonatomic) NSInteger userInterfaceLayoutDirection;
@property (readonly, nonatomic) NSArray *windows;


+(BOOL)_isBackgroundStyleTransparent:(NSInteger)arg0 ;
+(BOOL)_isCertainCheckpointInAppLaunchReached;
+(BOOL)_isClassic;
+(BOOL)_isRunningWithFixedMainThreadPriority;
+(BOOL)_isSystemUIService;
+(BOOL)_shouldBigify;
+(BOOL)_wantsApplicationBehaviorAsExtension;
+(BOOL)isRunningEventPump;
+(BOOL)isRunningInStoreDemoMode;
+(BOOL)registerAsSystemApp;
+(BOOL)rendersLocally;
+(BOOL)runStatusBarServer;
+(BOOL)shouldBackgroundMainThreadOnSuspendedLaunch;
+(BOOL)shouldMakeUIForDefaultPNG;
+(Class)_statusBarClass;
+(Class)_statusBarManagerClass;
+(Class)_statusBarWindowClass;
+(NSInteger)_backgroundStyleForString:(id)arg0 ;
+(NSInteger)_classicMode;
+(NSInteger)_debugUserInterfaceStyleOverride;
+(NSInteger)interfaceOrientationForString:(id)arg0 ;
+(NSInteger)runningInStoreDemoModeFProgramNumber;
+(NSInteger)statusBarStyleForString:(id)arg0 ;
+(NSUInteger)_statusBarStyleOverridesForArray:(id)arg0 ;
+(id)_accessibilitySettingsBundle;
+(id)_applicationNameForMenus;
+(id)_defaultContentSizeCategory;
+(id)_sanitizeBundleString:(id)arg0 ;
+(id)_stringForBackgroundStyle:(NSInteger)arg0 ;
+(id)_stringsForStatusBarStyleOverrides:(NSUInteger)arg0 ;
+(id)_systemAnimationFenceExemptQueue;
+(id)_systemUIServiceClientSettings;
+(id)_systemUIServiceIdentifier;
+(id)displayIdentifier;
+(id)displayManagerObserver;
+(id)sharedApplication;
+(id)stringForInterfaceOrientation:(NSInteger)arg0 ;
+(id)stringForStatusBarStyle:(NSInteger)arg0 ;
+(id)stringForStatusBarStyleOverrides:(NSUInteger)arg0 ;
+(void)_accessibilityLoadSettingsLoaderIfNeeded;
+(void)_screensHaveConnected;
+(void)_setDebugUserInterfaceStyleOverride:(NSInteger)arg0 ;
+(void)_startStatusBarServerIfNecessary;
+(void)_startWindowServerIfNecessary;
+(void)_updateAccessibilitySettingsLoader;
+(void)registerObjectForStateRestoration:(id)arg0 restorationIdentifier:(id)arg1 ;
-(BOOL)_UIApplicationLegacyVoipAllowed;
-(BOOL)_accessibilityApplicationIsSystemWideServer;
-(BOOL)_accessibilityCaptureSimulatorEvent:(struct __GSEvent *)arg0 ;
-(BOOL)_alwaysHitTestsForMainScreen;
-(BOOL)_appAdoptsUICanvasLifecycle;
-(BOOL)_appAdoptsUISceneLifecycle;
-(BOOL)_appSupportsMultipleScenes;
-(BOOL)_areFrontBoardInputOverlaysEnabled;
-(BOOL)_areKeyboardHUDsEnabled;
-(BOOL)_areSystemWindowsSecure;
-(BOOL)_canAnimateDragCancelInApp;
-(BOOL)_canOpenURL:(id)arg0 publicURLsOnly:(BOOL)arg1 ;
-(BOOL)_canReceiveDeviceOrientationEvents;
-(BOOL)_didEatCurrentTouchForWindow:(id)arg0 ;
-(BOOL)_disableBecomeFirstResponder;
-(BOOL)_doRestorationIfNecessary;
-(BOOL)_eatCurrentTouchForWindow:(id)arg0 ifPredicate:(id)arg1 ;
-(BOOL)_executableWasLinkedWithUIKit;
-(BOOL)_fakingRequiresHighResolution;
-(BOOL)_frontMostAppInterfaceOrientationIsSignificant;
-(BOOL)_handleDelegateCallbacksWithOptions:(id)arg0 isSuspended:(BOOL)arg1 restoreState:(BOOL)arg2 ;
-(BOOL)_handlePhysicalButtonEvent:(id)arg0 ;
-(BOOL)_hasApplicationCalledLaunchDelegate;
-(BOOL)_hasCalledRunWithMainScene;
-(BOOL)_hasNormalRestorationCompleted;
-(BOOL)_hasRemoteControlEventObservers;
-(BOOL)_hasStoryboard;
-(BOOL)_isActivated;
-(BOOL)_isActivatedIgnoringReason:(int)arg0 ;
-(BOOL)_isActivating;
-(BOOL)_isAutorotationDisabledForAppWindows;
-(BOOL)_isClassic;
-(BOOL)_isGlobeKeyShortcutHUDEnabled;
-(BOOL)_isHandlingMemoryWarning;
-(BOOL)_isIdleModeVisualEffectsEnabled;
-(BOOL)_isInteractionEvent:(struct __GSEvent *)arg0 ;
-(BOOL)_isLaunchedSuspended;
-(BOOL)_isNormalRestorationInProgress;
-(BOOL)_isOrientationVerticallyCompact:(NSInteger)arg0 ;
-(BOOL)_isResigningActive;
-(BOOL)_isRestorationExtended;
-(BOOL)_isSensitiveUIEnabled;
-(BOOL)_isSpringBoard;
-(BOOL)_isSpringBoardShowingAnAlert;
-(BOOL)_isStatusBarEffectivelyHiddenForContentOverlayInsetsForWindow:(id)arg0 ;
-(BOOL)_isStatusBarForcedHiddenForOrientation:(NSInteger)arg0 ;
-(BOOL)_isStatusBarHiddenForOrientation:(NSInteger)arg0 ;
-(BOOL)_isSupportedOrientation:(NSInteger)arg0 ;
-(BOOL)_isTerminating;
-(BOOL)_isTrackingAnyTouch;
-(BOOL)_isWindowServerHostingManaged;
-(BOOL)_keyCommandIsCurrentlyPerformable:(id)arg0 blockedAttributes:(NSUInteger)arg1 outTarget:(*id)arg2 validation:(id)arg3 ;
-(BOOL)_needsShakesWhenInactive;
-(BOOL)_openURL:(id)arg0 ;
-(BOOL)_overridesDynamicCaret;
-(BOOL)_prepareButtonEvent:(id)arg0 type:(NSInteger)arg1 phase:(NSInteger)arg2 timestamp:(CGFloat)arg3 contextID:(unsigned int)arg4 ;
-(BOOL)_prepareButtonEvent:(id)arg0 type:(NSInteger)arg1 phase:(NSInteger)arg2 timestamp:(CGFloat)arg3 force:(CGFloat)arg4 clickCount:(NSUInteger)arg5 longClick:(BOOL)arg6 contextID:(unsigned int)arg7 ;
-(BOOL)_prepareButtonEvent:(id)arg0 type:(NSInteger)arg1 phase:(NSInteger)arg2 timestamp:(CGFloat)arg3 force:(CGFloat)arg4 contextID:(unsigned int)arg5 ;
-(BOOL)_prepareButtonEvent:(id)arg0 withPressInfo:(id)arg1 ;
-(BOOL)_requiresHighResolution;
-(BOOL)_rotationDisabledDuringTouch;
-(BOOL)_saveSnapshotWithName:(id)arg0 ;
-(BOOL)_sceneSettingsIncludeSafeAreaInsets;
-(BOOL)_shakeToUndoEnabled;
-(BOOL)_shouldAllowKeyboardArbiter;
-(BOOL)_shouldAttemptOpenURL:(id)arg0 ;
-(BOOL)_shouldCreateStatusBarAtLaunch;
-(BOOL)_shouldForceClassicMode;
-(BOOL)_shouldHandleTestURL:(id)arg0 ;
-(BOOL)_shouldIgnoreHeadsetClicks;
-(BOOL)_shouldShowAlertForUndoManager:(id)arg0 ;
-(BOOL)_shouldUpdateSerializableKeyCommandsForResponder:(id)arg0 ;
-(BOOL)_statusBarOrientationFollowsWindow:(id)arg0 ;
-(BOOL)_supportedOnLockScreen;
-(BOOL)_supportsCompactStatusBarHiding;
-(BOOL)_supportsIndirectInputEvents;
-(BOOL)_supportsPrintCommand;
-(BOOL)_supportsShakesWhenNotActive;
-(BOOL)_systemShellAllowsInteractionTrackingKeyboardFocusUpdateForWindow:(id)arg0 ;
-(BOOL)_taskSuspendingUnsupported;
-(BOOL)_updateDefaultImage;
-(BOOL)_usesEmoji;
-(BOOL)_viewControllerBasedStatusBarAppearance;
-(BOOL)_viewServiceIgnoresSceneForLegacyInterfaceOrientation:(id)arg0 ;
-(BOOL)_wantsCompactStatusBarHiding;
-(BOOL)activityContinuationManager:(id)arg0 continueUserActivity:(id)arg1 ;
-(BOOL)activityContinuationManager:(id)arg0 willContinueUserActivityWithType:(id)arg1 ;
-(BOOL)activityContinuationManagerHandleErrorsByConfiguringProgressUI:(id)arg0 ;
-(BOOL)becomeFirstResponder;
-(BOOL)canOpenURL:(id)arg0 ;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)disablesFrontBoardImplicitWindowScenes;
-(BOOL)handleDoubleHeightStatusBarTapWithStyleOverride:(NSUInteger)arg0 ;
-(BOOL)handleEvent:(struct __GSEvent *)arg0 ;
-(BOOL)handleEvent:(struct __GSEvent *)arg0 withNewEvent:(id)arg1 ;
-(BOOL)handleKeyCommand:(id)arg0 repeatable:(BOOL)arg1 beforeKeyEvent:(BOOL)arg2 ;
-(BOOL)handleKeyUpCommand:(id)arg0 ;
-(BOOL)handleStatusBarHoverActionForRegion:(NSInteger)arg0 ;
-(BOOL)handleTestURL:(id)arg0 ;
-(BOOL)ignoresInteractionEvents;
-(BOOL)isFrontBoard;
-(BOOL)isHandlingOpenShortCut;
-(BOOL)isHandlingURL;
-(BOOL)isKeyCommand:(id)arg0 ;
-(BOOL)isLaunchTest:(id)arg0 ;
-(BOOL)isLocked;
-(BOOL)isPPTAvailable;
-(BOOL)isPasscodeRequiredToUnlock;
-(BOOL)isProximitySensingEnabled;
-(BOOL)isRegisteredForRemoteNotifications;
-(BOOL)isRunningInTaskSwitcher;
-(BOOL)isRunningQuitTest;
-(BOOL)isRunningSuspendTest;
-(BOOL)isRunningTest;
-(BOOL)isRunningTest:(id)arg0 ;
-(BOOL)isSuspended;
-(BOOL)isSuspendedEventsOnly;
-(BOOL)isSuspendedUnderLock;
-(BOOL)launchApplicationWithIdentifier:(id)arg0 suspended:(BOOL)arg1 ;
-(BOOL)launchedToTest;
-(BOOL)openURL:(id)arg0 ;
-(BOOL)removeDefaultImage:(id)arg0 ;
-(BOOL)removeDefaultImage:(id)arg0 forScreen:(id)arg1 ;
-(BOOL)reportApplicationSuspended;
-(BOOL)rotateIfNeeded:(NSInteger)arg0 ;
-(BOOL)runTest:(id)arg0 options:(id)arg1 ;
-(BOOL)sendAction:(SEL)arg0 to:(id)arg1 from:(id)arg2 forEvent:(id)arg3 ;
-(BOOL)sendAction:(SEL)arg0 toTarget:(id)arg1 fromSender:(id)arg2 forEvent:(id)arg3 ;
-(BOOL)setKeepAliveTimeout:(CGFloat)arg0 handler:(id)arg1 ;
-(BOOL)shouldFenceStatusBarRotation;
-(BOOL)shouldLaunchSafe;
-(BOOL)shouldRecordExtendedLaunchTime;
-(BOOL)systemIsAnimatingApplicationLifecycleEvent;
-(BOOL)usesBackgroundNetwork;
-(CGFloat)_execOrResumeTime;
-(CGFloat)_initialTouchTimestampForWindow:(id)arg0 ;
-(CGFloat)_launchTime;
-(CGFloat)defaultImageSnapshotExpiration;
-(CGFloat)statusBarHeight;
-(CGFloat)statusBarHeightForOrientation:(NSInteger)arg0 ;
-(CGFloat)statusBarHeightForOrientation:(NSInteger)arg0 ignoreHidden:(BOOL)arg1 ;
-(CGFloat)windowRotationDuration;
-(Class)_accessibilityBundlePrincipalClass;
-(NSInteger)_availableTextServices;
-(NSInteger)_carefulChoiceOrientation;
-(NSInteger)_carefulChoiceOrientationForWindow:(id)arg0 ;
-(NSInteger)_classicMode;
-(NSInteger)_currentExpectedInterfaceOrientation;
-(NSInteger)_defaultSceneInterfaceOrientationReturningUnknownForNilScene:(BOOL)arg0 ;
-(NSInteger)_effectiveUserInterfaceStyle;
-(NSInteger)_frontMostAppOrientation;
-(NSInteger)_getSpringBoardOrientation;
-(NSInteger)_normativeWhitePointAdaptivityStyleForWindow:(id)arg0 ;
-(NSInteger)_physicalButtonTypeForKeyboardEvent:(id)arg0 isTextual:(*BOOL)arg1 ;
-(NSInteger)_pureEffectiveUserInterfaceStyle;
-(NSInteger)_safeInterfaceOrientationForNoWindow;
-(NSInteger)_safeInterfaceOrientationForWindowIfExists:(id)arg0 ;
-(NSInteger)_safeInterfaceOrientationForWindowIfExists:(id)arg0 expectNonNilWindow:(BOOL)arg1 ;
-(NSInteger)_sceneInterfaceOrientationFromWindow:(id)arg0 ;
-(NSInteger)_statusBarOrientationForWindow:(id)arg0 ;
-(NSInteger)_systemUserInterfaceStyle;
-(NSInteger)_testOrientation:(id)arg0 options:(id)arg1 ;
-(NSInteger)activeInterfaceOrientation;
-(NSInteger)alertInterfaceOrientation;
-(NSInteger)interfaceOrientation;
-(NSInteger)overriddenRequestedStyleFromStyle:(NSInteger)arg0 ;
-(NSInteger)pureUserInterfaceLayoutDirection;
-(NSInteger)statusBar:(id)arg0 styleForRequestedStyle:(NSInteger)arg1 overrides:(NSUInteger)arg2 ;
-(NSUInteger)__beginBackgroundTaskWithExpirationHandler:(id)arg0 ;
-(NSUInteger)_beginBackgroundTaskWithExpirationHandler:(id)arg0 ;
-(NSUInteger)_beginBackgroundTaskWithName:(id)arg0 expirationHandler:(id)arg1 ;
-(NSUInteger)_restorationArchiveProtectionClass;
-(NSUInteger)_supportedInterfaceOrientationsForWindow:(id)arg0 ;
-(NSUInteger)beginBackgroundTaskWithExpirationHandler:(id)arg0 ;
-(NSUInteger)beginBackgroundTaskWithName:(id)arg0 expirationHandler:(id)arg1 ;
-(NSUInteger)blockInteractionEventsCount;
-(NSUInteger)enabledRemoteNotificationTypes;
-(NSUInteger)statusBar:(id)arg0 effectiveStyleOverridesForRequestedStyle:(NSInteger)arg1 overrides:(NSUInteger)arg2 ;
-(NSUInteger)supportedInterfaceOrientationsForWindow:(id)arg0 ;
-(float)backlightLevel;
-(id)_backgroundModes;
-(id)_cachedSystemAnimationFenceCreatingIfNecessary:(BOOL)arg0 ;
-(id)_connectUISceneFromFBSScene:(id)arg0 transitionContext:(id)arg1 ;
-(id)_createSnapshotContextForScene:(id)arg0 withName:(id)arg1 performLayoutWithSettings:(id)arg2 ;
-(id)_createSnapshotContextForSceneRemoval:(id)arg0 withName:(id)arg1 ;
-(id)_currentFrameCountForTestDisplay;
-(id)_currentHardwareKeyboardLayoutName;
-(id)_currentOpenApplicationEndpointForEnvironment:(id)arg0 ;
-(id)_currentTests;
-(id)_defaultSceneIfExists;
-(id)_defaultTopNavBarTintColor;
-(id)_defaultUISceneOrMainScreenPlaceholderIfExists;
-(id)_defaultUIWindowHostingUISceneOrMainScreenPlaceholderIfExists;
-(id)_discardedSceneSessionIdentifiersSinceLastRunWithContext:(id)arg0 knownSessions:(id)arg1 ;
-(id)_dragEvents;
-(id)_event;
-(id)_exclusiveTouchWindows;
-(id)_extendLaunchTest;
-(id)_findPrintTarget:(id)arg0 ;
-(id)_findUISceneForLegacyInterfaceOrientation;
-(id)_findWindowForControllingOverallAppearance;
-(id)_findWindowForControllingOverallAppearanceInCanvas:(id)arg0 ;
-(id)_findWindowForControllingOverallAppearanceInWindowScene:(id)arg0 ;
-(id)_firstCommitBlock:(SEL)arg0 ;
-(id)_firstEligibleResponderForPress:(id)arg0 ;
-(id)_forceStageObservable;
-(id)_gameControllerEventForWindow:(id)arg0 ;
-(id)_gestureEnvironment;
-(id)_getActivityContinuationManager;
-(id)_hoverEventForWindow:(id)arg0 ;
-(id)_hoverEventForWindowSpringBoardOnly:(id)arg0 ;
-(id)_idleModeController;
-(id)_implicitStatusBarAnimationParametersWithClass:(Class)arg0 ;
-(id)_implicitStatusBarHiddenAnimationParametersWithViewController:(id)arg0 animation:(NSInteger)arg1 ;
-(id)_implicitStatusBarStyleAnimationParametersWithViewController:(id)arg0 ;
-(id)_infoPlistCanvasDefinitions;
-(id)_infoPlistSceneConfigurations;
-(id)_keyCommandForKeyboardEvent:(id)arg0 target:(*id)arg1 ;
-(id)_keyCommands;
-(id)_keyDownDictionary;
-(id)_keyWindowForScreen:(id)arg0 ;
-(id)_launchTestName;
-(id)_localCachesDirectory;
-(id)_localizedApplicationName;
-(id)_mainEventEnvironment;
-(id)_mainScene;
-(id)_mainSceneForDisplay:(id)arg0 ;
-(id)_mainStoryboardName;
-(id)_motionEvent;
-(id)_motionKeyWindow;
-(id)_moveEventForWindow:(id)arg0 ;
-(id)_newDefaultStoryboardWindow;
-(id)_newSceneForWindow:(id)arg0 oldDisplay:(id)arg1 newDisplay:(id)arg2 ;
-(id)_openSessionForPersistentIdentifier:(id)arg0 ;
-(id)_openSessionsIncludingInternal:(BOOL)arg0 ;
-(id)_pencilEventForWindow:(id)arg0 ;
-(id)_physicalKeyboardEventForWindow:(id)arg0 ;
-(id)_preferredContentSizeCategory:(NSUInteger)arg0 ;
-(id)_pressInfoForPhysicalKeyboardEvent:(id)arg0 ;
-(id)_pressesEventForWindow:(id)arg0 ;
-(id)_remoteControlEvent;
-(id)_removePrivateOptionsFromOptions:(id)arg0 ;
-(id)_responderForKeyEvents;
-(id)_rootViewControllers;
-(id)_scrollEventForWindow:(id)arg0 ;
-(id)_showServiceForText:(id)arg0 selectedTextRange:(struct _NSRange )arg1 type:(NSInteger)arg2 fromRect:(struct CGRect )arg3 inView:(id)arg4 ;
-(id)_showServiceForText:(id)arg0 type:(NSInteger)arg1 fromRect:(struct CGRect )arg2 inView:(id)arg3 ;
-(id)_showServiceForType:(NSInteger)arg0 withContext:(id)arg1 ;
-(id)_statusBarControllingWindow;
-(id)_statusBarWindowIfExists;
-(id)_storyboardInitialMenu;
-(id)_systemAnimationFenceCreatingIfNecessary:(BOOL)arg0 ;
-(id)_systemAnimationFenceExemptQueue;
-(id)_systemNavigationAction;
-(id)_targetInChainForAction:(SEL)arg0 sender:(id)arg1 ;
-(id)_touchesEvent;
-(id)_touchesEventForWindow:(id)arg0 ;
-(id)_transformEventForWindow:(id)arg0 ;
-(id)_unswizzledTargetInChainForAction:(SEL)arg0 sender:(id)arg1 ;
-(id)_urlWithSettingsPrivateURLSchemeIfNeeded:(id)arg0 ;
-(id)_wheelEventForWindow:(id)arg0 ;
-(id)_windowForSystemAppButtonEventsForScreen:(id)arg0 ;
-(id)_workspace;
-(id)activityContinuationManagerUserCancelledError:(id)arg0 ;
-(id)currentUserNotificationSettings;
-(id)getKeyboardDevicePropertiesForSenderID:(NSUInteger)arg0 shouldUpdate:(BOOL)arg1 ;
-(id)getKeyboardDevicePropertiesForSenderID:(NSUInteger)arg0 shouldUpdate:(BOOL)arg1 usingSyntheticEvent:(BOOL)arg2 ;
-(id)idleTimerDisabledReasons;
-(id)init;
-(id)keyCommands;
-(id)nameOfDefaultImageToUpdateAtSuspension;
-(id)nextResponder;
-(id)pathToDefaultImageNamed:(id)arg0 forScreen:(id)arg1 ;
-(id)repeatedActionWillInvokeWithObject:(id)arg0 forPhase:(NSUInteger)arg1 ;
-(id)resultsForTest:(id)arg0 ;
-(id)scheduledLocalNotifications;
-(id)shortcutItems;
-(id)statusBar;
-(id)statusBarSystemNavigationAction:(id)arg0 ;
-(id)statusBarWindow;
-(id)statusBarWithWindow:(id)arg0 ;
-(id)subTest:(id)arg0 ForTest:(id)arg1 withMetrics:(id)arg2 ;
-(id)textInputMode;
-(id)userCachesDirectory;
-(id)userHomeDirectory;
-(id)userInfoDictionaryForRunLoopMode:(id)arg0 requester:(id)arg1 ;
-(id)userLibraryDirectory;
-(int)_loadMainInterfaceFile;
-(int)_loadMainNibFileNamed:(id)arg0 bundle:(id)arg1 ;
-(int)_loadMainStoryboardFileNamed:(id)arg0 bundle:(id)arg1 ;
-(struct CGRect )statusBarFrameForOrientation:(NSInteger)arg0 ;
-(struct __CFMessagePort *)_purplePPTServerPort;
-(struct __CFRunLoop *)_eventFetchRunLoop;
-(struct __GSKeyboard *)GSKeyboardForHWLayout:(id)arg0 forceRebuild:(BOOL)arg1 ;
-(struct __GSKeyboard *)GSKeyboardForHWLayout:(id)arg0 forceRebuild:(BOOL)arg1 createIfNeeded:(BOOL)arg2 ;
-(struct __GSKeyboard *)GSKeyboardForHWLayout:(id)arg0 senderID:(NSUInteger)arg1 forceRebuild:(BOOL)arg2 createIfNeeded:(BOOL)arg3 ;
-(struct __GSKeyboard *)_hardwareKeyboard;
-(struct __GSKeyboard *)_hardwareKeyboard:(BOOL)arg0 ;
-(struct __GSKeyboard *)_hardwareKeyboardForPhysicalKeyboardEvent:(id)arg0 createIfNeeded:(BOOL)arg1 ;
-(unsigned int)_currentHardwareKeyboardType;
-(unsigned int)_frontmostApplicationPort;
-(void)__completeAndRunAsPlugin;
-(void)_accessibilityInit;
-(void)_accessibilitySetUpQuickSpeak;
-(void)_accessibilityStatusChanged:(id)arg0 ;
-(void)_addAfterCACommitBlockForViewController:(id)arg0 ;
-(void)_addDocument:(id)arg0 forUserActivity:(id)arg1 ;
-(void)_addResponder:(id)arg0 forUserActivity:(id)arg1 ;
-(void)_alertItemStateChanged;
-(void)_appendSessionToSessionSet:(id)arg0 save:(BOOL)arg1 ;
-(void)_applicationDidEnterBackground;
-(void)_applicationHandleIntentForwardingAction:(id)arg0 ;
-(void)_applicationHandleSiriTask:(id)arg0 ;
-(void)_applicationHandleWatchKitRequest:(id)arg0 ;
-(void)_applicationOpenURL:(id)arg0 payload:(id)arg1 ;
-(void)_applicationOpenURLAction:(id)arg0 payload:(id)arg1 origin:(id)arg2 ;
-(void)_applicationShouldRequestHealthAuthorization;
-(void)_beginFenceTaskIfNecessary;
-(void)_beginShowingNetworkActivityIndicator;
-(void)_beginSnapshotSessionForScene:(id)arg0 withSnapshotBlock:(id)arg1 ;
-(void)_callInitializationDelegatesWithActions:(id)arg0 forCanvas:(id)arg1 payload:(id)arg2 fromOriginatingProcess:(id)arg3 ;
-(void)_cancelAllEventsOfType:(NSInteger)arg0 onEventRoutingScene:(id)arg1 ;
-(void)_cancelAllEventsOfType:(NSInteger)arg0 onWindowScene:(id)arg1 ;
-(void)_cancelAllInputs;
-(void)_cancelAllInputsOnEventRoutingScene:(id)arg0 ;
-(void)_cancelAllPressesForTVOnly;
-(void)_cancelAllTouches;
-(void)_cancelGestureRecognizers:(id)arg0 ;
-(void)_cancelGestureRecognizersForView:(id)arg0 ;
-(void)_cancelPhysicalButtonsWithType:(NSInteger)arg0 forPressesEvent:(id)arg1 ;
-(void)_cancelPressesIfNeededForViewRemovedFromResponderChain:(id)arg0 ;
-(void)_cancelTouchesOrPresses:(id)arg0 withEvent:(id)arg1 ;
-(void)_cancelTouchesOrPresses:(id)arg0 withEvent:(id)arg1 includingGestures:(BOOL)arg2 notificationBlock:(id)arg3 ;
-(void)_cancelUnfinishedPhysicalKeyboardPresses;
-(void)_cancelUnfinishedPhysicalKeyboardPressesForUIWindowEventRoutingScene:(id)arg0 ;
-(void)_cancelUnfinishedPressesForEvent:(id)arg0 ;
-(void)_cancelUnfinishedTouchesForEvent:(id)arg0 ;
-(void)_cancelViewProcessingOfTouchesOrPresses:(id)arg0 withEvent:(id)arg1 sendingCancelToViewsOfTouchesOrPresses:(id)arg2 ;
-(void)_checkActivityContinuationAndBecomeCurrentIfNeeded;
-(void)_checkBackgroundRefreshAPIAdoption;
-(void)_clearSystemNavigationAction;
-(void)_clearTouchesForView:(id)arg0 onWindow:(id)arg1 ;
-(void)_closeCanvasDefinition:(id)arg0 withOptions:(id)arg1 errorHandler:(id)arg2 ;
-(void)_compellApplicationLaunchToCompleteUnconditionally;
-(void)_configureLaunchOptions:(id)arg0 ;
-(void)_configureSnapshotContext:(id)arg0 forScreen:(id)arg1 scene:(id)arg2 ;
-(void)_createStatusBarIfNeededWithOrientation:(NSInteger)arg0 ;
-(void)_createStatusBarWithRequestedStyle:(NSInteger)arg0 orientation:(NSInteger)arg1 hidden:(BOOL)arg2 ;
-(void)_deactivateForReason:(int)arg0 ;
-(void)_deactivateForReason:(int)arg0 notify:(BOOL)arg1 ;
-(void)_deactivateReachability;
-(void)_deliverRemainingKeyUpEvents;
-(void)_discardSceneSessions:(id)arg0 ;
-(void)_discardSceneSessionsWithPersistentIdentifiers:(id)arg0 skippingPersistenceDeletion:(BOOL)arg1 ;
-(void)_eatCurrentTouchForWindow:(id)arg0 ;
-(void)_endBackgroundTask:(NSUInteger)arg0 ;
-(void)_endShowingNetworkActivityIndicator;
-(void)_enqueueHIDEvent:(struct __IOHIDEvent *)arg0 ;
-(void)_executeNextResizeSubTest;
-(void)_executeResizeTest;
-(void)_fetchInfoPlistFlags;
-(void)_findBestActivityToMakeCurrent:(id)arg0 ;
-(void)_finishButtonEvent:(id)arg0 ;
-(void)_fireBackgroundExpirationHandlers;
-(void)_fixupBackgroundHitTestWindow;
-(void)_forceEndIgnoringInteractionEvents;
-(void)_handleApplicationShortcutAction:(id)arg0 onWindowScene:(id)arg1 ;
-(void)_handleDaemonApplicationActivationWithScene:(id)arg0 completion:(id)arg1 ;
-(void)_handleDeviceOrientationChangedEvent:(struct __GSEvent *)arg0 ;
-(void)_handleGameControllerEvent:(id)arg0 ;
-(void)_handleHIDEvent:(struct __IOHIDEvent *)arg0 ;
-(void)_handleHeadsetButtonClick;
-(void)_handleHeadsetButtonDoubleClick;
-(void)_handleHeadsetButtonTripleClick;
-(void)_handleKeyEvent:(struct __GSEvent *)arg0 ;
-(void)_handleKeyHIDEvent:(struct __IOHIDEvent *)arg0 usingSyntheticEvent:(BOOL)arg1 ;
-(void)_handleKeyUIEvent:(id)arg0 ;
-(void)_handleKeyboardPressEvent:(id)arg0 ;
-(void)_handleLegacyEmojiKeyboardShortcut:(id)arg0 ;
-(void)_handleLocalizationDelegateCallbacks;
-(void)_handleNonLaunchSpecificActions:(id)arg0 forScene:(id)arg1 withTransitionContext:(id)arg2 completion:(id)arg3 ;
-(void)_handlePlatformSpecificActions:(id)arg0 forScene:(id)arg1 withTransitionContext:(id)arg2 ;
-(void)_handleScreenshot;
-(void)_handleSuspensionActions;
-(void)_handleTaskCompletionAndTerminate:(id)arg0 ;
-(void)_handleUnicodeEvent:(struct __IOHIDEvent *)arg0 ;
-(void)_handleUserDefaultsDidChange:(id)arg0 ;
-(void)_hardwareKeyboardAvailabilityChanged:(id)arg0 ;
-(void)_headsetButtonDown:(struct __IOHIDEvent *)arg0 ;
-(void)_headsetButtonUp:(struct __IOHIDEvent *)arg0 ;
-(void)_hideNetworkActivityIndicator;
-(void)_initiateLaunchActionsBackgrounded:(BOOL)arg0 firstActivation:(BOOL)arg1 ;
-(void)_leak;
-(void)_maybeEffectiveUserInterfaceStyleChanged;
-(void)_noteAnimationFinished:(id)arg0 ;
-(void)_noteAnimationStarted:(id)arg0 ;
-(void)_notifyDidChangeStatusBarFrame:(struct CGRect )arg0 ;
-(void)_notifyWillChangeStatusBarFrame:(struct CGRect )arg0 ;
-(void)_observeDebugOrTestUserInterfaceStyleChanged;
-(void)_openCanvasDefinition:(id)arg0 withUserActivity:(id)arg1 options:(id)arg2 errorHandler:(id)arg3 ;
-(void)_openURL:(id)arg0 options:(id)arg1 openApplicationEndpoint:(id)arg2 completionHandler:(id)arg3 ;
-(void)_openURL:(id)arg0 originatingView:(id)arg1 completionHandler:(id)arg2 ;
-(void)_openURL:(id)arg0 originatingView:(id)arg1 options:(id)arg2 completionHandler:(id)arg3 ;
-(void)_performAfterCATransactionCommitsWithLegacyRunloopObserverBasedTiming:(BOOL)arg0 block:(id)arg1 ;
-(void)_performBlockAfterCATransactionCommitSynchronizes:(id)arg0 ;
-(void)_performBlockAfterCATransactionCommits:(id)arg0 ;
-(void)_performMemoryWarning;
-(void)_performRefreshForUIScene:(id)arg0 disposeAfter:(BOOL)arg1 completion:(id)arg2 ;
-(void)_performSnapshotsWithAction:(id)arg0 forScene:(id)arg1 completion:(id)arg2 ;
-(void)_performWithUICACommitStateSnapshotting:(id)arg0 ;
-(void)_pipStateDidChange;
-(void)_popRunLoopMode:(id)arg0 requester:(id)arg1 reason:(id)arg2 ;
-(void)_postSimpleRemoteNotificationForAction:(NSInteger)arg0 andContext:(NSInteger)arg1 trackID:(id)arg2 ;
-(void)_presentEditAlertController:(id)arg0 ;
-(void)_printDocument:(id)arg0 ;
-(void)_purgeSharedInstances;
-(void)_pushRunLoopMode:(id)arg0 requester:(id)arg1 reason:(id)arg2 ;
-(void)_receivedMemoryNotification;
-(void)_registerEstimatedTouches:(id)arg0 event:(id)arg1 forTouchable:(id)arg2 ;
-(void)_registerForAlertItemStateChangeNotification;
-(void)_registerForBackgroundRefreshStatusChangedNotification;
-(void)_registerForHangTracerEnabledStateChangedNotification;
-(void)_registerForKeyBagLockStatusNotification;
-(void)_registerForKeyboardLayoutChangedNotification;
-(void)_registerForLanguageChangedNotification;
-(void)_registerForLocaleChangedNotification;
-(void)_registerForLocaleWillChangeNotification;
-(void)_registerForNameLayerTreeNotification;
-(void)_registerForRemoteNotificationTypes:(NSUInteger)arg0 ;
-(void)_registerForSignificantTimeChangeNotification;
-(void)_registerForUserDefaultsChanges;
-(void)_reloadKeyboardArbiterState;
-(void)_removeDocument:(id)arg0 forUserActivity:(id)arg1 ;
-(void)_removeHIDEventObserver;
-(void)_removeHIDGameControllerEventObserver;
-(void)_removeResponder:(id)arg0 forUserActivity:(id)arg1 ;
-(void)_removeSessionFromSessionSet:(id)arg0 ;
-(void)_reportMainSceneUpdateFinished:(id)arg0 ;
-(void)_reportMainSceneUpdateFinishedPossiblyDeferredPortions;
-(void)_reportResults:(id)arg0 ;
-(void)_requestDeviceUnlockWithCompletion:(id)arg0 ;
-(void)_requestSceneActivationWithConfiguration:(id)arg0 animated:(BOOL)arg1 sender:(id)arg2 errorHandler:(id)arg3 ;
-(void)_requestSceneSessionActivationWithConfiguration:(id)arg0 errorHandler:(id)arg1 ;
-(void)_resendHoverEventForWindow:(id)arg0 ;
-(void)_resetGSKeyboardModifierStateIfNecessary:(struct __IOHIDEvent *)arg0 ;
// -(void)_restoreApplicationPreservationStateWithSessionIdentifier:(id)arg0 beginHandler:(id)arg1 completionHandler:(unk)arg2  ;
-(void)_run;
// -(void)_runSubTestForKeyboardBringupWithName:(id)arg0 withShowKeyboardBlock:(id)arg1 withHideKeyboardBlock:(unk)arg2 withExtraResultsBlock:(id)arg3 withCleanupBlock:(unk)arg4  ;
// -(void)_runSubTestForKeyboardDismissalWithName:(id)arg0 withHideKeyboardBlock:(id)arg1 withExtraResultsBlock:(unk)arg2 withCleanupBlock:(id)arg3  ;
// -(void)_runSubTestForKeyboardMergeWithName:(id)arg0 withExtraResultsBlock:(id)arg1 withCleanupBlock:(unk)arg2  ;
// -(void)_runSubTestForKeyboardSplitWithName:(id)arg0 withShowKeyboardBlock:(id)arg1 withExtraResultsBlock:(unk)arg2 withCleanupBlock:(id)arg3  ;
-(void)_runWithDaemonScene:(id)arg0 completion:(id)arg1 ;
-(void)_runWithMainScene:(id)arg0 transitionContext:(id)arg1 completion:(id)arg2 ;
// -(void)_saveApplicationPreservationState:(id)arg0 viewController:(id)arg1 sessionIdentifier:(id)arg2 beginHandler:(id)arg3 completionHandler:(unk)arg4  ;
-(void)_saveApplicationPreservationStateIfSupported;
-(void)_saveRestorationUserActivityStateForCanvas:(id)arg0 ;
-(void)_saveRestorationUserActivityStateForScene:(id)arg0 ;
-(void)_scheduleLocalNotification:(id)arg0 ;
-(void)_scheduleSceneEventResponseForScene:(id)arg0 withResponseBlock:(id)arg1 ;
-(void)_scrollsToTopInitiatorView:(id)arg0 touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)_sendButtonEventWithPressInfo:(id)arg0 ;
-(void)_sendButtonEventWithType:(NSInteger)arg0 phase:(NSInteger)arg1 timestamp:(CGFloat)arg2 ;
-(void)_sendButtonEventWithType:(NSInteger)arg0 phase:(NSInteger)arg1 timestamp:(CGFloat)arg2 contextID:(unsigned int)arg3 ;
-(void)_sendDictionaryToPPT:(id)arg0 ;
-(void)_sendEventToGameControllerObserver:(struct __IOHIDEvent *)arg0 ;
-(void)_sendHeadsetOriginatedMediaRemoteCommand:(unsigned int)arg0 ;
-(void)_sendMoveEventWithDirection:(NSInteger)arg0 heading:(NSUInteger)arg1 fromEvent:(id)arg2 ;
-(void)_sendMoveEventWithPhysicalButtonsEvent:(id)arg0 ;
-(void)_sendWillEnterForegroundCallbacks;
-(void)_setAlwaysHitTestsForMainScreen:(BOOL)arg0 ;
-(void)_setAmbiguousControlCenterActivationMargin:(CGFloat)arg0 ;
-(void)_setApplicationBackdropStyle:(NSInteger)arg0 ;
-(void)_setApplicationIsOpaque:(BOOL)arg0 ;
-(void)_setBackgroundStyle:(NSInteger)arg0 ;
-(void)_setCompatibilityModeOnSettings:(id)arg0 ;
-(void)_setDefaultTopNavBarTintColor:(id)arg0 ;
-(void)_setDisableBecomeFirstResponder:(BOOL)arg0 ;
-(void)_setForcedUserInterfaceLayoutDirection:(NSInteger)arg0 ;
// -(void)_setHIDEventObserver:(id)arg0 onQueue:(unk)arg1  ;
// -(void)_setHIDGameControllerEventObserver:(id)arg0 onQueue:(unk)arg1  ;
-(void)_setHandlingURL:(BOOL)arg0 url:(id)arg1 ;
-(void)_setIdleModeVisualEffectsEnabled:(BOOL)arg0 ;
-(void)_setIgnoreHeadsetClicks:(BOOL)arg0 ;
-(void)_setPreferredUserInterfaceStyleForWallpaper:(NSInteger)arg0 ;
-(void)_setReachabilitySupported:(BOOL)arg0 ;
-(void)_setRestorationExtended:(BOOL)arg0 ;
-(void)_setRotationDisabledDuringTouch:(BOOL)arg0 ;
-(void)_setSaveStateRestorationArchiveWithFileProtectionCompleteUntilFirstUserAuthentication;
-(void)_setShouldFixMainThreadPriority:(BOOL)arg0 ;
-(void)_setStatusBarShowsProgress:(BOOL)arg0 ;
-(void)_setSystemNavigationAction:(id)arg0 ;
-(void)_setSystemUserInterfaceStyle:(NSInteger)arg0 ;
-(void)_setSystemWindowsSecure:(BOOL)arg0 ;
-(void)_setUserDefaultsSyncEnabled:(BOOL)arg0 ;
-(void)_setWatchSystemAppHIDEventFilter:(id)arg0 ;
-(void)_setupMotionFeedbackGenerator;
-(void)_setupStatusBarWithRequestedStyle:(NSInteger)arg0 orientation:(NSInteger)arg1 hidden:(BOOL)arg2 ;
-(void)_showEditAlertViewWithUndoManager:(id)arg0 window:(id)arg1 ;
-(void)_startHangTracer;
-(void)_stopDeactivatingForReason:(int)arg0 ;
-(void)_stopHangTracer;
-(void)_synchronizeSystemAnimationFencesWithSpinCleanUpBlock:(id)arg0 ;
-(void)_teardownMotionEventBehavior;
-(void)_terminateWithStatus:(int)arg0 ;
-(void)_trackSystemAnimationFence:(id)arg0 ;
-(void)_unregisterForLanguageChangedNotification;
-(void)_unregisterForLocaleChangedNotification;
-(void)_unregisterForSignificantTimeChangeNotification;
-(void)_unregisterForTimeChangedNotification;
-(void)_unregisterForUserDefaultsChanges;
-(void)_updateAccessibilityItunesSettings;
-(void)_updateAppPriorityForSuspendedState;
-(void)_updateApplicationAccessibility;
-(void)_updateEffectiveUserInterfaceStyleAfterChange:(id)arg0 ;
-(void)_updateHangTracer;
-(void)_updateIdleModeStatus;
-(void)_updateLargeTextNotification;
-(void)_updateOrientation;
-(void)_updateSerializableKeyCommandsForResponder:(id)arg0 ;
-(void)_updateSnapshotAndStateRestorationWithAction:(id)arg0 windowScene:(id)arg1 ;
-(void)_updateSnapshotForBackgroundApplication:(BOOL)arg0 ;
// -(void)_updateStateRestorationArchiveForBackgroundEvent:(id)arg0 saveState:(unk)arg1 exitIfCouldNotRestoreState:(BOOL)arg2 updateSnapshot:(BOOL)arg3 windowScene:(BOOL)arg4  ;
-(void)_wakeTimerFired;
-(void)_wheelChangedWithEvent:(id)arg0 ;
-(void)acceleratedInX:(float)arg0 Y:(float)arg1 Z:(float)arg2 ;
-(void)accessoryKeyStateChanged:(struct __GSEvent *)arg0 ;
-(void)activityContinuationManager:(id)arg0 configureProgressUIWithError:(id)arg1 ;
-(void)activityContinuationManager:(id)arg0 didFailToContinueUserActivityWithType:(id)arg1 error:(id)arg2 ;
-(void)activityContinuationManager:(id)arg0 didUpdateUserActivity:(id)arg1 ;
-(void)activityContinuationManager:(id)arg0 displayProgressUI:(id)arg1 dismissalHandler:(id)arg2 ;
-(void)activityContinuationManager:(id)arg0 hideProgressUIWithCompletion:(id)arg1 ;
-(void)addStatusBarItem:(int)arg0 ;
-(void)addStatusBarItem:(int)arg0 removeOnExit:(BOOL)arg1 ;
-(void)addStatusBarStyleOverrides:(NSUInteger)arg0 ;
-(void)addWebClipToHomeScreen:(id)arg0 ;
-(void)applicationDidBeginSuspendAnimation;
-(void)applicationDidEndResumeAnimation;
-(void)applicationDidResume;
-(void)applicationDidResumeForEventsOnly;
-(void)applicationDidResumeFromUnderLock;
-(void)applicationOpenToShortCut:(id)arg0 ;
-(void)applicationOpenURL:(id)arg0 ;
-(void)applicationSuspend;
-(void)applicationWillSuspend;
-(void)applicationWillSuspendForEventsOnly;
-(void)applicationWillSuspendUnderLock;
-(void)applicationWillTerminate;
-(void)batteryStatusDidChange:(id)arg0 ;
-(void)beginIgnoringInteractionEvents;
-(void)beginReceivingRemoteControlEvents;
-(void)beginRemoteSheetController:(id)arg0 delegate:(id)arg1 didEndSelector:(SEL)arg2 contextInfo:(*void)arg3 requireTopApplication:(BOOL)arg4 opaque:(BOOL)arg5 presentAnimated:(BOOL)arg6 ;
-(void)buildMenuWithBuilder:(id)arg0 ;
-(void)cancelAllLocalNotifications;
-(void)cancelLocalNotification:(id)arg0 ;
-(void)clearHardwareKeyboardState;
-(void)clearKeepAliveTimeout;
-(void)completeStateRestoration;
-(void)dealloc;
-(void)didDismissMiniAlert;
-(void)didReceiveMemoryWarning;
-(void)emitPPTEndTracePointForSubTestName:(id)arg0 identifier:(NSUInteger)arg1 ;
-(void)emitPPTEndTracePointForTestName:(id)arg0 identifier:(NSUInteger)arg1 ;
-(void)emitPPTStartTracePointForSubTestName:(id)arg0 identifier:(NSUInteger)arg1 testIdentifier:(NSUInteger)arg2 ;
-(void)emitPPTStartTracePointForTestName:(id)arg0 identifier:(NSUInteger)arg1 ;
-(void)endBackgroundTask:(NSUInteger)arg0 ;
-(void)endIgnoringInteractionEvents;
-(void)endReceivingRemoteControlEvents;
-(void)endRemoteSheet:(id)arg0 ;
-(void)extendSnapshotContext:(id)arg0 forSnapshotAction:(id)arg1 ;
-(void)extendStateRestoration;
-(void)failedTest:(id)arg0 ;
-(void)failedTest:(id)arg0 withFailure:(id)arg1 ;
-(void)failedTest:(id)arg0 withFailure:(id)arg1 withResults:(id)arg2 ;
-(void)failedTest:(id)arg0 withResults:(id)arg1 ;
-(void)finishedIPTest:(id)arg0 ;
-(void)finishedIPTest:(id)arg0 extraResults:(id)arg1 ;
-(void)finishedIPTest:(id)arg0 extraResults:(id)arg1 withTeardownBlock:(id)arg2 ;
-(void)finishedIPTest:(id)arg0 waitForCommit:(BOOL)arg1 extraResults:(id)arg2 withTeardownBlock:(id)arg3 ;
-(void)finishedSubTest:(id)arg0 forTest:(id)arg1 ;
-(void)finishedSubTest:(id)arg0 forTest:(id)arg1 waitForCommit:(BOOL)arg2 ;
-(void)finishedTest:(id)arg0 ;
-(void)finishedTest:(id)arg0 extraResults:(id)arg1 ;
-(void)finishedTest:(id)arg0 extraResults:(id)arg1 waitForNotification:(id)arg2 ;
-(void)finishedTest:(id)arg0 extraResults:(id)arg1 waitForNotification:(id)arg2 withTeardownBlock:(id)arg3 ;
-(void)finishedTest:(id)arg0 extraResults:(id)arg1 withTeardownBlock:(id)arg2 ;
-(void)finishedTest:(id)arg0 waitForCommit:(BOOL)arg1 extraResults:(id)arg2 ;
-(void)finishedTest:(id)arg0 waitForCommit:(BOOL)arg1 extraResults:(id)arg2 withTeardownBlock:(id)arg3 ;
-(void)handleKeyEvent:(struct __GSEvent *)arg0 ;
-(void)handleKeyHIDEvent:(struct __IOHIDEvent *)arg0 ;
-(void)handleKeyUIEvent:(id)arg0 ;
-(void)headsetAvailabilityChanged:(struct __GSEvent *)arg0 ;
-(void)headsetButtonDown:(struct __GSEvent *)arg0 ;
-(void)headsetButtonUp:(struct __GSEvent *)arg0 ;
-(void)ignoreSnapshotOnNextApplicationLaunch;
-(void)installCACommitCompletionBlock:(id)arg0 ;
-(void)installNotificationObserverForNotificationName:(id)arg0 forOneNotification:(BOOL)arg1 usingBlock:(id)arg2 ;
-(void)layoutMonitor:(id)arg0 didUpdateDisplayLayout:(id)arg1 withContext:(id)arg2 ;
-(void)lockButtonDown:(struct __GSEvent *)arg0 ;
-(void)lockButtonUp:(struct __GSEvent *)arg0 ;
-(void)lockDevice:(struct __GSEvent *)arg0 ;
-(void)mediaKeyDown:(struct __GSEvent *)arg0 ;
-(void)mediaKeyUp:(struct __GSEvent *)arg0 ;
-(void)menuButtonDown:(struct __GSEvent *)arg0 ;
-(void)menuButtonUp:(struct __GSEvent *)arg0 ;
-(void)motionBegan:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)motionCancelled:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)motionEnded:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)noteActiveInterfaceOrientationDidChangeToOrientation:(NSInteger)arg0 willAnimateWithSettings:(id)arg1 fromOrientation:(NSInteger)arg2 ;
-(void)noteActiveInterfaceOrientationWillChangeToOrientation:(NSInteger)arg0 ;
-(void)openURL:(id)arg0 options:(id)arg1 completionHandler:(id)arg2 ;
-(void)openURL:(id)arg0 withCompletionHandler:(id)arg1 ;
-(void)orderFrontCharacterPalette:(id)arg0 ;
-(void)popRunLoopMode:(id)arg0 ;
-(void)popRunLoopMode:(id)arg0 requester:(id)arg1 ;
-(void)prepareForDefaultImageSnapshot;
-(void)prepareForDefaultImageSnapshotForScreen:(id)arg0 ;
-(void)prepareSnapshotsWithAction:(id)arg0 forScene:(id)arg1 completion:(id)arg2 ;
-(void)presentLocalNotificationNow:(id)arg0 ;
-(void)pressesBegan:(id)arg0 withEvent:(id)arg1 ;
-(void)pressesCancelled:(id)arg0 withEvent:(id)arg1 ;
-(void)pressesEnded:(id)arg0 withEvent:(id)arg1 ;
-(void)proximityStateChanged:(BOOL)arg0 ;
-(void)pushRegistry:(id)arg0 didInvalidatePushTokenForType:(id)arg1 error:(id)arg2 ;
-(void)pushRegistry:(id)arg0 didReceiveIncomingPushWithPayload:(id)arg1 forType:(id)arg2 withCompletionHandler:(id)arg3 ;
-(void)pushRegistry:(id)arg0 didUpdatePushCredentials:(id)arg1 forType:(id)arg2 ;
-(void)pushRunLoopMode:(id)arg0 ;
-(void)pushRunLoopMode:(id)arg0 requester:(id)arg1 ;
-(void)registerForRemoteNotificationTypes:(NSUInteger)arg0 ;
-(void)registerForRemoteNotifications;
// -(void)registerPlatformSpecificLaunchOptions:(id)arg0 transitionContext:(unk)arg1  ;
-(void)registerUserNotificationSettings:(id)arg0 ;
-(void)removeApplicationPreservationStateWithSessionIdentifier:(id)arg0 ;
-(void)removeStatusBarItem:(int)arg0 ;
-(void)removeStatusBarStyleOverrides:(NSUInteger)arg0 ;
-(void)requestSceneSessionActivation:(id)arg0 userActivity:(id)arg1 options:(id)arg2 errorHandler:(id)arg3 ;
-(void)requestSceneSessionDestruction:(id)arg0 options:(id)arg1 errorHandler:(id)arg2 ;
-(void)requestSceneSessionRefresh:(id)arg0 ;
-(void)resetIdleTimerAndUndim;
// -(void)restoreApplicationPreservationStateWithSessionIdentifier:(id)arg0 viewController:(id)arg1 beginHandler:(id)arg2 completionHandler:(unk)arg3  ;
-(void)ringerChanged:(int)arg0 ;
// -(void)rotateIfNeeded:(NSInteger)arg0 before:(id)arg1 after:(unk)arg2  ;
-(void)rotateIfNeeded:(NSInteger)arg0 completion:(id)arg1 ;
-(void)runModal:(id)arg0 ;
-(void)runTest:(id)arg0 forAnimation:(id)arg1 ;
-(void)runTest:(id)arg0 startingBeforeAnimation:(id)arg1 stoppingAfterAnimation:(id)arg2 ;
// -(void)runTestForKeyboardBringupAndDismissalWithName:(id)arg0 withShowKeyboardBlock:(id)arg1 withHideKeyboardBlock:(unk)arg2 withExtraResultsBlock:(id)arg3 withCleanupBlock:(unk)arg4  ;
// -(void)runTestForKeyboardRotationWithName:(id)arg0 fromOrientation:(NSInteger)arg1 withShowKeyboardBlock:(id)arg2 withExtraResultsBlock:(unk)arg3 withCleanupBlock:(id)arg4  ;
// -(void)runTestForKeyboardSplitAndMergeWithName:(id)arg0 withShowKeyboardBlock:(id)arg1 withExtraResultsBlock:(unk)arg2 withCleanupBlock:(id)arg3  ;
// -(void)saveApplicationPreservationStateWithSessionIdentifier:(id)arg0 viewController:(id)arg1 beginHandler:(id)arg2 completionHandler:(unk)arg3  ;
-(void)scheduleLocalNotification:(id)arg0 ;
-(void)sendEvent:(id)arg0 ;
-(void)setApplicationBadgeString:(id)arg0 ;
-(void)setBacklightLevel:(float)arg0 ;
-(void)setCapsLockDelayOverride:(CGFloat)arg0 ;
-(void)setDoubleHeightPrefixText:(id)arg0 ;
-(void)setDoubleHeightStatusText:(id)arg0 ;
-(void)setDoubleHeightStatusText:(id)arg0 forStyle:(NSInteger)arg1 ;
-(void)setExpectsFaceContact:(BOOL)arg0 ;
-(void)setExpectsFaceContact:(BOOL)arg0 inLandscape:(BOOL)arg1 ;
-(void)setGlowAnimationEnabled:(BOOL)arg0 forStyle:(NSInteger)arg1 ;
-(void)setHardwareKeyboardLayoutName:(id)arg0 ;
-(void)setHardwareKeyboardLayoutName:(id)arg0 forceRebuild:(BOOL)arg1 ;
-(void)setIgnoresInteractionEvents:(BOOL)arg0 ;
-(void)setMinimumBackgroundFetchInterval:(CGFloat)arg0 ;
-(void)setNewsstandIconImage:(id)arg0 ;
-(void)setProximityEventsEnabled:(BOOL)arg0 ;
-(void)setProximitySensingEnabled:(BOOL)arg0 ;
-(void)setReceivesMemoryWarnings:(BOOL)arg0 ;
-(void)setScheduledLocalNotifications:(id)arg0 ;
-(void)setShortcutItems:(id)arg0 ;
-(void)setStatusBarShowsProgress:(BOOL)arg0 ;
-(void)setSuspensionAnimationDelay:(CGFloat)arg0 ;
-(void)setSystemVolumeHUDEnabled:(BOOL)arg0 ;
-(void)setSystemVolumeHUDEnabled:(BOOL)arg0 forAudioCategory:(id)arg1 ;
-(void)setUsesBackgroundNetwork:(BOOL)arg0 ;
-(void)setWantsLockEvents:(BOOL)arg0 ;
-(void)setWantsVolumeButtonEvents:(BOOL)arg0 ;
-(void)showHelp:(id)arg0 ;
// -(void)showKeyboardUsingBlock:(id)arg0 withCompletionBlock:(unk)arg1  ;
-(void)showNetworkPromptsIfNecessary:(BOOL)arg0 ;
-(void)significantTimeChange;
-(void)startCHUDRecording:(id)arg0 ;
-(void)startDictation:(id)arg0 ;
-(void)startLeaking;
-(void)startedAnimationTest:(id)arg0 ;
-(void)startedIPTest:(id)arg0 ;
-(void)startedSubTest:(id)arg0 forTest:(id)arg1 ;
-(void)startedSubTest:(id)arg0 forTest:(id)arg1 withMetrics:(id)arg2 ;
-(void)startedTest:(id)arg0 ;
-(void)statusBar:(id)arg0 didAnimateFromHeight:(CGFloat)arg1 toHeight:(CGFloat)arg2 animation:(int)arg3 ;
-(void)statusBar:(id)arg0 willAnimateFromHeight:(CGFloat)arg1 toHeight:(CGFloat)arg2 duration:(CGFloat)arg3 animation:(int)arg4 ;
-(void)stopAndReportResultsForTest:(id)arg0 extraResults:(id)arg1 waitForNotification:(id)arg2 withTeardownBlock:(id)arg3 ;
-(void)stopCHUDRecording;
-(void)stopLeaking;
-(void)stopModal;
-(void)suspend;
-(void)suspendReturningToLastApp:(BOOL)arg0 ;
-(void)terminateWithSuccess;
-(void)testPrep:(id)arg0 options:(id)arg1 ;
-(void)unregisterForRemoteNotifications;
-(void)updateSuspendedSettings:(id)arg0 ;
-(void)userDefaultsDidChange:(id)arg0 ;
-(void)vibrateForDuration:(int)arg0 ;
-(void)volumeChanged:(struct __GSEvent *)arg0 ;
-(void)willDisplayMiniAlert;
-(void)workspace:(id)arg0 didCreateScene:(id)arg1 withTransitionContext:(id)arg2 completion:(id)arg3 ;
-(void)workspace:(id)arg0 didReceiveActions:(id)arg1 ;
-(void)workspace:(id)arg0 willDestroyScene:(id)arg1 withTransitionContext:(id)arg2 completion:(id)arg3 ;
-(void)workspaceShouldExit:(id)arg0 withTransitionContext:(id)arg1 ;


@end


#endif