// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef CIFILTER_H
#define CIFILTER_H

@class NSDictionary, NSArray, NSString;
@protocol NSSecureCoding, NSCopying;

#import <Foundation/Foundation.h>

#import "CIImage.h"

@interface CIFilter : NSObject <NSSecureCoding, NSCopying>

 {
    *void _priv;
}


@property (readonly, nonatomic) NSDictionary *attributes;
@property (getter=isEnabled) BOOL enabled; // ivar: _enabled
@property (readonly, nonatomic) NSArray *inputKeys;
@property (copy, nonatomic) NSString *name;
@property (readonly, nonatomic) CIImage *outputImage;
@property (readonly, nonatomic) NSArray *outputKeys;


+(BOOL)exchangeImplementationsForClass;
+(BOOL)supportsSecureCoding;
+(BOOL)wrapClassIfNeeded:(Class)arg0 ;
+(id)CMYKHalftone;
+(id)KMeansFilter;
+(id)LabDeltaE;
+(id)PDF417BarcodeGenerator;
+(id)QRCodeGenerator;
+(id)_filterArrayFromImageMetadata:(struct CGImageMetadata *)arg0 inputImageExtent:(struct CGRect )arg1 ;
+(id)_filterArrayFromProperties:(id)arg0 ;
+(id)_filterArrayFromProperties:(id)arg0 inputImageExtent:(struct CGRect )arg1 ;
+(id)_propertyArrayFromFilters:(id)arg0 inputImageExtent:(struct CGRect )arg1 ;
+(id)accordionFoldTransitionFilter;
+(id)additionCompositingFilter;
+(id)affineClampFilter;
+(id)affineTileFilter;
+(id)allCategories:(BOOL)arg0 ;
+(id)areaAverageFilter;
+(id)areaHistogramFilter;
+(id)areaMaximumAlphaFilter;
+(id)areaMaximumFilter;
+(id)areaMinMaxFilter;
+(id)areaMinMaxRedFilter;
+(id)areaMinimumAlphaFilter;
+(id)areaMinimumFilter;
+(id)attributedTextImageGeneratorFilter;
+(id)aztecCodeGeneratorFilter;
+(id)barcodeGeneratorFilter;
+(id)barsSwipeTransitionFilter;
+(id)bicubicScaleTransformFilter;
+(id)blendWithAlphaMaskFilter;
+(id)blendWithBlueMaskFilter;
+(id)blendWithMaskFilter;
+(id)blendWithRedMaskFilter;
+(id)bloomFilter;
+(id)bokehBlurFilter;
+(id)boxBlurFilter;
+(id)bumpDistortionFilter;
+(id)bumpDistortionLinearFilter;
+(id)checkerboardGeneratorFilter;
+(id)circleSplashDistortionFilter;
+(id)circularScreenFilter;
+(id)circularWrapFilter;
+(id)code128BarcodeGeneratorFilter;
+(id)colorAbsoluteDifferenceFilter;
+(id)colorBlendModeFilter;
+(id)colorBurnBlendModeFilter;
+(id)colorClampFilter;
+(id)colorControlsFilter;
+(id)colorCrossPolynomialFilter;
+(id)colorCubeFilter;
+(id)colorCubeWithColorSpaceFilter;
+(id)colorCubesMixedWithMaskFilter;
+(id)colorCurvesFilter;
+(id)colorDodgeBlendModeFilter;
+(id)colorInvertFilter;
+(id)colorMapFilter;
+(id)colorMatrixFilter;
+(id)colorMonochromeFilter;
+(id)colorPolynomialFilter;
+(id)colorPosterizeFilter;
+(id)colorThresholdFilter;
+(id)colorThresholdOtsuFilter;
+(id)columnAverageFilter;
+(id)comicEffectFilter;
+(id)convolution3X3Filter;
+(id)convolution5X5Filter;
+(id)convolution7X7Filter;
+(id)convolution9HorizontalFilter;
+(id)convolution9VerticalFilter;
+(id)convolutionRGB3X3Filter;
+(id)convolutionRGB5X5Filter;
+(id)convolutionRGB7X7Filter;
+(id)convolutionRGB9HorizontalFilter;
+(id)convolutionRGB9VerticalFilter;
+(id)copyMachineTransitionFilter;
+(id)coreMLModelFilter;
+(id)crystallizeFilter;
+(id)customAttributes;
+(id)darkenBlendModeFilter;
+(id)depthOfFieldFilter;
+(id)depthToDisparityFilter;
+(id)differenceBlendModeFilter;
+(id)discBlurFilter;
+(id)disintegrateWithMaskTransitionFilter;
+(id)disparityToDepthFilter;
+(id)displacementDistortionFilter;
+(id)dissolveTransitionFilter;
+(id)ditherFilter;
+(id)divideBlendModeFilter;
+(id)documentEnhancerFilter;
+(id)dotScreenFilter;
+(id)drosteFilter;
+(id)edgePreserveUpsampleFilter;
+(id)edgeWorkFilter;
+(id)edgesFilter;
+(id)eightfoldReflectedTileFilter;
+(id)exclusionBlendModeFilter;
+(id)exposureAdjustFilter;
+(id)falseColorFilter;
+(id)filterArrayFromSerializedXMP:(id)arg0 inputImageExtent:(struct CGRect )arg1 error:(*id)arg2 ;
+(id)filterName:(id)arg0 append:(id)arg1 arguments:(id)arg2 ;
+(id)filterName:(id)arg0 prepend:(id)arg1 imageName:(id)arg2 arguments:(id)arg3 ;
+(id)filterName:(id)arg0 replacement:(id)arg1 ;
+(id)filterName:(id)arg0 replacement:(id)arg1 arguments:(id)arg2 ;
+(id)filterNamesInCategories:(id)arg0 ;
+(id)filterNamesInCategory:(id)arg0 ;
+(id)filterWithCVPixelBuffer:(struct __CVBuffer *)arg0 properties:(id)arg1 options:(id)arg2 ;
+(id)filterWithImageData:(id)arg0 options:(id)arg1 ;
+(id)filterWithImageURL:(id)arg0 options:(id)arg1 ;
+(id)filterWithName:(id)arg0 ;
+(id)filterWithName:(id)arg0 compatibilityVersion:(int)arg1 ;
+(id)filterWithName:(id)arg0 compatibilityVersion:(int)arg1 keysAndValues:(id)arg2 ;
+(id)filterWithName:(id)arg0 keysAndValues:(id)arg1 ;
+(id)filterWithName:(id)arg0 setDefaults:(BOOL)arg1 ;
+(id)filterWithName:(id)arg0 withInputParameters:(id)arg1 ;
+(id)filterWithString:(id)arg0 ;
+(id)flashTransitionFilter;
+(id)fourfoldReflectedTileFilter;
+(id)fourfoldRotatedTileFilter;
+(id)fourfoldTranslatedTileFilter;
+(id)gaborGradientsFilter;
+(id)gammaAdjustFilter;
+(id)gaussianBlurFilter;
+(id)gaussianGradientFilter;
+(id)glassDistortionFilter;
+(id)glassLozengeFilter;
+(id)glideReflectedTileFilter;
+(id)gloomFilter;
+(id)hardLightBlendModeFilter;
+(id)hatchedScreenFilter;
+(id)heightFieldFromMaskFilter;
+(id)hexagonalPixellateFilter;
+(id)highlightShadowAdjustFilter;
+(id)histogramDisplayFilter;
+(id)holeDistortionFilter;
+(id)hueAdjustFilter;
+(id)hueBlendModeFilter;
+(id)hueSaturationValueGradientFilter;
+(id)kaleidoscopeFilter;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg0 ;
+(id)keystoneCorrectionCombinedFilter;
+(id)keystoneCorrectionHorizontalFilter;
+(id)keystoneCorrectionVerticalFilter;
+(id)lanczosScaleTransformFilter;
+(id)lenticularHaloGeneratorFilter;
+(id)lightTunnelFilter;
+(id)lightenBlendModeFilter;
+(id)lineOverlayFilter;
+(id)lineScreenFilter;
+(id)linearBurnBlendModeFilter;
+(id)linearDodgeBlendModeFilter;
+(id)linearGradientFilter;
+(id)linearLightBlendModeFilter;
+(id)linearToSRGBToneCurveFilter;
+(id)localizedDescriptionForFilterName:(id)arg0 ;
+(id)localizedNameForCategory:(id)arg0 ;
+(id)localizedNameForFilterName:(id)arg0 ;
+(id)localizedReferenceDocumentationForFilterName:(id)arg0 ;
+(id)luminosityBlendModeFilter;
+(id)maskToAlphaFilter;
+(id)maskedVariableBlurFilter;
+(id)maximumComponentFilter;
+(id)maximumCompositingFilter;
+(id)medianFilter;
+(id)meshGeneratorFilter;
+(id)metalFilterWithName:(id)arg0 ;
+(id)metalFilterWithName:(id)arg0 withInputParameters:(id)arg1 ;
+(id)minimumComponentFilter;
+(id)minimumCompositingFilter;
+(id)mixFilter;
+(id)modTransitionFilter;
+(id)morphologyGradientFilter;
+(id)morphologyMaximumFilter;
+(id)morphologyMinimumFilter;
+(id)morphologyRectangleMaximumFilter;
+(id)morphologyRectangleMinimumFilter;
+(id)motionBlurFilter;
+(id)multiplyBlendModeFilter;
+(id)multiplyCompositingFilter;
+(id)ninePartStretchedFilter;
+(id)ninePartTiledFilter;
+(id)noiseReductionFilter;
+(id)opTileFilter;
+(id)overlayBlendModeFilter;
+(id)pageCurlTransitionFilter;
+(id)pageCurlWithShadowTransitionFilter;
+(id)paletteCentroidFilter;
+(id)palettizeFilter;
+(id)parallelogramTileFilter;
+(id)personSegmentationFilter;
+(id)perspectiveCorrectionFilter;
+(id)perspectiveRotateFilter;
+(id)perspectiveTileFilter;
+(id)perspectiveTransformFilter;
+(id)perspectiveTransformWithExtentFilter;
+(id)photoEffectChromeFilter;
+(id)photoEffectFadeFilter;
+(id)photoEffectInstantFilter;
+(id)photoEffectMonoFilter;
+(id)photoEffectNoirFilter;
+(id)photoEffectProcessFilter;
+(id)photoEffectTonalFilter;
+(id)photoEffectTransferFilter;
+(id)pinLightBlendModeFilter;
+(id)pinchDistortionFilter;
+(id)pixellateFilter;
+(id)pointillizeFilter;
+(id)prewarmedFilterFromString:(id)arg0 ;
+(id)radialGradientFilter;
+(id)randomGeneratorFilter;
+(id)rippleTransitionFilter;
+(id)roundedRectangleGeneratorFilter;
+(id)rowAverageFilter;
+(id)sRGBToneCurveToLinearFilter;
+(id)saliencyMapFilter;
+(id)saturationBlendModeFilter;
+(id)screenBlendModeFilter;
+(id)sepiaToneFilter;
+(id)serializedXMPFromFilters:(id)arg0 inputImageExtent:(struct CGRect )arg1 ;
+(id)shadedMaterialFilter;
+(id)sharpenLuminanceFilter;
+(id)sixfoldReflectedTileFilter;
+(id)sixfoldRotatedTileFilter;
+(id)smoothLinearGradientFilter;
+(id)softLightBlendModeFilter;
+(id)sourceAtopCompositingFilter;
+(id)sourceInCompositingFilter;
+(id)sourceOutCompositingFilter;
+(id)sourceOverCompositingFilter;
+(id)spotColorFilter;
+(id)spotLightFilter;
+(id)starShineGeneratorFilter;
+(id)straightenFilter;
+(id)stretchCropFilter;
+(id)stripesGeneratorFilter;
+(id)subtractBlendModeFilter;
+(id)sunbeamsGeneratorFilter;
+(id)supportedRawCameraModels;
+(id)swipeTransitionFilter;
+(id)temperatureAndTintFilter;
+(id)textImageGeneratorFilter;
+(id)thermalFilter;
+(id)toneCurveFilter;
+(id)torusLensDistortionFilter;
+(id)triangleKaleidoscopeFilter;
+(id)triangleTileFilter;
+(id)twelvefoldReflectedTileFilter;
+(id)twirlDistortionFilter;
+(id)unsharpMaskFilter;
+(id)vibranceFilter;
+(id)vignetteEffectFilter;
+(id)vignetteFilter;
+(id)vividLightBlendModeFilter;
+(id)vortexDistortionFilter;
+(id)whitePointAdjustFilter;
+(id)xRayFilter;
+(id)zoomBlurFilter;
+(int)getMinMaxSimulatedApertureFrom:(struct __CFData *)arg0 minValue:(*float)arg1 maxValue:(*float)arg2 version:(*int)arg3 ;
+(int)maxSDOFRenderingVersionSupported;
+(struct CGImageMetadata *)_imageMetadataFromFilters:(id)arg0 inputImageExtent:(struct CGRect )arg1 ;
+(unsigned int)indexForWrapperNumber:(unsigned int)arg0 ;
+(void)addFilterToSkip:(id)arg0 ;
+(void)clearCache;
+(void)registerFilterName:(id)arg0 constructor:(id)arg1 classAttributes:(id)arg2 ;
+(void)unregisterFilterName:(id)arg0 ;
-(BOOL)_filterClassInCategory:(id)arg0 ;
-(BOOL)_isIdentity;
-(BOOL)verifyPrewarmedFilter:(id)arg0 ;
-(NSUInteger)hash;
-(id)_append:(id)arg0 image:(id)arg1 ;
-(id)_appendSingleFilterTo:(id)arg0 filterAndSettings:(id)arg1 ;
-(id)_copyFilterWithZone:(struct _NSZone *)arg0 ;
-(id)_serializedXMPString;
-(id)apply:(id)arg0 ;
-(id)apply:(id)arg0 arguments:(id)arg1 options:(id)arg2 ;
-(id)apply:(id)arg0 image:(id)arg1 arguments:(id)arg2 inSpace:(struct CGColorSpace *)arg3 ;
-(id)apply:(id)arg0 image:(id)arg1 arguments:(id)arg2 inoutSpace:(struct CGColorSpace *)arg3 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)customAttributes;
-(id)debugDescription;
-(id)description;
-(id)initWithCoder:(id)arg0 ;
-(id)mutableCopyWithZone:(struct _NSZone *)arg0 ;
-(id)outputImageCatchAll:(unsigned int)arg0 ;
-(id)prewarmingString;
-(id)userInfo;
-(id)valueForUndefinedKey:(id)arg0 ;
-(id)wrappedOutputImage10;
-(id)wrappedOutputImage11;
-(id)wrappedOutputImage12;
-(id)wrappedOutputImage13;
-(id)wrappedOutputImage14;
-(id)wrappedOutputImage15;
-(id)wrappedOutputImage16;
-(id)wrappedOutputImage17;
-(id)wrappedOutputImage18;
-(id)wrappedOutputImage19;
-(id)wrappedOutputImage20;
-(id)wrappedOutputImage21;
-(id)wrappedOutputImage22;
-(id)wrappedOutputImage23;
-(id)wrappedOutputImage24;
-(id)wrappedOutputImage25;
-(id)wrappedOutputImage26;
-(id)wrappedOutputImage27;
-(id)wrappedOutputImage28;
-(id)wrappedOutputImage29;
-(id)wrappedOutputImage30;
-(id)wrappedOutputImage31;
-(id)wrappedOutputImage32;
-(id)wrappedOutputImage33;
-(id)wrappedOutputImage34;
-(id)wrappedOutputImage35;
-(id)wrappedOutputImage36;
-(id)wrappedOutputImage37;
-(id)wrappedOutputImage38;
-(id)wrappedOutputImage39;
-(id)wrappedOutputImage40;
-(id)wrappedOutputImage41;
-(id)wrappedOutputImage42;
-(id)wrappedOutputImage43;
-(id)wrappedOutputImage44;
-(id)wrappedOutputImage45;
-(id)wrappedOutputImage46;
-(id)wrappedOutputImage47;
-(id)wrappedOutputImage48;
-(id)wrappedOutputImage49;
-(id)wrappedOutputImage50;
-(id)wrappedOutputImage51;
-(id)wrappedOutputImage52;
-(id)wrappedOutputImage53;
-(id)wrappedOutputImage54;
-(id)wrappedOutputImage55;
-(id)wrappedOutputImage56;
-(id)wrappedOutputImage57;
-(id)wrappedOutputImage58;
-(id)wrappedOutputImage59;
-(id)wrappedOutputImage60;
-(id)wrappedOutputImage61;
-(id)wrappedOutputImage62;
-(id)wrappedOutputImage63;
-(id)wrappedOutputImage64;
-(id)wrappedOutputImage65;
-(id)wrappedOutputImage66;
-(id)wrappedOutputImage67;
-(id)wrappedOutputImage68;
-(id)wrappedOutputImage69;
-(id)wrappedOutputImage70;
-(id)wrappedOutputImage71;
-(id)wrappedOutputImage72;
-(id)wrappedOutputImage73;
-(id)wrappedOutputImage74;
-(id)wrappedOutputImage75;
-(id)wrappedOutputImage76;
-(id)wrappedOutputImage77;
-(id)wrappedOutputImage78;
-(id)wrappedOutputImage79;
-(id)wrappedOutputImage80;
-(id)wrappedOutputImage81;
-(id)wrappedOutputImage82;
-(id)wrappedOutputImage83;
-(id)wrappedOutputImage84;
-(id)wrappedOutputImage85;
-(id)wrappedOutputImage86;
-(id)wrappedOutputImage87;
-(id)wrappedOutputImage88;
-(id)wrappedOutputImage89;
-(id)wrappedOutputImage90;
-(id)wrappedOutputImage91;
-(id)wrappedOutputImage92;
-(id)wrappedOutputImage93;
-(id)wrappedOutputImage94;
-(id)wrappedOutputImage95;
-(id)wrappedOutputImage96;
-(id)wrappedOutputImage97;
-(id)wrappedOutputImage98;
-(id)wrappedOutputImage99;
-(int)compatibilityVersion;
-(void)_crashed_when_dealloc_called_setValue_nil_forKey_probably_because_the_subclass_already_released_it:(id)arg0 className:(char *)arg1 overridesDealloc:(BOOL)arg2 ;
-(void)_prepend:(id)arg0 ;
-(void)_prependSingleFilter:(id)arg0 ;
-(void)dealloc;
-(void)encodeWithCoder:(id)arg0 ;
-(void)finalize;
-(void)setDefaults;
-(void)setIdentity;
-(void)setOption:(id)arg0 forKey:(id)arg1 ;
-(void)setUserInfo:(id)arg0 ;
-(void)setValue:(id)arg0 forUndefinedKey:(id)arg1 ;


@end


#endif