// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef TSWPSTORAGE_H
#define TSWPSTORAGE_H

@class TSPObject, NSMutableString, NSArray, NSString, TSDInfoGeometry, TSPObject<TSDOwningAttachment>, TSDDrawableInfo, NSSet, TSSStylesheet;
@protocol TSDDrawableContainerInfo, TSKPencilAnnotationContainer, TSKTransformableObject, TSWPStyleProvider, TSWPStorageParent, TSSStyleClient, TSWPTextSource, TSDContainerInfo><TSWPStorageParent;


#import "TSWPStorageBroadcaster.h"
#import "TSWPDocumentRoot.h"
#import "TSWPCharacterStyle.h"

@interface TSWPStorage : TSPObject <TSDDrawableContainerInfo, TSKPencilAnnotationContainer, TSKTransformableObject, TSWPStyleProvider, TSWPStorageParent, TSSStyleClient, TSWPTextSource>

 {
    NSMutableString *_string;
    ? _attributesTable;
    TSWPStorageBroadcaster *_broadcaster;
    NSUInteger _charIndexForWord;
    _NSRange _wordAtCharIndex;
    BOOL _disallowElementKinds;
    BOOL _disallowSmartFieldKinds;
    BOOL _WPKind;
    BOOL _writingDirectionCache;
    BOOL _includePreviousWord;
    BOOL _includeHyphenation;
    BOOL _dolcSuppressed;
    BOOL _wasPreviouslyRemovedFromDocument;
    NSUInteger _wordAtCharIndexChangeCount;
    atomic<unsigned long> _changeCount;
}


@property (readonly, nonatomic, getter=isAnchoredToText) BOOL anchoredToText;
@property (readonly, nonatomic, getter=isAttachedToBodyText) BOOL attachedToBodyText;
@property (readonly, nonatomic) BOOL autoListRecognition;
@property (readonly, nonatomic) BOOL autoListTermination;
@property (readonly, nonatomic) TSWPStorageBroadcaster *broadcaster;
@property (readonly, nonatomic) NSUInteger changeCount;
@property (readonly, copy, nonatomic) NSArray *childInfos;
@property (readonly, nonatomic) BOOL containsOnlyInlineDrawableAttachments;
@property (readonly, nonatomic) NSInteger contentWritingDirection;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) *TSWPChangeAttributeArray deletionChangesTable;
@property (readonly, copy) NSString *description;
@property (weak, nonatomic) TSWPDocumentRoot *documentRoot; // ivar: _documentRoot
@property (readonly, nonatomic, getter=isFloatingAboveText) BOOL floatingAboveText;
@property (copy, nonatomic) TSDInfoGeometry *geometry;
@property (readonly, nonatomic) BOOL hasAnyCommentsRequiring2_2;
@property (readonly, nonatomic) BOOL hasComments;
@property (readonly, nonatomic) BOOL hasTrackedChanges;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic) TSWPCharacterStyle *hyperlinkStyle;
@property (nonatomic) BOOL ignoreContentsChangedNotifications; // ivar: _ignoreContentsChangedNotifications
@property (readonly, nonatomic, getter=isInlineWithText) BOOL inlineWithText;
@property (readonly, nonatomic, getter=isInlineWithTextWithWrap) BOOL inlineWithTextWithWrap;
@property (readonly, nonatomic) *TSWPChangeAttributeArray insertionChangesTable;
@property (nonatomic) BOOL isInInit; // ivar: _isInInit
@property (readonly, nonatomic) BOOL isMaster;
@property (readonly, nonatomic) BOOL isTopmostContainerInfo;
@property (nonatomic) BOOL matchesObjectPlaceholderGeometry;
@property (readonly, nonatomic) NSInteger nestedTextboxDepth;
@property (nonatomic) TSPObject<TSDOwningAttachment> *owningAttachment; // ivar: _owningAttachment
@property (readonly, nonatomic) TSPObject<TSDOwningAttachment> *owningAttachmentNoRecurse;
@property (readonly, nonatomic) TSDDrawableInfo *parentDrawable;
@property (weak, nonatomic) NSObject<TSDContainerInfo><TSWPStorageParent> *parentInfo; // ivar: _parentInfo
@property (readonly, nonatomic) BOOL preventsChangeTracking;
@property (readonly, nonatomic) BOOL preventsComments;
@property (readonly, nonatomic) NSSet *referencedStyles;
@property (readonly, nonatomic) BOOL storageChangesInvalidateWrap;
@property (retain, nonatomic) TSSStylesheet *stylesheet;
@property (readonly, nonatomic) TSSStylesheet *stylesheet; // ivar: _stylesheet
@property (readonly) Class superclass;
@property (readonly, nonatomic) BOOL supportsBoldItalicUnderlineShortcuts;
@property (readonly, nonatomic) BOOL supportsChangeTracking;
@property (readonly, nonatomic) BOOL supportsDropCapsInChildStorages;
@property (readonly, nonatomic) BOOL supportsMultipleColumns;
@property (readonly, nonatomic) BOOL supportsParentRotation;
@property (readonly, nonatomic) BOOL supportsVerticalTextLayoutInChildStorages;
@property (readonly, nonatomic) BOOL textIsLinked;


+(BOOL)allowsElementKind:(unsigned int)arg0 forStorageKind:(unsigned char)arg1 ;
+(BOOL)allowsSmartFieldKind:(unsigned short)arg0 forStorageKind:(unsigned char)arg1 ;
+(BOOL)needsObjectUUID;
+(BOOL)shouldInvalidateForStylePropertyChangeSet:(id)arg0 ;
+(Class)classForUnarchiver:(id)arg0 ;
+(Class)pStringClassForWPKind:(unsigned char)arg0 ;
+(id)filterMarkAttributes:(id)arg0 ;
+(id)filterText:(id)arg0 ;
+(id)filterText:(id)arg0 removingAttachments:(BOOL)arg1 ;
+(id)filterText:(id)arg0 removingAttachments:(BOOL)arg1 removingControlCharacters:(BOOL)arg2 ;
+(struct TSWPAttributeArray *)createAttributeArrayForKind:(NSUInteger)arg0 actionState:(*void)arg1 ;
+(struct TSWPAttributeArray *)createEmptyAttributeArrayForKind:(NSUInteger)arg0 ;
+(unsigned int)disallowedElementKindsForStorageKind:(unsigned char)arg0 ;
+(void)initialize;
+(void)nonUndoableRemoveUnsupportedHyperlinksInInfos:(id)arg0 ;
+(void)nonUndoableRemoveUnsupportedHyperlinksInInfos:(id)arg0 forCrossDocumentPaste:(BOOL)arg1 ;
+(void)resetAllTextAttributeUUIDStringsInInfo:(id)arg0 ;
+(void)resetAllTextAttributeUUIDStringsInInfos:(id)arg0 ;
+(void)resetDisallowedElementKinds;
+(void)resetDisallowedSmartFieldKinds;
+(void)setDisallowedElementKinds:(unsigned int)arg0 forStorageKind:(unsigned char)arg1 ;
+(void)setDisallowedSmartFieldKinds:(unsigned int)arg0 forStorageKind:(unsigned char)arg1 ;
-(*void)cfRetainedNonUndoableFastCopyAttributeRecord:(struct TSWPAttributeRecord *)arg0 shouldAddRecord:(*BOOL)arg1 attributeArrayKind:(NSUInteger)arg2 atIndex:(NSUInteger)arg3 sourceStorage:(id)arg4 objectContext:(id)arg5 flags:(unsigned int)arg6 actionState:(*void)arg7 ;
-(BOOL)WPKindSupportsDropCaps;
-(BOOL)adjustRangesByDelta:(NSInteger)arg0 startingAt:(NSUInteger)arg1 ;
-(BOOL)allowsElementKind:(unsigned int)arg0 ;
-(BOOL)allowsElementKind:(unsigned int)arg0 nestingDepth:(NSInteger)arg1 ;
-(BOOL)allowsSmartFieldKind:(unsigned short)arg0 ;
-(BOOL)allowsTypographicalFractions;
-(BOOL)anchoredDrawableAttachmentCharacterAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)canAcceptAttachmentForDrawableInfo:(id)arg0 ;
-(BOOL)canAcceptDrawableAttachments;
-(BOOL)canBeAnnotatedWithPencil;
-(BOOL)canBeStoredInAStringValueCell;
-(BOOL)canPasteAsPlainText;
-(BOOL)canPasteAsPlainTextWithUniformParagraphs;
-(BOOL)canTransferAttributesForInitialization:(NSUInteger)arg0 withFlags:(unsigned int)arg1 ;
-(BOOL)childrenCanBeAnnotatedWithPencil;
-(BOOL)hasAttachmentsRequiring4_1InRange:(struct _NSRange )arg0 ;
-(BOOL)hasColumnBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasColumnStyleForParagraphBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasData:(struct TSWPParagraphData )arg0 attribueArrayKind:(NSUInteger)arg1 range:(struct _NSRange )arg2 ;
-(BOOL)hasDeletedTextAtCharIndex:(NSUInteger)arg0 range:(struct _NSRange *)arg1 ;
-(BOOL)hasDeletionInRange:(struct _NSRange )arg0 ;
-(BOOL)hasDrawableAttachmentOfClass:(Class)arg0 ;
-(BOOL)hasEmptyListAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasEmptyParagraphFillOrBordersAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasHiddenTextAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasHiddenTextAtCharIndex:(NSUInteger)arg0 range:(struct _NSRange *)arg1 ;
-(BOOL)hasObject:(id)arg0 attribueArrayKind:(NSUInteger)arg1 range:(struct _NSRange )arg2 ;
-(BOOL)hasObject:(id)arg0 attribueArrayKind:(NSUInteger)arg1 range:(struct _NSRange )arg2 findUsingExactRangeLocation:(BOOL)arg3 ;
-(BOOL)hasPartitionableAttachmentAtStartOfTextRange:(struct _NSRange )arg0 ;
-(BOOL)hasSectionForParagraphBreakAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasSmartFields;
-(BOOL)hasSmartFieldsInRange:(struct _NSRange )arg0 ;
-(BOOL)hasUserGeneratedVisibleText;
-(BOOL)hasVisibleContent;
-(BOOL)hasVisibleTextAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)hasVisibleTextOnlyContent;
-(BOOL)hasVisibleTextOnlyContentInRange:(struct _NSRange )arg0 ;
-(BOOL)highlightsAllowed;
-(BOOL)isAllWhitespaceInRange:(struct _NSRange )arg0 ;
-(BOOL)isAllowedToAddCaptionToChildInfo:(id)arg0 ;
-(BOOL)isCharRangeEntirelyDeleted:(struct _NSRange )arg0 ;
-(BOOL)isCharRangeEntirelyHidden:(struct _NSRange )arg0 ;
-(BOOL)isCharRangePartiallyDeleted:(struct _NSRange )arg0 ;
-(BOOL)isDOLCSuppressed;
-(BOOL)isEmptyParagraphRange:(struct _NSRange )arg0 ignoreAttachmentCharacters:(BOOL)arg1 outRange:(struct _NSRange *)arg2 ;
-(BOOL)isEmptyParagraphSelection:(id)arg0 ignoreAttachmentCharacters:(BOOL)arg1 outRange:(struct _NSRange *)arg2 ;
-(BOOL)isObjectValid:(id)arg0 forStyleKind:(int)arg1 ;
-(BOOL)isSelectable;
-(BOOL)isSingleAnchoredDrawableAttachmentForSelection:(id)arg0 ;
-(BOOL)isThemeContent;
-(BOOL)isWholeParagraphsForRange:(struct _NSRange )arg0 ignoreAttachmentCharacters:(BOOL)arg1 requireParagraphBreakSelected:(BOOL)arg2 ;
-(BOOL)isWritingDirectionRightToLeftForListAtParIndex:(NSUInteger)arg0 ;
-(BOOL)isWritingDirectionRightToLeftForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)isWritingDirectionRightToLeftForParagraphAtParIndex:(NSUInteger)arg0 ;
-(BOOL)pAllowsAttachment:(id)arg0 withNestingDepth:(NSInteger)arg1 ;
-(BOOL)p_canTransferBookmark:(id)arg0 ;
-(BOOL)p_hasDeletedTextAtCharIndex:(NSUInteger)arg0 requireHidden:(BOOL)arg1 range:(struct _NSRange *)arg2 ;
-(BOOL)p_hasGoodAttributesForPlainTextPaste;
-(BOOL)p_hasVisibleTextInRange:(struct _NSRange )arg0 graphicalAttachmentsIncluded:(BOOL)arg1 ;
-(BOOL)p_isRotatedInAnyParent;
-(BOOL)p_nestedInHeaderFooter;
-(BOOL)p_passesExtraTablesChecksForStoringInAStringValueCell;
-(BOOL)p_shouldAcceptChangesForRange:(struct _NSRange )arg0 removeDeletedText:(*BOOL)arg1 ;
-(BOOL)p_shouldInsertionSplitChange:(id)arg0 changeSession:(id)arg1 ;
-(BOOL)paragraphHasListLabelAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)phoneticsExistOnRange:(struct _NSRange )arg0 ;
-(BOOL)selectionContainsExclusivelyEmptyParagraphs:(id)arg0 ignoreAttachmentCharacters:(BOOL)arg1 ;
-(BOOL)setDOLCSuppressed:(BOOL)arg0 ;
-(BOOL)supportsBookmarks;
-(BOOL)supportsColumnStyles;
-(BOOL)supportsDropCaps;
-(BOOL)supportsListStyles;
-(BOOL)supportsPageBreaks;
-(BOOL)supportsSectionCopying;
-(BOOL)supportsSections;
-(BOOL)textIsVerticalAtCharIndex:(NSUInteger)arg0 ;
-(BOOL)validate:(NSUInteger)arg0 ;
-(BOOL)wasPreviouslyRemovedFromDocument;
-(CGFloat)highestScaleFactorForRenderingDrawableInfo:(id)arg0 ;
-(Class)layoutClass;
-(Class)layoutClassForInstructionalText;
-(Class)repClass;
-(NSInteger)hyphenationLocationBeforeIndex:(NSInteger)arg0 inRange:(struct _NSRange )arg1 locale:(id)arg2 hyphenChar:(*unsigned int)arg3 ;
-(NSInteger)pFlipSpecialCharacterForObject:(id)arg0 range:(struct _NSRange )arg1 insertLength:(NSUInteger)arg2 outChangeRange:(struct _NSRange *)arg3 attributeArrayKind:(NSUInteger)arg4 actionState:(*void)arg5 ;
-(NSUInteger)attachmentCount;
-(NSUInteger)attachmentIndexAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)attachmentIndexForInsertionAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)attributeIndexForCharacterIndex:(NSUInteger)arg0 attributeKind:(NSUInteger)arg1 ;
-(NSUInteger)autoNumberFootnoteCountForRange:(struct _NSRange )arg0 ;
-(NSUInteger)charIndexBeforeAnyAnchoredAttachmentsAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)charIndexForParagraphAtIndex:(NSUInteger)arg0 ;
-(NSUInteger)charIndexMappedFromStorage:(NSUInteger)arg0 ;
-(NSUInteger)charIndexMappedToStorage:(NSUInteger)arg0 ;
-(NSUInteger)charIndexRemappedFromStorage:(NSUInteger)arg0 ;
-(NSUInteger)characterCount;
-(NSUInteger)characterStyleAttributeCount;
-(NSUInteger)columnStyleCount;
-(NSUInteger)countTrackChangesInSelection:(id)arg0 ;
-(NSUInteger)dropCapStyleCount;
-(NSUInteger)emptyParagraphCount:(struct _NSRange )arg0 ;
-(NSUInteger)findCharIndexForAttachment:(id)arg0 ;
-(NSUInteger)findCharIndexForAttachment:(id)arg0 withHintIndex:(*NSUInteger)arg1 ;
-(NSUInteger)findCharIndexForFootnoteAttachment:(id)arg0 ;
-(NSUInteger)findCharIndexForFootnoteAttachment:(id)arg0 withHintIndex:(*NSUInteger)arg1 ;
-(NSUInteger)findCharacterIndexForContainedInfo:(id)arg0 ;
-(NSUInteger)findNextParagraphStyleChange:(NSUInteger)arg0 maxCharIndex:(NSUInteger)arg1 ;
-(NSUInteger)footnoteCount;
-(NSUInteger)footnoteIndexForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)footnoteIndexForFootnote:(id)arg0 ;
-(NSUInteger)footnoteIndexForFootnoteStorage:(id)arg0 ;
-(NSUInteger)indexAfterLastVisibleCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)indexOfFirstNonDeletedCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)indexOfFirstVisibleCharInRange:(struct _NSRange )arg0 ;
-(NSUInteger)length;
-(NSUInteger)listEndAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)listNumberForParagraphEnumerator:(struct TSWPParagraphEnumerator *)arg0 numberingData:(struct ? *)arg1 ;
-(NSUInteger)listNumberForParagraphIndex:(NSUInteger)arg0 numberingData:(struct ? *)arg1 ;
-(NSUInteger)listStartAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)listStartAtParIndex:(NSUInteger)arg0 ;
-(NSUInteger)listStyleCount;
-(NSUInteger)moveByLineRange:(struct _NSRange )arg0 up:(BOOL)arg1 ;
-(NSUInteger)nextCharacterIndex:(NSUInteger)arg0 ;
-(NSUInteger)pFirstParIndexInListAtParIndex:(NSUInteger)arg0 ;
-(NSUInteger)p_indexOfFirstNonDeletedCharInRange:(struct _NSRange )arg0 requireVisible:(BOOL)arg1 ;
-(NSUInteger)paragraphCount;
-(NSUInteger)paragraphEndAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphIndexAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphLevelAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphLevelAtParIndex:(NSUInteger)arg0 ;
-(NSUInteger)paragraphStartAtCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)previousCharacterIndex:(NSUInteger)arg0 ;
-(NSUInteger)previousDecomposedCharacterIndex:(NSUInteger)arg0 ;
-(NSUInteger)sectionCount;
-(NSUInteger)sectionIndexForCharIndex:(NSUInteger)arg0 ;
-(NSUInteger)sectionIndexForSection:(id)arg0 ;
-(NSUInteger)selectedParagraphBreakCount:(struct _NSRange )arg0 ;
-(NSUInteger)storageLength;
-(NSUInteger)wordCount;
-(id)attachmentAtAttachmentIndex:(NSUInteger)arg0 outCharIndex:(*NSUInteger)arg1 ;
-(id)attachmentAtCharIndex:(NSUInteger)arg0 ;
-(id)attachmentOrFootnoteAtCharIndex:(NSUInteger)arg0 ;
-(id)attachments;
-(id)bestCharacterLanguageForTextRange:(struct _NSRange )arg0 ;
-(id)changeAtCharIndex:(NSUInteger)arg0 attributeKind:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)changeAtCharIndex:(NSUInteger)arg0 outRange:(struct _NSRange *)arg1 ;
-(id)changeDetailsAtCharIndex:(NSUInteger)arg0 outRange:(struct _NSRange *)arg1 ;
-(id)changeDetailsForChange:(id)arg0 withRange:(struct _NSRange )arg1 ;
-(id)characterStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)characterStyleAtCharIndex:(NSUInteger)arg0 left:(BOOL)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)characterStyleForDeletedRange:(struct _NSRange )arg0 ;
-(id)characterStyleForDropCapAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)childEnumerator;
-(id)columnStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)columnStyleAtColumnStyleIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)copyWithContext:(id)arg0 ;
-(id)deletedRangesInRange:(struct _NSRange )arg0 ;
-(id)dictationAndAutocorrectionKeyAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)dropCapCharIndexesInRange:(struct _NSRange )arg0 ;
-(id)dropCapStyleAtCharIndex:(NSUInteger)arg0 ;
-(id)dropCapStyleAtParIndex:(NSUInteger)arg0 ;
-(id)dropCapStyleIfMatchingSelectionExactly:(id)arg0 ;
-(id)editableAnnotationForInsertionPointSelection:(id)arg0 includeComments:(BOOL)arg1 withOutRange:(struct _NSRange *)arg2 selectionIsOnEdge:(*BOOL)arg3 ;
-(id)editableSmartFieldAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)extendSelectionForTopicChildren:(id)arg0 ;
-(id)extendSelectionToIncludeSmartFields:(id)arg0 ;
-(id)firstHighlightForSelectionRange:(struct _NSRange )arg0 outRange:(struct _NSRange *)arg1 ;
-(id)firstHighlightForSelectionRange:(struct _NSRange )arg0 outRange:(struct _NSRange *)arg1 requireComment:(BOOL)arg2 ;
-(id)fontNameAtCharIndex:(NSUInteger)arg0 size:(*CGFloat)arg1 effectiveRange:(struct _NSRange *)arg2 styleProvider:(id)arg3 ;
-(id)footnoteAtFootnoteIndex:(NSUInteger)arg0 outCharIndex:(*NSUInteger)arg1 ;
-(id)footnoteMarkAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteReferenceAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteReferenceAttachmentOrFootnoteMarkAttachmentAtCharIndex:(NSUInteger)arg0 ;
-(id)footnoteStorages;
-(id)glyphVariantDataAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)hiddenRangesInRange:(struct _NSRange )arg0 ;
-(id)highlightSelectionForSelection:(id)arg0 ;
-(id)highlightsForSelectionRange:(struct _NSRange )arg0 requireComment:(BOOL)arg1 ;
-(id)indexesSetForBIUProperties:(id)arg0 ;
-(id)indexesSetForBIUProperties:(id)arg0 selection:(id)arg1 insertionStyle:(id)arg2 ;
-(id)infoForSelectionPath:(id)arg0 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 kind:(unsigned char)arg2 stylesheet:(id)arg3 paragraphStyle:(id)arg4 listStyle:(id)arg5 section:(id)arg6 columnStyle:(id)arg7 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 kind:(unsigned char)arg2 stylesheet:(id)arg3 paragraphStyle:(id)arg4 listStyle:(id)arg5 section:(id)arg6 columnStyle:(id)arg7 paragraphDirection:(int)arg8 ;
-(id)initWithContext:(id)arg0 string:(id)arg1 stylesheet:(id)arg2 kind:(unsigned char)arg3 ;
-(id)languageAtParIndex:(NSUInteger)arg0 useStringTokenizer:(BOOL)arg1 useDocumentLanguage:(BOOL)arg2 ;
-(id)languageEntryAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)languageForTextRange:(struct _NSRange )arg0 useStringTokenizer:(BOOL)arg1 useDocumentLanguage:(BOOL)arg2 ;
-(id)listStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)listStyleAtParIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 context:(id)arg1 flags:(unsigned int)arg2 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 context:(id)arg1 flags:(unsigned int)arg2 kind:(unsigned char)arg3 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 storageContext:(id)arg1 objectsContext:(id)arg2 flags:(unsigned int)arg3 ;
-(id)newSubstorageWithRange:(struct _NSRange )arg0 storageContext:(id)arg1 objectsContext:(id)arg2 flags:(unsigned int)arg3 kind:(unsigned char)arg4 ;
-(id)nextChangeFromCharIndex:(NSUInteger)arg0 afterChange:(id)arg1 changeRange:(struct _NSRange *)arg2 ;
-(id)objectAtLocationAtExactCharIndex:(NSUInteger)arg0 forAttributeKind:(NSUInteger)arg1 ;
-(id)objectAtLocationPriorToMappedCharIndex:(NSUInteger)arg0 forAttributeKind:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)objectUUIDPath;
-(id)overlappingFieldsAtAttributeIndex:(NSUInteger)arg0 attributeKind:(NSUInteger)arg1 ;
-(id)pDefaultSectionForContext:(id)arg0 ;
-(id)pFindValidInsertionCharStyleFromCharIndex:(NSUInteger)arg0 ;
-(id)pFlipStringForObject:(id)arg0 insertLength:(NSUInteger)arg1 attributeArrayKind:(NSUInteger)arg2 ;
-(id)pOverrideObjectBeforeReplacingCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 withInsertionBehavior:(NSInteger)arg2 ;
-(id)pOverrideObjectBeforeReplacingCharactersInSelection:(id)arg0 withString:(id)arg1 ;
-(id)p_highlightsForSelectionRange:(struct _NSRange )arg0 outRange:(struct _NSRange *)arg1 requireComment:(BOOL)arg2 stopOnFirst:(BOOL)arg3 ;
-(id)p_lazyBroadcaster;
-(id)p_replacementsForSelection:(id)arg0 withString:(id)arg1 replaceTextData:(id)arg2 changeSession:(id)arg3 shouldTrackDeletions:(BOOL)arg4 ;
-(id)p_stringWithAttachmentCharacterSubstitutedWithCharacter:(id)arg0 ;
-(id)p_trackedChangesIntersectingRange:(struct _NSRange )arg0 ;
-(id)p_undeletedCharIndexesInRange:(struct _NSRange )arg0 ;
-(id)paragraphStyleAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)paragraphStyleAtParIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)pencilAnnotationsInContainedTextRange:(struct _NSRange )arg0 ;
-(id)placeholderSmartFieldAtRange:(struct _NSRange )arg0 ;
-(id)placeholderSmartFieldsIntersectingRange:(struct _NSRange )arg0 ;
-(id)previousChangeFromCharIndex:(NSUInteger)arg0 beforeChange:(id)arg1 changeRange:(struct _NSRange *)arg2 ;
-(id)referencedStylesOfClass:(Class)arg0 ;
-(id)relocateNonSelectedAnchorsInSelection:(id)arg0 undoTransaction:(*void)arg1 ;
-(id)sectionAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)sectionAtSectionIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(id)smartFieldAtCharIndex:(NSUInteger)arg0 attributeKind:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)smartFieldsWithAttributeKind:(NSUInteger)arg0 intersectingRange:(struct _NSRange )arg1 ;
-(id)smartFieldsWithAttributeKind:(NSUInteger)arg0 intersectingRange:(struct _NSRange )arg1 passingTest:(id)arg2 ;
-(id)smartFieldsWithAttributeKind:(NSUInteger)arg0 withClass:(Class)arg1 intersectingRange:(struct _NSRange )arg2 ;
-(id)snapshotRubyStateInRange:(struct _NSRange )arg0 ;
-(id)storageByApplyingCustomFormat:(id)arg0 ;
-(id)string;
-(id)stringForStatisticsInRange:(struct _NSRange )arg0 ;
-(id)stringValue;
-(id)stringWithAttachmentCharacterRemoved;
-(id)stringWithAttachmentCharacterSubstitution;
-(id)substringWithRange:(struct _NSRange )arg0 ;
-(id)substringWithSelection:(id)arg0 ;
-(id)textPropertiesForEquation:(id)arg0 basedOnProperties:(id)arg1 ;
-(id)textSourceForLayoutInRange:(struct _NSRange )arg0 ;
-(id)trackedChangesIntersectingSelection:(id)arg0 ;
-(id)valueForProperty:(int)arg0 atCharIndex:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 ;
-(id)visibleRangesInRange:(struct _NSRange )arg0 ;
-(int)compareAttributeArray1:(struct TSWPAttributeArray *)arg0 array2:(struct TSWPAttributeArray *)arg1 range1:(struct _NSRange )arg2 range2:(struct _NSRange )arg3 attributeIndex1:(NSUInteger)arg4 attributeIndex2:(NSUInteger)arg5 objectComparisonBlock:(id)arg6 ;
-(int)compareAttributeArray:(struct TSWPAttributeArray *)arg0 range:(struct _NSRange )arg1 otherStorage:(id)arg2 otherRange:(struct _NSRange )arg3 objectComparisonBlock:(id)arg4 ;
-(int)compareBreakingTablesWithStorage:(id)arg0 ;
-(int)compareRange:(struct _NSRange )arg0 otherStorage:(id)arg1 otherRange:(struct _NSRange )arg2 options:(NSUInteger)arg3 ;
-(int)compareRange:(struct _NSRange )arg0 otherStorage:(id)arg1 otherRange:(struct _NSRange )arg2 options:(NSUInteger)arg3 objectComparisonBlock:(id)arg4 ;
-(int)p_writingDirectionFromBidiAttributesTableForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(int)writingDirectionForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(int)writingDirectionForParagraphAtCharIndex:(NSUInteger)arg0 effectiveRange:(struct _NSRange *)arg1 ;
-(int)writingDirectionForParagraphAtParIndex:(NSUInteger)arg0 ;
-(struct TSWPAttributeArray *)attributeArrayForKind:(NSUInteger)arg0 ;
-(struct TSWPAttributeArray *)attributeArrayForKind:(NSUInteger)arg0 withCreate:(BOOL)arg1 ;
-(struct TSWPAttributeArray *)attributeArrayForKind:(NSUInteger)arg0 withCreate:(BOOL)arg1 actionState:(*void)arg2 ;
-(struct TSWPAttributeArray *)attributeArrayForKind:(NSUInteger)arg0 withCreate:(BOOL)arg1 fromUndo:(BOOL)arg2 actionState:(*void)arg3 ;
-(struct TSWPParagraphAttributeArray *)paragraphAttributeArrayForKind:(NSUInteger)arg0 withCreate:(BOOL)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorAtCharIndex:(NSUInteger)arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorAtParIndex:(NSUInteger)arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorForCharRange:(struct _NSRange )arg0 styleProvider:(id)arg1 ;
-(struct TSWPParagraphEnumerator )paragraphEnumeratorForCharRange:(struct _NSRange )arg0 styleProvider:(id)arg1 requireHidden:(BOOL)arg2 ;
-(struct _NSRange )annotationRangeForSelection:(id)arg0 ;
-(struct _NSRange )appendString:(id)arg0 undoTransaction:(*void)arg1 ;
-(struct _NSRange )attachmentIndexRangeForTextRange:(struct _NSRange )arg0 ;
-(struct _NSRange )attachmentRangeForCharIndex:(NSUInteger)arg0 forwards:(BOOL)arg1 ;
-(struct _NSRange )attachmentRangeForCharIndex:(NSUInteger)arg0 forwards:(BOOL)arg1 attributeKind:(NSUInteger)arg2 ;
-(struct _NSRange )attributeRangeForOverlappingField:(id)arg0 atAttributeIndex:(NSUInteger)arg1 attributeKind:(NSUInteger)arg2 ;
-(struct _NSRange )attributeRangeForOverlappingField:(id)arg0 attributeKind:(NSUInteger)arg1 ;
-(struct _NSRange )charRangeForAttributeRange:(struct _NSRange )arg0 attributeKind:(NSUInteger)arg1 ;
-(struct _NSRange )charRangeMappedFromStorage:(struct _NSRange )arg0 ;
-(struct _NSRange )charRangeMappedToStorage:(struct _NSRange )arg0 ;
-(struct _NSRange )charRangeRemappedFromStorage:(struct _NSRange )arg0 ;
-(struct _NSRange )footnoteRangeForTextRange:(struct _NSRange )arg0 ;
-(struct _NSRange )insertAttachmentOrFootnote:(id)arg0 range:(struct _NSRange )arg1 ;
-(struct _NSRange )insertAttachmentOrFootnote:(id)arg0 range:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 changeSession:(id)arg4 ;
-(struct _NSRange )insertAttachmentOrFootnote:(id)arg0 range:(struct _NSRange )arg1 placementIndex:(int)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 changeSession:(id)arg5 ;
-(struct _NSRange )insertSection:(id)arg0 atCharIndex:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 changeSession:(id)arg4 ;
-(struct _NSRange )insertSectionBreakAtCharIndex:(NSUInteger)arg0 replaceParagraphBreak:(BOOL)arg1 sectionToInsert:(id)arg2 changeSession:(id)arg3 dolcContext:(id)arg4 undoTransaction:(*void)arg5 ;
-(struct _NSRange )insertSpecialCharacter:(unsigned short)arg0 object:(id)arg1 kind:(NSUInteger)arg2 range:(struct _NSRange )arg3 dolcContext:(id)arg4 undoTransaction:(*void)arg5 changeSession:(id)arg6 ;
-(struct _NSRange )insertSpecialCharacter:(unsigned short)arg0 object:(id)arg1 kind:(NSUInteger)arg2 range:(struct _NSRange )arg3 placementIndex:(int)arg4 dolcContext:(id)arg5 undoTransaction:(*void)arg6 changeSession:(id)arg7 ;
-(struct _NSRange )moveCharactersInRange:(struct _NSRange )arg0 toLocation:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(struct _NSRange )nextWordFromIndex:(NSUInteger)arg0 forward:(BOOL)arg1 ;
-(struct _NSRange )p_RelocateNonSelectedAnchorsInRange:(struct _NSRange )arg0 selectionInfos:(id)arg1 undoTransaction:(*void)arg2 ;
-(struct _NSRange )p_extendRangeToIncludeSmartFields:(struct _NSRange )arg0 ;
-(struct _NSRange )p_extendRangeToIncludeSmartFields:(struct _NSRange )arg0 ofKind:(NSUInteger)arg1 ;
-(struct _NSRange )p_rangeForOverlappingField:(id)arg0 attributeKind:(NSUInteger)arg1 ;
-(struct _NSRange )p_rangeForSelectionAtCharIndex:(NSUInteger)arg0 caretIndex:(NSUInteger)arg1 handleNextWordWhitespace:(BOOL)arg2 ;
-(struct _NSRange )p_rangeWithNonVisibleAttachmentsTrimmedForRange:(struct _NSRange )arg0 ;
-(struct _NSRange )p_replaceCharactersInLogicalSelection:(id)arg0 withString:(id)arg1 withFlags:(unsigned int)arg2 replaceTextData:(id)arg3 changeSession:(id)arg4 undoTransaction:(*void)arg5 outInsertedRange:(struct _NSRange *)arg6 ;
-(struct _NSRange )paragraphIndexRangeForCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )paragraphIndexRangeIncludingFinalEmptyParagraphForCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )range;
-(struct _NSRange )rangeByExpandingToIncludePartialWords:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToLineBreak:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToWhitespace:(struct _NSRange )arg0 ;
-(struct _NSRange )rangeByExtendingRangeToWhitespace:(struct _NSRange )arg0 skipVisibleDeleted:(BOOL)arg1 ;
-(struct _NSRange )rangeByTrimmingRange:(struct _NSRange )arg0 withBlock:(id)arg1 ;
-(struct _NSRange )rangeForAnnotation:(id)arg0 ;
-(struct _NSRange )rangeForChange:(id)arg0 ;
-(struct _NSRange )rangeForHighlight:(id)arg0 ;
-(struct _NSRange )rangeForPencilAnnotation:(id)arg0 ;
-(struct _NSRange )rangeForSelectionAtCharIndex:(NSUInteger)arg0 caretIndex:(NSUInteger)arg1 ;
-(struct _NSRange )rangeForSelectionAtCharIndex:(NSUInteger)arg0 includePreviousWord:(BOOL)arg1 ;
-(struct _NSRange )rangeForSelectionWithInsertionSelection:(id)arg0 ;
-(struct _NSRange )rangeOfAnnotationWithOptions:(NSUInteger)arg0 range:(struct _NSRange )arg1 ;
-(struct _NSRange )rangeOfDropCapAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )rangeOfDropCapAtCharIndex:(NSUInteger)arg0 actualCharacterCount:(*NSUInteger)arg1 ;
-(struct _NSRange )rangeOfParagraphBreakingCharacter:(unsigned short)arg0 backwards:(BOOL)arg1 range:(struct _NSRange )arg2 ;
-(struct _NSRange )rangeOfString:(id)arg0 searchOptions:(NSUInteger)arg1 range:(struct _NSRange )arg2 ;
-(struct _NSRange )rangeOfString:(id)arg0 searchOptions:(NSUInteger)arg1 updatingSearchRange:(struct _NSRange *)arg2 ;
-(struct _NSRange )replaceAllOccurrencesOfObject:(id)arg0 withObject:(id)arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(struct _NSRange )replaceAllOccurrencesOfStyle:(id)arg0 withStyle:(id)arg1 undoTransaction:(*void)arg2 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withStorage:(id)arg1 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withStorage:(id)arg1 usePasteRules:(BOOL)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 notifyObservers:(BOOL)arg2 undoTransaction:(*void)arg3 ;
-(struct _NSRange )replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 undoTransaction:(*void)arg2 ;
-(struct _NSRange )replaceCharactersInSelection:(id)arg0 withStorage:(id)arg1 usePasteRules:(BOOL)arg2 srcStylesAmbiguous:(BOOL)arg3 dolcContext:(id)arg4 changeSession:(id)arg5 undoTransaction:(*void)arg6 ;
-(struct _NSRange )replaceCharactersInSelection:(id)arg0 withString:(id)arg1 withFlags:(unsigned int)arg2 replaceTextData:(id)arg3 changeSession:(id)arg4 undoTransaction:(*void)arg5 outInsertedRange:(struct _NSRange *)arg6 ;
-(struct _NSRange )replaceSectionAtSectionIndex:(NSUInteger)arg0 withSection:(id)arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(struct _NSRange )scanLeftForWordAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForListAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForListsInCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeForParagraphAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForParagraphAtIndex:(NSUInteger)arg0 ;
-(struct _NSRange )textRangeForParagraphIndexRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeForParagraphsInCharRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeForSectionRange:(struct _NSRange )arg0 ;
-(struct _NSRange )textRangeIgnoringTrailingLineBreaksForParagraphAtIndex:(NSUInteger)arg0 ;
-(struct _NSRange )whiteSpaceRangeAtCharIndex:(NSUInteger)arg0 ;
-(struct _NSRange )whiteSpaceRangeAtCharIndex:(NSUInteger)arg0 includingBreaks:(BOOL)arg1 ;
-(struct _NSRange )wordAtCharIndex:(NSUInteger)arg0 includePreviousWord:(BOOL)arg1 ;
-(struct _NSRange )wordAtCharIndex:(NSUInteger)arg0 includePreviousWord:(BOOL)arg1 includeHyphenation:(BOOL)arg2 ;
-(struct __CFStringTokenizer *)createTokenizerForCharIndex:(NSUInteger)arg0 outTokenizerRange:(struct _NSRange *)arg1 ;
-(struct __CTFont *)createFontAtCharIndex:(NSUInteger)arg0 scaleTextPercent:(NSUInteger)arg1 effectiveRange:(struct _NSRange *)arg2 styleProvider:(id)arg3 ;
-(struct vector<unsigned long, std::allocator<unsigned long>> )p_charIndicesForAttributeArray:(struct TSWPAttributeArray *)arg0 ;
-(struct vector<unsigned long, std::allocator<unsigned long>> )p_charIndicesForString:(id)arg0 breakingCharacterSet:(id)arg1 ;
-(unsigned char)wpKind;
-(unsigned int)disallowedElementKinds;
-(unsigned int)disallowedSmartFieldKinds;
-(unsigned short)characterAtIndex:(NSUInteger)arg0 ;
-(unsigned short)paragraphFlagsAtCharIndex:(NSUInteger)arg0 ;
-(void)acceptVisitor:(id)arg0 ;
-(void)addAllDictationAndAutocorrectionKeyRangesInRange:(struct _NSRange )arg0 toRanges:(id)arg1 ;
-(void)addDisallowedElementKind:(unsigned int)arg0 ;
-(void)addDisallowedSmartFieldKind:(unsigned short)arg0 ;
-(void)addGlyphVariantData:(id)arg0 toRange:(struct _NSRange )arg1 ;
-(void)addHighlight:(id)arg0 toRange:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(void)addObserver:(id)arg0 ;
-(void)addOverlappingField:(id)arg0 toRange:(struct _NSRange )arg1 attributeKind:(NSUInteger)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 ;
-(void)addParagraphObserver:(id)arg0 ;
-(void)addSmartField:(id)arg0 toRange:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(void)adoptStylesheet:(id)arg0 withMapper:(id)arg1 ;
-(void)afterReplacingReferencedStylesSetStylesheet:(id)arg0 ;
-(void)applyChange:(id)arg0 changeRange:(struct _NSRange )arg1 accept:(BOOL)arg2 undoTransaction:(*void)arg3 ;
-(void)applyChangeSet:(id)arg0 tableKind:(NSUInteger)arg1 range:(struct _NSRange )arg2 undoTransaction:(*void)arg3 ;
-(void)applyChanges:(BOOL)arg0 inRange:(struct _NSRange )arg1 inSelectionRange:(struct _NSRange )arg2 outChangedRange:(struct _NSRange *)arg3 outSelectionRange:(struct _NSRange *)arg4 undoTransaction:(*void)arg5 forceAll:(BOOL)arg6 kind:(int)arg7 ;
-(void)applyDataValue:(unsigned int)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)applyFlags:(unsigned short)arg0 level:(NSUInteger)arg1 toParagraphIndexRange:(struct _NSRange )arg2 forKind:(NSUInteger)arg3 undoTransaction:(*void)arg4 ;
-(void)applyFlags:(unsigned short)arg0 level:(NSUInteger)arg1 toParagraphsInCharRange:(struct _NSRange )arg2 undoTransaction:(*void)arg3 ;
-(void)applyObject:(id)arg0 toCharRange:(struct _NSRange )arg1 forKind:(int)arg2 actionBuilder:(*void)arg3 ;
-(void)applyObject:(id)arg0 toCharRange:(struct _NSRange )arg1 forKind:(int)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 ;
-(void)applyObject:(id)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)applyObject:(id)arg0 toParagraphsInCharRange:(struct _NSRange )arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)applyParagraphData:(struct TSWPParagraphData )arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)applyWritingDirection:(int)arg0 toParagraphIndexRange:(struct _NSRange )arg1 forKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)attributesAtCharIndex:(NSUInteger)arg0 attributesOfInterest:(BOOL)arg1 attributesTable:(id)arg2 effectiveRange:(struct _NSRange *)arg3 ;
-(void)autoUpdateField:(id)arg0 withRange:(struct _NSRange )arg1 documentRoot:(id)arg2 returningInsertedRange:(struct _NSRange *)arg3 ;
-(void)autoUpdateSmartFieldsWithDocumentRoot:(id)arg0 ;
-(void)capitalizeWithUndoTransaction:(*void)arg0 locale:(id)arg1 ;
-(void)clearBackPointerToParentInfoIfNeeded:(id)arg0 ;
-(void)commonInit;
-(void)compress:(*void)arg0 ;
-(void)compressAttributeArrayKind:(NSUInteger)arg0 actionState:(*void)arg1 ;
-(void)dealloc;
-(void)deleteRange:(struct _NSRange )arg0 undoTransaction:(*void)arg1 ;
-(void)didChangeParagraphAttributeLocation:(NSUInteger)arg0 delta:(NSInteger)arg1 ;
-(void)didChangeParagraphsInIndexRange:(struct _NSRange )arg0 ;
-(void)didChangeRange:(struct _NSRange )arg0 delta:(NSInteger)arg1 broadcastKind:(NSUInteger)arg2 ;
-(void)didChangeRange:(struct _NSRange )arg0 delta:(NSInteger)arg1 broadcastKind:(NSUInteger)arg2 attributeKindChanges:(id)arg3 ;
-(void)enumerateAllHyperlinksUsingBlock:(id)arg0 ;
-(void)enumerateAttachmentsInTextRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateAttachmentsOfClass:(Class)arg0 inTextRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)enumerateBookmarksInRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateFootnoteAttachmentsInTextRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateHighlightsInExpandedRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateHighlightsInRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateParagraphsIntersectingTextRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumeratePencilAnnotationsInRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumeratePencilAnnotationsUsingBlock:(id)arg0 ;
-(void)enumerateSmartFieldsWithAttributeKind:(NSUInteger)arg0 inRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)enumerateTateChuYokoInRange:(struct _NSRange )arg0 usingBlock:(id)arg1 ;
-(void)enumerateWithAttributeKind:(NSUInteger)arg0 inRange:(struct _NSRange )arg1 usingBlock:(id)arg2 ;
-(void)enumerateWithAttributeKind:(NSUInteger)arg0 inRange:(struct _NSRange )arg1 withOptions:(NSUInteger)arg2 usingBlock:(id)arg3 ;
-(void)fixGlyphVariantFontsForRange:(struct _NSRange )arg0 ;
-(void)getCharacters:(*unsigned short)arg0 range:(struct _NSRange )arg1 ;
-(void)i_assignStylesheet:(id)arg0 ;
-(void)i_repairParagraphArray;
-(void)insertPlaceholderText:(id)arg0 atCharIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)insertStorage:(id)arg0 atCharIndex:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(void)insertString:(id)arg0 atCharIndex:(NSUInteger)arg1 ;
-(void)insertString:(id)arg0 atCharIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)invalidateCharIndexForAttachment:(id)arg0 ;
-(void)invalidateFootnoteAttachmentCharIndexes;
-(void)invalidateForStyle:(id)arg0 ;
-(void)invalidatePageCountAttachmentCharIndexes:(BOOL)arg0 ;
-(void)loadFromUnarchiver:(id)arg0 ;
-(void)lowercaseWithUndoTransaction:(*void)arg0 locale:(id)arg1 ;
-(void)moveDropCapStyleFromParIndex:(NSUInteger)arg0 toParIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)nonUndoableAppendSection:(id)arg0 charIndex:(NSUInteger)arg1 ;
-(void)nonUndoableFilterInvalidContentForStorage:(id)arg0 keepHighlights:(BOOL)arg1 ;
-(void)nonUndoableFilterInvalidContentForStorage:(id)arg0 keepHighlights:(BOOL)arg1 nestingDepth:(NSInteger)arg2 ;
-(void)nonUndoableFilterParagraphStylesForHeaderFooter;
-(void)nonUndoableInitializeAttributeArraySource:(struct TSWPAttributeArray *)arg0 forSourceRange:(struct _NSRange )arg1 toDestStorage:(id)arg2 objectContext:(id)arg3 dolcContext:(id)arg4 flags:(unsigned int)arg5 ;
-(void)nonUndoableInsertObject:(id)arg0 charIndex:(NSUInteger)arg1 attributeArray:(struct TSWPAttributeArray *)arg2 attributeIndex:(NSUInteger)arg3 dolcContext:(id)arg4 ;
-(void)nonUndoableInsertParagraphData:(struct TSWPParagraphData )arg0 charIndex:(NSUInteger)arg1 attributeArray:(struct TSWPAttributeArray *)arg2 attributeIndex:(NSUInteger)arg3 ;
-(void)nonUndoableRemoveUnsupportedHyperlinks;
-(void)nonUndoableRemoveUnsupportedHyperlinksForCrossDocumentPaste:(BOOL)arg0 ;
-(void)nonUndoableReplaceWithAttachment:(id)arg0 forAttachmentIndex:(NSUInteger)arg1 dolcContext:(id)arg2 ;
-(void)nonUndoableSetWPKind:(unsigned char)arg0 keepHighlights:(BOOL)arg1 ;
-(void)p_attributesAtCharIndex:(NSUInteger)arg0 attributesOfInterest:(BOOL)arg1 attributesTable:(id)arg2 effectiveRange:(struct _NSRange *)arg3 ;
-(void)p_handleChangeSplittingForInsertedRange:(struct _NSRange )arg0 changeSession:(id)arg1 actionBuilder:(struct TSWPStorageActionBuilder *)arg2 ;
-(void)p_mutateByWordWithUndoTransaction:(*void)arg0 locale:(id)arg1 transformer:(id)arg2 ;
-(void)p_nonUndoableFilterPageBreaksFromStorage:(id)arg0 ;
-(void)p_nonUndoableFilterSectionBreaksFromStorage:(id)arg0 ;
-(void)p_removeOverlappingFieldsInRange:(struct _NSRange )arg0 attributeKind:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)p_repairListLevels;
-(void)p_repairSectionArray;
-(void)p_replaceRange:(struct _NSRange )arg0 withString:(id)arg1 markers:(*void)arg2 flags:(unsigned int)arg3 actionState:(*void)arg4 ;
-(void)p_updateChangeTimestampForDeletedRange:(struct _NSRange )arg0 actionBuilder:(struct TSWPStorageActionBuilder *)arg1 ;
-(void)paragraphFlags:(*unsigned short)arg0 andLevel:(*NSUInteger)arg1 atCharIndex:(NSUInteger)arg2 ;
-(void)removeAllObservers;
-(void)removeDisallowedElementKind:(unsigned int)arg0 ;
-(void)removeDisallowedSmartFieldKind:(unsigned short)arg0 ;
-(void)removeGlyphVariantDataFromRange:(struct _NSRange )arg0 ;
-(void)removeHighlight:(id)arg0 atRange:(struct _NSRange )arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(void)removeHighlight:(id)arg0 dolcContext:(id)arg1 undoTransaction:(*void)arg2 ;
-(void)removeHighlightsInRange:(struct _NSRange )arg0 dolcContext:(id)arg1 undoTransaction:(*void)arg2 author:(id)arg3 ;
-(void)removeObserver:(id)arg0 ;
-(void)removeOverlappingField:(id)arg0 fromRange:(struct _NSRange )arg1 attributeKind:(NSUInteger)arg2 undoTransaction:(*void)arg3 ;
-(void)removeParagraphObserver:(id)arg0 ;
-(void)removePencilAnnotations;
-(void)removePencilAnnotationsInRange:(struct _NSRange )arg0 undoTransaction:(*void)arg1 ;
-(void)removeSmartField:(id)arg0 fromRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)replaceCharactersInRange:(struct _NSRange )arg0 withString:(id)arg1 options:(NSUInteger)arg2 changedRange:(struct _NSRange *)arg3 changeDelta:(*NSInteger)arg4 undoTransaction:(*void)arg5 changeSession:(id)arg6 ;
-(void)replaceReferencedStylesUsingBlock:(id)arg0 ;
-(void)resetAllTextAttributeUUIDStrings;
-(void)saveRange:(struct _NSRange )arg0 toArchiver:(id)arg1 styleProvider:(id)arg2 archiveChanges:(BOOL)arg3 removeDeletedText:(BOOL)arg4 archivePencilAnnotations:(BOOL)arg5 ;
-(void)saveToArchiver:(id)arg0 ;
-(void)setCharacterStyle:(id)arg0 range:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setColumnStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setDictationAndAutocorrection:(id)arg0 forCharRange:(struct _NSRange )arg1 actionBuilder:(*void)arg2 ;
-(void)setDictationAndAutocorrection:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setDropCapStyle:(id)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)setDropCapStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setLanguage:(id)arg0 forCharRange:(struct _NSRange )arg1 actionBuilder:(*void)arg2 ;
-(void)setLanguage:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setListStart:(NSUInteger)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setListStyle:(id)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)setListStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphFlags:(unsigned short)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphFlags:(unsigned short)arg0 level:(NSUInteger)arg1 forCharRange:(struct _NSRange )arg2 undoTransaction:(*void)arg3 ;
-(void)setParagraphLevel:(NSUInteger)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphLevel:(NSUInteger)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphStyle:(id)arg0 atParIndex:(NSUInteger)arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphStyle:(id)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setParagraphWritingDirection:(int)arg0 forCharRange:(struct _NSRange )arg1 undoTransaction:(*void)arg2 ;
-(void)setPrimitiveGeometry:(id)arg0 ;
-(void)settingsDidChangeRequiringLayoutAndRendering;
-(void)smartFieldDidChange:(id)arg0 ;
-(void)splitSmartFieldAtCharIndex:(NSUInteger)arg0 lengthToInsert:(NSUInteger)arg1 attributeKind:(NSUInteger)arg2 dolcContext:(id)arg3 undoTransaction:(*void)arg4 ;
-(void)splitSmartFieldAtCharIndex:(NSUInteger)arg0 lengthToInsert:(NSUInteger)arg1 dolcContext:(id)arg2 undoTransaction:(*void)arg3 ;
-(void)styleDidChangeInRange:(struct _NSRange )arg0 ;
-(void)transferAttributeArraySource:(struct TSWPAttributeArray *)arg0 toAttributeArrayDest:(struct TSWPAttributeArray *)arg1 atCharIndex:(NSUInteger)arg2 delta:(NSInteger)arg3 dolcContext:(id)arg4 actionBuilder:(*void)arg5 ;
-(void)unarchiverAppendParagraphBreak:(unsigned short)arg0 ;
-(void)updateStorageChangeCount;
-(void)uppercaseWithUndoTransaction:(*void)arg0 locale:(id)arg1 ;
-(void)wasAddedToDocumentRoot:(id)arg0 dolcContext:(id)arg1 ;
-(void)wasRemovedFromDocumentRoot:(id)arg0 ;
-(void)willBeAddedToDocumentRoot:(id)arg0 dolcContext:(id)arg1 ;
-(void)willBeRemovedFromDocumentRoot:(id)arg0 ;


@end


#endif