// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef PLMODELMIGRATOR_H
#define PLMODELMIGRATOR_H

@class PLXPCTransaction, NSDictionary, PLLazyObject, PLCoreAnalyticsEventManager, NSString, NSFileManager, PLPhotoLibraryPathManager, NSProgress;
@protocol NSProgressReporting, OS_dispatch_queue, OS_dispatch_group;

#import <Foundation/Foundation.h>

#import "PLThumbnailManager.h"
#import "PLDeviceRestoreMigrationSupport.h"
#import "PLDeviceRestoreMigrationPostProcessingSupport.h"

@interface PLModelMigrator : NSObject <NSProgressReporting>

 {
    CGFloat _startTime;
    PLXPCTransaction *_transaction;
    NSDictionary *_syncedPropertiesByUUID;
    PLThumbnailManager *_thumbnailManager;
    PLLazyObject *_lazyCoreAnalysticsEventManager;
    PLLazyObject *_lazyDeviceRestoreMigrationSupport;
    PLLazyObject *_lazyDeviceRestoreMigrationPostProcessingSupport;
    PLLazyObject *_lazyMigrationLogger;
    BOOL _didCreateSqliteErrorFileForLightweightMigration;
    BOOL _isPostProcessingLightWeightMigration;
    NSObject<OS_dispatch_queue> *_fileSystemLoadQueue;
    NSObject<OS_dispatch_group> *_fileSystemLoadGroup;
}


@property (readonly) PLCoreAnalyticsEventManager *analyticsEventManager;
@property (readonly, getter=isCloudPhotoLibraryEnabled) BOOL cloudPhotoLibraryEnabled;
@property (nonatomic) os_unfair_lock_s containedObjectsLock; // ivar: _containedObjectsLock
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) PLDeviceRestoreMigrationSupport *deviceRestoreMigrationSupport;
@property (retain, nonatomic) NSFileManager *fileManager; // ivar: _fileManager
@property (readonly) NSUInteger hash;
@property (nonatomic) os_unfair_lock_s lightweightMigrationLock; // ivar: _lightweightMigrationLock
@property (copy) NSDictionary *options; // ivar: _options
@property (readonly, nonatomic) PLPhotoLibraryPathManager *pathManager; // ivar: _pathManager
@property (readonly, nonatomic) PLDeviceRestoreMigrationPostProcessingSupport *postProcessingToken;
@property (retain) NSProgress *progress; // ivar: _progress
@property (nonatomic) os_unfair_lock_s storeMetadataLock; // ivar: _storeMetadataLock
@property (readonly) Class superclass;


+(BOOL)_readBooleanFlagWithKey:(id)arg0 fromMetadataWithMOC:(id)arg1 pathManager:(id)arg2 ;
+(BOOL)_writeNumber:(id)arg0 forKey:(id)arg1 pathManager:(id)arg2 error:(*id)arg3 ;
+(BOOL)enumerateObjectsWithIncrementalSaveDefaultBatchSizeFetchRequest:(id)arg0 managedObjectContext:(id)arg1 count:(*NSUInteger)arg2 error:(*id)arg3 block:(id)arg4 ;
+(BOOL)executeBatchDeleteWithEntityName:(id)arg0 predicate:(id)arg1 managedObjectContext:(id)arg2 error:(*id)arg3 ;
+(BOOL)executeBatchUpdateWithEntityName:(id)arg0 predicate:(id)arg1 propertiesToUpdate:(id)arg2 managedObjectContext:(id)arg3 error:(*id)arg4 ;
+(BOOL)markAssetsWithThumbsForTableRebuildInContext:(id)arg0 ;
+(BOOL)performFaceAnalysisResetWithResetLevel:(NSInteger)arg0 pathManager:(id)arg1 context:(id)arg2 ;
+(BOOL)resetThumbnailIndexesAndInitiateThumbnailRebuildRequestIfSuccessfulForForThumbnailManager:(id)arg0 deferHintChanges:(BOOL)arg1 inContext:(id)arg2 ;
+(BOOL)shouldImportAssetsFromDCIMSubDirectoryAtURL:(id)arg0 assetsKind:(*int)arg1 ;
+(BOOL)shouldPromptUserForLibrarySchemaMismatch;
+(BOOL)waitForDataMigratorToExit;
+(id)_readNumberWithKey:(id)arg0 fromMetadataWithMOC:(id)arg1 pathManager:(id)arg2 error:(*id)arg3 ;
+(id)extractPathToAssetUUIDRecoveryMappingFromDatabasePath:(id)arg0 ;
+(id)schemaIncompatibilityDetailsForStoreMetadata:(id)arg0 model:(id)arg1 ;
+(int)currentModelVersion;
-(BOOL)_addCameraCaptureDeviceForAssetsInStore:(id)arg0 ;
-(BOOL)_addCloudKindSubtypeAndBurstFlagsInStore:(id)arg0 ;
-(BOOL)_addLocalVideoKeyFrameResourceInStore:(id)arg0 deferHintChanges:(BOOL)arg1 ;
-(BOOL)_addLocationHashesToAssets:(id)arg0 ;
-(BOOL)_addRAWPackedBadgeAttributeForAllRAWAssetsInStore:(id)arg0 ;
-(BOOL)_addUUIDsToCollectionLists:(id)arg0 skipMomentLists:(BOOL)arg1 ;
-(BOOL)_addUUIDsToExistingKeywordsInStore:(id)arg0 ;
-(BOOL)_applyDataProtectionToDCIMFromClassBToClassC;
-(BOOL)_batchOfflineDeleteFromDatabaseOnlyAssets:(id)arg0 inManagedObjectContext:(id)arg1 error:(*id)arg2 ;
-(BOOL)_cleanupInvalidAlbumsAndFoldersInStore:(id)arg0 ;
-(BOOL)_cleanupLegacyFiles;
-(BOOL)_clearAvalancheUUIDOnCloudSharedAssetsWithStore:(id)arg0 ;
-(BOOL)_convertAssetDepthStatesToDepthTypeInStore:(id)arg0 ;
-(BOOL)_convertNameSourceFromBoolToIntForDeferredRebuildFaceInStore:(id)arg0 ;
-(BOOL)_createImportSessionAlbums:(id)arg0 ;
-(BOOL)_createPhotoDataDirectoryIfNecessary:(*BOOL)arg0 error:(*id)arg1 ;
-(BOOL)_deleteAllMemoriesInStore:(id)arg0 ;
-(BOOL)_deleteCloudSharedAndSynced:(BOOL)arg0 assetReferencesInStore:(id)arg1 ;
-(BOOL)_deleteEmptyFolderWithProjectRootCloudGUIDOfWrongKindInStore:(id)arg0 ;
-(BOOL)_deleteExtraneousAdjustedFullSizeResourcesForSloMoAssetsWithStore:(id)arg0 ;
-(BOOL)_deleteLocalVideoKeyFrameResourcesForNonVideosInStore:(id)arg0 deferHintChanges:(BOOL)arg1 ;
-(BOOL)_deleteOrphanedExtendedAttributes:(id)arg0 ;
-(BOOL)_deleteOrphanedUnverifiedPeople:(id)arg0 ;
-(BOOL)_deletePersistentHistoryInStore:(id)arg0 ;
-(BOOL)_deletePersonsMissingUUIDInStore:(id)arg0 ;
-(BOOL)_deletePhotoCloudSharingMetadataInManagedObjectContext:(id)arg0 error:(*id)arg1 ;
-(BOOL)_deletePhotoStreamAssetReferencesInStore:(id)arg0 ;
-(BOOL)_deleteVideoThumbsMadeFromPreferredFrameInStore:(id)arg0 ;
-(BOOL)_disableICloudPhoto;
-(BOOL)_discardUnusedCustomRenderedValuesInStore:(id)arg0 ;
-(BOOL)_emptyResourceTablesInStagedStore:(id)arg0 ;
-(BOOL)_ensureAllUserVerifiedPersonsHaveFaceCropsInStore:(id)arg0 ;
-(BOOL)_filterSceneClassificationsInStore:(id)arg0 ;
-(BOOL)_fixAdjustedAssets:(id)arg0 ;
-(BOOL)_fixAdjustedFingerprintsInStore:(id)arg0 ;
-(BOOL)_fixAlbumAndFolderSortAscending:(id)arg0 ;
-(BOOL)_fixAssetMasterResources:(id)arg0 ;
-(BOOL)_fixCloudMasterCloudLocalState:(id)arg0 ;
-(BOOL)_fixCloudSharedGIFsInStore:(id)arg0 ;
-(BOOL)_fixCloudSharedVideosInStore:(id)arg0 ;
-(BOOL)_fixCorruptedOrientationsInStore:(id)arg0 ;
-(BOOL)_fixCustomKeyAssetForAlbum:(id)arg0 ;
-(BOOL)_fixCustomRenderedValues:(id)arg0 ;
-(BOOL)_fixDuplicatedAssets:(id)arg0 ;
-(BOOL)_fixDuplicatedRootFolderAndOrphanedAlbumsInStore:(id)arg0 ;
-(BOOL)_fixEmptyVideoResourcePathsInStore:(id)arg0 ;
-(BOOL)_fixFaceAlgorithmVersion:(id)arg0 ;
-(BOOL)_fixFaceGroupUnverifiedPerson:(id)arg0 ;
-(BOOL)_fixHasLocationSmartAlbum:(id)arg0 ;
-(BOOL)_fixImportedAssetsFromCMMSavedInDCIMWithWrongSavedAssetType:(id)arg0 ;
-(BOOL)_fixIncorrectAddedDateForAssetsInStore:(id)arg0 ;
-(BOOL)_fixIncorrectHeifMetadataInStore:(id)arg0 ;
-(BOOL)_fixIncorrectThumbnailTablesInStore:(id)arg0 deferHintChanges:(BOOL)arg1 ;
-(BOOL)_fixInitialSyncMarker;
-(BOOL)_fixInvalidPostMigrationFileSystemImportedAssets:(id)arg0 ;
-(BOOL)_fixItemIdentifierForVideoCmplInStore:(id)arg0 ;
-(BOOL)_fixKeywordsInStagedStore:(id)arg0 ;
-(BOOL)_fixKindSubtypeForLoopingVideoLivePhotosInStore:(id)arg0 ;
-(BOOL)_fixLastPrefetchDateInStore:(id)arg0 ;
-(BOOL)_fixLocalPathForVideoCmplDerivativesInStore:(id)arg0 ;
-(BOOL)_fixLocallyAvailableFlagForThumbnailsInStore:(id)arg0 ;
-(BOOL)_fixLocationValuesInStore:(id)arg0 ;
-(BOOL)_fixMasterCloudLocalStateEnum:(id)arg0 ;
-(BOOL)_fixMemoriesWithAssetLists:(id)arg0 ;
-(BOOL)_fixMergedPeopleThatShouldBeVerified:(id)arg0 ;
-(BOOL)_fixMovieAttributesInStore:(id)arg0 ;
-(BOOL)_fixNilCloudMasterGUID:(id)arg0 ;
-(BOOL)_fixNonDuplicatedAssets:(id)arg0 adjusted:(BOOL)arg1 ;
-(BOOL)_fixOriginalAlternateImageOrientationForResourcesInStore:(id)arg0 ;
-(BOOL)_fixOriginalPropertiesForCloudSharedAssetsInStore:(id)arg0 ;
-(BOOL)_fixPersonAndFaceGroup:(id)arg0 ;
-(BOOL)_fixRawWithZeroDimensions:(id)arg0 ;
-(BOOL)_fixRejectedKeyFace:(id)arg0 ;
-(BOOL)_fixSharedStreamVideoResourcesInStore:(id)arg0 ;
-(BOOL)_fixSidecarUTIsAndDataStoreSubtype:(id)arg0 ;
-(BOOL)_fixSingletonFaceFaceGroup:(id)arg0 ;
-(BOOL)_fixTrashedDate:(id)arg0 ;
-(BOOL)_fixUTIForRDMigrationInStore:(id)arg0 ;
-(BOOL)_fixUTIforSlowMoInStore:(id)arg0 ;
-(BOOL)_fixUnpushedVideoComplementResourcesInStore:(id)arg0 ;
-(BOOL)_fixUploadedButNotRemotelyAvailalbeCPLResourcesInStore:(id)arg0 ;
-(BOOL)_fixVideoDimensionsForAsset:(id)arg0 ;
-(BOOL)_fixVideoDimensionsInStore:(id)arg0 ;
-(BOOL)_fixVideoJPGPath:(id)arg0 ;
-(BOOL)_fixVisibleBurstAsset:(id)arg0 ;
-(BOOL)_fixWhiteBalanceValuesInStore:(id)arg0 ;
-(BOOL)_fixWhitelistOwnerForPendingInvitationsInStore:(id)arg0 ;
-(BOOL)_fixZeroDurationPhotoIrisWithLocalResourcesInStore:(id)arg0 assumeAdjustedIrisIsVisible:(BOOL)arg1 ;
-(BOOL)_fixZeroTrashedDateForEntityName:(id)arg0 inManagedObjectContext:(id)arg1 ;
-(BOOL)_fixupAlbumOrderInAlbumListInStore:(id)arg0 ;
-(BOOL)_fixupAssetPersistence:(id)arg0 ;
-(BOOL)_fixupBrokenBurstPicksInStore:(id)arg0 ;
-(BOOL)_fixupCloudResourcesInStore:(id)arg0 ;
-(BOOL)_fixupCroppedUnadjustedAssets:(id)arg0 ;
-(BOOL)_fixupImportedAssetsInStore:(id)arg0 ;
-(BOOL)_fixupImportedEventsInStore:(id)arg0 ;
-(BOOL)_fixupKeyAssetsForAlbumsInStore:(id)arg0 ;
-(BOOL)_fixupResourceTypeUnknownInStore:(id)arg0 ;
-(BOOL)_fixupSharedStreamOrientationsInStore:(id)arg0 ;
-(BOOL)_fixupSharedVideosWithoutThumbnailsInStore:(id)arg0 ;
-(BOOL)_fixupSyncedAssetAttributesInStore:(id)arg0 ;
-(BOOL)_flattenUnknownCustomRenderedValues:(id)arg0 ;
-(BOOL)_forceAlbumMetadataToDiskInStore:(id)arg0 ;
-(BOOL)_forceSoftResetSync;
-(BOOL)_generateAddedDateForAssetsInStore:(id)arg0 ;
-(BOOL)_identifyVariationsAndDepthAdjustmentsForAsset:(id)arg0 ;
-(BOOL)_identifyVariationsAndDepthAdjustmentsIncludingBakedInLongExposure:(BOOL)arg0 inStore:(id)arg1 ;
-(BOOL)_initiateLightweightReimportOfAllPhotoCloudSharingMetadataInStore:(id)arg0 ;
-(BOOL)_invalidateReverseGeocodingDataInStore:(id)arg0 ;
-(BOOL)_invalidateZeroHDRGainInStore:(id)arg0 ;
-(BOOL)_isReasonableCreationDate:(id)arg0 ;
-(BOOL)_markAllProcessedAnalysisStatesDirtyForWorkerType:(short)arg0 withStartingWorkerFlags:(int)arg1 inStore:(id)arg2 ;
-(BOOL)_markMigrationVerifiedTypePersonsInStore:(id)arg0 ;
-(BOOL)_markOldPhotoIrisEditsEvaluatedInStore:(id)arg0 ;
-(BOOL)_markPhotoIrisVideoOrphansInStore:(id)arg0 ;
-(BOOL)_migrateAssetLocationData:(id)arg0 ;
-(BOOL)_migrateCandidateBitsToDeferredProcessingCandidateOptions:(id)arg0 ;
-(BOOL)_migrateCloudResourcesRelationshipsInStagedStore:(id)arg0 ;
-(BOOL)_migrateDetectedFacesGroupInStagedStore:(id)arg0 ;
-(BOOL)_migrateLegacySlomoAdjustmentsInStore:(id)arg0 fromLegacySLMFormat:(BOOL)arg1 ;
-(BOOL)_migrateMetadataAndMigrationHistoryWithStore:(id)arg0 ;
-(BOOL)_migrateOriginalColorSpaceInStagedStore:(id)arg0 ;
-(BOOL)_migrateRejectedFacesGroupInStagedStore:(id)arg0 ;
-(BOOL)_migrateResourceUTIAndCodecInStagedStore:(id)arg0 ;
-(BOOL)_migrateTransformableUUIDsToStringsInStore:(id)arg0 ;
-(BOOL)_migrateVersionSpecific1kResourcesInStore:(id)arg0 deferHintChanges:(BOOL)arg1 ;
-(BOOL)_migrateVideoKeyFrameTimeValuesInStagedStore:(id)arg0 ;
-(BOOL)_move1kResourcesOutOfMastersDir:(id)arg0 ;
-(BOOL)_moveCloudSharedDerivativesInStore:(id)arg0 ;
-(BOOL)_moveGpsHorizontalAccuracyToNewAttribute:(id)arg0 ;
-(BOOL)_moveMyPhotoStreamToAlbumsListInStore:(id)arg0 ;
-(BOOL)_nukeWallpaperRemnantsInStore:(id)arg0 ;
// -(BOOL)_performChangesOnBatchFetchedObjects:(id)arg0 inMOC:(id)arg1 batchSize:(NSUInteger)arg2 objectHandler:(id)arg3 error:(unk)arg4  ;
-(BOOL)_performMigrationCacheDateCreatedOnResources:(BOOL)arg0 cacheItemIdentifierOnResources:(BOOL)arg1 store:(id)arg2 ;
-(BOOL)_persistImportSessionAlbumType:(id)arg0 ;
-(BOOL)_persistMemoriesInStore:(id)arg0 ;
-(BOOL)_persistMetadataToFileSystemForAlbum:(id)arg0 ;
-(BOOL)_persistPersonsInStore:(id)arg0 ;
-(BOOL)_persistPhotoIrisVisibilityStateToDiskInStore:(id)arg0 ;
-(BOOL)_persistPlaceAnnotationData:(id)arg0 ;
-(BOOL)_persistResourceTypeAttributeOnAlternateImageResourcesInStore:(id)arg0 ;
-(BOOL)_persistStoreUUIDToMobileCPLPlist:(id)arg0 ;
-(BOOL)_persistVideoComplPropertiesInStore:(id)arg0 ;
-(BOOL)_populateAdjustmentTimestampsOnAssets:(id)arg0 ;
-(BOOL)_populateAlbumAndFolderOrderKeysInStagedStore:(id)arg0 ;
-(BOOL)_populateCloudNameSourceOnFacesInStore:(id)arg0 ;
-(BOOL)_populateCloudResourceLocalStateInStor:(id)arg0 ;
-(BOOL)_populateCloudVerifiedTypeOnPersonsInStore:(id)arg0 ;
-(BOOL)_populateDurationAndHDRTypeFromAdditionalAssetAttributesInStagedStore:(id)arg0 ;
-(BOOL)_populateFaceRegionsInStore:(id)arg0 ;
-(BOOL)_populateHasAdjustmentsForAssetsInStore:(id)arg0 ;
-(BOOL)_populateLatLongInAsset:(id)arg0 ;
-(BOOL)_populateLightweightReimportDirectoryWithPhotoCloudSharingAssetsInManagedObjectContext:(id)arg0 error:(*id)arg1 ;
-(BOOL)_populateNilOriginalFilename:(id)arg0 ;
-(BOOL)_populateNilOriginalFilenameOnMaster:(id)arg0 ;
-(BOOL)_populateRepresentativeAssets:(id)arg0 ;
-(BOOL)_populateUserKeyFacePickSourceForPersonInStore:(id)arg0 ;
-(BOOL)_populateVideoCpFieldsInStagedStore:(id)arg0 ;
-(BOOL)_postProcessFromVersion6006Store:(id)arg0 ;
-(BOOL)_processDeletesForUUIDs:(id)arg0 ;
-(BOOL)_purgeCloudSharedResourcesInStore:(id)arg0 ;
-(BOOL)_rebuildWideCaptureThumbsInStore:(id)arg0 ;
-(BOOL)_reconstructImageExtendedAttributes:(id)arg0 ;
-(BOOL)_recordCurrentVersionMetadataInPersistentStore:(id)arg0 migrationType:(NSInteger)arg1 forceRebuildReason:(id)arg2 sourceModelVersion:(id)arg3 updateLegacyMigrationState:(BOOL)arg4 journalRebuildRequred:(BOOL)arg5 ;
-(BOOL)_recoverSingleBurstPhotos:(id)arg0 ;
-(BOOL)_refactorLargeVideoRecipeResourcesInStore:(id)arg0 ;
-(BOOL)_refreshTriggerValues:(id)arg0 ;
-(BOOL)_regenerateMonthHighlightTitlesWithStore:(id)arg0 ;
-(BOOL)_regenerateReferenceKeyDataInStore:(id)arg0 ;
-(BOOL)_regenerateSharedStreamsDataStoreKeysDataInStore:(id)arg0 deferHintChanges:(BOOL)arg1 ;
-(BOOL)_relocateCPLMarkerFiles;
-(BOOL)_removeAllLocalVideoKeyFrameResourcesRevert14037InStore:(id)arg0 ;
-(BOOL)_removeAllSharedAssetDCIMFilesInStore:(id)arg0 ;
-(BOOL)_removeAutoloopCacheIfExists;
-(BOOL)_removeAutoloopWorkerStatesInStore:(id)arg0 ;
-(BOOL)_removeCameraRollInStore:(id)arg0 ;
-(BOOL)_removeCloudSharedFileAtPath:(id)arg0 withFileManager:(id)arg1 error:(*id)arg2 ;
-(BOOL)_removeDuplicatedCloudSharedComments:(id)arg0 ;
-(BOOL)_removeEvents:(id)arg0 ;
-(BOOL)_removeInvalidAdjustmentResourceDataInStore:(id)arg0 ;
-(BOOL)_removeInvalidImportSessionAlbums:(id)arg0 ;
-(BOOL)_removeOldPersonMetadataInStore:(id)arg0 ;
-(BOOL)_removeResourceModelManualIdentityConstraintInStore:(id)arg0 ;
-(BOOL)_removeUnneededAnalysisStateTableEntries:(id)arg0 ;
-(BOOL)_removeUntrackedCloudResourceImageDerivativesInStore:(id)arg0 ;
-(BOOL)_removeUntrackedPersonMetadataInStore:(id)arg0 ;
-(BOOL)_removingDuplicatedCloudAssetGuid:(id)arg0 ;
-(BOOL)_renumberLocalAvailabilityAndLocalAvailabilityTargetsInStore:(id)arg0 ;
-(BOOL)_repairCTMOriginalVideosWithSOCAvailableBitInStore:(id)arg0 ;
-(BOOL)_repairCTMOriginalVideosWithoutAdjustmentsInStore:(id)arg0 ;
-(BOOL)_repairDuplicateSingletonFetchingAlbumsInStore:(id)arg0 ;
-(BOOL)_repairLegacyMigrationDuplicateVersionCloudResources:(id)arg0 ;
-(BOOL)_repairOrphanedProjectAlbumsInStore:(id)arg0 ;
-(BOOL)_repairReframedAssetsWithoutSOCAvailableBitWithStore:(id)arg0 ;
-(BOOL)_repairTableThumbFragmentation;
-(BOOL)_repairWallpaperAlbumsInStore:(id)arg0 containerUUID:(id)arg1 title:(id)arg2 ;
-(BOOL)_repersistDuplicatedAssets:(id)arg0 ;
-(BOOL)_repushAllUserSmartAlbum:(id)arg0 ;
-(BOOL)_repushAssetsMatchingPredicate:(id)arg0 inStore:(id)arg1 withMaster:(BOOL)arg2 ;
-(BOOL)_repushAssetsWithAnyUserConfirmedFaceInStore:(id)arg0 ;
-(BOOL)_repushMemoriesWithNewFeaturesInStore:(id)arg0 ;
-(BOOL)_repushPersonsWithMergeTargetInStore:(id)arg0 ;
-(BOOL)_requestAvailabilityChangeForAssetsMissing1kResourcesInStore:(id)arg0 ;
-(BOOL)_resetAlbumToFolderOrderKeyForAlbums:(id)arg0 ;
-(BOOL)_resetAnalysisStateForVideosInStore:(id)arg0 ;
-(BOOL)_resetAssetLocationShiftingAndRevGeoInStore:(id)arg0 ;
-(BOOL)_resetDeferredRepairAdjustmentFailureAndCloudRecoveryStateInStore:(id)arg0 ;
-(BOOL)_resetDupesAnalysisInStore:(id)arg0 ;
-(BOOL)_resetFailedAssets:(id)arg0 ;
-(BOOL)_resetFailedCloudMasters:(id)arg0 ;
-(BOOL)_resetLimitedLibraryFilterDataInStore:(id)arg0 ;
-(BOOL)_resetUploadAttempts:(id)arg0 ;
-(BOOL)_retryQuarantinedAssetsAndFixResourceRelation:(id)arg0 ;
-(BOOL)_revalidateImportSessionDates:(id)arg0 ;
-(BOOL)_runMigrationStepWithName:(id)arg0 fetchRequest:(id)arg1 store:(id)arg2 migrationHandler:(id)arg3 ;
-(BOOL)_runMigrationStepWithPrettyFunction:(char *)arg0 store:(id)arg1 migrationHandler:(id)arg2 ;
-(BOOL)_runPairingForAssetsInStore:(id)arg0 ;
-(BOOL)_saveChangesToPhotoIrisInStore:(id)arg0 matchingPredicate:(id)arg1 countChanged:(*NSUInteger)arg2 error:(*id)arg3 changeBlock:(id)arg4 ;
-(BOOL)_scavengeCameraProcessingAdjustmentMetadataForAssetsInStore:(id)arg0 ;
-(BOOL)_setImportedByInPLCloudMaster:(id)arg0 ;
-(BOOL)_setPlaybackStyleForAnimatedGIFsInStore:(id)arg0 ;
-(BOOL)_setUserTypeOnKeyFace:(id)arg0 ;
-(BOOL)_setupRootFolderInStore:(id)arg0 ;
-(BOOL)_shouldTriggerLightweightMigrationFailureForInternalTesting;
-(BOOL)_storeContainsFaceCrops:(id)arg0 success:(*BOOL)arg1 ;
-(BOOL)_tagScreenshotsForAssetsInStore:(id)arg0 ;
-(BOOL)_trimInvalidAlbumAssetsMappingRecords;
-(BOOL)_tryToPromoteUnknownAssetsInStore:(id)arg0 ;
-(BOOL)_unQuarantineAssetsIfPossibleInStore:(id)arg0 ;
-(BOOL)_unquarantineClass:(Class)arg0 inManagedObject:(id)arg1 ;
-(BOOL)_unquarantinedQuarantinedItems:(id)arg0 ;
-(BOOL)_updateAlbumDatesInStore:(id)arg0 ;
-(BOOL)_updateCPLMarkerFiles;
-(BOOL)_updateKeyAssetInMemory:(id)arg0 ;
-(BOOL)_updateKindSubtypeForPanoramaPhotosNeedsReset:(BOOL)arg0 inStore:(id)arg1 ;
-(BOOL)_updateMissingFileSystemVolumeUuidInStore:(id)arg0 ;
-(BOOL)_updateMogulSubtypeAndSetHighFrameRateStateOnAssetsInStore:(id)arg0 ;
-(BOOL)_updatePlaybackStylesAndVariationsInStore:(id)arg0 ;
-(BOOL)_updatePlaybackWithBatchUpdateRequest:(id)arg0 targetDescription:(id)arg1 inContext:(id)arg2 ;
-(BOOL)_updateQualitySortForResourcesWithCPLResourceTypeVideoFullSizeInStore:(id)arg0 ;
-(BOOL)_updateSuggestionStartAndEndDatesInStore:(id)arg0 ;
-(BOOL)_validateOrDeleteFileAtPath:(id)arg0 forCloudResource:(id)arg1 ;
-(BOOL)_verifyAndFixBrokenLocalAvailabilityForResourceWithFileIDsInStore:(id)arg0 ;
-(BOOL)_verifyCloudAssetsLocalAvailability:(id)arg0 ;
-(BOOL)clearVisionWorkerCache;
-(BOOL)debug_resetThumbnailsAndInitiateRebuildRequestInStore:(id)arg0 ;
-(BOOL)deleteAllAssetAnalysisStatesInStore:(id)arg0 ;
-(BOOL)deleteAllMomentsFromStore:(id)arg0 ;
-(BOOL)deleteAnalysisStatesInStore:(id)arg0 forWorkerType:(short)arg1 ;
-(BOOL)faceQualityResetRequiredForPreviousStoreVersion:(NSUInteger)arg0 ;
-(BOOL)fixPossiblyIncorrectAddedDateForAsset:(id)arg0 ;
-(BOOL)fixupStatesWithUnreachableAssetUUIDsInStore:(id)arg0 ;
-(BOOL)fixupUnknownAnalysisStatesInStore:(id)arg0 ;
-(BOOL)graphPersonResetRequiredForPreviousStoreVersion:(NSUInteger)arg0 ;
-(BOOL)isLoadingFacesFromFileSystem;
-(BOOL)isPhotoLibraryDatabaseReadyForOpen:(*id)arg0 ;
-(BOOL)isPostProcessingLightweightMigration;
-(BOOL)markAllDirtyFaceAnalysisStatesWithFaceDetectionWorkerFlagsInStore:(id)arg0 ;
-(BOOL)markAllSceneAnalysisStatesDirtyAndClearDistanceIdentitiesInStoreAndClearSceneprints:(id)arg0 ;
-(BOOL)markUserConfirmedFacesAndCorrespondingFaceAnalysisStatesDirtyInStore:(id)arg0 ;
-(BOOL)migratePurgeableResources;
-(BOOL)postProcessMigratedStore:(id)arg0 migrationUUID:(id)arg1 fromVersion:(int)arg2 progress:(id)arg3 progressUnitCount:(NSUInteger)arg4 ;
-(BOOL)postProcessThumbnailsOnlyIfVersionMismatchOrMissing:(*BOOL)arg0 coordinator:(id)arg1 ;
-(BOOL)processWelterweightMigrationStageOnStore:(id)arg0 migrationUUID:(id)arg1 fromVersion:(int)arg2 toVersion:(int)arg3 migrationContext:(id)arg4 progress:(id)arg5 progressUnitCount:(NSUInteger)arg6 ;
-(BOOL)rebuildAllMomentsInStore:(id)arg0 ;
-(BOOL)reconsiderAllowedForAnalysisOnAssetsMarkedNotAllowedInStore:(id)arg0 ;
-(BOOL)relocateOriginalUBFPaths:(id)arg0 ;
-(BOOL)resetAnalysisStateForVideosWithMoc:(id)arg0 ;
-(BOOL)resetFaceQualityInStore:(id)arg0 ;
-(BOOL)resetGraphPersonsInStore:(id)arg0 ;
-(BOOL)resetManualOrderForNonFavoritePeopleInManagedObjectContext:(id)arg0 ;
-(BOOL)resetManualOrderForNonFavoritePeopleInStore:(id)arg0 ;
-(BOOL)resetRejectedFacesOnAllPersonsInStore:(id)arg0 ;
-(BOOL)sceneStepRequiredForPreviousStoreVersion:(NSUInteger)arg0 ;
-(BOOL)shouldCreateDatabase;
-(BOOL)skipDataProtectionForFilePath:(id)arg0 ;
-(BOOL)touchAnalysisStateSortTokensInStoreInStore:(id)arg0 ;
-(BOOL)updateCompletedMigrationStateWithError:(*id)arg0 ;
-(BOOL)validateModelEntityNames:(*id)arg0 ;
-(NSInteger)attemptLightweightMigrationFromVersion:(id)arg0 onStore:(id)arg1 withMetadata:(id)arg2 orStoreURL:(id)arg3 options:(id)arg4 coordinator:(id)arg5 migrationPolicy:(unsigned int)arg6 error:(*id)arg7 ;
-(NSInteger)checkForceRebuildIndicatorFile;
-(NSInteger)createNewDatabaseWithMigrationType:(NSInteger)arg0 forceRebuildReason:(id)arg1 coordinator:(id)arg2 error:(*id)arg3 ;
-(NSInteger)legacyMigrationState;
-(NSInteger)migrateOrCreateDatabaseIfNecessaryWithPersistentContainer:(id)arg0 migrationPolicy:(unsigned int)arg1 error:(*id)arg2 ;
-(NSInteger)promptUserIfNeededForRebuildReason:(id)arg0 migrationError:(id)arg1 ;
-(NSUInteger)_assetCountForContext:(id)arg0 ;
-(NSUInteger)_assetCountForLibrary:(id)arg0 ;
-(NSUInteger)_assetCountForStore:(id)arg0 ;
-(id)_dateForFirstCRVSPhoto;
-(id)_dateForVariations;
-(id)_dateForWideGamutCapture;
-(id)_dateWithiTunesTimeInterval:(CGFloat)arg0 ;
-(id)_eventNameFromDate:(id)arg0 ;
-(id)_fetchRequestToIdentifyAdjustedDepthAndVariationsCandidates;
-(id)_fetchRequestToIdentifyBakedInVariationsCandidatesIncludingLongExposure:(BOOL)arg0 ;
-(id)_iTunesPhotosLastSyncMetadata;
-(id)_importFileSystemImportAssets:(id)arg0 intoLibrary:(id)arg1 forceUpdate:(BOOL)arg2 progress:(id)arg3 ;
-(id)_loadOriginalVideoMetadataFromAsset:(id)arg0 timeZoneLookup:(id)arg1 error:(*id)arg2 ;
-(id)_migrationThumbnailManagerWithStore:(id)arg0 ;
-(id)_newSyncedPropertiesByAssetUUIDs:(BOOL)arg0 ;
-(id)_orderedAssetsToImportInLibrary:(id)arg0 ;
-(id)_orderedAssetsToImportInLibrary:(id)arg0 cameraRollOnly:(BOOL)arg1 ;
-(id)_predicateForInconsistentHeifAssets;
-(id)_syncedPropertiesForAssetUUID:(id)arg0 ;
-(id)archivedAssetUUIDForURL:(id)arg0 ;
-(id)generatePathToAssetUUIDRecoveryMapping;
-(id)initWithPathManager:(id)arg0 ;
-(id)managedObjectContextForMigrationInStore:(id)arg0 name:(char *)arg1 concurrencyType:(NSUInteger)arg2 ;
-(id)managedObjectContextForMigrationWithName:(char *)arg0 persistentStoreCoordinator:(id)arg1 concurrencyType:(NSUInteger)arg2 ;
-(id)migrationLogger;
-(id)newDeviceRestoreMigrationSupport;
-(id)newShortLivedLibraryForRebuildWithName:(char *)arg0 ;
-(id)newShortLivedLibraryWithName:(char *)arg0 ;
-(int)_migrateLegacySlomoAdjustmentsForAsset:(id)arg0 ;
-(void)_addUBFBundleScopedOrderedAssetsToImport:(id)arg0 onDiskURLsToSkip:(id)arg1 ;
-(void)_applySyncedProperties:(id)arg0 toAsset:(id)arg1 ;
-(void)_convertImplicitDownloadAndKeepOriginalsEnabledToExplicit;
-(void)_failed_recordCurrentVersionMetadata;
-(void)_failed_repairSingletonObjectsInNewDatabaseWithNilContextError:(id)arg0 ;
-(void)_failed_repairSingletonObjectsInNewDatabaseWithNoPersistentStores;
-(void)_failed_repairSingletonObjectsInNewDatabaseWithRepairError:(id)arg0 ;
-(void)_failed_repairSingletonObjectsWithError:(id)arg0 ;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSCoreDataError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreIncompatibleSchemaError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreIncompatibleVersionHashError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreInvalidTypeError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreOpenError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreTimeoutError;
-(void)_failed_repairSingletonObjectsWithErrorTypeNSPersistentStoreTypeMismatchError;
-(void)_failed_repairSingletonObjectsWithErrorTypeOtherCoreDataError;
-(void)_failed_repairSingletonObjectsWithErrorTypeOtherPhotosError;
-(void)_failed_repairSingletonObjectsWithErrorTypeOtherSQLiteError;
-(void)_failed_repairSingletonObjectsWithErrorTypePLPhotosErrorInvalidState;
-(void)_failed_repairSingletonObjectsWithErrorTypePLPhotosErrorInvalidURL;
-(void)_failed_repairSingletonObjectsWithErrorTypePLPhotosErrorLibraryRequiresMigration;
-(void)_failed_repairSingletonObjectsWithErrorTypePLPhotosErrorLibraryTooNew;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_CANTOPEN;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_CORRUPT;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_ERROR;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_FULL;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_LOCKED;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_MISUSE;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_NOTADB;
-(void)_failed_repairSingletonObjectsWithErrorTypeSQLITE_PERM;
-(void)_failed_repairSingletonObjectsWithInvalidDatabaseFile;
-(void)_failed_repairSingletonObjectsWithInvalidFileTypeLibraryDirectory;
-(void)_failed_repairSingletonObjectsWithMissingDatabaseFile;
-(void)_failed_repairSingletonObjectsWithMissingLibraryDirectory;
-(void)_failed_repairSingletonObjectsWithNilContextError:(id)arg0 ;
-(void)_failed_repairSingletonObjectsWithNoPersistentStores;
-(void)_failed_repairSingletonObjectsWithRepairError:(id)arg0 ;
-(void)_fixIncorrectHeifMetadataForAsset:(id)arg0 ;
-(void)_fixPathForResource:(id)arg0 withPath:(id)arg1 ;
-(void)_forceDupeAnalysis;
-(void)_generateAlbumMetadataFromLastiTunesSyncedPlist;
-(void)_handleCreateOptionsUsingContext:(id)arg0 ;
-(void)_importAfterCrash:(id)arg0 dictionariesByPhotoStreamID:(id)arg1 completionBlock:(id)arg2 ;
-(void)_importAllDCIMAssetsInLibrary:(id)arg0 progress:(id)arg1 progressFraction:(id)arg2 rebuildComplete:(BOOL)arg3 ;
-(void)_loadFacesFileSystemDataIntoDatabase;
-(void)_loadFileSystemDataIntoDatabaseIfNeededWithReason:(id)arg0 progress:(id)arg1 ;
-(void)_migratePersonContactInfo;
-(void)_populateFaceRegionsForAsset:(id)arg0 ;
-(void)_prepareForImportDeleteCorruptAssetsWithImporter:(id)arg0 context:(id)arg1 ;
-(void)_rebuildAssetsFromJournal:(id)arg0 inLibrary:(id)arg1 progress:(id)arg2 progressFraction:(id)arg3 ;
-(void)_removeFileAt:(id)arg0 forResource:(id)arg1 ;
-(void)_repairInProgressDCIMLockedAssetTransfersInOrderedAssetsToImport:(id)arg0 baseDirectory:(id)arg1 photoDataLockedAssetsURL:(id)arg2 photoDataCPLAssetsURL:(id)arg3 photoStreamsBaseURL:(id)arg4 ;
-(void)_repairInProgressLockedAssetTransfersInOrderedAssetsToImport:(id)arg0 ;
-(void)_repairMetadataAndSingletonsForMigrationType:(NSInteger)arg0 forceRebuildReason:(id)arg1 journalRebuildRequired:(BOOL)arg2 ;
-(void)_repairPotentialModelCorruptionInLibrary:(id)arg0 ;
-(void)_setIsPostProcessingLightWeightMigration:(BOOL)arg0 ;
-(void)_validateCurrentModelVersionAttempt:(NSInteger)arg0 ;
-(void)_validateCurrentModelVersionFailedWithMismatchedVersion:(NSInteger)arg0 ;
-(void)_validateCurrentModelVersionFailedWithNoVersionFromServer;
-(void)applyDataProtectionToAllPhotosFilesOnce;
-(void)applyDataProtectionToPhotosPaths:(id)arg0 fromKeyClass:(int)arg1 toKeyClass:(int)arg2 ;
-(void)archiveAssetUUIDForPathPlist:(id)arg0 ;
-(void)cleanupModelForDataMigrationForRestoreType:(NSInteger)arg0 ;
-(void)dontImportFileSystemDataIntoDatabaseWithPhotoLibrary:(id)arg0 ;
-(void)filesystemImportResultsUpdateKeywordWithImportedAssets:(id)arg0 ;
-(void)forceImportFileSystemDataIntoDatabaseWithPhotoLibrary:(id)arg0 ;
-(void)handleGreenChanges:(id)arg0 ;
-(void)importAfterCrash:(id)arg0 dictionariesByPhotoStreamID:(id)arg1 completionBlock:(id)arg2 ;
-(void)loadFacesFileSystemDataIntoDatabase;
-(void)loadFileSystemAssetsNotifyCompleted:(id)arg0 ;
-(void)loadFileSystemAssetsNotifyEnter;
-(void)loadFileSystemAssetsNotifyLeave;
-(void)loadFileSystemDataIntoDatabaseIfNeededWithReason:(id)arg0 completionHandler:(id)arg1 ;
-(void)migratePersonContactInfo;
-(void)migrationLoggerClose;
-(void)pausePhotoStreams;
-(void)postProcessFixesAfterOTARestoreForCompleteAsset:(id)arg0 fixAddedDate:(BOOL)arg1 shouldGenerateThumbnails:(BOOL)arg2 ;
-(void)removeUnpairedTimelapsePreviewsInContext:(id)arg0 fromDuplicatedUUIDs:(id)arg1 ;
-(void)repairSingletonObjectsInDatabase;
-(void)resumePhotoStreams;
-(void)setLoadingFacesFromFileSystem:(BOOL)arg0 ;
-(void)validateCurrentModelVersion;


@end


#endif