// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef WEBHTMLVIEW_H
#define WEBHTMLVIEW_H

@class WAKView, NSString;
@protocol WebDocumentSelection, WebDocumentIncrementalSearching, WebDocumentElement, WebMultipleTextMatches, WebDocumentOptionsSearching, WebDocumentView, WebDocumentSearching;


#import "WebHTMLViewPrivate.h"

@interface WebHTMLView : WAKView <WebDocumentSelection, WebDocumentIncrementalSearching, WebDocumentElement, WebMultipleTextMatches, WebDocumentOptionsSearching, WebDocumentView, WebDocumentSearching>

 {
    WebHTMLViewPrivate *_private;
}


@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;


+(id)supportedImageMIMETypes;
+(id)supportedMIMETypes;
+(id)supportedMediaMIMETypes;
+(id)supportedNonImageMIMETypes;
+(id)unsupportedTextMIMETypes;
-(BOOL)_beginPrintModeWithMinimumPageWidth:(CGFloat)arg0 height:(CGFloat)arg1 maximumPageWidth:(CGFloat)arg2 ;
-(BOOL)_beginPrintModeWithPageWidth:(float)arg0 height:(float)arg1 shrinkToFit:(BOOL)arg2 ;
-(BOOL)_beginScreenPaginationModeWithPageSize:(struct CGSize )arg0 shrinkToFit:(BOOL)arg1 ;
-(BOOL)_canAlterCurrentSelection;
-(BOOL)_canDecreaseSelectionListLevel;
-(BOOL)_canEdit;
-(BOOL)_canEditRichly;
-(BOOL)_canIncreaseSelectionListLevel;
-(BOOL)_canSmartCopyOrDelete;
-(BOOL)_findString:(id)arg0 options:(NSUInteger)arg1 ;
-(BOOL)_handleEditingKeyEvent:(*void)arg0 ;
-(BOOL)_hasInsertionPoint;
-(BOOL)_hasSelection;
-(BOOL)_hasSelectionOrInsertionPoint;
-(BOOL)_isEditable;
-(BOOL)_isInPrintMode;
-(BOOL)_isInScreenPaginationMode;
-(BOOL)_isSelectionEvent:(id)arg0 ;
-(BOOL)_isTopHTMLView;
-(BOOL)_isUsingAcceleratedCompositing;
-(BOOL)_needsLayout;
-(BOOL)_shouldInsertFragment:(id)arg0 replacingDOMRange:(id)arg1 givenAction:(NSInteger)arg2 ;
-(BOOL)_shouldInsertText:(id)arg0 replacingDOMRange:(id)arg1 givenAction:(NSInteger)arg2 ;
-(BOOL)_shouldReplaceSelectionWithText:(id)arg0 givenAction:(NSInteger)arg1 ;
-(BOOL)_wantsKeyDownForEvent:(id)arg0 ;
-(BOOL)acceptsFirstResponder;
-(BOOL)becomeFirstResponder;
-(BOOL)callDelegateDoCommandBySelectorIfNeeded:(SEL)arg0 ;
-(BOOL)hasMarkedText;
-(BOOL)isOpaque;
-(BOOL)maintainsInactiveSelection;
-(BOOL)markedTextMatchesAreHighlighted;
-(BOOL)resignFirstResponder;
-(BOOL)searchFor:(id)arg0 direction:(BOOL)arg1 caseSensitive:(BOOL)arg2 wrap:(BOOL)arg3 ;
-(BOOL)searchFor:(id)arg0 direction:(BOOL)arg1 caseSensitive:(BOOL)arg2 wrap:(BOOL)arg3 startInSelection:(BOOL)arg4 ;
-(BOOL)supportsTextEncoding;
-(CGFloat)_adjustedBottomOfPageWithTop:(CGFloat)arg0 bottom:(CGFloat)arg1 limit:(CGFloat)arg2 ;
-(NSInteger)conversationIdentifier;
-(NSUInteger)characterIndexForPoint:(struct CGPoint )arg0 ;
-(NSUInteger)countMatchesForText:(id)arg0 inDOMRange:(id)arg1 options:(NSUInteger)arg2 limit:(NSUInteger)arg3 markMatches:(BOOL)arg4 ;
-(id)_accessibilityParentForSubview:(id)arg0 ;
-(id)_compositingLayersHostingView;
-(id)_dataSource;
-(id)_documentRange;
-(id)_emptyStyle;
-(id)_frame;
-(id)_frameView;
-(id)_increaseSelectionListLevel;
-(id)_increaseSelectionListLevelOrdered;
-(id)_increaseSelectionListLevelUnordered;
-(id)_insertOrderedList;
-(id)_insertUnorderedList;
-(id)_pluginController;
-(id)_selectedRange;
-(id)_topHTMLView;
-(id)_webView;
-(id)accessibilityFocusedUIElement;
-(id)accessibilityHitTest:(struct CGPoint )arg0 ;
-(id)accessibilityRootElement;
-(id)elementAtPoint:(struct CGPoint )arg0 ;
-(id)elementAtPoint:(struct CGPoint )arg0 allowShadowContent:(BOOL)arg1 ;
-(id)hitTest:(struct CGPoint )arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)rectsForTextMatches;
-(id)selectedString;
-(id)selectionTextRects;
-(id)selectionView;
-(id)string;
-(struct CGImage *)selectionImageForcingBlackText:(BOOL)arg0 ;
-(struct CGRect )_selectionRect;
-(struct CGRect )firstRectForCharacterRange:(struct _NSRange )arg0 ;
-(struct CGRect )selectionImageRect;
-(struct CGRect )selectionRect;
-(struct Command )coreCommandByName:(char *)arg0 ;
-(struct Command )coreCommandBySelector:(SEL)arg0 ;
-(struct _NSRange )markedRange;
-(struct _NSRange )selectedRange;
-(void)_applyEditingStyleToSelection:(*void)arg0 withUndoAction:(unsigned char)arg1 ;
-(void)_applyStyleToSelection:(id)arg0 withUndoAction:(unsigned char)arg1 ;
-(void)_changeWordCaseWithSelector:(SEL)arg0 ;
-(void)_decreaseSelectionListLevel;
-(void)_destroyAllWebPlugins;
-(void)_endPrintMode;
-(void)_endScreenPaginationMode;
-(void)_executeSavedKeypressCommands;
-(void)_frameOrBoundsChanged;
-(void)_layoutIfNeeded;
-(void)_restoreSubviews;
-(void)_selectionChanged;
-(void)_setAsideSubviews;
-(void)_setMouseDownEvent:(id)arg0 ;
-(void)_setPrinting:(BOOL)arg0 minimumPageLogicalWidth:(float)arg1 logicalHeight:(float)arg2 originalPageWidth:(float)arg3 originalPageHeight:(float)arg4 maximumShrinkRatio:(float)arg5 adjustViewSize:(BOOL)arg6 paginateScreenContent:(BOOL)arg7 ;
-(void)_setToolTip:(id)arg0 ;
-(void)_stopAutoscrollTimer;
-(void)_web_updateLayoutAndStyleIfNeededRecursive;
-(void)addSubview:(id)arg0 ;
-(void)alignCenter:(id)arg0 ;
-(void)alignJustified:(id)arg0 ;
-(void)alignLeft:(id)arg0 ;
-(void)alignRight:(id)arg0 ;
-(void)capitalizeWord:(id)arg0 ;
-(void)centerSelectionInVisibleArea:(id)arg0 ;
-(void)clearFocus;
-(void)clearText:(id)arg0 ;
-(void)close;
-(void)closeIfNotCurrentView;
-(void)copy:(id)arg0 ;
-(void)cut:(id)arg0 ;
-(void)dataSourceUpdated:(id)arg0 ;
-(void)dealloc;
-(void)delete:(id)arg0 ;
-(void)deleteBackward:(id)arg0 ;
-(void)deleteBackwardByDecomposingPreviousCharacter:(id)arg0 ;
-(void)deleteForward:(id)arg0 ;
-(void)deleteToBeginningOfLine:(id)arg0 ;
-(void)deleteToBeginningOfParagraph:(id)arg0 ;
-(void)deleteToEndOfLine:(id)arg0 ;
-(void)deleteToEndOfParagraph:(id)arg0 ;
-(void)deleteToMark:(id)arg0 ;
-(void)deleteWordBackward:(id)arg0 ;
-(void)deleteWordForward:(id)arg0 ;
-(void)deselectAll;
-(void)doCommandBySelector:(SEL)arg0 ;
-(void)drawRect:(struct CGRect )arg0 ;
-(void)drawSingleRect:(struct CGRect )arg0 ;
-(void)executeCoreCommandByName:(char *)arg0 ;
-(void)executeCoreCommandBySelector:(SEL)arg0 ;
-(void)ignoreSpelling:(id)arg0 ;
-(void)indent:(id)arg0 ;
-(void)insertBacktab:(id)arg0 ;
-(void)insertLineBreak:(id)arg0 ;
-(void)insertNewline:(id)arg0 ;
-(void)insertNewlineIgnoringFieldEditor:(id)arg0 ;
-(void)insertParagraphSeparator:(id)arg0 ;
-(void)insertTab:(id)arg0 ;
-(void)insertTabIgnoringFieldEditor:(id)arg0 ;
-(void)insertText:(id)arg0 ;
-(void)jumpToSelection:(id)arg0 ;
-(void)keyDown:(id)arg0 ;
-(void)keyUp:(id)arg0 ;
-(void)layout;
-(void)layoutIfNeeded;
-(void)layoutToMinimumPageWidth:(float)arg0 height:(float)arg1 originalPageWidth:(float)arg2 originalPageHeight:(float)arg3 maximumShrinkRatio:(float)arg4 adjustingViewSize:(BOOL)arg5 ;
-(void)lowercaseWord:(id)arg0 ;
-(void)makeBaseWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeTextWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeft:(id)arg0 ;
-(void)markedTextUpdate:(id)arg0 ;
-(void)mouseDown:(id)arg0 ;
-(void)mouseMoved:(id)arg0 ;
-(void)mouseUp:(id)arg0 ;
-(void)moveBackward:(id)arg0 ;
-(void)moveBackwardAndModifySelection:(id)arg0 ;
-(void)moveDown:(id)arg0 ;
-(void)moveDownAndModifySelection:(id)arg0 ;
-(void)moveForward:(id)arg0 ;
-(void)moveForwardAndModifySelection:(id)arg0 ;
-(void)moveLeft:(id)arg0 ;
-(void)moveLeftAndModifySelection:(id)arg0 ;
-(void)moveParagraphBackwardAndModifySelection:(id)arg0 ;
-(void)moveParagraphForwardAndModifySelection:(id)arg0 ;
-(void)moveRight:(id)arg0 ;
-(void)moveRightAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfDocument:(id)arg0 ;
-(void)moveToBeginningOfDocumentAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfLine:(id)arg0 ;
-(void)moveToBeginningOfLineAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfParagraph:(id)arg0 ;
-(void)moveToBeginningOfParagraphAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfSentence:(id)arg0 ;
-(void)moveToBeginningOfSentenceAndModifySelection:(id)arg0 ;
-(void)moveToEndOfDocument:(id)arg0 ;
-(void)moveToEndOfDocumentAndModifySelection:(id)arg0 ;
-(void)moveToEndOfLine:(id)arg0 ;
-(void)moveToEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveToEndOfParagraph:(id)arg0 ;
-(void)moveToEndOfParagraphAndModifySelection:(id)arg0 ;
-(void)moveToEndOfSentence:(id)arg0 ;
-(void)moveToEndOfSentenceAndModifySelection:(id)arg0 ;
-(void)moveToLeftEndOfLine:(id)arg0 ;
-(void)moveToLeftEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveToRightEndOfLine:(id)arg0 ;
-(void)moveToRightEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveUp:(id)arg0 ;
-(void)moveUpAndModifySelection:(id)arg0 ;
-(void)moveWordBackward:(id)arg0 ;
-(void)moveWordBackwardAndModifySelection:(id)arg0 ;
-(void)moveWordForward:(id)arg0 ;
-(void)moveWordForwardAndModifySelection:(id)arg0 ;
-(void)moveWordLeft:(id)arg0 ;
-(void)moveWordLeftAndModifySelection:(id)arg0 ;
-(void)moveWordRight:(id)arg0 ;
-(void)moveWordRightAndModifySelection:(id)arg0 ;
-(void)outdent:(id)arg0 ;
-(void)overWrite:(id)arg0 ;
-(void)pageDown:(id)arg0 ;
-(void)pageDownAndModifySelection:(id)arg0 ;
-(void)pageUp:(id)arg0 ;
-(void)pageUpAndModifySelection:(id)arg0 ;
-(void)paste:(id)arg0 ;
-(void)pasteAsPlainText:(id)arg0 ;
-(void)pressureChangeWithEvent:(id)arg0 ;
-(void)reapplyStyles;
-(void)scrollWheel:(id)arg0 ;
-(void)selectAll;
-(void)selectAll:(id)arg0 ;
-(void)selectLine:(id)arg0 ;
-(void)selectParagraph:(id)arg0 ;
-(void)selectSentence:(id)arg0 ;
-(void)selectToMark:(id)arg0 ;
-(void)selectWord:(id)arg0 ;
-(void)setDataSource:(id)arg0 ;
-(void)setMark:(id)arg0 ;
-(void)setMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)setMarkedTextMatchesAreHighlighted:(BOOL)arg0 ;
-(void)setNeedsDisplayInRect:(struct CGRect )arg0 ;
-(void)setNeedsLayout:(BOOL)arg0 ;
-(void)setNeedsToApplyStyles:(BOOL)arg0 ;
-(void)setScale:(float)arg0 ;
-(void)subscript:(id)arg0 ;
-(void)superscript:(id)arg0 ;
-(void)swapWithMark:(id)arg0 ;
-(void)toggleBold:(id)arg0 ;
-(void)toggleItalic:(id)arg0 ;
-(void)toggleUnderline:(id)arg0 ;
-(void)touch:(id)arg0 ;
-(void)transpose:(id)arg0 ;
-(void)underline:(id)arg0 ;
-(void)unmarkAllTextMatches;
-(void)unmarkText;
-(void)unscript:(id)arg0 ;
-(void)uppercaseWord:(id)arg0 ;
-(void)viewDidMoveToHostWindow;
-(void)viewDidMoveToWindow;
-(void)viewWillDraw;
-(void)viewWillMoveToHostWindow:(id)arg0 ;
-(void)viewWillMoveToWindow:(id)arg0 ;
-(void)willRemoveSubview:(id)arg0 ;
-(void)yank:(id)arg0 ;
-(void)yankAndSelect:(id)arg0 ;


@end


#endif