

#include "CinematicTrack.h"
#include "CinematicFramingSessionFramingParameters.h"
#include "CinematicTracker.h"
#include "CinematicFramingSession.h"
#include "AnimationEngineConfiguration.h"
#include "AnimationEngine.h"
#include "SceneFramingEngine.h"
#include "PerspectiveDistortionCorrectionSession.h"
#include "BaseTrack.h"
#include "MovementStateEstimatorOptions.h"
#include "MovementStateEstimator.h"
#include "DebugDrawer.h"
#include "EdgeRectangleAnimator.h"
#include "CinematicDirectorSession.h"
#include "CinematicFramingSessionOptions.h"
#include "Detection.h"
#include "CinematicFramingSessionInputMetadata.h"
#include "FrameUndistortionSession.h"
