

#include "MSPowerAssertionManager.h"
#include "MSAMNotificationInfo.h"
#include "MSAlertManager.h"
#include "MSAuthenticationManager.h"
#include "MSConnection.h"
#include "MSMSPlatform.h"
#include "MSClientSidePauseContext.h"
#include "MSPauseManager.h"
#include "MSBatteryPowerMonitor.h"
#include "MSASConnection.h"
#include "MSPBTimerContext.h"
#include "MSPowerBudget.h"
#include "MSASPlatformImplementation.h"
#include "XPCRequest.h"
#include "XPCClientConnection.h"
#include "XPCServiceConnection.h"
#include "XPCServiceListener.h"
#include "XPCNSRequest.h"
#include "XPCNSClientConnection.h"
#include "XPCNSServiceConnection.h"
#include "XPCNSServiceListener.h"
