

#include "PatternPlayer.h"
#include "CHHapticParameterAttributesImpl.h"
#include "CHDefaultHapticDeviceCapability.h"
#include "CHHapticParameterCurve.h"
#include "CHHapticParameterCurveControlPoint.h"
#include "HapticServerConfig.h"
#include "AdvancedPatternPlayer.h"
#include "EventToDictionaryConverter.h"
#include "PatternPlayerBase.h"
#include "HapticDictionaryWriter.h"
#include "HapticCommandConverter.h"
#include "HapticDictionaryReader.h"
#include "CHHapticEventParameter.h"
#include "CHHapticDynamicParameter.h"
#include "PlaybackAction.h"
#include "CHMetrics.h"
#include "AVHapticSequenceEntry.h"
#include "AVHapticClient.h"
#include "CHHapticPattern.h"
#include "CHEmbeddedAudioResourceInfo.h"
#include "CHHapticEngine.h"
#include "AVHapticPlayerChannel.h"
#include "AVHapticPlayer.h"
#include "AVHapticSequence.h"
#include "AVHapticParameterCurveValue.h"
#include "CHHapticEvent.h"
