

#include "MGHome.h"
#include "MGSoloDevice.h"
#include "MGZone.h"
#include "MGGroup.h"
#include "MGAudioReceiverAccessory.h"
#include "MGClientConnectionProvider.h"
#include "MGClientService.h"
#include "MGSpeakerAccessory.h"
#include "MGGroupIdentifier.h"
#include "MGAppleTVAccessory.h"
#include "MGHomePodAccessory.h"
#include "MGGroupQuery.h"
#include "MGRoom.h"
#include "MGMediaSystem.h"
