// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef CHDTITLE_H
#define CHDTITLE_H


#import <Foundation/Foundation.h>

#import "CHDChart.h"
#import "CHDFormula.h"
#import "EDString.h"
#import "OADGraphicProperties.h"

@interface CHDTitle : NSObject {
    CHDChart *mChart;
    BOOL mIsAutoGenerated;
    BOOL mPositionAutoGenerated;
    BOOL mSizeAutoGenerated;
    BOOL mIsOverlay;
    CHDFormula *mName;
    EDString *mLastCachedName;
    OADGraphicProperties *mGraphicProperties;
    CGFloat mRotation;
}




-(BOOL)isAutoGenerated;
-(BOOL)isAutoSizeAndPosition;
-(BOOL)isCachedTitleEmpty;
-(BOOL)isOverlay;
-(BOOL)isPositionAutoGenerated;
-(BOOL)isSizeAutoGenerated;
-(BOOL)isTitleVisible;
-(CGFloat)titleRotationAngle;
-(id)description;
-(id)graphicProperties;
-(id)initWithChart:(id)arg0 ;
-(id)lastCachedName;
-(id)name;
-(void)setGraphicProperties:(id)arg0 ;
-(void)setIsAutoGenerated:(BOOL)arg0 ;
-(void)setIsOverlay:(BOOL)arg0 ;
-(void)setIsPositionAutoGenerated:(BOOL)arg0 ;
-(void)setIsSizeAutoGenerated:(BOOL)arg0 ;
-(void)setLastCachedName:(id)arg0 ;
-(void)setName:(id)arg0 ;
-(void)setTitleRotationAngle:(CGFloat)arg0 ;


@end


#endif