

#include "MADEmbeddingGenerationRequest.h"
#include "MADVIVisualSearchGatingRequest.h"
#include "MADRequest.h"
#include "MADServicePublic.h"
#include "MADResult.h"
#include "MADVIMachineReadableCodeDetectionResultItem.h"
#include "MADVIMachineReadableCodeDetectionResult.h"
#include "MADVIMachineReadableCodeDetectionRequest.h"
#include "MADEmbeddingGenerationResult.h"
#include "MADServicePrivate.h"
#include "MADServiceProxy.h"
#include "MADService.h"
#include "MADVIDocumentRecognitionRequest.h"
#include "MADVIVisualSearchRequest.h"
#include "MADImageSafetyClassificationRequest.h"
#include "MADVIVisualSearchRegionAttributes.h"
#include "MADVIVisualSearchResultItem.h"
#include "MADVIVisualSearchResult.h"
#include "MADVIDocumentRecognitionResult.h"
#include "MADVIVisualSearchGatingDomainInfo.h"
#include "MADVIVisualSearchGatingResultItem.h"
#include "MADVIVisualSearchGatingResult.h"
#include "MADImageSafetyClassificationResult.h"
