// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef PVENVIRONMENT_H
#define PVENVIRONMENT_H


#import <Foundation/Foundation.h>


@interface PVEnvironment : NSObject



+(BOOL)PVHighlightHDRRegions;
+(BOOL)PV_CLAMP_XR_INPUTS_TO_FILTERS;
+(BOOL)PV_DEBUG_COLOR_NO_SOURCE_TRACK_NODE;
+(BOOL)PV_DEBUG_COLOR_OUT_OF_RANGE_EFFECTS;
+(BOOL)PV_DISABLE_PROXY_RENDERING;
+(BOOL)PV_DISABLE_TIMELINE_SCROLLING;
+(BOOL)PV_DISABLE_YCBCR_INPUTS;
+(BOOL)PV_ENABLE_420V_OUTPUT;
+(BOOL)PV_ENABLE_AVF_COLOR_CONFORM_INPUTS;
+(BOOL)PV_ENABLE_BGRA_OUTPUT_EXPORT;
+(BOOL)PV_ENABLE_CHECK_PASSTHRUS;
+(BOOL)PV_ENABLE_ENV_LOGS;
+(BOOL)PV_HIGHLIGHT_OUT_OF_GAMUT;
+(BOOL)PV_MULTI_SOURCE_PLAYBACK_FPS;
+(BOOL)PV_SERIALIZE_EXPORT_REQUESTS;
+(BOOL)PV_THROTTLE_EXPORT_ON_MEM_WARNING;
+(float)PVExportPrefilterValue;
+(float)PV_TEXTURE_POOL_FINISH_SIZE_RATIO;
+(id)versionInfo;
+(int)PV_NUM_RENDER_PASSES;
+(int)PV_PERFORMANCE_LOG_FORMAT;
+(int)PV_PERFORMANCE_LOG_LEVEL;
+(int)PV_PERFORMANCE_LOG_OUTPUT;
+(int)PV_RENDER_PASS_TEST_TYPE;
+(int)PV_RENDER_THREAD_PRIORITY;
+(int)PV_TEXTURE_BORDER_WIDTH;
+(int)PV_TEXTURE_POOL_SIZE_MB;
+(unsigned int)PV_HG_POOL_OBSERVER_INTERVAL;
+(unsigned int)PV_MAX_EXPECTED_LIVE_COMPOSITORS;
+(unsigned int)PV_METAL_COMMAND_Q_COMMAND_BUFFER_COUNT_MAX;
+(unsigned int)PV_METAL_COMMAND_Q_COMMAND_BUFFER_COUNT_MIN;
+(unsigned int)PV_METAL_COMMAND_Q_MEM_USAGE;
+(unsigned int)PV_TEXTURE_CLUSTER_PADDING_CLUMPING;
+(unsigned int)PV_TEXTURE_CLUSTER_PADDING_CUSHIONING;
+(unsigned int)PV_TEXTURE_CLUSTER_PADDING_REMEMBRANCE;
+(unsigned int)PV_THROTTLE_AVF_EXPORT_REQUEST_HANDLING_MS;
+(void)Initialize;


@end


#endif