// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef AFPREFERENCES_H
#define AFPREFERENCES_H

@class NSLock, NSMutableArray;
@protocol OS_dispatch_queue;

#import <Foundation/Foundation.h>

#import "AFInstanceContext.h"
#import "AFPreferencesNotificationCenter.h"

@interface AFPreferences : NSObject {
    atomic_flag _registeredForInternalPrefs;
    atomic_flag _registeredForLanguageCode;
    atomic_flag _registeredForOutputVoice;
    atomic_flag _registeredForNanoPrefs;
    atomic_flag _registeredForAssistantEnablement;
    atomic_flag _registeredForDictationEnablement;
    NSObject<OS_dispatch_queue> *_navTokenQueue;
    BOOL _navTokenIsValid;
    int _navToken;
    NSInteger _tlsSessionTicketFlushRequestPending;
    AFInstanceContext *_instanceContext;
    AFPreferencesNotificationCenter *_trampoline;
    NSLock *_trampolineObserverListLock;
    NSMutableArray *_trampolineObservers;
}




+(id)sharedPreferences;
+(id)sharedPreferencesWithInstanceContext:(id)arg0 ;
-(BOOL)_dictationIsAllowed;
-(BOOL)_languageCode:(id)arg0 isGoodFitForPreferredLanguages:(id)arg1 ;
-(BOOL)allowExplicitContent;
-(BOOL)alwaysAllowVoiceActivation;
-(BOOL)alwaysObscureBackgroundContentWhenActive;
-(BOOL)alwaysShowRecognizedSpeech;
-(BOOL)announceNotificationsOnBuiltInSpeakerEnabled;
-(BOOL)announceNotificationsOnHearingAidsEnabled;
-(BOOL)announceNotificationsOnHearingAidsSupported;
-(BOOL)assistantIsEnabled;
-(BOOL)assistantLanguageForceRTL;
-(BOOL)autoDismissal2018Enabled;
-(BOOL)avvcLoggingEnabled;
-(BOOL)cardLoggingEnabled;
-(BOOL)cloudSyncEnabled;
-(BOOL)commandLoggingEnabled;
-(BOOL)companionConnectionsOverBLEEnabled;
-(BOOL)crownActivationEnabled;
-(BOOL)curareOrchestrationEnabled;
-(BOOL)databaseSyncEnabled;
-(BOOL)debugButtonIsEnabled;
-(BOOL)designModeIsEnabled;
-(BOOL)deviceHasAtvOrHomepodInHome;
-(BOOL)deviceHasPairedWatches;
-(BOOL)dictationAutoPunctuationEnabled;
-(BOOL)dictationIsEnabled;
-(BOOL)disableAssistantWhilePasscodeLocked;
-(BOOL)disableMyriadBLEActivity;
-(BOOL)dismissWhenDeviceIsLoweredEnabled;
-(BOOL)dismissWhenFaceAttentionIsLostEnabled;
-(BOOL)displayedLowStorageNotificationForLanguage:(id)arg0 ;
-(BOOL)enableDragAndDrop;
-(BOOL)enableNonFullScreenAppearance;
-(BOOL)fileLoggingIsEnabled;
-(BOOL)forceOfflineRecognitionEnabled;
-(BOOL)getMessageWithoutConfirmationEnabled;
-(BOOL)getMessageWithoutConfirmationHeadphonesEnabled;
-(BOOL)getMessageWithoutConfirmationInCarPlayEnabled;
-(BOOL)ignoreMyriadPlatformBias;
-(BOOL)ignoreServerManualEndpointingThreshold;
-(BOOL)includeProbePacketCaptureForABC;
-(BOOL)infersQoSFromInstanceUUIDForEAR;
-(BOOL)isAccessibleEndpointerEnabled;
-(BOOL)isCurrentLocaleNativelySupported;
-(BOOL)isDictationHIPAACompliant;
-(BOOL)isDictationOnDeviceSamplingDisabled;
-(BOOL)isInRestrictedSharingMode;
-(BOOL)isLanguageDetectorEnabled;
-(BOOL)isLanguageDetectorEnabledByServer;
-(BOOL)isLocaleIdentifierNativelySupported:(id)arg0 ;
-(BOOL)isMediaEntitySyncDisabled;
-(BOOL)isOnDeviceDictationForced;
-(BOOL)isSmartLanguageSelectionEnabled;
-(BOOL)keepRecordedAudioFiles;
-(BOOL)limitedAudioLoggingEnabled;
-(BOOL)listenAfterSpeakingDisabled;
-(BOOL)mediaPlaybackEnabled;
-(BOOL)myriadCoordinationEnabled;
-(BOOL)myriadCoordinationEnabledForAccessoryLogging;
-(BOOL)myriadDuckingEnabled;
-(BOOL)myriadServerHasProvisioned;
-(BOOL)myriadServerProvisioning;
-(BOOL)myriadShouldIgnoreAdjustedBoost;
-(BOOL)nanoAlwaysShowRecognizedSpeech;
-(BOOL)nanoAssistantEnabled;
-(BOOL)nanoCrownActivationEnabled;
-(BOOL)nanoDictationAutoPunctuationEnabled;
-(BOOL)nanoDictationEnabled;
-(BOOL)nanoPhraseSpotterEnabled;
-(BOOL)nanoRaiseToSpeakEnabled;
-(BOOL)nanoSiriResponseShouldAlwaysPrint;
-(BOOL)networkLoggingEnabled;
-(BOOL)offlineDictationOverride;
-(BOOL)onDeviceDictationAvailableAlertPresented;
-(BOOL)opportuneSpeakingFileLoggingIsEnabled;
-(BOOL)preferOnlineRecognitionEnabled;
-(BOOL)shouldDisableMediaEntitySync;
-(BOOL)shouldLogForQA;
-(BOOL)shouldSuppressSiriDataSharingOptInAlert;
-(BOOL)showServerOnUI;
-(BOOL)showsHoldToTalkIndicator;
-(BOOL)siriDebugUIEnabled;
-(BOOL)siriResponseShouldAlwaysPrint;
-(BOOL)siriResponseShouldAlwaysPrintWithoutOverride;
-(BOOL)siriSpeakerGradingDebugUIEnabled;
-(BOOL)siriVocabularyEnabled;
-(BOOL)siriXDebugStatusEnabled;
-(BOOL)spokenNotificationSkipTriggerlessReplyConfirmation;
-(BOOL)startAlertEnabled;
-(BOOL)streamingDictationEnabled;
-(BOOL)suppressAssistantOptIn;
-(BOOL)suppressDictationOptIn;
-(BOOL)tlsSessionTicketsFlushPending;
-(BOOL)utteranceDetectionEnabled;
-(CGFloat)autoDismissalExtendedIdleTimeout;
-(CGFloat)autoDismissalIdleTimeout;
-(CGFloat)autoDismissalMaxAttentionSamplingTime;
-(CGFloat)handsOffIdleTimeInterval;
-(CGFloat)handsOnIdleTimeInterval;
-(CGFloat)myriadDeviceDelay;
-(CGFloat)myriadDeviceSlowdown;
-(CGFloat)myriadDeviceTrumpDelay;
-(CGFloat)myriadDeviceVTEndTimeDistanceThreshold;
-(CGFloat)myriadMaxNoOperationDelay;
-(CGFloat)myriadTestDeviceDelay;
-(CGFloat)opportuneSpeakingPauseInterval;
-(CGFloat)opportuneSpeakingTimeoutInterval;
-(NSInteger)accessibleEndpointerThreshold;
-(NSInteger)nanoSiriDataSharingOptInStatus;
-(NSInteger)nanoUseDeviceSpeakerForTTS;
-(NSInteger)siriDataSharingOptInStatus;
-(NSInteger)useDeviceSpeakerForTTS;
-(NSUInteger)currentNavigationState;
-(NSUInteger)internalUserClassification;
-(float)myriadDeviceAdjust;
-(float)nanoTTSSpeakerVolume;
-(id)_AFSupportPreferencesValueForKey:(id)arg0 ;
-(id)_bestSupportedLanguageCodeForLanguageCode:(id)arg0 isGoodFit:(*BOOL)arg1 ;
-(id)_bestSupportedLanguageCodeForLanguageCodes:(id)arg0 isGoodFit:(*BOOL)arg1 ;
-(id)_languageCodeWithFallback:(BOOL)arg0 ;
-(id)_languagePreferencesForCurrentSystemConfiguration;
-(id)_nanoPreferencesValueForKey:(id)arg0 ;
-(id)_outputVoiceWithFallback:(BOOL)arg0 ;
-(id)activeDictationLanguages;
-(id)allSiriLanguageCodesForSystemLanguageCode:(id)arg0 isGoodFit:(*BOOL)arg1 ;
-(id)bestSupportedLanguageCodeForLanguageCode:(id)arg0 ;
-(id)cloudSyncEnabledModificationDate;
-(id)configOverrides;
-(id)description;
-(id)dictationAutoPunctuationSupportedLocales;
-(id)dictationSLSLanguagesEnabled;
-(id)enabledDictationLocales;
-(id)getHomeAccessoriesRepromptStatus;
-(id)getHomeAccessorySiriDataSharingChangeLog;
-(id)getHomeAccessorySiriDataSharingPropagationLog;
-(id)horsemanSupplementalLanguageDictionary;
-(id)inProgressOutputVoice;
-(id)init;
-(id)initWithInstanceContext:(id)arg0 ;
-(id)instanceContext;
-(id)languageCode;
-(id)manualEndpointingThreshold;
-(id)myriadDeviceGroup;
-(id)myriadLastWin;
-(id)myriadMonitorTimeOutInterval;
-(id)nanoDictationAutoPunctuationSupportedLanguages;
-(id)nanoLanguageCode;
-(id)nanoOfflineDictationStatus;
-(id)nanoOutputVoice;
-(id)offlineDictationProfileOverridePath;
-(id)offlineDictationStatus;
-(id)outputVoice;
-(id)siriDataSharingOptInStatusHistory;
-(id)speechProfileExternalOfflineModelRootPath;
-(id)supplementalLanguageDictionaryForProduct:(id)arg0 ;
-(id)supplementalLanguages;
-(id)supplementalLanguagesForProduct:(id)arg0 forBuildVersion:(id)arg1 ;
-(id)supplementalLanguagesModificationDate;
-(id)valueForSessionContextPreferenceKey:(id)arg0 ;
-(int)myriadConstantGoodness;
-(unsigned char)myriadDeviceClass;
-(void)_AFSupportPreferencesSetValue:(id)arg0 forKey:(id)arg1 ;
-(void)_assistantEnablementDidChangeExternally;
-(void)_dictationEnablementDidChangeExternally;
-(void)_internalPreferencesDidChangeExternally;
-(void)_languageCodeDidChangeExternally;
-(void)_nanoPrefsDidChangeExternally;
-(void)_outputVoiceDidChangeExternally;
-(void)_preferencesDidChangeExternally;
-(void)_registerForAssistantEnablementChangeNotifications;
-(void)_registerForDarwinNotification:(struct __CFString *)arg0 block:(id)arg1 ;
-(void)_registerForDictationEnablementChangeNotifications;
-(void)_registerForInternalPrefs;
-(void)_registerForLanguageCodeChangeNotifications;
-(void)_registerForNanoPrefsChangeNotifications;
-(void)_registerForNavStatusIfNeeded;
-(void)_registerForOutputVoice;
-(void)_setAssistantIsEnabledLocal:(BOOL)arg0 ;
-(void)_setDictationAutoPunctuationEnabledLocal:(BOOL)arg0 ;
-(void)_setDictationIsAllowed:(BOOL)arg0 ;
-(void)_setDictationIsEnabledLocal:(BOOL)arg0 ;
-(void)_setLoggingDefaultValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setNanoPreferencesValue:(id)arg0 forKey:(id)arg1 ;
-(void)_setOnDeviceDictationAvailableAlertPresentedLocal:(BOOL)arg0 ;
-(void)_setSuppressDictationOptInLocal:(BOOL)arg0 ;
-(void)_suppressLowStorageNotificationForLanguage:(id)arg0 suppress:(BOOL)arg1 ;
-(void)appendHomeAccessorySiriDataSharingChangeLogEvent:(id)arg0 ;
-(void)appendToSiriDataSharingOptInStatusHistory:(NSInteger)arg0 previousOptInStatus:(NSInteger)arg1 statusChangeSource:(NSInteger)arg2 reason:(id)arg3 ;
-(void)clearAnnounceNotificationsInCarPlayTemporarilyDisabled;
-(void)clearAnnounceNotificationsInCarPlayType;
-(void)clearMessageWithoutConfirmationEnabled;
-(void)clearMessageWithoutConfirmationHeadphonesEnabled;
-(void)clearMessageWithoutConfirmationInCarPlayEnabled;
-(void)clearSpokenNotificationTemporarilyDisabledStatus;
-(void)dealloc;
-(void)erasePreferences;
-(void)getAnnounceNotificationsInCarPlayTemporarilyDisabledWithCompletion:(id)arg0 ;
-(void)getAnnounceNotificationsInCarPlayTypeWithCompletion:(id)arg0 ;
-(void)getAnnounceNotificationsTemporarilyDisabledEndDateForApp:(id)arg0 platform:(NSInteger)arg1 completion:(id)arg2 ;
-(void)getAnnounceNotificationsTemporarilyDisabledEndDateForPlatform:(NSInteger)arg0 completion:(id)arg1 ;
-(void)getAnnounceNotificationsTemporarilyDisabledForApp:(id)arg0 platform:(NSInteger)arg1 completion:(id)arg2 ;
-(void)getAnnounceNotificationsTemporarilyDisabledStatusForPlatform:(NSInteger)arg0 completion:(id)arg1 ;
-(void)getExperimentForConfigurationIdentifier:(id)arg0 completion:(id)arg1 ;
-(void)getMessageWithoutConfirmationEnabledWithCompletion:(id)arg0 ;
-(void)getMessageWithoutConfirmationHeadphonesEnabledWithCompletion:(id)arg0 ;
-(void)getMessageWithoutConfirmationInCarPlayEnabledWithCompletion:(id)arg0 ;
-(void)getOfflineDictationStatusWithCompletion:(id)arg0 ;
-(void)getSpokenNotificationIsAlwaysOpportuneWithCompletion:(id)arg0 ;
-(void)getSpokenNotificationShouldAnnounceAllNotificationsWithCompletion:(id)arg0 ;
-(void)getSpokenNotificationShouldSkipTriggerlessRepliesWithCompletion:(id)arg0 ;
-(void)getSpokenNotificationTemporarilyDisabledEndDateForApp:(id)arg0 completion:(id)arg1 ;
-(void)getSpokenNotificationTemporarilyDisabledEndDateWithCompletion:(id)arg0 ;
-(void)getSpokenNotificationTemporarilyDisabledForApp:(id)arg0 completion:(id)arg1 ;
-(void)getSpokenNotificationTemporarilyDisabledStatusWithCompletion:(id)arg0 ;
-(void)insertHomeAccessorySiriDataSharingPropagationLogEvent:(id)arg0 ;
-(void)removeConfigOverrideForKey:(id)arg0 ;
-(void)resetSessionLanguage;
-(void)setAVVCLoggingEnabled:(BOOL)arg0 ;
-(void)setAccessibleEndpointerThreshold:(NSInteger)arg0 ;
-(void)setAlwaysAllowVoiceActivation:(BOOL)arg0 ;
-(void)setAlwaysObscureBackgroundContentWhenActive:(BOOL)arg0 ;
-(void)setAlwaysShowRecognizedSpeech:(BOOL)arg0 ;
-(void)setAnnounceNotificationsInCarPlayTemporarilyDisabled:(BOOL)arg0 ;
-(void)setAnnounceNotificationsInCarPlayType:(NSInteger)arg0 ;
-(void)setAnnounceNotificationsOnBuiltInSpeakerEnabled:(BOOL)arg0 ;
-(void)setAnnounceNotificationsOnHearingAidsEnabled:(BOOL)arg0 ;
-(void)setAnnounceNotificationsOnHearingAidsSupported:(BOOL)arg0 ;
-(void)setAnnounceNotificationsTemporarilyDisabledUntil:(id)arg0 forApp:(id)arg1 platform:(NSInteger)arg2 ;
-(void)setAnnounceNotificationsTemporarilyDisabledUntil:(id)arg0 platform:(NSInteger)arg1 ;
-(void)setAssistantIsEnabled:(BOOL)arg0 ;
-(void)setAssistantLanguageForceRTL:(BOOL)arg0 ;
-(void)setAutoDismissal2018Enabled:(BOOL)arg0 ;
-(void)setAutoDismissalExtendedIdleTimeout:(CGFloat)arg0 ;
-(void)setAutoDismissalIdleTimeout:(CGFloat)arg0 ;
-(void)setAutoDismissalMaxAttentionSamplingTime:(CGFloat)arg0 ;
-(void)setCardLoggingEnabled:(BOOL)arg0 ;
-(void)setCloudSyncEnabled:(BOOL)arg0 ;
-(void)setCommandLoggingEnabled:(BOOL)arg0 ;
-(void)setCompanionConnectionsOverBLEEnabled:(BOOL)arg0 ;
-(void)setConfigOverrideWithValue:(id)arg0 forKey:(id)arg1 ;
-(void)setConfigOverrides:(id)arg0 ;
-(void)setCrownActivationEnabled:(BOOL)arg0 ;
-(void)setCurareOrchestrationEnabled:(BOOL)arg0 ;
-(void)setCurrentNavigationState:(NSUInteger)arg0 ;
-(void)setDatabaseSyncEnabled:(BOOL)arg0 ;
-(void)setDebugButtonIsEnabled:(BOOL)arg0 ;
-(void)setDesignModeEnabled:(BOOL)arg0 ;
-(void)setDictationAutoPunctuationEnabled:(BOOL)arg0 ;
-(void)setDictationIsEnabled:(BOOL)arg0 ;
-(void)setDictationSLSLanguagesEnabled:(id)arg0 ;
-(void)setDisableAssistantWhilePasscodeLocked:(BOOL)arg0 ;
-(void)setDismissWhenDeviceIsLoweredEnabled:(BOOL)arg0 ;
-(void)setDismissWhenFaceAttentionIsLostEnabled:(BOOL)arg0 ;
-(void)setEnableDragAndDrop:(BOOL)arg0 ;
-(void)setEnableNonFullScreenAppearance:(BOOL)arg0 ;
-(void)setFileLoggingIsEnabled:(BOOL)arg0 ;
-(void)setForceOfflineRecognitionEnabled:(BOOL)arg0 ;
-(void)setHandsOffIdleTimeInterval:(CGFloat)arg0 ;
-(void)setHandsOnIdleTimeInterval:(CGFloat)arg0 ;
-(void)setHomeAccessoriesRepromptStatus:(id)arg0 ;
-(void)setIgnoreMyriadAdjustedBoost:(BOOL)arg0 ;
-(void)setIgnoreMyriadPlatformBias:(BOOL)arg0 ;
-(void)setIgnoreServerManualEndpointingThreshold:(BOOL)arg0 ;
-(void)setInProgressOutputVoice:(id)arg0 ;
-(void)setInternalUserClassification:(NSUInteger)arg0 ;
-(void)setKeepRecordedAudioFiles:(BOOL)arg0 ;
-(void)setLanguageCode:(id)arg0 ;
-(void)setLanguageCode:(id)arg0 outputVoice:(id)arg1 ;
-(void)setLanguageDetectorEnabled:(BOOL)arg0 ;
-(void)setLimitedAudioLoggingEnabled:(BOOL)arg0 ;
-(void)setListenAfterSpeakingDisabled:(BOOL)arg0 ;
-(void)setManualEndpointingThreshold:(id)arg0 ;
-(void)setMediaPlaybackEnabled:(BOOL)arg0 ;
-(void)setMessageWithoutConfirmationEnabled:(BOOL)arg0 ;
-(void)setMessageWithoutConfirmationHeadphonesEnabled:(BOOL)arg0 ;
-(void)setMessageWithoutConfirmationInCarPlayEnabled:(BOOL)arg0 ;
-(void)setMyriadConstantGoodness:(int)arg0 ;
-(void)setMyriadCoordinationEnabled:(BOOL)arg0 ;
-(void)setMyriadDeviceAdjust:(float)arg0 ;
-(void)setMyriadDeviceClass:(unsigned char)arg0 ;
-(void)setMyriadDeviceDelay:(CGFloat)arg0 ;
-(void)setMyriadDeviceGroup:(id)arg0 ;
-(void)setMyriadDeviceSlowdown:(CGFloat)arg0 ;
-(void)setMyriadDeviceTrumpDelay:(CGFloat)arg0 ;
-(void)setMyriadDeviceVTEndTimeDistanceThreshold:(CGFloat)arg0 ;
-(void)setMyriadDuckingEnabled:(BOOL)arg0 ;
-(void)setMyriadLastWin;
-(void)setMyriadMaxNoOperationDelay:(CGFloat)arg0 ;
-(void)setMyriadServerHasProvisioned:(BOOL)arg0 ;
-(void)setMyriadServerProvisioning:(BOOL)arg0 ;
-(void)setMyriadTestDeviceDelay:(CGFloat)arg0 ;
-(void)setNanoAlwaysShowRecognizedSpeech:(BOOL)arg0 ;
-(void)setNanoAssistantEnabled:(BOOL)arg0 ;
-(void)setNanoCrownActivationEnabled:(BOOL)arg0 ;
-(void)setNanoDictationAutoPunctuationEnabled:(BOOL)arg0 ;
-(void)setNanoDictationEnabled:(BOOL)arg0 ;
-(void)setNanoLanguageCode:(id)arg0 ;
-(void)setNanoLanguageCode:(id)arg0 outputVoice:(id)arg1 forTinkerDevice:(id)arg2 ;
-(void)setNanoOutputVoice:(id)arg0 ;
-(void)setNanoPhraseSpotterEnabled:(BOOL)arg0 ;
-(void)setNanoRaiseToSpeakEnabled:(BOOL)arg0 ;
-(void)setNanoSiriDataSharingOptInStatus:(NSInteger)arg0 ;
-(void)setNanoSiriResponseShouldAlwaysPrint:(BOOL)arg0 ;
-(void)setNanoTTSSpeakerVolume:(float)arg0 ;
-(void)setNanoUseDeviceSpeakerForTTS:(NSInteger)arg0 ;
-(void)setNetworkLoggingEnabled:(BOOL)arg0 ;
-(void)setOfflineDictationOverride:(BOOL)arg0 ;
-(void)setOfflineDictationProfileOverridePath:(id)arg0 ;
-(void)setOfflineDictationStatus:(id)arg0 ;
-(void)setOnDeviceDictationAvailableAlertPresented:(BOOL)arg0 ;
-(void)setOpportuneSpeakingFileLoggingIsEnabled:(BOOL)arg0 ;
-(void)setOpportuneSpeakingPauseInterval:(CGFloat)arg0 ;
-(void)setOpportuneSpeakingTimeoutInterval:(CGFloat)arg0 ;
-(void)setOutputVoice:(id)arg0 ;
-(void)setPreferOnlineRecognitionEnabled:(BOOL)arg0 ;
-(void)setShowServerOnUI:(BOOL)arg0 ;
-(void)setShowsHoldToTalkIndicator:(BOOL)arg0 ;
-(void)setSiriDataSharingHomePodSetupDeviceIsValid:(BOOL)arg0 completion:(id)arg1 ;
-(void)setSiriDataSharingOptInAlertPresented:(BOOL)arg0 completion:(id)arg1 ;
-(void)setSiriDataSharingOptInStatus:(NSInteger)arg0 completion:(id)arg1 ;
-(void)setSiriDataSharingOptInStatus:(NSInteger)arg0 propagateToHomeAccessories:(BOOL)arg1 source:(NSInteger)arg2 reason:(id)arg3 completion:(id)arg4 ;
-(void)setSiriDebugUIEnabled:(BOOL)arg0 ;
-(void)setSiriResponseShouldAlwaysPrint:(BOOL)arg0 ;
-(void)setSiriSpeakerGradingDebugUIEnabled:(BOOL)arg0 ;
-(void)setSiriVocabularyEnabled:(BOOL)arg0 ;
-(void)setSiriXDebugStatusEnabled:(BOOL)arg0 ;
-(void)setSmartLanguageSelection:(BOOL)arg0 ;
-(void)setSpeechProfileExternalOfflineModelRootPath:(id)arg0 ;
-(void)setSpokenNotificationIsAlwaysOpportune:(BOOL)arg0 ;
-(void)setSpokenNotificationShouldAnnounceAllNotifications:(BOOL)arg0 ;
-(void)setSpokenNotificationShouldSkipTriggerlessReplies:(BOOL)arg0 ;
-(void)setSpokenNotificationSkipTriggerlessReplyConfirmation:(BOOL)arg0 ;
-(void)setSpokenNotificationTemporarilyDisabledForApp:(id)arg0 until:(id)arg1 ;
-(void)setSpokenNotificationTemporarilyDisabledUntil:(id)arg0 ;
-(void)setSpokenNotificationsProxCardSeen;
-(void)setStartAlertEnabled:(BOOL)arg0 ;
-(void)setStreamingDictationEnabled:(BOOL)arg0 ;
-(void)setSuppressAssistantOptIn:(BOOL)arg0 ;
-(void)setSuppressDictationOptIn:(BOOL)arg0 ;
-(void)setTLSSessionTicketsFlushPending:(BOOL)arg0 ;
-(void)setUseDeviceSpeakerForTTS:(NSInteger)arg0 ;
-(void)setUtteranceDetectionEnabled:(BOOL)arg0 ;
-(void)setValue:(id)arg0 forSessionContextKey:(id)arg1 ;
-(void)suppressLowStorageNotificationForLanguage:(id)arg0 suppress:(BOOL)arg1 ;
-(void)synchronize;
-(void)synchronizeAVVCPreferencesDomain;
-(void)synchronizeLogPreferencesDomain;
-(void)synchronizeVoiceServicesLanguageCode;


@end


#endif