// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef UIRESPONDER_H
#define UIRESPONDER_H

@class UIResponder<UITextInput>, UIView<UITextInputPrivate>, NSString, NSArray, NSUndoManager, NSUserActivity;
@protocol UIActivityItemsConfigurationProviding, UITextInput_Internal, UITextInputAdditions, UIUserActivityRestoring, _UIStateRestorationContinuation, _UITouchesEventRespondable, _UIPressesEventRespondable, UIResponderStandardEditActions, _UICopyConfigurationReading, UIActivityItemsConfigurationReading;

#import <Foundation/Foundation.h>

#import "UIResponder.h"
#import "UIView.h"
#import "UIInputViewController.h"
#import "UITextInputAssistantItem.h"
#import "UITextInputMode.h"

@interface UIResponder : NSObject <UIActivityItemsConfigurationProviding, UITextInput_Internal, UITextInputAdditions, UIUserActivityRestoring, _UIStateRestorationContinuation, _UITouchesEventRespondable, _UIPressesEventRespondable, UIResponderStandardEditActions>

 {
    ? _responderFlags;
}


@property (readonly, nonatomic, getter=_proxyTextInput) UIResponder<UITextInput> *__content;
@property (retain, nonatomic, setter=_setCopyConfiguration:) NSObject<_UICopyConfigurationReading> *_copyConfiguration;
@property (readonly, nonatomic) UIResponder *_editingDelegate;
@property (readonly, nonatomic) UIView<UITextInputPrivate> *_textSelectingContainer;
@property (retain, nonatomic) NSObject<UIActivityItemsConfigurationReading> *activityItemsConfiguration;
@property (readonly, nonatomic) BOOL canBecomeFirstResponder;
@property (readonly, nonatomic) BOOL canResignFirstResponder;
@property (readonly, nonatomic, getter=_caretRect) CGRect caretRect;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, nonatomic, getter=isEditable) BOOL editable;
@property (readonly, nonatomic, getter=isEditing) BOOL editing;
@property (readonly, nonatomic) NSInteger editingInteractionConfiguration;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic) UIView *inputAccessoryView;
@property (readonly, nonatomic) UIInputViewController *inputAccessoryViewController;
@property (readonly, nonatomic) UITextInputAssistantItem *inputAssistantItem;
@property (readonly, nonatomic) UIView *inputView;
@property (readonly, nonatomic) UIInputViewController *inputViewController;
@property (readonly, nonatomic) BOOL isFirstResponder;
@property (readonly, nonatomic) NSArray *keyCommands;
@property (readonly, nonatomic) UIResponder *nextResponder;
@property (copy, nonatomic) NSString *restorationIdentifier;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly, nonatomic) NSString *textInputContextIdentifier;
@property (readonly, nonatomic) UITextInputMode *textInputMode;
@property (readonly, nonatomic) NSUndoManager *undoManager;
@property (retain, nonatomic) NSUserActivity *userActivity;


+(BOOL)_callBecomeFirstResponder:(id)arg0 withIntent:(NSUInteger)arg1 ;
+(BOOL)_callResignFirstResponder:(id)arg0 withIntent:(NSUInteger)arg1 ;
+(NSUInteger)_currentChangeIntent;
+(id)objectWithRestorationIdentifierPath:(id)arg0 ;
+(void)_cleanupAllStateRestorationTables;
+(void)_cleanupStateRestorationObjectIdentifierTrackingTables;
+(void)_finishStateRestoration;
+(void)_prepareForSecondPassStateRestoration;
+(void)_setRestoredIdentifierPathForObject:(id)arg0 identifierPath:(id)arg1 ;
+(void)_startDeferredTrackingObjectsWithIdentifiers;
+(void)_stopDeferredTrackingObjectsWithIdentifiers;
+(void)_updateStateRestorationIdentifierMap;
+(void)clearTextInputContextIdentifier:(id)arg0 ;
-(BOOL)_allowsChangingFirstResponderForFocusUpdateWithContext:(id)arg0 ;
-(BOOL)_becomeFirstResponderWhenPossible;
-(BOOL)_canChangeFirstResponder:(id)arg0 toResponder:(id)arg1 ;
-(BOOL)_canResignIfContainsFirstResponder;
-(BOOL)_canShowTextServiceForType:(NSInteger)arg0 ;
-(BOOL)_conformsToProtocolUIKeyInput;
-(BOOL)_containedInAbsoluteResponderChain;
-(BOOL)_containsResponder:(id)arg0 ;
-(BOOL)_disableAutomaticKeyboardBehavior;
-(BOOL)_disableAutomaticKeyboardUI;
-(BOOL)_enableAutomaticKeyboardPressDone;
-(BOOL)_finishResignFirstResponder;
-(BOOL)_handleActivityItemsConfigurationCanPerformAction:(SEL)arg0 sender:(id)arg1 ;
-(BOOL)_handleActivityItemsConfigurationDoesNotHandleSelector:(SEL)arg0 ;
-(BOOL)_handleActivityItemsConfigurationShare:(id)arg0 ;
-(BOOL)_hasMarkedText;
-(BOOL)_hasMarkedTextOrRangedSelection;
-(BOOL)_isEmptySelection;
-(BOOL)_isPinningInputViews;
-(BOOL)_isRootForKeyResponderCycle;
-(BOOL)_isTransitioningFromView:(id)arg0 ;
-(BOOL)_isView;
-(BOOL)_isViewController;
-(BOOL)_nextResponderChainContainsResponder:(id)arg0 ;
-(BOOL)_ownsInputAccessoryView;
-(BOOL)_range:(id)arg0 containsRange:(id)arg1 ;
-(BOOL)_range:(id)arg0 intersectsRange:(id)arg1 ;
-(BOOL)_range:(id)arg0 isEqualToRange:(id)arg1 ;
-(BOOL)_requiresKeyboardResetOnReload;
-(BOOL)_requiresKeyboardWhenFirstResponder;
-(BOOL)_requiresKeyboardWindowWhenFirstResponder;
-(BOOL)_resignIfContainsFirstResponder;
-(BOOL)_restoreFirstResponder;
-(BOOL)_selectionAtDocumentEnd;
-(BOOL)_selectionAtDocumentStart;
-(BOOL)_selectionAtWordStart;
-(BOOL)_shouldForwardMovementToFocusEngine:(NSInteger)arg0 ;
-(BOOL)_shouldPerformUICalloutBarButtonReplaceAction:(SEL)arg0 forText:(id)arg1 checkAutocorrection:(BOOL)arg2 ;
-(BOOL)_shouldRestorationInputViewsOnlyWhenKeepingFirstResponder;
-(BOOL)_shouldSkipKeyCommand:(id)arg0 forMovement:(NSInteger)arg1 ;
-(BOOL)_supportsBecomeFirstResponderWhenPossible;
-(BOOL)_suppressSoftwareKeyboard;
-(BOOL)_usesAsynchronousProtocol;
-(BOOL)_wantsPriorityOverFocusUpdates;
-(BOOL)becomeFirstResponder;
-(BOOL)canPasteItemProviders:(id)arg0 ;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)resignFirstResponder;
-(BOOL)shouldReloadInputViews;
-(NSInteger)_availableTextServices;
-(NSInteger)_dataOwnerForCopy;
-(NSInteger)_dataOwnerForPaste;
-(NSInteger)_dragDataOwner;
-(NSInteger)_dropDataOwner;
-(NSInteger)_opposingDirectionFromDirection:(NSInteger)arg0 ;
-(NSInteger)_selectionAffinity;
-(NSInteger)_textInputSource;
-(NSInteger)selectionAffinity;
-(id)__textInteractionFromAssistant;
-(id)_additionalTextInputLocales;
-(id)_asTextSelection;
-(id)_captureOverrideState;
-(id)_clampedpositionFromPosition:(id)arg0 offset:(int)arg1 ;
-(id)_currentOverrideClient;
-(id)_currentOverrideHost;
-(id)_deepestActionResponder;
-(id)_deepestUnambiguousResponder;
-(id)_effectiveActivityItemsConfiguration;
-(id)_effectiveActivityItemsConfigurationAtLocation:(struct CGPoint )arg0 inCoordinateSpace:(id)arg1 sender:(id)arg2 ;
-(id)_effectiveActivityItemsConfigurationForSender:(id)arg0 ;
-(id)_effectiveActivityItemsConfigurationForView:(id)arg0 location:(struct CGPoint )arg1 sender:(id)arg2 ;
-(id)_effectivePasteConfiguration;
-(id)_findPleasingWordBoundaryFromPosition:(id)arg0 ;
-(id)_firstNonnullActivityItemsConfigurationInResponderChainForLocation:(struct CGPoint )arg0 inCoordinateSpace:(id)arg1 skipPresentingViewControllers:(BOOL)arg2 sender:(id)arg3 target:(*id)arg4 ;
-(id)_firstNonnullActivityItemsConfigurationInResponderChainForView:(id)arg0 location:(struct CGPoint )arg1 sender:(id)arg2 responder:(*id)arg3 ;
-(id)_firstResponder;
-(id)_fontForCaretSelection;
-(id)_fullRange;
-(id)_fullText;
-(id)_intersectionOfRange:(id)arg0 andRange:(id)arg1 ;
-(id)_keyCommandForEvent:(id)arg0 ;
-(id)_keyCommandForEvent:(id)arg0 target:(*id)arg1 ;
-(id)_keyInput;
-(id)_keyboardResponder;
-(id)_moveDown:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveLeft:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveRight:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfDocument:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfLine:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfParagraph:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfWord:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfDocument:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfLine:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfParagraph:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfWord:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveUp:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_nextKeyResponder;
-(id)_nextResponderUsingTraversalStrategy:(NSUInteger)arg0 ;
-(id)_normalizedStringForRangeComparison:(id)arg0 ;
-(id)_overrideHost;
-(id)_positionAtStartOfWords:(NSUInteger)arg0 beforePosition:(id)arg1 ;
-(id)_positionFromPosition:(id)arg0 inDirection:(NSInteger)arg1 offset:(NSInteger)arg2 withAffinityDownstream:(BOOL)arg3 ;
-(id)_positionFromPosition:(id)arg0 pastTextUnit:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(id)_positionWithinRange:(id)arg0 farthestInDirection:(NSInteger)arg1 ;
-(id)_previousKeyResponder;
-(id)_primaryContentResponder;
-(id)_rangeFromCurrentRangeWithDelta:(struct _NSRange )arg0 ;
-(id)_rangeOfEnclosingWord:(id)arg0 ;
-(id)_rangeOfLineEnclosingPosition:(id)arg0 ;
-(id)_rangeOfParagraphEnclosingPosition:(id)arg0 ;
-(id)_rangeOfSentenceEnclosingPosition:(id)arg0 ;
-(id)_rangeOfSmartSelectionIncludingRange:(id)arg0 ;
-(id)_rangeOfText:(id)arg0 endingAtPosition:(id)arg1 ;
-(id)_rangeOfTextUnit:(NSInteger)arg0 enclosingPosition:(id)arg1 ;
-(id)_rangeSpanningTextUnit:(NSInteger)arg0 andPosition:(id)arg1 ;
-(id)_responderForBecomeFirstResponder;
-(id)_responderForEditing;
-(id)_responderSelectionContainerViewForResponder:(id)arg0 ;
-(id)_responderSelectionImage;
-(id)_responderWindow;
-(id)_selectableText;
-(id)_setHistory:(id)arg0 withExtending:(BOOL)arg1 withAnchor:(int)arg2 withAffinityDownstream:(BOOL)arg3 ;
-(id)_setSelectionRangeWithHistory:(id)arg0 ;
-(id)_showServiceForText:(id)arg0 selectedTextRange:(struct _NSRange )arg1 type:(NSInteger)arg2 fromRect:(struct CGRect )arg3 inView:(id)arg4 ;
-(id)_showServiceForText:(id)arg0 type:(NSInteger)arg1 fromRect:(struct CGRect )arg2 inView:(id)arg3 ;
-(id)_showServiceForType:(NSInteger)arg0 withContext:(id)arg1 ;
-(id)_targetCanPerformBlock:(id)arg0 ;
-(id)_textColorForCaretSelection;
-(id)_textInteraction;
-(id)_textRangeFromNSRange:(struct _NSRange )arg0 ;
-(id)_textServicesResponderProxy;
-(id)_window;
-(id)_wordContainingCaretSelection;
-(id)firstResponder;
-(id)interactionAssistant;
-(id)nextFirstResponder;
-(id)pasteConfiguration;
-(id)recentsAccessoryView;
-(id)targetForAction:(SEL)arg0 withSender:(id)arg1 ;
-(id)textInputSuggestionDelegate;
-(id)textInputView;
-(int)_indexForTextPosition:(id)arg0 ;
-(struct CGRect )_lastRectForRange:(id)arg0 ;
-(struct CGRect )_rectToScrollToVisibleInCellInWindow:(id)arg0 ;
-(struct CGRect )_responderExternalTouchRectForWindow:(id)arg0 ;
-(struct CGRect )_responderSelectionRectForWindow:(id)arg0 ;
-(struct CGRect )_selectionClipRect;
-(struct _NSRange )_nsrangeForTextRange:(id)arg0 ;
-(struct _NSRange )_selectedNSRange;
-(struct _NSRange )_selectedRangeWithinMarkedText;
-(unsigned int)_characterAfterCaretSelection;
-(unsigned int)_characterBeforeCaretSelection;
-(unsigned int)_characterInRelationToCaretSelection:(int)arg0 ;
-(unsigned int)_characterInRelationToPosition:(id)arg0 amount:(int)arg1 ;
-(unsigned int)_characterInRelationToRangedSelection:(int)arg0 ;
-(void)__createInteractionAssistantIfNecessaryWithMode:(NSInteger)arg0 ;
-(void)__prepareInteractionAssistantIfNecessary;
-(void)__tearDownInteractionAssistantIfNecessary;
-(void)_addShortcut:(id)arg0 ;
-(void)_becomeFirstResponder;
-(void)_becomeFirstResponderAndMakeVisible;
-(void)_beginPinningInputViews;
-(void)_checkIsText:(*BOOL)arg0 isSecure:(*BOOL)arg1 isEditable:(*BOOL)arg2 isFormatted:(*BOOL)arg3 ;
-(void)_clearBecomeFirstResponderWhenCapable;
-(void)_clearOverrideHost;
-(void)_clearOverrideNextResponder;
-(void)_clearRestorableResponderStatus;
-(void)_completeForwardingTouches:(id)arg0 phase:(NSInteger)arg1 event:(id)arg2 ;
-(void)_completeForwardingTouches:(id)arg0 phase:(NSInteger)arg1 event:(id)arg2 index:(NSUInteger)arg3 ;
-(void)_controlTouchBegan:(id)arg0 withEvent:(id)arg1 ;
-(void)_controlTouchEnded:(id)arg0 withEvent:(id)arg1 ;
-(void)_controlTouchMoved:(id)arg0 withEvent:(id)arg1 ;
-(void)_define:(id)arg0 ;
-(void)_deleteBackwardAndNotify:(BOOL)arg0 ;
-(void)_deleteByWord;
-(void)_deleteForwardAndNotify:(BOOL)arg0 ;
-(void)_deleteForwardByWord;
-(void)_deleteTextRange:(id)arg0 ;
-(void)_deleteToEndOfLine;
-(void)_deleteToEndOfParagraph;
-(void)_deleteToStartOfLine;
-(void)_didChangeDeepestActionResponder;
-(void)_didChangeDeepestUnambiguousResponder;
-(void)_didChangeToFirstResponder:(id)arg0 ;
-(void)_endPinningInputViews;
-(void)_enumerateKeyCommandsInChainWithOptions:(NSUInteger)arg0 usingBlock:(id)arg1 ;
-(void)_expandSelectionToBackwardDeletionCluster;
-(void)_expandSelectionToStartOfWordBeforeCaretSelection;
-(void)_expandSelectionToStartOfWordsBeforeCaretSelection:(int)arg0 ;
-(void)_extendCurrentSelection:(int)arg0 ;
// -(void)_gatherKeyResponders:(id)arg0 indexOfSelf:(*NSUInteger)arg1 visibilityTest:(id)arg2 passingTest:(unk)arg3 subviewsTest:(id)arg4  ;
-(void)_handleGameControllerEvent:(id)arg0 ;
-(void)_handleKeyEvent:(struct __GSEvent *)arg0 ;
-(void)_handleKeyUIEvent:(id)arg0 ;
-(void)_lookup:(id)arg0 ;
-(void)_moveCurrentSelection:(int)arg0 ;
-(void)_moveWithEvent:(id)arg0 ;
-(void)_nonDestructivelyResignFirstResponder;
-(void)_notifyFocusEngine;
-(void)_overrideInputAccessoryViewNextResponderWithResponder:(id)arg0 ;
-(void)_overrideInputViewNextResponderWithResponder:(id)arg0 ;
-(void)_overrideNextResponderWithResponder:(id)arg0 forType:(NSInteger)arg1 ;
-(void)_overrideRehostedViewControllerNextResponderWithResponder:(id)arg0 ;
-(void)_preserveResponderOverridesWhilePerforming:(id)arg0 ;
-(void)_rebuildStateRestorationIdentifierPath;
-(void)_replaceCurrentWordWithText:(id)arg0 ;
-(void)_replaceDocumentWithText:(id)arg0 ;
-(void)_resignFirstResponder;
-(void)_restoreOverrideState:(id)arg0 ;
-(void)_scrollRectToVisible:(struct CGRect )arg0 animated:(BOOL)arg1 ;
-(void)_selectAll;
-(void)_setAttributedMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)_setCaretSelectionAtEndOfSelection;
-(void)_setDataOwnerForCopy:(NSInteger)arg0 ;
-(void)_setDataOwnerForPaste:(NSInteger)arg0 ;
-(void)_setDragDataOwner:(NSInteger)arg0 ;
-(void)_setDropDataOwner:(NSInteger)arg0 ;
-(void)_setFirstResponder:(id)arg0 ;
-(void)_setGestureRecognizers;
-(void)_setKeyboardCameraSession:(id)arg0 ;
-(void)_setMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)_setSelectedTextRange:(id)arg0 withAffinityDownstream:(BOOL)arg1 ;
-(void)_setSelectionToPosition:(id)arg0 ;
-(void)_setSuppressSoftwareKeyboard:(BOOL)arg0 ;
-(void)_share:(id)arg0 ;
-(void)_tagAsRestorableResponder;
-(void)_translate:(id)arg0 ;
-(void)_transpose;
-(void)_unmarkText;
-(void)_updateSelectionWithTextRange:(id)arg0 withAffinityDownstream:(BOOL)arg1 ;
-(void)_wheelChangedWithEvent:(id)arg0 ;
-(void)_willChangeToFirstResponder:(id)arg0 ;
-(void)_windowBecameKey;
-(void)_windowResignedKey;
-(void)beginSelectionChange;
-(void)buildMenuWithBuilder:(id)arg0 ;
-(void)captureTextFromCamera:(id)arg0 ;
-(void)dealloc;
-(void)decodeRestorableStateWithCoder:(id)arg0 ;
-(void)doesNotRecognizeSelector:(SEL)arg0 ;
-(void)encodeRestorableStateWithCoder:(id)arg0 ;
-(void)endSelectionChange;
-(void)gestureChanged:(struct __GSEvent *)arg0 ;
-(void)gestureEnded:(struct __GSEvent *)arg0 ;
-(void)gestureStarted:(struct __GSEvent *)arg0 ;
-(void)motionBegan:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)motionCancelled:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)motionEnded:(NSInteger)arg0 withEvent:(id)arg1 ;
-(void)pasteItemProviders:(id)arg0 ;
-(void)pressesBegan:(id)arg0 withEvent:(id)arg1 ;
-(void)pressesCancelled:(id)arg0 withEvent:(id)arg1 ;
-(void)pressesChanged:(id)arg0 withEvent:(id)arg1 ;
-(void)pressesEnded:(id)arg0 withEvent:(id)arg1 ;
-(void)reloadInputViews;
-(void)reloadInputViewsWithoutReset;
-(void)remoteControlReceivedWithEvent:(id)arg0 ;
-(void)restoreUserActivityState:(id)arg0 ;
-(void)scrollWheel:(struct __GSEvent *)arg0 ;
-(void)setPasteConfiguration:(id)arg0 ;
-(void)set_textInputSource:(NSInteger)arg0 ;
-(void)touchesBegan:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesCancelled:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesEnded:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesEstimatedPropertiesUpdated:(id)arg0 ;
-(void)touchesMoved:(id)arg0 withEvent:(id)arg1 ;
-(void)updateTextAttributesWithConversionHandler:(id)arg0 ;
-(void)updateUserActivityState:(id)arg0 ;
-(void)validateCommand:(id)arg0 ;


@end


#endif