// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef UIWEBDOCUMENTVIEW_H
#define UIWEBDOCUMENTVIEW_H

@class WebView, DOMHTMLElement, CALayer, NSArray, PKScribbleInteraction, WebHistoryItem, NSIndexSet, RTIInputSystemSourceSession, NSString, NSURL, NSDictionary, DOMRange;
@protocol DDDetectionControllerInteractionDelegate, UIDragInteractionDelegate, UIDropInteractionDelegate, UIPreviewItemDelegate, _UIRotatingAlertControllerDelegate, UITextAutoscrolling, UIAutoscrollContainer, UIGestureRecognizerDelegate, UIKeyboardInput, UITextInputPrivate, UIKeyInput, UITextInputTokenizer, UITextInputMultiDocument, _UIWebDoubleTapDelegate, UIWebFileUploadPanelDelegate, WebEditingDelegate, WebFrameLoadDelegate, UITextInputDelegate, UITextInputSuggestionDelegate, UIWebDraggingDelegate;


#import "UIWebTiledView.h"
#import "UIAutoscroll.h"
#import "UITextInputTraits.h"
#import "UITapGestureRecognizer.h"
#import "_UIWebHighlightLongPressGestureRecognizer.h"
#import "UILongPressGestureRecognizer.h"
#import "UIPanGestureRecognizer.h"
#import "UIPreviewItemController.h"
#import "_UIWebViewportHandler.h"
#import "WebThreadSafeUndoManager.h"
#import "UITextInteractionAssistant.h"
#import "UITextChecker.h"
#import "UIWebFileUploadPanel.h"
#import "UIWebTextPlaceholder.h"
#import "UIWebPlaybackTargetPicker.h"
#import "_UITextDragCaretView.h"
#import "_UITextServiceSession.h"
#import "UITextPosition.h"
#import "UIDragInteraction.h"
#import "UIDropInteraction.h"
#import "UIView.h"
#import "UIInputContextHistory.h"
#import "UIColor.h"
#import "UITextRange.h"
#import "UITextInputPasswordRules.h"
#import "UIImage.h"
#import "_UISupplementalLexicon.h"

@interface UIWebDocumentView : UIWebTiledView <DDDetectionControllerInteractionDelegate, UIDragInteractionDelegate, UIDropInteractionDelegate, UIPreviewItemDelegate, _UIRotatingAlertControllerDelegate, UITextAutoscrolling, UIAutoscrollContainer, UIGestureRecognizerDelegate, UIKeyboardInput, UITextInputPrivate, UIKeyInput, UITextInputTokenizer, UITextInputMultiDocument, _UIWebDoubleTapDelegate, UIWebFileUploadPanelDelegate, WebEditingDelegate, WebFrameLoadDelegate>

 {
    WebView *_webView;
    id *m_parentTextView;
    id *_delegate;
    id *_textSuggestionDelegate;
    CGRect _doubleTapRect;
    CGRect _mainDocumentDoubleTapRect;
    CGPoint _scrollPoint;
    CGPoint _doubleTapStartPosition;
    CGFloat _doubleTapStartTime;
    CGSize _pendingSize;
    NSInteger _orientation;
    DOMHTMLElement *_standaloneEditingElement;
    CGPoint _mouseDownPoint;
    CGFloat _mouseDownTime;
    UIAutoscroll *_autoscroll;
    *__CFDictionary _plugInViews;
    NSInteger m_selectionGranularity;
    CALayer *_contentLayersHostingLayer;
    CALayer *_flattenedRotatingContentLayer;
    NSArray *_additionalSubviews;
    UITextInputTraits *_traits;
    id<UITextInputDelegate> *_inputDelegate;
    UITapGestureRecognizer *_singleTapGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    UITapGestureRecognizer *_twoFingerDoubleTapGestureRecognizer;
    _UIWebHighlightLongPressGestureRecognizer *_highlightLongPressGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UIPanGestureRecognizer *_twoFingerPanGestureRecognizer;
    UILongPressGestureRecognizer *_previewGestureRecognizer;
    UILongPressGestureRecognizer *_previewSecondaryGestureRecognizer;
    BOOL _panGestureWasEnabled;
    BOOL _pinchGestureWasEnabled;
    UIPreviewItemController *_previewItemController;
    ? _interaction;
    _UIWebViewportHandler *_viewportHandler;
    int _documentType;
    float _documentScale;
    float _previousDocumentScale;
    CGSize _fixedLayoutOriginRoundingDelta;
    CGSize _fixedLayoutSizeRoundingDelta;
    unsigned int _mouseDownCount;
    unsigned int _printModeCount;
    NSUInteger _dataDetectorTypes;
    BOOL _webCoreNeedsSetNeedsDisplay;
    BOOL _webCoreNeedsDraw;
    BOOL _ignoresFocusingMouse;
    BOOL _ignoresKeyEvents;
    BOOL _autoresizes;
    BOOL _ignoresViewportOverflowWhenAutoresizing;
    BOOL _shouldIgnoreCustomViewport;
    BOOL _updatingSize;
    BOOL _scalesToFit;
    BOOL _alwaysConstrainsScale;
    BOOL _updatesScrollView;
    BOOL _hasCustomScale;
    BOOL _shouldRestoreScrollPosition;
    BOOL _pageNeedsReset;
    BOOL _hasScrollPoint;
    BOOL _gesturesDisabled;
    BOOL _doubleTapRectIsReplaced;
    BOOL _standaloneEditableView;
    BOOL _widgetEditingView;
    BOOL _mouseDragged;
    BOOL _mouseReentrancyGuard;
    BOOL _isShowingFullScreenPlugIn;
    BOOL _isSettingRedrawFrame;
    BOOL _needsScrollNotifications;
    BOOL _loadsSynchronously;
    BOOL _mouseDown;
    BOOL _geolocationDialogAllowed;
    BOOL _usingMinimalTilesDuringLoading;
    BOOL _sheetsCount;
    BOOL _didFirstVisuallyNonEmptyLayout;
    BOOL _loadInProgress;
    BOOL _uiwdvIsResigningFirstResponder;
    BOOL _sizeUpdatesSuspended;
    BOOL _sizeUpdateOccurredWhileSuspended;
    BOOL _shouldOnlyRecognizeGesturesOnActiveElements;
    BOOL _ignoresFocusEventFromFirstResponderChange;
    BOOL _shouldCloseWebViewAtDealloc;
    BOOL _shouldRemoveUserStyleSheet;
    BOOL _hasDrawnTiles;
    BOOL _showingTextStyleOptions;
    BOOL _subviewCachesNeedUpdate;
    BOOL _avoidFixedPositionUpdateViaDidScroll;
    BOOL _inspectorSearchingForNode;
    BOOL _previousScrollWasScrollToTop;
    BOOL _pageIsLoadedFromPageCache;
    BOOL _shouldSendWillShowInteractionHighlight;
    WebThreadSafeUndoManager *_undoManager;
    UITextInteractionAssistant *_textSelectionAssistant;
    UITextChecker *_textChecker;
    UIEdgeInsets _caretInsets;
    UIWebFileUploadPanel *_fileUploadPanel;
    int _selectionAffinity;
    UIWebTextPlaceholder *_textPlaceholder;
    id *_textPlaceholderRemovalObserver;
    UIWebPlaybackTargetPicker *_playbackTargetPicker;
    CGRect _currentDragCaretRect;
    _UITextDragCaretView *_textDragCaretView;
    CGRect _currentDragBoundingRect;
    BOOL _isPerformingDrop;
    BOOL _didEndDropSession;
    BOOL _didCreateDropPreview;
    PKScribbleInteraction *_scribbleInteraction;
    _UIWebViewportConfiguration _defaultViewportConfigurations;
    _UITextServiceSession *_definitionSession;
    _UITextServiceSession *_learnSession;
    _UITextServiceSession *_shareSession;
    _UITextServiceSession *_lookupSession;
    _UITextServiceSession *_translateSession;
    WebHistoryItem *_latestCommittedPageLoadHistoryItem;
}


@property (copy, nonatomic) NSIndexSet *PINEntrySeparatorIndexes;
@property (getter=_acceptsFirstResponder, setter=_setAcceptsFirstResponder:) BOOL _acceptsFirstResponder;
@property (readonly, nonatomic) RTIInputSystemSourceSession *_rtiSourceSession;
@property (nonatomic) NSInteger _textInputSource;
@property (nonatomic) BOOL acceptsDictationSearchResults;
@property (nonatomic) BOOL acceptsEmoji;
@property (nonatomic) BOOL acceptsFloatingKeyboard;
@property (nonatomic) BOOL acceptsInitialEmojiKeyboard;
@property (nonatomic) BOOL acceptsPayloads;
@property (nonatomic) BOOL acceptsSplitKeyboard;
@property (nonatomic) BOOL alwaysConstrainsScale;
@property (nonatomic) NSInteger autocapitalizationType;
@property (copy, nonatomic) NSString *autocorrectionContext;
@property (nonatomic) NSInteger autocorrectionType;
@property (nonatomic) CGPoint autoscrollContentOffset;
@property (readonly, nonatomic) UITextPosition *beginningOfDocument;
@property (nonatomic) BOOL contentsIsSingleValue;
@property (nonatomic) CGRect currentDragCaretRect;
@property (nonatomic) NSUInteger currentDragSourceAction; // ivar: _currentDragSourceAction
@property (readonly, nonatomic) NSInteger cursorBehavior;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL deferBecomingResponder;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (nonatomic, getter=isDevicePasscodeEntry) BOOL devicePasscodeEntry;
@property (nonatomic) BOOL disableHandwritingKeyboard;
@property (nonatomic) BOOL disableInputBars;
@property (nonatomic) BOOL disablePrediction;
@property (nonatomic) BOOL displaySecureEditsUsingPlainText;
@property (nonatomic) BOOL displaySecureTextUsingPlainText;
@property (nonatomic, getter=isDoubleTapEnabled) BOOL doubleTapEnabled;
@property (retain, nonatomic) UIDragInteraction *dragInteraction; // ivar: _dragInteraction
@property (retain, nonatomic) NSString *draggedLinkTitle; // ivar: _draggedLinkTitle
@property (retain, nonatomic) NSURL *draggedLinkURL; // ivar: _draggedLinkURL
@property (retain, nonatomic) UIDropInteraction *dropInteraction; // ivar: _dropInteraction
@property (nonatomic) int emptyContentReturnKeyType;
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic) BOOL enablesReturnKeyOnNonWhiteSpaceContent;
@property (readonly, nonatomic) UITextPosition *endOfDocument;
@property (nonatomic) CGRect exposedScrollViewRect; // ivar: _exposedScrollViewRect
@property (nonatomic) UIEdgeInsets floatingKeyboardEdgeInsets;
@property (nonatomic) BOOL forceDefaultDictationInfo;
@property (nonatomic) NSInteger forceDictationKeyboardType;
@property (nonatomic) BOOL forceDisableDictation;
@property (nonatomic) BOOL forceEnableDictation;
@property (nonatomic) BOOL forceFloatingKeyboard;
@property (nonatomic) BOOL hasDefaultContents;
@property (readonly, nonatomic) BOOL hasText;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (nonatomic) BOOL hidePrediction;
@property (retain, nonatomic) UIView *initialDropSnapshotView; // ivar: _initialDropSnapshotView
@property (retain, nonatomic) UIInputContextHistory *inputContextHistory;
@property (weak, nonatomic) NSObject<UITextInputDelegate> *inputDelegate;
@property (readonly, nonatomic) id *insertDictationResultPlaceholder;
@property (retain, nonatomic) UIColor *insertionPointColor;
@property (nonatomic) NSUInteger insertionPointWidth;
@property (readonly, nonatomic) UITextInteractionAssistant *interactionAssistant;
@property (nonatomic) BOOL isCarPlayIdiom;
@property (nonatomic) BOOL isSingleLineDocument;
@property (nonatomic) NSInteger keyboardAppearance;
@property (nonatomic) NSInteger keyboardType;
@property (nonatomic) CGPoint lastGlobalPosition; // ivar: _lastGlobalPosition
@property (nonatomic) BOOL learnsCorrections;
@property (nonatomic) BOOL loadKeyboardsForSiriLanguage;
@property (readonly, nonatomic) UITextRange *markedTextRange;
@property (copy, nonatomic) NSDictionary *markedTextStyle;
@property (nonatomic) BOOL mediaPlaybackAllowsAirPlay;
@property (copy, nonatomic) UITextInputPasswordRules *passwordRules;
@property (nonatomic) BOOL preferOnlineDictation;
@property (nonatomic) NSInteger preferredKeyboardStyle;
@property (retain, nonatomic) DOMRange *rangeToRestoreAfterDictation; // ivar: _rangeToRestoreAfterDictation
@property (copy, nonatomic) NSString *recentInputIdentifier;
@property (readonly, nonatomic) NSUInteger renderTreeSize; // ivar: _renderTreeSize
@property (nonatomic) NSUInteger renderTreeSizeThresholdForReset; // ivar: _renderTreeSizeThresholdForReset
@property (copy, nonatomic) NSString *responseContext;
@property (nonatomic) BOOL returnKeyGoesToNextResponder;
@property (nonatomic) NSInteger returnKeyType;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (copy) UITextRange *selectedTextRange;
@property (nonatomic) NSInteger selectionAffinity;
@property (retain, nonatomic) UIColor *selectionBarColor;
@property (retain, nonatomic) UIColor *selectionBorderColor;
@property (nonatomic) CGFloat selectionBorderWidth;
@property (nonatomic) CGFloat selectionCornerRadius;
@property (retain, nonatomic) UIImage *selectionDragDotImage;
@property (nonatomic) UIEdgeInsets selectionEdgeInsets;
@property (nonatomic) NSInteger selectionGranularity;
@property (retain, nonatomic) UIColor *selectionHighlightColor;
@property (readonly, nonatomic) int selectionState;
@property (nonatomic) int shortcutConversionType;
@property (nonatomic) BOOL shouldAutoscroll;
@property (nonatomic) BOOL shouldIgnoreCustomViewport;
@property (nonatomic) BOOL shouldOnlyRecognizeGesturesOnActiveElements;
@property (nonatomic) BOOL showDictationButton;
@property (nonatomic) BOOL sizeUpdatesSuspended;
@property (nonatomic) NSInteger smartDashesType;
@property (nonatomic) NSInteger smartInsertDeleteType;
@property (nonatomic) NSInteger smartQuotesType;
@property (nonatomic) NSInteger spellCheckingType;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (retain, nonatomic) _UISupplementalLexicon *supplementalLexicon;
@property (retain, nonatomic) UIImage *supplementalLexiconAmbiguousItemIcon;
@property (readonly, nonatomic) BOOL supportsImagePaste;
@property (nonatomic) BOOL suppressReturnKeyStyling;
@property (nonatomic) BOOL suppressesIncrementalRendering; // ivar: _suppressesIncrementalRendering
@property (copy, nonatomic) NSString *textContentType;
@property (readonly, nonatomic) NSObject<UITextInputSuggestionDelegate> *textInputSuggestionDelegate;
@property (readonly, nonatomic) UIView *textInputView;
@property (nonatomic) int textLoupeVisibility;
@property (readonly, nonatomic) UITextRange *textRangeForServicesInteraction;
@property (nonatomic) NSInteger textScriptType;
@property (nonatomic) int textSelectionBehavior;
@property (nonatomic) id *textSuggestionDelegate;
@property (nonatomic) *__CFCharacterSet textTrimmingSet;
@property (readonly, nonatomic) NSObject<UITextInputTokenizer> *tokenizer;
@property (retain, nonatomic) UIColor *underlineColorForSpelling;
@property (retain, nonatomic) UIColor *underlineColorForTextAlternatives;
@property (nonatomic) BOOL useAutomaticEndpointing;
@property (nonatomic) BOOL useInterfaceLanguageForLocalization;
@property (nonatomic) _NSRange validTextRange;
@property (readonly, nonatomic) BOOL wantsMinimalUI; // ivar: _wantsMinimalUI
@property (nonatomic) NSObject<UIWebDraggingDelegate> *webDraggingDelegate; // ivar: _webDraggingDelegate


+(BOOL)hasLandscapeOrientation;
+(CGFloat)getTimestamp;
+(Class)layerClass;
+(id)_createDefaultHighlightView;
+(id)_sharedHighlightView;
+(id)standardTextViewPreferences;
+(void)initialize;
-(*void)_createIOSurfaceFromRect:(struct CGRect )arg0 ;
-(BOOL)_dataDetectionIsActivated;
-(BOOL)_dragInteraction:(id)arg0 sessionSupportsSystemDrag:(id)arg1 ;
-(BOOL)_handleSingleTapZoomPreClickAtLocation:(struct CGPoint )arg0 ;
-(BOOL)_insertFragmentWithoutPreservingStyle:(id)arg0 atDestination:(id)arg1 smartReplace:(BOOL)arg2 collapseToEnd:(BOOL)arg3 ;
-(BOOL)_interactionShouldBeginFromPreviewItemController:(id)arg0 forPosition:(struct CGPoint )arg1 ;
-(BOOL)_isDisplayingLookupViewController;
-(BOOL)_isDisplayingReferenceLibraryViewController;
-(BOOL)_isDisplayingShareViewController;
-(BOOL)_isDisplayingShortcutViewController;
-(BOOL)_isDisplayingTranslateViewController;
-(BOOL)_isInspectorSearchingForNode;
-(BOOL)_isSubviewOfPlugInView:(id)arg0 ;
-(BOOL)_presentViewController:(id)arg0 animated:(BOOL)arg1 completion:(id)arg2 ;
-(BOOL)_previewAllowedForPosition:(struct CGPoint )arg0 ;
-(BOOL)_restoreFirstResponder;
-(BOOL)_shouldFlattenContentLayersForRect:(struct CGRect )arg0 ;
-(BOOL)_shouldPaste;
-(BOOL)_shouldResetForNewPage;
-(BOOL)_shouldUpdateSubviewCachesForPlugins;
-(BOOL)_textPlaceholderHasBeenRemoved;
-(BOOL)becomeFirstResponder;
-(BOOL)becomesEditableWithGestures;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)canResignFirstResponder;
-(BOOL)cancelMouseTracking;
-(BOOL)cancelTouchTracking;
-(BOOL)clearWKFirstResponder;
-(BOOL)considerHeightForDoubleTap;
-(BOOL)detectsPhoneNumbers;
-(BOOL)didFirstVisuallyNonEmptyLayout;
-(BOOL)doubleTapRectIsReplaced;
-(BOOL)fragmentContainsRichContent:(id)arg0 ;
-(BOOL)gestureRecognizer:(id)arg0 canBePreventedByGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 canPreventGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldReceiveTouch:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg0 ;
-(BOOL)handleKeyAppCommandForCurrentEvent;
-(BOOL)handleKeyTextCommandForCurrentEvent;
-(BOOL)hasBodyElement;
-(BOOL)hasContent;
-(BOOL)hasDrawnTiles;
-(BOOL)hasEditableSelection;
-(BOOL)hasMarkedText;
-(BOOL)hasPlugInSubviews;
-(BOOL)hasRangedSelection;
-(BOOL)hasRichlyEditableSelection;
-(BOOL)hasSelection;
-(BOOL)inPopover;
-(BOOL)isCaretInEmptyParagraph;
-(BOOL)isClassicViewportMode;
-(BOOL)isEditable;
-(BOOL)isEditing;
-(BOOL)isEditingSingleLineElement;
-(BOOL)isInInteraction;
-(BOOL)isInPrintMode;
-(BOOL)isInsideRichlyEditableTextWidget;
-(BOOL)isPosition:(id)arg0 atBoundary:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(BOOL)isPosition:(id)arg0 withinTextUnit:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(BOOL)isPreviewing;
-(BOOL)isShowingFullScreenPlugInUI;
-(BOOL)isStandaloneEditableView;
-(BOOL)isWidgetEditingView;
-(BOOL)keyboardInput:(id)arg0 shouldInsertText:(id)arg1 isMarkedText:(BOOL)arg2 ;
-(BOOL)keyboardInput:(id)arg0 shouldReplaceTextInRange:(struct _NSRange )arg1 replacementText:(id)arg2 ;
-(BOOL)keyboardInputChanged:(id)arg0 ;
-(BOOL)keyboardInputShouldDelete:(id)arg0 ;
-(BOOL)loadsSynchronously;
-(BOOL)makeWKFirstResponder;
-(BOOL)mouseEventsChangeSelection;
-(BOOL)needsScrollNotifications;
-(BOOL)performTwoStepDrop:(id)arg0 atDestination:(id)arg1 isMove:(BOOL)arg2 ;
-(BOOL)performsTwoStepPaste:(id)arg0 ;
-(BOOL)playsNicelyWithGestures;
-(BOOL)requiresKeyEvents;
-(BOOL)resignFirstResponder;
-(BOOL)selectionAtDocumentStart;
-(BOOL)selectionAtWordStart;
-(BOOL)setRangedSelectionExtentPoint:(struct CGPoint )arg0 baseIsStart:(BOOL)arg1 ;
-(BOOL)shouldRevealCurrentSelectionAfterInsertion;
-(BOOL)shouldSelectionAssistantReceiveDoubleTapAtPoint:(struct CGPoint )arg0 forScale:(CGFloat)arg1 ;
-(BOOL)shouldSuppressPasswordEcho;
-(BOOL)startActionSheet;
-(BOOL)supportsTwoFingerScrollingAtTouchLocation:(struct CGPoint )arg0 andLocation:(struct CGPoint )arg1 ;
-(BOOL)updateKeyboardStateOnResponderChanges;
-(BOOL)updatesScrollView;
-(BOOL)webView:(id)arg0 shouldScrollToPoint:(struct CGPoint )arg1 forFrame:(id)arg2 ;
-(BOOL)willInteractWithLocation:(struct CGPoint )arg0 ;
-(CGFloat)_zoomedDocumentScale;
-(CGFloat)currentDocumentScale;
-(CGFloat)maximumDoubleTapScale;
-(CGFloat)minimumScaleForSize:(struct CGSize )arg0 ;
-(CGFloat)zoomedDocumentScale;
-(Class)_printFormatterClass;
-(NSInteger)_dragInteraction:(id)arg0 dataOwnerForAddingToSession:(id)arg1 withTouchAtPoint:(struct CGPoint )arg2 ;
-(NSInteger)_dragInteraction:(id)arg0 dataOwnerForSession:(id)arg1 ;
-(NSInteger)_dropInteraction:(id)arg0 dataOwnerForSession:(id)arg1 ;
-(NSInteger)baseWritingDirectionForPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(NSInteger)comparePosition:(id)arg0 toPosition:(id)arg1 ;
-(NSInteger)getPasteboardChangeCount;
-(NSInteger)getPasteboardItemsCount;
-(NSInteger)offsetFromPosition:(id)arg0 toPosition:(id)arg1 ;
-(NSInteger)selectionBaseWritingDirection;
-(NSUInteger)dataDetectorTypes;
-(NSUInteger)effectiveDataDetectorTypes;
-(NSUInteger)offsetInMarkedTextForSelection:(id)arg0 ;
-(SEL)_actionForLongPressOnElement:(id)arg0 ;
-(float)_documentScale;
-(float)initialScale;
-(float)maximumScale;
-(float)minimumScale;
-(float)minimumScaleForMinimumSize:(struct CGSize )arg0 ;
-(id)_beginPrintModeForHTMLView:(id)arg0 withSize:(struct CGSize )arg1 startOffset:(CGFloat)arg2 minimumLayoutWidth:(CGFloat)arg3 maximumLayoutWidth:(CGFloat)arg4 tileClippedContent:(BOOL)arg5 ;
-(id)_beginPrintModeForPDFView:(id)arg0 withSize:(struct CGSize )arg1 startOffset:(CGFloat)arg2 minimumLayoutWidth:(CGFloat)arg3 maximumLayoutWidth:(CGFloat)arg4 ;
-(id)_collectAdditionalSubviews;
-(id)_dataForPreviewItemController:(id)arg0 atPosition:(struct CGPoint )arg1 type:(*NSInteger)arg2 ;
-(id)_documentUrl;
-(id)_doubleTapGestureRecognizer;
-(id)_focusedOrMainFrame;
-(id)_groupName;
-(id)_insertTextPlaceholderWithSize:(struct CGSize )arg0 ;
-(id)_parentTextView;
-(id)_positionFromPosition:(id)arg0 inDirection:(NSInteger)arg1 offset:(NSInteger)arg2 withAffinityDownstream:(BOOL)arg3 ;
-(id)_presentationRectsForPreview;
-(id)_presentationRectsForPreviewItemController:(id)arg0 ;
-(id)_presentationSnapshotForPreview;
-(id)_presentationSnapshotForPreviewItemController:(id)arg0 ;
-(id)_presentedViewControllerForPreviewItemController:(id)arg0 ;
-(id)_responderForBecomeFirstResponder;
-(id)_supportedPasteboardTypesForCurrentSelection;
-(id)_targetURL;
-(id)_textSelectingContainer;
-(id)approximateNodeAtViewportLocation:(struct CGPoint *)arg0 ;
-(id)asText;
-(id)automaticallySelectedOverlay;
-(id)beginPrintModeForFrame:(id)arg0 withSize:(struct CGSize )arg1 startOffset:(CGFloat)arg2 minimumLayoutWidth:(CGFloat)arg3 maximumLayoutWidth:(CGFloat)arg4 tileClippedContent:(BOOL)arg5 ;
-(id)beginPrintModeForFrame:(id)arg0 withWidth:(CGFloat)arg1 height:(CGFloat)arg2 startOffset:(CGFloat)arg3 shrinkToFit:(BOOL)arg4 tileClippedContent:(BOOL)arg5 ;
-(id)beginPrintModeWithSize:(struct CGSize )arg0 startOffset:(CGFloat)arg1 minimumLayoutWidth:(CGFloat)arg2 maximumLayoutWidth:(CGFloat)arg3 tileClippedContent:(BOOL)arg4 ;
-(id)beginPrintModeWithWidth:(CGFloat)arg0 height:(CGFloat)arg1 startOffset:(CGFloat)arg2 shrinkToFit:(BOOL)arg3 forFrame:(id)arg4 ;
-(id)beginPrintModeWithWidth:(CGFloat)arg0 height:(CGFloat)arg1 startOffset:(CGFloat)arg2 shrinkToFit:(BOOL)arg3 tileClippedContent:(BOOL)arg4 forFrame:(id)arg5 ;
-(id)characterRangeAtPoint:(struct CGPoint )arg0 ;
-(id)characterRangeByExtendingPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(id)checkSpellingOfString:(id)arg0 ;
-(id)closestPositionToPoint:(struct CGPoint )arg0 ;
-(id)closestPositionToPoint:(struct CGPoint )arg0 withinRange:(id)arg1 ;
-(id)contentView;
-(id)deepestNodeAtViewportLocation:(struct CGPoint )arg0 ;
-(id)delegate;
-(id)dictationInterpretations;
-(id)dictationResultMetadataForRange:(id)arg0 ;
-(id)dragInteraction:(id)arg0 itemsForBeginningSession:(id)arg1 ;
-(id)dragInteraction:(id)arg0 previewForCancellingItem:(id)arg1 withDefault:(id)arg2 ;
-(id)dragInteraction:(id)arg0 previewForLiftingItem:(id)arg1 session:(id)arg2 ;
-(id)dropInteraction:(id)arg0 previewForDroppingItem:(id)arg1 withDefault:(id)arg2 ;
-(id)dropInteraction:(id)arg0 sessionDidUpdate:(id)arg1 ;
-(id)editDragPreviewForTextIndicator:(id)arg0 ;
-(id)enclosingScrollView;
-(id)fallbackDropPreviewForUninsertedContent:(id)arg0 ;
-(id)fontForCaretSelection;
-(id)formElement;
-(id)hostViewForSheet:(id)arg0 ;
-(id)implementationWebView;
-(id)initSimpleHTMLDocumentWithStyle:(id)arg0 frame:(struct CGRect )arg1 preferences:(id)arg2 groupName:(id)arg3 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)initWithWebView:(id)arg0 frame:(struct CGRect )arg1 ;
-(id)insertTextPlaceholderWithSize:(struct CGSize )arg0 ;
-(id)interactionDelegate;
-(id)interactionElement;
-(id)metadataDictionariesForDictationResults;
-(id)methodSignatureForSelector:(SEL)arg0 ;
-(id)newMouseEvent:(int)arg0 ;
-(id)positionAtStartOrEndOfWord:(id)arg0 ;
-(id)positionFromPosition:(id)arg0 inDirection:(NSInteger)arg1 offset:(NSInteger)arg2 ;
-(id)positionFromPosition:(id)arg0 offset:(NSInteger)arg1 ;
-(id)positionFromPosition:(id)arg0 toBoundary:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(id)positionWithinRange:(id)arg0 farthestInDirection:(NSInteger)arg1 ;
-(id)rangeByExtendingCurrentSelection:(int)arg0 ;
-(id)rangeByMovingCurrentSelection:(int)arg0 ;
-(id)rangeEnclosingPosition:(id)arg0 withGranularity:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(id)rangeOfEnclosingWord:(id)arg0 ;
-(id)readDataFromPasteboard:(id)arg0 withIndex:(NSInteger)arg1 ;
-(id)rectsForNSRange:(struct _NSRange )arg0 ;
-(id)selectedDOMRange;
-(id)selectionRects;
-(id)selectionRectsForDOMRange:(id)arg0 ;
-(id)selectionRectsForRange:(id)arg0 ;
-(id)selectionView;
-(id)standaloneEditingElement;
-(id)subviews;
-(id)superviewForSheet;
-(id)supportedPasteboardTypesForCurrentSelection;
-(id)targetedDragPreviewFromCurrentTextIndicatorData;
-(id)text;
-(id)textColorForCaretSelection;
-(id)textFormElement;
-(id)textInDOMRange:(id)arg0 ;
-(id)textInRange:(id)arg0 ;
-(id)textInputTraits;
-(id)textRangeFromPosition:(id)arg0 toPosition:(id)arg1 ;
-(id)textStylingAtPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(id)undoManager;
-(id)undoManagerForWebView:(id)arg0 ;
-(id)webView;
-(id)webView:(id)arg0 plugInViewWithArguments:(id)arg1 fromPlugInPackage:(id)arg2 ;
-(id)webVisiblePositionForPoint:(struct CGPoint )arg0 ;
-(id)wordAtPoint:(struct CGPoint )arg0 ;
-(int)deviceOrientation;
-(int)documentType;
-(int)wordOffsetInRange:(id)arg0 ;
-(struct ? )doubleTapScalesForSize:(struct CGSize )arg0 ;
-(struct CGImage *)newSnapshotWithRect:(struct CGRect )arg0 ;
-(struct CGPoint )constrainedPoint:(struct CGPoint )arg0 ;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 fromFrame:(id)arg1 ;
-(struct CGPoint )convertPoint:(struct CGPoint )arg0 toFrame:(id)arg1 ;
-(struct CGPoint )convertPointToSelectedFrameCoordinates:(struct CGPoint )arg0 ;
-(struct CGPoint )interactionLocation;
-(struct CGRect )_adjustedLayoutRectForFixedPositionObjects;
-(struct CGRect )_documentViewVisibleRect;
-(struct CGRect )_lastRectForRange:(id)arg0 ;
-(struct CGRect )_layoutRectForFixedPositionObjects;
-(struct CGRect )_presentationRectForSheetGivenPoint:(struct CGPoint )arg0 inHostView:(id)arg1 ;
-(struct CGRect )_scribbleInteraction:(id)arg0 frameForElement:(id)arg1 ;
-(struct CGRect )_selectionClipRect;
-(struct CGRect )_shortcutPresentationRect;
-(struct CGRect )autoscrollContentFrame;
-(struct CGRect )autoscrollDragFrame;
-(struct CGRect )caretRect;
-(struct CGRect )caretRectForPosition:(id)arg0 ;
-(struct CGRect )caretRectForVisiblePosition:(id)arg0 ;
-(struct CGRect )closestCaretRectInMarkedTextRangeForPoint:(struct CGPoint )arg0 ;
-(struct CGRect )computeRectForElement:(id)arg0 withHighligh:(id)arg1 isInverted:(BOOL)arg2 ;
-(struct CGRect )contentFrameForView:(id)arg0 ;
-(struct CGRect )convertCaretRect:(struct CGRect )arg0 ;
-(struct CGRect )convertRect:(struct CGRect )arg0 fromFrame:(id)arg1 ;
-(struct CGRect )convertRect:(struct CGRect )arg0 toFrame:(id)arg1 ;
-(struct CGRect )convertRectFromSelectedFrameCoordinates:(struct CGRect )arg0 ;
-(struct CGRect )convertRectWithDocumentScale:(struct CGRect )arg0 ;
-(struct CGRect )documentBounds;
-(struct CGRect )doubleTapRect;
-(struct CGRect )firstRectForRange:(id)arg0 ;
-(struct CGRect )frameForDictationResultPlaceholder:(id)arg0 ;
-(struct CGRect )initialPresentationRectInHostViewForSheet:(id)arg0 ;
-(struct CGRect )presentationRectInHostViewForSheet:(id)arg0 ;
-(struct CGRect )rectOfInterestForPoint:(struct CGPoint )arg0 ;
-(struct CGRect )visibleBounds;
-(struct CGRect )visibleContentFrame;
-(struct CGRect )visibleContentRect;
-(struct CGRect )visibleFrame;
-(struct CGRect )webViewFrameForUIFrame:(struct CGRect )arg0 ;
-(struct CGSize )_sizeForDictationResultPlaceholder;
-(struct UIEdgeInsets )caretInsets;
-(struct _NSRange )selectionRange;
-(unsigned int)_contentSizeInExposedRect:(struct CGRect )arg0 topLayer:(id)arg1 visibleLayerCount:(*int)arg2 ;
-(unsigned short)characterAfterCaretSelection;
-(unsigned short)characterInRelationToCaretSelection:(int)arg0 ;
-(void)_WAKViewSizeDidChange:(id)arg0 ;
-(void)_addShortcut:(id)arg0 ;
-(void)_appendOpenActionsForURL:(id)arg0 actions:(id)arg1 ;
-(void)_applyViewportArguments:(id)arg0 ;
-(void)_cancelLongPressGestureRecognizer;
-(void)_cleanUpFrameStateAndLoad:(id)arg0 ;
-(void)_cleanupSheet;
-(void)_clearAllConsoleMessages;
-(void)_clearDoubleTapRect;
-(void)_clearPreviewRevealInformation;
-(void)_collectPreviewRevealInformationIfNeeded;
-(void)_createSheetWithElementActions:(id)arg0 showLinkTitle:(BOOL)arg1 ;
-(void)_define:(id)arg0 ;
-(void)_didChangeDragCaretRectFromRect:(struct CGRect )arg0 toRect:(struct CGRect )arg1 ;
-(void)_didDismissElementSheet;
-(void)_didMoveFromWindow:(id)arg0 toWindow:(id)arg1 ;
-(void)_didScroll;
-(void)_dismissViewControllerAnimated:(BOOL)arg0 completion:(id)arg1 ;
-(void)_doubleTapRecognized:(id)arg0 ;
-(void)_drawPDFPagesForPage:(NSUInteger)arg0 withPaginationInfo:(id)arg1 ;
-(void)_editableSelectionLayoutChangedByScrolling:(BOOL)arg0 ;
-(void)_endPrintMode;
-(void)_finishedUsingTextPlaceholder;
-(void)_flattenAndSwapContentLayersInRect:(struct CGRect )arg0 ;
-(void)_focusAndAssistFormNode:(id)arg0 ;
-(void)_handleDoubleTapAtLocation:(struct CGPoint )arg0 ;
-(void)_handleSingleTapZoomPostClickAtLocation:(struct CGPoint )arg0 ;
-(void)_handleTwoFingerDoubleTapAtLocation:(struct CGPoint )arg0 ;
-(void)_highlightLongPressRecognized:(id)arg0 ;
-(void)_insertAttributedTextWithoutClosingTyping:(id)arg0 ;
-(void)_inspectorDidStartSearchingForNode:(id)arg0 ;
-(void)_inspectorDidStopSearchingForNode:(id)arg0 ;
-(void)_interactionStartedFromPreviewItemController:(id)arg0 ;
-(void)_interactionStoppedFromPreviewItemController:(id)arg0 ;
-(void)_longPressRecognized:(id)arg0 ;
-(void)_notifyContentHostingLayersOfScaleChange;
-(void)_notifyPlugInViewsOfDidEndZooming;
-(void)_notifyPlugInViewsOfDidZoom;
-(void)_notifyPlugInViewsOfScaleChange;
-(void)_notifyPlugInViewsOfWillBeginZooming;
-(void)_previewItemController:(id)arg0 commitPreview:(id)arg1 ;
-(void)_previewItemController:(id)arg0 didDismissPreview:(id)arg1 committing:(BOOL)arg2 ;
-(void)_previewItemController:(id)arg0 willPresentPreview:(id)arg1 forPosition:(struct CGPoint )arg2 inSourceView:(id)arg3 ;
-(void)_promptForReplace:(id)arg0 ;
-(void)_registerPreview;
-(void)_removeDefinitionController:(BOOL)arg0 ;
-(void)_removeShareController:(BOOL)arg0 ;
-(void)_removeShortcutController:(BOOL)arg0 ;
-(void)_removeTextPlaceholder:(id)arg0 willInsertResult:(BOOL)arg1 ;
-(void)_renderUnbufferedInContext:(struct CGContext *)arg0 ;
-(void)_resetForNewPage;
-(void)_resetFormDataForFrame:(id)arg0 ;
-(void)_resetInteractionWithLocation:(struct CGPoint )arg0 modifierFlags:(NSInteger)arg1 ;
-(void)_resetShowingTextStyle:(id)arg0 ;
-(void)_reshapePlugInViews;
-(void)_restoreFlattenedContentLayers;
-(void)_restoreScrollPointForce:(BOOL)arg0 ;
-(void)_restoreViewportSettingsWithSize:(struct CGSize )arg0 ;
-(void)_runLoadBlock:(id)arg0 ;
-(void)_saveStateToHistoryItem:(id)arg0 ;
-(void)_scribbleInteraction:(id)arg0 didFinishWritingInElement:(id)arg1 ;
-(void)_scribbleInteraction:(id)arg0 focusElement:(id)arg1 initialFocusSelectionReferencePoint:(struct CGPoint )arg2 completion:(id)arg3 ;
-(void)_scribbleInteraction:(id)arg0 requestElementsInRect:(struct CGRect )arg1 completion:(id)arg2 ;
-(void)_scribbleInteraction:(id)arg0 willBeginWritingInElement:(id)arg1 ;
-(void)_scrollRectToVisible:(struct CGRect )arg0 animated:(BOOL)arg1 ;
-(void)_selectPositionAtPoint:(struct CGPoint )arg0 ;
-(void)_selectionLayoutChangedByScrolling:(BOOL)arg0 ;
-(void)_sendMouseMoveAndAttemptClick:(id)arg0 ;
-(void)_setDocumentScale:(float)arg0 ;
-(void)_setDocumentType:(int)arg0 ;
-(void)_setDocumentType:(int)arg0 overrideCustomConfigurations:(BOOL)arg1 viewportArguments:(id)arg2 ;
-(void)_setFont:(id)arg0 ;
-(void)_setParentTextView:(id)arg0 ;
-(void)_setSubviewCachesNeedUpdate:(BOOL)arg0 ;
-(void)_setTextColor:(id)arg0 ;
-(void)_share:(id)arg0 ;
-(void)_shareElement:(id)arg0 withURL:(id)arg1 ;
-(void)_shareText:(id)arg0 fromRect:(struct CGRect )arg1 ;
-(void)_showDataDetectorsSheet;
-(void)_showImageSheet;
-(void)_showLinkSheet;
-(void)_showPendingContentLayers;
-(void)_showTextStyleOptions:(id)arg0 ;
-(void)_singleTapRecognized:(id)arg0 ;
-(void)_syntheticMouseEventNotHandledAtLocation:(struct CGPoint )arg0 ;
-(void)_transitionDragPreviewToImageIfNecessary:(id)arg0 ;
-(void)_translate:(id)arg0 ;
-(void)_transliterateChinese:(id)arg0 ;
-(void)_twoFingerDoubleTapRecognized:(id)arg0 ;
-(void)_twoFingerPanRecognized:(id)arg0 ;
-(void)_undoManagerDidRedo:(id)arg0 ;
-(void)_undoManagerDidUndo:(id)arg0 ;
-(void)_unregisterPreview;
-(void)_updateFixedPositionContent;
-(void)_updateFixedPositionedObjectsLayoutRectUsingWebThread:(BOOL)arg0 synchronize:(BOOL)arg1 ;
-(void)_updateFixedPositioningObjectsLayoutAfterScroll;
-(void)_updateFixedPositioningObjectsLayoutAfterVisibleGeometryChange;
-(void)_updateFixedPositioningObjectsLayoutDuringScroll;
-(void)_updateScrollViewBoundaryZoomScales;
-(void)_updateSize;
-(void)_updateSubviewCaches;
-(void)_updateWebKitExposedScrollViewRect;
-(void)_webthread_webView:(id)arg0 attachRootLayer:(id)arg1 ;
-(void)action:(id)arg0 didDismissAlertController:(id)arg1 ;
-(void)actionDidFinish;
-(void)addInputString:(id)arg0 ;
-(void)addInputString:(id)arg0 withFlags:(NSUInteger)arg1 ;
-(void)assistFormNode:(id)arg0 ;
-(void)attemptClick:(id)arg0 ;
-(void)beginFloatingCursorAtPoint:(struct CGPoint )arg0 ;
-(void)beginSelectionChange;
-(void)cancelAutoscroll;
-(void)cancelInteraction;
-(void)cancelInteractionWithImmediateDisplay:(BOOL)arg0 ;
-(void)clearInteractionTimer;
-(void)clearMarkedText;
-(void)clearRangedSelectionInitialExtent;
-(void)clearSelection;
-(void)collapseSelection;
-(void)completeInteraction;
-(void)computeClientAndGlobalPointsForSession:(id)arg0 outClientPoint:(struct CGPoint *)arg1 outGlobalPoint:(struct CGPoint *)arg2 ;
-(void)confirmMarkedText:(id)arg0 ;
-(void)continueInteractionWithLocation:(struct CGPoint )arg0 ;
-(void)copy:(id)arg0 ;
-(void)cut:(id)arg0 ;
-(void)dealloc;
-(void)decreaseSize:(id)arg0 ;
-(void)deferInteraction;
-(void)deferredBecomeFirstResponder;
-(void)deleteBackward;
-(void)deleteFromInput;
-(void)deleteFromInputWithFlags:(NSUInteger)arg0 ;
-(void)didEndScroll;
-(void)didEndZoom;
-(void)didMoveToSuperview;
-(void)didRemovePlugInView:(id)arg0 ;
-(void)didRotateInteractionSheet;
-(void)didZoom;
-(void)disableClearsOnInsertion;
-(void)dragInteraction:(id)arg0 session:(id)arg1 didEndWithOperation:(NSUInteger)arg2 ;
-(void)dragInteraction:(id)arg0 sessionWillBegin:(id)arg1 ;
-(void)dragInteraction:(id)arg0 willAnimateLiftWithAnimator:(id)arg1 session:(id)arg2 ;
-(void)drawPage:(NSUInteger)arg0 withPaginationInfo:(id)arg1 ;
-(void)dropInteraction:(id)arg0 concludeDrop:(id)arg1 ;
-(void)dropInteraction:(id)arg0 item:(id)arg1 willAnimateDropWithAnimator:(id)arg2 ;
-(void)dropInteraction:(id)arg0 performDrop:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidEnd:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidEnter:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidExit:(id)arg1 ;
-(void)endFloatingCursor;
-(void)endPrintMode;
-(void)endSelectionChange;
-(void)ensureSelection;
-(void)extendCurrentSelection:(int)arg0 ;
-(void)fileUploadPanelDidDismiss:(id)arg0 ;
-(void)forceLayout;
-(void)forwardInvocation:(id)arg0 ;
-(void)handleKeyWebEvent:(id)arg0 ;
-(void)hideTapHighlight;
-(void)highlightApproximateNodeAndDisplayInfoSheet;
-(void)highlightApproximateNodeInverted:(BOOL)arg0 ;
-(void)increaseSize:(id)arg0 ;
-(void)insertDictationResult:(id)arg0 withCorrectionIdentifier:(id)arg1 ;
-(void)insertText:(id)arg0 ;
-(void)installGestureRecognizers;
-(void)keyboardInputChangedSelection:(id)arg0 ;
-(void)layoutSubviews;
-(void)loadData:(id)arg0 MIMEType:(id)arg1 textEncodingName:(id)arg2 baseURL:(id)arg3 ;
-(void)loadHTMLString:(id)arg0 baseURL:(id)arg1 ;
-(void)loadRequest:(id)arg0 ;
-(void)makeTextWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeTextWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeft:(id)arg0 ;
-(void)paste:(id)arg0 ;
-(void)pasteAndMatchStyle:(id)arg0 ;
-(void)performClick:(id)arg0 ;
-(void)performInteractionSelector:(SEL)arg0 afterDelay:(CGFloat)arg1 ;
-(void)redrawScaledDocument;
-(void)releasePrintMode;
-(void)removeDictationResultPlaceholder:(id)arg0 willInsertResult:(BOOL)arg1 ;
-(void)removeTextPlaceholder:(id)arg0 ;
-(void)replace:(id)arg0 ;
-(void)replaceCurrentWordWithText:(id)arg0 ;
-(void)replaceRange:(id)arg0 withText:(id)arg1 ;
-(void)replaceRangeWithTextWithoutClosingTyping:(id)arg0 replacementText:(id)arg1 ;
-(void)replaceSelectionWithWebArchive:(id)arg0 selectReplacement:(BOOL)arg1 smartReplace:(BOOL)arg2 ;
-(void)resetCurrentDragInformation;
-(void)resetInteraction;
-(void)resetSelectionAssistant;
-(void)resetTilingAfterLoadComplete;
-(void)revealedSelectionByScrollingWebFrame:(id)arg0 ;
-(void)saveStateToCurrentHistoryItem;
-(void)scrollSelectionToVisible:(BOOL)arg0 ;
-(void)scrollViewWasRemoved;
-(void)select:(id)arg0 ;
-(void)selectAll;
-(void)selectAll:(id)arg0 ;
-(void)selectWord;
-(void)selectionChanged;
-(void)selectionChanged:(id)arg0 ;
-(void)sendOrientationEventForOrientation:(NSInteger)arg0 ;
-(void)sendScrollEventIfNecessary;
-(void)sendScrollEventIfNecessaryWasUserScroll:(BOOL)arg0 ;
-(void)sendScrollWheelEvents;
-(void)setAllowsDataDetectorsSheet:(BOOL)arg0 ;
-(void)setAllowsImageSheet:(BOOL)arg0 ;
-(void)setAllowsLinkSheet:(BOOL)arg0 ;
-(void)setAllowsShrinkToFit:(BOOL)arg0 forDocumentTypes:(int)arg1 ;
-(void)setAllowsUserScaling:(BOOL)arg0 forDocumentTypes:(int)arg1 ;
-(void)setAutoresizes:(BOOL)arg0 ;
-(void)setAvoidsUnsafeArea:(BOOL)arg0 forDocumentTypes:(int)arg1 ;
-(void)setBaseWritingDirection:(NSInteger)arg0 ;
-(void)setBaseWritingDirection:(NSInteger)arg0 forRange:(id)arg1 ;
-(void)setBecomesEditableWithGestures:(BOOL)arg0 ;
-(void)setBottomBufferHeight:(CGFloat)arg0 ;
-(void)setCaretChangeListener:(id)arg0 ;
-(void)setCaretInsets:(struct UIEdgeInsets )arg0 ;
-(void)setContinuousSpellCheckingEnabled:(BOOL)arg0 ;
-(void)setDataDetectorTypes:(NSUInteger)arg0 ;
-(void)setDelegate:(id)arg0 ;
-(void)setDetectsPhoneNumbers:(BOOL)arg0 ;
-(void)setDrawsBackground:(BOOL)arg0 ;
-(void)setFrame:(struct CGRect )arg0 ;
-(void)setIgnoresFocusingMouse:(BOOL)arg0 ;
-(void)setIgnoresKeyEvents:(BOOL)arg0 ;
-(void)setIgnoresViewportOverflowWhenAutoresizing:(BOOL)arg0 ;
-(void)setInitialScale:(float)arg0 forDocumentTypes:(int)arg1 ;
-(void)setInteractionDelegate:(id)arg0 ;
-(void)setIsStandaloneEditableView:(BOOL)arg0 ;
-(void)setIsWidgetEditingView:(BOOL)arg0 ;
-(void)setLoadsSynchronously:(BOOL)arg0 ;
-(void)setMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)setMaximumScale:(float)arg0 forDocumentTypes:(int)arg1 ;
-(void)setMinimumScale:(float)arg0 forDocumentTypes:(int)arg1 ;
-(void)setMinimumSize:(struct CGSize )arg0 ;
-(void)setMinimumSize:(struct CGSize )arg0 updateCurrentViewportConfigurationSize:(BOOL)arg1 ;
-(void)setOpaque:(BOOL)arg0 ;
-(void)setPaused:(BOOL)arg0 ;
-(void)setPaused:(BOOL)arg0 withEvents:(BOOL)arg1 ;
-(void)setRangedSelectionBaseToCurrentSelection;
-(void)setRangedSelectionBaseToCurrentSelectionEnd;
-(void)setRangedSelectionBaseToCurrentSelectionStart;
-(void)setRangedSelectionExtentPoint:(struct CGPoint )arg0 baseIsStart:(BOOL)arg1 allowFlipping:(BOOL)arg2 ;
-(void)setRangedSelectionInitialExtentToCurrentSelectionEnd;
-(void)setRangedSelectionInitialExtentToCurrentSelectionStart;
-(void)setRangedSelectionWithExtentPoint:(struct CGPoint )arg0 ;
-(void)setSelectedDOMRange:(id)arg0 affinity:(NSUInteger)arg1 ;
-(void)setSelectedDOMRange:(id)arg0 affinityDownstream:(BOOL)arg1 ;
-(void)setSelectionToEnd;
-(void)setSelectionToStart;
-(void)setSelectionWithFirstPoint:(struct CGPoint )arg0 secondPoint:(struct CGPoint )arg1 ;
-(void)setSelectionWithPoint:(struct CGPoint )arg0 ;
-(void)setSmoothsFonts:(BOOL)arg0 ;
-(void)setStandaloneEditingElement:(id)arg0 ;
-(void)setText:(id)arg0 ;
-(void)setTileUpdatesDisabled:(BOOL)arg0 ;
-(void)setTilingArea:(int)arg0 ;
-(void)setUpdatesScrollView:(BOOL)arg0 ;
-(void)setUserStyleSheet:(id)arg0 ;
-(void)setViewportSize:(struct CGSize )arg0 forDocumentTypes:(int)arg1 ;
-(void)showPlaybackTargetPicker:(BOOL)arg0 fromRect:(struct CGRect )arg1 ;
-(void)smartExtendRangedSelection:(int)arg0 ;
-(void)startAutoscroll:(struct CGPoint )arg0 ;
-(void)startInteractionWithLocation:(struct CGPoint )arg0 ;
-(void)stopLoading:(id)arg0 ;
-(void)takeTraitsFrom:(id)arg0 ;
-(void)tapInteractionWithLocation:(struct CGPoint )arg0 ;
-(void)toggleBaseWritingDirection;
-(void)toggleBoldface:(id)arg0 ;
-(void)toggleItalics:(id)arg0 ;
-(void)toggleUnderline:(id)arg0 ;
-(void)unmarkText;
-(void)updateDragCaretIfPossible;
-(void)updateFloatingCursorAtPoint:(struct CGPoint )arg0 ;
-(void)updateFloatingCursorAtPoint:(struct CGPoint )arg0 velocity:(struct CGPoint )arg1 ;
-(void)updateInteractionElements;
-(void)updateSelection;
-(void)useSelectionAssistantWithMode:(int)arg0 ;
-(void)validateInteractionWithLocation:(struct CGPoint )arg0 ;
-(void)viewportHandler:(id)arg0 didChangeAvoidsUnsafeArea:(BOOL)arg1 ;
-(void)viewportHandler:(id)arg0 didChangeViewportSize:(struct CGSize )arg1 ;
-(void)viewportHandlerDidChangeScales:(id)arg0 ;
-(void)webThreadWebViewDidLayout:(id)arg0 byScrolling:(BOOL)arg1 ;
-(void)webView:(id)arg0 didChangeLocationWithinPageForFrame:(id)arg1 ;
-(void)webView:(id)arg0 didCommitLoadForFrame:(id)arg1 ;
-(void)webView:(id)arg0 didFailLoadWithError:(id)arg1 forFrame:(id)arg2 ;
-(void)webView:(id)arg0 didFinishLoadForFrame:(id)arg1 ;
-(void)webView:(id)arg0 didFirstVisuallyNonEmptyLayoutInFrame:(id)arg1 ;
-(void)webView:(id)arg0 didHideFullScreenForPlugInView:(id)arg1 ;
-(void)webView:(id)arg0 didObserveDeferredContentChange:(int)arg1 forFrame:(id)arg2 ;
-(void)webView:(id)arg0 didReceiveViewportArguments:(id)arg1 ;
-(void)webView:(id)arg0 needsScrollNotifications:(id)arg1 forFrame:(id)arg2 ;
-(void)webView:(id)arg0 restoreStateFromHistoryItem:(id)arg1 forFrame:(id)arg2 force:(BOOL)arg3 ;
-(void)webView:(id)arg0 runOpenPanelForFileButtonWithResultListener:(id)arg1 configuration:(id)arg2 ;
-(void)webView:(id)arg0 saveStateToHistoryItem:(id)arg1 forFrame:(id)arg2 ;
-(void)webView:(id)arg0 willAddPlugInView:(id)arg1 ;
-(void)webView:(id)arg0 willShowFullScreenForPlugInView:(id)arg1 ;
-(void)webViewDidCommitCompositingLayerChanges:(id)arg0 ;
-(void)webViewDidDrawTiles:(id)arg0 ;
-(void)webViewDidEndOverflowScroll:(id)arg0 ;
-(void)webViewDidPreventDefaultForEvent:(id)arg0 ;
-(void)webViewDidReceiveMobileDocType:(id)arg0 ;
-(void)webViewDidRestoreFromPageCache:(id)arg0 ;
-(void)webViewDidStartOverflowScroll:(id)arg0 ;
-(void)willMoveToSuperview:(id)arg0 ;
-(void)willMoveToWindow:(id)arg0 ;
-(void)willRotateInteractionSheet;
-(void)willStartScroll;
-(void)willStartScrollToTop;
-(void)willStartZoom;
-(void)willZoomToLocation:(struct CGPoint )arg0 atScale:(CGFloat)arg1 forDuration:(CGFloat)arg2 ;
-(void)willZoomToMinimumScale;
-(void)writeDataToPasteboard:(id)arg0 ;


@end


#endif