// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef MAILACCOUNT_H
#define MAILACCOUNT_H

@class NSString, MFLock, NSMutableDictionary, ECAccount, NSArray, NSDate, ACAccount;
@protocol EFLoggable, EDReceivingAccount, EDIndexableAccount, EFScheduler, MFTaskManager;


#import "MFAccount.h"
#import "MFMailboxUid.h"
#import "MFError.h"
#import "MFMailMessageLibrary.h"
#import "MFWeakObjectCache.h"
#import "MFLocalActionReplayHandler.h"

@interface MailAccount : MFAccount <EFLoggable, EDReceivingAccount, EDIndexableAccount>

 {
    NSString *_path;
    NSString *_nonPersistentPath;
    MFMailboxUid *_rootMailboxUid;
    ? _flags;
    os_unfair_lock_s _flagsLock;
    MFMailboxUid *_inboxMailboxUid;
    MFMailboxUid *_draftsMailboxUid;
    MFMailboxUid *_sentMessagesMailboxUid;
    MFMailboxUid *_trashMailboxUid;
    MFMailboxUid *_archiveMailboxUid;
    MFMailboxUid *_junkMailboxUid;
    MFLock *_cachedMailboxenLock;
    MFLock *_deletionLock;
    MFError *_lastConnectionError;
    MFMailMessageLibrary *_library;
    NSMutableDictionary *_currentChokedActions;
    NSString *_mailboxCachePath;
    MFWeakObjectCache *_messageStoresCache;
}


@property (readonly, copy, nonatomic) NSString *altDSID;
@property (readonly, nonatomic) ECAccount *baseAccount;
@property BOOL cacheHasBeenRead;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSString *defaultPath;
@property (readonly, copy) NSString *description;
@property (copy, nonatomic) NSString *displayName;
@property (readonly, copy, nonatomic) NSArray *emailAddressStrings;
@property (readonly, nonatomic) NSArray *emailAddresses;
@property (readonly) NSUInteger hash;
@property (copy, nonatomic) NSString *hostname;
@property (readonly, copy, nonatomic) NSString *identifier;
@property (readonly, nonatomic) BOOL isActive;
@property (readonly, nonatomic) BOOL isLocalAccount;
@property (readonly, nonatomic) BOOL isManaged;
@property (retain, nonatomic) NSDate *lastEmailAliasesSyncDate;
@property (retain, nonatomic) NSString *lastEmailAliasesSyncEntityTag;
@property (retain, nonatomic) NSObject<EFScheduler> *mailboxCacheWriteScheduler; // ivar: _mailboxCacheWriteScheduler
@property (readonly, copy, nonatomic) NSString *mailboxPathExtension;
@property (readonly, nonatomic, getter=isManaged) BOOL managed;
@property (readonly) BOOL moveSupported;
@property (copy, nonatomic) NSString *password;
@property (readonly, nonatomic) BOOL primaryiCloudAccount;
@property (retain, nonatomic) MFLocalActionReplayHandler *replayHandler; // ivar: _replayHandler
@property (readonly, nonatomic) MFMailboxUid *rootMailbox;
@property (readonly, nonatomic) MFMailboxUid *rootMailboxUid;
@property (readonly) BOOL shouldArchiveByDefault;
@property (readonly, copy, nonatomic) NSString *smtpIdentifier;
@property (readonly) BOOL sourceIsManaged;
@property (readonly, copy, nonatomic) NSString *statisticsKind;
@property (readonly) Class superclass;
@property (readonly, nonatomic) BOOL supportsFastRemoteBodySearch; // ivar: _supportsFastRemoteBodySearch
@property (readonly, nonatomic) BOOL supportsRemoteAppend;
@property (readonly, nonatomic) ACAccount *systemAccount;
@property (readonly, nonatomic) NSObject<MFTaskManager> *taskManager;
@property (readonly, copy, nonatomic) NSString *username;


+(BOOL)canMoveMessagesFromAccount:(id)arg0 toAccount:(id)arg1 ;
+(BOOL)canMoveMessagesFromAccount:(id)arg0 toAccount:(id)arg1 profileConnection:(id)arg2 ;
+(BOOL)getConfigurationFromServerForEmail:(id)arg0 ;
+(BOOL)isPredefinedAccountType;
+(BOOL)mailboxListingNotificationsAreEnabled;
+(BOOL)primaryDeliveryAccountIsDynamic;
+(id)URLForInfo:(id)arg0 ;
+(id)_accountContainingEmailAddress:(id)arg0 matchingAddress:(*id)arg1 fullUserName:(*id)arg2 includingInactive:(BOOL)arg3 ;
+(id)_accountWithPath:(id)arg0 ;
+(id)_defaultMailAccountForDeliveryIncludingRestricted:(BOOL)arg0 ;
+(id)_loadAllAccountsWithError:(*id)arg0 ;
+(id)_loadDataAccessAccountsWithError:(*id)arg0 ;
+(id)accountContainingEmailAddress:(id)arg0 ;
+(id)accountContainingEmailAddress:(id)arg0 includingInactive:(BOOL)arg1 ;
+(id)accountForHeaders:(id)arg0 message:(id)arg1 includingInactive:(BOOL)arg2 ;
+(id)accountThatMessageIsFrom:(id)arg0 ;
+(id)accountThatMessageIsFrom:(id)arg0 includingInactive:(BOOL)arg1 ;
+(id)accountWithPath:(id)arg0 ;
+(id)accountWithURL:(id)arg0 ;
+(id)accountWithURLString:(id)arg0 ;
+(id)accountWithUniqueId:(id)arg0 ;
+(id)activeAccounts;
+(id)activeAccountsWithError:(*id)arg0 ;
+(id)activeNonLocalAccounts;
+(id)addressesThatReceivedMessage:(id)arg0 ;
+(id)allActivePrimaryMailboxUids;
+(id)allMailboxUids;
+(id)allMailboxUidsForAccounts:(id)arg0 ;
+(id)allPurgeableMailboxUids;
+(id)csAccountTypeString;
+(id)defaultAccountDirectory;
+(id)defaultDeliveryAccount;
+(id)defaultMailAccountForDelivery;
+(id)defaultMailAccountForDeliveryExcludingRestricted;
+(id)existingAccountForUniqueID:(id)arg0 ;
+(id)existingAccountWithType:(id)arg0 hostname:(id)arg1 username:(id)arg2 ;
+(id)existingDAMailAccountForDAAccount:(id)arg0 ;
+(id)infoForURL:(id)arg0 ;
+(id)lastMailAccountsReloadDate;
+(id)legacyPathForAccountIdentifier:(id)arg0 withHostname:(id)arg1 username:(id)arg2 ;
+(id)legacyPathNameForAccountWithHostname:(id)arg0 username:(id)arg1 ;
+(id)log;
+(id)mailAccounts;
+(id)mailAccountsWithError:(*id)arg0 ;
+(id)mailboxUidForFileSystemPath:(id)arg0 create:(BOOL)arg1 ;
+(id)mailboxUidFromActiveAccountsForURL:(id)arg0 ;
+(id)newAccountWithDictionary:(id)arg0 ;
+(id)newAccountWithPath:(id)arg0 ;
+(id)outboxMailboxUid;
+(id)outboxMessageStore:(BOOL)arg0 ;
+(id)predefinedValueForKey:(id)arg0 ;
+(id)purgeableAccounts;
+(id)standardAccountClass:(Class)arg0 valueForKey:(id)arg1 ;
+(struct os_unfair_recursive_lock_s *)lock;
+(void)_addAccountToSortedPaths:(id)arg0 ;
+(void)_removeAccountFromSortedPaths:(id)arg0 ;
+(void)_removeLookAsideValuesNotInAccountList:(id)arg0 ;
+(void)_setMailAccounts:(id)arg0 saveIfChanged:(BOOL)arg1 alreadyLocked:(BOOL)arg2 ;
+(void)_setOutboxMailboxUid:(id)arg0 ;
+(void)_setupSortedPathsForAccounts:(id)arg0 ;
+(void)disableMailboxListingNotifications;
+(void)enableMailboxListingNotifications:(BOOL)arg0 ;
+(void)initialize;
+(void)notifyOfAccountsAdded:(id)arg0 accountsRemoved:(id)arg1 changedAccounts:(id)arg2 ;
+(void)reloadAccounts;
+(void)resetMailboxTimers;
+(void)saveStateForAllAccounts;
+(void)setMailAccounts:(id)arg0 ;
+(void)setMailAccounts:(id)arg0 saveIfChanged:(BOOL)arg1 ;
+(void)test_tearDown;
+(void)updateEmailAliasesForActiveAccounts;
-(BOOL)_assignSpecialMailboxToAppropriateIvar:(id)arg0 forType:(int)arg1 ;
-(BOOL)_canEmptyMessagesFromMailboxUid:(id)arg0 ;
-(BOOL)_cleanInboxDuplication:(id)arg0 ;
-(BOOL)_deleteMailbox:(id)arg0 reflectToServer:(BOOL)arg1 ;
-(BOOL)_loadMailboxListingIntoCache:(id)arg0 attributes:(unsigned int)arg1 children:(id)arg2 parent:(id)arg3 ;
-(BOOL)_registerPushNotificationPrefix:(id)arg0 forMailboxNames:(id)arg1 ;
-(BOOL)_renameMailbox:(id)arg0 newName:(id)arg1 parent:(id)arg2 ;
-(BOOL)_resetSpecialMailboxes;
-(BOOL)_setChildren:(id)arg0 forMailboxUid:(id)arg1 ;
-(BOOL)_setPath:(id)arg0 ;
-(BOOL)_shouldConfigureMailboxCache;
-(BOOL)_shouldLogDeleteActivity;
-(BOOL)canArchiveForMailbox:(id)arg0 ;
-(BOOL)canArchiveSentMessages;
-(BOOL)canAuthenticateWithCurrentCredentials;
-(BOOL)canCreateNewMailboxes;
-(BOOL)canFetch;
-(BOOL)canMailboxBeDeleted:(id)arg0 ;
-(BOOL)canMailboxBeRenamed:(id)arg0 ;
-(BOOL)canReceiveNewMailNotifications;
-(BOOL)canUseCarrierDeliveryFallback;
-(BOOL)canUseDeliveryAccount:(id)arg0 ;
-(BOOL)checkAndSetDefaultEmailAddress:(id)arg0 ;
-(BOOL)checkAndSetEmailAddresses:(id)arg0 ;
-(BOOL)checkAndSetReceiveEmailAliasAddresses:(id)arg0 ;
-(BOOL)containsMailboxWithURL:(id)arg0 ;
-(BOOL)deleteInPlaceForAllMailboxes;
-(BOOL)deleteInPlaceForMailbox:(id)arg0 ;
-(BOOL)deleteMailbox:(id)arg0 ;
-(BOOL)deleteMailbox:(id)arg0 reflectToServer:(BOOL)arg1 ;
-(BOOL)deliveryAccountInUseByOtherAccounts:(id)arg0 ;
-(BOOL)derivesDeliveryAccountInfoFromMailAccount;
-(BOOL)hasEnoughInformationForEasySetup;
-(BOOL)isAccountClassEquivalentTo:(id)arg0 ;
-(BOOL)isActiveWithPersistentAccount:(id)arg0 ;
-(BOOL)isEquivalentTo:(id)arg0 hostname:(id)arg1 username:(id)arg2 ;
-(BOOL)isHostnameEquivalentTo:(id)arg0 ;
-(BOOL)isMailboxLocalForType:(int)arg0 ;
-(BOOL)isPrimaryDeliveryAccountDisabled;
-(BOOL)isSpecialMailbox:(id)arg0 ;
-(BOOL)isUsernameEquivalentTo:(id)arg0 ;
-(BOOL)moveMailbox:(id)arg0 intoParent:(id)arg1 ;
-(BOOL)mustArchiveSentMessages;
-(BOOL)newMailboxNameIsAcceptable:(id)arg0 reasonForFailure:(*id)arg1 ;
-(BOOL)ownsMailboxUidWithURL:(id)arg0 ;
-(BOOL)perMessageEncryptionEnabledForAddress:(id)arg0 ;
-(BOOL)preventArchiveForMailbox:(id)arg0 ;
-(BOOL)reconstituteOrphanedMeetingInMessage:(id)arg0 ;
-(BOOL)renameMailbox:(id)arg0 newName:(id)arg1 ;
-(BOOL)renameMailbox:(id)arg0 newName:(id)arg1 parent:(id)arg2 ;
-(BOOL)restrictedFromSendingExternally;
-(BOOL)restrictedFromSyncingRecents;
-(BOOL)restrictedFromTransferingMessagesToOtherAccounts;
-(BOOL)shouldFetchAgainWithError:(id)arg0 foregroundRequest:(BOOL)arg1 ;
-(BOOL)shouldFetchRemoteLinksWithDateReceived:(id)arg0 ;
-(BOOL)shouldRestoreMessagesAfterFailedDelete;
-(BOOL)supportsAppend;
-(BOOL)supportsArchiving;
-(BOOL)supportsHandoffType:(id)arg0 ;
-(BOOL)supportsMailDrop;
-(BOOL)supportsMailboxEditing;
-(BOOL)supportsMessageFlagging;
-(BOOL)supportsPurge;
-(BOOL)supportsSyncingReadState;
-(BOOL)supportsThreadOperations;
-(BOOL)supportsUserPushedMailboxes;
-(BOOL)willPerformActionForChokePoint:(id)arg0 coalescePoint:(id)arg1 result:(*id)arg2 ;
-(Class)storeClass;
-(Class)storeClassForMailbox:(id)arg0 ;
-(id)URL;
-(id)URLForMessage:(id)arg0 ;
-(id)URLString;
-(id)URLStringFromLegacyURLString:(id)arg0 ;
-(id)_URLForInfo:(id)arg0 ;
-(id)_URLScheme;
-(id)_cachedSpecialMailboxOfType:(int)arg0 ;
-(id)_childOfMailbox:(id)arg0 withComponentName:(id)arg1 ;
-(id)_copyMailboxUidWithParent:(id)arg0 name:(id)arg1 attributes:(NSUInteger)arg2 existingMailboxUid:(id)arg3 dictionary:(id)arg4 ;
-(id)_copyMailboxWithParent:(id)arg0 name:(id)arg1 attributes:(NSUInteger)arg2 dictionary:(id)arg3 ;
-(id)_defaultSpecialMailboxNameForType:(int)arg0 ;
-(id)_deliveryAccountCreateIfNeeded:(BOOL)arg0 ;
-(id)_infoForMatchingURL:(id)arg0 ;
-(id)_localMailboxNameForType:(int)arg0 usingDisplayName:(id)arg1 ;
-(id)_mailboxPathPrefix;
-(id)_newMailboxWithParent:(id)arg0 name:(id)arg1 attributes:(unsigned int)arg2 dictionary:(id)arg3 withCreationOption:(int)arg4 ;
-(id)_pathComponentForUidName:(id)arg0 ;
-(id)_specialMailboxUidWithType:(int)arg0 create:(BOOL)arg1 ;
-(id)_uidNameForPathComponent:(id)arg0 ;
-(id)allLocalMailboxUids;
-(id)allMailMailboxUid;
-(id)allMailboxUids;
-(id)allMailboxesFilteringNotes:(BOOL)arg0 ;
-(id)connectionError;
-(id)copyDataForRemoteEncryptionCertificatesForAddress:(id)arg0 error:(*id)arg1 ;
-(id)copyDataForRemoteEncryptionCertificatesForAddresses:(id)arg0 errors:(*id)arg1 ;
-(id)copyReceivingEmailAddresses;
-(id)customSignature;
-(id)debugAccountState;
-(id)defaultEmailAddress;
-(id)deliveryAccount;
-(id)deliveryAccountAlternates;
-(id)displayNameUsingSpecialNamesForMailboxUid:(id)arg0 ;
-(id)displayUsername;
-(id)encryptionIdentityPersistentReferenceForAddress:(id)arg0 ;
-(id)fetchLimits;
-(id)firstEmailAddress;
-(id)fromEmailAddresses;
-(id)fromEmailAddressesIncludingDisabled;
-(id)fullUserName;
-(id)iconString;
-(id)initWithLibrary:(id)arg0 path:(id)arg1 ;
-(id)initWithLibrary:(id)arg0 persistentAccount:(id)arg1 ;
-(id)initWithPath:(id)arg0 ;
-(id)initWithPersistentAccount:(id)arg0 ;
-(id)lastKnownCapabilities;
-(id)legacySQLExpressionToMatchAllMailboxes;
-(id)library;
-(id)loggingIdentifier;
-(id)mailboxCachePath;
-(id)mailboxForType:(NSInteger)arg0 ;
-(id)mailboxUidForInfo:(id)arg0 ;
-(id)mailboxUidForRelativePath:(id)arg0 create:(BOOL)arg1 ;
-(id)mailboxUidForRelativePath:(id)arg0 create:(BOOL)arg1 withOption:(int)arg2 ;
-(id)mailboxUidForURL:(id)arg0 ;
-(id)mailboxUidOfType:(int)arg0 createIfNeeded:(BOOL)arg1 ;
-(id)mailboxesForSuggestionsLostMessageSearchPriorToTime:(CGFloat)arg0 ;
-(id)meetingStorePersistentID;
-(id)newMailboxWithParent:(id)arg0 name:(id)arg1 ;
-(id)path;
-(id)persistentNameForMailbox:(id)arg0 ;
-(id)powerAssertionIdentifierWithPrefix:(id)arg0 ;
-(id)primaryMailboxUid;
-(id)pushedMailboxUids;
-(id)receiveEmailAliasAddresses;
-(id)replayAction:(id)arg0 ;
-(id)saveSentFolder;
-(id)signingIdentityPersistentReferenceForAddress:(id)arg0 ;
-(id)specialMailboxNameForType:(int)arg0 ;
-(id)stateCaptureTitle;
-(id)storeForMailboxUid:(id)arg0 ;
-(id)transferDisabledMailboxUids;
-(id)unactionableInvitationICSRepresentationInMessage:(id)arg0 summary:(*id)arg1 ;
-(id)uniqueIdForPersistentConnection;
-(id)uniqueServerIdForMessage:(id)arg0 ;
-(id)unsupportedHandoffTypes;
-(id)valueInAccountLookAsidePropertiesForKey:(id)arg0 ;
-(int)_emptyFrequencyForKey:(id)arg0 defaultValue:(id)arg1 ;
-(int)archiveDestinationForMailbox:(id)arg0 ;
-(int)emptyFrequencyForMailboxType:(int)arg0 ;
-(int)secureCompositionEncryptionPolicyForAddress:(id)arg0 ;
-(int)secureCompositionSigningPolicyForAddress:(id)arg0 ;
-(void)_asynchronouslyInvalidateAndDeleteAccountData:(BOOL)arg0 ;
-(void)_deleteHook;
-(void)_didBecomeActive:(BOOL)arg0 ;
-(void)_incrementCacheDirtyCount;
-(void)_invalidateAndDeleteAccountData:(BOOL)arg0 ;
-(void)_invalidateCachedMailboxen;
-(void)_loadEntriesFromFileSystemPath:(id)arg0 parent:(id)arg1 ;
-(void)_mailboxesWereRemovedFromTree:(id)arg0 withFileSystemPaths:(id)arg1 ;
-(void)_readCustomInfoFromMailboxCache:(id)arg0 ;
-(void)_registerStateCaptureHandler;
-(void)_resetAllMailboxURLs:(BOOL)arg0 ;
-(void)_setAccountProperties:(id)arg0 ;
-(void)_setEmptyFrequency:(int)arg0 forKey:(id)arg1 ;
-(void)_setSpecialMailbox:(id)arg0 forType:(int)arg1 ;
-(void)_setSpecialMailboxName:(id)arg0 forType:(int)arg1 ;
-(void)_setValueInAccountLookAsideProperties:(id)arg0 forKey:(id)arg1 subKey:(id)arg2 ;
-(void)_synchronizeMailboxListWithFileSystem;
-(void)_synchronouslyLoadListingForParent:(id)arg0 ;
-(void)_writeCustomInfoToMailboxCache:(id)arg0 ;
-(void)_writeMailboxCacheWithPrejudice:(BOOL)arg0 ;
-(void)_writeMailboxCacheWithPrejudice:(BOOL)arg0 completionHandler:(id)arg1 ;
-(void)addNewAction:(id)arg0 ;
-(void)changePushedMailboxUidsAdded:(id)arg0 deleted:(id)arg1 ;
-(void)dealloc;
-(void)deleteDeliveryAccountIfNeeded;
-(void)deleteMessagesFromMailboxUid:(id)arg0 olderThanNumberOfDays:(unsigned int)arg1 ;
-(void)deliveryAccountWillBeRemoved:(id)arg0 ;
-(void)didFinishActionForChokePoint:(id)arg0 coalescePoint:(id)arg1 withResult:(id)arg2 ;
-(void)emptyTrash;
-(void)fetchMailboxList;
-(void)forceFetchMailboxList;
-(void)invalidate;
-(void)invalidateAndDelete;
-(void)invalidateEmailAliases;
-(void)newActionsAdded;
-(void)persistentAccountDidChange:(id)arg0 previousAccount:(id)arg1 ;
-(void)pushUpdateForAliasData;
-(void)releaseAllConnections;
-(void)releaseAllForcedConnections;
-(void)resetMailboxCache;
-(void)resetMailboxTimer;
-(void)resetMailboxURLs;
-(void)resetSpecialMailboxes;
-(void)saveState;
-(void)setActive:(BOOL)arg0 ;
-(void)setCanUseCarrierDeliveryFallback:(BOOL)arg0 ;
-(void)setConnectionError:(id)arg0 ;
-(void)setCustomSignature:(id)arg0 ;
-(void)setDefaultEmailAddress:(id)arg0 ;
-(void)setDeliveryAccount:(id)arg0 ;
-(void)setDeliveryAccountAlternates:(id)arg0 ;
-(void)setEmptyFrequency:(int)arg0 forMailboxType:(int)arg1 ;
-(void)setEnabled:(BOOL)arg0 forEmailAddress:(id)arg1 ;
-(void)setEncryptionIdentityPersistentReference:(id)arg0 forAddress:(id)arg1 ;
-(void)setFullUserName:(id)arg0 ;
-(void)setLibrary:(id)arg0 ;
-(void)setMailboxCachePath:(id)arg0 ;
-(void)setMailboxUid:(id)arg0 forMailboxType:(int)arg1 ;
-(void)setPath:(id)arg0 ;
-(void)setPortNumber:(unsigned int)arg0 ;
-(void)setPrimaryDeliveryAccountDisabled:(BOOL)arg0 ;
-(void)setReceiveEmailAliasAddresses:(id)arg0 ;
-(void)setSigningIdentityPersistentReference:(id)arg0 forAddress:(id)arg1 ;
-(void)setValueInAccountLookAsideProperties:(id)arg0 forKey:(id)arg1 ;
-(void)setValueInAccountProperties:(id)arg0 forKey:(id)arg1 ;
-(void)setupLibrary;
-(void)startListeningForNotifications;
-(void)stopListeningForNotifications;
-(void)systemDidWake;
-(void)systemWillSleep;
-(void)test_tearDown;
-(void)transferNotificationSessionToAccount:(id)arg0 ;
-(void)updateEmailAliasesIfNeeded;


@end


#endif