// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef HMCCONTEXT_H
#define HMCCONTEXT_H

@class HMFObject, NSString;
@protocol HMFAsyncContext;


#import "HMDBackingStore.h"
#import "HMDManagedObjectContext.h"
#import "HMCPartition.h"

@interface HMCContext : HMFObject <HMFAsyncContext>



@property (weak, nonatomic) HMDBackingStore *backingStore; // ivar: _backingStore
@property BOOL isExecuting; // ivar: _isExecuting
@property (readonly, nonatomic) HMDManagedObjectContext *managedObjectContext; // ivar: _managedObjectContext
@property (readonly, nonatomic) NSString *name; // ivar: _name
@property (readonly, nonatomic) HMCPartition *partition; // ivar: _partition
@property (readonly, nonatomic) NSString *transactionAuthor; // ivar: _transactionAuthor


+(BOOL)managedObjectIsMKF:(id)arg0 ;
+(Class)managedObjectClassFromProtocol:(id)arg0 ;
+(id)currentContext;
+(id)findAccessoryNetworkProtectionGroupWithDatabaseID:(id)arg0 ;
+(id)findAccessoryNetworkProtectionGroupWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAccessoryNetworkProtectionGroupWithModelID:(id)arg0 ;
+(id)findAccessoryNetworkProtectionGroupWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAccessoryWithDatabaseID:(id)arg0 ;
+(id)findAccessoryWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAccessoryWithModelID:(id)arg0 ;
+(id)findAccessoryWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAccountHandleWithDatabaseID:(id)arg0 ;
+(id)findAccountHandleWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAccountHandleWithModelID:(id)arg0 ;
+(id)findAccountHandleWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAccountWithDatabaseID:(id)arg0 ;
+(id)findAccountWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAccountWithModelID:(id)arg0 ;
+(id)findAccountWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findActionSetWithDatabaseID:(id)arg0 ;
+(id)findActionSetWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findActionSetWithModelID:(id)arg0 ;
+(id)findActionSetWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findActionWithDatabaseID:(id)arg0 ;
+(id)findActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findActionWithModelID:(id)arg0 ;
+(id)findActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAirPlayAccessoryWithDatabaseID:(id)arg0 ;
+(id)findAirPlayAccessoryWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAirPlayAccessoryWithModelID:(id)arg0 ;
+(id)findAirPlayAccessoryWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAllModelsOfType:(id)arg0 error:(*id)arg1 ;
+(id)findAnalysisEventBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findAnalysisEventBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAnalysisEventBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findAnalysisEventBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAppleMediaAccessoryPowerActionWithDatabaseID:(id)arg0 ;
+(id)findAppleMediaAccessoryPowerActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAppleMediaAccessoryPowerActionWithModelID:(id)arg0 ;
+(id)findAppleMediaAccessoryPowerActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findAppleMediaAccessoryWithDatabaseID:(id)arg0 ;
+(id)findAppleMediaAccessoryWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findAppleMediaAccessoryWithModelID:(id)arg0 ;
+(id)findAppleMediaAccessoryWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findApplicationDataWithDatabaseID:(id)arg0 ;
+(id)findApplicationDataWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findApplicationDataWithModelID:(id)arg0 ;
+(id)findApplicationDataWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinConditionWithDatabaseID:(id)arg0 ;
+(id)findBulletinConditionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinConditionWithModelID:(id)arg0 ;
+(id)findBulletinConditionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinTimeSpecificationWithDatabaseID:(id)arg0 ;
+(id)findBulletinTimeSpecificationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findBulletinTimeSpecificationWithModelID:(id)arg0 ;
+(id)findBulletinTimeSpecificationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCalendarEventWithDatabaseID:(id)arg0 ;
+(id)findCalendarEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCalendarEventWithModelID:(id)arg0 ;
+(id)findCalendarEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraAccessModeBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findCameraAccessModeBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraAccessModeBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findCameraAccessModeBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraReachabilityBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findCameraReachabilityBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraReachabilityBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findCameraReachabilityBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraSignificantEventBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findCameraSignificantEventBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCameraSignificantEventBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findCameraSignificantEventBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicBulletinRegistrationWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicBulletinRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicBulletinRegistrationWithModelID:(id)arg0 ;
+(id)findCharacteristicBulletinRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicEventWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicEventWithModelID:(id)arg0 ;
+(id)findCharacteristicEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicRangeEventWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicRangeEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicRangeEventWithModelID:(id)arg0 ;
+(id)findCharacteristicRangeEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicValueEventWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicValueEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicValueEventWithModelID:(id)arg0 ;
+(id)findCharacteristicValueEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 ;
+(id)findCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 error:(*id)arg2 ;
+(id)findCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 ;
+(id)findCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 error:(*id)arg2 ;
+(id)findCharacteristicWriteActionWithDatabaseID:(id)arg0 ;
+(id)findCharacteristicWriteActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findCharacteristicWriteActionWithModelID:(id)arg0 ;
+(id)findCharacteristicWriteActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findDeviceWithDatabaseID:(id)arg0 ;
+(id)findDeviceWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findDeviceWithDeviceIdentifier:(id)arg0 ;
+(id)findDeviceWithModelID:(id)arg0 ;
+(id)findDeviceWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findDurationEventWithDatabaseID:(id)arg0 ;
+(id)findDurationEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findDurationEventWithModelID:(id)arg0 ;
+(id)findDurationEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findEventTriggerWithDatabaseID:(id)arg0 ;
+(id)findEventTriggerWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findEventTriggerWithModelID:(id)arg0 ;
+(id)findEventTriggerWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findEventWithDatabaseID:(id)arg0 ;
+(id)findEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findEventWithModelID:(id)arg0 ;
+(id)findEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findFloatCharacteristicWithDatabaseID:(id)arg0 ;
+(id)findFloatCharacteristicWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findFloatCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 ;
+(id)findFloatCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 error:(*id)arg2 ;
+(id)findFloatCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 ;
+(id)findFloatCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 error:(*id)arg2 ;
+(id)findGuestAccessCodeWithDatabaseID:(id)arg0 ;
+(id)findGuestAccessCodeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findGuestAccessCodeWithModelID:(id)arg0 ;
+(id)findGuestAccessCodeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHAPAccessoryWithDatabaseID:(id)arg0 ;
+(id)findHAPAccessoryWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHAPAccessoryWithModelID:(id)arg0 ;
+(id)findHAPAccessoryWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHAPMetadataWithDatabaseID:(id)arg0 ;
+(id)findHAPMetadataWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHAPMetadataWithModelID:(id)arg0 ;
+(id)findHAPMetadataWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeAccessCodeWithDatabaseID:(id)arg0 ;
+(id)findHomeAccessCodeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeAccessCodeWithModelID:(id)arg0 ;
+(id)findHomeAccessCodeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeManagerHomeWithDatabaseID:(id)arg0 ;
+(id)findHomeManagerHomeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeManagerHomeWithModelID:(id)arg0 ;
+(id)findHomeManagerHomeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeManagerWithDatabaseID:(id)arg0 ;
+(id)findHomeManagerWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeManagerWithModelID:(id)arg0 ;
+(id)findHomeManagerWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeMediaSettingWithDatabaseID:(id)arg0 ;
+(id)findHomeMediaSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeMediaSettingWithModelID:(id)arg0 ;
+(id)findHomeMediaSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeNetworkRouterManagingDeviceSettingWithDatabaseID:(id)arg0 ;
+(id)findHomeNetworkRouterManagingDeviceSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeNetworkRouterManagingDeviceSettingWithModelID:(id)arg0 ;
+(id)findHomeNetworkRouterManagingDeviceSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeNetworkRouterSettingWithDatabaseID:(id)arg0 ;
+(id)findHomeNetworkRouterSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeNetworkRouterSettingWithModelID:(id)arg0 ;
+(id)findHomeNetworkRouterSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomePersonManagerSettingWithDatabaseID:(id)arg0 ;
+(id)findHomePersonManagerSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomePersonManagerSettingWithModelID:(id)arg0 ;
+(id)findHomePersonManagerSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomePersonWithDatabaseID:(id)arg0 ;
+(id)findHomePersonWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomePersonWithModelID:(id)arg0 ;
+(id)findHomePersonWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeSettingWithDatabaseID:(id)arg0 ;
+(id)findHomeSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeSettingWithModelID:(id)arg0 ;
+(id)findHomeSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeSoftwareUpdateSettingWithDatabaseID:(id)arg0 ;
+(id)findHomeSoftwareUpdateSettingWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeSoftwareUpdateSettingWithModelID:(id)arg0 ;
+(id)findHomeSoftwareUpdateSettingWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeThreadNetworkWithDatabaseID:(id)arg0 ;
+(id)findHomeThreadNetworkWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeThreadNetworkWithModelID:(id)arg0 ;
+(id)findHomeThreadNetworkWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeWithDatabaseID:(id)arg0 ;
+(id)findHomeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findHomeWithModelID:(id)arg0 ;
+(id)findHomeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findIncomingInvitationWithDatabaseID:(id)arg0 ;
+(id)findIncomingInvitationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findIncomingInvitationWithModelID:(id)arg0 ;
+(id)findIncomingInvitationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findIntegerCharacteristicWithDatabaseID:(id)arg0 ;
+(id)findIntegerCharacteristicWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findIntegerCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 ;
+(id)findIntegerCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 error:(*id)arg2 ;
+(id)findIntegerCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 ;
+(id)findIntegerCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 error:(*id)arg2 ;
+(id)findInvitationWithDatabaseID:(id)arg0 ;
+(id)findInvitationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findInvitationWithModelID:(id)arg0 ;
+(id)findInvitationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findLocationEventWithDatabaseID:(id)arg0 ;
+(id)findLocationEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findLocationEventWithModelID:(id)arg0 ;
+(id)findLocationEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findMediaAccessoryWithDatabaseID:(id)arg0 ;
+(id)findMediaAccessoryWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findMediaAccessoryWithModelID:(id)arg0 ;
+(id)findMediaAccessoryWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findMediaPlaybackActionWithDatabaseID:(id)arg0 ;
+(id)findMediaPlaybackActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findMediaPlaybackActionWithModelID:(id)arg0 ;
+(id)findMediaPlaybackActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findModelObjectOfType:(id)arg0 databaseID:(id)arg1 error:(*id)arg2 ;
+(id)findModelObjectOfType:(id)arg0 parentObjectID:(id)arg1 template:(id)arg2 substitutions:(id)arg3 error:(*id)arg4 ;
+(id)findModelObjectOfType:(id)arg0 template:(id)arg1 substitutions:(id)arg2 error:(*id)arg3 ;
+(id)findModelWithModelID:(id)arg0 ofType:(id)arg1 error:(*id)arg2 ;
+(id)findNaturalLightingActionWithDatabaseID:(id)arg0 ;
+(id)findNaturalLightingActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findNaturalLightingActionWithModelID:(id)arg0 ;
+(id)findNaturalLightingActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationCharacteristicWithDatabaseID:(id)arg0 ;
+(id)findNotificationRegistrationCharacteristicWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationCharacteristicWithModelID:(id)arg0 ;
+(id)findNotificationRegistrationCharacteristicWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationMediaPropertyWithDatabaseID:(id)arg0 ;
+(id)findNotificationRegistrationMediaPropertyWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationMediaPropertyWithModelID:(id)arg0 ;
+(id)findNotificationRegistrationMediaPropertyWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationWithDatabaseID:(id)arg0 ;
+(id)findNotificationRegistrationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findNotificationRegistrationWithModelID:(id)arg0 ;
+(id)findNotificationRegistrationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findOutgoingInvitationWithDatabaseID:(id)arg0 ;
+(id)findOutgoingInvitationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findOutgoingInvitationWithModelID:(id)arg0 ;
+(id)findOutgoingInvitationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findPersonWithDatabaseID:(id)arg0 ;
+(id)findPersonWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findPersonWithModelID:(id)arg0 ;
+(id)findPersonWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findPhotosPersonWithDatabaseID:(id)arg0 ;
+(id)findPhotosPersonWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findPhotosPersonWithModelID:(id)arg0 ;
+(id)findPhotosPersonWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findPresenceBulletinConditionWithDatabaseID:(id)arg0 ;
+(id)findPresenceBulletinConditionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findPresenceBulletinConditionWithModelID:(id)arg0 ;
+(id)findPresenceBulletinConditionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findPresenceEventWithDatabaseID:(id)arg0 ;
+(id)findPresenceEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findPresenceEventWithModelID:(id)arg0 ;
+(id)findPresenceEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findRemovedUserAccessCodeWithDatabaseID:(id)arg0 ;
+(id)findRemovedUserAccessCodeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findRemovedUserAccessCodeWithModelID:(id)arg0 ;
+(id)findRemovedUserAccessCodeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findResidentWithDatabaseID:(id)arg0 ;
+(id)findResidentWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findResidentWithModelID:(id)arg0 ;
+(id)findResidentWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findRoomWithDatabaseID:(id)arg0 ;
+(id)findRoomWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findRoomWithModelID:(id)arg0 ;
+(id)findRoomWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findServiceGroupWithDatabaseID:(id)arg0 ;
+(id)findServiceGroupWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findServiceGroupWithModelID:(id)arg0 ;
+(id)findServiceGroupWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findServiceWithDatabaseID:(id)arg0 ;
+(id)findServiceWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findServiceWithInstanceID:(id)arg0 accessory:(id)arg1 ;
+(id)findServiceWithInstanceID:(id)arg0 accessory:(id)arg1 error:(*id)arg2 ;
+(id)findServiceWithInstanceID:(id)arg0 accessoryDatabaseID:(id)arg1 ;
+(id)findServiceWithInstanceID:(id)arg0 accessoryDatabaseID:(id)arg1 error:(*id)arg2 ;
+(id)findServiceWithModelID:(id)arg0 ;
+(id)findServiceWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findShortcutActionWithDatabaseID:(id)arg0 ;
+(id)findShortcutActionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findShortcutActionWithModelID:(id)arg0 ;
+(id)findShortcutActionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findSignificantTimeEventWithDatabaseID:(id)arg0 ;
+(id)findSignificantTimeEventWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findSignificantTimeEventWithModelID:(id)arg0 ;
+(id)findSignificantTimeEventWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findSoftwareUpdateWithDatabaseID:(id)arg0 ;
+(id)findSoftwareUpdateWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findSoftwareUpdateWithModelID:(id)arg0 ;
+(id)findSoftwareUpdateWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findStringCharacteristicWithDatabaseID:(id)arg0 ;
+(id)findStringCharacteristicWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findStringCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 ;
+(id)findStringCharacteristicWithInstanceID:(id)arg0 service:(id)arg1 error:(*id)arg2 ;
+(id)findStringCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 ;
+(id)findStringCharacteristicWithInstanceID:(id)arg0 serviceDatabaseID:(id)arg1 error:(*id)arg2 ;
+(id)findSunriseSunsetTimeSpecificationWithDatabaseID:(id)arg0 ;
+(id)findSunriseSunsetTimeSpecificationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findSunriseSunsetTimeSpecificationWithModelID:(id)arg0 ;
+(id)findSunriseSunsetTimeSpecificationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findTimeOfDayTimeSpecificationWithDatabaseID:(id)arg0 ;
+(id)findTimeOfDayTimeSpecificationWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findTimeOfDayTimeSpecificationWithModelID:(id)arg0 ;
+(id)findTimeOfDayTimeSpecificationWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findTimePeriodBulletinConditionWithDatabaseID:(id)arg0 ;
+(id)findTimePeriodBulletinConditionWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findTimePeriodBulletinConditionWithModelID:(id)arg0 ;
+(id)findTimePeriodBulletinConditionWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findTimerTriggerWithDatabaseID:(id)arg0 ;
+(id)findTimerTriggerWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findTimerTriggerWithModelID:(id)arg0 ;
+(id)findTimerTriggerWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findTriggerWithDatabaseID:(id)arg0 ;
+(id)findTriggerWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findTriggerWithModelID:(id)arg0 ;
+(id)findTriggerWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findUserAccessCodeWithDatabaseID:(id)arg0 ;
+(id)findUserAccessCodeWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findUserAccessCodeWithModelID:(id)arg0 ;
+(id)findUserAccessCodeWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findUserWithDatabaseID:(id)arg0 ;
+(id)findUserWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findUserWithModelID:(id)arg0 ;
+(id)findUserWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)findZoneWithDatabaseID:(id)arg0 ;
+(id)findZoneWithDatabaseID:(id)arg0 error:(*id)arg1 ;
+(id)findZoneWithModelID:(id)arg0 ;
+(id)findZoneWithModelID:(id)arg0 error:(*id)arg1 ;
+(id)synchronizationTokenFromLegacyModelID:(id)arg0 ;
-(BOOL)save;
-(BOOL)save:(*id)arg0 ;
-(id)createNewModelOfClass:(Class)arg0 ;
-(id)findHomeManagerWithError:(*id)arg0 ;
-(id)findLocalAccountWithError:(*id)arg0 ;
-(id)findRemoteAccountsWithError:(*id)arg0 ;
-(id)home;
-(id)homeManager;
-(id)initWithContext:(id)arg0 partition:(id)arg1 ;
-(void)assertIsExecuting;
-(void)deleteObject:(id)arg0 ;
-(void)performBlock:(id)arg0 ;
-(void)reset;
-(void)rollback;
-(void)unsafeSynchronousBlock:(id)arg0 ;


@end


#endif