

#include "HDMCDaySummaryObserverQueryServer.h"
#include "HDMCAnalysisManager.h"
#include "HDMCDailyAnalytics.h"
#include "HDMCNotificationManager.h"
#include "HDMCAnalysisQueryServer.h"
#include "HDMCHeartStatisticsEnumerator.h"
#include "HDMCAnalysisScheduler.h"
#include "HDMCDaySummaryEnumerator.h"
#include "HDMCDiagnosticsServer.h"
#include "HDMCSymptomHistoryBuilder.h"
#include "HDMCDaySummaryQueryServer.h"
#include "HDMCDailyMetric.h"
#include "HDMCNotification.h"
#include "HDMCPluginServer.h"
#include "HDMCProfileExtension.h"
#include "HDMCAnalyticsManager.h"
#include "HDMCDaySummaryBuilder.h"
