// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef AVPLAYERITEM_H
#define AVPLAYERITEM_H

@class NSDate, NSError, NSArray, NSString;
@protocol NSCopying, NSObject><NSCopying;

#import <Foundation/Foundation.h>

#import "AVPlayerItemInternal.h"
#import "AVPlayerItem.h"

@interface AVPlayerItem : NSObject <NSCopying>

 {
    AVPlayerItemInternal *_playerItem;
}


@property (retain) NSObject<NSObject><NSCopying> *AVKitData;
@property (nonatomic, getter=_isExternalProtectionRequiredForPlayback, setter=_setExternalProtectionRequiredForPlayback:) BOOL _externalProtectionRequiredForPlayback;
@property (readonly, nonatomic, getter=_isRental) BOOL _rental;
@property (readonly, nonatomic) NSDate *_rentalExpirationDate;
@property (readonly, nonatomic) NSDate *_rentalPlaybackExpirationDate;
@property (readonly, nonatomic, getter=_isRentalPlaybackStarted) BOOL _rentalPlaybackStarted;
@property (readonly, nonatomic) NSDate *_rentalPlaybackStartedDate;
@property (readonly, nonatomic) NSDate *_rentalStartDate;
@property (readonly, nonatomic, getter=isApplicationAuthorizedForPlayback) BOOL applicationAuthorizedForPlayback;
@property (readonly, nonatomic, getter=isAuthorizationRequiredForPlayback) BOOL authorizationRequiredForPlayback;
@property (nonatomic) BOOL automaticallyHandlesInterstitialEvents;
@property (readonly, nonatomic, getter=isContentAuthorizedForPlayback) BOOL contentAuthorizedForPlayback;
@property (readonly) NSError *error;
@property (readonly, nonatomic) NSArray *mediaDataCollectors;
@property (readonly, nonatomic) NSArray *outputs;
@property BOOL playHapticTracks;
@property (copy, nonatomic) NSString *serviceIdentifier;
@property (readonly) NSInteger status;
@property (readonly, nonatomic) AVPlayerItem *templatePlayerItem;


+(?)_createFigPlaybackItemForFigPlayer:(?)arg0 asset:(?)arg1 URL:(?)arg2 flags:(?)arg3 optionsplaybackItem;
+(BOOL)_forNonStreamingURLsFireKVOForAssetWhenReadyForInspection;
+(BOOL)_forStreamingItemsVendAssetWithFigPlaybackItem;
+(BOOL)_hasOverrideForSelector:(SEL)arg0 ;
+(BOOL)automaticallyNotifiesObserversOfAllowProgressiveResume;
+(BOOL)automaticallyNotifiesObserversOfAllowProgressiveStartup;
+(BOOL)automaticallyNotifiesObserversOfAllowProgressiveSwitchUp;
+(BOOL)automaticallyNotifiesObserversOfAsset;
+(BOOL)automaticallyNotifiesObserversOfHasEnabledAudio;
+(BOOL)automaticallyNotifiesObserversOfHasEnabledVideo;
+(BOOL)automaticallyNotifiesObserversOfLoadedTimeRanges;
+(BOOL)automaticallyNotifiesObserversOfNetworkUsuallyExceedsMaxBitRate;
+(BOOL)automaticallyNotifiesObserversOfPlaybackBufferEmpty;
+(BOOL)automaticallyNotifiesObserversOfPlaybackBufferFull;
+(BOOL)automaticallyNotifiesObserversOfPlaybackLikelyToKeepUp;
+(BOOL)automaticallyNotifiesObserversOfPresentationSize;
+(BOOL)automaticallyNotifiesObserversOfSavesDownloadedDataToDiskWhenDone;
+(BOOL)automaticallyNotifiesObserversOfSeekableTimeRanges;
+(BOOL)automaticallyNotifiesObserversOfStatus;
+(BOOL)automaticallyNotifiesObserversOfTracks;
+(BOOL)automaticallyNotifiesObserversOfUsesMinimalLatencyForVideoCompositionRendering;
+(BOOL)automaticallyNotifiesObserversOfVariantIndex;
+(id)_initializeProtectedContentPlaybackSupportSessionAsynchronouslyForProvider:(id)arg0 withOptions:(id)arg1 ;
+(id)playerItemWithAsset:(id)arg0 ;
+(id)playerItemWithAsset:(id)arg0 automaticallyLoadedAssetKeys:(id)arg1 ;
+(id)playerItemWithURL:(id)arg0 ;
+(struct OpaqueCMTimebase *)_copyTimebaseFromFigPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 ;
+(void)_uninitializeProtectedContentPlaybackSupportSession:(id)arg0 ;
+(void)initialize;
-(BOOL)_addToPlayQueueOfFigPlayerOfPlayer:(id)arg0 afterFigPlaybackItemOfItem:(id)arg1 ;
-(BOOL)_canPlayFastForward;
-(BOOL)_canPlayFastReverse;
-(BOOL)_canPlayReverse;
-(BOOL)_canStepBackward;
-(BOOL)_canStepForward;
-(BOOL)_configurePlaybackItemAndReturnError:(*id)arg0 ;
-(BOOL)_getCachedNonForcedSubtitleEnabled:(*BOOL)arg0 ;
-(BOOL)_getCachedPresentationSize:(struct CGSize *)arg0 ;
-(BOOL)_hasEnabledAudio;
-(BOOL)_hasEnabledVideo;
-(BOOL)_hasEnqueuedVideoFrame;
-(BOOL)_hasSelectionInCachedMediaSelectionGroup:(id)arg0 ;
-(BOOL)_isAFileBasedItemThatsReadyToPlay;
-(BOOL)_isFigAssetReadyForInspectionOfMediaSelectionOptions;
-(BOOL)_isFigAssetReadyForInspectionOfMediaSelectionOptionsAndFigPlaybackItemIsReadyForInspection;
-(BOOL)_isNonForcedSubtitleDisplayEnabled;
-(BOOL)_isReadyForBasicInspection;
-(BOOL)_isReadyForInspectionOfDuration;
-(BOOL)_isReadyForInspectionOfPresentationSize;
-(BOOL)_isReadyForInspectionOfRecommendedTimeOffsetFromLive;
-(BOOL)_isReadyForInspectionOfTracks;
-(BOOL)_suppressesVideoLayers;
-(BOOL)_suppressionForOutputs:(id)arg0 ;
-(BOOL)_timeJumpedNotificationIncludesExtendedDiagnosticPayload;
-(BOOL)advanceTimeForOverlappedPlaybackWasSet;
-(BOOL)aggressivelyCachesVideoFrames;
-(BOOL)aggressivelyCachesVideoFramesWasSet;
-(BOOL)allowProgressiveResume;
-(BOOL)allowProgressiveStartup;
-(BOOL)allowProgressiveSwitchUp;
-(BOOL)allowedAudioSpatializationFormatsWasSet;
-(BOOL)allowsExtendedReadAhead;
-(BOOL)alwaysMonitorsPlayability;
-(BOOL)appliesPerFrameHDRDisplayMetadata;
-(BOOL)appliesPerFrameHDRDisplayMetadataWasSet;
-(BOOL)audioSpatializationAllowedWasSet;
-(BOOL)autoSwitchAtmosStreamVariants;
-(BOOL)automaticallyPreservesTimeOffsetFromLive;
-(BOOL)blendsVideoFrames;
-(BOOL)blendsVideoFramesWasSet;
-(BOOL)canPlayFastForward;
-(BOOL)canPlayFastReverse;
-(BOOL)canPlayReverse;
-(BOOL)canPlaySlowForward;
-(BOOL)canPlaySlowReverse;
-(BOOL)canStepBackward;
-(BOOL)canStepForward;
-(BOOL)canUseNetworkResourcesForLiveStreamingWhilePaused;
-(BOOL)continuesPlayingDuringPrerollForRateChange;
-(BOOL)continuesPlayingDuringPrerollForSeek;
-(BOOL)decodesAllFramesDuringOrdinaryPlayback;
-(BOOL)decodesAllFramesDuringOrdinaryPlaybackWasSet;
-(BOOL)hasEnabledAudio;
-(BOOL)hasEnabledVideo;
-(BOOL)hasVideo;
-(BOOL)imageQueueInterpolationCurveWasSet;
-(BOOL)isAudioSpatializationAllowed;
-(BOOL)isNonForcedSubtitleDisplayEnabled;
-(BOOL)isPlaybackBufferEmpty;
-(BOOL)isPlaybackBufferFull;
-(BOOL)isPlaybackLikelyToKeepUp;
-(BOOL)isRenderingSpatialAudio;
-(BOOL)limitReadAhead;
-(BOOL)minimumIntervalForIFrameOnlyPlaybackWasSet;
-(BOOL)networkUsuallyExceedsMaxBitRate;
-(BOOL)playerAppliesAutomaticMediaSelectionToGroup:(id)arg0 ;
-(BOOL)prefersOfflinePlayableVariants;
-(BOOL)requiresAccessLog;
-(BOOL)restrictsAutomaticMediaSelectionToAvailableOfflineOptions;
-(BOOL)reversesMoreVideoFramesInMemory;
-(BOOL)reversesMoreVideoFramesInMemoryWasSet;
-(BOOL)savesDownloadedDataToDiskWhenDone;
-(BOOL)seekToDate:(id)arg0 ;
-(BOOL)seekToDate:(id)arg0 completionHandler:(id)arg1 ;
-(BOOL)seekingWaitsForVideoCompositionRendering;
-(BOOL)speedThresholdForIFrameOnlyPlaybackWasSet;
-(BOOL)startsOnFirstEligibleVariant;
-(BOOL)suppressesAudioOnlyVariants;
-(BOOL)usesIFrameOnlyPlaybackForHighRateScaledEdits;
-(BOOL)usesIFrameOnlyPlaybackForHighRateScaledEditsWasSet;
-(BOOL)usesMinimalLatencyForVideoCompositionRendering;
-(BOOL)willNeverSeekBackwardsHint;
-(CGFloat)liveUpdateInterval;
-(CGFloat)preferredForwardBufferDuration;
-(CGFloat)preferredMaximumAudioSampleRate;
-(CGFloat)preferredPeakBitRate;
-(CGFloat)preferredPeakBitRateForExpensiveNetworks;
-(CGFloat)seekableTimeRangesLastModifiedTime;
-(NSInteger)_availableFileSize;
-(NSInteger)_fileSize;
-(NSInteger)playbackLikelyToKeepUpTrigger;
-(NSInteger)variantIndex;
-(NSUInteger)allowedAudioSpatializationFormats;
-(NSUInteger)restrictions;
-(NSUInteger)variantPreferences;
-(float)maximumBitRate;
-(float)progressTowardsPlaybackLikelyToKeepUp;
-(float)soundCheckVolumeNormalization;
-(float)speedThresholdForIFrameOnlyPlayback;
-(float)volumeAdjustment;
-(id)_URL;
-(id)_cachedTracks;
-(id)_copyStateDispatchQueue;
-(id)_currentMediaSelectionFromFigSelectedMediaArray:(id)arg0 ;
-(id)_enabledTrackFormatDescriptions;
-(id)_ensureAssetWithFigPlaybackItemWithTrackIDs:(id)arg0 ;
-(id)_figSelectedMediaArray;
-(id)_fpNotificationNames;
-(id)_legibleOutputForKey:(id)arg0 ;
-(id)_legibleOutputsForKeys;
-(id)_loadedTimeRanges;
-(id)_loadedTimeRangesFromFPPlaybableTimeIntervals:(id)arg0 ;
-(id)_mediaOptionsSelectedByClient;
-(id)_mediaOptionsSelectedByClientForKey:(id)arg0 ;
-(id)_metadataCollectors;
-(id)_metadataOutputForKey:(id)arg0 ;
-(id)_metadataOutputsForKeys;
-(id)_nameForLogging;
-(id)_nextItem;
-(id)_playbackCoordinator;
-(id)_playbackItemNotificationPayloadToError:(struct __CFDictionary *)arg0 ;
-(id)_playbackProperties;
-(id)_player;
-(id)_playerConnection;
-(id)_preferredPixelBufferAttributes;
-(id)_previousItem;
-(id)_propertyListForMediaSelection:(id)arg0 forGroup:(id)arg1 ;
-(id)_propertyListForSelectedMediaOptionUsingFigSelectedMediaArrayObtainedFromGroup:(id)arg0 ;
-(id)_seekableTimeRanges;
-(id)_seekableTimeRangesFromFPSeekableTimeIntervals:(id)arg0 ;
-(id)_trackWithTrackID:(int)arg0 ;
-(id)_tracks;
-(id)_tracksFromAssetTrackIDs;
-(id)_tracksWithFPTrackIDArray:(id)arg0 fromFigPlaybackItem:(struct OpaqueFigPlaybackItem *)arg1 ;
-(id)_videoOutputs;
-(id)_weakReference;
-(id)accessLog;
-(id)asset;
-(id)audioMix;
-(id)audioTimePitchAlgorithm;
-(id)automaticallyLoadedAssetKeys;
-(id)configurationGroup;
-(id)copy;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)copyWithZone:(struct _NSZone *)arg0 newAssetOptions:(id)arg1 ;
-(id)currentDate;
-(id)currentEstimatedDate;
-(id)currentMediaSelection;
-(id)currentStableVariantID;
-(id)customVideoCompositor;
-(id)delegate;
-(id)description;
-(id)gaplessInfo;
-(id)imageQueueInterpolationCurve;
-(id)init;
-(id)initWithAsset:(id)arg0 ;
-(id)initWithAsset:(id)arg0 automaticallyLoadedAssetKeys:(id)arg1 ;
-(id)initWithURL:(id)arg0 ;
-(id)initialDate;
-(id)initialEstimatedDate;
-(id)loadedTimeRanges;
-(id)loudnessInfo;
-(id)mediaKind;
-(id)nonForcedSubtitleDisplayEnabledPublisher;
-(id)playabilityMetrics;
-(id)presentationSizePublisher;
-(id)seekableTimeRanges;
-(id)selectedMediaOptionInMediaSelectionGroup:(id)arg0 ;
-(id)textHighlightArray;
-(id)textStyleRules;
-(id)timedMetadata;
-(id)tracks;
-(id)tracksPublisher;
-(id)valueForUndefinedKey:(id)arg0 ;
-(id)videoApertureMode;
-(id)videoComposition;
-(id)videoEnhancementMode;
-(int)_CreateSeekID;
-(int)_cancelPendingSeekAndRegisterSeekCompletionHandler:(id)arg0 ;
-(struct ? )_configuredTimeOffsetFromLive;
-(struct ? )_currentTimeWithOptionalFoldedTimebase:(struct OpaqueCMTimebase *)arg0 ;
-(struct ? )_duration;
-(struct ? )_recommendedTimeOffsetFromLive;
-(struct ? )_timeToPauseBuffering;
-(struct ? )_timeToPausePlayback;
-(struct ? )advanceTimeForOverlappedPlayback;
-(struct ? )configuredTimeOffsetFromLive;
-(struct ? )currentTime;
-(struct ? )currentUnfoldedTime;
-(struct ? )duration;
-(struct ? )forwardPlaybackEndTime;
-(struct ? )loopTimeRange;
-(struct ? )maximumForwardBufferDuration;
-(struct ? )maximumTrailingBufferDuration;
-(struct ? )minimumIntervalForIFrameOnlyPlayback;
-(struct ? )recommendedTimeOffsetFromLive;
-(struct ? )reversePlaybackEndTime;
-(struct ? )timeToPauseBuffering;
-(struct ? )timeToPausePlayback;
-(struct CGSize )IFramePrefetchTargetDimensions;
-(struct CGSize )_presentationSize;
-(struct CGSize )preferredMaximumResolution;
-(struct CGSize )preferredMaximumResolutionForExpensiveNetworks;
-(struct CGSize )preferredMinimumResolution;
-(struct CGSize )preferredPeakPresentationSize;
-(struct CGSize )presentationSize;
-(struct OpaqueCMTimebase *)_copyFoldedTimebase;
-(struct OpaqueCMTimebase *)_copyProxyFoldedTimebase;
-(struct OpaqueCMTimebase *)_copyProxyTimebase;
-(struct OpaqueCMTimebase *)_copyProxyUnfoldedTimebase;
-(struct OpaqueCMTimebase *)_copyUnfoldedFigTimebase;
-(struct OpaqueCMTimebase *)timebase;
-(struct OpaqueCMTimebase *)unfoldedTimebase;
-(struct OpaqueFigCPEProtector *)_figCPEProtector;
-(struct OpaqueFigPlaybackItem *)_copyFigPlaybackItem;
-(struct opaqueMTAudioProcessingTap *)audioTapProcessor;
-(unsigned char)_snapTimeToPausePlayback;
-(unsigned char)snapTimeToPausePlayback;
-(unsigned int)RTCReportingFlags;
-(void)_addFAListeners;
-(void)_addFPListeners;
-(void)_addFoldedTBListeners;
-(void)_addInterstitialEventCollector;
-(void)_addLegibleOutput:(id)arg0 ;
-(void)_addMetadataCollector:(id)arg0 ;
-(void)_addMetadataOutput:(id)arg0 ;
-(void)_addSyncLayer:(id)arg0 ;
-(void)_addVideoOutput:(id)arg0 ;
-(void)_allowSelectMediaOptionsAutomaticallyUsingFigSelectedMediaArrayObtainedFromGroup:(id)arg0 ;
-(void)_applyCurrentAudioMix;
-(void)_applyMediaSelectionOptions;
-(void)_attachToFigPlayer;
-(void)_attachToPlayer:(id)arg0 ;
-(void)_cacheMediaSelectionOption:(id)arg0 forMediaSelectionGroup:(id)arg1 ;
-(void)_changeStatusToFailedWithError:(id)arg0 ;
-(void)_clearCachedMediaSelectionGroup:(id)arg0 ;
-(void)_configureVideoCompositionColorProperties;
-(void)_evaluateLegibleOutputs;
-(void)_evaluateMetadataOutputs;
-(void)_evaluateVideoOutputs;
-(void)_figPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 didFlushLegibleOutputWithDictionaryKey:(id)arg1 ;
-(void)_figPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 didFlushMetadataOutputWithDictionaryKey:(id)arg1 ;
-(void)_figPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 didOutputAttributedStrings:(id)arg1 nativeSampleBuffers:(id)arg2 atItemTime:(struct ? )arg3 withLegibleOutputsDictionaryKey:(id)arg4 ;
-(void)_figPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 didOutputSampleBuffers:(id)arg1 fromTrackWithID:(int)arg2 forMetadataOutputWithDictionaryKey:(id)arg3 ;
-(void)_informObserversAboutAvailabilityOfCurrentMediaSelection;
-(void)_informObserversAboutAvailabilityOfDuration:(struct ? )arg0 ;
-(void)_informObserversAboutAvailabilityOfPresentationSize;
-(void)_informObserversAboutAvailabilityOfTracks:(id)arg0 ;
-(void)_insertAfterItem:(id)arg0 ;
-(void)_invokeReadyForEnqueueingHandlers;
-(void)_kickAssetObserversIfAppropriate;
-(void)_makeReadyForEnqueueingWithCompletionHandler:(id)arg0 ;
-(void)_markAsNeedingNewAssetWithFigPlaybackItem;
-(void)_markAsReadyForBasicInspection;
-(void)_markAsReadyForInspectionOfDuration;
-(void)_markAsReadyForInspectionOfPresentationSize;
-(void)_markAsReadyForInspectionOfRecommendedTimeOffsetFromLive;
-(void)_markAsReadyForInspectionOfTracks;
-(void)_markAssetWithFigPlaybackItemAsNeedingNewTracks;
-(void)_markFigAssetAsReadyForInspectionOfMediaSelectionOptions;
-(void)_playerChangeStatusToFailedWithError:(id)arg0 ;
-(void)_quietlySetEQPreset:(int)arg0 ;
-(void)_quietlySetServiceIdentifier:(id)arg0 ;
-(void)_quietlySetVariantIndex:(NSInteger)arg0 ;
-(void)_removeFAListeners;
-(void)_removeFPListeners;
-(void)_removeFoldedTBListeners;
-(void)_removeFromItems;
-(void)_removeFromPlayQueueOfFigPlayerOfAttachedPlayer;
-(void)_removeInterstitialEventCollector;
-(void)_removeLegibleOutput:(id)arg0 ;
-(void)_removeMediaOptionsSelectedByClient;
-(void)_removeMetadataCollector:(id)arg0 ;
-(void)_removeMetadataOutput:(id)arg0 ;
-(void)_removeSyncLayer:(id)arg0 ;
-(void)_removeVideoOutput:(id)arg0 ;
-(void)_renderingSuppressionDidChangeForOutput:(id)arg0 ;
-(void)_respondToBecomingReadyForBasicInspection;
-(void)_respondToBecomingReadyForBasicInspectionWithDuration:(struct ? )arg0 ;
-(void)_selectMediaOption:(id)arg0 inGroup:(id)arg1 cacheIfAppropriate:(BOOL)arg2 ;
-(void)_selectMediaOption:(id)arg0 inMediaSelectionGroup:(id)arg1 cacheIfAppropriate:(BOOL)arg2 ;
-(void)_selectMediaOption:(id)arg0 usingFigSelectedMediaArrayObtainedFromGroup:(id)arg1 ;
-(void)_setAsset:(id)arg0 ;
-(void)_setAssetToAssetWithFigPlaybackItemIfAppropriate;
-(void)_setAudibleDRMInfo:(id)arg0 ;
-(void)_setAudioCurvesAccordingToInputParameters:(id)arg0 forTrackID:(int)arg1 ;
-(void)_setAudioEffectParameters:(id)arg0 forTrackID:(int)arg1 ;
-(void)_setAudioTapProcessor:(struct opaqueMTAudioProcessingTap *)arg0 forTrackID:(int)arg1 ;
-(void)_setAudioTimePitchAlgorithm:(id)arg0 forTrackID:(int)arg1 ;
-(void)_setCurrentMediaSelection:(id)arg0 ;
-(void)_setEQPreset:(int)arg0 ;
-(void)_setMediaOptionsSelectedByClient:(id)arg0 forKey:(id)arg1 ;
-(void)_setPlaybackCoordinator:(id)arg0 ;
-(void)_setRampInOutInfo:(id)arg0 ;
-(void)_setSuppressesVideoLayers:(BOOL)arg0 ;
-(void)_setSyncLayersOnFigPlaybackItem:(id)arg0 ;
-(void)_setTimeJumpedNotificationIncludesExtendedDiagnosticPayload:(BOOL)arg0 ;
-(void)_setTimedMetadata:(id)arg0 ;
-(void)_setURL:(id)arg0 ;
-(void)_setVideoCompositionColorPrimaries:(id)arg0 ;
-(void)_setVideoCompositionColorTransferFunction:(id)arg0 ;
-(void)_setVideoCompositionColorYCbCrMatrix:(id)arg0 ;
-(void)_setVideoCompositionFrameDuration:(struct ? )arg0 ;
-(void)_setVideoCompositionInstructions:(id)arg0 ;
-(void)_setVideoCompositionRenderScale:(float)arg0 ;
-(void)_setVideoCompositionRenderSize:(struct CGSize )arg0 ;
-(void)_setVideoCompositionSourceSampleDataTrackIDs:(id)arg0 ;
-(void)_setVideoCompositionSourceTrackIDForFrameTiming:(int)arg0 ;
-(void)_setVideoCompositor:(*void)arg0 ;
-(void)_unregisterInvokeAndReleasePendingSeekCompletionHandlerForSeekID:(int)arg0 completeAnyPendingSeek:(BOOL)arg1 finished:(BOOL)arg2 ;
-(void)_updateAdvanceTimeForOverlappedPlaybackOnFigPlaybackItem;
-(void)_updateAggressivelyCachesVideoFramesOnFigPlaybackItem;
-(void)_updateAllowedAudioSpatializationFormats;
-(void)_updateAllowedAudioSpatializationFormatsFromFigItem;
-(void)_updateAlwaysMonitorsPlayabilityOnFigPlaybackItem;
-(void)_updateAppliesPerFrameHDRDisplayMetadataOnFigPlaybackItem;
-(void)_updateAudioSpatializationAllowed;
-(void)_updateAudioTapProcessorOnFigPlaybackItem;
-(void)_updateAutoSwitchAtmosStreamVariantsOnFigPlaybackItem;
-(void)_updateBlendsVideoFramesOnFigPlaybackItem;
-(void)_updateCanPlayAndCanStepPropertiesWhenReadyToPlayWithNotificationPayload:(id)arg0 updateStatusToReadyToPlay:(BOOL)arg1 ;
-(void)_updateCanUseNetworkResourcesForLiveStreamingWhilePausedOnFigPlaybackItem;
-(void)_updateConfiguredTimeOffsetFromLiveOnFigPlaybackItem;
-(void)_updateContinuesPlayingDuringPrerollForRateChangeOnFigPlaybackItem;
-(void)_updateContinuesPlayingDuringPrerollForSeekOnFigPlaybackItem;
-(void)_updateDecodesAllFramesDuringOrdinaryPlaybackOnFigPlaybackItem;
-(void)_updateFigTimePitchAlgorithmOnFigPlaybackItem;
-(void)_updateForwardPlaybackEndTimeOnFigPlaybackItem;
-(void)_updateIFramePrefetchTargetDimensionsOnFigPlaybackItem;
-(void)_updateImageQueueInterpolationCurveOnFigPlaybackItem;
-(void)_updateItemIdentifierForCoordinatedPlayback;
-(void)_updateLegibleSuppressionOnFigPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 basedOnOutputs:(id)arg1 ;
-(void)_updateLimitReadAheadOnFigPlaybackItem;
-(void)_updateLoopTimeRangeOnFigPlaybackItem;
-(void)_updateLoudnessInfoOnFigPlaybackItem;
-(void)_updateMaximumForwardBufferDurationOnFigPlaybackItem;
-(void)_updateMaximumTrailingBufferDurationOnFigPlaybackItem;
-(void)_updateMediaKindOnFigPlaybackItem;
-(void)_updateMinimumIntervalForIFrameOnlyPlaybackOnFigPlaybackItem;
-(void)_updateNonForcedSubtitleDisplayEnabledOnFigPlaybackItem;
-(void)_updatePlaybackLikelyToKeepUpTriggerOnFigPlaybackItem;
-(void)_updatePlaybackPropertiesOnFigPlaybackItem;
-(void)_updatePreferredMaximumAudioSampleRateOnFigPlaybackItem;
-(void)_updatePreferredMaximumResolutionForExpensiveNetworksOnFigPlaybackItem;
-(void)_updatePreferredMaximumResolutionOnFigPlaybackItem;
-(void)_updatePreferredMinimumResolutionOnFigPlaybackItem;
-(void)_updatePreferredPeakBitRateForExpensiveNetworksOnFigPlaybackItem;
-(void)_updatePreferredPeakBitRateOnFigPlaybackItem;
-(void)_updatePreservesTimeOffsetFromLive;
-(void)_updateRTCReportingFlagsOnFigPlaybackItem;
-(void)_updateRestrictionsOnFigPlaybackItem;
-(void)_updateRestrictsAutomaticMediaSelectionToAvailableOfflineOptions;
-(void)_updateReversePlaybackEndTimeOnFigPlaybackItem;
-(void)_updateReversesMoreVideoFramesInMemoryOnFigPlaybackItem;
-(void)_updateSeekingWaitsForVideoCompositionRenderingOnFigPlaybackItem;
-(void)_updateSnapTimeToPausePlaybackOnFigPlaybackItem;
-(void)_updateSoundCheckVolumeNormalizationOnFigPlaybackItem;
-(void)_updateSpeedThresholdForIFrameOnlyPlaybackOnFigPlaybackItem;
-(void)_updateStartsOnFirstEligibleVariantOnFigPlaybackItem;
-(void)_updateTaggedMetadataArray:(id)arg0 ;
-(void)_updateTextHighlightArrayOnFigPlaybackItem;
-(void)_updateTextStyleRulesOnFigPlaybackItem;
-(void)_updateTimeToPauseBufferingOnFigPlaybackItem;
-(void)_updateTimeToPausePlaybackOnFigPlaybackItem;
-(void)_updateTimebase;
-(void)_updateUsesIFrameOnlyPlaybackForHighRateScaledEditsOnFigPlaybackItem;
-(void)_updateUsesMinimalLatencyForVideoCompositionRenderingOnFigPlaybackItem;
-(void)_updateVariantPreferencesOnFigPlaybackItem;
-(void)_updateVideoApertureModeOnFigPlaybackItem;
-(void)_updateVideoEnhancementModeOnFigPlaybackItem;
-(void)_updateVideoSuppressionOnFigPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 basedOnOutputs:(id)arg1 ;
-(void)_updateVolumeAdjustmentOnFigPlaybackItem;
-(void)_updateWillNeverSeekBackwardsHintOnFigPlaybackItem;
-(void)addMediaDataCollector:(id)arg0 ;
-(void)addObserver:(id)arg0 forKeyPath:(id)arg1 options:(NSUInteger)arg2 context:(*void)arg3 ;
-(void)addOutput:(id)arg0 ;
-(void)cancelPendingSeeks;
-(void)dealloc;
-(void)removeMediaDataCollector:(id)arg0 ;
-(void)removeOutput:(id)arg0 ;
-(void)seekToTime:(struct ? )arg0 ;
-(void)seekToTime:(struct ? )arg0 completionHandler:(id)arg1 ;
-(void)seekToTime:(struct ? )arg0 toleranceBefore:(struct ? )arg1 toleranceAfter:(struct ? )arg2 ;
-(void)seekToTime:(struct ? )arg0 toleranceBefore:(struct ? )arg1 toleranceAfter:(struct ? )arg2 completionHandler:(id)arg3 ;
-(void)selectMediaOption:(id)arg0 inMediaSelectionGroup:(id)arg1 ;
-(void)selectMediaOptionAutomaticallyInMediaSelectionGroup:(id)arg0 ;
-(void)setAdvanceTimeForOverlappedPlayback:(struct ? )arg0 ;
-(void)setAggressivelyCachesVideoFrames:(BOOL)arg0 ;
-(void)setAllowProgressiveResume:(BOOL)arg0 ;
-(void)setAllowProgressiveStartup:(BOOL)arg0 ;
-(void)setAllowProgressiveSwitchUp:(BOOL)arg0 ;
-(void)setAllowedAudioSpatializationFormats:(NSUInteger)arg0 ;
-(void)setAllowsExtendedReadAhead:(BOOL)arg0 ;
-(void)setAlwaysMonitorsPlayability:(BOOL)arg0 ;
-(void)setAppliesPerFrameHDRDisplayMetadata:(BOOL)arg0 ;
-(void)setAudioMix:(id)arg0 ;
-(void)setAudioSpatializationAllowed:(BOOL)arg0 ;
-(void)setAudioTapProcessor:(struct opaqueMTAudioProcessingTap *)arg0 ;
-(void)setAudioTimePitchAlgorithm:(id)arg0 ;
-(void)setAutoSwitchAtmosStreamVariants:(BOOL)arg0 ;
-(void)setAutomaticallyPreservesTimeOffsetFromLive:(BOOL)arg0 ;
-(void)setBlendsVideoFrames:(BOOL)arg0 ;
-(void)setCanUseNetworkResourcesForLiveStreamingWhilePaused:(BOOL)arg0 ;
-(void)setConfiguredTimeOffsetFromLive:(struct ? )arg0 ;
-(void)setContinuesPlayingDuringPrerollForRateChange:(BOOL)arg0 ;
-(void)setContinuesPlayingDuringPrerollForSeek:(BOOL)arg0 ;
-(void)setDecodesAllFramesDuringOrdinaryPlayback:(BOOL)arg0 ;
-(void)setDelegate:(id)arg0 ;
-(void)setForwardPlaybackEndTime:(struct ? )arg0 ;
-(void)setGaplessInfo:(id)arg0 ;
-(void)setIFramePrefetchTargetDimensions:(struct CGSize )arg0 ;
-(void)setImageQueueInterpolationCurve:(id)arg0 ;
-(void)setInitialDate:(id)arg0 ;
-(void)setInitialEstimatedDate:(id)arg0 ;
-(void)setLimitReadAhead:(BOOL)arg0 ;
-(void)setLoopTimeRange:(struct ? )arg0 ;
-(void)setLoudnessInfo:(id)arg0 ;
-(void)setMaximumBitRate:(float)arg0 ;
-(void)setMaximumForwardBufferDuration:(struct ? )arg0 ;
-(void)setMaximumTrailingBufferDuration:(struct ? )arg0 ;
-(void)setMediaKind:(id)arg0 ;
-(void)setMinimumIntervalForIFrameOnlyPlayback:(struct ? )arg0 ;
-(void)setNetworkUsuallyExceedsMaxBitRate:(BOOL)arg0 ;
-(void)setNonForcedSubtitleDisplayEnabled:(BOOL)arg0 ;
-(void)setPlaybackLikelyToKeepUpTrigger:(NSInteger)arg0 ;
-(void)setPreferredForwardBufferDuration:(CGFloat)arg0 ;
-(void)setPreferredMaximumAudioSampleRate:(CGFloat)arg0 ;
-(void)setPreferredMaximumResolution:(struct CGSize )arg0 ;
-(void)setPreferredMaximumResolutionForExpensiveNetworks:(struct CGSize )arg0 ;
-(void)setPreferredMinimumResolution:(struct CGSize )arg0 ;
-(void)setPreferredPeakBitRate:(CGFloat)arg0 ;
-(void)setPreferredPeakBitRateForExpensiveNetworks:(CGFloat)arg0 ;
-(void)setPreferredPeakPresentationSize:(struct CGSize )arg0 ;
-(void)setPrefersOfflinePlayableVariants:(BOOL)arg0 ;
-(void)setRTCReportingFlags:(unsigned int)arg0 ;
-(void)setRequiresAccessLog:(BOOL)arg0 ;
-(void)setRestrictions:(NSUInteger)arg0 ;
-(void)setRestrictsAutomaticMediaSelectionToAvailableOfflineOptions:(BOOL)arg0 ;
-(void)setReversePlaybackEndTime:(struct ? )arg0 ;
-(void)setReversesMoreVideoFramesInMemory:(BOOL)arg0 ;
-(void)setSavesDownloadedDataToDiskWhenDone:(BOOL)arg0 ;
-(void)setSeekingWaitsForVideoCompositionRendering:(BOOL)arg0 ;
-(void)setSnapTimeToPausePlayback:(unsigned char)arg0 ;
-(void)setSoundCheckVolumeNormalization:(float)arg0 ;
-(void)setSpeedThresholdForIFrameOnlyPlayback:(float)arg0 ;
-(void)setStartsOnFirstEligibleVariant:(BOOL)arg0 ;
-(void)setSuppressesAudioOnlyVariants:(BOOL)arg0 ;
-(void)setTextHighlightArray:(id)arg0 ;
-(void)setTextStyleRules:(id)arg0 ;
-(void)setTimeToPauseBuffering:(struct ? )arg0 ;
-(void)setTimeToPausePlayback:(struct ? )arg0 ;
-(void)setUsesIFrameOnlyPlaybackForHighRateScaledEdits:(BOOL)arg0 ;
-(void)setUsesMinimalLatencyForVideoCompositionRendering:(BOOL)arg0 ;
-(void)setVariantIndex:(NSInteger)arg0 ;
-(void)setVariantPreferences:(NSUInteger)arg0 ;
-(void)setVideoApertureMode:(id)arg0 ;
-(void)setVideoComposition:(id)arg0 ;
-(void)setVideoEnhancementMode:(id)arg0 ;
-(void)setVolumeAdjustment:(float)arg0 ;
-(void)setWillNeverSeekBackwardsHint:(BOOL)arg0 ;
-(void)stepByCount:(NSInteger)arg0 ;


@end


#endif