// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef AVPLAYER_H
#define AVPLAYER_H

@class NSString, NSArray, AVAudioSession, NSError, NSNumber;
@protocol AVAudioSessionParticipant, AVLoggingIdentifier;

#import <Foundation/Foundation.h>

#import "AVPlayerInternal.h"
#import "AVPlayerPlaybackCoordinator.h"

@interface AVPlayer : NSObject <AVAudioSessionParticipant>

 {
    AVPlayerInternal *_player;
}


@property (readonly, nonatomic, getter=_isPIPModePossible) BOOL PIPModePossible;
@property (retain, nonatomic, getter=_STSLabel, setter=_setSTSLabel:) NSString *STSLabel;
@property (copy, nonatomic, setter=_setDisplaysUsedForPlayback:) NSArray *_displaysUsedForPlayback;
@property (readonly, nonatomic) NSInteger _externalProtectionStatus;
@property BOOL allowsOutOfBandTextTrackRendering;
@property BOOL allowsPixelBufferPoolSharing;
@property BOOL appliesMediaSelectionCriteriaAutomatically;
@property (copy) NSString *audioOutputDeviceUniqueID;
@property (readonly, nonatomic, getter=isAudioPlaybackEnabledAtAllRates) BOOL audioPlaybackEnabledAtAllRates;
@property (retain) AVAudioSession *audioSession;
@property (copy, nonatomic) NSString *backgroundPIPAuthorizationToken;
@property (copy, nonatomic) NSString *captionPipelineStrategy;
@property (copy, nonatomic) NSString *captionRenderingStrategy;
@property BOOL disallowsAMRAudio;
@property (nonatomic, getter=_disallowsAutoPauseOnRouteRemovalIfNoAudio, setter=_setDisallowsAutoPauseOnRouteRemovalIfNoAudio:) BOOL disallowsAutoPauseOnRouteRemovalIfNoAudio;
@property (readonly, nonatomic) NSError *error;
@property (readonly, nonatomic) BOOL isSilencedDueToConflictWithOtherPlayback;
@property (retain, nonatomic) NSObject<AVLoggingIdentifier> *loggingIdentifier;
@property float maxRateForAudioPlayback;
@property float minRateForAudioPlayback;
@property (copy) NSString *multichannelAudioStrategy;
@property (readonly, nonatomic) NSNumber *mxSessionID;
@property (readonly) AVPlayerPlaybackCoordinator *playbackCoordinator;
@property (nonatomic) NSUInteger preferredVideoDecoderGPURegistryID;
@property (nonatomic) BOOL prefersPlayingSilentlyWhenConflictingWithOtherPlayback;
@property (nonatomic, getter=_preservesAudioSessionSampleRate, setter=_setPreservesAudioSessionSampleRate:) BOOL preservesAudioSessionSampleRate;
@property (nonatomic) BOOL preventsDisplaySleepDuringVideoPlayback;
@property (nonatomic, getter=_silencesOtherPlaybackDuringPIP, setter=_setSilencesOtherPlaybackDuringPIP:) BOOL silencesOtherPlaybackDuringPIP;
@property (readonly, nonatomic) NSInteger status;
@property (readonly, nonatomic) NSArray *videoTargets;


+(?)_createFigPlayerWithType:(?)arg0 optionsplayer;
+(BOOL)automaticallyNotifiesObserversOfAirPlayVideoActive;
+(BOOL)automaticallyNotifiesObserversOfAutoSwitchStreamVariants;
+(BOOL)automaticallyNotifiesObserversOfCurrentItem;
+(BOOL)automaticallyNotifiesObserversOfExternalPlaybackActive;
+(BOOL)automaticallyNotifiesObserversOfRate;
+(BOOL)automaticallyNotifiesObserversOfUserVolume;
+(BOOL)automaticallyNotifiesObserversOfUsesAirPlayVideoWhileAirPlayScreenIsActive;
+(BOOL)automaticallyNotifiesObserversOfUsesAudioOnlyModeForExternalPlayback;
+(BOOL)automaticallyNotifiesObserversOfUsesLegacyAutomaticWaitingBehavior;
+(BOOL)automaticallyNotifiesObserversOfVibrationPattern;
+(BOOL)eligibleForHDRPlayback;
+(BOOL)isIAPDExtendedModeActive;
+(BOOL)worksAroundConcurrentKVOCrash;
+(NSInteger)availableHDRModes;
+(id)keyPathsForValuesAffectingActionAtItemEnd;
+(id)keyPathsForValuesAffectingClosedCaptionDisplayEnabled;
+(id)keyPathsForValuesAffectingMuted;
+(id)keyPathsForValuesAffectingVolume;
+(id)makePlayerLoggingIdentifier;
+(id)playerWithFigPlayer:(struct OpaqueFigPlayer *)arg0 ;
+(id)playerWithPlayerItem:(id)arg0 ;
+(id)playerWithURL:(id)arg0 ;
+(void)checkForAvailableHDRModesChanges;
+(void)fireAvailableHDRModesDidChangeNotification;
+(void)fireEligibleForHDRPlaybackDidChangeNotification;
+(void)initialize;
+(void)registerForScreenConnectionChanges;
-(BOOL)_CALayerDestinationIsTVOut;
-(BOOL)_airPlayVideoActive;
-(BOOL)_applicationHasExternallyDisplayedAVPlayerLayerAndIsUnderDeviceLock;
-(BOOL)_cachedNonForcedSubtitleDisplayEnabledForCurrentItem;
-(BOOL)_canContinuePlaybackInBackgrounBasedOnAudiovisualBackgroundPlaybackPolicy:(NSInteger)arg0 ;
-(BOOL)_carplayIsActive;
-(BOOL)_clientRequestedPlaybackCoordinator;
-(BOOL)_disallowsVideoLayerDisplayCompositing;
-(BOOL)_dynamicallyChoosesInitialVariant;
-(BOOL)_ensuresActiveAudioSessionWhenStartingPlayback;
-(BOOL)_externalPlaybackActive;
-(BOOL)_getDisplayVideoRange:(*id)arg0 displaySize:(struct CGSize *)arg1 refreshRate:(*id)arg2 ;
-(BOOL)_hasAssociatedAVPlayerLayerInPIPMode;
-(BOOL)_hasAssociatedOnscreenAVPlayerLayer;
-(BOOL)_hasForegroundLayers;
-(BOOL)_hostApplicationHasForegroundExemption;
-(BOOL)_hostApplicationInForeground;
-(BOOL)_isAirPlayVideoActive;
-(BOOL)_isConnectedToPhysicalSecondScreen;
-(BOOL)_isDisplayingClosedCaptions;
-(BOOL)_isIAPDExtendedModeActive;
-(BOOL)_isInterstitialPlayer;
-(BOOL)_isMuted;
-(BOOL)_isVideoPlaybackAllowedWhileInBackground;
-(BOOL)_limitsBandwidthForCellularAccess;
-(BOOL)_pausesAudioVisualPlaybackInBackground;
-(BOOL)_preventsSleepDuringVideoPlayback;
-(BOOL)_rateDidChangeNotificationIncludesExtendedDiagnosticPayload;
-(BOOL)_rateUpdateDuringTransitionDecided;
-(BOOL)_resumePlayback:(CGFloat)arg0 error:(*id)arg1 ;
// -(BOOL)_runOnIvarAccessQueueOperationThatMayChangeCurrentItemWithPreflightBlock:(id)arg0 modificationBlock:(unk)arg1 error:(id)arg2  ;
-(BOOL)_shouldDetachVideoLayersFromFigPlayer;
-(BOOL)_shouldLogPerformanceData;
-(BOOL)_suppressesAudioRendering;
-(BOOL)_usesLegacyAutomaticWaitingBehavior;
-(BOOL)allowsAirPlayVideo;
-(BOOL)allowsExternalPlayback;
-(BOOL)autoSwitchStreamVariants;
-(BOOL)automaticallyWaitsToMinimizeStalling;
-(BOOL)disallowsHardwareAcceleratedVideoDecoder;
-(BOOL)isAirPlayVideoActive;
-(BOOL)isClosedCaptionDisplayEnabled;
-(BOOL)isDisplayingClosedCaptions;
-(BOOL)isExternalPlaybackActive;
-(BOOL)isMuted;
-(BOOL)outputObscuredDueToInsufficientExternalProtection;
-(BOOL)preparesItemsForPlaybackAsynchronously;
-(BOOL)shouldReduceResourceUsage;
-(BOOL)usesAirPlayVideoWhileAirPlayScreenIsActive;
-(BOOL)usesAudioOnlyModeForExternalPlayback;
-(BOOL)usesDedicatedNotificationQueueForMediaServices;
-(BOOL)usesExternalPlaybackWhileExternalScreenIsActive;
-(NSInteger)_clientPriority;
-(NSInteger)_extractFPExternalProtectionStatus:(id)arg0 ;
-(NSInteger)_inferredTimeControlStatusAndWaitingReason:(*id)arg0 forRate:(float)arg1 ;
-(NSInteger)_itemOkayToPlayWhileTransitioningToBackground:(id)arg0 ;
-(NSInteger)_timeControlStatusAndWaitingReason:(*id)arg0 ;
-(NSInteger)_timeControlStatusAndWaitingReason:(*id)arg0 forPlaybackState:(int)arg1 ;
-(NSInteger)_updateWaitingReasonAccordingToInterstitialEventCoordinator:(*id)arg0 forTimeControlStatus:(NSInteger)arg1 ;
-(NSInteger)actionAtItemEnd;
-(NSInteger)audiovisualBackgroundPlaybackPolicy;
-(NSInteger)externalPlaybackType;
-(NSInteger)resourceConservationLevelWhilePaused;
-(NSInteger)timeControlStatus;
-(float)_playerVolume;
-(float)_rate;
-(float)_userVolume;
-(float)rate;
-(float)volume;
-(id)_acquireBackgroundAssertion;
-(id)_ancillaryPerformanceInformationForDisplay;
-(id)_avPlayerLayers;
-(id)_clientName;
-(id)_closedCaptionLayers;
-(id)_copyPerformanceDataForCurrentItem;
-(id)_externalPlaybackVideoGravity;
-(id)_fpNotificationNames;
-(id)_interstitialPlayerIfCreated;
-(id)_items;
-(id)_items_invokeOnIvarAccessQueue;
-(id)_nameForLogging;
-(id)_pendingFigPlayerProperties;
-(id)_pendingFigPlayerPropertyForKey:(id)arg0 ;
-(id)_performanceDictionary;
-(id)_pixelBufferAttributeMediator;
-(id)_playbackDisplaysForFigPlayer;
-(id)_rateDidChangeNotificationPayloadForAVFRateChangeReason:(id)arg0 reasonIsExtendedDiagnostic:(BOOL)arg1 rateChangeIdentifier:(id)arg2 rateChangeOriginator:(id)arg3 ;
-(id)_rateDidChangeNotificationPayloadForFigRateChangeReason:(int)arg0 rateChangeIdentifier:(id)arg1 rateChangeOriginator:(id)arg2 ;
-(id)_stateDispatchQueue;
-(id)_subtitleLayers;
-(id)_synchronizeWithNewCurrentItem;
-(id)_unregisterAndReturnRetainedPrerollCompletionHandler:(SEL)arg0 ;
-(id)_videoLayers;
-(id)_weakReference;
-(id)addBoundaryTimeObserverForTimes:(id)arg0 queue:(id)arg1 usingBlock:(id)arg2 ;
-(id)addPeriodicTimeObserverForInterval:(struct ? )arg0 queue:(id)arg1 usingBlock:(id)arg2 ;
-(id)closedCaptionsDisplayPublisher;
-(id)currentItem;
-(id)currentItemPublisher;
-(id)defaultMediaSelectionCriteriaForMediaCharacteristic:(id)arg0 ;
-(id)dispatchQueue;
-(id)expectedAssetTypes;
-(id)externalPlaybackVideoGravity;
-(id)init;
-(id)initWithDispatchQueue:(id)arg0 ;
-(id)initWithFigPlayer:(struct OpaqueFigPlayer *)arg0 ;
-(id)initWithPlayerItem:(id)arg0 ;
-(id)initWithURL:(id)arg0 ;
-(id)interstitialPlayer;
-(id)mediaSelectionCriteriaForMediaCharacteristic:(id)arg0 ;
-(id)outputContext;
-(id)playerAVAudioSession;
-(id)playerRole;
-(id)reasonForWaitingToPlay;
-(id)valueForUndefinedKey:(id)arg0 ;
-(id)vibrationPattern;
-(int)_cancelPendingPrerollAndRegisterPrerollCompletionHandler:(id)arg0 ;
-(int)_createPrerollID;
-(struct ? )currentTime;
-(struct ? )currentUnfoldedTime;
-(struct CGSize )_cachedPresentationSizeOfCurrentItem;
-(struct CGSize )_maximumAVPlayerLayerDisplaySize;
-(struct CGSize )dimensionsOfReservedVideoMemory;
-(struct OpaqueCMClock *)masterClock;
-(struct OpaqueCMClock *)sourceClock;
-(struct OpaqueFigPlayer *)_copyFigPlayer;
-(struct OpaqueFigPlayerInterstitialCoordinator *)_retainInterstitialCoordinatorIfCreated;
-(struct OpaqueFigPlayerInterstitialCoordinator *)retainInterstitialEventCoordinator;
-(struct __CFDictionary *)_createDictionaryWithDimensionsOfReservedVideoMemory:(struct CGSize )arg0 ;
-(struct __CFString *)figPlayerActionForActionAtItemEnd:(NSInteger)arg0 ;
-(void)_addCaptionLayer:(id)arg0 subtitleLayer:(id)arg1 ;
-(void)_addFPInterstitialCoordinatorListeners;
-(void)_addFPListeners;
-(void)_addItemToLinkedList_invokeOnIvarAccessQueue:(id)arg0 afterItem:(id)arg1 ;
-(void)_addLayer:(id)arg0 ;
-(void)_advanceCurrentItemAccordingToFigPlaybackItem:(struct OpaqueFigPlaybackItem *)arg0 ;
-(void)_advanceToNextItem;
-(void)_applyLinkedListOfItemsToFigPlayerUsingBlock:(id)arg0 ;
-(void)_applyPlayQueueChangesToFigPlayerWithCompletionHandler:(id)arg0 ;
-(void)_attachClosedCaptionLayersToFigPlayer;
-(void)_attachFigPlayerToSubtitleLayers;
-(void)_attachVideoLayersToFigPlayer;
-(void)_changeStatusToFailedWithError:(id)arg0 ;
-(void)_createAndConfigureFigPlayerWithType:(NSInteger)arg0 completionHandler:(id)arg1 ;
-(void)_detachClosedCaptionLayersFromFigPlayer:(struct OpaqueFigPlayer *)arg0 ;
-(void)_detachFigPlayerFromSubtitleLayers;
-(void)_detachVideoLayersForSuspension;
-(void)_detachVideoLayersFromFigPlayer:(struct OpaqueFigPlayer *)arg0 ;
-(void)_didEnterBackground:(id)arg0 ;
-(void)_didFinishSuspension:(id)arg0 ;
-(void)_enqueuePlayQueueModification_invokeOnIvarAccessQueue:(id)arg0 ;
-(void)_ensureFigPlaybackCoordinatorIsConnected;
-(void)_ensureVideoLayersAreAttached;
-(void)_enumerateItemsUsingBlock:(id)arg0 ;
-(void)_evaluateDisplaySizeOfAllAttachedLayers;
-(void)_forceHostApplicationInForeground:(BOOL)arg0 ;
-(void)_insertItem:(id)arg0 afterItem:(id)arg1 ;
-(void)_itemIsReadyToPlay:(id)arg0 ;
-(void)_layerForegroundStateChanged:(id)arg0 ;
-(void)_logPerformanceDataForCurrentItem;
-(void)_logPerformanceDataForPreviousItem;
-(void)_noteCurrentRemoteInterstitialEvent:(id)arg0 ;
-(void)_noteNewNonForcedSubtitleDisplayEnabledForPlayerItem:(id)arg0 ;
-(void)_noteNewPresentationSizeForPlayerItem:(id)arg0 ;
-(void)_noteRemoteInterstitialEvents:(id)arg0 forItem:(id)arg1 ;
-(void)_pixelBufferAttributesDidChangeForLayer:(id)arg0 ;
-(void)_removeAllItems;
-(void)_removeAllLayers;
-(void)_removeCaptionLayer:(id)arg0 subtitleLayer:(id)arg1 ;
-(void)_removeFPInterstitialCoordinatorListeners;
-(void)_removeFPListeners;
-(void)_removeItem:(id)arg0 ;
-(void)_removeItemFromLinkedList_invokeOnIvarAccessQueue:(id)arg0 ;
-(void)_removeLayer:(id)arg0 ;
-(void)_removeLayer:(id)arg0 videoLayer:(id)arg1 closedCaptionLayer:(id)arg2 subtitleLayer:(id)arg3 interstitialLayer:(id)arg4 ;
-(void)_setActionAtItemEnd:(NSInteger)arg0 allowingAdvance:(BOOL)arg1 ;
-(void)_setAncillaryPerformanceInformationForDisplay:(id)arg0 ;
-(void)_setCALayerDestinationIsTVOut:(BOOL)arg0 ;
-(void)_setClientName:(id)arg0 ;
-(void)_setClientPriority:(NSInteger)arg0 ;
-(void)_setCurrentItem:(id)arg0 ;
-(void)_setDisallowsVideoLayerDisplayCompositing:(BOOL)arg0 ;
-(void)_setDynamicallyChoosesInitialVariant:(BOOL)arg0 ;
-(void)_setEQPreset:(int)arg0 ;
-(void)_setEnsuresActiveAudioSessionWhenStartingPlayback:(BOOL)arg0 ;
-(void)_setFigPlaybackItemToMakeCurrent:(struct OpaqueFigPlaybackItem *)arg0 ;
-(void)_setHostApplicationInForeground:(BOOL)arg0 ;
-(void)_setInterstitialPlayer:(id)arg0 ;
-(void)_setInterstitialPlayerGuts:(id)arg0 ;
-(void)_setIsInterstitialPlayer:(BOOL)arg0 ;
-(void)_setLimitsBandwidthForCellularAccess:(BOOL)arg0 ;
-(void)_setNeroVideoGravityOnFigPlayer;
-(void)_setPausesAudioVisualPlaybackInBackground:(BOOL)arg0 ;
-(void)_setPendingFigPlayerProperty:(id)arg0 forKey:(id)arg1 ;
-(void)_setPreferredLanguageList:(id)arg0 ;
-(void)_setPreventsSleepDuringVideoPlayback:(BOOL)arg0 ;
-(void)_setRateDidChangeNotificationIncludesExtendedDiagnosticPayload:(BOOL)arg0 ;
-(void)_setStoppingFadeOutDuration:(float)arg0 ;
-(void)_setSuppressesAudioRendering:(BOOL)arg0 ;
-(void)_setUserVolume:(float)arg0 ;
-(void)_setUsesLegacyAutomaticWaitingBehavior:(BOOL)arg0 ;
-(void)_setWantsVolumeChangesWhenPausedOrInactive:(BOOL)arg0 ;
-(void)_startObservingPropertiesOfCurrentItem:(id)arg0 ;
-(void)_stopObservingPropertiesOfCurrentItem:(id)arg0 ;
-(void)_updateClosedCaptionLayerBounds:(id)arg0 videoRelativeToViewport:(struct CGRect *)arg1 captionsAvoidanceMargins:(struct NSEdgeInsets *)arg2 ;
-(void)_updateConnectionToSecondScreen;
-(void)_updateCurrentItemPreferredPixelBufferAttributesAndVideoLayerSuppression;
-(void)_updateDecoderPixelBufferAttributes:(id)arg0 onFigPlayer:(struct OpaqueFigPlayer *)arg1 ;
-(void)_updatePixelBufferAttributesForLayer:(id)arg0 ;
-(void)_updatePlayerRate:(float)arg0 rateChangeReason:(int)arg1 rateChangeIdentifier:(id)arg2 figPlayerSetRateHandler:(id)arg3 ;
-(void)_updateProxyTimebaseFromNewCurrentItem;
-(void)_updateVideoTargetOnFigPlayer;
-(void)_willEnterForeground:(id)arg0 ;
-(void)addObserver:(id)arg0 forKeyPath:(id)arg1 options:(NSUInteger)arg2 context:(*void)arg3 ;
-(void)addVideoTarget:(struct OpaqueFigVideoTarget *)arg0 ;
-(void)cancelPendingPrerolls;
-(void)dealloc;
-(void)linkInterstitialFigPlayersOnQueue;
-(void)pause;
-(void)pauseWithoutAffectingCoordinatedPlayback;
-(void)play;
-(void)playImmediatelyAtRate:(float)arg0 ;
-(void)prepareItem:(id)arg0 withCompletionHandler:(id)arg1 ;
-(void)prerollAtRate:(float)arg0 completionHandler:(id)arg1 ;
-(void)prerollOperationDidComplete:(BOOL)arg0 notificationPayload:(struct __CFDictionary *)arg1 ;
-(void)removeAudioPlaybackRateLimits;
-(void)removeTimeObserver:(id)arg0 ;
-(void)removeVideoTarget:(struct OpaqueFigVideoTarget *)arg0 ;
-(void)replaceCurrentItemWithPlayerItem:(id)arg0 ;
-(void)seekToDate:(id)arg0 ;
-(void)seekToDate:(id)arg0 completionHandler:(id)arg1 ;
-(void)seekToTime:(struct ? )arg0 ;
-(void)seekToTime:(struct ? )arg0 completionHandler:(id)arg1 ;
-(void)seekToTime:(struct ? )arg0 toleranceBefore:(struct ? )arg1 toleranceAfter:(struct ? )arg2 ;
-(void)seekToTime:(struct ? )arg0 toleranceBefore:(struct ? )arg1 toleranceAfter:(struct ? )arg2 completionHandler:(id)arg3 ;
-(void)setActionAtItemEnd:(NSInteger)arg0 ;
-(void)setAllowsAirPlayVideo:(BOOL)arg0 ;
-(void)setAllowsExternalPlayback:(BOOL)arg0 ;
-(void)setAudiovisualBackgroundPlaybackPolicy:(NSInteger)arg0 ;
-(void)setAutoSwitchStreamVariants:(BOOL)arg0 ;
-(void)setAutomaticallyWaitsToMinimizeStalling:(BOOL)arg0 ;
-(void)setClosedCaptionDisplayEnabled:(BOOL)arg0 ;
-(void)setDimensionsOfReservedVideoMemory:(struct CGSize )arg0 ;
-(void)setDisallowsHardwareAcceleratedVideoDecoder:(BOOL)arg0 ;
-(void)setExpectedAssetTypes:(id)arg0 ;
-(void)setExternalPlaybackVideoGravity:(id)arg0 ;
-(void)setMasterClock:(struct OpaqueCMClock *)arg0 ;
-(void)setMediaSelectionCriteria:(id)arg0 forMediaCharacteristic:(id)arg1 ;
-(void)setMuted:(BOOL)arg0 ;
-(void)setOutputContext:(id)arg0 ;
-(void)setPlayerRole:(id)arg0 ;
-(void)setPlayerRole:(id)arg0 synchronously:(BOOL)arg1 ;
-(void)setPreparesItemsForPlaybackAsynchronously:(BOOL)arg0 ;
-(void)setRate:(float)arg0 ;
-(void)setRate:(float)arg0 time:(struct ? )arg1 atHostTime:(struct ? )arg2 ;
-(void)setRate:(float)arg0 withVolumeRampDuration:(struct ? )arg1 ;
-(void)setRate:(float)arg0 withVolumeRampDuration:(struct ? )arg1 playImmediately:(BOOL)arg2 rateChangeReason:(int)arg3 affectsCoordinatedPlayback:(BOOL)arg4 ;
-(void)setResourceConservationLevelWhilePaused:(NSInteger)arg0 ;
-(void)setShouldReduceResourceUsage:(BOOL)arg0 ;
-(void)setSourceClock:(struct OpaqueCMClock *)arg0 ;
-(void)setUsesAirPlayVideoWhileAirPlayScreenIsActive:(BOOL)arg0 ;
-(void)setUsesAudioOnlyModeForExternalPlayback:(BOOL)arg0 ;
-(void)setUsesDedicatedNotificationQueueForMediaServices:(BOOL)arg0 ;
-(void)setUsesExternalPlaybackWhileExternalScreenIsActive:(BOOL)arg0 ;
-(void)setValue:(id)arg0 forUndefinedKey:(id)arg1 ;
-(void)setVibrationPattern:(id)arg0 ;
-(void)setVolume:(float)arg0 ;
-(void)syncAudioSessionToInterstitialPlayer:(id)arg0 ;


@end


#endif