

#include "SFAcousticFeature.h"
#include "SFVoiceAnalytics.h"
#include "_SFSearchResult.h"
#include "SFSpeechRecognitionTask.h"
#include "_SFSpeechRecognitionBlockTask.h"
#include "_SFSpeechRecognitionDelegateTask.h"
#include "SFRequestParameters.h"
#include "SFSpeechLanguageModel.h"
#include "SFSpeechRecognitionResult.h"
#include "SFSpeechRecognizer.h"
#include "SFTranscriptionSegment.h"
#include "SFLocalSpeechRecognitionClient.h"
#include "SFUtilities.h"
#include "_SFSearchRequest.h"
#include "SFSpeechRecognitionRequest.h"
#include "SFSpeechURLRecognitionRequest.h"
#include "SFSpeechAudioBufferRecognitionRequest.h"
#include "SFTranscription.h"
#include "SFSpeechAssetManager.h"
#include "SFSpeechRecognitionMetadata.h"
