// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef EDAMLIMITSCONSTANTS_H
#define EDAMLIMITSCONSTANTS_H


#import <Foundation/Foundation.h>


@interface EDAMLimitsConstants : NSObject



+(id)EDAM_DEVICE_DESCRIPTION_REGEX;
+(id)EDAM_DEVICE_ID_REGEX;
+(id)EDAM_MIME_TYPE_AMR;
+(id)EDAM_MIME_TYPE_GIF;
+(id)EDAM_MIME_TYPE_INK;
+(id)EDAM_MIME_TYPE_JPEG;
+(id)EDAM_MIME_TYPE_MP3;
+(id)EDAM_MIME_TYPE_MP4_VIDEO;
+(id)EDAM_MIME_TYPE_PDF;
+(id)EDAM_MIME_TYPE_PNG;
+(id)EDAM_MIME_TYPE_WAV;
+(id)EDAM_NOTE_TITLE_REGEX;
+(id)EDAM_TAG_NAME_REGEX;
+(int)EDAM_DEVICE_DESCRIPTION_LEN_MAX;
+(int)EDAM_DEVICE_ID_LEN_MAX;
+(int)EDAM_NOTE_CONTENT_LEN_MAX;
+(int)EDAM_NOTE_CONTENT_LEN_MIN;
+(int)EDAM_NOTE_RESOURCES_MAX;
+(int)EDAM_NOTE_TITLE_LEN_MAX;
+(int)EDAM_NOTE_TITLE_LEN_MIN;
+(int)EDAM_RESOURCE_SIZE_MAX_FREE;
+(int)EDAM_RESOURCE_SIZE_MAX_PREMIUM;
+(int)EDAM_TAG_NAME_LEN_MAX;
+(int)EDAM_TAG_NAME_LEN_MIN;


@end


#endif