

#include "CRDefaultCaptureSessionManager.h"
#include "CRInsightsContext.h"
#include "CRInsightsCodeSection.h"
#include "CRInsights.h"
#include "CRColor.h"
#include "CRAlignmentLayer.h"
#include "CRCameraReaderOutputInternal.h"
#include "CRCameraReaderOutput.h"
#include "CRCameraReaderOutputExpirationDate.h"
#include "CRCameraReaderOutputIDCard.h"
#include "CRCameraReaderOutputCameraText.h"
#include "ActivationMapTools.h"
#include "CRMLCCModel.h"
#include "CRMLFlatModel.h"
#include "CRMLEmbossedNumberModel.h"
#include "CRMLEmbossedCardholderModel.h"
#include "CRMLEmbossedExpirationModel.h"
#include "CRCameraReader.h"
#include "CRCodeRedeemerController.h"
#include "DiagnosticHUDLayer.h"
#include "CRBoxLayer.h"
