// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef UISCROLLVIEW_H
#define UISCROLLVIEW_H

@class CADisplayLink, NSString, NSHashTable, NSTimer, NSMutableDictionary, NSArray, NSISVariable;
@protocol UIScrollViewDelayedTouchesBeganGestureRecognizerClient, UIGestureRecognizerDelegateInternal, UIPanGestureRecognizerDelegateInternal, _UIScrollEventAsyncDeliveryTarget, _UIScrollToTopView, UIIndexBarAccessoryViewDelegate, NSCoding, UIFocusItemScrollableContainer, _UIScrollViewLayoutObserver, _UIScrollViewScrollableAncestor, UIFocusItem, UICoordinateSpace, UIScrollViewDelegate;


#import "UIView.h"
#import "_UIStaticScrollBar.h"
#import "UIScrollViewScrollAnimation.h"
#import "UIViewAnimationState.h"
#import "UIScrollViewDelayedTouchesBeganGestureRecognizer.h"
#import "_UIDragAutoScrollGestureRecognizer.h"
#import "_UIAutoScrollAssistant.h"
#import "UIScrollView.h"
#import "UIRefreshControl.h"
#import "_UIZoomEdgeFeedbackGenerator.h"
#import "_UIFocusFastScrollingRequest.h"
#import "_UIFocusFastScrollingController.h"
#import "_UIFocusFastScrollingIndexBarView.h"
#import "UILayoutGuide.h"
#import "_UIScrollViewScrollIndicator.h"
#import "_UIClickFeedbackGenerator.h"
#import "UIScrollViewKnobLongPressGestureRecognizer.h"
#import "UIHoverGestureRecognizer.h"
#import "UIDelayedAction.h"
#import "_UIScrollViewVFD.h"
#import "_UIFocusSystemSceneComponent.h"
#import "UIPointerRegion.h"
#import "_UIScrollViewAsyncScrollDecelerationState.h"
#import "UIScrollViewMonitor.h"
#import "UIGestureRecognizer.h"
#import "UIPanGestureRecognizer.h"
#import "UIPinchGestureRecognizer.h"

@interface UIScrollView : UIView <UIScrollViewDelayedTouchesBeganGestureRecognizerClient, UIGestureRecognizerDelegateInternal, UIPanGestureRecognizerDelegateInternal, _UIScrollEventAsyncDeliveryTarget, _UIScrollToTopView, UIIndexBarAccessoryViewDelegate, NSCoding, UIFocusItemScrollableContainer>

 {
    CGFloat _refreshControlContentInsetHeight;
    UIEdgeInsets _contentScrollInset;
    _UIStaticScrollBar *_staticScrollBar;
    UIEdgeInsets _scrollIndicatorInset;
    UIEdgeInsets _verticalScrollIndicatorInsets;
    UIEdgeInsets _horizontalScrollIndicatorInsets;
    NSUInteger _edgesAllowingScrollAccessoriesExtendedToBoundingPath;
    CGFloat _startOffsetX;
    CGFloat _startOffsetY;
    CGFloat _lastUpdateOffsetX;
    CGFloat _lastUpdateOffsetY;
    CGFloat _lastUpdateTime;
    CGPoint _lastSetContentOffsetUnrounded;
    CGFloat _lastOffsetUpdateTimeInterval;
    CGSize _lastOffsetUpdateOffset;
    NSInteger _smoothScrollCallbackSkips;
    NSInteger _smoothScrollCallbackCurrentSkipCount;
    CGFloat _minimumZoomScale;
    UIView *_zoomView;
    CGFloat _horizontalVelocity;
    CGFloat _verticalVelocity;
    CGFloat _previousHorizontalVelocity;
    CGFloat _previousVerticalVelocity;
    CADisplayLink *_scrollHeartbeat;
    NSString *_interactionActivityTrackingBaseName;
    id<NSObject>" _activityTrackingTokens;
    CGFloat _telemetryOffsetChangeTime;
    NSInteger _telemetryOffsetChangeCount;
    CGFloat _telemetryOffsetChangeHighRateDuration;
    CGSize _telemetryOffsetChange;
    CGPoint _pageDecelerationTarget;
    CGSize _decelerationFactor;
    CGPoint _adjustedDecelerationTarget;
    CGSize _adjustedDecelerationFactor;
    CGFloat _decelerationLnFactorH;
    CGFloat _decelerationLnFactorV;
    *id _shadows;
    NSHashTable *_scrollNotificationObservers;
    CGFloat _contentOffsetAnimationDuration;
    UIScrollViewScrollAnimation *_animation;
    id *_zoomAnimation;
    UIViewAnimationState *_zoomAnimationState;
    id *_swipe;
    UIScrollViewDelayedTouchesBeganGestureRecognizer *_touchDelayGestureRecognizer;
    UISwipeGestureRecognizer" _lowFidelitySwipeGestureRecognizers;
    _UIDragAutoScrollGestureRecognizer *_dragAutoScrollGestureRecognizer;
    _UIAutoScrollAssistant *_autoScrollAssistant;
    UIScrollView *_draggingChildScrollView;
    CGPoint _parentAdjustment;
    CGFloat _pagingSpringPull;
    CGFloat _pagingFriction;
    NSInteger _fastScrollCount;
    CGFloat _fastScrollMultiplier;
    CGFloat _fastScrollStartMultiplier;
    CGFloat _fastScrollEndTime;
    CGFloat _discreteFastScrollLastHighVelocityEventTime;
    NSInteger _discreteFastScrollCount;
    CGFloat _discreteFastScrollMultiplier;
    CGFloat _discreteFastScrollStartMultiplier;
    CGFloat _discreteFastScrollEndTime;
    CGPoint _rotationCenterPoint;
    CGFloat _accuracy;
    NSUInteger _zoomAnimationCount;
    CGSize _accumulatedOffset;
    NSInteger _touchLevel;
    CGFloat _savedKeyboardAdjustmentDelta;
    CGFloat _keyboardBottomInsetAdjustment;
    CGSize _interpageSpacing;
    CGPoint _pagingOrigin;
    UIOffset _firstPageOffset;
    CGFloat _allowedNavigationOverlapAmount;
    UIRefreshControl *_refreshControl;
    UIView *_relativePanView;
    id<_UIScrollViewLayoutObserver> *_layoutObserver;
    _UIZoomEdgeFeedbackGenerator *_zoomFeedbackGenerator;
    id<_UIScrollViewScrollableAncestor> *_scrollableAncestor;
    UIEdgeInsets _gradientMaskLengths;
    UIEdgeInsets _gradientMaskEdgeInsets;
    _UIFocusFastScrollingRequest *_focusFastScrollingRequest;
    _UIFocusFastScrollingController *_focusFastScrollingController;
    _UIFocusFastScrollingIndexBarView *_focusFastScrollingIndexBarView;
    id<UIFocusItem> *_overridingDestinationItemForFocusUpdate;
    UILayoutGuide *_contentLayoutGuide;
    UILayoutGuide *_contentMarginsGuide;
    UILayoutGuide *_frameLayoutGuide;
    UILayoutGuide *_contentOffsetLayoutGuide;
    NSInteger _contentInsetAdjustmentBehavior;
    CGFloat _velocityScaleFactor;
    BOOL _deferredUpdateTargetIsValid;
    CGPoint _deferredUpdateTargetContentOffset;
    CGSize _deferredUpdateTargetContentSize;
    NSTimer *_verticalScrollIndicatorHideDelayTimer;
    NSTimer *_horizontalScrollIndicatorHideDelayTimer;
    _UIScrollViewScrollIndicator *_verticalScrollIndicator;
    _UIScrollViewScrollIndicator *_horizontalScrollIndicator;
    CGFloat _knobLastFadeTime;
    CGFloat _knobInteractionBeginTime;
    UIEdgeInsets _knobRelativeIndicatorInsets;
    UIEdgeInsets _knobRelativeContentInsets;
    _UIClickFeedbackGenerator *_knobFeedbackGenerator;
    UIScrollViewKnobLongPressGestureRecognizer *_knobLongPressGestureRecognizer;
    UIScrollViewKnobLongPressGestureRecognizer *_knobPointerLongPressGestureRecognizer;
    UIHoverGestureRecognizer *_knobHoverGestureRecognizer;
    UIDelayedAction *_trackpadScrollInterruptionDelayedAction;
    CGFloat _lastScrollInterruptionByPointerEventTime;
    CGFloat _intervalBetweenPanGestures;
    CGFloat _lastPanGestureEndTime;
    CGRect _lastVisibleBounds;
    _UIScrollViewVFD *_vfd;
    _UIFocusSystemSceneComponent *_sceneComponentHoldingLock;
    CGFloat _contentInsetAdjustmentsSum;
    NSMutableDictionary *_contentInsetAdjustments;
    ? _scrollViewFlags;
    NSTimer *_trackingWatchdogTimer;
    NSUInteger _currentScrollDeviceCategory;
    UIPointerRegion *_scrollingPointerRegion;
    NSUInteger _scrollingPointerRegionGenerationID;
    _UIScrollViewAsyncScrollDecelerationState *_asyncScrollDecelerationState;
}


@property (copy, nonatomic, setter=_setAllowedTouchTypesForScrolling:) NSArray *_allowedTouchTypesForScrolling; // ivar: __allowedTouchTypesForScrolling
@property (nonatomic, setter=_setAlternativeVerticalScrollIndicatorTopSafeAreaInset:) CGFloat _alternativeVerticalScrollIndicatorTopSafeAreaInset; // ivar: __alternativeVerticalScrollIndicatorTopSafeAreaInset
@property (nonatomic, setter=_setApplyVerticalSafeAreaInsetsToNonscrollingContent:) BOOL _applyVerticalSafeAreaInsetsToNonscrollingContent;
@property (readonly, nonatomic) _UIAutoScrollAssistant *_autoScrollAssistant;
@property (copy, nonatomic, setter=_setAutomaticContentConstraints:) NSArray *_automaticContentConstraints; // ivar: _automaticContentConstraints
@property (nonatomic, setter=_setConfigureForObservingByTVSearchController:) BOOL _configureForObservingByTVSearchController;
@property (readonly, retain, nonatomic) NSISVariable *_contentHeightVariable; // ivar: _contentHeightVariable
@property (readonly, nonatomic, getter=_contentInsetIncludingDecorations) UIEdgeInsets _contentInsetIncludingDecorations;
@property (readonly, nonatomic) NSUInteger _contentScrollableAxes;
@property (readonly, retain, nonatomic) NSISVariable *_contentWidthVariable; // ivar: _contentWidthVariable
@property (readonly, retain, nonatomic) NSISVariable *_contentXOffsetVariable; // ivar: _contentXOffsetVariable
@property (readonly, retain, nonatomic) NSISVariable *_contentYOffsetVariable; // ivar: _contentYOffsetVariable
@property (readonly, nonatomic, getter=_isInSetContentOffset) BOOL _inSetContentOffset;
@property (readonly, nonatomic) CGFloat _intervalBetweenPanGestures;
@property (retain, nonatomic, setter=_setRefreshControl:) UIRefreshControl *_refreshControl;
@property (retain, nonatomic) UIScrollViewMonitor *_scrollViewMonitor; // ivar: __scrollViewMonitor
@property (readonly, nonatomic, getter=_isScrubbing) BOOL _scrubbing;
@property (nonatomic, setter=_setShouldAdjustLayoutToCollapseTopSpacing:) BOOL _shouldAdjustLayoutToCollapseTopSpacing;
@property (nonatomic, setter=_setShouldAdjustLayoutToDrawTopSeparator:) BOOL _shouldAdjustLayoutToDrawTopSeparator;
@property (nonatomic, setter=_setShouldPreventFocusScrollPastContentSize:) BOOL _shouldPreventFocusScrollPastContentSize;
@property (nonatomic, setter=_setShouldScrollAncestors:) BOOL _shouldScrollAncestors;
@property (readonly, nonatomic) _UIStaticScrollBar *_staticScrollBar;
@property (nonatomic, setter=_setTopLayoutInsetForSidebar:) CGFloat _topLayoutInsetForSidebar; // ivar: _topLayoutInsetForSidebar
@property (nonatomic, setter=_setTopScrollIndicatorFollowsContentOffset:) BOOL _topScrollIndicatorFollowsContentOffset;
@property (nonatomic, setter=_setUseContentDimensionVariablesForConstraintLowering:) BOOL _useContentDimensionVariablesForConstraintLowering; // ivar: _useContentDimensionVariablesForConstraintLowering
@property (nonatomic, setter=_setVerticalScrollIndicatorUsesAlternativeTopSafeAreaInset:) BOOL _verticalScrollIndicatorUsesAlternativeTopSafeAreaInset;
@property (nonatomic, setter=_setWantsConstrainedContentSize:) BOOL _wantsConstrainedContentSize;
@property (readonly, nonatomic) UIEdgeInsets accessoryInsets; // ivar: _accessoryInsets
@property (retain, nonatomic) NSMutableDictionary *accessoryViews; // ivar: _accessoryViews
@property (readonly, nonatomic) UIEdgeInsets adjustedContentInset;
@property (nonatomic, getter=_adjustsTargetsOnContentOffsetChanges, setter=_setAdjustsTargetsOnContentOffsetChanges:) BOOL adjustsTargetsOnContentOffsetChanges;
@property (nonatomic) BOOL alwaysBounceHorizontal;
@property (nonatomic) BOOL alwaysBounceVertical;
@property (readonly, nonatomic, getter=_isAttemptingToEndFocusFastScrolling) BOOL attemptingToEndFocusFastScrolling;
@property (nonatomic) BOOL automaticallyAdjustsScrollIndicatorInsets;
@property (nonatomic) BOOL bounces;
@property (nonatomic) BOOL bouncesZoom;
@property (nonatomic, getter=_cachedHorizontalScrollIndicatorBaseInsets, setter=_setCachedHorizontalScrollIndicatorBaseInsets:) UIEdgeInsets cachedHorizontalScrollIndicatorBaseInsets; // ivar: _cachedHorizontalScrollIndicatorBaseInsets
@property (nonatomic, getter=_cachedVerticalScrollIndicatorBaseInsets, setter=_setCachedVerticalScrollIndicatorBaseInsets:) UIEdgeInsets cachedVerticalScrollIndicatorBaseInsets; // ivar: _cachedVerticalScrollIndicatorBaseInsets
@property (nonatomic) BOOL canCancelContentTouches;
@property (readonly, nonatomic, getter=_canScrollX) BOOL canScrollX;
@property (readonly, nonatomic, getter=_canScrollY) BOOL canScrollY;
@property (nonatomic) UIEdgeInsets contentInset; // ivar: _contentInset
@property (nonatomic) NSInteger contentInsetAdjustmentBehavior;
@property (readonly, nonatomic) UILayoutGuide *contentLayoutGuide;
@property (nonatomic) CGPoint contentOffset;
@property (nonatomic, getter=_contentScrollsAlongXAxis, setter=_setContentScrollsAlongXAxis:) BOOL contentScrollsAlongXAxis;
@property (nonatomic, getter=_contentScrollsAlongYAxis, setter=_setContentScrollsAlongYAxis:) BOOL contentScrollsAlongYAxis;
@property (nonatomic) CGSize contentSize; // ivar: _contentSize
@property (readonly, nonatomic) NSObject<UICoordinateSpace> *coordinateSpace;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic, getter=isDecelerating) BOOL decelerating;
@property (nonatomic) CGFloat decelerationRate;
@property (nonatomic) BOOL delaysContentTouches;
@property (weak, nonatomic) NSObject<UIScrollViewDelegate> *delegate; // ivar: _delegate
@property (readonly, copy) NSString *description;
@property (nonatomic, getter=isDirectionalLockEnabled) BOOL directionalLockEnabled;
@property (readonly, nonatomic) UIGestureRecognizer *directionalPressGestureRecognizer; // ivar: _directionalPressGestureRecognizer
@property (readonly, nonatomic, getter=isDragging) BOOL dragging;
@property (nonatomic, getter=_forwardsTouchesUpResponderChain, setter=_setForwardsTouchesUpResponderChain:) BOOL forwardsTouchesUpResponderChain;
@property (readonly, nonatomic) UILayoutGuide *frameLayoutGuide;
@property (readonly) NSUInteger hash;
@property (readonly, nonatomic, getter=_horizontalScrollIndicator) UIView *horizontalScrollIndicator;
@property (nonatomic) UIEdgeInsets horizontalScrollIndicatorInsets;
@property (nonatomic) NSInteger indexDisplayMode;
@property (nonatomic) NSInteger indicatorStyle;
@property (readonly, nonatomic, getter=_isAnimatingScroll) BOOL isAnimatingScroll;
@property (readonly, nonatomic, getter=_isAnimatingZoom) BOOL isAnimatingZoom;
@property (readonly, nonatomic, getter=_isHorizontalBouncing) BOOL isHorizontalBouncing;
@property (readonly, nonatomic, getter=_isVerticalBouncing) BOOL isVerticalBouncing;
@property (nonatomic) NSInteger keyboardDismissMode; // ivar: _keyboardDismissMode
@property (readonly, nonatomic, getter=_maximumContentOffset) CGPoint maximumContentOffset;
@property (readonly, nonatomic, getter=_maximumContentPoint) CGPoint maximumContentPoint;
@property (nonatomic) CGFloat maximumZoomScale; // ivar: _maximumZoomScale
@property (readonly, nonatomic, getter=_minimumContentOffset) CGPoint minimumContentOffset;
@property (nonatomic) CGFloat minimumZoomScale;
@property (nonatomic, getter=_pageDecelerationTarget, setter=_setPageDecelerationTarget:) CGPoint pageDecelerationTarget;
@property (nonatomic, getter=isPagingEnabled) BOOL pagingEnabled;
@property (readonly, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // ivar: _pan
@property (readonly, nonatomic) UIPinchGestureRecognizer *pinchGestureRecognizer; // ivar: _pinch
@property (nonatomic, getter=isProgrammaticScrollEnabled) BOOL programmaticScrollEnabled;
@property (retain, nonatomic) UIRefreshControl *refreshControl;
@property (nonatomic, getter=isScrollEnabled) BOOL scrollEnabled;
@property (readonly, nonatomic, getter=_scrollHysteresis) CGFloat scrollHysteresis;
@property (nonatomic) UIEdgeInsets scrollIndicatorInsets;
@property (retain, nonatomic) id *scrollTestParameters; // ivar: _scrollTestParameters
@property (readonly, nonatomic, getter=_isScrollingToTop) BOOL scrollingToTop;
@property (nonatomic) BOOL scrollsToTop;
@property (nonatomic, getter=_isShowingFocusFastScrollingPreview, setter=_setShowingFocusFastScrollingPreview:) BOOL showingFocusFastScrollingPreview;
@property (nonatomic) BOOL showsHorizontalScrollIndicator;
@property (nonatomic) BOOL showsVerticalScrollIndicator;
@property (readonly) Class superclass;
@property (readonly, nonatomic, getter=_touchDelayForScrollDetection) CGFloat touchDelayForScrollDetection;
@property (readonly, nonatomic, getter=isTracking) BOOL tracking;
@property (nonatomic, getter=_velocityScaleFactor, setter=_setVelocityScaleFactor:) CGFloat velocityScaleFactor;
@property (readonly, nonatomic, getter=_verticalScrollIndicator) UIView *verticalScrollIndicator;
@property (nonatomic) UIEdgeInsets verticalScrollIndicatorInsets;
@property (readonly, nonatomic) CGSize visibleSize;
@property (nonatomic, getter=_zoomAnchorPoint, setter=_setZoomAnchorPoint:) CGPoint zoomAnchorPoint; // ivar: _zoomAnchorPoint
@property (readonly, nonatomic, getter=isZoomBouncing) BOOL zoomBouncing;
@property (nonatomic) CGFloat zoomScale;
@property (readonly, nonatomic, getter=isZooming) BOOL zooming;


+(CGFloat)_maximumFocusFastScrollingIndexBarWidth;
+(NSUInteger)_defaultEdgesScrollingContentIntoSafeArea;
+(SEL)_panGestureAction;
+(SEL)_pinchGestureAction;
+(id)_implicitAnimationCulprits;
-(BOOL)__canScrollWithoutBouncingYIncludingAdditionalContentInsetAmount:(CGFloat)arg0 ;
-(BOOL)__isKindOfUIScrollView;
-(BOOL)_allowsAsyncScrollEvent;
-(BOOL)_allowsParentToBeginHorizontally;
-(BOOL)_allowsParentToBeginVertically;
-(BOOL)_alwaysAppliesKeyboardBottomInsetAdjustment;
-(BOOL)_applicationHasExplicitlySetBounces;
-(BOOL)_attemptToEndFocusFastScrolling:(BOOL)arg0 ;
-(BOOL)_avoidsJumpOnInterruptedBounce;
-(BOOL)_beginTrackingWithEvent:(id)arg0 ;
-(BOOL)_bounceForCarPlayIfNecessary;
-(BOOL)_canCancelContentTouches:(id)arg0 ;
-(BOOL)_canContentFocusFastScrollInDirection:(NSUInteger)arg0 ;
-(BOOL)_canHandleAsyncScrollEvent;
-(BOOL)_canPerformAsyncScrollDecelerationReturningEvent:(*id)arg0 ;
-(BOOL)_canScrollIgnoringAncestorPermissionX;
-(BOOL)_canScrollIgnoringAncestorPermissionY;
-(BOOL)_canScrollWithoutBouncingIncludingRevealableContentPaddingTopY;
-(BOOL)_canScrollWithoutBouncingX;
-(BOOL)_canScrollWithoutBouncingY;
-(BOOL)_canScrubWithTouch:(id)arg0 ;
-(BOOL)_canSkipTraitsAndOverlayUpdatesForViewControllerToNotifyOnLayoutResetState:(BOOL)arg0 ;
-(BOOL)_constraintAffectsContentSize:(id)arg0 ;
-(BOOL)_contentOffsetWithinFastScrollFocusRestorationRange:(struct CGRect )arg0 ;
-(BOOL)_effectiveShouldPreventFocusScrollPastContentSize;
-(BOOL)_evaluateWantsConstrainedContentSize;
-(BOOL)_focusFastScrollingDisabled;
-(BOOL)_forwardsToParentScroller;
-(BOOL)_gestureRecognizer:(id)arg0 shouldReceiveTouch:(id)arg1 ;
-(BOOL)_gestureRecognizer:(id)arg0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg1 ;
-(BOOL)_getBouncingDecelerationOffset:(*CGFloat)arg0 forTimeInterval:(CGFloat)arg1 lastUpdateOffset:(CGFloat)arg2 min:(CGFloat)arg3 max:(CGFloat)arg4 decelerationFactor:(CGFloat)arg5 decelerationLnFactor:(CGFloat)arg6 velocity:(*CGFloat)arg7 ;
-(BOOL)_getPagingDecelerationOffset:(struct CGPoint *)arg0 forTimeInterval:(CGFloat)arg1 ;
-(BOOL)_hasContentForBarInteractions;
-(BOOL)_hasScrollViewWillEndDraggingInvocationsToPerform;
-(BOOL)_isAutoScrollEnabled;
-(BOOL)_isAutomaticContentOffsetAdjustmentEnabled;
-(BOOL)_isAutoscrolling;
-(BOOL)_isBouncing;
-(BOOL)_isFirstResponderKeyboardAvoidanceEnabled;
-(BOOL)_isFocusFastScrolling;
-(BOOL)_isInterruptingDeceleration;
-(BOOL)_isPoint:(struct CGPoint )arg0 inExpandedIndicatorForAxis:(NSUInteger)arg1 ;
-(BOOL)_isPoint:(struct CGPoint )arg0 inExpandedIndicatorForAxis:(NSUInteger)arg1 containerRect:(struct CGRect )arg2 ;
-(BOOL)_isRectFullyVisible:(struct CGRect )arg0 ;
-(BOOL)_isScrollViewScrollObserver:(id)arg0 ;
-(BOOL)_isScrollingEnabled;
-(BOOL)_needsLayoutOnVisibleBoundsChange;
-(BOOL)_ownsAnimationForKey:(id)arg0 ofView:(id)arg1 ;
-(BOOL)_pagingDown;
-(BOOL)_pagingLeft;
-(BOOL)_pagingRight;
-(BOOL)_pagingUp;
-(BOOL)_panGestureRecognizer:(id)arg0 shouldTryToBeginHorizontallyWithEvent:(id)arg1 ;
-(BOOL)_panGestureRecognizer:(id)arg0 shouldTryToBeginVerticallyWithEvent:(id)arg1 ;
-(BOOL)_requiresExplicitLayoutMarginsGuideForAttribute:(NSInteger)arg0 getAttributeForGuide:(*int)arg1 ;
-(BOOL)_resetScrollingForGestureEvent:(id)arg0 ;
-(BOOL)_resetsBoundingPathForSubtree;
-(BOOL)_scrollToTopIfPossible:(BOOL)arg0 ;
-(BOOL)_scrollViewWillEndDraggingWithDeceleration:(BOOL)arg0 ;
-(BOOL)_scrollsToMakeFirstResponderVisible;
-(BOOL)_shouldAutoScroll;
-(BOOL)_shouldContentOffsetAlwaysIgnoreSafeAreaInsetsChange;
-(BOOL)_shouldContentOffsetMaintainRelativeDistanceFromSafeArea;
-(BOOL)_shouldReverseLayoutDirectionConsideringFlippedHorizontalAxis;
-(BOOL)_shouldScrollToContentBeginningInRightToLeft;
-(BOOL)_shouldTrackImmediatelyWhileDecelerating;
-(BOOL)_showsBackgroundShadow;
-(BOOL)_skipsContentOffsetAdjustmentsIfScrolling;
-(BOOL)_startBeingDraggedByChild:(id)arg0 ;
-(BOOL)_staysCenteredDuringPinch;
-(BOOL)_stopBeingDraggedByChild:(id)arg0 ;
-(BOOL)_subviewPreventsSkipLayout:(id)arg0 ;
-(BOOL)_supportsContentDimensionVariables;
-(BOOL)_supportsPointerDragScrolling;
-(BOOL)_touchMayChangeSelection;
-(BOOL)_transfersScrollToContainer;
-(BOOL)_usesLowFidelityPanning;
-(BOOL)_viewIsInsideNavigationController;
-(BOOL)allowsMultipleFingers;
-(BOOL)cancelMouseTracking;
-(BOOL)cancelTouchTracking;
-(BOOL)gestureRecognizer:(id)arg0 canPreventGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldReceiveTouch:(id)arg1 ;
-(BOOL)isAutomaticContentOffsetAdjustmentsAnimated;
-(BOOL)isElementAccessibilityExposedToInterfaceBuilder;
-(BOOL)isZoomEnabled;
-(BOOL)preservesCenterDuringRotation;
-(BOOL)touchesShouldBegin:(id)arg0 withEvent:(id)arg1 inContentView:(id)arg2 ;
-(BOOL)touchesShouldCancelInContentView:(id)arg0 ;
-(BOOL)tracksImmediatelyWhileDecelerating;
-(BOOL)updateInsetBottomDuringKeyboardDismiss;
-(CGFloat)_adjustedHorizontalOffsetPinnedToScrollableBounds:(CGFloat)arg0 ;
-(CGFloat)_adjustedVerticalOffsetPinnedToScrollableBounds:(CGFloat)arg0 ;
-(CGFloat)_alignedContentMarginGivenMargin:(CGFloat)arg0 ;
-(CGFloat)_allowedNavigationOverlapAmount;
-(CGFloat)_clampedZoomScale:(CGFloat)arg0 allowRubberbanding:(BOOL)arg1 ;
-(CGFloat)_contentBottomForScrollObservation;
-(CGFloat)_contentFitCanScrollThreshold;
-(CGFloat)_currentRubberBandCoefficient;
-(CGFloat)_defaultPagingFriction;
-(CGFloat)_focusFastScrollingBarZPosition;
-(CGFloat)_heightForFocusFastScrollingUI:(CGFloat)arg0 ;
-(CGFloat)_horizontalVelocity;
-(CGFloat)_maxTopOffset;
-(CGFloat)_maxTopOffsetAdjustedForRevealableContentPadding:(CGFloat)arg0 ;
-(CGFloat)_offsetForRubberBandOffset:(CGFloat)arg0 maxOffset:(CGFloat)arg1 minOffset:(CGFloat)arg2 range:(CGFloat)arg3 ;
-(CGFloat)_offsetWithoutDecorationForRubberBandOffset:(CGFloat)arg0 maxOffset:(CGFloat)arg1 minOffset:(CGFloat)arg2 range:(CGFloat)arg3 ;
-(CGFloat)_pagingFriction;
-(CGFloat)_rubberBandOffsetForOffset:(CGFloat)arg0 maxOffset:(CGFloat)arg1 minOffset:(CGFloat)arg2 range:(CGFloat)arg3 outside:(*BOOL)arg4 ;
-(CGFloat)_rubberBandOffsetWithoutDecorationForOffset:(CGFloat)arg0 maxOffset:(CGFloat)arg1 minOffset:(CGFloat)arg2 range:(CGFloat)arg3 outside:(*BOOL)arg4 ;
-(CGFloat)_scrollIndicatorAdditionalInset;
-(CGFloat)_shadowHeightOffset;
-(CGFloat)_systemInsetAdjustmentForAdjustmentTypeIdentifier:(id)arg0 ;
-(CGFloat)_systemInsetAdjustmentSum;
-(CGFloat)_verticalVelocity;
-(CGFloat)_zoomRubberBandScaleForScale:(CGFloat)arg0 ;
-(CGFloat)_zoomScaleForRubberBandScale:(CGFloat)arg0 ;
-(CGFloat)_zoomScaleFromPresentationLayer:(BOOL)arg0 ;
-(CGFloat)horizontalScrollDecelerationFactor;
-(CGFloat)keyboardBottomInsetAdjustmentDelta;
-(CGFloat)verticalScrollDecelerationFactor;
-(NSInteger)_compatibleContentInsetAdjustmentBehavior;
-(NSInteger)_effectiveIndicatorStyle;
-(NSInteger)_focusFastScrollingIndexMaximumSlotCount;
-(NSInteger)_indicatorInsetAdjustmentBehavior;
-(NSInteger)_scrubbingForPoint:(struct CGPoint )arg0 touch:(id)arg1 ;
-(NSInteger)_scrubbingForPoint:(struct CGPoint )arg0 touchType:(NSInteger)arg1 ;
-(NSUInteger)_abuttedEdgesForContentOffset:(struct CGPoint )arg0 ;
-(NSUInteger)_abuttedPagingEdges;
-(NSUInteger)_allowedFocusBounceEdges;
-(NSUInteger)_currentlyAbuttedContentEdges;
-(NSUInteger)_edgesAllowingScrollAccessoriesExtendedToBoundingPath;
-(NSUInteger)_edgesApplyingBaseInsetsToScrollIndicatorInsets;
-(NSUInteger)_edgesApplyingSafeAreaInsetsToContentInset;
-(NSUInteger)_edgesApplyingSafeAreaInsetsToContentInsetForContentSize:(struct CGSize )arg0 ;
-(NSUInteger)_edgesApplyingSafeAreaInsetsToScrollAccessoryInsets;
-(NSUInteger)_edgesPropagatingSafeAreaInsetsToSubviews;
-(NSUInteger)_edgesScrollingContentIntoSafeArea;
-(NSUInteger)_focusPrimaryScrollableAxis;
-(float)_zoomAnimationDurationForScale:(CGFloat)arg0 ;
-(id)_actingParentScrollView;
-(id)_actingParentViewForGestureRecognizers;
-(id)_asyncDeliveryTargetForScrollEvent:(id)arg0 ;
-(id)_backgroundShadowForSlideAnimation;
-(id)_boundingPathForSubtree;
-(id)_constraintsFromContentSize;
-(id)_contentMarginsGuideIfExists;
-(id)_createStaticScrollBar;
-(id)_effectiveInteractionActivityTrackingBaseName;
-(id)_enclosingViewController;
-(id)_focusFastScrollingDestinationItemAtContentEndForIsEndingFastScrolling:(BOOL)arg0 ;
-(id)_focusFastScrollingDestinationItemAtContentStartForIsEndingFastScrolling:(BOOL)arg0 ;
-(id)_focusFastScrollingDestinationItemAtRelativePosition:(CGFloat)arg0 isEndingFastScrolling:(BOOL)arg1 ;
-(id)_focusFastScrollingDestinationItemForIndexEntry:(id)arg0 ;
-(id)_focusFastScrollingDestinationItemForIsEndingFastScrolling:(BOOL)arg0 ;
-(id)_focusFastScrollingDestinationItemNearItem:(id)arg0 atContentEnd:(BOOL)arg1 ;
-(id)_focusFastScrollingIndexBarEntries;
-(id)_focusFastScrollingIndexEntriesForDisplay;
-(id)_frameLayoutItem;
-(id)_getDelegateZoomView;
-(id)_indexBarEntries;
-(id)_layoutGuideOfType:(NSInteger)arg0 createIfNecessary:(BOOL)arg1 ;
-(id)_layoutObserver;
-(id)_layoutVariablesWithAmbiguousValue;
-(id)_observerImplementingWillEndDraggingMethod;
-(id)_overridingPreferredFocusEnvironment;
-(id)_parentScrollView;
-(id)_puic_observerImplementingWillEndDraggingMethod;
-(id)_relativePanView;
-(id)_scrollDetentOffsets;
-(id)_scrollTestExtraResults;
-(id)_scrollViewTouchDelayGesture;
-(id)_swipeGestureRecognizer;
-(id)_touchesDelayedGestureRecognizer;
-(id)_uili_existingObservationEligibleLayoutVariables;
-(id)_zoomFeedbackGenerator;
-(id)accessoryViewAtEdge:(NSInteger)arg0 ;
-(id)hitTest:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(id)initWithCoder:(id)arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)interactionActivityTrackingBaseName;
-(id)nsli_layoutMarginsItem;
-(struct CGPoint )_adjustFocusContentOffset:(struct CGPoint )arg0 toShowFocusItemWithInfo:(id)arg1 ;
-(struct CGPoint )_adjustedContentOffsetForContentOffset:(struct CGPoint )arg0 ;
-(struct CGPoint )_adjustedContentOffsetForContentOffset:(struct CGPoint )arg0 contentSize:(struct CGSize )arg1 skipsAdjustmentIfScrolling:(BOOL)arg2 ;
-(struct CGPoint )_adjustedContentOffsetForContentOffset:(struct CGPoint )arg0 skipsAdjustmentIfScrolling:(BOOL)arg1 ;
-(struct CGPoint )_animatedOriginalOffset;
-(struct CGPoint )_animatedTargetOffset;
-(struct CGPoint )_centeredZoomAnchorPointInScene;
-(struct CGPoint )_clampScrollOffsetToBounds:(struct CGPoint )arg0 ;
-(struct CGPoint )_contentOffsetForLowFidelityScrollInDirection:(struct CGPoint )arg0 duration:(*CGFloat)arg1 ;
-(struct CGPoint )_contentOffsetForScrollingToRect:(struct CGRect )arg0 ;
-(struct CGPoint )_focusTargetOffset;
-(struct CGPoint )_maximumContentOffsetForContentSize:(struct CGSize )arg0 ;
-(struct CGPoint )_newScrollOffsetForScrubReturningAnimated:(*BOOL)arg0 ;
-(struct CGPoint )_offsetToScrollToForArrowPressType:(NSInteger)arg0 ;
-(struct CGPoint )_originalOffsetForAnimatedSetContentOffset;
-(struct CGPoint )_pagingOrigin;
-(struct CGPoint )_roundedProposedContentOffset:(struct CGPoint )arg0 ;
-(struct CGPoint )_rubberBandContentOffsetForOffset:(struct CGPoint )arg0 outsideX:(*BOOL)arg1 outsideY:(*BOOL)arg2 ;
-(struct CGPoint )_velocityForAnimatedScrollFromOffset:(struct CGPoint )arg0 toOffset:(struct CGPoint )arg1 ;
-(struct CGPoint )autoscrollContentOffset;
-(struct CGPoint )indexBarAccessoryView:(id)arg0 contentOffsetForEntry:(id)arg1 atIndex:(NSInteger)arg2 ;
-(struct CGRect )_focusFastScrollingRestorationRect;
-(struct CGRect )_layoutGuide:(id)arg0 adjustedLayoutFrameForFrame:(struct CGRect )arg1 ;
-(struct CGRect )_layoutVerticalScrollIndicatorWithBounds:(struct CGRect )arg0 effectiveInset:(struct UIEdgeInsets )arg1 contentOffset:(struct CGPoint )arg2 fraction:(CGFloat)arg3 additionalInset:(CGFloat)arg4 cornerAdjust:(CGFloat)arg5 needsIndicator:(BOOL)arg6 showing:(BOOL)arg7 recalcSize:(BOOL)arg8 ;
-(struct CGRect )_rectForPageContainingRect:(struct CGRect )arg0 ;
-(struct CGRect )_rectForPageContainingView:(id)arg0 ;
-(struct CGRect )_scrollIndicatorContainerRect;
-(struct CGRect )contentFrameForView:(id)arg0 ;
-(struct CGRect )visibleBounds;
-(struct CGSize )_interpageSpacing;
-(struct UIEdgeInsets )_autoScrollTouchInsets;
-(struct UIEdgeInsets )_baseInsetsForAccessoryOnEdge:(NSInteger)arg0 hasCustomClientInsets:(BOOL)arg1 accessorySize:(CGFloat)arg2 additionalInsetFromEdge:(CGFloat)arg3 ;
-(struct UIEdgeInsets )_collapsableContentPadding;
-(struct UIEdgeInsets )_computeBaseInsetsForHorizontalScrollIndicatorWithClientInsets:(struct UIEdgeInsets )arg0 ;
-(struct UIEdgeInsets )_computeBaseInsetsForVerticalScrollIndicatorWithClientInsets:(struct UIEdgeInsets )arg0 ;
-(struct UIEdgeInsets )_contentScrollInset;
-(struct UIEdgeInsets )_effectiveContentInset;
-(struct UIEdgeInsets )_effectiveGradientMaskLengths;
-(struct UIEdgeInsets )_effectiveHorizontalScrollIndicatorInsets;
-(struct UIEdgeInsets )_effectiveVerticalScrollIndicatorInsets;
-(struct UIEdgeInsets )_focusFastScrollingIndexBarInsets;
-(struct UIEdgeInsets )_focusScrollableAreaInsets;
-(struct UIEdgeInsets )_gradientMaskEdgeInsets;
-(struct UIEdgeInsets )_gradientMaskInsets;
-(struct UIEdgeInsets )_gradientMaskLengths;
-(struct UIEdgeInsets )_revealableContentPadding;
-(struct UIEdgeInsets )_revealableContentPaddingIncludingContentWithCollapsedAffinity:(BOOL)arg0 ;
-(struct UIEdgeInsets )_safeAreaInsetsConsultingAlternativeTopInsetIfApplicable;
-(struct UIEdgeInsets )_systemContentInset;
-(struct UIEdgeInsets )_systemContentInsetIncludingAccessories:(BOOL)arg0 ;
-(struct UIOffset )_firstPageOffset;
-(struct UIOffset )_offsetForCenterOfPossibleZoomView:(id)arg0 withIncomingBoundsSize:(struct CGSize )arg1 ;
-(void)_accumulateViewConstraintsIntoArray:(id)arg0 ;
-(void)_activateZoomFeedback;
-(void)_addContentSubview:(id)arg0 atBack:(BOOL)arg1 ;
-(void)_addRefreshInset:(CGFloat)arg0 ;
-(void)_addScrollViewScrollObserver:(id)arg0 ;
-(void)_adjustBackgroundShadowsForContentSizeForcedVisible:(BOOL)arg0 ;
-(void)_adjustBackgroundShadowsForContentSizeForcedVisible:(BOOL)arg0 withOffset:(CGFloat)arg1 ;
-(void)_adjustContentOffsetIfNecessary;
-(void)_adjustContentSizeForView:(id)arg0 atScale:(CGFloat)arg1 ;
-(void)_adjustCrossingConstraintsIfNecessaryForOldContentInset:(struct UIEdgeInsets )arg0 ;
-(void)_adjustForAutomaticKeyboardInfo:(id)arg0 animated:(BOOL)arg1 lastAdjustment:(*CGFloat)arg2 ;
-(void)_adjustScrollerIndicators:(BOOL)arg0 alwaysShowingThem:(BOOL)arg1 ;
-(void)_adjustScrollerIndicatorsIfNeeded;
-(void)_adjustShadowsIfNecessary;
-(void)_adjustShadowsIfNecessaryForOffset:(CGFloat)arg0 ;
-(void)_adjustStartOffsetForGrabbedBouncingScrollView;
-(void)_applyAutomaticAdjustedContentOffset:(struct CGPoint )arg0 ;
-(void)_applyConstrainedContentSizeIfNecessary;
-(void)_asynchronouslyDeliverScrollEvent:(id)arg0 completion:(id)arg1 ;
-(void)_attemptToBeginFocusFastScrollingWithRequest:(id)arg0 ;
-(void)_attemptToDragParent:(id)arg0 forNewBounds:(struct CGRect )arg1 oldBounds:(struct CGRect )arg2 ;
-(void)_autoScrollAssistantUpdateContentOffset:(struct CGPoint )arg0 ;
-(void)_beginActivityTrackingIfNeededForReason:(NSInteger)arg0 ;
-(void)_beginDeferredContentOffsetTransitionToOffset:(struct CGPoint )arg0 contentSize:(struct CGSize )arg1 ;
-(void)_beginDirectManipulationIfNecessaryWithGestureRecognizer:(id)arg0 ;
-(void)_beginIndicatingFocusFastScrollingDestination;
-(void)_beginRefreshing;
-(void)_beginScrollingCursorOverrideIfNecessary;
-(void)_boundingPathMayHaveChangedForView:(id)arg0 relativeToBoundsOriginOnly:(BOOL)arg1 ;
-(void)_bumpTrackingWatchdogTimer;
-(void)_cancelDeferredContentOffsetTransition;
-(void)_centerContentIfNecessary;
-(void)_centerContentIfNecessaryAdjustingContentOffset:(BOOL)arg0 ;
-(void)_clearContentOffsetAnimation;
-(void)_clearContentOffsetAnimation:(id)arg0 ;
-(void)_clearParentAdjustment;
-(void)_clearScrollBounceStatisticsTrackingState;
-(void)_commitDeferredContentOffsetTransition;
-(void)_commitScrollBounceStatisticsTrackingState;
-(void)_createGestureRecognizersForCurrentTouchLevel;
-(void)_didAddDependentConstraint:(id)arg0 ;
-(void)_didBeginDirectManipulationWithScrubbingDirection:(NSInteger)arg0 ;
-(void)_didChangeFromIdiom:(NSInteger)arg0 onScreen:(id)arg1 traverseHierarchy:(BOOL)arg2 ;
-(void)_didEndDirectManipulationWithScrubbingDirection:(NSInteger)arg0 ;
-(void)_didMoveFromWindow:(id)arg0 toWindow:(id)arg1 ;
-(void)_didRemoveDependentConstraint:(id)arg0 ;
-(void)_didUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)_disableScrollingWithoutAffectingSystemContentInset;
-(void)_enableOnlyGestureRecognizersForCurrentTouchLevel;
-(void)_enableScrollingWithoutAffectingSystemContentInset;
-(void)_endActivityTrackingIfNeededForReason:(NSInteger)arg0 ;
-(void)_endIndicatingFocusFastScrollingDestination;
-(void)_endPanNormal:(BOOL)arg0 ;
-(void)_endRefreshingAnimated:(BOOL)arg0 ;
-(void)_endScrollingCursorOverrideIfNecessary;
-(void)_ensureViewsAreLoadedInRect:(struct CGRect )arg0 ;
-(void)_faultInContentOffsetGuide;
-(void)_findScrollableAncestorIfNeededWithEvent:(id)arg0 ;
-(void)_flashScrollIndicatorsForAxes:(NSUInteger)arg0 persistingPreviousFlashes:(BOOL)arg1 ;
-(void)_flashScrollIndicatorsPersistingPreviousFlashes;
-(void)_focusedItem:(id)arg0 isMinX:(*BOOL)arg1 isMaxX:(*BOOL)arg2 isMinY:(*BOOL)arg3 isMaxY:(*BOOL)arg4 ;
-(void)_forceDelegateScrollViewDidZoom:(BOOL)arg0 ;
-(void)_forcePanGestureToEndImmediately;
-(void)_geometryChanged:(struct ? *)arg0 forAncestor:(id)arg1 ;
-(void)_gestureRecognizerFailed:(id)arg0 ;
-(void)_getGradientMaskBounds:(struct CGRect *)arg0 startInsets:(struct UIEdgeInsets *)arg1 endInsets:(struct UIEdgeInsets *)arg2 intensities:(struct UIEdgeInsets *)arg3 ;
-(void)_getStandardDecelerationOffset:(*CGFloat)arg0 forTimeInterval:(CGFloat)arg1 min:(CGFloat)arg2 max:(CGFloat)arg3 decelerationFactor:(CGFloat)arg4 decelerationLnFactor:(CGFloat)arg5 velocity:(*CGFloat)arg6 ;
-(void)_handleAutoScroll:(id)arg0 ;
-(void)_handleDirectionalPageWithHorizontalVelocity:(CGFloat)arg0 verticalVelocity:(CGFloat)arg1 ;
-(void)_handleDirectionalPress:(id)arg0 ;
-(void)_handleDirectionalScrollToOffset:(struct CGPoint )arg0 clampingToBounds:(BOOL)arg1 ;
-(void)_handleKnobHoverGesture:(id)arg0 ;
-(void)_handleKnobLongPressGesture:(id)arg0 ;
-(void)_handleLowFidelitySwipe:(id)arg0 ;
-(void)_handlePanFailure;
-(void)_handleSwipe:(id)arg0 ;
-(void)_hideScrollIndicator:(id)arg0 afterDelay:(CGFloat)arg1 animated:(BOOL)arg2 ;
-(void)_hideScrollIndicators;
-(void)_incrementForScrollTest:(id)arg0 ;
-(void)_invalidateLayoutForVisibleBounds:(struct CGRect )arg0 oldVisibleBounds:(struct CGRect )arg1 ;
-(void)_layoutAdjustmentsDidChange;
-(void)_layoutFocusFastScrollingUI;
-(void)_layoutHorizontalScrollIndicatorWithBounds:(struct CGRect )arg0 effectiveInset:(struct UIEdgeInsets )arg1 contentOffset:(struct CGPoint )arg2 fraction:(CGFloat)arg3 additionalInset:(CGFloat)arg4 cornerAdjust:(CGFloat)arg5 needsIndicator:(BOOL)arg6 showing:(BOOL)arg7 recalcSize:(BOOL)arg8 verticalIndicatorFrame:(struct CGRect )arg9 ;
-(void)_lowFidelityScrollInDirection:(struct CGPoint )arg0 ;
-(void)_managedSubviewAdded:(id)arg0 ;
-(void)_markScrollViewAnimationForKey:(id)arg0 ofView:(id)arg1 ;
-(void)_moveContentSubview:(id)arg0 toBack:(BOOL)arg1 ;
-(void)_notifyAdjustedContentInsetDidChange;
-(void)_notifyAlignedContentMarginChanged;
-(void)_notifyDidScroll;
-(void)_old_updateAutomaticContentSizeConstraintsIfNecessaryWithContentSize:(struct CGSize )arg0 ;
-(void)_performFullScreenScrollTest:(id)arg0 iterations:(int)arg1 scrollAxis:(NSUInteger)arg2 ;
-(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 ;
-(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 length:(int)arg3 ;
-(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 length:(int)arg3 scrollAxis:(NSUInteger)arg4 ;
-(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 length:(int)arg3 scrollAxis:(NSUInteger)arg4 extraResultsBlock:(id)arg5 ;
// -(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 length:(int)arg3 scrollAxis:(NSUInteger)arg4 extraResultsBlock:(id)arg5 completionBlock:(unk)arg6  ;
-(void)_performScrollTest:(id)arg0 iterations:(int)arg1 delta:(int)arg2 scrollAxis:(NSUInteger)arg3 ;
-(void)_performScrollTestWithParameters:(id)arg0 completionBlock:(id)arg1 ;
-(void)_performScrollViewWillEndDraggingInvocationsWithVelocity:(struct CGPoint )arg0 targetContentOffset:(struct CGPoint *)arg1 unclampedOriginalTarget:(struct CGPoint )arg2 ;
-(void)_pinContentOffsetToClosestPageBoundary;
-(void)_popTrackingRunLoopModeIfNecessaryForReason:(id)arg0 ;
-(void)_populateArchivedSubviews:(id)arg0 ;
-(void)_prepareToPageWithHorizontalVelocity:(CGFloat)arg0 verticalVelocity:(CGFloat)arg1 ;
-(void)_pushTrackingRunLoopModeIfNecessaryForReason:(id)arg0 ;
-(void)_reenableImplicitAnimationsAfterScrollTest;
-(void)_registerAsScrollToTopViewIfPossible;
-(void)_registerForRotation:(BOOL)arg0 ofWindow:(id)arg1 ;
-(void)_registerForSpringBoardBlankedScreenNotification;
-(void)_reloadFocusFastScrollingIndexEntries;
-(void)_removeFocusFastScrollingUI;
-(void)_removeRefreshInset:(CGFloat)arg0 ;
-(void)_removeScrollViewScrollObserver:(id)arg0 ;
-(void)_resetContentScrollableAxes;
-(void)_resetDiscreteFastScroll;
-(void)_resetScrollableAncestor;
-(void)_resetScrollingWithUIEvent:(id)arg0 ;
-(void)_resizeWithOldSuperviewSize:(struct CGSize )arg0 ;
-(void)_runLoopModePopped:(id)arg0 ;
-(void)_scrollToTopFromTouchAtScreenLocation:(struct CGPoint )arg0 resultHandler:(id)arg1 ;
-(void)_scrollViewAnimationEnded:(id)arg0 finished:(BOOL)arg1 ;
-(void)_scrollViewDidEndDecelerating;
-(void)_scrollViewDidEndDeceleratingForDelegate;
-(void)_scrollViewDidEndDraggingForDelegateWithDeceleration:(BOOL)arg0 ;
-(void)_scrollViewDidEndDraggingWithDeceleration:(BOOL)arg0 ;
-(void)_scrollViewDidEndZooming;
-(void)_scrollViewDidLayoutSubviews;
-(void)_scrollViewWillBeginDragging;
-(void)_scrollViewWillBeginZooming;
-(void)_sendDelayedTouchesIfNecessary;
-(void)_sendGeometryAffectingContentBottomChangedToScrollObservers;
-(void)_setAbsoluteContentOffset:(struct CGPoint )arg0 animated:(BOOL)arg1 ;
-(void)_setAllowedFocusBounceEdges:(NSUInteger)arg0 ;
-(void)_setAllowedNavigationOverlapAmount:(CGFloat)arg0 ;
-(void)_setAllowsAsyncScrollEvent:(BOOL)arg0 ;
-(void)_setAllowsParentToBeginHorizontally:(BOOL)arg0 ;
-(void)_setAllowsParentToBeginVertically:(BOOL)arg0 ;
-(void)_setAlwaysAppliesKeyboardBottomInsetAdjustment:(BOOL)arg0 ;
-(void)_setAutoScrollEnabled:(BOOL)arg0 ;
-(void)_setAutoScrollTouchInsets:(struct UIEdgeInsets )arg0 ;
-(void)_setAutomaticContentOffsetAdjustmentEnabled:(BOOL)arg0 ;
-(void)_setAutoscrolling:(BOOL)arg0 ;
-(void)_setAvoidsJumpOnInterruptedBounce:(BOOL)arg0 ;
-(void)_setContentMarginsGuide:(id)arg0 ;
-(void)_setContentScrollInset:(struct UIEdgeInsets )arg0 ;
-(void)_setEdgesAllowingScrollAccessoriesExtendedToBoundingPath:(NSUInteger)arg0 ;
-(void)_setEdgesScrollingContentIntoSafeArea:(NSUInteger)arg0 ;
-(void)_setFirstPageOffset:(struct UIOffset )arg0 ;
-(void)_setFirstResponderKeyboardAvoidanceEnabled:(BOOL)arg0 ;
-(void)_setFlipsHorizontalAxis:(BOOL)arg0 ;
-(void)_setFocusFastScrollingDisabled:(BOOL)arg0 ;
-(void)_setFocusFastScrollingRestorationRect:(struct CGRect )arg0 ;
-(void)_setGradientMaskEdgeInsets:(struct UIEdgeInsets )arg0 ;
-(void)_setGradientMaskInsets:(struct UIEdgeInsets )arg0 ;
-(void)_setGradientMaskLengths:(struct UIEdgeInsets )arg0 ;
-(void)_setIndicatorInsetAdjustmentBehavior:(NSInteger)arg0 ;
-(void)_setInterpageSpacing:(struct CGSize )arg0 ;
-(void)_setKnobInteractionGestureDelayed:(BOOL)arg0 ;
-(void)_setLayoutObserver:(id)arg0 ;
-(void)_setMaskView:(id)arg0 ;
-(void)_setNeedsLayoutOnVisibleBoundsChange:(BOOL)arg0 ;
-(void)_setPagingFriction:(CGFloat)arg0 ;
-(void)_setPagingOrigin:(struct CGPoint )arg0 ;
-(void)_setRelativePanView:(id)arg0 ;
-(void)_setResetsBoundingPathForSubtree:(BOOL)arg0 ;
-(void)_setShouldContentOffsetAlwaysIgnoreSafeAreaInsetsChange:(BOOL)arg0 ;
-(void)_setShowsBackgroundShadow:(BOOL)arg0 ;
-(void)_setSkipsContentOffsetAdjustmentsIfScrolling:(BOOL)arg0 ;
-(void)_setStaysCenteredDuringPinch:(BOOL)arg0 ;
-(void)_setSubviewWantsAutolayoutTripWantsAutolayout:(BOOL)arg0 ;
-(void)_setSupportsPointerDragScrolling:(BOOL)arg0 ;
-(void)_setSystemInsetAdjustment:(CGFloat)arg0 forAdjustmentTypeIdentifier:(id)arg1 ;
-(void)_setTransfersScrollToContainer:(BOOL)arg0 ;
-(void)_setUpGradientMaskViewIfNecessary;
-(void)_setUpdateRequestRecord:(struct _UIUpdateRequestRecord *)arg0 ;
-(void)_setUsesStaticScrollBar:(BOOL)arg0 ;
-(void)_setZoomFeedbackGenerator:(id)arg0 ;
-(void)_showFocusFastScrollingIndexBar:(id)arg0 shouldEmphasize:(BOOL)arg1 ;
-(void)_showFocusFastScrollingIndexBarShouldEmphasize:(BOOL)arg0 ;
// -(void)_simulateGestureWithDuration:(CGFloat)arg0 begin:(id)arg1 update:(unk)arg2 end:(id)arg3  ;
// -(void)_simulateScrollWithTranslation:(struct CGPoint )arg0 duration:(CGFloat)arg1 willBeginDragging:(id)arg2 didEndDragging:(unk)arg3 willBeginDecelerating:(id)arg4 didEndDecelerating:(unk)arg5  ;
// -(void)_simulateZoomByScaleFactor:(CGFloat)arg0 duration:(CGFloat)arg1 willBeginZooming:(id)arg2 didEndZooming:(unk)arg3  ;
-(void)_skipNextStartOffsetAdjustment;
-(void)_smoothScrollAsyncWithUpdateTime:(CGFloat)arg0 state:(id)arg1 ;
-(void)_smoothScrollDisplayLink:(id)arg0 ;
-(void)_smoothScrollSyncWithUpdateTime:(CGFloat)arg0 ;
-(void)_smoothScrollWithUpdateTime:(CGFloat)arg0 ;
-(void)_springBoardBlankedScreenNotification:(id)arg0 ;
-(void)_startDraggingParent:(id)arg0 ;
-(void)_startTimer:(BOOL)arg0 ;
-(void)_staticScrollBar:(id)arg0 didScrollInDirection:(struct CGPoint )arg1 ;
-(void)_stopAutoScrollAssistant;
-(void)_stopDraggingParent:(id)arg0 ;
-(void)_stopScrollDecelerationNotify:(BOOL)arg0 ;
-(void)_stopScrollingAndZoomingAnimations;
-(void)_stopScrollingAndZoomingAnimationsPinningToContentViewport:(BOOL)arg0 ;
-(void)_stopScrollingAndZoomingAnimationsPinningToContentViewport:(BOOL)arg0 tramplingDragFlags:(BOOL)arg1 ;
-(void)_stopScrollingNotify:(BOOL)arg0 pin:(BOOL)arg1 ;
-(void)_stopScrollingNotify:(BOOL)arg0 pin:(BOOL)arg1 tramplingDragFlags:(BOOL)arg2 ;
-(void)_suppressImplicitAnimationsForScrollTest;
-(void)_switchToLayoutEngine:(id)arg0 ;
-(void)_trackingDidBegin;
-(void)_trackingDidEnd;
-(void)_trackpadInterruptScroll:(id)arg0 ;
-(void)_traitCollectionDidChangeInternal:(struct _UITraitCollectionChangeDescription *)arg0 ;
-(void)_unregisterForSpringBoardBlankedScreenNotification;
-(void)_updateAccessories;
-(void)_updateAccessoriesInset;
-(void)_updateContentFitDisableScrolling;
-(void)_updateDecelerationLastOffset:(struct CGPoint )arg0 ;
-(void)_updateDecelerationLastOffsetScrollViewPoint:(struct CGPoint )arg0 ;
-(void)_updateForChangedEdgesConvertingSafeAreaToContentInsetWithOldSystemContentInset:(struct UIEdgeInsets )arg0 oldEdgesPropagatingSafeAreaInsets:(NSUInteger)arg1 adjustContentOffsetIfNecessary:(BOOL)arg2 ;
-(void)_updateForChangedScrollIndicatorRelatedInsets;
-(void)_updateForChangedScrollRelatedInsets;
-(void)_updateGradientMaskView;
-(void)_updateIndicatedFocusFastScrollingDestination;
-(void)_updateLayoutMarginsGuideConstraintsIfNecessary;
-(void)_updatePagingGesture;
-(void)_updatePanGesture;
-(void)_updatePanGestureConfiguration;
-(void)_updatePinchGesture;
-(void)_updatePinchGestureForState:(NSInteger)arg0 ;
-(void)_updateRubberbandingStatisticTrackingState;
-(void)_updateScrollAnimationForChangedTargetOffset:(struct CGPoint )arg0 ;
-(void)_updateScrollGestureRecognizersEnabled;
-(void)_updateUsesStaticScrollBar;
-(void)_updateZoomGestureRecognizersEnabled;
-(void)_webCustomViewWillBeRemovedFromSuperview;
-(void)_willMoveToWindow:(id)arg0 ;
-(void)_zoomAnimationDidStop;
-(void)_zoomToCenter:(struct CGPoint )arg0 scale:(CGFloat)arg1 duration:(CGFloat)arg2 ;
-(void)_zoomToCenter:(struct CGPoint )arg0 scale:(CGFloat)arg1 duration:(CGFloat)arg2 force:(BOOL)arg3 ;
-(void)_zoomToCenterInternal:(struct CGPoint )arg0 scale:(CGFloat)arg1 duration:(CGFloat)arg2 allowRubberbanding:(BOOL)arg3 force:(BOOL)arg4 ;
-(void)accessoryInsetsDidChange:(struct UIEdgeInsets )arg0 ;
-(void)animator:(id)arg0 startAnimation:(id)arg1 ;
-(void)animator:(id)arg0 stopAnimation:(id)arg1 fraction:(float)arg2 ;
-(void)dealloc;
-(void)decodeRestorableStateWithCoder:(id)arg0 ;
-(void)delayed:(id)arg0 ;
-(void)encodeRestorableStateWithCoder:(id)arg0 ;
-(void)encodeWithCoder:(id)arg0 ;
-(void)flashScrollIndicators;
-(void)handlePan:(id)arg0 ;
-(void)handlePinch:(id)arg0 ;
-(void)layoutSubviews;
-(void)nsis_valueOfVariable:(id)arg0 didChangeInEngine:(id)arg1 ;
-(void)performWhileAnimatingAutomaticContentOffsetAdjustments:(id)arg0 ;
-(void)removeFromSuperview;
-(void)scrollRectToVisible:(struct CGRect )arg0 animated:(BOOL)arg1 ;
-(void)setAccessoryView:(id)arg0 atEdge:(NSInteger)arg1 ;
-(void)setAllowsMultipleFingers:(BOOL)arg0 ;
-(void)setAutoscrollContentOffset:(struct CGPoint )arg0 ;
-(void)setBounds:(struct CGRect )arg0 ;
-(void)setCenter:(struct CGPoint )arg0 ;
-(void)setFrame:(struct CGRect )arg0 ;
-(void)setHorizontalScrollDecelerationFactor:(CGFloat)arg0 ;
-(void)setInteractionActivityTrackingBaseName:(id)arg0 ;
-(void)setNeedsLayout;
-(void)setPreservesCenterDuringRotation:(BOOL)arg0 ;
-(void)setSafeAreaInsets:(struct UIEdgeInsets )arg0 ;
-(void)setScrollingEnabled:(BOOL)arg0 ;
-(void)setShowBackgroundShadow:(BOOL)arg0 ;
-(void)setTracksImmediatelyWhileDecelerating:(BOOL)arg0 ;
-(void)setUpdateInsetBottomDuringKeyboardDismiss:(BOOL)arg0 ;
-(void)setUserInteractionEnabled:(BOOL)arg0 ;
-(void)setVerticalScrollDecelerationFactor:(CGFloat)arg0 ;
-(void)setZoomEnabled:(BOOL)arg0 ;
-(void)startScrollViewMonitoring;
-(void)stopScrollViewMonitoring;
-(void)touchesBegan:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesCancelled:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesEnded:(id)arg0 withEvent:(id)arg1 ;
-(void)touchesMoved:(id)arg0 withEvent:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg0 ;
-(void)willAnimateRotationToInterfaceOrientation:(id)arg0 ;
-(void)willRotateToInterfaceOrientation:(id)arg0 ;
-(void)zoomToRect:(struct CGRect )arg0 animated:(BOOL)arg1 ;


@end


#endif