// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef MTEPISODE_H
#define MTEPISODE_H

@class NSManagedObject, NSString, NSAttributedString, NSSet, NSData;


#import "MTPodcast.h"
#import "MTSyncInfo.h"

@interface MTEpisode : NSManagedObject

@property (retain, nonatomic) NSString *assetURL;
@property (nonatomic) BOOL audio;
@property (retain, nonatomic) NSString *author;
@property (nonatomic) BOOL backCatalog;
@property (nonatomic) NSInteger byteSize;
@property (retain, nonatomic) NSString *category;
@property (retain, nonatomic) NSString *cleanedTitle;
@property (nonatomic) NSInteger downloadBehavior;
@property (nonatomic) CGFloat downloadDate;
@property (retain, nonatomic) NSString *downloadPath;
@property (retain, nonatomic) NSString *drmKeyUri;
@property (nonatomic) CGFloat duration;
@property (retain, nonatomic) NSString *enclosureURL;
@property (nonatomic) NSInteger entitlementState;
@property (nonatomic) NSInteger episodeLevel;
@property (nonatomic) NSInteger episodeNumber;
@property (retain, nonatomic) NSString *episodeType;
@property (nonatomic) BOOL explicit;
@property (nonatomic) BOOL externalType;
@property (nonatomic) BOOL feedDeleted;
@property (nonatomic) NSInteger flags;
@property (retain, nonatomic) NSString *guid;
@property (nonatomic) BOOL hasBeenPlayed;
@property (nonatomic) CGFloat importDate;
@property (nonatomic) int importSource;
@property (nonatomic) BOOL isBookmarked;
@property (nonatomic) BOOL isBookmarksMigrationRecoveredEpisode;
@property (nonatomic) BOOL isFromITunesSync;
@property (nonatomic) BOOL isHidden;
@property (nonatomic) BOOL isNew;
@property (retain, nonatomic) NSString *itemDescription;
@property (nonatomic) BOOL itemDescriptionHasHTML;
@property (retain, nonatomic) NSAttributedString *itemDescriptionWithHTML;
@property (retain, nonatomic) NSString *itemDescriptionWithoutHTML;
@property (retain, nonatomic) NSString *itunesSubtitle;
@property (retain, nonatomic) NSString *itunesTitle;
@property (nonatomic) CGFloat lastBookmarkedDate;
@property (nonatomic) CGFloat lastDatePlayed;
@property (nonatomic) CGFloat lastUserMarkedAsPlayedDate;
@property (nonatomic) BOOL listenNowEpisode;
@property (nonatomic) BOOL manuallyAdded;
@property (nonatomic) BOOL metadataFirstSyncEligible;
@property (retain, nonatomic) NSString *metadataIdentifier;
@property (nonatomic) CGFloat metadataTimestamp;
@property (nonatomic) NSInteger persistentID;
@property (nonatomic) NSInteger playCount;
@property (readonly, nonatomic) NSInteger playState;
@property (nonatomic) CGFloat playStateLastModifiedDate;
@property (readonly, nonatomic) BOOL playStateManuallySet;
@property (readonly, nonatomic) NSInteger playStateSource;
@property (nonatomic) float playhead;
@property (retain, nonatomic) NSSet *playlists;
@property (retain, nonatomic) MTPodcast *podcast;
@property (retain, nonatomic) NSString *podcastUuid;
@property (retain, nonatomic) NSString *priceType;
@property (nonatomic) CGFloat pubDate;
@property (nonatomic) BOOL saved;
@property (nonatomic) NSInteger seasonNumber;
@property (retain, nonatomic) NSData *securityScopedAssetData;
@property (nonatomic) BOOL sentNotification;
@property (retain, nonatomic) NSSet *settings;
@property (nonatomic) NSInteger storeTrackId;
@property (nonatomic) BOOL suppressAutoDownload;
@property (retain, nonatomic) MTSyncInfo *syncInfo;
@property (retain, nonatomic) NSString *title;
@property (nonatomic) NSInteger trackNum;
@property (nonatomic) BOOL unplayedTab;
@property (nonatomic) BOOL userDeleted;
@property (nonatomic) BOOL userEpisode;
@property (retain, nonatomic) NSString *uti;
@property (retain, nonatomic) NSString *uuid;
@property (nonatomic) BOOL video;
@property (nonatomic) BOOL visible;
@property (retain, nonatomic) NSString *webpageURL;


+(BOOL)isPlayhead:(CGFloat)arg0 resumableForDuration:(CGFloat)arg1 ;
+(CGFloat)endOfTrackForDuration:(CGFloat)arg0 ;
+(id)_predicateForNotEntitlementState:(NSInteger)arg0 ;
+(id)_predicateForPriceType:(NSInteger)arg0 excluding:(BOOL)arg1 ;
+(id)predicateForAllBookmarkedEpisodes;
+(id)predicateForAllBookmarksMigrationRecoveredEpisodes;
+(id)predicateForAllEpisodes;
+(id)predicateForAllEpisodesIncludingHiddenOnPodcastUuid:(id)arg0 ;
+(id)predicateForAllEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForAllEpisodesOnPodcastUuid:(id)arg0 includeNonAudioEpisodes:(BOOL)arg1 ;
+(id)predicateForAllUnbookmarkedEpisodes;
+(id)predicateForAudio:(BOOL)arg0 ;
+(id)predicateForBacklog:(BOOL)arg0 ;
+(id)predicateForBookmarkedEpisodes;
+(id)predicateForBookmarkedEpisodesExcludingUUIDs:(id)arg0 ;
+(id)predicateForBookmarkedEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForBookmarksMigrationRecoveredEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForDownloadBehavior:(NSInteger)arg0 ;
+(id)predicateForDownloaded:(BOOL)arg0 excludeHidden:(BOOL)arg1 ;
+(id)predicateForDownloadedEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForEpisodeGuid:(id)arg0 ;
+(id)predicateForEpisodeGuid:(id)arg0 onFeedURL:(id)arg1 ;
+(id)predicateForEpisodeGuid:(id)arg0 onPodcastUuid:(id)arg1 ;
+(id)predicateForEpisodeGuids:(id)arg0 ;
+(id)predicateForEpisodeStoreTrackId:(NSInteger)arg0 ;
+(id)predicateForEpisodeStoreTrackIds:(id)arg0 ;
+(id)predicateForEpisodeTitle:(id)arg0 ;
+(id)predicateForEpisodeTitle:(id)arg0 onPodcastUuid:(id)arg1 ;
+(id)predicateForEpisodeType:(NSInteger)arg0 ;
+(id)predicateForEpisodeTypeFilter:(NSInteger)arg0 ;
+(id)predicateForEpisodeUuid:(id)arg0 ;
+(id)predicateForEpisodeUuids:(id)arg0 ;
+(id)predicateForEpisodesDeterminedByLimitSettings:(NSInteger)arg0 ;
+(id)predicateForEpisodesImportedAfterDate:(id)arg0 ;
+(id)predicateForEpisodesInFeedForPodcastUuid:(id)arg0 ;
+(id)predicateForEpisodesInSearchResults;
+(id)predicateForEpisodesInStationShow:(id)arg0 ;
+(id)predicateForEpisodesInStationShow:(id)arg0 excludeUnentitled:(BOOL)arg1 ;
+(id)predicateForEpisodesIsFromiTunesSyncOnPodcastUuid:(id)arg0 ;
+(id)predicateForEpisodesOnPodcastUuid:(id)arg0 deletePlayedEpisodes:(BOOL)arg1 ;
+(id)predicateForEpisodesOnSavedTabForPodcastUuid:(id)arg0 ;
+(id)predicateForEpisodesOnUnplayedTab;
+(id)predicateForEpisodesOnUnplayedTabOnPodcastUuid:(id)arg0 ctx:(id)arg1 ;
+(id)predicateForEpisodesOnUnplayedTabOnPodcastUuid:(id)arg0 deletePlayedEpisodes:(BOOL)arg1 ;
+(id)predicateForEpisodesOnUnplayedTabOnPodcastUuid:(id)arg0 episodeLimit:(NSInteger)arg1 deletePlayedEpisodes:(BOOL)arg2 ;
+(id)predicateForEpisodesPlayableWithoutAccount;
+(id)predicateForEpisodesPublishedAfterDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedAfterOffset:(id)arg0 fromDate:(id)arg1 ;
+(id)predicateForEpisodesPublishedBeforeDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedLastTwoWeeks;
+(id)predicateForEpisodesPublishedLastTwoWeeksWithTodayDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedOnDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedThisMonth;
+(id)predicateForEpisodesPublishedThisMonthWithTodayDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedThisWeek;
+(id)predicateForEpisodesPublishedThisWeekWithTodayDate:(id)arg0 ;
+(id)predicateForEpisodesPublishedToday;
+(id)predicateForEpisodesRequiringAccount;
+(id)predicateForEpisodesWithEpisodeNumbersGreaterThan:(NSInteger)arg0 ;
+(id)predicateForEpisodesWithSeasonNumbersOnPodcastUuid:(id)arg0 ;
+(id)predicateForExplicit:(BOOL)arg0 ;
+(id)predicateForExternalType:(BOOL)arg0 ;
+(id)predicateForFeedDeleted:(BOOL)arg0 ;
+(id)predicateForFeedURL:(id)arg0 ;
+(id)predicateForFeedURLs:(id)arg0 ;
+(id)predicateForHLSDownloadedExcludeHidden:(BOOL)arg0 ;
+(id)predicateForHasBeenPlayed;
+(id)predicateForHasSeasonNumber;
+(id)predicateForHasValidPersistentId:(BOOL)arg0 ;
+(id)predicateForHidingFuturePlayedTimestamps;
+(id)predicateForIsBackCatalogItem;
+(id)predicateForIsFromiTunesSync:(BOOL)arg0 ;
+(id)predicateForIsNew:(BOOL)arg0 ;
+(id)predicateForIsTopLevel;
+(id)predicateForLibraryEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForLimittedEpisodesOnPodcastUuid:(id)arg0 determinedByLimit:(NSInteger)arg1 deletePlayedEpisodes:(BOOL)arg2 ;
+(id)predicateForListenNow;
+(id)predicateForListenNowForPodcastUuid:(id)arg0 ;
+(id)predicateForListenNowLatestEpisodes;
+(id)predicateForMetadataFirstSyncEligible:(BOOL)arg0 ;
+(id)predicateForMyEpisodesOnPodcastUuid:(id)arg0 ctx:(id)arg1 ;
+(id)predicateForMyEpisodesOnPodcastUuid:(id)arg0 deletePlayedEpisodes:(BOOL)arg1 ;
+(id)predicateForNewEpisodesOnPodcastUuid:(id)arg0 ;
+(id)predicateForNotPriceType:(NSInteger)arg0 ;
+(id)predicateForOtherEpisodesOnPodcastUuid:(id)arg0 baseEpisodesPredicate:(id)arg1 deletePlayedEpisodes:(BOOL)arg2 ;
+(id)predicateForPersistentId:(id)arg0 ;
+(id)predicateForPersistentIds:(id)arg0 ;
+(id)predicateForPlayStateManuallySet:(BOOL)arg0 ;
+(id)predicateForPlayed:(BOOL)arg0 ;
+(id)predicateForPlaylistEpisodes;
+(id)predicateForPodcastIsHidden:(BOOL)arg0 ;
+(id)predicateForPodcastIsSubscribed:(BOOL)arg0 ;
+(id)predicateForPodcastPaidSubscriptionActive:(BOOL)arg0 ;
+(id)predicateForPreviouslyPlayed;
+(id)predicateForPreviouslyPlayedHidingFutureTimestamps;
+(id)predicateForPriceType:(NSInteger)arg0 ;
+(id)predicateForPubDateLimit:(NSInteger)arg0 ;
+(id)predicateForRSSEpisodes;
+(id)predicateForRecentlyPlayed;
+(id)predicateForRecentlyPlayedEpisodesToBeDeletedOnPodcastUuid:(id)arg0 deletePlayedEpisodes:(BOOL)arg1 ;
+(id)predicateForSaved:(BOOL)arg0 ;
+(id)predicateForSeasonNumber:(NSInteger)arg0 ;
+(id)predicateForSentNotification:(BOOL)arg0 ;
+(id)predicateForStoreIdentifier:(id)arg0 ;
+(id)predicateForSuppressAutoDownload:(BOOL)arg0 ;
+(id)predicateForUnbookmarkedEpisodes;
+(id)predicateForUnplayedTabFlag:(BOOL)arg0 ;
+(id)predicateForUserEpisode:(BOOL)arg0 ;
+(id)predicateForUserEpisodes;
+(id)predicateForUserEpisodesOnPodcastUuid:(id)arg0 ctx:(id)arg1 ;
+(id)predicateForUserEpisodesOnPodcastUuid:(id)arg0 deletePlayedEpisodes:(BOOL)arg1 ;
+(id)predicateForUserEpisodesOnPodcastUuid:(id)arg0 episodeLimit:(NSInteger)arg1 deletePlayedEpisodes:(BOOL)arg2 ;
+(id)predicateForUserSetTopLevelEpisodes;
+(id)predicateForVideo:(BOOL)arg0 ;
+(id)predicateForVisuallyPlayed:(BOOL)arg0 ;
+(id)propertiesToFetchAssetURL;
+(id)propertiesToFetchBestTitle;
+(id)propertiesToFetchIsBackCatalogItem;
+(id)propertiesToFetchIsExplicit;
+(id)propertiesToFetchIsPartiallyPlayed;
+(id)propertiesToFetchIsPartiallyPlayedBackCatalogItem;
+(id)propertiesToFetchIsPlayed;
+(id)propertiesToFetchIsPlayheadPartiallyPlayed;
+(id)propertiesToFetchIsVisuallyPlayed;
+(id)propertiesToFetchPlaybackProgress;
+(id)propertiesToFetchTimeRemaining;
+(id)propertyPathForPodcastProperty:(id)arg0 ;
+(id)relationshipKeyPathsForPrefetchingIsExplicit;
+(id)sortDescriptorsForDownloadedDateAscending:(BOOL)arg0 ;
+(id)sortDescriptorsForLastBookmarkedDateAscending:(BOOL)arg0 ;
+(id)sortDescriptorsForLastDatePlayedAscending:(BOOL)arg0 ;
+(id)sortDescriptorsForListenNow;
+(id)sortDescriptorsForListenNowLatestEpisodes;
+(id)sortDescriptorsForPubDateAscending:(BOOL)arg0 ;
+(id)sortDescriptorsForRecentlyPlayed;
+(id)sortDescriptorsForSeasonsWithOldestEpisodesFirst:(BOOL)arg0 ;
+(id)sortDescriptorsForTitle;
+(id)userDefaultPropertiesAffectingPredicates;
-(BOOL)isAudio;
-(BOOL)isBackCatalogItem;
-(BOOL)isBonus;
-(BOOL)isDownloaded;
-(BOOL)isExplicit;
-(BOOL)isExternalType;
-(BOOL)isMedia;
-(BOOL)isPartiallyPlayed;
-(BOOL)isPartiallyPlayedBackCatalogItem;
-(BOOL)isPlayed;
-(BOOL)isPlayheadPartiallyPlayed;
-(BOOL)isPlayheadResumable;
-(BOOL)isShareable;
-(BOOL)isTopLevel;
-(BOOL)isTrailer;
-(BOOL)isUnplayed;
-(BOOL)isVideo;
-(BOOL)isVisuallyPlayed;
-(CGFloat)endOfTrack;
-(CGFloat)playbackProgress;
-(CGFloat)playbackProgressSanitized;
-(CGFloat)timeRemaining;
-(NSInteger)mt_syncID;
-(NSInteger)parsePriceType;
-(id)bestSummary;
-(id)bestTitle;
-(id)bestUrl;
-(id)displayURL;
-(id)numberedTitle;
-(id)playURL;
-(void)_setAssetUrl:(id)arg0 ;
-(void)markAsBookmarked;
-(void)markAsBookmarkedOnTimestamp:(CGFloat)arg0 ;
-(void)markAsUnbookmarked;
-(void)setIsTopLevel:(BOOL)arg0 ;
-(void)suppressAutomaticDownloadsIfNeeded;
-(void)unsuppressAutomaticDownloadsIfNeeded;


@end


#endif