// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef _SFAPPPASSWORDSAVINGVIEWCONTROLLER_H
#define _SFAPPPASSWORDSAVINGVIEWCONTROLLER_H

@class SFPasswordViewController, SFQueueingServiceViewControllerProxy<SFPasswordSavingServiceViewControllerProtocol>, NSString;


#import "SFPasswordSavingRemoteViewController.h"

@interface _SFAppPasswordSavingViewController : SFPasswordViewController {
    SFPasswordSavingRemoteViewController *_remoteViewController;
    SFQueueingServiceViewControllerProxy<SFPasswordSavingServiceViewControllerProtocol> *_serviceProxy;
    NSString *_tokenForShowingPrompt;
}




-(id)_connectToServiceWithCompletion:(id)arg0 ;
-(id)_remoteViewController;
-(id)init;
-(void)_setUpServiceProxyIfNeeded;
-(void)credentialsSubmittedForWebsiteURL:(id)arg0 user:(id)arg1 password:(id)arg2 passwordIsAutoGenerated:(BOOL)arg3 completionHandler:(id)arg4 ;
-(void)remoteViewController:(id)arg0 viewServiceDidTerminateWithError:(id)arg1 ;
-(void)remoteViewControllerWillDismiss:(id)arg0 ;
-(void)viewDidAppear:(BOOL)arg0 ;
-(void)viewDidLoad;


@end


#endif