// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef WEBVIEW_H
#define WEBVIEW_H

@class WAKView, NSString, NSURL, WAKWindow, NSData, NSUndoManager, WebScriptObject;
@protocol WebUIDelegate, WebDownloadDelegate, WebEditingDelegate, WebFrameLoadDelegate, WebPolicyDelegate, WebResourceLoadDelegate;


#import "WebViewPrivate.h"
#import "WebBackForwardList.h"
#import "WebUITextIndicatorData.h"
#import "WebFrame.h"
#import "DOMDocument.h"
#import "WebPreferences.h"
#import "DOMRange.h"
#import "DOMCSSStyleDeclaration.h"

@interface WebView : WAKView {
    WebViewPrivate *_private;
}


@property (nonatomic) NSObject<WebUIDelegate> *UIDelegate;
@property (readonly, nonatomic) NSUInteger _dragSourceAction;
@property (readonly, nonatomic) CGRect _draggedElementBounds;
@property (readonly, nonatomic) NSString *_draggedLinkTitle;
@property (readonly, nonatomic) NSURL *_draggedLinkURL;
@property (nonatomic, setter=_setUnobscuredSafeAreaInsets:) WebEdgeInsets _unobscuredSafeAreaInsets;
@property (nonatomic, setter=_setUseDarkAppearance:) BOOL _useDarkAppearance;
@property (nonatomic, setter=_setUseElevatedUserInterfaceLevel:) BOOL _useElevatedUserInterfaceLevel;
@property (nonatomic, setter=_setUseSystemAppearance:) BOOL _useSystemAppearance;
@property (copy, nonatomic) NSString *applicationNameForUserAgent;
@property (readonly, nonatomic) WebBackForwardList *backForwardList;
@property (readonly, nonatomic) BOOL canGoBack;
@property (readonly, nonatomic) BOOL canGoForward;
@property (readonly, nonatomic) BOOL canMakeTextLarger;
@property (readonly, nonatomic) BOOL canMakeTextSmaller;
@property (readonly, nonatomic) BOOL canMakeTextStandardSize;
@property (nonatomic, getter=isContinuousSpellCheckingEnabled) BOOL continuousSpellCheckingEnabled;
@property (copy, nonatomic) NSString *customTextEncodingName;
@property (copy, nonatomic) NSString *customUserAgent;
@property (readonly, nonatomic, getter=_dataInteractionCaretRect) CGRect dataInteractionCaretRect;
@property (readonly, nonatomic, getter=_dataOperationTextIndicator) WebUITextIndicatorData *dataOperationTextIndicator;
@property (nonatomic) NSObject<WebDownloadDelegate> *downloadDelegate;
@property (nonatomic) BOOL drawsBackground;
@property (nonatomic, getter=isEditable) BOOL editable;
@property (nonatomic) NSObject<WebEditingDelegate> *editingDelegate;
@property (readonly, nonatomic) CGFloat estimatedProgress;
@property (nonatomic) NSObject<WebFrameLoadDelegate> *frameLoadDelegate;
@property (copy, nonatomic) NSString *groupName;
@property (retain, nonatomic) WAKWindow *hostWindow;
@property (readonly, nonatomic, getter=isLoading) BOOL loading;
@property (readonly, nonatomic) WebFrame *mainFrame;
@property (readonly, nonatomic) DOMDocument *mainFrameDocument;
@property (readonly, copy, nonatomic) NSString *mainFrameTitle;
@property (copy, nonatomic) NSString *mainFrameURL;
@property (readonly, nonatomic) BOOL maintainsInactiveSelection;
@property (copy, nonatomic) NSString *mediaStyle;
@property (nonatomic) NSObject<WebPolicyDelegate> *policyDelegate;
@property (retain, nonatomic) WebPreferences *preferences;
@property (copy, nonatomic) NSString *preferencesIdentifier;
@property (nonatomic) NSObject<WebResourceLoadDelegate> *resourceLoadDelegate;
@property (readonly, nonatomic) DOMRange *selectedDOMRange;
@property (readonly, nonatomic) WebFrame *selectedFrame;
@property (readonly, nonatomic) NSUInteger selectionAffinity;
@property (nonatomic) BOOL shouldCloseWithWindow;
@property (nonatomic) BOOL shouldUpdateWhileOffscreen;
@property (nonatomic) BOOL smartInsertDeleteEnabled;
@property (copy, nonatomic, getter=_sourceApplicationAuditData, setter=_setSourceApplicationAuditData:) NSData *sourceApplicationAuditData;
@property (readonly, nonatomic) BOOL supportsTextEncoding;
@property (nonatomic) float textSizeMultiplier;
@property (retain, nonatomic) DOMCSSStyleDeclaration *typingStyle;
@property (readonly, nonatomic) NSUndoManager *undoManager;
@property (readonly, nonatomic) WebScriptObject *windowScriptObject;


+(BOOL)_HTTPPipeliningEnabled;
+(BOOL)_canHandleRequest:(id)arg0 ;
+(BOOL)_canHandleRequest:(id)arg0 forMainFrame:(BOOL)arg1 ;
+(BOOL)_canShowMIMEType:(id)arg0 allowingPlugins:(BOOL)arg1 ;
+(BOOL)_didSetCacheModel;
+(BOOL)_hasRemoteInspectorSession;
+(BOOL)_isIconLoadingEnabled;
+(BOOL)_isRemoteInspectorEnabled;
+(BOOL)_isUnderMemoryPressure;
+(BOOL)_representationExistsForURLScheme:(id)arg0 ;
+(BOOL)_shouldUseFontSmoothing;
+(BOOL)_viewClass:(*Class)arg0 andRepresentationClass:(*Class)arg1 forMIMEType:(id)arg2 allowingPlugins:(BOOL)arg3 ;
+(BOOL)canCloseAllWebViews;
+(BOOL)canShowFile:(id)arg0 ;
+(BOOL)canShowMIMEType:(id)arg0 ;
+(BOOL)canShowMIMETypeAsHTML:(id)arg0 ;
+(BOOL)isCharacterSmartReplaceExempt:(unsigned short)arg0 isPreviousCharacter:(BOOL)arg1 ;
+(BOOL)shouldIncludeInWebKitStatistics;
+(Class)_getPDFRepresentationClass;
+(Class)_getPDFViewClass;
+(NSUInteger)_cacheModel;
+(NSUInteger)_maxCacheModelInAnyInstance;
+(id)MIMETypesShownAsHTML;
+(id)_MIMETypeForFile:(id)arg0 ;
+(id)_decodeData:(id)arg0 ;
+(id)_generatedMIMETypeForURLScheme:(id)arg0 ;
+(id)_productivityDocumentMIMETypes;
+(id)_standardUserAgentWithApplicationName:(id)arg0 ;
+(id)_supportedMIMETypes;
+(void)_addOriginAccessAllowListEntryWithSourceOrigin:(id)arg0 destinationProtocol:(id)arg1 destinationHost:(id)arg2 allowDestinationSubdomains:(BOOL)arg3 ;
+(void)_addUserScriptToGroup:(id)arg0 world:(id)arg1 source:(id)arg2 url:(id)arg3 includeMatchPatternStrings:(id)arg4 excludeMatchPatternStrings:(id)arg5 injectionTime:(int)arg6 injectedFrames:(int)arg7 ;
+(void)_addUserStyleSheetToGroup:(id)arg0 world:(id)arg1 source:(id)arg2 url:(id)arg3 includeMatchPatternStrings:(id)arg4 excludeMatchPatternStrings:(id)arg5 injectedFrames:(int)arg6 ;
+(void)_cacheModelChangedNotification:(id)arg0 ;
+(void)_disableAutoStartRemoteInspector;
+(void)_disableRemoteInspector;
+(void)_doNotStartObservingNetworkReachability;
+(void)_enableRemoteInspector;
+(void)_makeAllWebViewsPerformSelector:(SEL)arg0 ;
+(void)_preferencesRemovedNotification:(id)arg0 ;
+(void)_preflightSpellChecker;
+(void)_preflightSpellCheckerNow:(id)arg0 ;
+(void)_registerPluginMIMEType:(id)arg0 ;
+(void)_registerURLSchemeAsAllowingDatabaseAccessInPrivateBrowsing:(id)arg0 ;
+(void)_registerURLSchemeAsAllowingLocalStorageAccessInPrivateBrowsing:(id)arg0 ;
+(void)_registerURLSchemeAsSecure:(id)arg0 ;
+(void)_registerViewClass:(Class)arg0 representationClass:(Class)arg1 forURLScheme:(id)arg2 ;
+(void)_releaseMemoryNow;
+(void)_removeAllUserContentFromGroup:(id)arg0 ;
+(void)_removeOriginAccessAllowListEntryWithSourceOrigin:(id)arg0 destinationProtocol:(id)arg1 destinationHost:(id)arg2 allowDestinationSubdomains:(BOOL)arg3 ;
+(void)_removeUserScriptFromGroup:(id)arg0 world:(id)arg1 url:(id)arg2 ;
+(void)_removeUserScriptsFromGroup:(id)arg0 world:(id)arg1 ;
+(void)_removeUserStyleSheetFromGroup:(id)arg0 world:(id)arg1 url:(id)arg2 ;
+(void)_removeUserStyleSheetsFromGroup:(id)arg0 world:(id)arg1 ;
+(void)_reportException:(struct OpaqueJSValue *)arg0 inContext:(struct OpaqueJSContext *)arg1 ;
+(void)_resetOriginAccessAllowLists;
+(void)_setAlwaysUsesComplexTextCodePath:(BOOL)arg0 ;
+(void)_setCacheModel:(NSUInteger)arg0 ;
+(void)_setDomainRelaxationForbidden:(BOOL)arg0 forURLScheme:(id)arg1 ;
+(void)_setFontAllowList:(id)arg0 ;
+(void)_setHTTPPipeliningEnabled:(BOOL)arg0 ;
+(void)_setIconLoadingEnabled:(BOOL)arg0 ;
+(void)_setLoadResourcesSerially:(BOOL)arg0 ;
+(void)_setPDFRepresentationClass:(Class)arg0 ;
+(void)_setPDFViewClass:(Class)arg0 ;
+(void)_setShouldUseFontSmoothing:(BOOL)arg0 ;
+(void)_setTileCacheLayerPoolCapacity:(unsigned int)arg0 ;
+(void)_unregisterPluginMIMEType:(id)arg0 ;
+(void)_unregisterViewClassAndRepresentationClassForMIMEType:(id)arg0 ;
+(void)closeAllWebViews;
+(void)enableWebThread;
+(void)initialize;
+(void)registerURLSchemeAsLocal:(id)arg0 ;
+(void)registerViewClass:(Class)arg0 representationClass:(Class)arg1 forMIMEType:(id)arg2 ;
+(void)setMIMETypesShownAsHTML:(id)arg0 ;
+(void)willEnterBackgroundWithCompletionHandler:(id)arg0 ;
-(*void)_mainCoreFrame;
-(?)_dictationAlternatives;
-(BOOL)_allowsMessaging;
-(BOOL)_becomingFirstResponderFromOutside;
-(BOOL)_canResetZoom:(BOOL)arg0 ;
-(BOOL)_canShowMIMEType:(id)arg0 ;
-(BOOL)_canZoomIn:(BOOL)arg0 ;
-(BOOL)_canZoomOut:(BOOL)arg0 ;
-(BOOL)_continuousCheckingAllowed;
-(BOOL)_cookieEnabled;
-(BOOL)_fetchCustomFixedPositionLayoutRect:(struct CGRect *)arg0 ;
-(BOOL)_flushCompositingChanges;
-(BOOL)_inFastImageScalingMode;
-(BOOL)_isClosed;
-(BOOL)_isClosing;
-(BOOL)_isMIMETypeRegisteredAsPlugin:(id)arg0 ;
-(BOOL)_isPerformingProgrammaticFocus;
-(BOOL)_isProcessingUserGesture;
-(BOOL)_isSoftwareRenderable;
-(BOOL)_isStopping;
-(BOOL)_isUsingAcceleratedCompositing;
-(BOOL)_isViewVisible;
-(BOOL)_locked_plugInsAreRunningInFrame:(id)arg0 ;
-(BOOL)_needsOneShotDrawingSynchronization;
-(BOOL)_paginationBehavesLikeColumns;
-(BOOL)_paginationLineGridEnabled;
-(BOOL)_pluginsAreRunning;
-(BOOL)_postsAcceleratedCompositingNotifications;
-(BOOL)_realZoomMultiplierIsTextOnly;
-(BOOL)_requestStartDataInteraction:(struct CGPoint )arg0 globalPosition:(struct CGPoint )arg1 ;
-(BOOL)_selectionIsAll;
-(BOOL)_selectionIsCaret;
-(BOOL)_setMediaLayer:(id)arg0 forPluginView:(id)arg1 ;
-(BOOL)_shouldChangeSelectedDOMRange:(id)arg0 toDOMRange:(id)arg1 affinity:(NSUInteger)arg2 stillSelecting:(BOOL)arg3 ;
-(BOOL)_tryToPerformDataInteraction:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(BOOL)_useFixedLayout;
-(BOOL)_viewClass:(*Class)arg0 andRepresentationClass:(*Class)arg1 forMIMEType:(id)arg2 ;
-(BOOL)_wantsTelephoneNumberParsing;
-(BOOL)_webGLEnabled;
-(BOOL)acceptsFirstResponder;
-(BOOL)allowsRemoteInspection;
-(BOOL)allowsUndo;
-(BOOL)areMemoryCacheDelegateCallsEnabled;
-(BOOL)becomeFirstResponder;
-(BOOL)canMarkAllTextMatches;
-(BOOL)canResetPageZoom;
-(BOOL)canZoomPageIn;
-(BOOL)canZoomPageOut;
-(BOOL)defersCallbacks;
-(BOOL)findString:(id)arg0 options:(NSUInteger)arg1 ;
-(BOOL)goBack;
-(BOOL)goForward;
-(BOOL)goToBackForwardItem:(id)arg0 ;
-(BOOL)interactiveFormValidationEnabled;
-(BOOL)isAutomaticDashSubstitutionEnabled;
-(BOOL)isAutomaticLinkDetectionEnabled;
-(BOOL)isAutomaticQuoteSubstitutionEnabled;
-(BOOL)isAutomaticSpellingCorrectionEnabled;
-(BOOL)isAutomaticTextReplacementEnabled;
-(BOOL)isSelectTrailingWhitespaceEnabled;
-(BOOL)isTrackingRepaints;
-(BOOL)searchFor:(id)arg0 direction:(BOOL)arg1 caseSensitive:(BOOL)arg2 wrap:(BOOL)arg3 ;
-(BOOL)searchFor:(id)arg0 direction:(BOOL)arg1 caseSensitive:(BOOL)arg2 wrap:(BOOL)arg3 startInSelection:(BOOL)arg4 ;
-(BOOL)shouldClose;
-(BOOL)shouldRequestCandidates;
-(BOOL)tabKeyCyclesThroughElements;
-(BOOL)usesPageCache;
-(CGFloat)_gapBetweenPages;
-(CGFloat)_pageLength;
-(NSUInteger)_deviceOrientation;
-(NSUInteger)_enteredDataInteraction:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(NSUInteger)_layoutMilestones;
-(NSUInteger)_notificationIDForTesting:(struct OpaqueJSValue *)arg0 ;
-(NSUInteger)_pageCount;
-(NSUInteger)_renderTreeSize;
-(NSUInteger)_updatedDataInteraction:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(NSUInteger)countMatchesForText:(id)arg0 caseSensitive:(BOOL)arg1 highlight:(BOOL)arg2 limit:(NSUInteger)arg3 markMatches:(BOOL)arg4 ;
-(NSUInteger)countMatchesForText:(id)arg0 inDOMRange:(id)arg1 options:(NSUInteger)arg2 highlight:(BOOL)arg3 limit:(NSUInteger)arg4 markMatches:(BOOL)arg5 ;
-(NSUInteger)countMatchesForText:(id)arg0 options:(NSUInteger)arg1 highlight:(BOOL)arg2 limit:(NSUInteger)arg3 markMatches:(BOOL)arg4 ;
-(NSUInteger)dragDestinationActionMaskForSession:(id)arg0 ;
-(NSUInteger)markAllMatchesForText:(id)arg0 caseSensitive:(BOOL)arg1 highlight:(BOOL)arg2 limit:(NSUInteger)arg3 ;
-(float)_realZoomMultiplier;
-(float)_viewScaleFactor;
-(float)_zoomMultiplier:(BOOL)arg0 ;
-(float)mediaVolume;
-(float)pageSizeMultiplier;
-(id)DOMRangeOfString:(id)arg0 relativeTo:(id)arg1 options:(NSUInteger)arg2 ;
-(id)_UIDelegateForSelector:(SEL)arg0 ;
-(id)_UIKitDelegate;
-(id)_UIKitDelegateForwarder;
-(id)_contentsOfUserInterfaceItem:(id)arg0 ;
-(id)_deviceOrientationProvider;
-(id)_displayURL;
-(id)_downloadURL:(id)arg0 ;
-(id)_editableElementsInRect:(struct CGRect )arg0 ;
-(id)_elementAtWindowPoint:(struct CGPoint )arg0 ;
-(id)_fixedPositionContent;
-(id)_focusedFrame;
-(id)_formDelegate;
-(id)_formDelegateForSelector:(SEL)arg0 ;
-(id)_formDelegateForwarder;
-(id)_frameViewAtWindowPoint:(struct CGPoint )arg0 ;
-(id)_geolocationProvider;
-(id)_getDataInteractionData;
-(id)_initWithArguments:(id)arg0 ;
-(id)_initWithFrame:(struct CGRect )arg0 frameName:(id)arg1 groupName:(id)arg2 ;
-(id)_notificationProvider;
-(id)_objectForIdentifier:(NSUInteger)arg0 ;
-(id)_openNewWindowWithRequest:(id)arg0 ;
-(id)_pluginForExtension:(id)arg0 ;
-(id)_pluginForMIMEType:(id)arg0 ;
-(id)_responderForResponderOperations;
-(id)_selectedOrMainFrame;
-(id)_touchEventRegions;
-(id)_webMailDelegate;
-(id)_webcore_effectiveFirstResponder;
-(id)candidateList;
-(id)caretChangeListener;
-(id)caretChangeListeners;
-(id)computedStyleForElement:(id)arg0 pseudoElement:(id)arg1 ;
-(id)currentNodeHighlight;
-(id)documentViewAtWindowPoint:(struct CGPoint )arg0 ;
-(id)editableDOMRangeForPoint:(struct CGPoint )arg0 ;
-(id)elementAtPoint:(struct CGPoint )arg0 ;
-(id)fullScreenPlaceholderView;
-(id)historyDelegate;
-(id)initSimpleHTMLDocumentWithStyle:(id)arg0 frame:(struct CGRect )arg1 preferences:(id)arg2 groupName:(id)arg3 ;
-(id)initWithFrame:(struct CGRect )arg0 ;
-(id)initWithFrame:(struct CGRect )arg0 frameName:(id)arg1 groupName:(id)arg2 ;
-(id)inspector;
-(id)previousValidKeyView;
-(id)quickLookContentForURL:(id)arg0 ;
-(id)rectsForTextMatches;
-(id)scriptDebugDelegate;
-(id)stringByEvaluatingJavaScriptFromString:(id)arg0 ;
-(id)styleAtSelectionStart;
-(id)styleDeclarationWithText:(id)arg0 ;
-(id)textIteratorForRect:(struct CGRect )arg0 ;
-(id)trackedRepaintRects;
-(id)typingAttributes;
-(id)userAgentForURL:(id)arg0 ;
-(int)_keyboardUIMode;
-(int)_paginationMode;
-(int)_visibilityState;
-(int)validationMessageTimerMagnification;
-(struct CGColor *)backgroundColor;
-(struct CGPoint )_convertPointFromRootView:(struct CGPoint )arg0 ;
-(struct CGRect )_convertRectFromRootView:(struct CGRect )arg0 ;
-(struct CGSize )_fixedLayoutSize;
-(struct DragData )dragDataForSession:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(struct NakedPtr<WebCore::Page> )page;
-(struct String )_userAgentString;
-(void)_addObject:(id)arg0 forIdentifier:(NSUInteger)arg1 ;
-(void)_addToAllWebViewsSet;
-(void)_attachScriptDebuggerToAllFrames;
-(void)_cacheFrameLoadDelegateImplementations;
-(void)_cacheHistoryDelegateImplementations;
-(void)_cacheResourceLoadDelegateImplementations;
-(void)_cacheScriptDebugDelegateImplementations;
-(void)_clearCredentials;
-(void)_clearDelegates;
-(void)_clearMainFrameName;
-(void)_close;
-(void)_closePluginDatabases;
-(void)_closeWindow;
-(void)_closeWithFastTeardown;
-(void)_commonInitializationWithFrameName:(id)arg0 groupName:(id)arg1 ;
-(void)_destroyAllPlugIns;
-(void)_detachScriptDebuggerFromAllFrames;
-(void)_didCommitLoadForFrame:(id)arg0 ;
-(void)_didConcludeEditDrag;
-(void)_didFinishScrollingOrZooming;
-(void)_didScrollDocumentInFrameView:(id)arg0 ;
-(void)_dispatchPendingLoadRequests;
-(void)_dispatchTileDidDraw:(id)arg0 ;
-(void)_dispatchUnloadEvent;
-(void)_documentScaleChanged;
-(void)_endedDataInteraction:(struct CGPoint )arg0 global:(struct CGPoint )arg1 ;
-(void)_enterVideoFullscreenForVideoElement:(struct NakedPtr<WebCore::HTMLVideoElement> )arg0 mode:(unsigned int)arg1 ;
-(void)_executeCoreCommandByName:(id)arg0 value:(id)arg1 ;
-(void)_exitVideoFullscreen;
-(void)_exitedDataInteraction:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(void)_forceRepaintForTesting;
-(void)_geolocationDidChangePosition:(id)arg0 ;
-(void)_geolocationDidFailWithMessage:(id)arg0 ;
-(void)_getWebCoreDictationAlternatives:(*void)arg0 fromTextAlternatives:(*void)arg1 ;
-(void)_injectLaBanquePostaleQuirks;
-(void)_insertNewlineInQuotedContent;
-(void)_installVisualIdentificationOverlayForViewIfNeeded:(id)arg0 kind:(id)arg1 ;
-(void)_invalidateUserAgentCache;
-(void)_listenForLayoutMilestones:(NSUInteger)arg0 ;
-(void)_loadBackForwardListFromOtherView:(id)arg0 ;
-(void)_locked_recursivelyPerformPlugInSelector:(SEL)arg0 inFrame:(id)arg1 ;
-(void)_mouseDidMoveOverElement:(id)arg0 modifierFlags:(NSUInteger)arg1 ;
-(void)_notificationDidClick:(NSUInteger)arg0 ;
-(void)_notificationDidShow:(NSUInteger)arg0 ;
-(void)_notificationsDidClose:(id)arg0 ;
-(void)_overflowScrollPositionChangedTo:(struct CGPoint )arg0 forNode:(id)arg1 isUserScroll:(BOOL)arg2 ;
-(void)_performDataInteraction:(id)arg0 client:(struct CGPoint )arg1 global:(struct CGPoint )arg2 operation:(NSUInteger)arg3 ;
-(void)_performResponderOperation:(SEL)arg0 with:(id)arg1 ;
-(void)_popPerformingProgrammaticFocus;
-(void)_preferencesChanged:(id)arg0 ;
-(void)_preferencesChangedGenerated:(id)arg0 ;
-(void)_preferencesChangedNotification:(id)arg0 ;
-(void)_pushPerformingProgrammaticFocus;
-(void)_removeDictationAlternatives:(struct ObjectIdentifier<WebCore::DictationContextType> )arg0 ;
-(void)_removeFromAllWebViewsSet;
-(void)_removeObjectForIdentifier:(NSUInteger)arg0 ;
-(void)_replaceCurrentHistoryItem:(id)arg0 ;
-(void)_replaceSelectionWithNode:(id)arg0 matchStyle:(BOOL)arg1 ;
-(void)_resetAllGeolocationPermission;
-(void)_resetZoom:(id)arg0 isTextOnly:(BOOL)arg1 ;
-(void)_restorePlugInsFromCache;
-(void)_retrieveKeyboardUIModeFromPreferences:(id)arg0 ;
-(void)_scaleWebView:(float)arg0 atOrigin:(struct CGPoint )arg1 ;
-(void)_scheduleRenderingUpdateForPendingTileCacheRepaint;
-(void)_scheduleUpdateRendering;
-(void)_setAllowsMessaging:(BOOL)arg0 ;
-(void)_setBaseCTM:(struct CGAffineTransform )arg0 forContext:(struct CGContext *)arg1 ;
-(void)_setBrowserUserAgentProductVersion:(id)arg0 buildVersion:(id)arg1 bundleVersion:(id)arg2 ;
-(void)_setCookieEnabled:(BOOL)arg0 ;
-(void)_setCustomFixedPositionLayoutRect:(struct CGRect )arg0 ;
-(void)_setCustomFixedPositionLayoutRectInWebThread:(struct CGRect )arg0 synchronize:(BOOL)arg1 ;
-(void)_setDeviceOrientation:(NSUInteger)arg0 ;
-(void)_setDeviceOrientationProvider:(id)arg0 ;
-(void)_setFixedLayoutSize:(struct CGSize )arg0 ;
-(void)_setFontFallbackPrefersPictographs:(BOOL)arg0 ;
-(void)_setFormDelegate:(id)arg0 ;
-(void)_setGapBetweenPages:(CGFloat)arg0 ;
-(void)_setGeolocationProvider:(id)arg0 ;
-(void)_setHostApplicationProcessIdentifier:(int)arg0 auditToken:(struct ? )arg1 ;
-(void)_setIsVisible:(BOOL)arg0 ;
-(void)_setNeedsOneShotDrawingSynchronization:(BOOL)arg0 ;
-(void)_setNeedsUnrestrictedGetMatchedCSSRules:(BOOL)arg0 ;
-(void)_setNotificationProvider:(id)arg0 ;
-(void)_setPageLength:(CGFloat)arg0 ;
-(void)_setPaginationBehavesLikeColumns:(BOOL)arg0 ;
-(void)_setPaginationLineGridEnabled:(BOOL)arg0 ;
-(void)_setPaginationMode:(int)arg0 ;
-(void)_setPostsAcceleratedCompositingNotifications:(BOOL)arg0 ;
-(void)_setResourceLoadSchedulerSuspended:(BOOL)arg0 ;
-(void)_setUIKitDelegate:(id)arg0 ;
-(void)_setUIWebViewUserAgentWithBuildVersion:(id)arg0 ;
-(void)_setUseFastImageScalingMode:(BOOL)arg0 ;
-(void)_setUseFixedLayout:(BOOL)arg0 ;
-(void)_setVisibilityState:(int)arg0 isInitialState:(BOOL)arg1 ;
-(void)_setWantsTelephoneNumberParsing:(BOOL)arg0 ;
-(void)_setWebGLEnabled:(BOOL)arg0 ;
-(void)_setZoomMultiplier:(float)arg0 isTextOnly:(BOOL)arg1 ;
-(void)_showDictationAlternativeUI:(struct FloatRect *)arg0 forDictationContext:(struct ObjectIdentifier<WebCore::DictationContextType> )arg1 ;
-(void)_simplifyMarkup:(id)arg0 endNode:(id)arg1 ;
-(void)_startAllPlugIns;
-(void)_startDrag:(*void)arg0 ;
-(void)_stopAllPlugIns;
-(void)_stopAllPlugInsForPageCache;
-(void)_synchronizeCustomFixedPositionLayoutRect;
-(void)_updateActiveState;
-(void)_updateRendering;
-(void)_updateScreenScaleFromWindow;
-(void)_updateVisibilityState;
-(void)_viewGeometryDidChange;
-(void)_wakWindowScreenScaleChanged:(id)arg0 ;
-(void)_wakWindowVisibilityChanged:(id)arg0 ;
-(void)_willStartScrollingOrZooming;
-(void)_windowVisibilityChanged:(id)arg0 ;
-(void)_zoomIn:(id)arg0 isTextOnly:(BOOL)arg1 ;
-(void)_zoomOut:(id)arg0 isTextOnly:(BOOL)arg1 ;
-(void)addCaretChangeListener:(id)arg0 ;
-(void)addVisitedLinks:(id)arg0 ;
-(void)alignCenter:(id)arg0 ;
-(void)alignJustified:(id)arg0 ;
-(void)alignLeft:(id)arg0 ;
-(void)alignRight:(id)arg0 ;
-(void)applyStyle:(id)arg0 ;
-(void)capitalizeWord:(id)arg0 ;
-(void)caretChanged;
-(void)centerSelectionInVisibleArea:(id)arg0 ;
-(void)changeAttributes:(id)arg0 ;
-(void)changeBaseWritingDirection:(id)arg0 ;
-(void)changeBaseWritingDirectionToLTR:(id)arg0 ;
-(void)changeBaseWritingDirectionToRTL:(id)arg0 ;
-(void)changeColor:(id)arg0 ;
-(void)changeDocumentBackgroundColor:(id)arg0 ;
-(void)changeFont:(id)arg0 ;
-(void)changeSpelling:(id)arg0 ;
-(void)checkSpelling:(id)arg0 ;
-(void)clearText:(id)arg0 ;
-(void)close;
-(void)complete:(id)arg0 ;
-(void)copy:(id)arg0 ;
-(void)copyFont:(id)arg0 ;
-(void)cut:(id)arg0 ;
-(void)dealloc;
-(void)delete:(id)arg0 ;
-(void)deleteBackward:(id)arg0 ;
-(void)deleteBackwardByDecomposingPreviousCharacter:(id)arg0 ;
-(void)deleteForward:(id)arg0 ;
-(void)deleteSelection;
-(void)deleteToBeginningOfLine:(id)arg0 ;
-(void)deleteToBeginningOfParagraph:(id)arg0 ;
-(void)deleteToEndOfLine:(id)arg0 ;
-(void)deleteToEndOfParagraph:(id)arg0 ;
-(void)deleteToMark:(id)arg0 ;
-(void)deleteWordBackward:(id)arg0 ;
-(void)deleteWordForward:(id)arg0 ;
-(void)forceRequestCandidatesForTesting;
-(void)goBack:(id)arg0 ;
-(void)goForward:(id)arg0 ;
-(void)hideFormValidationMessage;
-(void)ignoreSpelling:(id)arg0 ;
-(void)indent:(id)arg0 ;
-(void)insertBacktab:(id)arg0 ;
-(void)insertDictationPhrases:(id)arg0 metadata:(id)arg1 ;
-(void)insertLineBreak:(id)arg0 ;
-(void)insertNewline:(id)arg0 ;
-(void)insertNewlineIgnoringFieldEditor:(id)arg0 ;
-(void)insertParagraphSeparator:(id)arg0 ;
-(void)insertTab:(id)arg0 ;
-(void)insertTabIgnoringFieldEditor:(id)arg0 ;
-(void)insertText:(id)arg0 ;
-(void)lowercaseWord:(id)arg0 ;
-(void)makeBaseWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeBaseWritingDirectionRightToLeft:(id)arg0 ;
-(void)makeTextLarger:(id)arg0 ;
-(void)makeTextSmaller:(id)arg0 ;
-(void)makeTextStandardSize:(id)arg0 ;
-(void)makeTextWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeTextWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeft:(id)arg0 ;
-(void)moveBackward:(id)arg0 ;
-(void)moveBackwardAndModifySelection:(id)arg0 ;
-(void)moveDown:(id)arg0 ;
-(void)moveDownAndModifySelection:(id)arg0 ;
-(void)moveForward:(id)arg0 ;
-(void)moveForwardAndModifySelection:(id)arg0 ;
-(void)moveLeft:(id)arg0 ;
-(void)moveLeftAndModifySelection:(id)arg0 ;
-(void)moveParagraphBackwardAndModifySelection:(id)arg0 ;
-(void)moveParagraphForwardAndModifySelection:(id)arg0 ;
-(void)moveRight:(id)arg0 ;
-(void)moveRightAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfDocument:(id)arg0 ;
-(void)moveToBeginningOfDocumentAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfLine:(id)arg0 ;
-(void)moveToBeginningOfLineAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfParagraph:(id)arg0 ;
-(void)moveToBeginningOfParagraphAndModifySelection:(id)arg0 ;
-(void)moveToBeginningOfSentence:(id)arg0 ;
-(void)moveToBeginningOfSentenceAndModifySelection:(id)arg0 ;
-(void)moveToEndOfDocument:(id)arg0 ;
-(void)moveToEndOfDocumentAndModifySelection:(id)arg0 ;
-(void)moveToEndOfLine:(id)arg0 ;
-(void)moveToEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveToEndOfParagraph:(id)arg0 ;
-(void)moveToEndOfParagraphAndModifySelection:(id)arg0 ;
-(void)moveToEndOfSentence:(id)arg0 ;
-(void)moveToEndOfSentenceAndModifySelection:(id)arg0 ;
-(void)moveToLeftEndOfLine:(id)arg0 ;
-(void)moveToLeftEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveToRightEndOfLine:(id)arg0 ;
-(void)moveToRightEndOfLineAndModifySelection:(id)arg0 ;
-(void)moveUp:(id)arg0 ;
-(void)moveUpAndModifySelection:(id)arg0 ;
-(void)moveWordBackward:(id)arg0 ;
-(void)moveWordBackwardAndModifySelection:(id)arg0 ;
-(void)moveWordForward:(id)arg0 ;
-(void)moveWordForwardAndModifySelection:(id)arg0 ;
-(void)moveWordLeft:(id)arg0 ;
-(void)moveWordLeftAndModifySelection:(id)arg0 ;
-(void)moveWordRight:(id)arg0 ;
-(void)moveWordRightAndModifySelection:(id)arg0 ;
-(void)orderFrontSubstitutionsPanel:(id)arg0 ;
-(void)outdent:(id)arg0 ;
-(void)overWrite:(id)arg0 ;
-(void)pageDown:(id)arg0 ;
-(void)pageDownAndModifySelection:(id)arg0 ;
-(void)pageUp:(id)arg0 ;
-(void)pageUpAndModifySelection:(id)arg0 ;
-(void)paste:(id)arg0 ;
-(void)pasteAsPlainText:(id)arg0 ;
-(void)pasteAsRichText:(id)arg0 ;
-(void)pasteFont:(id)arg0 ;
-(void)performFindPanelAction:(id)arg0 ;
-(void)prepareForMouseDown;
-(void)prepareForMouseUp;
-(void)registerForEditingDelegateNotification:(id)arg0 selector:(SEL)arg1 ;
-(void)reload:(id)arg0 ;
-(void)reloadFromOrigin:(id)arg0 ;
-(void)removeAllCaretChangeListeners;
-(void)removeCaretChangeListener:(id)arg0 ;
-(void)removeVisitedLink:(id)arg0 ;
-(void)replaceSelectionWithArchive:(id)arg0 ;
-(void)replaceSelectionWithMarkupString:(id)arg0 ;
-(void)replaceSelectionWithNode:(id)arg0 ;
-(void)replaceSelectionWithText:(id)arg0 ;
-(void)resetPageZoom:(id)arg0 ;
-(void)resetTrackedRepaints;
-(void)resumeAllMediaPlayback;
-(void)revealCurrentSelection;
-(void)scheduleInRunLoop:(id)arg0 forMode:(id)arg1 ;
-(void)scrollDOMRangeToVisible:(id)arg0 ;
-(void)scrollDOMRangeToVisible:(id)arg0 withInset:(CGFloat)arg1 ;
-(void)scrollLineDown:(id)arg0 ;
-(void)scrollLineUp:(id)arg0 ;
-(void)scrollPageDown:(id)arg0 ;
-(void)scrollPageUp:(id)arg0 ;
-(void)scrollToBeginningOfDocument:(id)arg0 ;
-(void)scrollToEndOfDocument:(id)arg0 ;
-(void)selectAll:(id)arg0 ;
-(void)selectLine:(id)arg0 ;
-(void)selectParagraph:(id)arg0 ;
-(void)selectSentence:(id)arg0 ;
-(void)selectToMark:(id)arg0 ;
-(void)selectWord:(id)arg0 ;
-(void)setAllowsRemoteInspection:(BOOL)arg0 ;
-(void)setAllowsUndo:(BOOL)arg0 ;
-(void)setBackgroundColor:(struct CGColor *)arg0 ;
-(void)setCaretChangeListener:(id)arg0 ;
-(void)setCurrentNodeHighlight:(id)arg0 ;
-(void)setDefersCallbacks:(BOOL)arg0 ;
-(void)setHistoryDelegate:(id)arg0 ;
-(void)setInteractiveFormValidationEnabled:(BOOL)arg0 ;
-(void)setMaintainsBackForwardList:(BOOL)arg0 ;
-(void)setMark:(id)arg0 ;
-(void)setMediaVolume:(float)arg0 ;
-(void)setMemoryCacheDelegateCallsEnabled:(BOOL)arg0 ;
-(void)setNextKeyView:(id)arg0 ;
-(void)setPageSizeMultiplier:(float)arg0 ;
-(void)setScriptDebugDelegate:(id)arg0 ;
-(void)setSelectTrailingWhitespaceEnabled:(BOOL)arg0 ;
-(void)setShowingInspectorIndication:(BOOL)arg0 ;
-(void)setTabKeyCyclesThroughElements:(BOOL)arg0 ;
-(void)setTracksRepaints:(BOOL)arg0 ;
-(void)setUsesPageCache:(BOOL)arg0 ;
-(void)setValidationMessageTimerMagnification:(int)arg0 ;
-(void)setWebMailDelegate:(id)arg0 ;
-(void)showCandidates:(id)arg0 forString:(id)arg1 inRect:(struct CGRect )arg2 forSelectedRange:(struct _NSRange )arg3 view:(id)arg4 completionHandler:(id)arg5 ;
-(void)showFormValidationMessage:(id)arg0 withAnchorRect:(struct CGRect )arg1 ;
-(void)showGuessPanel:(id)arg0 ;
-(void)startSpeaking:(id)arg0 ;
-(void)stopLoading:(id)arg0 ;
-(void)stopLoadingAndClear;
-(void)stopSpeaking:(id)arg0 ;
-(void)subscript:(id)arg0 ;
-(void)superscript:(id)arg0 ;
-(void)suspendAllMediaPlayback;
-(void)swapWithMark:(id)arg0 ;
-(void)takeFindStringFromSelection:(id)arg0 ;
-(void)takeStringURLFrom:(id)arg0 ;
-(void)toggleBaseWritingDirection:(id)arg0 ;
-(void)toggleBold:(id)arg0 ;
-(void)toggleContinuousSpellChecking:(id)arg0 ;
-(void)toggleItalic:(id)arg0 ;
-(void)toggleUnderline:(id)arg0 ;
-(void)transpose:(id)arg0 ;
-(void)underline:(id)arg0 ;
-(void)unmarkAllTextMatches;
-(void)unscheduleFromRunLoop:(id)arg0 forMode:(id)arg1 ;
-(void)unscript:(id)arg0 ;
-(void)updateLayoutIgnorePendingStyleSheets;
-(void)updateTouchBar;
-(void)uppercaseWord:(id)arg0 ;
-(void)viewDidMoveToWindow;
-(void)yank:(id)arg0 ;
-(void)yankAndSelect:(id)arg0 ;
-(void)zoomPageIn:(id)arg0 ;
-(void)zoomPageOut:(id)arg0 ;


@end


#endif