// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.6.0 | SDK: 15.6.0


#ifndef GEOACTIVETILEGROUP_H
#define GEOACTIVETILEGROUP_H

@class PBCodable, PBDataReader, PBUnknownFields, NSString, NSMutableArray, NSData;
@protocol NSCopying;


#import "GEODataSetDescription.h"
#import "GEOURLInfoSet.h"
#import "GEOVersionManifest.h"

@interface GEOActiveTileGroup : PBCodable <NSCopying>

 {
    PBDataReader *_reader;
    PBUnknownFields *_unknownFields;
    ? _activeScales;
    ? _activeScenarios;
    *GEOTileSetRegion _hybridUnavailableRegions;
    NSUInteger _hybridUnavailableRegionsCount;
    NSUInteger _hybridUnavailableRegionsSpace;
    NSString *_abExperimentURLLegacy;
    NSMutableArray *_activeResources;
    NSString *_addressCorrectionInitURLLegacy;
    NSString *_addressCorrectionUpdateURLLegacy;
    NSMutableArray *_announcementsSupportedLanguages;
    NSString *_announcementsURLLegacy;
    NSMutableArray *_attributions;
    NSString *_backgroundDispatcherURLLegacy;
    NSString *_backgroundRevGeoURLLegacy;
    NSString *_batchReverseGeocoderURLLegacy;
    NSString *_batchTrafficProbeURLLegacy;
    NSString *_bluePOIURLLegacy;
    NSString *_businessPortalBaseURLLegacy;
    GEODataSetDescription *_dataSet;
    NSString *_directionsURLLegacy;
    NSString *_dispatcherURLLegacy;
    NSMutableArray *_displayStrings;
    NSString *_environment;
    NSString *_etaURLLegacy;
    NSData *_flyoverRegionVersions;
    NSMutableArray *_fontChecksums;
    NSMutableArray *_fonts;
    NSMutableArray *_iconChecksums;
    NSMutableArray *_icons;
    NSMutableArray *_locationShiftEnabledRegions;
    NSString *_logMessageUsageURLLegacy;
    NSString *_logMessageUsageV3URLLegacy;
    NSString *_muninBaseURL;
    NSMutableArray *_muninBuckets;
    NSString *_polyLocationShiftURLLegacy;
    NSString *_proactiveRoutingURLLegacy;
    NSString *_problemCategoriesURLLegacy;
    NSString *_problemOptInURLLegacy;
    NSString *_problemStatusURLLegacy;
    NSString *_problemSubmissionURLLegacy;
    NSString *_realtimeTrafficProbeURLLegacy;
    NSMutableArray *_regionalResourceRegions;
    NSMutableArray *_regionalResourceTiles;
    NSString *_regionalResourcesURLLegacy;
    NSMutableArray *_regionalResources;
    NSString *_releaseInfo;
    NSData *_reserved;
    NSString *_resourcesURLLegacy;
    NSMutableArray *_resources;
    NSString *_reverseGeocoderVersionsURLLegacy;
    NSString *_searchAttributionManifestURLLegacy;
    NSString *_simpleETAURLLegacy;
    NSString *_spatialLookupURLLegacy;
    NSMutableArray *_staleResources;
    NSMutableArray *_styleSheetChecksums;
    NSMutableArray *_styleSheets;
    NSMutableArray *_textureChecksums;
    NSMutableArray *_textures;
    NSMutableArray *_tileSets;
    NSString *_uniqueIdentifier;
    GEOURLInfoSet *_urlInfoSet;
    GEOVersionManifest *_versionManifest;
    NSString *_wifiConnectionQualityProbeURLLegacy;
    NSMutableArray *_xmlChecksums;
    NSMutableArray *_xmls;
    unsigned int _readerMarkPos;
    unsigned int _readerMarkLength;
    os_unfair_lock_s _readerLock;
    unsigned int _identifier;
    unsigned int _locationShiftVersion;
    unsigned int _modelVersion;
    ? _flags;
}


@property (retain, nonatomic) NSString *abExperimentURLLegacy;
@property (retain, nonatomic) NSMutableArray *activeResources;
@property (readonly, nonatomic) *int activeScales;
@property (readonly, nonatomic) NSUInteger activeScalesCount;
@property (readonly, nonatomic) *int activeScenarios;
@property (readonly, nonatomic) NSUInteger activeScenariosCount;
@property (retain, nonatomic) NSString *addressCorrectionInitURLLegacy;
@property (retain, nonatomic) NSString *addressCorrectionUpdateURLLegacy;
@property (retain, nonatomic) NSMutableArray *announcementsSupportedLanguages;
@property (retain, nonatomic) NSString *announcementsURLLegacy;
@property (retain, nonatomic) NSMutableArray *attributions;
@property (retain, nonatomic) NSString *backgroundDispatcherURLLegacy;
@property (retain, nonatomic) NSString *backgroundRevGeoURLLegacy;
@property (retain, nonatomic) NSString *batchReverseGeocoderURLLegacy;
@property (retain, nonatomic) NSString *batchTrafficProbeURLLegacy;
@property (retain, nonatomic) NSString *bluePOIURLLegacy;
@property (retain, nonatomic) NSString *businessPortalBaseURLLegacy;
@property (retain, nonatomic) GEODataSetDescription *dataSet;
@property (retain, nonatomic) NSString *directionsURLLegacy;
@property (retain, nonatomic) NSString *dispatcherURLLegacy;
@property (retain, nonatomic) NSMutableArray *displayStrings;
@property (retain, nonatomic) NSString *environment;
@property (retain, nonatomic) NSString *etaURLLegacy;
@property (retain, nonatomic) NSData *flyoverRegionVersions;
@property (retain, nonatomic) NSMutableArray *fontChecksums;
@property (retain, nonatomic) NSMutableArray *fonts;
@property (readonly, nonatomic) BOOL hasAbExperimentURLLegacy;
@property (readonly, nonatomic) BOOL hasAddressCorrectionInitURLLegacy;
@property (readonly, nonatomic) BOOL hasAddressCorrectionUpdateURLLegacy;
@property (readonly, nonatomic) BOOL hasAnnouncementsURLLegacy;
@property (readonly, nonatomic) BOOL hasBackgroundDispatcherURLLegacy;
@property (readonly, nonatomic) BOOL hasBackgroundRevGeoURLLegacy;
@property (readonly, nonatomic) BOOL hasBatchReverseGeocoderURLLegacy;
@property (readonly, nonatomic) BOOL hasBatchTrafficProbeURLLegacy;
@property (readonly, nonatomic) BOOL hasBluePOIURLLegacy;
@property (readonly, nonatomic) BOOL hasBusinessPortalBaseURLLegacy;
@property (readonly, nonatomic) BOOL hasDataSet;
@property (readonly, nonatomic) BOOL hasDirectionsURLLegacy;
@property (readonly, nonatomic) BOOL hasDispatcherURLLegacy;
@property (readonly, nonatomic) BOOL hasEnvironment;
@property (readonly, nonatomic) BOOL hasEtaURLLegacy;
@property (readonly, nonatomic) BOOL hasFlyoverRegionVersions;
@property (nonatomic) BOOL hasLocationShiftVersion;
@property (readonly, nonatomic) BOOL hasLogMessageUsageURLLegacy;
@property (readonly, nonatomic) BOOL hasLogMessageUsageV3URLLegacy;
@property (nonatomic) BOOL hasModelVersion;
@property (readonly, nonatomic) BOOL hasMuninBaseURL;
@property (readonly, nonatomic) BOOL hasPolyLocationShiftURLLegacy;
@property (readonly, nonatomic) BOOL hasProactiveRoutingURLLegacy;
@property (readonly, nonatomic) BOOL hasProblemCategoriesURLLegacy;
@property (readonly, nonatomic) BOOL hasProblemOptInURLLegacy;
@property (readonly, nonatomic) BOOL hasProblemStatusURLLegacy;
@property (readonly, nonatomic) BOOL hasProblemSubmissionURLLegacy;
@property (readonly, nonatomic) BOOL hasRealtimeTrafficProbeURLLegacy;
@property (readonly, nonatomic) BOOL hasRegionalResourcesURLLegacy;
@property (readonly, nonatomic) BOOL hasReleaseInfo;
@property (readonly, nonatomic) BOOL hasReserved;
@property (readonly, nonatomic) BOOL hasResourcesURLLegacy;
@property (readonly, nonatomic) BOOL hasReverseGeocoderVersionsURLLegacy;
@property (readonly, nonatomic) BOOL hasSearchAttributionManifestURLLegacy;
@property (readonly, nonatomic) BOOL hasSimpleETAURLLegacy;
@property (readonly, nonatomic) BOOL hasSpatialLookupURLLegacy;
@property (readonly, nonatomic) BOOL hasUniqueIdentifier;
@property (readonly, nonatomic) BOOL hasUrlInfoSet;
@property (readonly, nonatomic) BOOL hasVersionManifest;
@property (readonly, nonatomic) BOOL hasWifiConnectionQualityProbeURLLegacy;
@property (readonly, nonatomic) *GEOTileSetRegion hybridUnavailableRegions;
@property (readonly, nonatomic) NSUInteger hybridUnavailableRegionsCount;
@property (retain, nonatomic) NSMutableArray *iconChecksums;
@property (retain, nonatomic) NSMutableArray *icons;
@property (nonatomic) unsigned int identifier;
@property (retain, nonatomic) NSMutableArray *locationShiftEnabledRegions;
@property (nonatomic) unsigned int locationShiftVersion;
@property (retain, nonatomic) NSString *logMessageUsageURLLegacy;
@property (retain, nonatomic) NSString *logMessageUsageV3URLLegacy;
@property (nonatomic) unsigned int modelVersion;
@property (retain, nonatomic) NSString *muninBaseURL;
@property (retain, nonatomic) NSMutableArray *muninBuckets;
@property (retain, nonatomic) NSString *polyLocationShiftURLLegacy;
@property (retain, nonatomic) NSString *proactiveRoutingURLLegacy;
@property (retain, nonatomic) NSString *problemCategoriesURLLegacy;
@property (retain, nonatomic) NSString *problemOptInURLLegacy;
@property (retain, nonatomic) NSString *problemStatusURLLegacy;
@property (retain, nonatomic) NSString *problemSubmissionURLLegacy;
@property (retain, nonatomic) NSString *realtimeTrafficProbeURLLegacy;
@property (retain, nonatomic) NSMutableArray *regionalResourceRegions;
@property (retain, nonatomic) NSMutableArray *regionalResourceTiles;
@property (retain, nonatomic) NSMutableArray *regionalResources;
@property (retain, nonatomic) NSString *regionalResourcesURLLegacy;
@property (retain, nonatomic) NSString *releaseInfo;
@property (retain, nonatomic) NSData *reserved;
@property (retain, nonatomic) NSMutableArray *resources;
@property (retain, nonatomic) NSString *resourcesURLLegacy;
@property (retain, nonatomic) NSString *reverseGeocoderVersionsURLLegacy;
@property (retain, nonatomic) NSString *searchAttributionManifestURLLegacy;
@property (retain, nonatomic) NSString *simpleETAURLLegacy;
@property (retain, nonatomic) NSString *spatialLookupURLLegacy;
@property (retain, nonatomic) NSMutableArray *staleResources;
@property (retain, nonatomic) NSMutableArray *styleSheetChecksums;
@property (retain, nonatomic) NSMutableArray *styleSheets;
@property (retain, nonatomic) NSMutableArray *textureChecksums;
@property (retain, nonatomic) NSMutableArray *textures;
@property (retain, nonatomic) NSMutableArray *tileSets;
@property (retain, nonatomic) NSString *uniqueIdentifier;
@property (readonly, nonatomic) PBUnknownFields *unknownFields;
@property (retain, nonatomic) GEOURLInfoSet *urlInfoSet;
@property (retain, nonatomic) GEOVersionManifest *versionManifest;
@property (retain, nonatomic) NSString *wifiConnectionQualityProbeURLLegacy;
@property (retain, nonatomic) NSMutableArray *xmlChecksums;
@property (retain, nonatomic) NSMutableArray *xmls;


+(BOOL)isValid:(id)arg0 ;
+(Class)activeResourceType;
+(Class)attributionType;
+(Class)fontChecksumType;
+(Class)fontType;
+(Class)iconChecksumType;
+(Class)iconType;
+(Class)locationShiftEnabledRegionType;
+(Class)muninBucketType;
+(Class)regionalResourceRegionType;
+(Class)regionalResourceTileType;
+(Class)regionalResourceType;
+(Class)resourceType;
+(Class)staleResourceType;
+(Class)styleSheetChecksumType;
+(Class)styleSheetType;
+(Class)textureChecksumType;
+(Class)textureType;
+(Class)tileSetType;
+(Class)xmlChecksumType;
+(Class)xmlType;
-(BOOL)hasDataVersionForFlyoverRegion:(unsigned int)arg0 ;
-(BOOL)hasGreenTeaWithValue:(BOOL)arg0 ;
-(BOOL)hasRegionalResourcesForTileKey:(struct _GEOTileKey *)arg0 ;
-(BOOL)isAvailableForTileKey:(struct _GEOTileKey *)arg0 ;
-(BOOL)isEqual:(id)arg0 ;
-(BOOL)isHybridModeAvailableForTileKey:(struct _GEOTileKey *)arg0 ;
-(BOOL)isMuninEnabled;
-(BOOL)readFrom:(id)arg0 ;
-(BOOL)supportsTileStyle:(int)arg0 size:(int)arg1 scale:(int)arg2 ;
-(BOOL)useProxyAuthForTileKey:(struct _GEOTileKey *)arg0 ;
-(CGFloat)timeToLiveForTileKey:(struct _GEOTileKey *)arg0 ;
-(NSUInteger)hash;
-(id)_decodedFlyoverRegionVersions;
-(id)activeResourceAtIndex:(NSUInteger)arg0 ;
-(id)activeScalesAsString:(int)arg0 ;
-(id)activeScenariosAsString:(int)arg0 ;
-(id)activeTileSetForKey:(struct _GEOTileKey *)arg0 ;
-(id)activeTileSetForStyle:(int)arg0 ;
-(id)activeTileSetForStyle:(int)arg0 size:(int)arg1 scale:(int)arg2 ;
-(id)activeTileSetForTileType:(int)arg0 scale:(int)arg1 ;
-(id)announcementsSupportedLanguagesAtIndex:(NSUInteger)arg0 ;
-(id)attributionAtIndex:(NSUInteger)arg0 ;
-(id)copyWithZone:(struct _NSZone *)arg0 ;
-(id)description;
-(id)dictionaryRepresentation;
-(id)displayStringsAtIndex:(NSUInteger)arg0 ;
-(id)fontAtIndex:(NSUInteger)arg0 ;
-(id)fontChecksumAtIndex:(NSUInteger)arg0 ;
-(id)iconAtIndex:(NSUInteger)arg0 ;
-(id)iconChecksumAtIndex:(NSUInteger)arg0 ;
-(id)init;
-(id)initWithData:(id)arg0 ;
-(id)initWithDictionary:(id)arg0 ;
-(id)initWithJSON:(id)arg0 ;
-(id)jsonRepresentation;
-(id)languageForTileKey:(struct _GEOTileKey *)arg0 ;
-(id)languageForTileKey:(struct _GEOTileKey *)arg0 overrideLocale:(id)arg1 ;
-(id)localizationURLStringForTileKey:(struct _GEOTileKey *)arg0 ;
-(id)locationShiftEnabledRegionAtIndex:(NSUInteger)arg0 ;
-(id)muninBucketAtIndex:(NSUInteger)arg0 ;
-(id)muninBucketURLForId:(unsigned short)arg0 lod:(unsigned char)arg1 ;
-(id)regionalResourceAtIndex:(NSUInteger)arg0 ;
-(id)regionalResourceKeysForTileKey:(struct _GEOTileKey *)arg0 scale:(int)arg1 scenarios:(id)arg2 ;
-(id)regionalResourceRegionAtIndex:(NSUInteger)arg0 ;
-(id)regionalResourceTileAtIndex:(NSUInteger)arg0 ;
-(id)regionalResourcesForMapRect:(struct ? )arg0 ;
// -(id)regionalResourcesForMapRegions:(id)arg0 resourceFilter:(id)arg1 attributionFilter:(unk)arg2  ;
-(id)resourceAtIndex:(NSUInteger)arg0 ;
-(id)staleResourceAtIndex:(NSUInteger)arg0 ;
-(id)styleSheetAtIndex:(NSUInteger)arg0 ;
-(id)styleSheetChecksumAtIndex:(NSUInteger)arg0 ;
-(id)textureAtIndex:(NSUInteger)arg0 ;
-(id)textureChecksumAtIndex:(NSUInteger)arg0 ;
-(id)tileSetAtIndex:(NSUInteger)arg0 ;
-(id)xmlAtIndex:(NSUInteger)arg0 ;
-(id)xmlChecksumAtIndex:(NSUInteger)arg0 ;
-(int)StringAsActiveScales:(id)arg0 ;
-(int)StringAsActiveScenarios:(id)arg0 ;
-(int)activeScaleAtIndex:(NSUInteger)arg0 ;
-(int)activeScenarioAtIndex:(NSUInteger)arg0 ;
-(int)requestStyleForTileKey:(struct _GEOTileKey *)arg0 ;
-(struct GEOTileSetRegion )hybridUnavailableRegionAtIndex:(NSUInteger)arg0 ;
-(unsigned int)dataVersionForFlyoverRegion:(unsigned int)arg0 ;
-(unsigned int)largestRegionalResourceZoomLevelContainingTileKey:(struct _GEOTileKey *)arg0 ;
-(unsigned int)versionForFlyoverRegion:(unsigned int)arg0 ;
-(unsigned int)versionForTileKey:(struct _GEOTileKey *)arg0 ;
-(void)_resetBestLanguages;
-(void)_setDecodedFlyoverRegionVersions:(id)arg0 ;
-(void)addActiveResource:(id)arg0 ;
-(void)addActiveScale:(int)arg0 ;
-(void)addActiveScenario:(int)arg0 ;
-(void)addAnnouncementsSupportedLanguages:(id)arg0 ;
-(void)addAttribution:(id)arg0 ;
-(void)addDisplayStrings:(id)arg0 ;
-(void)addFont:(id)arg0 ;
-(void)addFontChecksum:(id)arg0 ;
-(void)addHybridUnavailableRegion:(struct GEOTileSetRegion )arg0 ;
-(void)addIcon:(id)arg0 ;
-(void)addIconChecksum:(id)arg0 ;
-(void)addLocationShiftEnabledRegion:(id)arg0 ;
-(void)addMuninBucket:(id)arg0 ;
-(void)addRegionalResource:(id)arg0 ;
-(void)addRegionalResourceRegion:(id)arg0 ;
-(void)addRegionalResourceTile:(id)arg0 ;
-(void)addResource:(id)arg0 ;
-(void)addStaleResource:(id)arg0 ;
-(void)addStyleSheet:(id)arg0 ;
-(void)addStyleSheetChecksum:(id)arg0 ;
-(void)addTexture:(id)arg0 ;
-(void)addTextureChecksum:(id)arg0 ;
-(void)addTileSet:(id)arg0 ;
-(void)addXml:(id)arg0 ;
-(void)addXmlChecksum:(id)arg0 ;
-(void)clearActiveResources;
-(void)clearActiveScales;
-(void)clearActiveScenarios;
-(void)clearAnnouncementsSupportedLanguages;
-(void)clearAttributions;
-(void)clearDisplayStrings;
-(void)clearFontChecksums;
-(void)clearFonts;
-(void)clearHybridUnavailableRegions;
-(void)clearIconChecksums;
-(void)clearIcons;
-(void)clearLocationShiftEnabledRegions;
-(void)clearModernFormatFields;
-(void)clearMuninBuckets;
-(void)clearRegionalResourceRegions;
-(void)clearRegionalResourceTiles;
-(void)clearRegionalResources;
-(void)clearResources;
-(void)clearStaleResources;
-(void)clearStyleSheetChecksums;
-(void)clearStyleSheets;
-(void)clearTextureChecksums;
-(void)clearTextures;
-(void)clearTileSets;
-(void)clearUnknownFields:(BOOL)arg0 ;
-(void)clearXmlChecksums;
-(void)clearXmls;
-(void)copyTo:(id)arg0 ;
-(void)dealloc;
-(void)enumerateFlyoverRegions:(id)arg0 ;
-(void)iterateActiveTileSets:(id)arg0 ;
-(void)mergeFrom:(id)arg0 ;
-(void)populateLegacyFormat;
-(void)readAll:(BOOL)arg0 ;
-(void)writeTo:(id)arg0 ;


@end


#endif