

#include "SFCredentialProviderExtensionHelperProxy.h"
#include "SFSafariCredential.h"
#include "SFExternalCredentialIdentityStore.h"
#include "SFAutoFillHelperProxy.h"
#include "SFDomainAssociationUtilities.h"
#include "SFSafariCredentialStore.h"
#include "SFStrongPasswordGenerator.h"
#include "SFPasswordCredentialIdentity.h"
#include "SFCredentialProviderExtensionState.h"
#include "SFSharedWebCredentialsDatabaseEntry.h"
#include "SFExternalCredentialIdentityStoreManager.h"
#include "SFSharablePasswordReceiver.h"
#include "SFAutoFillFeatureManager.h"
#include "SFAutoFillOneTimeCodeEmbeddedDomainPair.h"
#include "SFAutoFillOneTimeCode.h"
#include "SFSuggestedUserProvider.h"
#include "SFCredentialProviderExtensionManager.h"
#include "SFSuggestedUser.h"
#include "TOTPGeneratorSnapshot.h"
#include "SFAppAutoFillOneTimeCodeProvider.h"
#include "_SFSharablePasswordEncryptionInformation.h"
#include "SFSharablePassword.h"
