// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.0.0 | SDK: 16.0.0


#ifndef BRCUSERDEFAULTS_H
#define BRCUSERDEFAULTS_H

@class NSDictionary, NSMutableDictionary, NSString, NSSet, NSArray, NSIndexSet;
@protocol OS_xpc_object;

#import <Foundation/Foundation.h>

#import "BRCUserDefaults.h"
#import "BRCSyncOperationThrottleParams.h"

@interface BRCUserDefaults : NSObject {
    BRCUserDefaults *_globalUserDefault;
    NSDictionary *_serverContainerConfigurationDict;
    NSMutableDictionary *_cache;
    NSString *_clientZoneIdentifier;
}


@property (readonly, nonatomic) CGFloat accessTimeDeltaInHighUrgency;
@property (readonly, nonatomic) CGFloat accessTimeDeltaInLowUrgency;
@property (readonly, nonatomic) CGFloat accessTimeDeltaInMedUrgency;
@property (readonly, nonatomic) CGFloat accessTimeDeltaInVeryHighUrgency;
@property (readonly, nonatomic) CGFloat activeDownloadSizeRefreshInterval;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *aggressivePCSChainActivity;
@property (readonly, nonatomic) NSUInteger aliasDeletionBatchSize;
@property (readonly, nonatomic) BOOL allowForceTelemetryDequeue;
@property (readonly, nonatomic) BOOL allowReadOnlyDBInIPC;
@property (readonly, nonatomic) BOOL allowsDirectoryListBeforeInitialChangeToken;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *analyticsReportXPCActivity;
@property (readonly, nonatomic) NSDictionary *appLibraryAliasRemovalThrottleParams;
@property (readonly, nonatomic) NSDictionary *appLibraryResetThrottleParams;
@property (readonly, nonatomic) NSDictionary *appLibraryScanThrottleParams;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *appTelemetryGatherXPCActivity;
@property (readonly, nonatomic) NSUInteger applyCountToSignalFaultsLive;
@property (readonly, nonatomic) NSUInteger applyRetryCountForFailure;
@property (readonly, nonatomic) unsigned int applySchedulerJobMaxRetriesBeforeAssert;
@property (readonly, nonatomic) NSDictionary *applyThrottleParams;
@property (readonly, nonatomic) CGFloat appsFetchPacerDelay;
@property (readonly, nonatomic) NSSet *autoEvictableUTIs;
@property (readonly, nonatomic) unsigned int autoResumeSyncBatchSize;
@property (readonly, nonatomic) NSUInteger availableQuotaComfortSize;
@property (readonly, nonatomic) NSSet *benignTelemetryErrorDescriptions;
@property (readonly, nonatomic) NSSet *blacklistPCSPrep;
@property (readonly, nonatomic) NSSet *blacklistedPackageExtensions;
@property (readonly, nonatomic) NSSet *blacklistedThumbnailExtensions;
@property (readonly, nonatomic) BOOL blockApplyUntilList;
@property (readonly, nonatomic) unsigned int bounceFileMaxRetries;
@property (readonly, nonatomic) CGFloat bounceFileReportInterval;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *cacheDeletePushXPCActivity;
@property (readonly, nonatomic) CGFloat cacheDeleteRecomputeInterval;
@property (readonly, nonatomic) BOOL canSaveRecordsDirectlyForDeltaSync;
@property (readonly, nonatomic) BOOL canSaveRecordsDirectlyForList;
@property (readonly, nonatomic) BOOL canSaveRecordsDirectlyWithDeletes;
@property (readonly, nonatomic) NSArray *carryPartitions;
@property (readonly, nonatomic) BOOL changeItemIDOnUnknownItem;
@property (readonly, nonatomic) BOOL ciconiaDisableAutomatedStart;
@property (readonly, nonatomic) BOOL ciconiaHideMigrationDomain;
@property (readonly, nonatomic) NSUInteger ciconiaImportTimeout;
@property (readonly, nonatomic) BOOL ciconiaKeepDomainAfterMigration;
@property (readonly, nonatomic) unsigned int ciconiaMaxFailurePerVersion;
@property (readonly, nonatomic) NSUInteger ciconiaMaxReconciliationFailures;
@property (readonly, nonatomic) NSUInteger ciconiaMaxSideFaultsMigration;
@property (readonly, nonatomic) NSUInteger ciconiaRepeatInterval;
@property (readonly, nonatomic) NSUInteger computeEvictableBatchSize;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *configurationUpdateXPCActivity;
@property (readonly, nonatomic) NSUInteger copyShareIDsBatchSize;
@property (readonly, nonatomic) NSInteger dbAutovacuumBatchSize;
@property (readonly, nonatomic) float dbAutovacuumRatio;
@property (readonly, nonatomic) CGFloat dbBatchDelay;
@property (readonly, nonatomic) int dbBatchSize;
@property (readonly, nonatomic) BOOL dbIntegrityCheckApplyJobs;
@property (readonly, nonatomic) BOOL dbIntegrityCheckDownloadJobs;
@property (readonly, nonatomic) BOOL dbIntegrityCheckReaderJobs;
@property (readonly, nonatomic) BOOL dbIntegrityCheckSyncUpJobs;
@property (readonly, nonatomic) BOOL dbIntegrityCheckUploadJobs;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *dbIntegrityCheckXPCActivity;
@property (readonly, nonatomic) NSInteger dbMigrationBatchSize;
@property (readonly, nonatomic) BOOL dbProfiled;
@property (readonly, nonatomic) NSInteger dbReclaimableSpaceThreshold;
@property (readonly, nonatomic) BOOL dbTraced;
@property (readonly, nonatomic) CGFloat defaultOnDiskAccessTimeDefaultForEviction;
@property (readonly, nonatomic) CGFloat defaultTimeDeltaForEviction;
@property (readonly, nonatomic) NSInteger delayForStuckThrottle;
@property (readonly, nonatomic) NSUInteger deleteShareIDBatchCount;
@property (readonly, nonatomic) BOOL deleteShareOnEmptySave;
@property (readonly, nonatomic) BOOL destroyiWorkShares;
@property (readonly, nonatomic) int discretionaryRecursiveListMaxOperationCount;
@property (readonly, nonatomic) CGFloat diskSpaceCheckInterval;
@property (readonly, nonatomic) NSUInteger diskSpaceRequiredToReturnToGreedyState;
@property (readonly, nonatomic) CGFloat documentAccessHighPriorityInterval;
@property (readonly, nonatomic) NSUInteger downloadBatchCount;
@property (readonly, nonatomic) NSUInteger downloadBatchRecordsCount;
@property (readonly, nonatomic) NSUInteger downloadRetryCountForFailure;
@property (readonly, nonatomic) CGFloat downloadSizeRefreshInterval;
@property (readonly, nonatomic) CGFloat downloadStageAgeDelta;
@property (readonly, nonatomic) NSDictionary *downloadThrottleParams;
@property (readonly, nonatomic) NSUInteger downloadWillRetryProgressMaxCount;
@property (readonly, nonatomic) CGFloat eventMetricTimeout;
@property (readonly, nonatomic) NSSet *excludedExtensionsWorthPreserving;
@property (readonly, nonatomic) NSSet *excludedFilenamesWorthPreserving;
@property (readonly, nonatomic) NSSet *excludedFilenamesWorthWarningAtLogout;
@property (readonly, nonatomic) NSSet *extensionsSkippingBundleBitFixup;
@property (readonly, nonatomic) NSString *fakeEtagForFailIfOutdated;
@property (readonly, nonatomic) BOOL fetchContentRecordsInline;
@property (readonly, nonatomic) BOOL fetchFullAppLibraryContents;
@property (readonly, nonatomic) BOOL fetchParticipantDocumentToken;
@property (readonly, nonatomic) BOOL fetchShareRecordsInline;
@property (readonly, nonatomic) NSUInteger fieldsToMoveOutOfTrashMask;
@property (readonly, nonatomic) BOOL forceBatchFailureWhenReceivingAssetTokenExpiration;
@property (readonly, nonatomic) BOOL forceDeltaInitialSync;
@property (readonly, nonatomic) BOOL forceFailIfExistOnRevival;
@property (readonly, nonatomic) CGFloat forceForegroundGracePeriod;
@property (readonly, nonatomic) char forceSyncOverride;
@property (readonly, nonatomic) unsigned int forceTelemetryDequeuePercentage;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *forcedSyncXPCActivity;
@property (readonly, nonatomic) CGFloat foregroundGracePeriod;
@property (readonly, nonatomic) NSUInteger fseventProcessBatchSize;
@property (readonly, nonatomic) NSUInteger fseventQueueBufferSize;
@property (readonly, nonatomic) CGFloat fseventsLatency;
@property (readonly, nonatomic) CGFloat fseventsResetBackoff;
@property (readonly, nonatomic) CGFloat graveyardAgeDeltaInLowUrgency;
@property (readonly, nonatomic) CGFloat graveyardAgeDeltaInMedUrgency;
@property (readonly, nonatomic) BOOL hasMultiAccountsHandling;
@property (readonly, nonatomic) NSSet *healthErrorsForReset;
@property (readonly, nonatomic) NSSet *healthErrorsToReport;
@property (readonly, nonatomic) NSUInteger healthZoneMaxNumberOfResets;
@property (readonly, nonatomic) CGFloat healthZoneTimeIntervalForMaxNumberOfResets;
@property (readonly, nonatomic) unsigned int highPriorityTelemetryEventsPercentage;
@property (readonly, nonatomic) unsigned int iWorkFetchPausedFilesBatchSize;
@property (readonly, nonatomic) unsigned int ignoredQuarantineMask;
@property (readonly, nonatomic) BOOL integrityCheckBoosting;
@property (readonly, nonatomic) CGFloat intervalToWaitBeforeShowingAdditionalDescription;
@property (readonly, nonatomic) BOOL isBlacklistedFromFolderSharing;
@property (readonly, nonatomic) NSSet *iworkShareableExtensions;
@property (readonly, nonatomic) NSUInteger listDirChangesCancelDelay;
@property (readonly, nonatomic) unsigned int logoutTimeout;
@property (readonly, nonatomic) NSDictionary *lostItemThrottleParams;
@property (readonly, nonatomic) NSUInteger lostItemUnderUnknownParentBeforeDeepScan;
@property (readonly, nonatomic) NSUInteger lostScanDeepScanFirstThreshold;
@property (readonly, nonatomic) CGFloat markChildLostBackoff;
@property (readonly, nonatomic) NSUInteger maxBackoffToRetryUserInitiated;
@property (readonly, nonatomic) NSUInteger maxFolderEnumerationCount;
@property (readonly, nonatomic) NSUInteger maxFolderEnumerationDepth;
@property (readonly, nonatomic) NSUInteger maxNumberOfFilesInAFolder;
@property (readonly, nonatomic) CGFloat maxPauseFileTimeout;
@property (readonly, nonatomic) NSUInteger maxPreservedXattrBlobSize;
@property (readonly, nonatomic) unsigned int maxRecordCountInClientZoneModifyRecordsOperation;
@property (readonly, nonatomic) unsigned int maxRecordCountInFetchRecordsOperation;
@property (readonly, nonatomic) unsigned int maxRecordCountInModifyRecordsOperation;
@property (readonly, nonatomic) unsigned int maxRecordCountInQuerySharedRecordsOperation;
@property (readonly, nonatomic) unsigned int maxRecordCountWhenListingDirChanges;
@property (readonly, nonatomic) unsigned int maxRelativePathDepth;
@property (readonly, nonatomic) unsigned int maxSyncPathDepth;
@property (readonly, nonatomic) NSUInteger maxTotalFilesCount;
@property (readonly, nonatomic) NSUInteger maxXattrBlobSize;
@property (readonly, nonatomic) NSUInteger maximumAccountSizeToBeAlwaysGreedy;
@property (readonly, nonatomic) CGFloat maximumDocumentAgeToBeGreedy;
@property (readonly, nonatomic) NSDictionary *migrationThrottleParams;
@property (readonly, nonatomic) NSInteger minAutomaticallyEvictableFilesize;
@property (readonly, nonatomic) CGFloat minFetchQuotaInterval;
@property (readonly, nonatomic) NSInteger minFileSizeForGraveyard;
@property (readonly, nonatomic) NSInteger minFileSizeForThumbnailTransfer;
@property (readonly, nonatomic) CGFloat minForceTelemetrySyncInterval;
@property (readonly, nonatomic) NSInteger minimalSizeToShowAdditionalDescription;
@property (readonly, nonatomic) NSUInteger minimumDiskSpaceRequiredToBeFunctional;
@property (readonly, nonatomic) NSUInteger minimumDiskSpaceRequiredToBeGreedy;
@property (readonly, nonatomic) NSUInteger minimumDiskSpaceRequiredToDownload;
@property (readonly, nonatomic) NSUInteger minimumDiskSpaceRequiredToDownloadUserInitiated;
@property (readonly, nonatomic) float modifyRecordsCountAdditiveIncreaseFraction;
@property (readonly, nonatomic) float modifyRecordsCountMultiplicativeDecrease;
@property (readonly, nonatomic) NSSet *nonAutoEvictableExtensions;
@property (readonly, nonatomic) NSSet *nonAutoEvictableUTIs;
@property (readonly, nonatomic) int nonDiscretionaryRecursiveListMaxOperationCount;
@property (readonly, nonatomic) NSSet *nonEvictableExtensions;
@property (readonly, nonatomic) NSSet *nonEvictablePathComponents;
@property (readonly, nonatomic) NSUInteger notifBatchSize;
@property (readonly, nonatomic) NSUInteger notifGatherUpTo;
@property (readonly, nonatomic) NSUInteger notifOverflowLimit;
@property (readonly, nonatomic) BOOL nsurlsessiondEnabled;
@property (readonly, nonatomic) NSUInteger numberOfGreedyRecentlyUsedItems;
@property (readonly, nonatomic) CGFloat onDiskAccessTimeDeltaInHighUrgency;
@property (readonly, nonatomic) CGFloat onDiskAccessTimeDeltaInLowUrgency;
@property (readonly, nonatomic) CGFloat onDiskAccessTimeDeltaInMedUrgency;
@property (readonly, nonatomic) CGFloat onDiskAccessTimeDeltaInVeryHighUrgency;
@property (readonly, nonatomic) BOOL onlyTreatCaughtUpAsConsistent;
@property (readonly, nonatomic) NSDictionary *operationFailureThrottleParams;
@property (readonly, nonatomic) CGFloat operationTimeout;
@property (readonly, nonatomic) CGFloat packageExtensionPlistWriteInterval;
@property (readonly, nonatomic) NSSet *packageExtensions;
@property (readonly, nonatomic) BOOL pcsChainShareAliases;
@property (readonly, nonatomic) NSUInteger pcsChainingBatchSize;
@property (readonly, nonatomic) NSUInteger pcsChainingMaxPathDepth;
@property (readonly, nonatomic) NSUInteger pendingChangesStreamCloseDelay;
@property (readonly, nonatomic) NSUInteger pendingChangesStreamHardOpenCount;
@property (readonly, nonatomic) NSUInteger pendingChangesStreamSoftOpenCount;
@property (readonly, nonatomic) NSDictionary *perItemSyncUpThrottleParams;
@property (readonly, nonatomic) CGFloat periodicSyncTimeInterval;
@property (readonly, nonatomic) CGFloat powerLogReportInterval;
@property (readonly, nonatomic) BOOL preventConcurrentModifyRecordsOperations;
@property (readonly, nonatomic) BOOL preventRecordSyncWithoutDiffs;
@property (readonly, nonatomic) BOOL preventSharingFolderWithPendingDelete;
@property (readonly, nonatomic) unsigned int publishURLTimeout;
@property (readonly, nonatomic) CGFloat purgePacerInterval;
@property (readonly, nonatomic) CGFloat qbsExpectedItemsFetchedCheckInterval;
@property (readonly, nonatomic) NSUInteger qbsExpectedItemsFetchedPerInterval;
@property (readonly, nonatomic) CGFloat quotaFetchPacerDelay;
@property (readonly, nonatomic) CGFloat readerIOsCancelDelay;
@property (readonly, nonatomic) CGFloat readerLostItemBackoff;
@property (readonly, nonatomic) NSUInteger readerMarkChildrenLostBatchSize;
@property (readonly, nonatomic) int readerMaxConcurrentIOs;
@property (readonly, nonatomic) CGFloat readerPackageProcessingDelay;
@property (readonly, nonatomic) NSUInteger readerRetryCountForFailure;
@property (readonly, nonatomic) int readerScanBatchSize;
@property (readonly, nonatomic) NSDictionary *readerThrottleParams;
@property (readonly, nonatomic) NSUInteger recentsEnumeratorBatchSize;
@property (readonly, nonatomic) NSDictionary *recentsEnumeratorFailureThrottleParams;
@property (readonly, nonatomic) NSUInteger recentsEnumeratorMaxHierarchyDepth;
@property (readonly, nonatomic) CGFloat recentsEnumeratorPacerInterval;
@property (readonly, nonatomic) NSSet *recordsToIgnoreOnSyncDown;
@property (readonly, nonatomic) NSInteger recursiveListFetchDirFaultBatchSize;
@property (readonly, nonatomic) float relativeDiskSpaceRequiredToReturnToGreedyState;
@property (readonly, nonatomic) BOOL reportXPCErrorOnPCSChain;
@property (readonly, nonatomic) NSUInteger rescheduleItemsRecursivelyBatchSize;
@property (readonly, nonatomic) NSString *serverConfigurationURL;
@property (readonly, nonatomic) NSDictionary *serverStitchingThrottleParams;
@property (readonly, nonatomic) BOOL sessionZombiesEnabled;
@property (readonly, nonatomic) NSDictionary *sharedAppLibraryResetThrottleParams;
@property (readonly, nonatomic) NSUInteger sharedDBSyncDownBatchRecordsCount;
@property (readonly, nonatomic) NSUInteger sharedDbSyncDownCoalesceNanoseconds;
@property (readonly, nonatomic) BOOL should2PhasePCSChain;
@property (readonly, nonatomic) BOOL shouldAppLibraryBeGreedy;
@property (readonly, nonatomic) BOOL shouldAutoMigrateToCloudDocs;
@property (readonly, nonatomic) NSSet *shouldBeGreedyExtensions;
@property (readonly, nonatomic) BOOL shouldDisplayUploadNotification;
@property (readonly, nonatomic) BOOL shouldFetchAllChanges;
@property (readonly, nonatomic) BOOL shouldFixupBundleBitOnPackages;
@property (readonly, nonatomic) BOOL shouldFixupTargetCZMAliases;
@property (readonly, nonatomic) BOOL shouldMigrateFetchShareAliases;
@property (readonly, nonatomic) BOOL shouldPreparePCSMigration;
@property (readonly, nonatomic) BOOL shouldReportAllPerItemFailures;
@property (readonly, nonatomic) BOOL shouldReportTelemetryEvents;
@property (readonly, nonatomic) BOOL shouldSessionBeGreedy;
@property (readonly, nonatomic) BOOL skipContainerRecordsWithMissingAssets;
@property (readonly, nonatomic) BOOL skipPerItemSyncUpThrottling;
@property (readonly, nonatomic) BOOL skipServerSideThrottling;
@property (readonly, nonatomic) BOOL skipSyncUpThrottlingOnBatchFailures;
@property (readonly, nonatomic) BOOL spotlightIndexingEnabled;
@property (readonly, nonatomic) NSUInteger sqliteCacheSize;
@property (readonly, nonatomic) NSUInteger sqliteCacheSpill;
@property (readonly, nonatomic) unsigned short stageDirectoryUmask;
@property (readonly, nonatomic) unsigned short stageFSRootUmask;
@property (readonly, nonatomic) unsigned short stageFileUmask;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *stageGCXPCActivity;
@property (readonly, nonatomic) unsigned short stageInPackageDirectoryUmask;
@property (readonly, nonatomic) unsigned short stageInPackageFileUmask;
@property (readonly, nonatomic) NSUInteger statementCacheMaxCountForClientTruth;
@property (readonly, nonatomic) NSUInteger statementCacheMaxCountForServerTruth;
@property (readonly, nonatomic) BOOL stripBirthtimeFromSyncUpMaskOnDocuments;
@property (readonly, nonatomic) unsigned int subResourceFetchLoopCacheSize;
@property (readonly, nonatomic) BOOL supportsServerSideAssetCopies;
@property (readonly, nonatomic) NSDictionary *syncClientZoneErrorThrottleParams;
@property (readonly, nonatomic) NSDictionary *syncClientZoneThrottleParams;
@property (readonly, nonatomic) BOOL syncConsistencyCheckerEnabled;
@property (readonly, nonatomic) BOOL syncConsistencyCheckerSnapshotting;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *syncConsistencyCheckerXPCActivity;
@property (readonly, nonatomic) unsigned int syncConsistencyFileChecksumRate;
@property (readonly, nonatomic) unsigned int syncConsistencyMaxEventsCount;
@property (readonly, nonatomic) unsigned int syncConsistencyPackageChecksumRate;
@property (readonly, nonatomic) CGFloat syncConsistencyTimeout;
@property (readonly, nonatomic) CGFloat syncConsistencyXPCActivityCheckLeeway;
@property (readonly, nonatomic) CGFloat syncConsistencyXPCActivityDeferralCheckInterval;
@property (readonly, nonatomic) CGFloat syncDownDelayForFailure;
@property (readonly, nonatomic) BRCSyncOperationThrottleParams *syncDownThrottle;
@property (readonly, nonatomic) NSArray *syncThrottles;
@property (readonly, nonatomic) float syncUpBackoffDelayForFailure;
@property (readonly, nonatomic) float syncUpBackoffRatioForFailure;
@property (readonly, nonatomic) float syncUpDailyBudget;
@property (readonly, nonatomic) float syncUpDataCreateCost;
@property (readonly, nonatomic) float syncUpDataDeleteCost;
@property (readonly, nonatomic) float syncUpDataEditCost;
@property (readonly, nonatomic) CGFloat syncUpDelayForFailure;
@property (readonly, nonatomic) float syncUpDocumentCreateCost;
@property (readonly, nonatomic) float syncUpDocumentDeleteCost;
@property (readonly, nonatomic) float syncUpDocumentEditCost;
@property (readonly, nonatomic) float syncUpHourlyBudget;
@property (readonly, nonatomic) float syncUpInitialItemCost;
@property (readonly, nonatomic) float syncUpMinimalBudget;
@property (readonly, nonatomic) float syncUpMinutelyBudget;
@property (readonly, nonatomic) NSUInteger syncUpRetryCountForFailure;
@property (readonly, nonatomic) float syncUpStructureCreateCost;
@property (readonly, nonatomic) float syncUpStructureDeleteCost;
@property (readonly, nonatomic) float syncUpStructureEditCost;
@property (readonly, nonatomic) BRCSyncOperationThrottleParams *syncUpThrottle;
@property (readonly, nonatomic) CGFloat systemLowDiskLatency;
@property (readonly, nonatomic) CGFloat systemPowerLatency;
@property (readonly, nonatomic) CGFloat systemReachabilityLatency;
@property (readonly, nonatomic) CGFloat telemetryApplySchedulerTimeout;
@property (readonly, nonatomic) NSUInteger telemetryErrorDescriptionMaxLength;
@property (readonly, nonatomic) NSIndexSet *telemetryEventDisabledMessages;
@property (readonly, nonatomic) unsigned int telemetryEventQueueReductionAmount;
@property (readonly, nonatomic) NSInteger telemetryEventQueueSize;
@property (readonly, nonatomic) NSInteger telemetryEventReportBatchSize;
@property (readonly, nonatomic) NSSet *telemetryHeaderSupportedClasses;
@property (readonly, nonatomic) NSInteger telemetryRetryCountForPermenentFailure;
@property (readonly, nonatomic) unsigned int thumbnailTransferQueueWidth;
@property (readonly, nonatomic) NSInteger timeoutForCZMProcessing;
@property (readonly, nonatomic) int transferQueueMaxConcurrentOperations;
@property (readonly, nonatomic) int transferQueueMinBatchSize;
@property (readonly, nonatomic) int transferQueueMinConcurrentOperations;
@property (readonly, nonatomic) CGFloat transferQueueTransferBudget;
@property (readonly, nonatomic) NSObject<OS_xpc_object> *transmogrifyXPCActivity;
@property (readonly, nonatomic) unsigned int treeEnumeratorBatchSize;
@property (readonly, nonatomic) unsigned int ubiquitousMigrationMaxBouncingAttempts;
@property (readonly, nonatomic) NSUInteger uploadBatchCount;
@property (readonly, nonatomic) NSUInteger uploadBatchRecordsCount;
@property (readonly, nonatomic) NSDictionary *uploadFileModifiedThrottleParams;
@property (readonly, nonatomic) NSInteger uploadMaxFileSize;
@property (readonly, nonatomic) NSInteger uploadMaxInPkgFileSize;
@property (readonly, nonatomic) NSInteger uploadMaxPkgFileSize;
@property (readonly, nonatomic) NSUInteger uploadRetryCountForFailure;
@property (readonly, nonatomic) NSDictionary *uploadThrottleParams;
@property (readonly, nonatomic) BOOL useFailIfOutdatedForResets;
@property (readonly, nonatomic) BOOL useShareReferenceOnSideCar;
@property (readonly, nonatomic) NSUInteger utiCacheSize;
@property (readonly, nonatomic) int writerApplyBatchSize;
@property (readonly, nonatomic) CGFloat writerIOsCancelDelay;
@property (readonly, nonatomic) int writerMaxConcurrentIOs;
@property (readonly, nonatomic) CGFloat xattrAgeDelta;
@property (readonly, nonatomic) NSUInteger zoneHealthReportedRecordNamesCount;
@property (readonly, nonatomic) NSUInteger zoneHealthSyncDownBatchRecordsCount;


+(id)_userDefaultsManager;
+(id)cachedServerConfigurationPath;
+(id)defaultsForMangledID:(id)arg0 ;
+(id)defaultsForMetadataContainer;
+(id)defaultsForSharedZone;
+(id)defaultsForSideCar;
+(int)rampNumberWithSession:(id)arg0 ;
+(void)loadCachedServerConfiguration;
+(void)reset;
-(BOOL)_isSharedDefaults;
-(BOOL)_shouldRampForKey:(id)arg0 session:(id)arg1 ;
-(BOOL)aggressivelyPCSChainWithSession:(id)arg0 ;
-(BOOL)boolForKey:(id)arg0 byDefault:(BOOL)arg1 ;
-(BOOL)boolForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 byDefault:(BOOL)arg2 ;
-(BOOL)optimisticallyPCSChainDuringResetWithSession:(id)arg0 ;
-(BOOL)optimisticallyPCSChainWithSession:(id)arg0 ;
-(CGFloat)doubleForKey:(id)arg0 min:(CGFloat)arg1 max:(CGFloat)arg2 byDefault:(CGFloat)arg3 ;
-(NSUInteger)unsignedLongLongForKey:(id)arg0 min:(NSUInteger)arg1 max:(NSUInteger)arg2 byDefault:(NSUInteger)arg3 ;
-(float)_defaultSyncUpDailyBudget;
-(float)_defaultSyncUpHourlyBudget;
-(float)_defaultSyncUpMinutelyBudget;
-(float)floatForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 min:(float)arg2 max:(float)arg3 byDefault:(float)arg4 ;
-(float)floatForKey:(id)arg0 min:(float)arg1 max:(float)arg2 byDefault:(float)arg3 ;
-(id)_UTISetFor:(id)arg0 startingWithExtensions:(id)arg1 ;
-(id)_extensionSetForKey:(id)arg0 startingWithExtensions:(id)arg1 ;
-(id)_healthErrorSetForKey:(id)arg0 byDefault:(id)arg1 ;
-(id)_loadObjectForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 validateWithBlock:(id)arg2 ;
-(id)_serverDefaultForKey:(id)arg0 ;
-(id)indexSetForKey:(id)arg0 byDefault:(id)arg1 ;
-(id)indexSetForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 byDefault:(id)arg2 ;
-(id)initAsGlobalWithServerConfiguration:(id)arg0 ;
-(id)initWithServerConfiguration:(id)arg0 globalUserDefaults:(id)arg1 clientZoneIdentifier:(id)arg2 ;
-(id)objectForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 validateWithBlock:(id)arg2 ;
-(id)stringForKey:(id)arg0 byDefault:(id)arg1 ;
-(id)stringForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 byDefault:(id)arg2 ;
-(id)xpcActivityDictionaryForKey:(id)arg0 byDefault:(id)arg1 ;
-(int)intForKey:(id)arg0 min:(int)arg1 max:(int)arg2 byDefault:(int)arg3 ;
-(unsigned int)unsignedIntForKey:(id)arg0 inheritFromGlobal:(BOOL)arg1 min:(unsigned int)arg2 max:(unsigned int)arg3 byDefault:(unsigned int)arg4 ;
-(unsigned int)unsignedIntForKey:(id)arg0 min:(unsigned int)arg1 max:(unsigned int)arg2 byDefault:(unsigned int)arg3 ;
-(unsigned short)_umaskForKey:(id)arg0 ;


@end


#endif