// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef MPSGRAPH_H
#define MPSGRAPH_H

@class NSMutableDictionary, NSMutableArray, NSSet, NSArray;

#import <Foundation/Foundation.h>

#import "MPSGraphBlock.h"

@interface MPSGraph : NSObject {
    NSMutableDictionary *_placeholderMap;
    NSMutableArray *_placeholderArray;
    NSMutableDictionary *_variableOpsMap;
    NSMutableArray *_variableOps;
    shared_ptr<mlir::MLIRContext> _context;
    *void _builder;
    OwningModuleRef _module;
    *void _symbolTable;
    NSMutableArray *_operations;
    _opaque_pthread_mutex_t _graphMutex;
    NSSet *_currentControlDependencies;
    MPSGraphBlock *_currentInsertionBlock;
    NSMutableArray *_traininableHighLevelOpVariables;
    NSMutableArray *_executableCache;
}


@property NSUInteger compilerOptions; // ivar: _compilerOptions
@property NSUInteger options; // ivar: _options
@property (readonly, nonatomic) NSArray *placeholderTensors;


+(id)new;
-(id)L2NormPooling4DGradientWithGradientTensor:(id)arg0 sourceTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)L2NormPooling4DWithSourceTensor:(id)arg0 descriptor:(id)arg1 name:(id)arg2 ;
-(id)absoluteErrorWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 reductionType:(NSUInteger)arg2 name:(id)arg3 ;
-(id)absoluteWithTensor:(id)arg0 name:(id)arg1 ;
-(id)acosWithTensor:(id)arg0 name:(id)arg1 ;
-(id)acoshWithTensor:(id)arg0 name:(id)arg1 ;
-(id)adamAssignWithInputVariableTensor:(id)arg0 momentumVariableTensor:(id)arg1 velocityVariableTensor:(id)arg2 maximumVelocityVariableTensor:(id)arg3 updates:(id)arg4 name:(id)arg5 ;
-(id)adamUpdateWithCurrentLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 valuesTensor:(id)arg4 momentumTensor:(id)arg5 velocityTensor:(id)arg6 maximumVelocityTensor:(id)arg7 gradientTensor:(id)arg8 name:(id)arg9 ;
-(id)adamUpdateWithLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 beta1PowerTensor:(id)arg4 beta2PowerTensor:(id)arg5 valuesTensor:(id)arg6 momentumTensor:(id)arg7 velocityTensor:(id)arg8 maximumVelocityTensor:(id)arg9 gradientTensor:(id)arg10 name:(id)arg11 ;
-(id)adamUpdateWithLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 iterationTensor:(id)arg4 valuesTensor:(id)arg5 momentumTensor:(id)arg6 velocityTensor:(id)arg7 gradientTensor:(id)arg8 name:(id)arg9 ;
-(id)additionWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)applyAdamWithCurrentLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 variable:(id)arg4 momentumVariable:(id)arg5 velocityVariable:(id)arg6 maximumVelocityVariable:(id)arg7 gradientTensor:(id)arg8 name:(id)arg9 ;
-(id)applyAdamWithLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 beta1PowerTensor:(id)arg4 beta2PowerTensor:(id)arg5 variable:(id)arg6 momentumVariable:(id)arg7 velocityVariable:(id)arg8 gradientTensor:(id)arg9 name:(id)arg10 ;
-(id)applyAdamWithLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 epsilonTensor:(id)arg3 iterationTensor:(id)arg4 variable:(id)arg5 momentumVariable:(id)arg6 velocityVariable:(id)arg7 gradientTensor:(id)arg8 name:(id)arg9 ;
-(id)applyStochasticGradientDescentWithLearningRateTensor:(id)arg0 variable:(id)arg1 gradientTensor:(id)arg2 name:(id)arg3 ;
-(id)asinWithTensor:(id)arg0 name:(id)arg1 ;
-(id)asinhWithTensor:(id)arg0 name:(id)arg1 ;
-(id)assignVariable:(id)arg0 withValueOfTensor:(id)arg1 name:(id)arg2 ;
-(id)atan2WithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)atanWithTensor:(id)arg0 name:(id)arg1 ;
-(id)atanhWithTensor:(id)arg0 name:(id)arg1 ;
-(id)avgPooling2DGradientWithGradientTensor:(id)arg0 sourceTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)avgPooling2DLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 strides:(id)arg2 paddingStyle:(NSUInteger)arg3 dataLayout:(NSUInteger)arg4 name:(id)arg5 ;
-(id)avgPooling2DWithSourceTensor:(id)arg0 descriptor:(id)arg1 name:(id)arg2 ;
-(id)avgPooling4DGradientWithGradientTensor:(id)arg0 sourceTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)avgPooling4DWithSourceTensor:(id)arg0 descriptor:(id)arg1 name:(id)arg2 ;
-(id)bandPartWithTensor:(id)arg0 numLowerTensor:(id)arg1 numUpperTensor:(id)arg2 name:(id)arg3 ;
-(id)batchNormalizationLayerWithTensor:(id)arg0 batchNormalizationGammaInitializer:(id)arg1 batchNormalizationBetaInitializer:(id)arg2 batchNormalizationMeanInitializer:(id)arg3 batchNormalizationVarianceInitializer:(id)arg4 batchNormalizationEpsilon:(CGFloat)arg5 dataLayout:(NSUInteger)arg6 name:(id)arg7 ;
-(id)biasAddWithTensor:(id)arg0 biases:(id)arg1 dataLayout:(NSUInteger)arg2 name:(id)arg3 ;
-(id)broadcastGradientArgsForPrimaryTensor:(id)arg0 withSecondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)broadcastTensor:(id)arg0 toShape:(id)arg1 name:(id)arg2 ;
-(id)broadcastTensor:(id)arg0 toShapeTensor:(id)arg1 name:(id)arg2 ;
-(id)castTensor:(id)arg0 toType:(unsigned int)arg1 name:(id)arg2 ;
-(id)ceilWithTensor:(id)arg0 name:(id)arg1 ;
-(id)clampWithTensor:(id)arg0 minValueTensor:(id)arg1 maxValueTensor:(id)arg2 name:(id)arg3 ;
-(id)compileWithDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 ;
-(id)compileWithDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 compilationDescriptor:(id)arg4 ;
-(id)concatTensor:(id)arg0 withTensor:(id)arg1 dimension:(NSInteger)arg2 name:(id)arg3 ;
-(id)concatTensors:(id)arg0 dimension:(NSInteger)arg1 interleave:(BOOL)arg2 name:(id)arg3 ;
-(id)concatTensors:(id)arg0 dimension:(NSInteger)arg1 name:(id)arg2 ;
-(id)constantWithData:(id)arg0 shape:(id)arg1 dataType:(unsigned int)arg2 ;
-(id)constantWithScalar:(CGFloat)arg0 dataType:(unsigned int)arg1 ;
-(id)constantWithScalar:(CGFloat)arg0 shape:(id)arg1 dataType:(unsigned int)arg2 ;
// -(id)controlDependencyWithOperations:(id)arg0 dependentBlock:(id)arg1 name:(unk)arg2  ;
-(id)convolution2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShape:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolution2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShapeTensor:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolution2DLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 outputChannelCount:(NSUInteger)arg2 strides:(id)arg3 activationType:(unsigned int)arg4 weightsInitializer:(id)arg5 biasesInitializer:(id)arg6 batchNormalizationGammaInitializer:(id)arg7 batchNormalizationBetaInitializer:(id)arg8 batchNormalizationMeanInitializer:(id)arg9 batchNormalizationVarianceInitializer:(id)arg10 batchNormalizationEpsilon:(CGFloat)arg11 paddingStyle:(NSUInteger)arg12 dataLayout:(NSUInteger)arg13 weightsLayout:(NSUInteger)arg14 name:(id)arg15 ;
-(id)convolution2DLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 outputChannelCount:(NSUInteger)arg2 strides:(id)arg3 activationType:(unsigned int)arg4 weightsInitializer:(id)arg5 biasesInitializer:(id)arg6 paddingStyle:(NSUInteger)arg7 dataLayout:(NSUInteger)arg8 weightsLayout:(NSUInteger)arg9 name:(id)arg10 ;
-(id)convolution2DLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 outputChannelCount:(NSUInteger)arg2 strides:(id)arg3 dilationRates:(id)arg4 groups:(NSUInteger)arg5 activationType:(unsigned int)arg6 weightsInitializer:(id)arg7 biasesInitializer:(id)arg8 batchNormalizationGammaInitializer:(id)arg9 batchNormalizationBetaInitializer:(id)arg10 batchNormalizationMeanInitializer:(id)arg11 batchNormalizationVarianceInitializer:(id)arg12 batchNormalizationEpsilon:(CGFloat)arg13 paddingStyle:(NSUInteger)arg14 dataLayout:(NSUInteger)arg15 weightsLayout:(NSUInteger)arg16 name:(id)arg17 ;
-(id)convolution2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShape:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolution2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShapeTensor:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolution2DWithDefaultBatchNormalizationLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 outputChannelCount:(NSUInteger)arg2 strides:(id)arg3 activationType:(unsigned int)arg4 weightsInitializer:(id)arg5 biasesInitializer:(id)arg6 paddingStyle:(NSUInteger)arg7 dataLayout:(NSUInteger)arg8 weightsLayout:(NSUInteger)arg9 name:(id)arg10 ;
-(id)convolution2DWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)convolutionTranspose2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShape:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolutionTranspose2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShapeTensor:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolutionTranspose2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShape:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolutionTranspose2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShapeTensor:(id)arg2 forwardConvolutionDescriptor:(id)arg3 name:(id)arg4 ;
-(id)convolutionTranspose2DWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 outputShape:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)convolutionTranspose2DWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 outputShapeTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)cosWithTensor:(id)arg0 name:(id)arg1 ;
-(id)coshWithTensor:(id)arg0 name:(id)arg1 ;
-(id)cropResizeWithImagesTensor:(id)arg0 boxesTensor:(id)arg1 boxIndicesTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)cropTensor:(id)arg0 dimension:(NSUInteger)arg1 amount_before:(NSUInteger)arg2 amount_after:(NSUInteger)arg3 name:(id)arg4 ;
-(id)currentLearningRateWithLearningRateTensor:(id)arg0 beta1Tensor:(id)arg1 beta2Tensor:(id)arg2 beta1PowerTensor:(id)arg3 beta2PowerTensor:(id)arg4 name:(id)arg5 ;
-(id)debugDescription;
-(id)depthToSpace2DTensor:(id)arg0 widthAxis:(NSUInteger)arg1 heightAxis:(NSUInteger)arg2 depthAxis:(NSUInteger)arg3 blockSize:(NSUInteger)arg4 usePixelShuffleOrder:(BOOL)arg5 name:(id)arg6 ;
-(id)depthToSpace2DTensor:(id)arg0 widthAxisTensor:(id)arg1 heightAxisTensor:(id)arg2 depthAxisTensor:(id)arg3 blockSize:(NSUInteger)arg4 usePixelShuffleOrder:(BOOL)arg5 name:(id)arg6 ;
-(id)depthwiseConvolution2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShape:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution2DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShapeTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShape:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution2DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShapeTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution2DWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)depthwiseConvolution3DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShape:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution3DDataGradientWithIncomingGradientTensor:(id)arg0 weightsTensor:(id)arg1 outputShapeTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution3DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShape:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution3DWeightsGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 outputShapeTensor:(id)arg2 descriptor:(id)arg3 name:(id)arg4 ;
-(id)depthwiseConvolution3DWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)dimensionSizeOfTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)dimensionSizeOfTensor:(id)arg0 axesTensor:(id)arg1 name:(id)arg2 ;
-(id)divisionNoNaNWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)divisionWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)dropoutTensor:(id)arg0 rate:(CGFloat)arg1 name:(id)arg2 ;
-(id)dropoutTensor:(id)arg0 rateTensor:(id)arg1 name:(id)arg2 ;
-(id)eluGradientWithIncomingGradient:(id)arg0 sourceTensor:(id)arg1 alpha:(CGFloat)arg2 name:(id)arg3 ;
-(id)eluWithTensor:(id)arg0 alpha:(CGFloat)arg1 name:(id)arg2 ;
-(id)encodeToCommandBuffer:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 executionDescriptor:(id)arg4 ;
-(id)equalWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)erfWithTensor:(id)arg0 name:(id)arg1 ;
-(id)expandTensor:(id)arg0 dimension:(NSUInteger)arg1 name:(id)arg2 ;
-(id)exponentBase10WithTensor:(id)arg0 name:(id)arg1 ;
-(id)exponentBase2WithTensor:(id)arg0 name:(id)arg1 ;
-(id)exponentWithTensor:(id)arg0 name:(id)arg1 ;
-(id)flatten2DTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)flatten2DTensor:(id)arg0 axisTensor:(id)arg1 name:(id)arg2 ;
-(id)floorModuloWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)floorWithTensor:(id)arg0 name:(id)arg1 ;
// -(id)forLoopWithLowerBound:(id)arg0 upperBound:(id)arg1 step:(id)arg2 initialBodyArguments:(id)arg3 body:(id)arg4 name:(unk)arg5  ;
// -(id)forLoopWithNumberOfIterations:(id)arg0 initialBodyArguments:(id)arg1 body:(id)arg2 name:(unk)arg3  ;
-(id)fullyConnectedLayerWithTensor:(id)arg0 outputChannelCount:(NSUInteger)arg1 activationType:(unsigned int)arg2 weightsInitializer:(id)arg3 biasesInitializer:(id)arg4 name:(id)arg5 ;
-(id)gatherAlongAxisWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 axis:(NSInteger)arg2 name:(id)arg3 ;
-(id)gatherNDWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 batchDimensions:(NSUInteger)arg2 name:(id)arg3 ;
-(id)gatherWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 axis:(NSInteger)arg2 batchDimensions:(NSUInteger)arg3 name:(id)arg4 ;
-(id)getCoordinateValueWithShapeTensor:(id)arg0 axisTensor:(id)arg1 name:(id)arg2 ;
-(id)getExecutableForDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 resultsDictionary:(id)arg4 executionDescriptor:(id)arg5 ;
-(id)gradientForPrimaryTensor:(id)arg0 withSecondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)gradientForPrimaryTensor:(id)arg0 withTensors:(id)arg1 name:(id)arg2 ;
-(id)greaterThanOrEqualToWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)greaterThanWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)identityWithTensor:(id)arg0 name:(id)arg1 ;
// -(id)ifWithPredicateTensor:(id)arg0 thenBlock:(id)arg1 elseBlock:(unk)arg2 name:(id)arg3  ;
-(id)init;
-(id)isFiniteWithTensor:(id)arg0 name:(id)arg1 ;
-(id)isInfiniteWithTensor:(id)arg0 name:(id)arg1 ;
-(id)isNaNWithTensor:(id)arg0 name:(id)arg1 ;
-(id)kernelPredictorWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 layout:(NSUInteger)arg2 kernelShape:(id)arg3 dilationRates:(id)arg4 name:(id)arg5 ;
-(id)kernelPredictorWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 layout:(NSUInteger)arg2 kernelShape:(id)arg3 name:(id)arg4 ;
-(id)leakyReLUGradientWithIncomingGradient:(id)arg0 sourceTensor:(id)arg1 alphaTensor:(id)arg2 name:(id)arg3 ;
-(id)leakyReLUWithTensor:(id)arg0 alpha:(CGFloat)arg1 name:(id)arg2 ;
-(id)leakyReLUWithTensor:(id)arg0 alphaTensor:(id)arg1 name:(id)arg2 ;
-(id)lessThanOrEqualToWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)lessThanWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)localConvolutionDataGradientWithIncomingGradientTensor:(id)arg0 weightTensor:(id)arg1 dataLayout:(NSUInteger)arg2 kernelShape:(id)arg3 dilationRateInX:(NSUInteger)arg4 dilationRateInY:(NSUInteger)arg5 name:(id)arg6 ;
-(id)localConvolutionWeightGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 dataLayout:(NSUInteger)arg2 kernelShape:(id)arg3 dilationRateInX:(NSUInteger)arg4 dilationRateInY:(NSUInteger)arg5 name:(id)arg6 ;
-(id)localConvolutionWithSourceTensor:(id)arg0 weightTensor:(id)arg1 dataLayout:(NSUInteger)arg2 kernelShape:(id)arg3 dilationRateInX:(NSUInteger)arg4 dilationRateInY:(NSUInteger)arg5 name:(id)arg6 ;
-(id)logarithmBase10WithTensor:(id)arg0 name:(id)arg1 ;
-(id)logarithmBase2WithTensor:(id)arg0 name:(id)arg1 ;
-(id)logarithmWithTensor:(id)arg0 name:(id)arg1 ;
-(id)logicalANDWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)logicalNANDWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)logicalNORWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)logicalORWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)logicalXNORWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)logicalXORWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)lossReductionWithTensor:(id)arg0 reductionType:(NSUInteger)arg1 axis:(*NSInteger)arg2 name:(id)arg3 ;
-(id)makeListWithElementType:(id)arg0 maxSize:(NSUInteger)arg1 name:(id)arg2 ;
-(id)makeListWithElementType:(id)arg0 name:(id)arg1 ;
-(id)mathOpsWithTensors:(id)arg0 mathOpType:(NSUInteger)arg1 name:(id)arg2 ;
-(id)matrixMultiplicationPrimaryGradientWithIncomingGradientTensor:(id)arg0 primaryTensor:(id)arg1 secondaryTensor:(id)arg2 name:(id)arg3 ;
-(id)matrixMultiplicationSecondaryGradientWithIncomingGradientTensor:(id)arg0 primaryTensor:(id)arg1 secondaryTensor:(id)arg2 name:(id)arg3 ;
-(id)matrixMultiplicationWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)maxPooling2DGradientWithGradientTensor:(id)arg0 sourceTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)maxPooling2DLayerWithTensor:(id)arg0 kernelSizes:(id)arg1 strides:(id)arg2 paddingStyle:(NSUInteger)arg3 dataLayout:(NSUInteger)arg4 name:(id)arg5 ;
-(id)maxPooling2DWithSourceTensor:(id)arg0 descriptor:(id)arg1 name:(id)arg2 ;
-(id)maxPooling4DGradientWithGradientTensor:(id)arg0 sourceTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)maxPooling4DWithSourceTensor:(id)arg0 descriptor:(id)arg1 name:(id)arg2 ;
-(id)maximumWithNaNPropagationWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)maximumWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)meanOfTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)minimumWithNaNPropagationWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)minimumWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)moduloWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)momentumUpdateWithBetaTensor:(id)arg0 momentumTensor:(id)arg1 gradientTensor:(id)arg2 name:(id)arg3 ;
-(id)multiplicationWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)negativeWithTensor:(id)arg0 name:(id)arg1 ;
-(id)normalizationBetaGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 reductionAxes:(id)arg2 name:(id)arg3 ;
-(id)normalizationGammaGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 meanTensor:(id)arg2 varianceTensor:(id)arg3 reductionAxes:(id)arg4 epsilon:(float)arg5 name:(id)arg6 ;
-(id)normalizationGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 meanTensor:(id)arg2 varianceTensor:(id)arg3 gammaTensor:(id)arg4 gammaGradientTensor:(id)arg5 betaGradientTensor:(id)arg6 reductionAxes:(id)arg7 epsilon:(float)arg8 name:(id)arg9 ;
-(id)normalizationWithTensor:(id)arg0 meanTensor:(id)arg1 varianceTensor:(id)arg2 gammaTensor:(id)arg3 betaTensor:(id)arg4 epsilon:(float)arg5 name:(id)arg6 ;
-(id)notEqualWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)notWithTensor:(id)arg0 name:(id)arg1 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 axis:(NSUInteger)arg2 dataType:(unsigned int)arg3 name:(id)arg4 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 axis:(NSUInteger)arg2 dataType:(unsigned int)arg3 onValue:(CGFloat)arg4 offValue:(CGFloat)arg5 name:(id)arg6 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 axis:(NSUInteger)arg2 name:(id)arg3 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 dataType:(unsigned int)arg2 name:(id)arg3 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 dataType:(unsigned int)arg2 onValue:(CGFloat)arg3 offValue:(CGFloat)arg4 name:(id)arg5 ;
-(id)oneHotWithIndicesTensor:(id)arg0 depth:(NSUInteger)arg1 name:(id)arg2 ;
-(id)operationWithName:(id)arg0 ;
-(id)padGradientWithIncomingGradientTensor:(id)arg0 inputTensor:(id)arg1 paddingMode:(NSInteger)arg2 paddingTensor:(id)arg3 constantValuesTensor:(id)arg4 name:(id)arg5 ;
-(id)padGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 paddingMode:(NSInteger)arg2 leftPadding:(id)arg3 rightPadding:(id)arg4 name:(id)arg5 ;
-(id)padGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 paddingMode:(NSInteger)arg2 paddingTensor:(id)arg3 name:(id)arg4 ;
-(id)padTensor:(id)arg0 paddingMode:(NSInteger)arg1 paddingTensor:(id)arg2 constantValuesTensor:(id)arg3 name:(id)arg4 ;
-(id)padTensor:(id)arg0 withPaddingMode:(NSInteger)arg1 leftPadding:(id)arg2 rightPadding:(id)arg3 constantValue:(CGFloat)arg4 name:(id)arg5 ;
-(id)paddingTensorWithLeftPadding:(id)arg0 rightPadding:(id)arg1 ;
-(id)placeholderWithShape:(id)arg0 dataType:(unsigned int)arg1 name:(id)arg2 ;
-(id)placeholderWithShape:(id)arg0 name:(id)arg1 ;
-(id)popBackFromList:(id)arg0 outputList:(*id)arg1 name:(id)arg2 ;
-(id)powerWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)pushBackToList:(id)arg0 element:(id)arg1 name:(id)arg2 ;
-(id)randomUniformTensorWithShape:(id)arg0 name:(id)arg1 ;
-(id)randomUniformTensorWithShape:(id)arg0 seed:(NSUInteger)arg1 name:(id)arg2 ;
-(id)randomUniformTensorWithShapeTensor:(id)arg0 name:(id)arg1 ;
-(id)randomUniformTensorWithShapeTensor:(id)arg0 seed:(NSUInteger)arg1 name:(id)arg2 ;
-(id)rankOfTensor:(id)arg0 name:(id)arg1 ;
-(id)reLUGradientWithIncomingGradient:(id)arg0 sourceTensor:(id)arg1 name:(id)arg2 ;
-(id)reLUWithTensor:(id)arg0 name:(id)arg1 ;
-(id)readVariable:(id)arg0 name:(id)arg1 ;
-(id)reciprocalWithTensor:(id)arg0 name:(id)arg1 ;
-(id)reductionArgMaximumWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reductionArgMinimumWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reductionMaximumWithTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)reductionMaximumWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reductionMinimumWithTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)reductionMinimumWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reductionProductWithTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)reductionProductWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reductionSumWithTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)reductionSumWithTensor:(id)arg0 axesTensor:(id)arg1 name:(id)arg2 ;
-(id)reductionSumWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)reshapeTensor:(id)arg0 withShape:(id)arg1 name:(id)arg2 ;
-(id)reshapeTensor:(id)arg0 withShapeTensor:(id)arg1 name:(id)arg2 ;
-(id)resizeTensor:(id)arg0 size:(id)arg1 mode:(NSUInteger)arg2 centerResult:(BOOL)arg3 alignCorners:(BOOL)arg4 layout:(NSUInteger)arg5 name:(id)arg6 ;
-(id)resizeTensor:(id)arg0 sizeTensor:(id)arg1 mode:(NSUInteger)arg2 centerResult:(BOOL)arg3 alignCorners:(BOOL)arg4 layout:(NSUInteger)arg5 name:(id)arg6 ;
-(id)resizeWithGradientTensor:(id)arg0 input:(id)arg1 mode:(NSUInteger)arg2 centerResult:(BOOL)arg3 alignCorners:(BOOL)arg4 layout:(NSUInteger)arg5 name:(id)arg6 ;
-(id)reverseSquareRootWithTensor:(id)arg0 name:(id)arg1 ;
-(id)reverseTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)reverseTensor:(id)arg0 axesTensor:(id)arg1 name:(id)arg2 ;
-(id)reverseTensor:(id)arg0 name:(id)arg1 ;
-(id)rintWithTensor:(id)arg0 name:(id)arg1 ;
-(id)roundWithTensor:(id)arg0 name:(id)arg1 ;
-(id)runAsyncWithDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 executionDescriptor:(id)arg4 ;
-(id)runAsyncWithFeeds:(id)arg0 targetTensors:(id)arg1 targetOperations:(id)arg2 executionDescriptor:(id)arg3 ;
-(id)runAsyncWithMTLCommandQueue:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 executionDescriptor:(id)arg4 ;
-(id)runInternalWithMPSCommandBuffer:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 resultsDictionary:(id)arg4 executionDescriptor:(id)arg5 mpsGraphOwnedCommandBuffer:(BOOL)arg6 ;
-(id)runInternalWithMPSGraphDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 resultsDictionary:(id)arg4 executionDescriptor:(id)arg5 ;
-(id)runInternalWithMTLCommandQueue:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 resultsDictionary:(id)arg4 executionDescriptor:(id)arg5 ;
-(id)runWithDevice:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 executionDescriptor:(id)arg4 ;
-(id)runWithFeeds:(id)arg0 targetTensors:(id)arg1 targetOperations:(id)arg2 ;
-(id)runWithMTLCommandQueue:(id)arg0 feeds:(id)arg1 targetTensors:(id)arg2 targetOperations:(id)arg3 ;
-(id)sampleGridDataGradientWithIncomingGradientTensor:(id)arg0 coordinateTensor:(id)arg1 outputShape:(id)arg2 normalizeCoordinates:(BOOL)arg3 relativeCoordinates:(BOOL)arg4 paddingMode:(NSInteger)arg5 samplingMode:(NSUInteger)arg6 name:(id)arg7 ;
-(id)sampleGridDataGradientWithIncomingGradientTensor:(id)arg0 coordinateTensor:(id)arg1 outputShapeTensor:(id)arg2 normalizeCoordinates:(BOOL)arg3 relativeCoordinates:(BOOL)arg4 paddingMode:(NSInteger)arg5 samplingMode:(NSUInteger)arg6 name:(id)arg7 ;
-(id)sampleGridWithSourceTensor:(id)arg0 coordinateTensor:(id)arg1 normalizeCoordinates:(BOOL)arg2 relativeCoordinates:(BOOL)arg3 paddingMode:(NSInteger)arg4 samplingMode:(NSUInteger)arg5 constantValue:(CGFloat)arg6 name:(id)arg7 ;
-(id)scatterAlongAxisWithDataTensor:(id)arg0 updatesTensor:(id)arg1 indicesTensor:(id)arg2 axis:(NSInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterAlongAxisWithDataTensor:(id)arg0 updatesTensor:(id)arg1 indicesTensor:(id)arg2 axis:(NSInteger)arg3 name:(id)arg4 ;
-(id)scatterAlongAxisWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 axis:(NSInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterAlongAxisWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 axis:(NSInteger)arg3 name:(id)arg4 ;
-(id)scatterNDWithDataTensor:(id)arg0 updatesTensor:(id)arg1 indicesTensor:(id)arg2 batchDimensions:(NSUInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterNDWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 batchDimensions:(NSUInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterNDWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 batchDimensions:(NSUInteger)arg3 name:(id)arg4 ;
-(id)scatterWithDataTensor:(id)arg0 updatesTensor:(id)arg1 indicesTensor:(id)arg2 axis:(NSInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterWithDataTensor:(id)arg0 updatesTensor:(id)arg1 indicesTensor:(id)arg2 axis:(NSInteger)arg3 name:(id)arg4 ;
-(id)scatterWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 axis:(NSInteger)arg3 mode:(NSInteger)arg4 name:(id)arg5 ;
-(id)scatterWithUpdatesTensor:(id)arg0 indicesTensor:(id)arg1 shape:(id)arg2 axis:(NSInteger)arg3 name:(id)arg4 ;
-(id)selectWithPredicateTensor:(id)arg0 truePredicateTensor:(id)arg1 falsePredicateTensor:(id)arg2 name:(id)arg3 ;
-(id)shapeOfTensor:(id)arg0 name:(id)arg1 ;
-(id)sigmoidGradientWithIncomingGradient:(id)arg0 sourceTensor:(id)arg1 name:(id)arg2 ;
-(id)sigmoidWithTensor:(id)arg0 name:(id)arg1 ;
-(id)signWithTensor:(id)arg0 name:(id)arg1 ;
-(id)signbitWithTensor:(id)arg0 name:(id)arg1 ;
-(id)sinWithTensor:(id)arg0 name:(id)arg1 ;
-(id)sinhWithTensor:(id)arg0 name:(id)arg1 ;
-(id)sizeOfTensor:(id)arg0 name:(id)arg1 ;
-(id)sliceGradientTensor:(id)arg0 fwdInShapeTensor:(id)arg1 starts:(id)arg2 ends:(id)arg3 strides:(id)arg4 name:(id)arg5 ;
-(id)sliceGradientTensor:(id)arg0 fwdInShapeTensor:(id)arg1 starts:(id)arg2 ends:(id)arg3 strides:(id)arg4 startMask:(unsigned int)arg5 endMask:(unsigned int)arg6 squeezeMask:(unsigned int)arg7 name:(id)arg8 ;
-(id)sliceTensor:(id)arg0 dimension:(NSUInteger)arg1 start:(NSInteger)arg2 length:(NSInteger)arg3 name:(id)arg4 ;
-(id)sliceTensor:(id)arg0 starts:(id)arg1 ends:(id)arg2 strides:(id)arg3 name:(id)arg4 ;
-(id)sliceTensor:(id)arg0 starts:(id)arg1 ends:(id)arg2 strides:(id)arg3 startMask:(unsigned int)arg4 endMask:(unsigned int)arg5 squeezeMask:(unsigned int)arg6 name:(id)arg7 ;
-(id)softMaxCrossEntropyGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 labelsTensor:(id)arg2 axis:(NSInteger)arg3 reductionType:(NSUInteger)arg4 name:(id)arg5 ;
-(id)softMaxCrossEntropyWithSourceTensor:(id)arg0 labelsTensor:(id)arg1 axis:(NSInteger)arg2 reductionType:(NSUInteger)arg3 name:(id)arg4 ;
-(id)softMaxGradientWithIncomingGradient:(id)arg0 sourceTensor:(id)arg1 axis:(NSInteger)arg2 name:(id)arg3 ;
-(id)softMaxWithTensor:(id)arg0 axis:(NSInteger)arg1 name:(id)arg2 ;
-(id)spaceToDepth2DTensor:(id)arg0 widthAxis:(NSUInteger)arg1 heightAxis:(NSUInteger)arg2 depthAxis:(NSUInteger)arg3 blockSize:(NSUInteger)arg4 usePixelShuffleOrder:(BOOL)arg5 name:(id)arg6 ;
-(id)spaceToDepth2DTensor:(id)arg0 widthAxisTensor:(id)arg1 heightAxisTensor:(id)arg2 depthAxisTensor:(id)arg3 blockSize:(NSUInteger)arg4 usePixelShuffleOrder:(BOOL)arg5 name:(id)arg6 ;
-(id)sparseTensorWithDescriptor:(id)arg0 tensors:(id)arg1 shape:(id)arg2 name:(id)arg3 ;
-(id)sparseTensorWithType:(NSUInteger)arg0 tensors:(id)arg1 shape:(id)arg2 dataType:(unsigned int)arg3 name:(id)arg4 ;
-(id)squareRootWithTensor:(id)arg0 name:(id)arg1 ;
-(id)squareWithTensor:(id)arg0 name:(id)arg1 ;
-(id)squaredErrorWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 reductionType:(NSUInteger)arg2 name:(id)arg3 ;
-(id)squeezeTensor:(id)arg0 dimension:(NSUInteger)arg1 name:(id)arg2 ;
-(id)stencilWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 descriptor:(id)arg2 name:(id)arg3 ;
-(id)stencilWithSourceTensor:(id)arg0 weightsTensor:(id)arg1 offsets:(id)arg2 name:(id)arg3 ;
// -(id)stitchedOpsWithBlock:(id)arg0 name:(unk)arg1  ;
-(id)stochasticGradientDescentWithLearningRateTensor:(id)arg0 valuesTensor:(id)arg1 gradientTensor:(id)arg2 name:(id)arg3 ;
-(id)subtractionWithPrimaryTensor:(id)arg0 secondaryTensor:(id)arg1 name:(id)arg2 ;
-(id)tanWithTensor:(id)arg0 name:(id)arg1 ;
-(id)tanhWithTensor:(id)arg0 name:(id)arg1 ;
-(id)tileGradientWithIncomingGradientTensor:(id)arg0 sourceTensor:(id)arg1 withMultiplier:(id)arg2 name:(id)arg3 ;
-(id)tileTensor:(id)arg0 withMultiplier:(id)arg1 name:(id)arg2 ;
-(id)tileTensorWithMultiplier:(id)arg0 ;
-(id)topKWithGradientTensor:(id)arg0 source:(id)arg1 k:(NSUInteger)arg2 name:(id)arg3 ;
-(id)topKWithGradientTensor:(id)arg0 source:(id)arg1 kTensor:(id)arg2 name:(id)arg3 ;
-(id)topKWithSourceTensor:(id)arg0 k:(NSUInteger)arg1 name:(id)arg2 ;
-(id)topKWithSourceTensor:(id)arg0 kTensor:(id)arg1 name:(id)arg2 ;
-(id)traininableHighLevelOpVariables;
-(id)transposeTensor:(id)arg0 dimension:(NSUInteger)arg1 withDimension:(NSUInteger)arg2 name:(id)arg3 ;
-(id)transposeTensor:(id)arg0 permute:(id)arg1 name:(id)arg2 ;
-(id)variableOps;
-(id)variableWithData:(id)arg0 shape:(id)arg1 dataType:(unsigned int)arg2 name:(id)arg3 ;
-(id)varianceOfTensor:(id)arg0 axes:(id)arg1 name:(id)arg2 ;
-(id)varianceOfTensor:(id)arg0 meanTensor:(id)arg1 axes:(id)arg2 name:(id)arg3 ;
-(id)velocityUpdateWithBetaTensor:(id)arg0 velocityTensor:(id)arg1 gradientTensor:(id)arg2 name:(id)arg3 ;
// -(id)whileWithInitialInputs:(id)arg0 before:(id)arg1 after:(unk)arg2 name:(id)arg3  ;
-(void)dealloc;
-(void)dump;
-(void)encodeToCommandBuffer:(id)arg0 feeds:(id)arg1 targetOperations:(id)arg2 resultsDictionary:(id)arg3 executionDescriptor:(id)arg4 ;
-(void)runAsyncWithDevice:(id)arg0 feeds:(id)arg1 targetOperations:(id)arg2 resultsDictionary:(id)arg3 executionDescriptor:(id)arg4 ;
-(void)runAsyncWithMTLCommandQueue:(id)arg0 feeds:(id)arg1 targetOperations:(id)arg2 resultsDictionary:(id)arg3 executionDescriptor:(id)arg4 ;
-(void)runWithDevice:(id)arg0 feeds:(id)arg1 targetOperations:(id)arg2 resultsDictionary:(id)arg3 executionDescriptor:(id)arg4 ;
-(void)runWithMTLCommandQueue:(id)arg0 feeds:(id)arg1 targetOperations:(id)arg2 resultsDictionary:(id)arg3 ;


@end


#endif