

#include "VGVehicleDeduper.h"
#include "VGVehicle.h"
#include "VGVehicleStateStorage.h"
#include "VGDataCoordinator.h"
#include "VGExternalAccessoryState.h"
#include "VGExternalAccessory.h"
#include "VGVehicleState.h"
#include "VGDenylistEntry.h"
#include "VGExternalAccessoryModelFilter.h"
#include "VGVirtualGarage.h"
#include "VGOEMApplicationFinder.h"
#include "VGOEMApplication.h"
#include "VGVirtualGarageServer.h"
#include "VGVirtualGarageService.h"
