// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 16.5.0 | SDK: 16.5.0


#ifndef WKCONTENTVIEW_H
#define WKCONTENTVIEW_H

@class NSIndexSet, RTIInputSystemSourceSession, NSString, UITextPosition, UIContextMenuInteraction, NSArray, UIView<WKFormControl>, UIWebFormAccessory, UIGestureRecognizer, UIView, UITextInputAssistantItem, UIInputContextHistory, UIColor, UITextInteractionAssistant, UITextRange, NSDictionary, UITextInputPasswordRules, UIImage, _UISupplementalLexicon, UITextInputTraits, UIWKTextInteractionAssistant, UIWebTouchEventsGestureRecognizer, NSUndoManager;
@protocol _WKWebViewPrintProvider, UIGestureRecognizerDelegate, UITextAutoscrolling, UITextInputMultiDocument, UITextInputPrivate, UIWebFormAccessoryDelegate, UIWebTouchEventsGestureRecognizerDelegate, UIWKInteractionViewProtocol, _UITextInputTranslationSupport, WKActionSheetAssistantDelegate, WKFileUploadPanelDelegate, WKKeyboardScrollViewAnimatorDelegate, WKDeferringGestureRecognizerDelegate, WKContactPickerDelegate, WKShareSheetDelegate, UIDragInteractionDelegate, UIDropInteractionDelegate, WKTouchActionGestureRecognizerDelegate, UITextSearching, UIContextMenuInteractionDelegate, UIPreviewItemDelegate, UITextInputDelegate, NSObject><NSCopying, UITextInputSuggestionDelegate, UITextInputTokenizer;


#import "WKApplicationStateTrackingView.h"
#import "WKBrowsingContextController.h"
#import "WKDateTimeInputControl.h"
#import "WKFormSelectControl.h"

@interface WKContentView : WKApplicationStateTrackingView <_WKWebViewPrintProvider, UIGestureRecognizerDelegate, UITextAutoscrolling, UITextInputMultiDocument, UITextInputPrivate, UIWebFormAccessoryDelegate, UIWebTouchEventsGestureRecognizerDelegate, UIWKInteractionViewProtocol, _UITextInputTranslationSupport, WKActionSheetAssistantDelegate, WKFileUploadPanelDelegate, WKKeyboardScrollViewAnimatorDelegate, WKDeferringGestureRecognizerDelegate, WKContactPickerDelegate, WKShareSheetDelegate, UIDragInteractionDelegate, UIDropInteractionDelegate, WKTouchActionGestureRecognizerDelegate, UITextSearching, UIContextMenuInteractionDelegate, UIPreviewItemDelegate>

 {
    RefPtr<WebKit::WebPageProxy, WTF::RawPtrTraits<WebKit::WebPageProxy>, WTF::DefaultRefDerefTraits<WebKit::WebPageProxy>> _page;
    WeakObjCPtr<WKWebView> _webView;
    RetainPtr<WKDeferringGestureRecognizer> _touchStartDeferringGestureRecognizerForImmediatelyResettableGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchStartDeferringGestureRecognizerForDelayedResettableGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchStartDeferringGestureRecognizerForSyntheticTapGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchEndDeferringGestureRecognizerForImmediatelyResettableGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchEndDeferringGestureRecognizerForDelayedResettableGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchEndDeferringGestureRecognizerForSyntheticTapGestures;
    RetainPtr<WKDeferringGestureRecognizer> _touchMoveDeferringGestureRecognizer;
    optional<WTF::HashSet<WTF::RetainPtr<WKDeferringGestureRecognizer>>> _failedTouchStartDeferringGestures;
    RetainPtr<WKDeferringGestureRecognizer> _imageAnalysisDeferringGestureRecognizer;
    unique_ptr<WebKit::GestureRecognizerConsistencyEnforcer, std::default_delete<WebKit::GestureRecognizerConsistencyEnforcer>> _gestureRecognizerConsistencyEnforcer;
    RetainPtr<UIWebTouchEventsGestureRecognizer> _touchEventGestureRecognizer;
    BOOL _touchEventsCanPreventNativeGestures;
    BOOL _preventsPanningInXAxis;
    BOOL _preventsPanningInYAxis;
    RetainPtr<WKSyntheticTapGestureRecognizer> _singleTapGestureRecognizer;
    RetainPtr<WKHighlightLongPressGestureRecognizer> _highlightLongPressGestureRecognizer;
    RetainPtr<UILongPressGestureRecognizer> _longPressGestureRecognizer;
    RetainPtr<WKSyntheticTapGestureRecognizer> _doubleTapGestureRecognizer;
    RetainPtr<UITapGestureRecognizer> _nonBlockingDoubleTapGestureRecognizer;
    RetainPtr<UITapGestureRecognizer> _doubleTapGestureRecognizerForDoubleClick;
    RetainPtr<UITapGestureRecognizer> _twoFingerDoubleTapGestureRecognizer;
    RetainPtr<UITapGestureRecognizer> _twoFingerSingleTapGestureRecognizer;
    RetainPtr<WKInspectorNodeSearchGestureRecognizer> _inspectorNodeSearchGestureRecognizer;
    RetainPtr<WKTouchActionGestureRecognizer> _touchActionGestureRecognizer;
    RetainPtr<UISwipeGestureRecognizer> _touchActionLeftSwipeGestureRecognizer;
    RetainPtr<UISwipeGestureRecognizer> _touchActionRightSwipeGestureRecognizer;
    RetainPtr<UISwipeGestureRecognizer> _touchActionUpSwipeGestureRecognizer;
    RetainPtr<UISwipeGestureRecognizer> _touchActionDownSwipeGestureRecognizer;
    RetainPtr<WKMouseGestureRecognizer> _mouseGestureRecognizer;
    unsigned char _mouseEventPolicy;
    RetainPtr<WKMouseGestureRecognizer> _pencilHoverGestureRecognizer;
    RetainPtr<UIIndirectScribbleInteraction> _scribbleInteraction;
    RetainPtr<UIPointerInteraction> _pointerInteraction;
    BOOL _hasOutstandingPointerInteractionRequest;
    optional<std::pair<WebKit::InteractionInformationRequest, WTF::BlockPtr<void (UIPointerRegion *)>>> _deferredPointerInteractionRequest;
    RetainPtr<UIWKTextInteractionAssistant> _textInteractionAssistant;
    OptionSet<WebKit::SuppressSelectionAssistantReason> _suppressSelectionAssistantReasons;
    RetainPtr<UITextInputTraits> _traits;
    RetainPtr<UIWebFormAccessory> _formAccessoryView;
    RetainPtr<_UIHighlightView> _highlightView;
    RetainPtr<UIView> _interactionViewsContainerView;
    RetainPtr<WKTargetedPreviewContainer> _contextMenuHintContainerView;
    WeakObjCPtr<UIScrollView> _scrollViewForTargetedPreview;
    CGPoint _scrollViewForTargetedPreviewInitialOffset;
    RetainPtr<WKTargetedPreviewContainer> _dragPreviewContainerView;
    RetainPtr<WKTargetedPreviewContainer> _dropPreviewContainerView;
    RetainPtr<NSString> _markedText;
    RetainPtr<WKActionSheetAssistant> _actionSheetAssistant;
    RetainPtr<WKAirPlayRoutePicker> _airPlayRoutePicker;
    RetainPtr<WKFormInputSession> _formInputSession;
    RetainPtr<WKFileUploadPanel> _fileUploadPanel;
    FrameInfoData _frameInfoForFileUploadPanel;
    RetainPtr<WKShareSheet> _shareSheet;
    RetainPtr<WKContactPicker> _contactPicker;
    RetainPtr<UIGestureRecognizer> _previewGestureRecognizer;
    RetainPtr<UIGestureRecognizer> _previewSecondaryGestureRecognizer;
    Vector<bool, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _focusStateStack;
    RetainPtr<UIContextMenuInteraction> _contextMenuInteraction;
    RetainPtr<WKContextMenuElementInfo> _contextMenuElementInfo;
    BOOL _showLinkPreviews;
    RetainPtr<UIViewController> _contextMenuLegacyPreviewController;
    RetainPtr<UIMenu> _contextMenuLegacyMenu;
    BOOL _contextMenuHasRequestedLegacyData;
    BOOL _contextMenuActionProviderDelegateNeedsOverride;
    BOOL _contextMenuIsUsingAlternateURLForImage;
    BOOL _isDisplayingContextMenuWithAnimation;
    RetainPtr<UIPreviewItemController> _previewItemController;
    RefPtr<WebCore::TextIndicator, WTF::RawPtrTraits<WebCore::TextIndicator>, WTF::DefaultRefDerefTraits<WebCore::TextIndicator>> _textIndicator;
    RetainPtr<WebTextIndicatorLayer> _textIndicatorLayer;
    RetainPtr<UITargetedPreview> _contextMenuInteractionTargetedPreview;
    unique_ptr<WebKit::SmartMagnificationController, std::default_delete<WebKit::SmartMagnificationController>> _smartMagnificationController;
    WeakObjCPtr<id<UITextInputDelegate>> _inputDelegate;
    ObjectIdentifier<WebKit::TapIdentifierType> _latestTapID;
    TapHighlightInformation _tapHighlightInformation;
    WebAutocorrectionContext _lastAutocorrectionContext;
    WKAutoCorrectionData _autocorrectionData;
    InteractionInformationAtPosition _positionInformation;
    FocusedElementInformation _focusedElementInformation;
    RetainPtr<NSObject<WKFormPeripheral>> _inputPeripheral;
    BlockPtr<void (WebEvent *, bool)> _keyWebEventHandler;
    CGPoint _lastInteractionLocation;
    MonotonicObjectIdentifier<WebKit::TransactionIDType> _layerTreeTransactionIdAtLastInteractionStart;
    WKSelectionDrawingInfo _lastSelectionDrawingInfo;
    RetainPtr<WKTextRange> _cachedSelectedTextRange;
    optional<WebKit::InteractionInformationRequest> _lastOutstandingPositionInformationRequest;
    NSUInteger _positionInformationCallbackDepth;
    Vector<std::optional<std::pair<WebKit::InteractionInformationRequest, WTF::BlockPtr<void (WebKit::InteractionInformationAtPosition)>>>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _pendingPositionInformationHandlers;
    OptionSet<WebKit::InputViewUpdateDeferralSource> _inputViewUpdateDeferralSources;
    RetainPtr<WKKeyboardScrollViewAnimator> _keyboardScrollingAnimator;
    Vector<WTF::BlockPtr<void ()>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _actionsToPerformAfterEditorStateUpdate;
    RetainPtr<UIView<WKFormControl>> _dataListTextSuggestionsInputView;
    RetainPtr<NSArray<UITextSuggestion *>> _dataListTextSuggestions;
    WeakObjCPtr<WKDataListSuggestionsControl> _dataListSuggestionsControl;
    RefPtr<WebKit::RevealFocusedElementDeferrer, WTF::RawPtrTraits<WebKit::RevealFocusedElementDeferrer>, WTF::DefaultRefDerefTraits<WebKit::RevealFocusedElementDeferrer>> _revealFocusedElementDeferrer;
    BOOL _isEditable;
    BOOL _showingTextStyleOptions;
    BOOL _hasValidPositionInformation;
    BOOL _isTapHighlightIDValid;
    BOOL _isTapHighlightFading;
    BOOL _potentialTapInProgress;
    BOOL _isDoubleTapPending;
    BOOL _longPressCanClick;
    BOOL _hasTapHighlightForPotentialTap;
    BOOL _selectionNeedsUpdate;
    BOOL _shouldRestoreSelection;
    BOOL _usingGestureForSelection;
    BOOL _inspectorNodeSearchEnabled;
    BOOL _isChangingFocusUsingAccessoryTab;
    BOOL _didAccessoryTabInitiateFocus;
    BOOL _isExpectingFastSingleTapCommit;
    BOOL _showDebugTapHighlightsForFastClicking;
    BOOL _textInteractionDidChangeFocusedElement;
    BOOL _treatAsContentEditableUntilNextEditorStateUpdate;
    BOOL _isWaitingOnPositionInformation;
    BOOL _autocorrectionContextNeedsUpdate;
    int _commitPotentialTapPointerId;
    BOOL _keyboardDidRequestDismissal;
    BOOL _candidateViewNeedsUpdate;
    BOOL _seenHardwareKeyDownInNonEditableElement;
    BOOL _becomingFirstResponder;
    BOOL _needsDeferredEndScrollingSelectionUpdate;
    BOOL _isChangingFocus;
    BOOL _isFocusingElementWithKeyboard;
    BOOL _isBlurringFocusedElement;
    BOOL _isRelinquishingFirstResponderToFocusedElement;
    BOOL _unsuppressSoftwareKeyboardAfterNextAutocorrectionContextUpdate;
    BOOL _isUnsuppressingSoftwareKeyboardUsingLastAutocorrectionContext;
    BOOL _waitingForKeyboardAppearanceAnimationToStart;
    BOOL _isHidingKeyboard;
    BOOL _isPreparingEditMenu;
    BOOL _focusRequiresStrongPasswordAssistance;
    BOOL _waitingForEditDragSnapshot;
    NSInteger _dropAnimationCount;
    BOOL _hasSetUpInteractions;
    NSUInteger _ignoreSelectionCommandFadeCount;
    NSUInteger _activeTextInteractionCount;
    NSInteger _suppressNonEditableSingleTapTextInteractionCount;
    CompletionHandler<void (WebCore::DOMPasteAccessResponse)> _domPasteRequestHandler;
    optional<WebCore::DOMPasteAccessCategory> _domPasteRequestCategory;
    BlockPtr<void (UIWKAutocorrectionContext *)> _pendingAutocorrectionContextHandler;
    CompletionHandler<void ()> _pendingRunModalJavaScriptDialogCallback;
    RetainPtr<NSDictionary> _additionalContextForStrongPasswordAssistance;
    optional<int> _lastInsertedCharacterToOverrideCharacterBeforeSelection;
    unsigned int _selectionChangeNestingLevel;
    DragDropInteractionState _dragDropInteractionState;
    RetainPtr<UIDragInteraction> _dragInteraction;
    RetainPtr<UIDropInteraction> _dropInteraction;
    BOOL _isAnimatingDragCancel;
    BOOL _shouldRestoreCalloutBarAfterDrop;
    RetainPtr<UIView> _visibleContentViewSnapshot;
    RetainPtr<UIView> _unselectedContentSnapshot;
    RetainPtr<_UITextDragCaretView> _editDropCaretView;
    BlockPtr<void ()> _actionToPerformAfterReceivingEditDragSnapshot;
    RetainPtr<WKImageAnalysisGestureRecognizer> _imageAnalysisGestureRecognizer;
    RetainPtr<UILongPressGestureRecognizer> _imageAnalysisTimeoutGestureRecognizer;
    optional<WTF::ObjectIdentifier<WebKit::ImageAnalysisRequestIdentifierType>> _pendingImageAnalysisRequestIdentifier;
    optional<WebCore::ElementContext> _elementPendingImageAnalysis;
    Vector<WTF::BlockPtr<void (WebKit::ProceedWithTextSelectionInImage)>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _actionsToPerformAfterPendingImageAnalysis;
    BOOL _contextMenuWasTriggeredByImageAnalysisTimeout;
    BOOL _isProceedingWithTextSelectionInImage;
    RetainPtr<VKCImageAnalyzer> _imageAnalyzer;
    RetainPtr<QLPreviewController> _visualSearchPreviewController;
    RetainPtr<UIImage> _visualSearchPreviewImage;
    RetainPtr<NSURL> _visualSearchPreviewImageURL;
    RetainPtr<NSString> _visualSearchPreviewTitle;
    CGRect _visualSearchPreviewImageBounds;
    BOOL _waitingForDynamicImageAnalysisContextMenuActions;
    optional<WebKit::ImageAnalysisContextMenuActionData> _imageAnalysisContextMenuActionData;
    unsigned int _fullscreenVideoImageAnalysisRequestIdentifier;
    RetainPtr<VKCImageAnalysisInteraction> _imageAnalysisInteraction;
    RetainPtr<NSMutableSet<UIButton *>> _imageAnalysisActionButtons;
    FloatRect _imageAnalysisInteractionBounds;
    optional<WebKit::RemoveBackgroundData> _removeBackgroundData;
    unique_ptr<WebKit::PageClientImpl, std::default_delete<WebKit::PageClientImpl>> _pageClient;
    RetainPtr<WKBrowsingContextController> _browsingContextController;
    RetainPtr<UIView> _rootContentView;
    RetainPtr<UIView> _fixedClippingView;
    RetainPtr<WKInspectorIndicationView> _inspectorIndicationView;
    RetainPtr<WKInspectorHighlightView> _inspectorHighlightView;
    RetainPtr<_UILayerHostView> _visibilityPropagationViewForWebProcess;
    RetainPtr<_UILayerHostView> _visibilityPropagationViewForGPUProcess;
    HistoricalVelocityData _historicalKinematicData;
    RetainPtr<NSUndoManager> _undoManager;
    RetainPtr<WKQuirkyNSUndoManager> _quirkyUndoManager;
    Lock _pendingBackgroundPrintFormattersLock;
    RetainPtr<NSMutableSet> _pendingBackgroundPrintFormatters;
    ObjectIdentifier<IPC::Connection::AsyncReplyIDType> _pdfPrintCallbackID;
    Vector<WTF::RetainPtr<NSURL>, 0UL, WTF::CrashOnOverflow, 16UL, WTF::FastMalloc> _temporaryURLsToDeleteWhenDeallocated;
}


@property (copy, nonatomic) NSIndexSet *PINEntrySeparatorIndexes;
@property (readonly, nonatomic) RTIInputSystemSourceSession *_rtiSourceSession;
@property (readonly, nonatomic) BOOL _shouldAvoidResizingWhenInputViewBoundsChange;
@property (readonly, nonatomic) BOOL _shouldAvoidScrollingWhenFocusedContentIsVisible;
@property (readonly, nonatomic) BOOL _shouldAvoidSecurityHeuristicScoreUpdates;
@property (readonly, nonatomic) BOOL _shouldUseContextMenus;
@property (readonly, nonatomic) BOOL _shouldUseContextMenusForFormControls;
@property (readonly, nonatomic) BOOL _shouldUseLegacySelectPopoverDismissalBehavior;
@property (nonatomic) NSInteger _textInputSource;
@property (readonly, nonatomic) BOOL _wk_printFormatterRequiresMainThread;
@property (nonatomic) BOOL acceptsDictationSearchResults;
@property (nonatomic) BOOL acceptsEmoji;
@property (nonatomic) BOOL acceptsFloatingKeyboard;
@property (nonatomic) BOOL acceptsInitialEmojiKeyboard;
@property (nonatomic) BOOL acceptsPayloads;
@property (nonatomic) BOOL acceptsSplitKeyboard;
@property (readonly, nonatomic, getter=isAnimatingDragCancel) BOOL animatingDragCancel;
@property (nonatomic) NSInteger autocapitalizationType;
@property (copy, nonatomic) NSString *autocorrectionContext;
@property (readonly, nonatomic) *void autocorrectionData;
@property (nonatomic) NSInteger autocorrectionType;
@property (readonly, nonatomic) UITextPosition *beginningOfDocument;
@property (readonly, nonatomic) WKBrowsingContextController *browsingContextController;
@property (nonatomic) BOOL contentsIsSingleValue;
@property (readonly, nonatomic) UIContextMenuInteraction *contextMenuInteraction;
@property (readonly, nonatomic) NSInteger cursorBehavior;
@property (retain, nonatomic) NSArray *dataListTextSuggestions;
@property (retain, nonatomic) UIView<WKFormControl> *dataListTextSuggestionsInputView;
@property (readonly, nonatomic) WKDateTimeInputControl *dateTimeInputControl;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL deferBecomingResponder;
@property (readonly, nonatomic) NSArray *deferringGestures;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *description;
@property (nonatomic, getter=isDevicePasscodeEntry) BOOL devicePasscodeEntry;
@property (nonatomic) BOOL disableHandwritingKeyboard;
@property (nonatomic) BOOL disableInputBars;
@property (nonatomic) BOOL disablePrediction;
@property (nonatomic) BOOL displaySecureEditsUsingPlainText;
@property (nonatomic) BOOL displaySecureTextUsingPlainText;
@property (nonatomic) int emptyContentReturnKeyType;
@property (nonatomic) BOOL enablesReturnKeyAutomatically;
@property (nonatomic) BOOL enablesReturnKeyOnNonWhiteSpaceContent;
@property (readonly, nonatomic) UITextPosition *endOfDocument;
@property (nonatomic) UIEdgeInsets floatingKeyboardEdgeInsets;
@property (readonly, nonatomic) *void focusedElementInformation;
@property (nonatomic) BOOL forceDefaultDictationInfo;
@property (nonatomic) NSInteger forceDictationKeyboardType;
@property (nonatomic) BOOL forceDisableDictation;
@property (nonatomic) BOOL forceEnableDictation;
@property (nonatomic) BOOL forceFloatingKeyboard;
@property (nonatomic) BOOL forceSpellingDictation;
@property (readonly, nonatomic) UIWebFormAccessory *formAccessoryView;
@property (readonly, nonatomic) NSString *formInputLabel;
@property (readonly, nonatomic) *void gestureRecognizerConsistencyEnforcer;
@property (nonatomic) BOOL hasDefaultContents;
@property (readonly, nonatomic) BOOL hasText;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (readonly) NSUInteger hash;
@property (nonatomic) BOOL hidePrediction;
@property (readonly, nonatomic) UIGestureRecognizer *imageAnalysisGestureRecognizer;
@property (readonly, nonatomic, getter=isImageBacked) BOOL imageBacked;
@property (readonly, nonatomic) UIView *inputAccessoryViewForWebView;
@property (readonly, nonatomic) UITextInputAssistantItem *inputAssistantItemForWebView;
@property (retain, nonatomic) UIInputContextHistory *inputContextHistory;
@property (weak, nonatomic) NSObject<UITextInputDelegate> *inputDelegate;
@property (readonly, nonatomic) UIView *inputViewForWebView;
@property (readonly, nonatomic) id *insertDictationResultPlaceholder;
@property (retain, nonatomic) UIColor *insertionPointColor;
@property (nonatomic) NSUInteger insertionPointWidth;
@property (readonly, nonatomic) UITextInteractionAssistant *interactionAssistant;
@property (readonly, nonatomic) NSInteger interfaceOrientation;
@property (nonatomic) BOOL isCarPlayIdiom;
@property (readonly, nonatomic) BOOL isEditable;
@property (readonly, nonatomic) BOOL isFocusingElement;
@property (readonly, nonatomic) BOOL isShowingDataListSuggestions;
@property (nonatomic) BOOL isSingleLineDocument;
@property (readonly, nonatomic) BOOL isTextRecognitionInFullscreenVideoEnabled;
@property (nonatomic) NSInteger keyboardAppearance;
@property (nonatomic) NSInteger keyboardType;
@property (readonly, nonatomic) CGPoint lastInteractionLocation;
@property (nonatomic) BOOL learnsCorrections;
@property (nonatomic) BOOL loadKeyboardsForSiriLanguage;
@property (readonly, nonatomic) UITextRange *markedTextRange;
@property (copy, nonatomic) NSDictionary *markedTextStyle;
@property (readonly, nonatomic) *void page;
@property (copy, nonatomic) UITextInputPasswordRules *passwordRules;
@property (readonly, nonatomic) *void positionInformation;
@property (nonatomic) BOOL preferOnlineDictation;
@property (nonatomic) NSInteger preferredKeyboardStyle;
@property (readonly, nonatomic) BOOL preventsPanningInXAxis;
@property (readonly, nonatomic) BOOL preventsPanningInYAxis;
@property (copy, nonatomic) NSString *recentInputIdentifier;
@property (readonly, nonatomic, getter=isResigningFirstResponder) BOOL resigningFirstResponder; // ivar: _resigningFirstResponder
@property (copy, nonatomic) NSString *responseContext;
@property (nonatomic) BOOL returnKeyGoesToNextResponder;
@property (nonatomic) NSInteger returnKeyType;
@property (nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property (readonly, nonatomic) WKFormSelectControl *selectControl;
@property (readonly, nonatomic) NSString *selectFormPopoverTitle;
@property (copy) UITextRange *selectedTextRange;
@property (readonly) NSObject<NSObject><NSCopying> *selectedTextSearchDocument;
@property (nonatomic) NSInteger selectionAffinity;
@property (retain, nonatomic) UIColor *selectionBarColor;
@property (retain, nonatomic) UIColor *selectionBorderColor;
@property (nonatomic) CGFloat selectionBorderWidth;
@property (nonatomic) CGFloat selectionCornerRadius;
@property (retain, nonatomic) UIImage *selectionDragDotImage;
@property (nonatomic) UIEdgeInsets selectionEdgeInsets;
@property (nonatomic) NSInteger selectionGranularity;
@property (retain, nonatomic) UIColor *selectionHighlightColor;
@property (nonatomic) int shortcutConversionType;
@property (readonly, nonatomic) BOOL shouldHideSelectionWhenScrolling;
@property (readonly, nonatomic) BOOL shouldIgnoreKeyboardWillHideNotification;
@property (nonatomic) BOOL showDictationButton;
@property (nonatomic, getter=isShowingInspectorIndication) BOOL showingInspectorIndication;
@property (nonatomic) BOOL sizeChangedSinceLastVisibleContentRectUpdate; // ivar: _sizeChangedSinceLastVisibleContentRectUpdate
@property (nonatomic) NSInteger smartDashesType;
@property (nonatomic) NSInteger smartInsertDeleteType;
@property (nonatomic) NSInteger smartQuotesType;
@property (nonatomic) NSInteger spellCheckingType;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (readonly) Class superclass;
@property (retain, nonatomic) _UISupplementalLexicon *supplementalLexicon;
@property (retain, nonatomic) UIImage *supplementalLexiconAmbiguousItemIcon;
@property (readonly, nonatomic) BOOL supportsImagePaste;
@property (readonly, nonatomic) BOOL supportsTextReplacement;
@property (readonly, nonatomic) BOOL supportsTextReplacementForWebView;
@property (nonatomic) BOOL suppressReturnKeyStyling;
@property (readonly, nonatomic) CGRect tapHighlightViewRect;
@property (copy, nonatomic) NSString *textContentType;
@property (readonly, nonatomic) NSString *textContentTypeForTesting;
@property (readonly, nonatomic) NSObject<UITextInputSuggestionDelegate> *textInputSuggestionDelegate;
@property (readonly, nonatomic) UITextInputTraits *textInputTraitsForWebView;
@property (readonly, nonatomic) UIView *textInputView;
@property (readonly, nonatomic) UIWKTextInteractionAssistant *textInteractionAssistant;
@property (nonatomic) int textLoupeVisibility;
@property (readonly, nonatomic) UITextRange *textRangeForServicesInteraction;
@property (nonatomic) NSInteger textScriptType;
@property (nonatomic) int textSelectionBehavior;
@property (nonatomic) id *textSuggestionDelegate;
@property (nonatomic) *__CFCharacterSet textTrimmingSet;
@property (readonly, nonatomic) NSObject<UITextInputTokenizer> *tokenizer;
@property (readonly, nonatomic) UIWebTouchEventsGestureRecognizer *touchEventGestureRecognizer;
@property (retain, nonatomic) UIColor *underlineColorForSpelling;
@property (retain, nonatomic) UIColor *underlineColorForTextAlternatives;
@property (readonly, nonatomic) NSUndoManager *undoManagerForWebView;
@property (nonatomic) BOOL useAutomaticEndpointing;
@property (nonatomic) BOOL useInterfaceLanguageForLocalization;
@property (nonatomic) _NSRange validTextRange;


-(*void)focusedSelectElementOptions;
-(BOOL)_allowAnimatedUpdateSelectionRectViews;
-(BOOL)_currentPositionInformationIsApproximatelyValidForRequest:(struct InteractionInformationRequest *)arg0 radiusForApproximation:(int)arg1 ;
-(BOOL)_currentPositionInformationIsValidForRequest:(struct InteractionInformationRequest *)arg0 ;
-(BOOL)_disableAutomaticKeyboardUI;
-(BOOL)_dragInteraction:(id)arg0 item:(id)arg1 shouldDelaySetDownAnimationWithCompletion:(id)arg2 ;
-(BOOL)_dragInteraction:(id)arg0 shouldDelayCompetingGestureRecognizer:(id)arg1 ;
-(BOOL)_elementForTextInputContextIsFocused:(id)arg0 ;
-(BOOL)_elementTypeRequiresAccessoryView:(int)arg0 ;
-(BOOL)_formControlRefreshEnabled;
-(BOOL)_gestureRecognizerCanBePreventedByTouchEvents:(id)arg0 ;
-(BOOL)_handleDOMPasteRequestWithResult:(unsigned char)arg0 ;
-(BOOL)_handleDropByInsertingImagePlaceholders:(id)arg0 session:(id)arg1 ;
-(BOOL)_handleTapOverImageAnalysisInteractionButton:(struct CGPoint )arg0 ;
-(BOOL)_hasFocusedElement;
-(BOOL)_hasValidOutstandingPositionInformationRequest:(struct InteractionInformationRequest *)arg0 ;
-(BOOL)_interactionShouldBeginFromPreviewItemController:(id)arg0 forPosition:(struct CGPoint )arg1 ;
-(BOOL)_interpretKeyEvent:(id)arg0 isCharEvent:(BOOL)arg1 ;
-(BOOL)_isTextInputContextFocused:(id)arg0 ;
-(BOOL)_isTouchEndDeferringGesture:(id)arg0 ;
-(BOOL)_isTouchStartDeferringGesture:(id)arg0 ;
-(BOOL)_mayDisableDoubleTapGesturesDuringSingleTap;
-(BOOL)_pointIsInsideSelectionRect:(struct CGPoint )arg0 outBoundingRect:(struct FloatRect *)arg1 ;
-(BOOL)_requiresKeyboardResetOnReload;
-(BOOL)_requiresKeyboardWhenFirstResponder;
-(BOOL)_restoreFocusWithToken:(id)arg0 ;
-(BOOL)_scrollToRect:(struct CGRect )arg0 withOrigin:(struct CGPoint )arg1 minimumScrollDistance:(CGFloat)arg2 ;
-(BOOL)_selectionAtDocumentStart;
-(BOOL)_shouldAdditionallyRecognizeGestureRecognizer:(id)arg0 simultaneouslyWithGestureRecognizer:(id)arg1 ;
-(BOOL)_shouldShowAutomaticKeyboardUIIgnoringInputMode;
-(BOOL)_shouldShowKeyboardForElement:(*void)arg0 ;
-(BOOL)_shouldShowKeyboardForElementIgnoringInputMode:(*void)arg0 ;
-(BOOL)_shouldSimulateKeyboardInputOnTextInsertion;
-(BOOL)_shouldSuppressSelectionCommands;
-(BOOL)_shouldToggleSelectionCommandsAfterTapAt:(struct CGPoint )arg0 ;
-(BOOL)_touchEventsMustRequireGestureRecognizerToFail:(id)arg0 ;
-(BOOL)_zoomToRect:(struct CGRect )arg0 withOrigin:(struct CGPoint )arg1 fitEntireRect:(BOOL)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 minimumScrollDistance:(CGFloat)arg5 ;
-(BOOL)actionSheetAssistant:(id)arg0 shouldIncludeAppLinkActionsForElement:(id)arg1 ;
-(BOOL)actionSheetAssistant:(id)arg0 shouldIncludeLookUpImageActionForElement:(id)arg1 ;
-(BOOL)actionSheetAssistant:(id)arg0 shouldIncludeShowTextActionForElement:(id)arg1 ;
-(BOOL)actionSheetAssistant:(id)arg0 showCustomSheetForElement:(id)arg1 ;
-(BOOL)actionSheetAssistantShouldIncludeCopySubjectAction:(id)arg0 ;
-(BOOL)becomeFirstResponder;
-(BOOL)becomeFirstResponderForWebView;
-(BOOL)canBecomeFirstResponder;
-(BOOL)canBecomeFirstResponderForWebView;
-(BOOL)canBecomeFocused;
-(BOOL)canPerformAction:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)canPerformActionForWebView:(SEL)arg0 withSender:(id)arg1 ;
-(BOOL)canShowNonEmptySelectionView;
-(BOOL)deferringGestureRecognizer:(id)arg0 shouldDeferOtherGestureRecognizer:(id)arg1 ;
-(BOOL)deferringGestureRecognizer:(id)arg0 willBeginTouchesWithEvent:(id)arg1 ;
-(BOOL)dropInteraction:(id)arg0 canHandleSession:(id)arg1 ;
-(BOOL)ensurePositionInformationIsUpToDate:(struct InteractionInformationRequest )arg0 ;
-(BOOL)fileUploadPanelDestinationIsManaged:(id)arg0 ;
-(BOOL)gestureRecognizer:(id)arg0 canBePreventedByGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 canPreventGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 isInterruptingMomentumScrollingWithEvent:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldBeRequiredToFailByGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldIgnoreWebTouchWithEvent:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldReceivePress:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldReceiveTouch:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg0 shouldRequireFailureOfGestureRecognizer:(id)arg1 ;
-(BOOL)gestureRecognizerMayDoubleTapToZoomWebView:(id)arg0 ;
-(BOOL)gestureRecognizerMayPanWebView:(id)arg0 ;
-(BOOL)gestureRecognizerMayPinchToZoomWebView:(id)arg0 ;
-(BOOL)gestureRecognizerShouldBegin:(id)arg0 ;
-(BOOL)hasContent;
-(BOOL)hasHiddenContentEditable;
-(BOOL)hasMarkedText;
-(BOOL)hasPendingImageAnalysisRequest;
-(BOOL)hasSelectablePositionAtPoint:(struct CGPoint )arg0 ;
-(BOOL)hasSelectableTextForImageContextMenu;
-(BOOL)hasSelection;
-(BOOL)hasVisualSearchResultsForImageContextMenu;
-(BOOL)imageAnalysisInteraction:(id)arg0 shouldBeginAtPoint:(struct CGPoint )arg1 forAnalysisType:(NSUInteger)arg2 ;
-(BOOL)indirectScribbleInteraction:(id)arg0 isElementFocused:(id)arg1 ;
-(BOOL)isAnyTouchOverActiveArea:(id)arg0 ;
-(BOOL)isPosition:(id)arg0 atBoundary:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(BOOL)isPosition:(id)arg0 withinTextUnit:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(BOOL)isReplaceAllowed;
-(BOOL)isScrollableForKeyboardScrollViewAnimator:(id)arg0 ;
-(BOOL)pointIsNearMarkedText:(struct CGPoint )arg0 ;
-(BOOL)requiresAccessoryView;
-(BOOL)requiresKeyEvents;
-(BOOL)resignFirstResponder;
-(BOOL)resignFirstResponderForWebView;
-(BOOL)selectFormAccessoryHasCheckedItemAtRow:(NSInteger)arg0 ;
-(BOOL)shouldAllowAppHighlightCreation;
-(BOOL)shouldAllowHidingSelectionCommands;
-(BOOL)shouldDeferGestureDueToImageAnalysis:(id)arg0 ;
-(BOOL)shouldShowAutomaticKeyboardUI;
-(BOOL)shouldSuppressUpdateCandidateView;
-(BOOL)shouldSynthesizeKeyEvents;
-(BOOL)shouldUseMouseGestureRecognizer;
-(BOOL)supportsTextSelectionWithCharacterGranularity;
-(BOOL)textInteractionGesture:(NSInteger)arg0 shouldBeginAtPoint:(struct CGPoint )arg1 ;
-(BOOL)validateImageAnalysisRequestIdentifier:(struct ObjectIdentifier<WebKit::ImageAnalysisRequestIdentifierType> )arg0 ;
-(CGFloat)_contentZoomScale;
-(CGFloat)_initialScaleFactor;
-(CGFloat)_targetContentZoomScaleForRect:(struct FloatRect *)arg0 currentScale:(CGFloat)arg1 fitEntireRect:(BOOL)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 ;
-(CGFloat)dragLiftDelay;
-(CGFloat)inverseScale;
-(CGFloat)keyboardScrollViewAnimator:(id)arg0 distanceForIncrement:(unsigned char)arg1 inDirection:(unsigned char)arg2 ;
-(CGFloat)timePickerValueHour;
-(CGFloat)timePickerValueMinute;
-(NSInteger)_dragInteraction:(id)arg0 dataOwnerForSession:(id)arg1 ;
-(NSInteger)_dropInteraction:(id)arg0 dataOwnerForSession:(id)arg1 ;
-(NSInteger)baseWritingDirectionForPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(NSInteger)compareFoundRange:(id)arg0 toRange:(id)arg1 inDocument:(id)arg2 ;
-(NSInteger)comparePosition:(id)arg0 toPosition:(id)arg1 ;
-(NSInteger)numberOfPreviewItemsInPreviewController:(id)arg0 ;
-(NSInteger)offsetFromPosition:(id)arg0 toPosition:(id)arg1 ;
-(NSInteger)offsetFromPosition:(id)arg0 toPosition:(id)arg1 inDocument:(id)arg2 ;
-(NSUInteger)_dragDestinationActionForDropSession:(id)arg0 ;
-(NSUInteger)_wk_pageCountForPrintFormatter:(id)arg0 ;
-(SEL)_actionForLongPress;
-(SEL)_actionForLongPressFromPositionInformation:(*void)arg0 ;
-(id)_autofillContext;
-(id)_cascadeInteractionTintColor;
-(id)_commonInitializationWithProcessPool:(*void)arg0 configuration:(*void)arg1 ;
-(id)_contentsOfUserInterfaceItem:(id)arg0 ;
-(id)_contextMenuInteraction:(id)arg0 overrideSuggestedActionsForConfiguration:(id)arg1 ;
-(id)_contextMenuInteraction:(id)arg0 styleForMenuWithConfiguration:(id)arg1 ;
-(id)_createTargetedContextMenuHintPreviewForFocusedElement;
-(id)_createTargetedContextMenuHintPreviewIfPossible;
-(id)_dataDetectionResults;
-(id)_dataForPreviewItemController:(id)arg0 atPosition:(struct CGPoint )arg1 type:(*NSInteger)arg2 ;
-(id)_formInputSession;
-(id)_itemsForBeginningOrAddingToSessionWithRegistrationLists:(id)arg0 stagedDragSource:(*void)arg1 ;
-(id)_moveDown:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveLeft:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveRight:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfDocument:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfLine:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfParagraph:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToEndOfWord:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfDocument:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfLine:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfParagraph:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveToStartOfWord:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_moveUp:(BOOL)arg0 withHistory:(id)arg1 ;
-(id)_presentationRectsForPreviewItemController:(id)arg0 ;
-(id)_presentationSnapshotForPreviewItemController:(id)arg0 ;
-(id)_presentedViewControllerForPreviewItemController:(id)arg0 ;
-(id)_scroller;
-(id)_textInputContextByScribbleIdentifier:(id)arg0 ;
-(id)_touchEndDeferringGestures;
-(id)_touchStartDeferringGestures;
-(id)_uiTextSelectionRects;
-(id)alternativesForSelectedText;
-(id)appHighlightMenu;
-(id)automaticallySelectedOverlay;
-(id)characterRangeAtPoint:(struct CGPoint )arg0 ;
-(id)characterRangeByExtendingPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(id)closestPositionToPoint:(struct CGPoint )arg0 ;
-(id)closestPositionToPoint:(struct CGPoint )arg0 withinRange:(id)arg1 ;
-(id)containerForContextMenuHintPreviews;
-(id)containerForDragPreviews;
-(id)containerForDropPreviews;
-(id)contextMenuInteraction:(id)arg0 configuration:(id)arg1 dismissalPreviewForItemWithIdentifier:(id)arg2 ;
-(id)contextMenuInteraction:(id)arg0 configuration:(id)arg1 highlightPreviewForItemWithIdentifier:(id)arg2 ;
-(id)contextMenuInteraction:(id)arg0 configurationForMenuAtLocation:(struct CGPoint )arg1 ;
-(id)createTargetedContextMenuHintForActionSheetAssistant:(id)arg0 ;
-(id)currentDragOrDropSession;
-(id)dataDetectionContextForActionSheetAssistant:(id)arg0 positionInformation:(*void)arg1 ;
-(id)dataDetectionContextForPositionInformation:(*void)arg0 ;
-(id)dragInteraction:(id)arg0 itemsForBeginningSession:(id)arg1 ;
-(id)dragInteraction:(id)arg0 previewForCancellingItem:(id)arg1 withDefault:(id)arg2 ;
-(id)dragInteraction:(id)arg0 previewForLiftingItem:(id)arg1 session:(id)arg2 ;
-(id)dropInteraction:(id)arg0 previewForDroppingItem:(id)arg1 withDefault:(id)arg2 ;
-(id)dropInteraction:(id)arg0 sessionDidUpdate:(id)arg1 ;
-(id)filePickerAcceptedTypeIdentifiers;
-(id)fontForCaretSelection;
-(id)hitTest:(struct CGPoint )arg0 withEvent:(id)arg1 ;
-(id)imageAnalyzer;
-(id)initWithFrame:(struct CGRect )arg0 processPool:(struct NakedRef<WebKit::WebProcessPool> )arg1 configuration:(*void)arg2 webView:(id)arg3 ;
-(id)inputAccessoryView;
-(id)inputAssistantItem;
-(id)inputLabelText;
-(id)inputView;
-(id)machineReadableCodeSubMenuForImageContextMenu;
-(id)markedText;
-(id)menuWithInlineAction:(id)arg0 image:(id)arg1 identifier:(id)arg2 handler:(*void)arg3 ;
-(id)metadataDictionariesForDictationResults;
-(id)placeholderForDynamicallyInsertedImageAnalysisActions;
-(id)pointerInteraction:(id)arg0 styleForRegion:(id)arg1 ;
-(id)pointerRegionForPositionInformation:(*void)arg0 point:(struct CGPoint )arg1 ;
-(id)positionFromPosition:(id)arg0 inDirection:(NSInteger)arg1 offset:(NSInteger)arg2 ;
-(id)positionFromPosition:(id)arg0 offset:(NSInteger)arg1 ;
-(id)positionFromPosition:(id)arg0 toBoundary:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(id)positionWithinRange:(id)arg0 farthestInDirection:(NSInteger)arg1 ;
-(id)previewController:(id)arg0 previewItemAtIndex:(NSInteger)arg1 ;
-(id)previewController:(id)arg0 transitionImageForPreviewItem:(id)arg1 contentRect:(struct CGRect *)arg2 ;
-(id)provideDataForItem:(id)arg0 ;
-(id)rangeEnclosingPosition:(id)arg0 withGranularity:(NSInteger)arg1 inDirection:(NSInteger)arg2 ;
-(id)removeBackgroundMenu;
-(id)rootContentView;
-(id)selectedDOMRange;
-(id)selectedText;
-(id)selectedTextForActionSheetAssistant:(id)arg0 ;
-(id)selectionRectsForRange:(id)arg0 ;
-(id)supportedPasteboardTypesForCurrentSelection;
-(id)targetForAction:(SEL)arg0 withSender:(id)arg1 ;
-(id)targetForActionForWebView:(SEL)arg0 withSender:(id)arg1 ;
-(id)textColorForCaretSelection;
-(id)textEffectsWindow;
-(id)textInRange:(id)arg0 ;
-(id)textInputTraits;
-(id)textRangeFromPosition:(id)arg0 toPosition:(id)arg1 ;
-(id)textStylingAtPosition:(id)arg0 inDirection:(NSInteger)arg1 ;
-(id)touchActionActiveTouches;
-(id)unscaledView;
-(id)webSelectionRects;
-(id)webSelectionRectsForSelectionGeometries:(*void)arg0 ;
-(id)webView;
-(id)webViewUIDelegate;
-(id)wordContainingCaretSelection;
-(id)wordRangeContainingCaretSelection;
-(struct CGImage *)copySubjectResultForImageContextMenu;
-(struct CGRect )_computeUnobscuredContentRectRespectingInputViewBounds:(struct CGRect )arg0 inputViewBounds:(struct CGRect )arg1 ;
-(struct CGRect )_presentationRectForPreviewItemController:(id)arg0 ;
-(struct CGRect )_selectionClipRect;
-(struct CGRect )caretRectForPosition:(id)arg0 ;
-(struct CGRect )contentsRectForImageAnalysisInteraction:(id)arg0 ;
-(struct CGRect )firstRectForRange:(id)arg0 ;
-(struct CGRect )indirectScribbleInteraction:(id)arg0 frameForElement:(id)arg1 ;
-(struct CGRect )previewController:(id)arg0 frameForPreviewItem:(id)arg1 inSourceView:(*id)arg2 ;
-(struct CGRect )rectContainingCaretSelection;
-(struct CGRect )rectForNSRange:(struct _NSRange )arg0 ;
-(struct CGRect )textFirstRect;
-(struct CGRect )textLastRect;
-(struct CGRect )unobscuredContentRect;
-(struct CGRect )unoccludedWindowBoundsForActionSheetAssistant:(id)arg0 ;
-(struct Color )_tapHighlightColorForFastClick:(BOOL)arg0 ;
-(struct DragData )dragDataForDropSession:(id)arg0 dragDestinationAction:(NSUInteger)arg1 ;
-(struct FloatRect )_scaledCaretRectForSelectionEnd:(struct FloatRect )arg0 ;
-(struct FloatRect )_scaledCaretRectForSelectionStart:(struct FloatRect )arg0 ;
-(struct FloatRect )rectToRevealWhenZoomingToFocusedElement;
-(struct ObjectIdentifier<WebKit::TapIdentifierType> )nextTapIdentifier;
-(struct OptionSet<WebCore::DragSourceAction> )_allowedDragSourceActions;
-(struct RetainPtr<NSArray> )actionSheetAssistant:(id)arg0 decideActionsForElement:(id)arg1 defaultActions:(struct RetainPtr<NSArray> )arg2 ;
-(struct RetainPtr<VKCImageAnalyzerRequest> )createImageAnalyzerRequest:(NSUInteger)arg0 image:(struct CGImage *)arg1 ;
-(struct RetainPtr<VKCImageAnalyzerRequest> )createImageAnalyzerRequest:(NSUInteger)arg0 image:(struct CGImage *)arg1 imageURL:(id)arg2 ;
-(struct RetainPtr<WKTargetedPreviewContainer> )_createPreviewContainerWithLayerName:(id)arg0 ;
-(struct _NSRange )_markedTextNSRange;
-(struct _NSRange )selectionRange;
-(struct optional<WebCore::ProcessQualified<WTF::ObjectIdentifier<WebCore::FrameIdentifierType>>> )_frameIdentifierForPrintFormatter:(id)arg0 ;
-(struct optional<WebKit::InteractionInformationAtPosition> )positionInformationForActionSheetAssistant:(id)arg0 ;
-(struct optional<unsigned int> )activeTouchIdentifierForGestureRecognizer:(id)arg0 ;
-(struct unique_ptr<WebKit::DrawingAreaProxy, std::default_delete<WebKit::DrawingAreaProxy>> )_createDrawingAreaProxy:(*void)arg0 ;
-(unsigned char)_dataOwnerForPasteboard:(BOOL)arg0 ;
-(unsigned int)_characterInRelationToCaretSelection:(int)arg0 ;
-(unsigned short)characterBeforeCaretSelection;
-(void)_accessibilityClearSelection;
-(void)_accessibilityRegisterUIProcessTokens;
-(void)_accessibilityRetrieveRectsAtSelectionOffset:(NSInteger)arg0 withText:(id)arg1 ;
-(void)_accessibilityRetrieveRectsAtSelectionOffset:(NSInteger)arg0 withText:(id)arg1 completionHandler:(id)arg2 ;
-(void)_accessibilityRetrieveRectsEnclosingSelectionOffset:(NSInteger)arg0 withGranularity:(NSInteger)arg1 ;
-(void)_accessibilityStoreSelection;
-(void)_addDefaultGestureRecognizers;
-(void)_addShortcut:(id)arg0 ;
-(void)_addShortcutForWebView:(id)arg0 ;
-(void)_alignCenter:(id)arg0 ;
-(void)_alignCenterForWebView:(id)arg0 ;
-(void)_alignJustified:(id)arg0 ;
-(void)_alignJustifiedForWebView:(id)arg0 ;
-(void)_alignLeft:(id)arg0 ;
-(void)_alignLeftForWebView:(id)arg0 ;
-(void)_alignRight:(id)arg0 ;
-(void)_alignRightForWebView:(id)arg0 ;
-(void)_applicationDidBecomeActive:(id)arg0 ;
-(void)_applicationDidEnterBackground:(id)arg0 ;
-(void)_applicationWillEnterForeground:(id)arg0 ;
-(void)_applicationWillResignActive:(id)arg0 ;
-(void)_attemptSyntheticClickAtLocation:(struct CGPoint )arg0 modifierFlags:(NSInteger)arg1 ;
-(void)_becomeFirstResponderWithSelectionMovingForward:(BOOL)arg0 completionHandler:(id)arg1 ;
-(void)_cancelImageAnalysis;
-(void)_cancelInteraction;
-(void)_cancelLongPressGestureRecognizer;
-(void)_cancelPendingAutocorrectionContextHandler;
-(void)_cancelPendingKeyEventHandler;
-(void)_cancelPreviousResetInputViewDeferralRequest;
-(void)_cancelTouchEventGestureRecognizer;
-(void)_changeListType:(id)arg0 ;
-(void)_changeListTypeForWebView:(id)arg0 ;
-(void)_commitPotentialTapFailed;
-(void)_completeImageAnalysisRequestForContextMenu:(struct CGImage *)arg0 requestIdentifier:(struct ObjectIdentifier<WebKit::ImageAnalysisRequestIdentifierType> )arg1 hasTextResults:(BOOL)arg2 ;
-(void)_configureMouseGestureRecognizer;
-(void)_contextMenuInteraction:(id)arg0 configurationForMenuAtLocation:(struct CGPoint )arg1 completion:(id)arg2 ;
-(void)_createAndConfigureDoubleTapGestureRecognizer;
-(void)_createAndConfigureHighlightLongPressGestureRecognizer;
-(void)_createAndConfigureLongPressGestureRecognizer;
-(void)_decreaseListLevel:(id)arg0 ;
-(void)_decreaseListLevelForWebView:(id)arg0 ;
-(void)_define:(id)arg0 ;
-(void)_defineForWebView:(id)arg0 ;
-(void)_deleteByWord;
-(void)_deleteForwardAndNotify:(BOOL)arg0 ;
-(void)_deleteForwardByWord;
-(void)_deleteToEndOfLine;
-(void)_deleteToEndOfParagraph;
-(void)_deleteToStartOfLine;
-(void)_deliverDelayedDropPreviewIfPossible:(struct optional<WebCore::TextIndicatorData> )arg0 ;
-(void)_didChangeDragCaretRect:(struct CGRect )arg0 currentRect:(struct CGRect )arg1 ;
-(void)_didChangeDragInteractionPolicy;
-(void)_didChangeLinkPreviewAvailability;
-(void)_didChangeWebViewEditability;
-(void)_didCommitLayerTree:(*void)arg0 ;
-(void)_didCommitLoadForMainFrame;
-(void)_didCompleteSyntheticClick;
-(void)_didEndScrollingOrZooming;
-(void)_didEnterFullscreen;
-(void)_didExitFullscreen;
-(void)_didExitStableState;
-(void)_didFinishTextInteractionInTextInputContext:(id)arg0 ;
-(void)_didGetTapHighlightForRequest:(struct ObjectIdentifier<WebKit::TapIdentifierType> )arg0 color:(struct Color *)arg1 quads:(*void)arg2 topLeftRadius:(struct IntSize *)arg3 topRightRadius:(struct IntSize *)arg4 bottomLeftRadius:(struct IntSize *)arg5 bottomRightRadius:(struct IntSize *)arg6 nodeHasBuiltInClickHandling:(BOOL)arg7 ;
-(void)_didHandleAdditionalDragItemsRequest:(BOOL)arg0 ;
-(void)_didHandleDragStartRequest:(BOOL)arg0 ;
-(void)_didHandleKeyEvent:(id)arg0 eventWasHandled:(BOOL)arg1 ;
-(void)_didHandleTapAsHover;
-(void)_didHideMenu:(id)arg0 ;
-(void)_didNotHandleTapAsClick:(struct IntPoint *)arg0 ;
-(void)_didPerformAction:(SEL)arg0 sender:(id)arg1 ;
-(void)_didPerformDragOperation:(BOOL)arg0 ;
-(void)_didReceiveEditDragSnapshot:(struct optional<WebCore::TextIndicatorData> )arg0 ;
-(void)_didRelaunchProcess;
-(void)_didScroll;
-(void)_didStartProvisionalLoadForMainFrame;
-(void)_didUpdateEditorState;
-(void)_didUpdateInputMode:(unsigned char)arg0 ;
-(void)_disableDoubleTapGesturesDuringTapIfNecessary:(struct ObjectIdentifier<WebKit::TapIdentifierType> )arg0 ;
-(void)_disableInspectorNodeSearch;
-(void)_dismissContactPickerWithContacts:(id)arg0 ;
-(void)_doAfterPendingImageAnalysis:(id)arg0 ;
-(void)_doAfterReceivingEditDragSnapshotForTesting:(id)arg0 ;
-(void)_doneDeferringTouchEnd:(BOOL)arg0 ;
-(void)_doneDeferringTouchMove:(BOOL)arg0 ;
-(void)_doneDeferringTouchStart:(BOOL)arg0 ;
-(void)_doubleTapDidFail:(id)arg0 ;
-(void)_doubleTapRecognized:(id)arg0 ;
-(void)_doubleTapRecognizedForDoubleClick:(id)arg0 ;
-(void)_dragInteraction:(id)arg0 itemsForAddingToSession:(id)arg1 withTouchAtPoint:(struct CGPoint )arg2 completion:(id)arg3 ;
-(void)_dragInteraction:(id)arg0 prepareForSession:(id)arg1 completion:(id)arg2 ;
-(void)_dropInteraction:(id)arg0 delayedPreviewProviderForDroppingItem:(id)arg1 previewProvider:(id)arg2 ;
-(void)_elementDidBlur;
-(void)_elementDidFocus:(*void)arg0 userIsInteracting:(BOOL)arg1 blurPreviousNode:(BOOL)arg2 activityStateChanges:(struct OptionSet<WebCore::ActivityState::Flag> )arg3 userObject:(id)arg4 ;
-(void)_enableInspectorNodeSearch;
-(void)_endEditing;
-(void)_endImageAnalysisGestureDeferral:(BOOL)arg0 ;
-(void)_endPotentialTapAndEnableDoubleTapGesturesIfNecessary;
-(void)_fadeTapHighlightViewIfNeeded;
-(void)_findSelected:(id)arg0 ;
-(void)_findSelectedForWebView:(id)arg0 ;
-(void)_finishInteraction;
-(void)_focusTextInputContext:(id)arg0 placeCaretAt:(struct CGPoint )arg1 completionHandler:(id)arg2 ;
-(void)_gpuProcessDidCreateContextForVisibilityPropagation;
-(void)_gpuProcessDidExit;
-(void)_handleAutocorrectionContext:(*void)arg0 ;
-(void)_handleKeyUIEvent:(id)arg0 ;
-(void)_handleSmartMagnificationInformationForPotentialTap:(struct ObjectIdentifier<WebKit::TapIdentifierType> )arg0 renderRect:(struct FloatRect *)arg1 fitEntireRect:(BOOL)arg2 viewportMinimumScale:(CGFloat)arg3 viewportMaximumScale:(CGFloat)arg4 nodeIsRootLevel:(BOOL)arg5 ;
-(void)_handleTouchActionsForTouchEvent:(*void)arg0 ;
-(void)_hardwareKeyboardAvailabilityChanged;
-(void)_hideInspectorHighlight;
-(void)_hideKeyboard;
-(void)_highlightLongPressRecognized:(id)arg0 ;
-(void)_increaseListLevel:(id)arg0 ;
-(void)_increaseListLevelForWebView:(id)arg0 ;
-(void)_indent:(id)arg0 ;
-(void)_indentForWebView:(id)arg0 ;
-(void)_insertNestedOrderedList:(id)arg0 ;
-(void)_insertNestedOrderedListForWebView:(id)arg0 ;
-(void)_insertNestedUnorderedList:(id)arg0 ;
-(void)_insertNestedUnorderedListForWebView:(id)arg0 ;
-(void)_insertOrderedList:(id)arg0 ;
-(void)_insertOrderedListForWebView:(id)arg0 ;
-(void)_insertUnorderedList:(id)arg0 ;
-(void)_insertUnorderedListForWebView:(id)arg0 ;
-(void)_inspectorNodeSearchRecognized:(id)arg0 ;
-(void)_interactionStartedFromPreviewItemController:(id)arg0 ;
-(void)_interactionStoppedFromPreviewItemController:(id)arg0 ;
-(void)_invalidateCurrentPositionInformation;
-(void)_invokeAllActionsToPerformAfterPendingImageAnalysis:(BOOL)arg0 ;
-(void)_invokeAndRemovePendingHandlersValidForCurrentPositionInformation;
-(void)_invokePendingAutocorrectionContextHandler:(id)arg0 ;
-(void)_keyboardDidRequestDismissal:(id)arg0 ;
-(void)_keyboardDidShow;
-(void)_keyboardWillShow;
-(void)_layerTreeCommitComplete;
-(void)_longPressRecognized:(id)arg0 ;
-(void)_lookup:(id)arg0 ;
-(void)_lookupForWebView:(id)arg0 ;
-(void)_nextAccessoryTab:(id)arg0 ;
-(void)_nextAccessoryTabForWebView:(id)arg0 ;
-(void)_nonBlockingDoubleTapRecognized:(id)arg0 ;
-(void)_outdent:(id)arg0 ;
-(void)_outdentForWebView:(id)arg0 ;
-(void)_pasteAndMatchStyle:(id)arg0 ;
-(void)_pasteAndMatchStyleForWebView:(id)arg0 ;
-(void)_pasteAsQuotation:(id)arg0 ;
-(void)_pasteAsQuotationForWebView:(id)arg0 ;
-(void)_pointerInteraction:(id)arg0 regionForRequest:(id)arg1 defaultRegion:(id)arg2 completion:(id)arg3 ;
-(void)_positionInformationDidChange:(*void)arg0 ;
-(void)_prepareToDragPromisedAttachment:(*void)arg0 ;
-(void)_preserveFocusWithToken:(id)arg0 destructively:(BOOL)arg1 ;
-(void)_previewItemController:(id)arg0 commitPreview:(id)arg1 ;
-(void)_previewItemController:(id)arg0 didDismissPreview:(id)arg1 committing:(BOOL)arg2 ;
-(void)_previewItemControllerDidCancelPreview:(id)arg0 ;
-(void)_previousAccessoryTab:(id)arg0 ;
-(void)_previousAccessoryTabForWebView:(id)arg0 ;
-(void)_processDidExit;
-(void)_processWillSwap;
-(void)_promptForReplace:(id)arg0 ;
-(void)_promptForReplaceForWebView:(id)arg0 ;
-(void)_registerPreview;
-(void)_removeContainerForContextMenuHintPreviews;
-(void)_removeContainerForDragPreviews;
-(void)_removeContainerForDropPreviews;
-(void)_removeContextMenuHintContainerIfPossible;
-(void)_removeDefaultGestureRecognizers;
-(void)_removeTemporaryDirectoriesWhenDeallocated:(*void)arg0 ;
-(void)_removeTemporaryFilesIfNecessary;
-(void)_removeVisibilityPropagationViewForGPUProcess;
-(void)_removeVisibilityPropagationViewForWebProcess;
-(void)_requestDOMPasteAccessForCategory:(unsigned char)arg0 elementRect:(struct IntRect *)arg1 originIdentifier:(*void)arg2 completionHandler:(*void)arg3 ;
-(void)_requestEvasionRectsAboveSelectionIfNeeded:(*void)arg0 ;
-(void)_requestTextInputContextsInRect:(struct CGRect )arg0 completionHandler:(id)arg1 ;
-(void)_resetIsDoubleTapPending;
-(void)_resetPanningPreventionFlags;
-(void)_resetPrintingState;
-(void)_restoreCalloutBarIfNeeded;
-(void)_scheduleResetInputViewDeferralAfterBecomingFirstResponder;
-(void)_screenCapturedDidChange:(id)arg0 ;
-(void)_scrollingNodeScrollingDidEnd:(NSUInteger)arg0 ;
-(void)_scrollingNodeScrollingWillBegin:(NSUInteger)arg0 ;
-(void)_selectDataListOption:(NSInteger)arg0 ;
-(void)_selectPositionAtPoint:(struct CGPoint )arg0 stayingWithinFocusedElement:(BOOL)arg1 completionHandler:(id)arg2 ;
-(void)_selectionChanged;
-(void)_setAcceleratedCompositingRootView:(id)arg0 ;
-(void)_setAccessibilityWebProcessToken:(id)arg0 ;
-(void)_setDataListSuggestionsControl:(id)arg0 ;
-(void)_setDoubleTapGesturesEnabled:(BOOL)arg0 ;
-(void)_setFontForWebView:(id)arg0 sender:(id)arg1 ;
-(void)_setFontSizeForWebView:(CGFloat)arg0 sender:(id)arg1 ;
-(void)_setMarkedText:(id)arg0 underlines:(*void)arg1 highlights:(*void)arg2 selectedRange:(struct _NSRange )arg3 ;
-(void)_setMouseEventPolicy:(unsigned char)arg0 ;
-(void)_setTextColorForWebView:(id)arg0 sender:(id)arg1 ;
-(void)_setUpImageAnalysis;
-(void)_setupVisibilityPropagationViewForGPUProcess;
-(void)_setupVisibilityPropagationViewForWebProcess;
-(void)_share:(id)arg0 ;
-(void)_shareForWebView:(id)arg0 ;
-(void)_showAttachmentSheet;
-(void)_showContactPicker:(*void)arg0 completionHandler:(*void)arg1 ;
-(void)_showDataDetectorsUI;
-(void)_showDataDetectorsUIForPositionInformation:(*void)arg0 ;
-(void)_showDictionary:(id)arg0 ;
-(void)_showImageSheet;
-(void)_showInspectorHighlight:(*void)arg0 ;
-(void)_showKeyboard;
-(void)_showLinkSheet;
-(void)_showMediaControlsContextMenu:(struct FloatRect *)arg0 items:(*void)arg1 completionHandler:(*void)arg2 ;
-(void)_showPlaybackTargetPicker:(BOOL)arg0 fromRect:(struct IntRect *)arg1 routeSharingPolicy:(unsigned char)arg2 routingContextUID:(id)arg3 ;
-(void)_showRunOpenPanel:(struct OpenPanelParameters *)arg0 frameInfo:(*void)arg1 resultListener:(struct WebOpenPanelResultListenerProxy *)arg2 ;
-(void)_showShareSheet:(*void)arg0 inRect:(struct optional<WebCore::FloatRect> )arg1 completionHandler:(*void)arg2 ;
-(void)_showTapHighlight;
-(void)_showTextStyleOptions:(id)arg0 ;
-(void)_showTextStyleOptionsForWebView:(id)arg0 ;
-(void)_simulateElementAction:(NSInteger)arg0 atLocation:(struct CGPoint )arg1 ;
-(void)_simulateLongPressActionAtLocation:(struct CGPoint )arg0 ;
-(void)_simulateSelectionStart;
-(void)_simulateTextEntered:(id)arg0 ;
-(void)_singleTapDidReset:(id)arg0 ;
-(void)_singleTapIdentified:(id)arg0 ;
-(void)_singleTapRecognized:(id)arg0 ;
-(void)_startDrag:(struct RetainPtr<CGImage *> )arg0 item:(*void)arg1 ;
-(void)_startSuppressingSelectionAssistantForReason:(unsigned char)arg0 ;
-(void)_stopSuppressingSelectionAssistantForReason:(unsigned char)arg0 ;
-(void)_targetedPreviewContainerDidRemoveLastSubview:(id)arg0 ;
-(void)_tearDownImageAnalysis;
-(void)_toggleStrikeThrough:(id)arg0 ;
-(void)_toggleStrikeThroughForWebView:(id)arg0 ;
-(void)_translate:(id)arg0 ;
-(void)_translateForWebView:(id)arg0 ;
-(void)_transliterateChinese:(id)arg0 ;
-(void)_transliterateChineseForWebView:(id)arg0 ;
-(void)_transpose;
-(void)_twoFingerDoubleTapRecognized:(id)arg0 ;
-(void)_twoFingerSingleTapGestureRecognized:(id)arg0 ;
-(void)_unregisterPreview;
-(void)_updateAccessory;
-(void)_updateChangedSelection;
-(void)_updateChangedSelection:(BOOL)arg0 ;
-(void)_updateForScreen:(id)arg0 ;
-(void)_updateFrameOfContainerForContextMenuHintPreviewsIfNeeded;
-(void)_updateInitialWritingDirectionIfNecessary;
-(void)_updateInputContextAfterBlurringAndRefocusingElement;
-(void)_updateInteractionTintColor:(id)arg0 ;
-(void)_updateLongPressAndHighlightLongPressGestures;
-(void)_updateRemoteAccessibilityRegistration:(BOOL)arg0 ;
-(void)_updateSelectionAssistantSuppressionState;
-(void)_updateTapHighlight;
-(void)_updateTargetedPreviewScrollViewUsingContainerScrollingNodeID:(NSUInteger)arg0 ;
-(void)_updateTextInputTraits:(id)arg0 ;
-(void)_waitForDrawToPDFCallbackForPrintFormatterIfNeeded:(id)arg0 ;
-(void)_webProcessDidCreateContextForVisibilityPropagation;
-(void)_webTouchEvent:(*void)arg0 preventsNativeGestures:(BOOL)arg1 ;
-(void)_webTouchEventsRecognized:(id)arg0 ;
-(void)_webViewDestroyed;
-(void)_wheelChangedWithEvent:(id)arg0 ;
-(void)_willBeginTextInteractionInTextInputContext:(id)arg0 ;
-(void)_willHideMenu:(id)arg0 ;
-(void)_willPerformAction:(SEL)arg0 sender:(id)arg1 ;
-(void)_willReceiveEditDragSnapshot;
-(void)_willStartScrollingOrZooming;
-(void)_windowDidMoveToScreenNotification:(id)arg0 ;
-(void)_wk_requestDocumentForPrintFormatter:(id)arg0 ;
-(void)_writePromisedAttachmentToPasteboard:(*void)arg0 ;
-(void)_zoomOutWithOrigin:(struct CGPoint )arg0 ;
-(void)_zoomToFocusRect:(struct CGRect )arg0 selectionRect:(struct CGRect )arg1 fontSize:(float)arg2 minimumScale:(CGFloat)arg3 maximumScale:(CGFloat)arg4 allowScaling:(BOOL)arg5 forceScroll:(BOOL)arg6 ;
-(void)_zoomToInitialScaleWithOrigin:(struct CGPoint )arg0 ;
-(void)_zoomToRevealFocusedElement;
-(void)accessibilityRetrieveSpeakSelectionContent;
-(void)accessoryAutoFill;
-(void)accessoryClear;
-(void)accessoryDone;
-(void)accessoryOpen;
-(void)accessoryTab:(BOOL)arg0 ;
-(void)actionSheetAssistant:(id)arg0 copySubject:(id)arg1 sourceMIMEType:(id)arg2 ;
-(void)actionSheetAssistant:(id)arg0 getAlternateURLForImage:(id)arg1 completion:(id)arg2 ;
-(void)actionSheetAssistant:(id)arg0 lookUpImage:(id)arg1 imageURL:(id)arg2 title:(id)arg3 imageBounds:(struct CGRect )arg4 ;
-(void)actionSheetAssistant:(id)arg0 openElementAtLocation:(struct CGPoint )arg1 ;
-(void)actionSheetAssistant:(id)arg0 performAction:(BOOL)arg1 ;
-(void)actionSheetAssistant:(id)arg0 shareElementWithImage:(id)arg1 rect:(struct CGRect )arg2 ;
-(void)actionSheetAssistant:(id)arg0 shareElementWithURL:(id)arg1 rect:(struct CGRect )arg2 ;
-(void)actionSheetAssistant:(id)arg0 showTextForImage:(id)arg1 imageURL:(id)arg2 title:(id)arg3 imageBounds:(struct CGRect )arg4 ;
-(void)actionSheetAssistant:(id)arg0 willStartInteractionWithElement:(id)arg1 ;
-(void)actionSheetAssistantDidDismissContextMenu:(id)arg0 ;
-(void)actionSheetAssistantDidShowContextMenu:(id)arg0 ;
-(void)actionSheetAssistantDidStopInteraction:(id)arg0 ;
-(void)addTextAlternatives:(id)arg0 ;
-(void)adjustSelectionWithDelta:(struct _NSRange )arg0 completionHandler:(id)arg1 ;
-(void)alignCenterForWebView:(id)arg0 ;
-(void)alignJustifiedForWebView:(id)arg0 ;
-(void)alignLeftForWebView:(id)arg0 ;
-(void)alignRightForWebView:(id)arg0 ;
-(void)applyAutocorrection:(id)arg0 toString:(id)arg1 withCompletionHandler:(id)arg2 ;
-(void)assignLegacyDataForContextMenuInteraction;
-(void)beginSelectionChange;
-(void)beginSelectionInDirection:(NSInteger)arg0 completionHandler:(id)arg1 ;
-(void)beginTextRecognitionForFullscreenVideo:(*void)arg0 playerViewController:(id)arg1 ;
-(void)beginTextRecognitionForVideoInElementFullscreen:(*void)arg0 bounds:(struct FloatRect )arg1 ;
-(void)buildMenuForWebViewWithBuilder:(id)arg0 ;
-(void)cancelActiveTextInteractionGestures;
-(void)cancelAutoscroll;
-(void)cancelPointersForGestureRecognizer:(id)arg0 ;
-(void)cancelTextRecognitionForFullscreenVideo:(id)arg0 ;
-(void)cancelTextRecognitionForVideoInElementFullscreen;
-(void)captureTextFromCamera:(id)arg0 ;
-(void)captureTextFromCameraForWebView:(id)arg0 ;
-(void)changeSelectionWithGestureAt:(struct CGPoint )arg0 withGesture:(NSInteger)arg1 withState:(NSInteger)arg2 ;
-(void)changeSelectionWithGestureAt:(struct CGPoint )arg0 withGesture:(NSInteger)arg1 withState:(NSInteger)arg2 withFlags:(NSInteger)arg3 ;
-(void)changeSelectionWithTouchAt:(struct CGPoint )arg0 withSelectionTouch:(NSInteger)arg1 baseIsStart:(BOOL)arg2 withFlags:(NSInteger)arg3 ;
-(void)changeSelectionWithTouchesFrom:(struct CGPoint )arg0 to:(struct CGPoint )arg1 withGesture:(NSInteger)arg2 withState:(NSInteger)arg3 ;
-(void)cleanUpDragSourceSessionState;
-(void)cleanUpInteraction;
-(void)cleanUpInteractionPreviewContainers;
-(void)cleanUpScribbleInteraction;
-(void)clearAllDecoratedFoundText;
-(void)clearSelection;
-(void)clearTextIndicator:(unsigned char)arg0 ;
-(void)computeClientAndGlobalPointsForDropSession:(id)arg0 outClientPoint:(struct CGPoint *)arg1 outGlobalPoint:(struct CGPoint *)arg2 ;
-(void)contactPickerDidDismiss:(id)arg0 ;
-(void)contactPickerDidPresent:(id)arg0 ;
-(void)contextMenuInteraction:(id)arg0 willDisplayMenuForConfiguration:(id)arg1 animator:(id)arg2 ;
-(void)contextMenuInteraction:(id)arg0 willEndForConfiguration:(id)arg1 animator:(id)arg2 ;
-(void)contextMenuInteraction:(id)arg0 willPerformPreviewActionForMenuWithConfiguration:(id)arg1 animator:(id)arg2 ;
-(void)continueContextMenuInteraction:(id)arg0 ;
-(void)continueContextMenuInteractionWithDataDetectors:(id)arg0 ;
-(void)copy:(id)arg0 ;
-(void)copyForWebView:(id)arg0 ;
-(void)cut:(id)arg0 ;
-(void)cutForWebView:(id)arg0 ;
-(void)dealloc;
-(void)decorateFoundTextRange:(id)arg0 inDocument:(id)arg1 usingStyle:(NSInteger)arg2 ;
-(void)decreaseSize:(id)arg0 ;
-(void)decreaseSizeForWebView:(id)arg0 ;
-(void)deferringGestureRecognizer:(id)arg0 didEndTouchesWithEvent:(id)arg1 ;
-(void)deferringGestureRecognizer:(id)arg0 didTransitionToState:(NSInteger)arg1 ;
-(void)deleteBackward;
-(void)didBeginTextSearchOperation;
-(void)didEndTextSearchOperation;
-(void)didFinishScrolling;
-(void)didInsertFinalDictationResult;
-(void)didInterruptScrolling;
-(void)didMoveToWindow;
-(void)didUpdateFocusInContext:(id)arg0 withAnimationCoordinator:(id)arg1 ;
-(void)didUpdateVisibleRect:(struct CGRect )arg0 unobscuredRect:(struct CGRect )arg1 contentInsets:(struct UIEdgeInsets )arg2 unobscuredRectInScrollViewCoordinates:(struct CGRect )arg3 obscuredInsets:(struct UIEdgeInsets )arg4 unobscuredSafeAreaInsets:(struct UIEdgeInsets )arg5 inputViewBounds:(struct CGRect )arg6 scale:(CGFloat)arg7 minimumScale:(CGFloat)arg8 viewStability:(struct OptionSet<WebKit::ViewStabilityFlag> )arg9 enclosedInScrollableAncestorView:(BOOL)arg10 sendEvenIfUnchanged:(BOOL)arg11 ;
-(void)didZoomToScale:(CGFloat)arg0 ;
-(void)dismissFilePicker;
-(void)doAfterComputingImageAnalysisResultsForBackgroundRemoval:(*void)arg0 ;
-(void)doAfterEditorStateUpdateAfterFocusingElement:(id)arg0 ;
// -(void)doAfterPositionInformationUpdate:(id)arg0 forRequest:(unk)arg1  ;
-(void)dragInteraction:(id)arg0 item:(id)arg1 willAnimateCancelWithAnimator:(id)arg2 ;
-(void)dragInteraction:(id)arg0 session:(id)arg1 didEndWithOperation:(NSUInteger)arg2 ;
-(void)dragInteraction:(id)arg0 sessionDidTransferItems:(id)arg1 ;
-(void)dragInteraction:(id)arg0 sessionWillBegin:(id)arg1 ;
-(void)dragInteraction:(id)arg0 willAnimateLiftWithAnimator:(id)arg1 session:(id)arg2 ;
-(void)dropInteraction:(id)arg0 concludeDrop:(id)arg1 ;
-(void)dropInteraction:(id)arg0 item:(id)arg1 willAnimateDropWithAnimator:(id)arg2 ;
-(void)dropInteraction:(id)arg0 performDrop:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidEnd:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidEnter:(id)arg1 ;
-(void)dropInteraction:(id)arg0 sessionDidExit:(id)arg1 ;
-(void)endEditingAndUpdateFocusAppearanceWithReason:(NSInteger)arg0 ;
-(void)endSelectionChange;
-(void)executeEditCommandWithCallback:(id)arg0 ;
-(void)fileUploadPanelDidDismiss:(id)arg0 ;
-(void)generateSyntheticEditingCommand:(unsigned char)arg0 ;
-(void)handleKeyWebEvent:(id)arg0 ;
-(void)handleKeyWebEvent:(id)arg0 withCompletionHandler:(id)arg1 ;
-(void)imageAnalysisGestureDidBegin:(id)arg0 ;
-(void)imageAnalysisGestureDidFail:(id)arg0 ;
-(void)imageAnalysisGestureDidTimeOut:(id)arg0 ;
-(void)increaseSize:(id)arg0 ;
-(void)increaseSizeForWebView:(id)arg0 ;
-(void)indentForWebView:(id)arg0 ;
-(void)indirectScribbleInteraction:(id)arg0 didFinishWritingInElement:(id)arg1 ;
-(void)indirectScribbleInteraction:(id)arg0 focusElementIfNeeded:(id)arg1 referencePoint:(struct CGPoint )arg2 completion:(id)arg3 ;
-(void)indirectScribbleInteraction:(id)arg0 requestElementsInRect:(struct CGRect )arg1 completion:(id)arg2 ;
-(void)indirectScribbleInteraction:(id)arg0 willBeginWritingInElement:(id)arg1 ;
-(void)insertNestedOrderedListForWebView:(id)arg0 ;
-(void)insertNestedUnorderedListForWebView:(id)arg0 ;
-(void)insertOrderedListForWebView:(id)arg0 ;
-(void)insertText:(id)arg0 ;
-(void)insertText:(id)arg0 alternatives:(id)arg1 style:(NSInteger)arg2 ;
-(void)insertTextPlaceholderWithSize:(struct CGSize )arg0 completionHandler:(id)arg1 ;
-(void)insertTextSuggestion:(id)arg0 ;
-(void)insertUnorderedListForWebView:(id)arg0 ;
-(void)installImageAnalysisInteraction:(id)arg0 ;
-(void)keyboardScrollViewAnimatorDidFinishScrolling:(id)arg0 ;
-(void)keyboardScrollViewAnimatorWillScroll:(id)arg0 ;
-(void)makeTextWritingDirectionLeftToRight:(id)arg0 ;
-(void)makeTextWritingDirectionLeftToRightForWebView:(id)arg0 ;
-(void)makeTextWritingDirectionNatural:(id)arg0 ;
-(void)makeTextWritingDirectionNaturalForWebView:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeft:(id)arg0 ;
-(void)makeTextWritingDirectionRightToLeftForWebView:(id)arg0 ;
-(void)modifierFlagsDidChangeFrom:(NSInteger)arg0 to:(NSInteger)arg1 ;
-(void)mouseGestureRecognizerChanged:(id)arg0 ;
-(void)moveBackward:(unsigned int)arg0 ;
-(void)moveByOffset:(NSInteger)arg0 ;
-(void)moveForward:(unsigned int)arg0 ;
-(void)moveSelectionAtBoundary:(NSInteger)arg0 inDirection:(NSInteger)arg1 completionHandler:(id)arg2 ;
-(void)observeValueForKeyPath:(id)arg0 ofObject:(id)arg1 change:(id)arg2 context:(*void)arg3 ;
-(void)outdentForWebView:(id)arg0 ;
-(void)paste:(id)arg0 ;
-(void)pasteAndMatchStyle:(id)arg0 ;
-(void)pasteAndMatchStyleForWebView:(id)arg0 ;
-(void)pasteForWebView:(id)arg0 ;
-(void)pasteWithCompletionHandler:(id)arg0 ;
-(void)performTextSearchWithQueryString:(id)arg0 usingOptions:(id)arg1 resultAggregator:(id)arg2 ;
-(void)prepareSelectionForContextMenuWithLocationInView:(struct CGPoint )arg0 completionHandler:(id)arg1 ;
-(void)presentContextMenu:(id)arg0 atLocation:(struct CGPoint )arg1 ;
-(void)presentVisualSearchPreviewControllerForImage:(id)arg0 imageURL:(id)arg1 title:(id)arg2 imageBounds:(struct CGRect )arg3 appearanceActions:(NSUInteger)arg4 ;
-(void)previewControllerDidDismiss:(id)arg0 ;
-(void)reloadContextViewForPresentedListViewController;
-(void)removeContextMenuViewIfPossibleForActionSheetAssistant:(id)arg0 ;
-(void)removeEmojiAlternatives;
-(void)removeTextPlaceholder:(id)arg0 willInsertText:(BOOL)arg1 completionHandler:(id)arg2 ;
-(void)replace:(id)arg0 ;
-(void)replaceDictatedText:(id)arg0 withText:(id)arg1 ;
-(void)replaceForWebView:(id)arg0 ;
-(void)replaceFoundTextInRange:(id)arg0 inDocument:(id)arg1 withText:(id)arg2 ;
-(void)replaceRange:(id)arg0 withText:(id)arg1 ;
-(void)replaceRangeWithTextWithoutClosingTyping:(id)arg0 replacementText:(id)arg1 ;
-(void)replaceText:(id)arg0 withText:(id)arg1 ;
-(void)requestAsynchronousPositionInformationUpdate:(struct InteractionInformationRequest )arg0 ;
-(void)requestAutocorrectionContextWithCompletionHandler:(id)arg0 ;
-(void)requestAutocorrectionRectsForString:(id)arg0 withCompletionHandler:(id)arg1 ;
-(void)requestDictationContext:(id)arg0 ;
-(void)requestDocumentContext:(id)arg0 completionHandler:(id)arg1 ;
-(void)requestPreferredArrowDirectionForEditMenuWithCompletionHandler:(id)arg0 ;
-(void)requestRVItemInSelectedRangeWithCompletionHandler:(id)arg0 ;
-(void)requestRectForFoundTextRange:(id)arg0 completionHandler:(id)arg1 ;
-(void)requestRectsToEvadeForSelectionCommandsWithCompletionHandler:(id)arg0 ;
-(void)requestTextRecognition:(id)arg0 imageData:(*void)arg1 sourceLanguageIdentifier:(id)arg2 targetLanguageIdentifier:(id)arg3 completionHandler:(*void)arg4 ;
-(void)runModalJavaScriptDialog:(*void)arg0 ;
-(void)scrollRangeToVisible:(id)arg0 inDocument:(id)arg1 ;
-(void)scrollSelectionToVisible:(BOOL)arg0 ;
-(void)scrollViewWillStartPanOrPinchGesture;
-(void)select:(id)arg0 ;
-(void)selectAll;
-(void)selectAll:(id)arg0 ;
-(void)selectAllForWebView:(id)arg0 ;
-(void)selectForWebView:(id)arg0 ;
-(void)selectFormAccessoryPickerRow:(NSInteger)arg0 ;
-(void)selectPositionAtBoundary:(NSInteger)arg0 inDirection:(NSInteger)arg1 fromPoint:(struct CGPoint )arg2 completionHandler:(id)arg3 ;
-(void)selectPositionAtPoint:(struct CGPoint )arg0 completionHandler:(id)arg1 ;
-(void)selectPositionAtPoint:(struct CGPoint )arg0 withContextRequest:(id)arg1 completionHandler:(id)arg2 ;
-(void)selectTextWithGranularity:(NSInteger)arg0 atPoint:(struct CGPoint )arg1 completionHandler:(id)arg2 ;
-(void)selectWordBackward;
-(void)selectWordForReplacement;
-(void)setAttributedMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)setBaseWritingDirection:(NSInteger)arg0 forRange:(id)arg1 ;
-(void)setBottomBufferHeight:(CGFloat)arg0 ;
-(void)setContinuousSpellCheckingEnabled:(BOOL)arg0 ;
-(void)setMarkedText:(id)arg0 ;
-(void)setMarkedText:(id)arg0 selectedRange:(struct _NSRange )arg1 ;
-(void)setSelectedColorForColorPicker:(id)arg0 ;
-(void)setSelectedDOMRange:(id)arg0 affinityDownstream:(BOOL)arg1 ;
-(void)setTextIndicatorAnimationProgress:(float)arg0 ;
-(void)setTimePickerValueToHour:(NSInteger)arg0 minute:(NSInteger)arg1 ;
-(void)setUpDragAndDropInteractions;
-(void)setUpInteraction;
-(void)setUpMouseGestureRecognizer;
-(void)setUpPointerInteraction;
-(void)setUpScribbleInteraction;
-(void)setUpTextIndicator:(struct Ref<WebCore::TextIndicator, WTF::RawPtrTraits<WebCore::TextIndicator>> )arg0 ;
-(void)setUpTextSelectionAssistant;
-(void)shareSheet:(id)arg0 willShowActivityItems:(id)arg1 ;
-(void)shareSheetDidDismiss:(id)arg0 ;
-(void)startAutoscroll:(struct CGPoint )arg0 ;
-(void)startDeferringInputViewUpdates:(struct OptionSet<WebKit::InputViewUpdateDeferralSource> )arg0 ;
-(void)startFadeOut;
-(void)startRelinquishingFirstResponderToFocusedElement;
-(void)stopDeferringInputViewUpdates:(struct OptionSet<WebKit::InputViewUpdateDeferralSource> )arg0 ;
-(void)stopDeferringInputViewUpdatesForAllSources;
-(void)stopRelinquishingFirstResponderToFocusedElement;
-(void)takeTraitsFrom:(id)arg0 ;
-(void)teardownDragAndDropInteractions;
-(void)teardownTextIndicatorLayer;
-(void)tintColorDidChange;
-(void)toggleBoldface:(id)arg0 ;
-(void)toggleBoldfaceForWebView:(id)arg0 ;
-(void)toggleItalics:(id)arg0 ;
-(void)toggleItalicsForWebView:(id)arg0 ;
-(void)toggleStrikeThroughForWebView:(id)arg0 ;
-(void)toggleUnderline:(id)arg0 ;
-(void)toggleUnderlineForWebView:(id)arg0 ;
-(void)uninstallImageAnalysisInteraction;
-(void)unmarkText;
-(void)unsuppressSoftwareKeyboardUsingLastAutocorrectionContextIfNeeded;
-(void)updateCurrentFocusedElementInformation:(*void)arg0 ;
-(void)updateFixedClippingView:(struct FloatRect )arg0 ;
-(void)updateFocusedElementFocusedWithDataListDropdown:(BOOL)arg0 ;
-(void)updateFocusedElementSelectedIndex:(unsigned int)arg0 allowsMultipleSelection:(BOOL)arg1 ;
-(void)updateFocusedElementValue:(id)arg0 ;
-(void)updateFocusedElementValueAsColor:(id)arg0 ;
-(void)updateImageAnalysisForContextMenuPresentation:(id)arg0 ;
-(void)updatePositionInformationForActionSheetAssistant:(id)arg0 ;
-(void)updateSelectionWithExtentPoint:(struct CGPoint )arg0 completionHandler:(id)arg1 ;
-(void)updateSelectionWithExtentPoint:(struct CGPoint )arg0 withBoundary:(NSInteger)arg1 completionHandler:(id)arg2 ;
-(void)updateSoftwareKeyboardSuppressionStateFromWebView;
-(void)updateTextSuggestionsForInputDelegate;
-(void)useSelectionForFind:(id)arg0 ;
-(void)useSelectionForFindForWebView:(id)arg0 ;
-(void)willDismissEditMenuWithAnimator:(id)arg0 ;
-(void)willFinishIgnoringCalloutBarFadeAfterPerformingAction;
-(void)willInsertFinalDictationResult;
-(void)willMoveToWindow:(id)arg0 ;
-(void)willPresentEditMenuWithAnimator:(id)arg0 ;
-(void)willStartZoomOrScroll;


@end


#endif