// Headers generated with ktool v2.0.0
// https://github.com/cxnder/ktool | pip3 install k2l
// Platform: IOS | Minimum OS: 15.0.0 | SDK: 15.0.0


#ifndef CKUIBEHAVIOR_H
#define CKUIBEHAVIOR_H

@class NSArray, UIFont, NSString, NSParagraphStyle, UIImage, NSDictionary, UIColor, NSDateFormatter, NSAttributedString;

#import <Foundation/Foundation.h>

#import "CKMessageEntryViewLayoutMetrics.h"
#import "CKUITheme.h"

@interface CKUIBehavior : NSObject

@property (nonatomic) NSInteger HUDStyle; // ivar: _HUDStyle
@property (readonly, nonatomic) NSArray *acceptableUTIs;
@property (readonly, nonatomic) CGFloat accessibilityBottomConversationListSpace;
@property (readonly, nonatomic) Class acknowledgementPickerBarClass;
@property (readonly, nonatomic) CGFloat actionMenuWindowLevel;
@property (readonly, nonatomic) UIFont *addContactFont;
@property (readonly, nonatomic) CGSize aggregateAcknowledgmentTranscriptBalloonSize;
@property (readonly, nonatomic) BOOL alwaysShowSelectionInConversationList;
@property (readonly, nonatomic) NSUInteger appIconPrefetchLimit;
@property (readonly, nonatomic) CGSize appIconSize;
@property (readonly, nonatomic) UIFont *appLabelFont;
@property (readonly, nonatomic) BOOL areBannersSupported;
@property (readonly, nonatomic) CGFloat arrowButtonRightPadding;
@property (readonly, nonatomic) char attachmentBalloonFillColor;
@property (readonly, nonatomic) UIEdgeInsets attachmentBalloonRichIconInsets;
@property (readonly, nonatomic) CGSize attachmentBalloonSize;
@property (readonly, nonatomic) char attachmentBalloonStrokeColor;
@property (readonly, nonatomic) CGSize attachmentBrowserDefaultSizeForSquare;
@property (readonly, nonatomic) UIEdgeInsets attachmentBrowserFeedLayoutSectionInset;
@property (readonly, nonatomic) CGFloat attachmentBrowserGridInterItemSpacing;
@property (readonly, nonatomic) CGFloat attachmentBrowserGridMinimumLineSpacing;
@property (readonly, nonatomic) UIEdgeInsets attachmentBrowserGridSectionInset;
@property (readonly, nonatomic) CGFloat attachmentBrowserHeaderLabelPadding;
@property (readonly, nonatomic) UIEdgeInsets attachmentReplyPreviewBalloonAlignmentRectInsets;
@property (readonly, nonatomic) UIFont *attachmentTextFont;
@property (readonly, nonatomic) Class attachmentViewClass;
@property (readonly, nonatomic) UIEdgeInsets audioBalloonAlignmentInsets;
@property (readonly, nonatomic) Class audioBalloonCellClass;
@property (readonly, nonatomic) CGFloat audioBalloonProgressInset;
@property (readonly, nonatomic) UIFont *audioBalloonTimeFont;
@property (readonly, nonatomic) CGFloat audioBalloonTimeInset;
@property (readonly, nonatomic) Class audioBalloonViewClass;
@property (readonly, nonatomic) CGFloat audioBalloonWaveformTimeSpace;
@property (readonly, nonatomic) UIFont *audioHintFont;
@property (readonly, nonatomic) CGSize audioProgressViewSize;
@property (readonly, nonatomic) UIEdgeInsets audioReplyPreviewBalloonAlignmentInsets;
@property (readonly, nonatomic) CGFloat audioReplyPreviewBalloonInset;
@property (readonly, nonatomic) BOOL automaticallyShowsKeyboard;
@property (readonly, nonatomic) CGFloat avatarContactImageNameMargin;
@property (readonly, nonatomic) CGSize avatarCutoutSize;
@property (readonly, nonatomic) UIFont *avatarNameEmergencyFont;
@property (readonly, nonatomic) UIFont *avatarNameFont;
@property (readonly, nonatomic) CGFloat avatarNameWidth;
@property (readonly, nonatomic) CGFloat avatarPancakeGroupOffset;
@property (readonly, nonatomic) CGFloat avatarPancakeMaxOffset;
@property (readonly, nonatomic) CGSize avatarSize;
@property (readonly, nonatomic) CGFloat avatarSpacingMargin;
@property (readonly, nonatomic) UIFont *avatarStackTitleFont;
@property (readonly, nonatomic) CGFloat avatarTitleOffset;
@property (readonly, nonatomic) CGFloat avatarVerticalOffset;
@property (readonly, nonatomic) CGFloat balloonContiguousSpace;
@property (readonly, nonatomic) UIEdgeInsets balloonLineFragmentInsets;
@property (readonly, nonatomic) CGFloat balloonLineFragmentPadding;
@property (readonly, nonatomic) CGFloat balloonMaskTailWidth;
@property (readonly, nonatomic) CGFloat balloonMaxWidthPercent;
@property (readonly, nonatomic) NSString *balloonName;
@property (readonly, nonatomic) CGFloat balloonNonContiguousSpace;
@property (readonly, nonatomic) NSParagraphStyle *balloonParagraphStyle;
@property (readonly, nonatomic) CGFloat balloonSelectionLoadMoreSpinnerHeight; // ivar: _balloonSelectionLoadMoreSpinnerHeight
@property (readonly, nonatomic) CGFloat balloonSelectionMaxScrollSpeed; // ivar: _balloonSelectionMaxScrollSpeed
@property (readonly, nonatomic) CGFloat balloonSelectionScrollThresholdBottom; // ivar: _balloonSelectionScrollThresholdBottom
@property (readonly, nonatomic) CGFloat balloonSelectionScrollThresholdTop; // ivar: _balloonSelectionScrollThresholdTop
@property (readonly, nonatomic) UIFont *balloonSubjectFont;
@property (readonly, nonatomic) UIEdgeInsets balloonTextContainerInset;
@property (readonly, nonatomic) UIFont *balloonTextFont;
@property (readonly, nonatomic) UIEdgeInsets balloonTranscriptInsets;
@property (readonly, nonatomic) CGFloat bannerAdditionalOffset;
@property (readonly, nonatomic) CGSize bannerCellSize;
@property (readonly, nonatomic) CGFloat bannerTitleAdditionalOffset;
@property (readonly, nonatomic) UIEdgeInsets bigEmojiAlignmentRectInsets;
@property (readonly, nonatomic) UIFont *bigEmojiFont;
@property (readonly, nonatomic) CGFloat bottomConversationListSpace;
@property (readonly, nonatomic) CGFloat bottomTranscriptSpace;
@property (readonly, nonatomic) BOOL browserButtonShouldUseExternalMenu;
@property (readonly, nonatomic) BOOL browserButtonShouldUseMenu;
@property (readonly, nonatomic) CGSize browserButtonSize;
@property (readonly, nonatomic) UIFont *browserCellFont;
@property (readonly, nonatomic) CGFloat browserSwitcherCollapsedGrabberHeaderHeight;
@property (readonly, nonatomic) CGFloat browserSwitcherCompactGrabberVisibleHeight;
@property (readonly, nonatomic) CGFloat browserSwitcherEdgeGestureWidth;
@property (readonly, nonatomic) CGFloat browserSwitcherExpandThreshold;
@property (readonly, nonatomic) CGFloat browserSwitcherExpandedGrabberHeaderHeight;
@property (readonly, nonatomic) CGFloat browserSwitcherGutterWidth;
@property (readonly, nonatomic) CGFloat browserSwitcherScrollerHeight;
@property (readonly, nonatomic) CGSize businessBannerSize;
@property (readonly, nonatomic) CGFloat businessBrandingAnimationDuration;
@property (readonly, nonatomic) CGFloat businessBrandingBannerInset;
@property (readonly, nonatomic) Class businessChatControllerClass;
@property (readonly, nonatomic) UIFont *businessDescriptionVCTextViewFont;
@property (readonly, nonatomic) UIImage *businessFallbackImage;
@property (readonly, nonatomic) UIFont *businessInfoViewDescriptionTextFont;
@property (readonly, nonatomic) UIFont *businessInfoViewGreetingTextFont;
@property (readonly, nonatomic) UIFont *businessInfoViewTitleLabelFont;
@property (readonly, nonatomic) UIImage *businessVerifiedImageLarge;
@property (readonly, nonatomic) UIImage *businessVerifiedImageSmall;
@property (readonly, nonatomic) BOOL calculatesWidthForAttachmentBalloons;
@property (readonly, nonatomic) UIEdgeInsets callButtonImageInsets;
@property (readonly, nonatomic) CGFloat callButtonLongPressDuration;
@property (readonly, nonatomic) CGFloat callButtonSize;
@property (readonly, nonatomic) CGFloat cameraAppsMinimizedDockHeight;
@property (readonly, nonatomic) BOOL cameraIsAllowlisted;
@property (readonly, nonatomic) BOOL canAccessContacts;
@property (readonly, nonatomic) BOOL canAccessPhotos;
@property (readonly, nonatomic) BOOL canPluginBalloonsUseOpaqueMask;
@property (readonly, nonatomic) BOOL canPresentOverKeyboard;
@property (readonly, nonatomic) BOOL canShowContactPhotosInConversationList;
@property (readonly, nonatomic) BOOL canUseWindowedSendAnimation;
@property (readonly, nonatomic) NSDictionary *centerTranscriptButtonTextAttributes;
@property (readonly, nonatomic) UIFont *characterCountFont;
@property (readonly, nonatomic) CGFloat chatChromeBottomInset;
@property (readonly, nonatomic) Class chatControllerClass;
@property (readonly, nonatomic) CGFloat chatMagnifiedChromeBottomInset;
@property (readonly, nonatomic) CGFloat checkmarkHorizontalPadding;
@property (readonly, nonatomic) UIImage *chevronImage;
@property (readonly, nonatomic) NSUInteger commonRepliesLoadLimit;
@property (readonly, nonatomic) UIFont *contactAttachmentNameFont;
@property (readonly, nonatomic) UIFont *contactAttachmentOrgFont;
@property (readonly, nonatomic) CGFloat contactBalloonHeight;
@property (readonly, nonatomic) CGFloat contactBalloonInnerItemSpacing;
@property (readonly, nonatomic) CGFloat contactBalloonMinWidth;
@property (readonly, nonatomic) CGFloat contactBalloonNameOrgSpacing;
@property (readonly, nonatomic) CGFloat contactBalloonOrgBottomSpacing;
@property (readonly, nonatomic) CGFloat contactBalloonTopNameSpacing;
@property (readonly, nonatomic) Class contactBalloonViewClass;
@property (readonly, nonatomic) CGSize contactImageSize;
@property (readonly, nonatomic) CGFloat contactPhotoBalloonMargin;
@property (readonly, nonatomic) UIEdgeInsets contactPhotoTranscriptInsets;
@property (readonly, nonatomic) BOOL converastionListAlwaysSupportsLargeTitles;
@property (readonly, nonatomic) NSUInteger conversationCacheSize;
@property (readonly, nonatomic) NSDictionary *conversationCellSummaryBoldIconTextAttributes;
@property (readonly, nonatomic) NSDictionary *conversationCellSummaryBoldPreviewTextAttributes;
@property (readonly, nonatomic) NSDictionary *conversationCellSummaryPreviewTextAttributes;
@property (readonly, nonatomic) BOOL conversationListAlwaysShowsSearchBar;
@property (readonly, nonatomic) UIFont *conversationListBoldSummaryFont;
@property (readonly, nonatomic) CGFloat conversationListButtonToTitleSpacing;
@property (readonly, nonatomic) CGFloat conversationListCellBackgroundPadding;
@property (readonly, nonatomic) CGFloat conversationListCellHighlightViewToUnreadIndicatorPadding;
@property (readonly, nonatomic) CGFloat conversationListCellLargeTextLeftMargin;
@property (readonly, nonatomic) CGFloat conversationListCellLeftMargin;
@property (readonly, nonatomic) NSUInteger conversationListCellMaxSummaryLength;
@property (readonly, nonatomic) CGFloat conversationListCellRightMargin;
@property (readonly, nonatomic) CGFloat conversationListCellRoundSelectorLeftInset;
@property (readonly, nonatomic) CGFloat conversationListCellRoundSelectorRightInset;
@property (readonly, nonatomic) NSUInteger conversationListCellSummaryNumberOfLines;
@property (readonly, nonatomic) CGFloat conversationListCellTypingIndicatorScale;
@property (readonly, nonatomic) BOOL conversationListCellUsesLargeTextLayout;
@property (readonly, nonatomic) CGFloat conversationListComposeButtonSpacing;
@property (readonly, nonatomic) CGFloat conversationListContactImageDiameter;
@property (readonly, nonatomic) CGFloat conversationListContactImageTrailingSpace;
@property (readonly, nonatomic) Class conversationListControllerClass;
@property (readonly, nonatomic) UIFont *conversationListDateFont;
@property (readonly, nonatomic) CGFloat conversationListEditingTableMarginWidth;
@property (readonly, nonatomic) UIImage *conversationListFacetimeAudioIcon;
@property (readonly, nonatomic) UIImage *conversationListFacetimeVideoIcon;
@property (readonly, nonatomic) UIFont *conversationListGroupCountFont;
@property (readonly, nonatomic) UIFont *conversationListGroupSenderFont;
@property (readonly, nonatomic) UIFont *conversationListLargeTitleReducedFont;
@property (readonly, nonatomic) UIFont *conversationListLargeTitleStandardFont;
@property (readonly, nonatomic) NSInteger conversationListLayoutPinnedSectionNumberOfColumns;
@property (readonly, nonatomic) CGFloat conversationListMinimumWidthForHiddenContactImage;
@property (readonly, nonatomic) CGFloat conversationListMultipleContactsImageDiameter;
@property (readonly, nonatomic) UIImage *conversationListMuteIndicatorImage;
@property (readonly, nonatomic) CGFloat conversationListMuteIndicatorToSummaryLabelPadding;
@property (readonly, nonatomic) Class conversationListNavigationControllerClass;
@property (readonly, nonatomic) CGFloat conversationListPinnedCellSelectedBackgroundCornerRadius;
@property (readonly, nonatomic) UIFont *conversationListPinnedConversationNameFont;
@property (readonly, nonatomic) CGFloat conversationListPinnedConversationPreviewFontSizeOverrideLarge;
@property (readonly, nonatomic) CGFloat conversationListPinnedConversationPreviewFontSizeOverrideStandard;
@property (readonly, nonatomic) NSUInteger conversationListScrollingBatchSize;
@property (readonly, nonatomic) NSUInteger conversationListScrollingPaddingRowCount;
@property (readonly, nonatomic) BOOL conversationListSearchBarSkipExtraAlignment;
@property (readonly, nonatomic) UIFont *conversationListSenderFont;
@property (readonly, nonatomic) CGFloat conversationListSummaryBodyLeading;
@property (readonly, nonatomic) UIFont *conversationListSummaryFont;
@property (readonly, nonatomic) CGFloat conversationListTableMarginWidth;
@property (readonly, nonatomic) Class conversationListTableViewClass;
@property (readonly, nonatomic) BOOL darkUIEnabled;
@property (readonly, nonatomic) UIEdgeInsets defaultAVPlayerViewContorllerControlsInsets;
@property (readonly, nonatomic) UIFont *defaultBalloonTextFont;
@property (readonly, nonatomic) NSUInteger defaultConversationLoadMoreCount;
@property (readonly, nonatomic) NSUInteger defaultConversationSummaryMessageCount;
@property (readonly, nonatomic) NSUInteger defaultConversationViewingMessageCount;
@property (readonly, nonatomic) UIImage *defaultWaveformImage;
@property (readonly, nonatomic) CGFloat detailsAvatarCornerRadius;
@property (readonly, nonatomic) CGFloat detailsAvatarCutoutDiameter;
@property (readonly, nonatomic) CGFloat detailsAvatarHeight;
@property (readonly, nonatomic) CGFloat detailsAvatarPancakeViewOverlapOffset;
@property (readonly, nonatomic) CGFloat detailsAvatarPancakeViewWidth2Avatars;
@property (readonly, nonatomic) CGFloat detailsAvatarPancakeViewWidth3Avatars;
@property (readonly, nonatomic) CGFloat detailsAvatarWidth;
@property (readonly, nonatomic) UIEdgeInsets detailsContactCellButtonEdgeInsets;
@property (readonly, nonatomic) CGFloat detailsContactCellButtonHeight;
@property (readonly, nonatomic) CGFloat detailsContactCellButtonWidth;
@property (readonly, nonatomic) CGFloat detailsContactCellMinimumHeight;
@property (readonly, nonatomic) CGFloat detailsExpanseActivityDescriptionVerticalPadding;
@property (readonly, nonatomic) CGFloat detailsExpanseActivityImageInsetPadding;
@property (readonly, nonatomic) CGFloat detailsExpanseCellHeight;
@property (readonly, nonatomic) CGFloat detailsExpanseDescriptionLabelHeight;
@property (readonly, nonatomic) CGFloat detailsExpanseImageFallbackDimension;
@property (readonly, nonatomic) CGFloat detailsExpanseScreenShareCellHeight;
@property (readonly, nonatomic) CGFloat detailsExpanseScreenShareIconHorizontalInsetPadding;
@property (readonly, nonatomic) CGFloat detailsExpanseScreenShareIconVerticalInsetPadding;
@property (readonly, nonatomic) CGFloat detailsGroupHeaderCellInterTextVerticalSpacing;
@property (readonly, nonatomic) CGFloat detailsGroupHeaderCellTextVerticalPadding;
@property (readonly, nonatomic) UIImage *detailsImage;
@property (readonly, nonatomic) NSUInteger detailsSectionCount;
@property (readonly, nonatomic) BOOL detailsSeperatorsFollowLayoutMargins;
@property (readonly, nonatomic) CGFloat detailsTUConversationCellButtonHeight;
@property (readonly, nonatomic) CGFloat detailsTUConversationCellButtonMinWidth;
@property (readonly, nonatomic) CGFloat detailsTUConversationDetailsSummaryImageDiameter;
@property (readonly, nonatomic) CGFloat detailsViewContactImageDiameter;
@property (readonly, nonatomic) UIImage *detailsViewFaceTimeVideoImage;
@property (readonly, nonatomic) CGFloat detailsViewMapHeight;
@property (readonly, nonatomic) UIImage *detailsViewMessagesImage;
@property (readonly, nonatomic) UIImage *detailsViewPhoneImage;
@property (readonly, nonatomic) BOOL disableTranscriptOrb;
@property (readonly, nonatomic) UIImage *disabledFacetimeAudioImage;
@property (readonly, nonatomic) UIImage *disabledFacetimeVideoImage;
@property (readonly, nonatomic) CGFloat dividerHeight;
@property (readonly, nonatomic) UIImage *dndActionImage; // ivar: _dndActionImage
@property (readonly, nonatomic) CGSize documentIconSize;
@property (readonly, nonatomic) UIFont *downloadButtonFont;
@property (readonly, nonatomic) CGFloat dragBalloonCornerRadius;
@property (readonly, nonatomic) CGFloat dragBalloonHeightReducedAttractorThreshold;
@property (readonly, nonatomic) CGFloat dragBalloonTailCropWidth;
@property (readonly, nonatomic) CGFloat dragBalloonWidthIncreasedAttractorThreshold;
@property (readonly, nonatomic) CGFloat dragEdgeLayoutIntentPadding;
@property (readonly, nonatomic) CGFloat dragPinchGestureScaleFactor;
@property (readonly, nonatomic) CGFloat dragTranscriptScrollDisplayLinkMaxDelta;
@property (readonly, nonatomic) CGFloat dragTranscriptScrollThreshold;
@property (readonly, nonatomic) NSDictionary *drawerTranscriptTextAttributes;
@property (readonly, nonatomic) CGFloat editingTransitionAnimationDuration;
@property (readonly, nonatomic) CGFloat emojiPreviewMaxWidth;
@property (readonly, nonatomic) BOOL enableBalloonTextSelection;
@property (readonly, nonatomic) UIImage *enabledExpanseImage;
@property (readonly, nonatomic) UIImage *enabledExpanseImagePill;
@property (readonly, nonatomic) UIImage *enabledFacetimeAudioImage;
@property (readonly, nonatomic) UIImage *enabledFacetimeAudioImagePill;
@property (readonly, nonatomic) UIImage *enabledFacetimeVideoImage;
@property (readonly, nonatomic) UIImage *enabledFacetimeVideoImagePill;
@property (readonly, nonatomic) CGFloat entryFieldCoverLineWidth;
@property (readonly, nonatomic) BOOL entryFieldShouldUseBackdropView;
@property (readonly, nonatomic) BOOL entryFieldShouldUseNewPhotoUI;
@property (readonly, nonatomic) NSString *entryViewAppButtonName;
@property (readonly, nonatomic) NSString *entryViewArrowButtonName;
@property (readonly, nonatomic) NSString *entryViewAudioButtonName;
@property (readonly, nonatomic) CGFloat entryViewBackgroundAlpha;
@property (readonly, nonatomic) CGFloat entryViewCoverMinHeight;
@property (readonly, nonatomic) UIEdgeInsets entryViewHorizontalCoverInsets;
@property (readonly, nonatomic) CGFloat entryViewMaxExtensionShelfHeight;
@property (readonly, nonatomic) CGFloat entryViewMaxHandWritingPluginShelfHeight;
@property (readonly, nonatomic) CGFloat entryViewMaxPluginShelfHeight;
@property (readonly, nonatomic) CGFloat entryViewMinPluginShelfHeight;
@property (readonly, nonatomic) NSString *entryViewPhotoButtonName;
@property (readonly, nonatomic) CGFloat entryViewSendButtonCoverSpace;
@property (readonly, nonatomic) NSString *entryViewSendButtonName;
@property (readonly, nonatomic) BOOL entryViewSupportsPhotoButton;
@property (readonly, nonatomic) UIEdgeInsets entryViewVerticalCoverInsets;
@property (readonly, nonatomic) CKMessageEntryViewLayoutMetrics *entryViewlayoutMetrics;
@property (readonly, nonatomic) UIImage *errorDocumentIcon;
@property (readonly, nonatomic) CGFloat extensionBalloonMaximumHeight;
@property (readonly, nonatomic) CGFloat extraLargeTranscriptSpace;
@property (readonly, nonatomic) CGFloat extraTallExtensionBalloonMaximumHeight;
@property (readonly, nonatomic) BOOL faceTimeAudioIsAllowlisted;
@property (readonly, nonatomic) BOOL faceTimeVideoIsAllowlisted;
@property (readonly, nonatomic) UIImage *facetimeAudioIcon;
@property (readonly, nonatomic) CGFloat fadeInBubbleAnimationDuration;
@property (readonly, nonatomic) UIFont *filterCellTitleFont;
@property (readonly, nonatomic) UIImage *forwardImage;
@property (readonly, nonatomic) UIImage *genericDocumentIcon;
@property (readonly, nonatomic) UIImage *grayA1AckImage;
@property (readonly, nonatomic) UIImage *grayA2AckImage;
@property (readonly, nonatomic) UIImage *grayExclamationLeftAckImage;
@property (readonly, nonatomic) UIImage *grayExclamationRightAckImage;
@property (readonly, nonatomic) UIImage *grayH1AckImage;
@property (readonly, nonatomic) UIImage *grayH2AckImage;
@property (readonly, nonatomic) UIImage *grayHaAckImage;
@property (readonly, nonatomic) UIImage *grayHeartAckImage;
@property (readonly, nonatomic) UIImage *grayQuestionMarkDotAckImage;
@property (readonly, nonatomic) UIImage *grayQuestionMarkGlyphAckImage;
@property (readonly, nonatomic) UIImage *grayThumbsDownAckImage;
@property (readonly, nonatomic) UIImage *grayThumbsUpAckImage;
@property (readonly, nonatomic) CGSize groupAvatarViewSize;
@property (readonly, nonatomic) BOOL handlesBalloonViewTitleTapsSeparately;
@property (readonly, nonatomic) UIImage *hawkingWarningIcon;
@property (readonly, nonatomic) UIImage *hawkingWarningIconRed;
@property (readonly, nonatomic) UIFont *headerFont;
@property (readonly, nonatomic) BOOL hidesUnreadIndicatorWhenEditing;
@property (readonly, nonatomic) CGFloat horizontalBalloonBadgeInset;
@property (readonly, nonatomic) BOOL hyphenatesTextContent;
@property (readonly, nonatomic) UIFont *iCloudTextFont;
@property (readonly, nonatomic) UIColor *imageBalloonSelectionOverlayColor;
@property (readonly, nonatomic) BOOL includeKeyboardInEntryViewHeight;
@property (readonly, nonatomic) NSUInteger initialConversationSizingMessageCount;
@property (readonly, nonatomic) NSUInteger initialConversationViewingMessageCount;
@property (readonly, nonatomic) BOOL isAccessibilityPreferredContentSizeCategory;
@property (readonly, nonatomic) BOOL isAppStripInKeyboard;
@property (readonly, nonatomic) BOOL isBrowserButtonAlwaysHighlighted;
@property (readonly, nonatomic) BOOL isEntryViewCollapsable;
@property (readonly, nonatomic) BOOL isMentionSuggestionViewInKeyboard;
@property (readonly, nonatomic) BOOL isProximityMonitoringSupported;
@property (readonly, nonatomic) BOOL isRunningInStoreDemoMode;
@property (readonly, nonatomic) BOOL isSendButtonEnabledOnPlatform;
@property (readonly, nonatomic) BOOL isSizeConstrained;
@property (readonly, nonatomic) BOOL isThreeColumnLayoutEnabled;
@property (readonly, nonatomic) BOOL joystickUsesWindow;
@property (readonly, nonatomic) UIEdgeInsets landscapeKeyboardInsets;
@property (readonly, nonatomic) CGFloat largeTextTopConversationListSpace;
@property (readonly, nonatomic) CGFloat largeTranscriptSpace;
@property (readonly, nonatomic) NSDictionary *leftStatusTranscriptTextAttributes;
@property (readonly, nonatomic) NSDictionary *leftTranscriptButtonTextAttributes;
@property (readonly, nonatomic) UIFont *locationBoldButtonFont;
@property (readonly, nonatomic) UIFont *locationButtonFont;
@property (readonly, nonatomic) NSDateFormatter *locationRelativeDateFormatter;
@property (readonly, nonatomic) UIImage *locationShareActionIcon;
@property (readonly, nonatomic) CGFloat locationShareBalloonButtonCharge;
@property (readonly, nonatomic) CGFloat locationShareBalloonButtonHeight;
@property (readonly, nonatomic) CGFloat locationShareBalloonContactImageDiameter;
@property (readonly, nonatomic) CGFloat locationShareBalloonLabelPadding;
@property (readonly, nonatomic) CGFloat locationShareBalloonMaxVisibleMapHeight;
@property (readonly, nonatomic) NSInteger locationShareEODHour;
@property (readonly, nonatomic) CGFloat locationShareOneHourTimeInterval;
@property (readonly, nonatomic) UIFont *locationSubtitleFont;
@property (readonly, nonatomic) CGFloat locationValidInterval;
@property (readonly, nonatomic) BOOL lowClearanceInLandscape;
@property (readonly, nonatomic) BOOL mailIsAllowlisted;
@property (readonly, nonatomic) CGFloat mapPreviewMaxWidth;
@property (readonly, nonatomic) CGFloat maxAudioRecordingDuration;
@property (readonly, nonatomic) CGFloat maxConversationListWidth;
@property (readonly, nonatomic) CGFloat maxNavigationBarCollapsedHeightValue;
@property (readonly, nonatomic) CGFloat maxNavigationBarExpandedHeightValue;
@property (readonly, nonatomic) CGFloat maxNavigationBarHeightValue;
@property (readonly, nonatomic) CGFloat maxNavigationBarNoContactPhotoCollapsedHeightValue;
@property (readonly, nonatomic) CGFloat maxNavigationBarNoContactPhotoExpandedHeightValue;
@property (readonly, nonatomic) NSInteger maxNumExtensionRemoteViewControllers;
@property (readonly, nonatomic) NSUInteger maxNumLiveBrowserViewsToKeepInViewHierarchy;
@property (readonly, nonatomic) NSUInteger maxNumberOfItemsPerAppDrawerPage;
@property (readonly, nonatomic) CGFloat maxPrimaryColumnWidth;
@property (readonly, nonatomic) CGFloat maxTranscriptPortraitHeight;
@property (readonly, nonatomic) CGFloat maxTranscriptPortraitWidth;
@property (readonly, nonatomic) NSUInteger maximumNumberOfPinnedConversations;
@property (readonly, nonatomic) CGFloat mediumTranscriptSpace;
@property (readonly, nonatomic) UIFont *mentionsCellNameFont;
@property (readonly, nonatomic) CGFloat messageAcknowledgementVotingViewHeight;
@property (readonly, nonatomic) CGFloat messageAcknowledgementVotingViewMaxWidth;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarAcknowledgmentImageSize;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarAcknowledgmentItemBalloonSize;
@property (readonly, nonatomic) NSArray *messageAcknowledgmentPickerBarAcknowledgmentOrder;
@property (readonly, nonatomic) UIImage *messageAcknowledgmentPickerBarBubbleImage;
@property (readonly, nonatomic) NSString *messageAcknowledgmentPickerBarBubbleName;
@property (readonly, nonatomic) CGPoint messageAcknowledgmentPickerBarBubbleStartingOrigin;
@property (readonly, nonatomic) NSString *messageAcknowledgmentPickerBarBubbleTailName;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarBubbleTailSize;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarItemViewSize;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarOffsetFromBalloon;
@property (readonly, nonatomic) CGPoint messageAcknowledgmentPickerBarRelativePosition;
@property (readonly, nonatomic) CGSize messageAcknowledgmentPickerBarSize;
@property (readonly, nonatomic) CGPoint messageAcknowledgmentTranscriptBalloonRelativePosition;
@property (readonly, nonatomic) CGSize messageAcknowledgmentTranscriptBalloonSize;
@property (readonly, nonatomic) UIEdgeInsets messageAcknowledgmentTranscriptGlyphInset;
@property (readonly, nonatomic) CGPoint messageAcknowledgmentTranscriptOrganicBalloonAdditionalOffset;
@property (readonly, nonatomic) UIFont *messageAcknowledgmentVoteCountFont;
@property (readonly, nonatomic) CGSize messageAcknowledgmentVotingAvatarSize;
@property (readonly, nonatomic) NSUInteger messageAcknowledgmentVotingStackSize;
@property (readonly, nonatomic) NSUInteger messageCountToLoadForPinnedGroupConversationWithPhoto;
@property (readonly, nonatomic) CGFloat messageHighlightButtonGlyphPointSize; // ivar: _messageHighlightButtonGlyphPointSize
@property (readonly, nonatomic) CGFloat messageHighlightButtonGlyphSymbolPointSize;
@property (readonly, nonatomic) UIImage *messageHighlightButtonImageHighlightOff;
@property (readonly, nonatomic) UIImage *messageHighlightButtonImageHighlightOn;
@property (readonly, nonatomic) UIEdgeInsets messageHighlightButtonInsets;
@property (readonly, nonatomic) CGPoint messageHighlightButtonRelativePositionToTranscriptMessageBalloon;
@property (readonly, nonatomic) UIColor *messageHighlightButtonSelectedBackgroundColor;
@property (readonly, nonatomic) UIColor *messageHighlightButtonUnselectedBackgroundColor;
@property (readonly, nonatomic) CGSize messageHighlightButtonVisibleViewSize;
@property (readonly, nonatomic) UIColor *messageHighlightGlyphColor;
@property (readonly, nonatomic) CGFloat messageHighlightGlyphSymbolPointSize;
@property (readonly, nonatomic) UIColor *messageHighlightGoldColor;
@property (readonly, nonatomic) UIImage *messageHighlightImage;
@property (readonly, nonatomic) CGFloat messageHighlightTranscriptBalloonBorderWidth;
@property (readonly, nonatomic) CGFloat messageHighlightTranscriptBalloonBottomPadding;
@property (readonly, nonatomic) CGPoint messageHighlightTranscriptBalloonRelativePosition;
@property (readonly, nonatomic) CGSize messageHighlightTranscriptBalloonSize;
@property (readonly, nonatomic) UIImage *messageReplyImage; // ivar: _messageReplyImage
@property (readonly, nonatomic) CGFloat minAudioRecordingDuration;
@property (readonly, nonatomic) CGFloat minConversationListWidth;
@property (readonly, nonatomic) CGFloat minNavigationBarHeightValue;
@property (readonly, nonatomic) CGFloat minPrimaryColumnWidth;
@property (readonly, nonatomic) UIEdgeInsets minTranscriptMarginInsets;
@property (readonly, nonatomic) CGFloat minTranscriptSpace;
@property (readonly, nonatomic) UIEdgeInsets minimumPlayButtonInsets;
@property (readonly, nonatomic) UIImage *muteButtonImage;
@property (readonly, nonatomic) CGFloat muteEightHourTimeInterval;
@property (readonly, nonatomic) CGFloat muteOneHourTimeInterval;
@property (readonly, nonatomic) UIFont *nameFieldFont;
@property (readonly, nonatomic) CGFloat nanoNoteSenderContentSpace;
@property (readonly, nonatomic) UIImage *navBarAudioFillImage;
@property (readonly, nonatomic) UIImage *navBarAudioImage;
@property (readonly, nonatomic) UIImage *navBarHeaderAudioImage;
@property (readonly, nonatomic) UIImage *navBarHeaderChevronImage;
@property (readonly, nonatomic) UIImage *navBarHeaderChevronImageNoAvatar;
@property (readonly, nonatomic) UIImage *navBarHeaderExpanseImage;
@property (readonly, nonatomic) UIImage *navBarHeaderVideoImage;
@property (readonly, nonatomic) UIImage *navBarInfoImage;
@property (readonly, nonatomic) NSString *navBarInfoImageName;
@property (readonly, nonatomic) UIFont *navBarUnifiedCallButtonJoinTextFont;
@property (readonly, nonatomic) UIImage *navBarVideoFillImage;
@property (readonly, nonatomic) UIImage *navBarVideoImage;
@property (readonly, nonatomic) CGFloat navbarButtonImagePointSize;
@property (readonly, nonatomic) UIFont *navbarDefaultLabelFont;
@property (readonly, nonatomic) UIImage *navbarJoinPillAudioImage;
@property (readonly, nonatomic) UIImage *navbarJoinPillVideoImage;
@property (readonly, nonatomic) UIFont *navbarToLabelFont;
@property (readonly, nonatomic) CGFloat navigationBarBackButtonMargin;
@property (readonly, nonatomic) Class navigationBarClass;
@property (readonly, nonatomic) CGFloat navigationBarHeaderButtonVerticalOffset;
@property (readonly, nonatomic) CGFloat navigationBarLeftItemVerticalCenterOffset;
@property (readonly, nonatomic) CGFloat navigationBarMaxHeight;
@property (readonly, nonatomic) CGFloat navigationBarMinHeight;
@property (readonly, nonatomic) CGFloat navigationBarTitleViewHeightWithContactPhoto;
@property (readonly, nonatomic) CGFloat navigationBarTitleViewVerticalOffset;
@property (readonly, nonatomic) UIFont *navigationHeaderJoinLabelFont;
@property (readonly, nonatomic) UIImage *newComposeImage;
@property (readonly, nonatomic) NSDictionary *nickNameTranscriptTextAttributes;
@property (readonly, nonatomic) UIFont *nicknameDescriptionFont;
@property (readonly, nonatomic) UIFont *nicknameLabelFont;
@property (readonly, nonatomic) UIFont *nicknameUpdatesSubtitleFont;
@property (readonly, nonatomic) UIFont *nicknameUpdatesTitleFont;
@property (readonly, nonatomic) UIFont *noAvatarTitleFont;
@property (readonly, nonatomic) CGFloat notifyAnywayBottomTranscriptSpace;
@property (readonly, nonatomic) NSUInteger numberOfAssetsInPhotoPicker;
@property (readonly, nonatomic) NSUInteger numberOfButtonsInPhotoPicker;
@property (readonly, nonatomic) BOOL opensLocationsInMapsApp;
@property (readonly, nonatomic) UIImage *optionsImage;
@property (readonly, nonatomic) CGFloat paddleDividerInset;
@property (readonly, nonatomic) CGFloat paddleOvelayRadius;
@property (readonly, nonatomic) UIEdgeInsets phishingWarningEdgeInsets;
@property (readonly, nonatomic) NSDictionary *phishingWarningTextAttributes;
@property (readonly, nonatomic) BOOL phoneIsAllowlisted;
@property (readonly, nonatomic) UIImage *photoPickerDisabledBadge;
@property (readonly, nonatomic) CGFloat photoPickerInterItemSpacing;
@property (readonly, nonatomic) CGFloat photoPickerMaxPhotoHeight;
@property (readonly, nonatomic) UIImage *photoPickerOffBadge;
@property (readonly, nonatomic) UIImage *photoPickerOnBadge;
@property (readonly, nonatomic) CGFloat photoPickerPopoverWidth;
@property (readonly, nonatomic) UIEdgeInsets photoPickerSectionInsets;
@property (readonly, nonatomic) BOOL photoPickerShouldZoomOnSelection;
@property (readonly, nonatomic) BOOL photoPickerUsesVitality;
@property (readonly, nonatomic) CGSize photoSheetProgressIndicatorSize;
@property (readonly, nonatomic) CGFloat photoSheetVideoIconPadding;
@property (readonly, nonatomic) BOOL photosIsAllowlisted;
@property (readonly, nonatomic) UIImage *pinnedAdHocConversationRadiantShadowImage;
@property (readonly, nonatomic) CGSize pinnedConversationActivityBroadShadowDarkOffset;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityBroadShadowDarkOpacity;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityBroadShadowDarkRadius;
@property (readonly, nonatomic) CGSize pinnedConversationActivityBroadShadowLightOffset;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityBroadShadowLightOpacity;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityBroadShadowLightRadius;
@property (readonly, nonatomic) CGSize pinnedConversationActivityTightShadowDarkOffset;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityTightShadowDarkOpacity;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityTightShadowDarkRadius;
@property (readonly, nonatomic) CGSize pinnedConversationActivityTightShadowLightOffset;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityTightShadowLightOpacity;
@property (readonly, nonatomic) CGFloat pinnedConversationActivityTightShadowLightRadius;
@property (readonly, nonatomic) CGFloat pinnedConversationViewTitleLabelToEdgePaddingWhenNoUnreadIndicator;
@property (readonly, nonatomic) UIFont *pinningOnboardingSubtitleLabelFont;
@property (readonly, nonatomic) UIImage *playButtonArrowImage;
@property (readonly, nonatomic) NSInteger playButtonBackdropStyle;
@property (readonly, nonatomic) UIImage *playButtonImage;
@property (readonly, nonatomic) BOOL playButtonPunchesOutArrow;
@property (readonly, nonatomic) BOOL playsInlineVideo;
@property (readonly, nonatomic) BOOL presentForwardingUIModally;
@property (readonly, nonatomic) CGFloat presentationControllerWindowLevel;
@property (readonly, nonatomic) BOOL presentsAutocompleteInAPopover;
@property (readonly, nonatomic) BOOL presentsFullscreenInViewService;
@property (readonly, nonatomic) BOOL presentsQuickLookController;
@property (readonly, nonatomic) CGFloat previewMaxWidth;
@property (readonly, nonatomic) CGFloat previewTitleBarHeight;
@property (readonly, nonatomic) UIFont *previewTitleFont;
@property (readonly, nonatomic) CGFloat progressThresholdForTitleUpdateAnimation;
@property (readonly, nonatomic) BOOL promptsForReadReceiptsSetting;
@property (readonly, nonatomic) CGFloat psMode1;
@property (readonly, nonatomic) CGFloat psMode2;
@property (readonly, nonatomic) CGFloat psMode3;
@property (readonly, nonatomic) UIImage *quickSaveButtonImage;
@property (readonly, nonatomic) UIEdgeInsets quickSaveButtonImageInsets;
@property (readonly, nonatomic) CGFloat raiseToTalkAutoSendMaxDuration;
@property (readonly, nonatomic) CGFloat raiseToTalkErrorMaxDuration;
@property (readonly, nonatomic) UIImage *readDNDImage;
@property (readonly, nonatomic) UIFont *readerFont;
@property (readonly, nonatomic) UIFont *recipientNameFont;
@property (readonly, nonatomic) BOOL recordsRecentContact;
@property (readonly, nonatomic) UIImage *redHeartAckImage;
@property (readonly, nonatomic) UIImage *replayImage;
@property (readonly, nonatomic) NSInteger replyBalloonMaximumNumberOfLines;
@property (readonly, nonatomic) UIEdgeInsets replyBalloonTextContainerInset;
@property (readonly, nonatomic) UIFont *replyBalloonTextFont;
@property (readonly, nonatomic) CGFloat replyButtonAnimationDuration;
@property (readonly, nonatomic) CGFloat replyButtonBackgroundBlurRadius;
@property (readonly, nonatomic) CGFloat replyButtonBorderWidth;
@property (readonly, nonatomic) UIEdgeInsets replyButtonEdgeInsets;
@property (readonly, nonatomic) UIFont *replyButtonFont;
@property (readonly, nonatomic) CGFloat replyButtonHorizontalOriginOffsetPercent;
@property (readonly, nonatomic) CGFloat replyButtonPadding;
@property (readonly, nonatomic) CGPoint replyButtonRelativePosition;
@property (readonly, nonatomic) CGFloat replyButtonTouchAlpha;
@property (readonly, nonatomic) CGFloat replyButtonTouchScale;
@property (readonly, nonatomic) CGFloat replyButtonVerticalOriginOffsetPercent;
@property (readonly, nonatomic) CGFloat replyEntryViewBackagroundAlpha;
@property (readonly, nonatomic) CGFloat replyLineBracketRadius;
@property (readonly, nonatomic) CGFloat replyLineViewHorizontalPadding;
@property (readonly, nonatomic) CGFloat replyLineViewVerticalPadding;
@property (readonly, nonatomic) CGFloat replyLineWidth;
@property (readonly, nonatomic) CGFloat replyPreviewBalloonAlpha;
@property (readonly, nonatomic) CGFloat replyPreviewBalloonMinWidth;
@property (readonly, nonatomic) NSString *replyPreviewContactIconName;
@property (readonly, nonatomic) NSString *replyPreviewDocumentIconName;
@property (readonly, nonatomic) CGFloat replyPreviewImageDiameter;
@property (readonly, nonatomic) NSString *replyPreviewLocationIconName;
@property (readonly, nonatomic) UIEdgeInsets replySenderTranscriptInsets;
@property (readonly, nonatomic) NSDictionary *replySenderTranscriptTextAttributes;
@property (readonly, nonatomic) CGFloat replyTranscriptBackgroundBlurAnimationTime;
@property (readonly, nonatomic) CGFloat replyTranscriptBackgroundBlurRadius;
@property (readonly, nonatomic) CGFloat replyTranscriptUpdateBannerAnimateInTime;
@property (readonly, nonatomic) CGFloat replyTranscriptUpdateBannerAnimateOutTime;
@property (readonly, nonatomic) BOOL resetsIdleTimer;
@property (readonly, nonatomic) CGFloat resizeMessageEntryViewAnimationDuration;
@property (readonly, nonatomic) CGFloat resumeToConversationListTimeInterval;
@property (readonly, nonatomic) NSDictionary *rightStatusTranscriptTextAttributes;
@property (readonly, nonatomic) NSDictionary *rightTranscriptButtonTextAttributes;
@property (readonly, nonatomic) UIImage *screenTimeConversationListSummaryIcon;
@property (readonly, nonatomic) CGFloat scrollInNewMessageAnimationDuration;
@property (readonly, nonatomic) BOOL scrollToBottomStopsAtTopOfLastBubble;
@property (readonly, nonatomic) CGFloat searchAttachmentsCellCornerRadius;
@property (readonly, nonatomic) CGFloat searchAttachmentsInterItemSpacing;
@property (readonly, nonatomic) CGFloat searchConversationMinAvatarLabelSpacing;
@property (readonly, nonatomic) UIFont *searchDetailsHeaderFont;
@property (readonly, nonatomic) UIFont *searchDetailsHeaderFontIdentity;
@property (readonly, nonatomic) UIFont *searchDetailsSubHeaderFont; // ivar: _searchDetailsSubHeaderFont
@property (readonly, nonatomic) UIFont *searchHeaderButtonFont;
@property (readonly, nonatomic) UIFont *searchHeaderFont;
@property (readonly, nonatomic) CGFloat searchHeaderHeight;
@property (readonly, nonatomic) CGFloat searchHighlightsInterItemSpacing;
@property (readonly, nonatomic) UIFont *searchIndexingSubtitleFont;
@property (readonly, nonatomic) UIFont *searchIndexingTitleFont;
@property (readonly, nonatomic) CGFloat searchLeadingAndTrailingMaxPadding;
@property (readonly, nonatomic) CGFloat searchLinksCellCornerRadius;
@property (readonly, nonatomic) CGFloat searchLinksInterItemSpacing;
@property (readonly, nonatomic) CGFloat searchLinksThumbnailWidth;
@property (readonly, nonatomic) CGFloat searchLocationCellCornerRadius;
@property (readonly, nonatomic) CGFloat searchLocationsInterItemSpacing;
@property (readonly, nonatomic) CGFloat searchPhotosCellCornerRadius;
@property (readonly, nonatomic) CGFloat searchPhotosCellZKWAndDetailsCornerRadius;
@property (readonly, nonatomic) CGFloat searchPhotosInterItemSpacing;
@property (readonly, nonatomic) CGFloat searchPhotosInterItemSpacingDetailsView;
@property (readonly, nonatomic) CGFloat searchPhotosThumbnailWidth;
@property (readonly, nonatomic) CGFloat searchPhotosZKWAndDetailsInterItemSpacing;
@property (readonly, nonatomic) UIFont *searchResultLabelBoldFont;
@property (readonly, nonatomic) UIFont *searchResultLabelFont;
@property (readonly, nonatomic) UIEdgeInsets searchSectionInsets;
@property (readonly, nonatomic) UIEdgeInsets searchSectionMarginInsets;
@property (readonly, nonatomic) CGFloat searchSectionTitleVertPadding;
@property (readonly, nonatomic) BOOL selectNewConversationOnDeletion;
@property (readonly, nonatomic) BOOL selectNewConversationOnStateRestore;
@property (readonly, nonatomic) CGFloat sendAnimationDuration;
@property (readonly, nonatomic) CGFloat sendButtonSize;
@property (readonly, nonatomic) CGFloat sendProgressTitleTransitionProgressThreshold;
@property (readonly, nonatomic) CGFloat senderSummaryConversationListSpace;
@property (readonly, nonatomic) UIEdgeInsets senderTranscriptInsets;
@property (readonly, nonatomic) NSDictionary *senderTranscriptTextAttributes;
@property (readonly, nonatomic) BOOL shouldAdjustWidthForSendFailure;
@property (readonly, nonatomic) BOOL shouldAlignRecipientGlyphsWithMargins;
@property (readonly, nonatomic) BOOL shouldAnimateGifsInPhotoGrid;
@property (readonly, nonatomic) BOOL shouldAutomaticallyCheckAvailabilityOfAlternateAddresses;
@property (readonly, nonatomic) BOOL shouldBackfillTranscript;
@property (readonly, nonatomic) BOOL shouldDisableFocusRing;
@property (readonly, nonatomic) BOOL shouldDisableSendButtonClickInteraction;
@property (readonly, nonatomic) BOOL shouldFillAndStrokeAttachmentBalloon;
@property (readonly, nonatomic) BOOL shouldGrabBackgroundAssertion;
@property (readonly, nonatomic) BOOL shouldHideStatusBarForFullScreenEffects;
@property (readonly, nonatomic) BOOL shouldHomogenizeAtomsForPreferredService;
@property (readonly, nonatomic) BOOL shouldInsetForStatusBar;
@property (readonly, nonatomic) BOOL shouldLoadInitialViewingMessageCount;
@property (readonly, nonatomic) BOOL shouldOnlyResumeToConversationListAfterTimeout;
@property (readonly, nonatomic) BOOL shouldPopoverSuggestionsBanner;
@property (readonly, nonatomic) BOOL shouldRefreshAlternateAddressesSheet;
@property (readonly, nonatomic) BOOL shouldShowContactPhotosInTranscript;
@property (readonly, nonatomic) BOOL shouldShowDisclosureChevronInRecipientAtoms;
@property (readonly, nonatomic) BOOL shouldShowSearchBarInConversationList;
@property (readonly, nonatomic) BOOL shouldSizeInitialViewingMessageCount;
@property (readonly, nonatomic) BOOL shouldSuppressDynamicsOnKeyboardPresentation;
@property (readonly, nonatomic) BOOL shouldSuppressRotationInNewCompose;
@property (readonly, nonatomic) BOOL shouldUseDynamicGradient;
@property (readonly, nonatomic) BOOL shouldUseDynamicScrolling;
@property (readonly, nonatomic) BOOL shouldUseRotisserieScrolling;
@property (readonly, nonatomic) BOOL shouldUseSendAnimation;
@property (readonly, nonatomic) BOOL shouldUseTranslucentBars;
@property (readonly, nonatomic) BOOL showMMSSetup;
@property (readonly, nonatomic) BOOL showPendingInConversationList;
@property (readonly, nonatomic) BOOL showsBalloonBadges;
@property (readonly, nonatomic) BOOL showsBalloonChevron;
@property (readonly, nonatomic) BOOL showsCompositionPanel;
@property (readonly, nonatomic) BOOL showsConversationListCellChevronImage;
@property (readonly, nonatomic) BOOL showsFileSizeInSubtitle;
@property (readonly, nonatomic) BOOL showsHoverToDeleteButton;
@property (readonly, nonatomic) BOOL showsHoverToDeleteButtonForNewCompose;
@property (readonly, nonatomic) BOOL showsLoadMoreItem;
@property (readonly, nonatomic) BOOL showsNoMessagesDialog;
@property (readonly, nonatomic) BOOL showsPlaceCardForBalloonViewTitleTap;
@property (readonly, nonatomic) BOOL showsProgressInNavigationBar;
@property (readonly, nonatomic) BOOL showsReplyButtonsInTranscript;
@property (readonly, nonatomic) BOOL showsSendAnimation;
@property (readonly, nonatomic) BOOL showsVCalViewer;
@property (readonly, nonatomic) NSString *skinnyBalloonName;
@property (readonly, nonatomic) CGFloat skinnyBalloonWidthDifference;
@property (readonly, nonatomic) NSString *skinnyTaillessBalloonName;
@property (readonly, nonatomic) CGFloat smallTranscriptSpace;
@property (readonly, nonatomic) CGFloat stackBalloonVerticalInset;
@property (readonly, nonatomic) UIEdgeInsets stampTranscriptInsets;
@property (readonly, nonatomic) NSAttributedString *statusSaveButtonTranscriptText;
@property (readonly, nonatomic) CGSize statusSaveButtonTranscriptTextSize;
@property (readonly, nonatomic) UIFont *stickerDetailsSenderFont;
@property (readonly, nonatomic) UIFont *stickerDetailsStickerPackFont;
@property (readonly, nonatomic) UIFont *stickerDetailsTimestampFont;
@property (readonly, nonatomic) UIFont *stickerDetailsTitleFont;
@property (readonly, nonatomic) NSUInteger stickerScreenScale;
@property (readonly, nonatomic) NSString *strokedBalloonName;
@property (readonly, nonatomic) NSString *strokedTaillessBalloonName;
@property (readonly, nonatomic) NSUInteger suggestedAppStripLimit;
@property (readonly, nonatomic) NSUInteger suggestedMinimumRecentsCount;
@property (readonly, nonatomic) CGFloat summaryDateConversationListSpace;
@property (readonly, nonatomic) NSUInteger supportedInterfaceOrientations;
@property (readonly, nonatomic) BOOL supportsContiguousAttachments;
@property (readonly, nonatomic) BOOL supportsConversationListEditing;
@property (readonly, nonatomic) BOOL supportsOrbPreviewsInConversationList;
@property (readonly, nonatomic) BOOL supportsPassbookAttachments;
@property (readonly, nonatomic) BOOL supportsTypingIndicatorAnimation;
@property (readonly, nonatomic) UIFont *syncProgressLabelFont;
@property (readonly, nonatomic) *__CFCharacterSet systemUIFontExcessiveLineHeightCharacterSet;
@property (readonly, nonatomic) CGFloat system_checkmarkHorizontalPadding;
@property (readonly, nonatomic) NSString *taillessBallonName;
@property (readonly, nonatomic) CGFloat textAlignmentRectInsetsScaleFactor;
@property (readonly, nonatomic) CGFloat textBalloonMinHeight;
@property (readonly, nonatomic) UIImage *textDocumentIcon;
@property (readonly, nonatomic) UIEdgeInsets textReplyPreviewBalloonAlignmentRectInsets;
@property (readonly, nonatomic) CGFloat textReplyPreviewBalloonMinHeight;
@property (readonly, nonatomic) CKUITheme *theme;
@property (readonly, nonatomic) CGFloat throwMessageAnimationDuration;
@property (readonly, nonatomic) NSDateFormatter *timestampDateFormatter;
@property (readonly, nonatomic) BOOL timestampsPushBalloons;
@property (readonly, nonatomic) CGFloat toFieldInterItemSpacing; // ivar: _toFieldInterItemSpacing
@property (readonly, nonatomic) UIEdgeInsets toFieldScrollViewInsets;
@property (readonly, nonatomic) CGFloat toFieldXOffset; // ivar: _toFieldXOffset
@property (readonly, nonatomic) CGFloat toFieldYOffset; // ivar: _toFieldYOffset
@property (readonly, nonatomic) CGFloat topConversationListSpace;
@property (readonly, nonatomic) CGFloat topTranscriptSpace;
@property (readonly, nonatomic) NSDictionary *transcriptAvailabilityDeemphasizedFontAttributes;
@property (readonly, nonatomic) UIFont *transcriptAvailabilityFont;
@property (readonly, nonatomic) NSDictionary *transcriptAvailabilityFontAttributes;
@property (readonly, nonatomic) UIFont *transcriptBodyBoldTextFont;
@property (readonly, nonatomic) UIFont *transcriptBoldFont;
@property (readonly, nonatomic) UIEdgeInsets transcriptBoldTextAlignmentInsets;
@property (readonly, nonatomic) CGFloat transcriptBoldTextHeight;
@property (readonly, nonatomic) CGFloat transcriptButtonCharge;
@property (readonly, nonatomic) UIEdgeInsets transcriptButtonContentEdgeInsets;
@property (readonly, nonatomic) BOOL transcriptCanUseOpaqueMask;
@property (readonly, nonatomic) Class transcriptCollectionViewControllerClass;
@property (readonly, nonatomic) CGFloat transcriptContactImageDiameter;
@property (readonly, nonatomic) CGSize transcriptCustomStatusImageDefaultSize;
@property (readonly, nonatomic) UIEdgeInsets transcriptCustomStatusImageEdgeInsets;
@property (readonly, nonatomic) CGFloat transcriptCustomStatusImagePadding;
@property (readonly, nonatomic) CGFloat transcriptDrawerContactImageDiameter;
@property (readonly, nonatomic) CGFloat transcriptDrawerContactImagePadding;
@property (readonly, nonatomic) CGFloat transcriptDrawerGestureAcceleration;
@property (readonly, nonatomic) NSDictionary *transcriptEmphasizedFontAttributes;
@property (readonly, nonatomic) CGFloat transcriptHeaderChevronRotationAnimationSpeed;
@property (readonly, nonatomic) CGFloat transcriptHeaderViewMaxRows;
@property (readonly, nonatomic) UIFont *transcriptJunkHeaderButtonFont;
@property (readonly, nonatomic) CGFloat transcriptJunkHeaderButtonHeight;
@property (readonly, nonatomic) UIFont *transcriptJunkHeaderTitleFont;
@property (readonly, nonatomic) NSInteger transcriptLoadingIndicatorStyle;
@property (readonly, nonatomic) UIFont *transcriptLoadingViewTextFont;
@property (readonly, nonatomic) UIFont *transcriptMessageStatusDateFont;
@property (readonly, nonatomic) UIFont *transcriptMessageStatusFont;
@property (readonly, nonatomic) BOOL transcriptMinBottomInsetIsEntryViewHeight;
@property (readonly, nonatomic) UIFont *transcriptNotifyAnywayFont;
@property (readonly, nonatomic) NSDictionary *transcriptNotifyAnywayFontAttributes;
@property (readonly, nonatomic) CGFloat transcriptQuickSaveButtonDiameter;
@property (readonly, nonatomic) CGFloat transcriptQuickSaveButtonHorizontalSpacing;
@property (readonly, nonatomic) UIFont *transcriptRegularFont;
@property (readonly, nonatomic) NSDictionary *transcriptRegularFontAttributes;
@property (readonly, nonatomic) CGFloat transcriptReplyPreviewContextContactAlpha;
@property (readonly, nonatomic) CGFloat transcriptReplyPreviewContextContactImageDiameter;
@property (readonly, nonatomic) CGFloat transcriptResortTimeout;
@property (readonly, nonatomic) CGFloat transcriptScrollToBottomDuration;
@property (readonly, nonatomic) CGFloat transcriptScrollToBottomThreshold;
@property (readonly, nonatomic) UIFont *transcriptTextFont;
@property (readonly, nonatomic) UIEdgeInsets transcriptTextFontLanguageAwareOutsets;
@property (readonly, nonatomic) UIImage *trashImage;
@property (readonly, nonatomic) UIFont *tuConversationBalloonActionButtonFont;
@property (readonly, nonatomic) NSString *tuConversationBalloonActionButtonFontStyle;
@property (readonly, nonatomic) CGSize tuConversationBalloonActivityImageViewSize; // ivar: _tuConversationBalloonActivityImageViewSize
@property (readonly, nonatomic) CGFloat tuConversationBalloonAvatarDimensions;
@property (readonly, nonatomic) CGSize tuConversationBalloonButtonAsIconSize;
@property (readonly, nonatomic) CGFloat tuConversationBalloonButtonInteritemSpacing;
@property (readonly, nonatomic) CGFloat tuConversationBalloonButtonTitleHorizontalSpacing;
@property (readonly, nonatomic) CGFloat tuConversationBalloonButtonTitleMaxStringWidth;
@property (readonly, nonatomic) CGFloat tuConversationBalloonButtonTitleVerticalSpacing;
@property (readonly, nonatomic) CGFloat tuConversationBalloonCornerRadius;
@property (readonly, nonatomic) UIEdgeInsets tuConversationBalloonEdgeInsets;
@property (readonly, nonatomic) CGFloat tuConversationBalloonFaceTimeIconDimensions;
@property (readonly, nonatomic) CGFloat tuConversationBalloonIconDimensions;
@property (readonly, nonatomic) CGFloat tuConversationBalloonImageDimensions;
@property (readonly, nonatomic) CGFloat tuConversationBalloonInsetPadding;
@property (readonly, nonatomic) CGFloat tuConversationBalloonInteritemSpacing;
@property (readonly, nonatomic) CGFloat tuConversationBalloonJoinButtonHeight;
@property (readonly, nonatomic) CGFloat tuConversationBalloonJoinButtonMaxWidthPercentage;
@property (readonly, nonatomic) CGFloat tuConversationBalloonJoinButtonMinWidth;
@property (readonly, nonatomic) CGFloat tuConversationBalloonScreenShareDeviceIconSize;
@property (readonly, nonatomic) CGFloat tuConversationBalloonScreenShareImageViewDimensions;
@property (readonly, nonatomic) CGSize tuConversationBalloonScreenSharingImageViewSize; // ivar: _tuConversationBalloonScreenSharingImageViewSize
@property (readonly, nonatomic) UIFont *tuConversationBalloonSubtitleFont;
@property (readonly, nonatomic) UIFont *tuConversationBalloonTitleFont;
@property (readonly, nonatomic) CGFloat tuConversationBalloonTwoLineVerticalPadding;
@property (readonly, nonatomic) CGFloat tuConversationButtonInteritemSpacing;
@property (readonly, nonatomic) CGFloat tuConversationButtonTitleHorizontalSpacing;
@property (readonly, nonatomic) CGFloat tuConversationButtonTitleVerticalSpacing;
@property (readonly, nonatomic) CGFloat tuConversationIconPointSize;
@property (readonly, nonatomic) CGFloat tuConversationInsetPadding;
@property (readonly, nonatomic) CGFloat tuConversationInteritemSpacing;
@property (readonly, nonatomic) CGFloat tuConversationJoinButtonCornerRadius;
@property (readonly, nonatomic) CGFloat tuConversationJoinButtonHeight;
@property (readonly, nonatomic) CGFloat tuConversationJoinButtonMinWidth;
@property (readonly, nonatomic) UIFont *tuConversationViewActionButtonFont;
@property (readonly, nonatomic) UIImage *unDNDActionImage; // ivar: _unDNDActionImage
@property (readonly, nonatomic) CGFloat unavailabilityIndicatorBottomTranscriptSpace;
@property (readonly, nonatomic) UIImage *unavailabilityIndicatorDeemphasizedIcon;
@property (readonly, nonatomic) UIImage *unavailabilityIndicatorIcon;
@property (readonly, nonatomic) UIImage *unmuteButtonImage;
@property (readonly, nonatomic) UIImage *unreadDNDImage;
@property (readonly, nonatomic) UIImage *unreadImage;
@property (readonly, nonatomic) CGSize unreadIndicatorImageViewSize;
@property (readonly, nonatomic) UIImage *unreadIndicatorMutedImage;
@property (readonly, nonatomic) CGFloat updateTranscriptInsetsAnimationDuration;
@property (readonly, nonatomic) BOOL useMacToolbar;
@property (readonly, nonatomic) BOOL useSingleLineForContactVCardNames;
@property (readonly, nonatomic) BOOL usesActionMenu;
@property (readonly, nonatomic) BOOL usesDataDetectorsUI;
@property (readonly, nonatomic) BOOL usesEntryView;
@property (readonly, nonatomic) BOOL usesNavigationBarControls;
@property (readonly, nonatomic) BOOL usesPersistentConversationSelection;
@property (readonly, nonatomic) BOOL usesPopovers;
@property (readonly, nonatomic) BOOL usesUncollapsedSplitview;
@property (readonly, nonatomic) CGFloat verticalBalloonBadgeInset;
@property (readonly, nonatomic) CGFloat videoControllerWindowLevel;
@property (readonly, nonatomic) NSUInteger waveformGapWidth;
@property (readonly, nonatomic) CGFloat waveformHeight;
@property (readonly, nonatomic) NSUInteger waveformMaxPowerLevelsCount;
@property (readonly, nonatomic) CGFloat waveformMaxWidth; // ivar: _waveformMaxWidth
@property (readonly, nonatomic) CGFloat waveformMaxWidthDuration;
@property (readonly, nonatomic) CGFloat waveformMinDbPowerLevel;
@property (readonly, nonatomic) CGFloat waveformMinLinearPowerLevel;
@property (readonly, nonatomic) NSUInteger waveformMinPowerLevelsCount;
@property (readonly, nonatomic) NSUInteger waveformPowerLevelWidth;
@property (readonly, nonatomic) NSUInteger waveformPowerLevelWidthIncrement;
@property (readonly, nonatomic) UIFont *welcomeViewCancelButtonFont;
@property (readonly, nonatomic) UIFont *welcomeViewConfirmButtonFont;
@property (readonly, nonatomic) CGFloat welcomeViewContentViewLeadingAnchorLayoutConstraintConstant;
@property (readonly, nonatomic) CGFloat welcomeViewContentViewTopAnchorLayoutConstraintConstant;
@property (readonly, nonatomic) UIFont *welcomeViewTitleLabelFont;
@property (readonly, nonatomic) UIFont *whatsNewFeatureViewDescriptionLabelFont;
@property (readonly, nonatomic) UIFont *whatsNewFeatureViewTitleLabelFont;
@property (readonly, nonatomic) UIImage *whatsNewViewApplePayImage;
@property (readonly, nonatomic) UIFont *whatsNewViewBulletPointSymbolLabelFont;
@property (readonly, nonatomic) CGFloat whatsNewViewBulletPointSymbolLeadingAnchorLayoutConstraintConstant;
@property (readonly, nonatomic) UIFont *whatsNewViewBulletPointTextLabelFont;
@property (readonly, nonatomic) CGFloat whatsNewViewBulletPointTextTrailingAnchorLayoutConstraintConstant;
@property (readonly, nonatomic) UIFont *whatsNewViewDescriptionLabelFont;
@property (readonly, nonatomic) UIImage *whiteA1AckImage;
@property (readonly, nonatomic) UIImage *whiteA2AckImage;
@property (readonly, nonatomic) UIImage *whiteExclamationLeftAckImage;
@property (readonly, nonatomic) UIImage *whiteExclamationRightAckImage;
@property (readonly, nonatomic) UIImage *whiteH1AckImage;
@property (readonly, nonatomic) UIImage *whiteH2AckImage;
@property (readonly, nonatomic) UIImage *whiteHaAckImage;
@property (readonly, nonatomic) UIImage *whiteQuestionMarkDotAckImage;
@property (readonly, nonatomic) UIImage *whiteQuestionMarkGlyphAckImage;
@property (readonly, nonatomic) UIImage *whiteThumbsDownAckImage;
@property (readonly, nonatomic) UIImage *whiteThumbsUpAckImage;
@property (readonly, nonatomic) Class windowClass;
@property (readonly, nonatomic) CGFloat xsTranscriptSpace;


+(id)fontWithStyle:(id)arg0 adjustedForMaxSizeCategory:(id)arg1 ;
+(id)orderedContentSizeCategories;
+(id)sharedBehaviors;
+(void)testOverrideClearSharedBehaviors;
-(BOOL)_isVerticallyCompact;
-(BOOL)contactPhotosEnabled;
-(BOOL)shouldShowAvatarForWidth:(CGFloat)arg0 ;
-(BOOL)suppressPinActivityForState:(NSUInteger)arg0 ;
-(BOOL)useSelectedAppearanceForConversationCellState:(NSUInteger)arg0 traitCollection:(id)arg1 ;
-(CGFloat)_transcriptAnimationScaleFactor;
-(CGFloat)audioBalloonTimeWidthForDuration:(CGFloat)arg0 ;
-(CGFloat)balloonBalloonTranscriptSpace:(unsigned char)arg0 ;
-(CGFloat)balloonMaskTailHeight;
-(CGFloat)balloonMaxWidthForTranscriptWidth:(CGFloat)arg0 marginInsets:(struct UIEdgeInsets )arg1 shouldShowPluginButtons:(BOOL)arg2 shouldShowCharacterCount:(BOOL)arg3 shouldCoverSendButton:(BOOL)arg4 ;
-(CGFloat)composeBalloonMaxWidthForEntryContentViewWidth:(CGFloat)arg0 ;
-(CGFloat)conversationListSenderBodyLeading;
-(CGFloat)disabledNavigationButtonStrokeWidth;
-(CGFloat)disabledNavigationButtonWidth;
-(CGFloat)locationShareBalloonAdditionalVertPadding;
-(CGFloat)locationShareBalloonLabelMaxHeightForOfferState:(NSInteger)arg0 ;
-(CGFloat)navBarButtonSymbolImageFontSize;
-(CGFloat)navigationBarCollapsedHeightValue;
-(CGFloat)navigationBarExpandedHeightValue;
-(CGFloat)photoPickerMaxPhotoWidthForAlertWidth:(CGFloat)arg0 ;
-(CGFloat)photoPickerMaxPopoverPhotoHeight;
-(CGFloat)photoPickerMaxZoomedPhotoHeightForAlertWidth:(CGFloat)arg0 ;
-(CGFloat)previewBalloonMaxWidthForBalloonMaxWidth:(CGFloat)arg0 ;
-(CGFloat)primaryColumnWidthForInterfaceOrientation:(NSInteger)arg0 ;
-(CGFloat)replyBalloonMinHeight;
-(CGFloat)searchMessageCellHeightForDisplayScale:(CGFloat)arg0 ;
-(CGFloat)toFieldPreferredHeight;
-(CGFloat)transcriptDrawerMaxContentOffsetXForMarginInsets:(struct UIEdgeInsets )arg0 ;
-(CGFloat)transcriptDrawerOverlapForMarginInsets:(struct UIEdgeInsets )arg0 ;
-(CGFloat)transcriptDrawerSpace;
-(CGFloat)transcriptDrawerWidthForMarginInsets:(struct UIEdgeInsets )arg0 ;
-(CGFloat)transcriptWaveformWidthForDuration:(CGFloat)arg0 ;
-(NSUInteger)minBalloonsForTranscriptHeight;
-(id)_breadcrumbTranscriptTextAttributes;
-(id)aggregateAcknowledgmentBottomMiddleName:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentBottomTopName:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentMiddleName:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentStackBackgroundName2:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentStackBackgroundName3:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentStackName2:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentStackName3:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentTopBackgroundName:(BOOL)arg0 ;
-(id)aggregateAcknowledgmentTopName:(BOOL)arg0 ;
-(id)breadcrumbTranscriptTextAttributes;
-(id)chevronImageForColorType:(char)arg0 ;
-(id)disabledNavigationButtonStrokeColor;
-(id)filteredAppMenuItemsForOrderedCollection:(id)arg0 ;
-(id)fullscreenPickerActionLayoutAxisPrioritiesForWidth:(CGFloat)arg0 ;
-(id)imageNameForBalloonDescriptor:(struct CKBalloonDescriptor_t )arg0 ;
-(id)imageNameForBalloonDescriptorWithFilledStyle:(struct CKBalloonDescriptor_t )arg0 ;
-(id)imageNameForBalloonDescriptorWithStrokedStyle:(struct CKBalloonDescriptor_t )arg0 ;
-(id)imageNamed:(id)arg0 pointSize:(CGFloat)arg1 insets:(struct UIEdgeInsets )arg2 ;
-(id)imageNamed:(id)arg0 pointSize:(CGFloat)arg1 insets:(struct UIEdgeInsets )arg2 color:(id)arg3 ;
-(id)impactBalloonName;
-(id)impactSkinnyBalloonName;
-(id)largeMessageAcknowledgmentPollingImageNameForAcknowledgmentType:(NSInteger)arg0 ;
-(id)mentionTranscriptFontFromOrignalFont:(id)arg0 ;
-(id)messageAcknowledgmentImageNameForType:(NSInteger)arg0 ;
-(id)messageAcknowledgmentPollingImageNameForAcknowledgmentType:(NSInteger)arg0 ;
-(id)multilineBalloonName;
-(id)multilineStrokedBalloonName;
-(id)multilineStrokedTaillessBalloonName;
-(id)multilineTaillessBalloonName;
-(id)multiwayGrayChevronImage;
-(id)navBarExpanseImageName;
-(id)navBarGlyphFont;
-(id)replyBalloonName;
-(id)replyDeleteBalloonName;
-(id)replyMultilineBalloonName;
-(id)replySkinnyBalloonName;
-(id)replyStrokedBalloonName;
-(id)replyStrokedMultilineBalloonName;
-(id)replyStrokedSkinnyBalloonName;
-(id)roundBalloonName;
-(id)systemGrayChevronImage;
-(id)touchBarImageNameForAcknowledgmentType:(NSInteger)arg0 ;
-(id)transcriptButtonTextFont;
-(id)transcriptDrawerFont;
-(id)transcriptSenderFont;
-(id)whiteChevronImage;
-(struct CGRect )extensionIconBadgeRectForOrientation:(char)arg0 ;
-(struct CGSize )avatarCollapsedSize;
-(struct CGSize )balloonMaskSize;
-(struct CGSize )balloonMaskSizeWithBalloonDescriptor:(struct CKBalloonDescriptor_t )arg0 ;
-(struct CGSize )balloonMaskSizeWithTailShape:(char)arg0 isMultiline:(BOOL)arg1 ;
-(struct CGSize )balloonMaskTailSizeForTailShape:(char)arg0 ;
-(struct CGSize )deletedReplyBalloonMaskSizeWithTailShape:(char)arg0 ;
-(struct CGSize )locationOfferMapThumbnailFillSizeForWidth:(CGFloat)arg0 ;
-(struct CGSize )locationShareBalloonSizeForWidth:(CGFloat)arg0 offerState:(NSInteger)arg1 ;
-(struct CGSize )mapThumbnailFillSizeForWidth:(CGFloat)arg0 ;
-(struct CGSize )multilineBalloonMaskSize;
-(struct CGSize )previewBalloonSizeThatFits:(struct CGSize )arg0 ;
-(struct CGSize )replyBalloonMaskSize;
-(struct CGSize )replyBalloonMaskSizeWithTailShape:(char)arg0 isMultiline:(BOOL)arg1 ;
-(struct CGSize )replyDeleteBalloonMaskSize;
-(struct CGSize )replyMultilineBalloonMaskSize;
-(struct CGSize )replySkinnyBalloonMaskSize;
-(struct CGSize )roundBalloonMaskSizeWithTailShape:(char)arg0 ;
-(struct CGSize )skinnyBalloonMaskSize;
-(struct CGSize )skinnyBalloonMaskSizeWithTailShape:(char)arg0 ;
-(struct CGSize )skinnyReplyBalloonMaskSizeWithTailShape:(char)arg0 ;
-(struct CGSize )stickerSizeScaledWithInitialSize:(struct CGSize )arg0 imageScale:(CGFloat)arg1 userScale:(CGFloat)arg2 rectifiedScreenScale:(CGFloat)arg3 maxWidth:(CGFloat)arg4 ;
-(struct CGSize )taillessBalloonMaskSize;
-(struct CGSize )taillessMultilineBalloonMaskSize;
-(struct CGSize )taillessSkinnyBalloonMaskSize;
-(struct CGSize )thumbnailFillSizeForWidth:(CGFloat)arg0 imageSize:(struct CGSize )arg1 ;
-(struct UIEdgeInsets )attachmentBalloonAlignmentRectInsets;
-(struct UIEdgeInsets )attachmentBalloonAlignmentRectInsetsWithTailShape:(char)arg0 ;
-(struct UIEdgeInsets )balloonMaskAlignmentRectInsets;
-(struct UIEdgeInsets )balloonMaskAlignmentRectInsetsWithTailShape:(char)arg0 ;
-(struct UIEdgeInsets )balloonMaskFrameInsets;
-(struct UIEdgeInsets )balloonMaskFrameInsetsWithBalloonShape:(char)arg0 ;
-(struct UIEdgeInsets )bigEmojiBalloonMaskAlignmentRectInsets;
-(struct UIEdgeInsets )extensionBalloonContentInsetsForOrientation:(char)arg0 ;
-(struct UIEdgeInsets )pluginBalloonInsetsForMessageFromMe:(BOOL)arg0 ;
-(struct UIEdgeInsets )taillessAttachmentBalloonAlignmentRectInsets;
-(struct UIEdgeInsets )taillessBalloonMaskAlignmentRectInsets;
-(struct UIEdgeInsets )thumbnailContentAlignmentInsetsForOrientation:(char)arg0 ;
-(void)invalidateTranscriptDrawerWidth;
-(void)prewarmAcknowledgementsImage;
-(void)setupNavBarAppearanceWithNavigationController:(id)arg0 ;
-(void)setupNavBarAppearanceWithNavigationController:(id)arg0 withBackgroundColor:(id)arg1 ;


@end


#endif